### ISSUE TITLE
ndk-depends at NDK root is a Windows batch file but has .EXE file extension

### ISSUE THREAD

**Issue by jubajube** [android-ndk/ndk#100]
I notice that the ndk-depends.exe file in the NDK root changed from a real executable to a Windows bat file which invokes the real ndk-depends.exe which was moved to prebuilt/windows-x86_64/bin/ndk-depends.exe (for 64-bit NDK).  However, since the file extension wasn't changed, when I try to run it from the Windows command prompt, Windows tries to load it as an executable, and fails.

![ndk-depends-wrong-file-extension](https://cloud.githubusercontent.com/assets/6889558/15377960/68c67a06-1d14-11e6-8f49-92dd305b172f.png)

Renaming the file to ndk-depends.cmd fixes the problem.

**Comment by DanAlbert** [comment]
Testing a fix now.

**Comment by DanAlbert** [comment]
Up for review: https://android-review.googlesource.com/231001
