### ISSUE TITLE
[question] r20 armeabi-v7a crashes in je_malloc/je_free

### ISSUE THREAD

**Issue by andreya108** [android-ndk/ndk#1001]
After switching from ndk r19b to r20, all tests on every armeabi-v7a devices became red.
Quick analysis shows that in every case it caused by crash in libc inside je_malloc or je_free like:
```
********** Crash dump: ********** 
Build fingerprint: 'samsung/kltexx/klte:6.0.1/MMB29M/G900FXXS1CQD1:user/release-keys' 
#00 0x000491e8 /system/lib/libc.so (arena_run_reg_alloc+87) 
#01 0x0004afaf /system/lib/libc.so (je_arena_tcache_fill_small+94) 
#02 0x0005c2eb /system/lib/libc.so (je_tcache_alloc_small_hard+18) 
#03 0x00056ddd /system/lib/libc.so (je_malloc+1112) 
#04 0x000487ed /system/lib/libc++.so (_Znwj+16) 

********** Crash dump: ********** 
Build fingerprint: 'samsung/kltexx/klte:6.0.1/MMB29M/G900FXXS1CQD1:user/release-keys' 
#00 0x000491e8 /system/lib/libc.so (arena_run_reg_alloc+87) 
#01 0x0004afaf /system/lib/libc.so (je_arena_tcache_fill_small+94) 
#02 0x0005c2eb /system/lib/libc.so (je_tcache_alloc_small_hard+18) 
#03 0x00056ddd /system/lib/libc.so (je_malloc+1112) 
#04 0x0005f28d /data/app/com.vipnet.client-1/lib/arm/libc++_shared.so (_Znwj+24)

********** Crash dump: ********** 
Build fingerprint: 'samsung/gta2sltedx/gta2slte:8.1.0/M1AJQ/T385DXU2BSA2:user/release-keys' 
#00 0x000584b6 /system/lib/libc.so (je_arena_malloc_hard+201) 
#01 0x0006754f /system/lib/libc.so (je_malloc+114) 
#02 0x0005f28d /data/app/com.vipnet.client-MA96gRgyV7fZyy0eCk0_yA==/lib/arm/libc++_shared.so (operator new(unsigned int)+24)

********** Crash dump: ********** 
Build fingerprint: 'samsung/gta2sltedx/gta2slte:8.1.0/M1AJQ/T385DXU2BSA2:user/release-keys' 
Abort message: 'Invalid address 0x95b7cb40 passed to free: value not allocated' 
#00 0x0001a73a /system/lib/libc.so (abort+63) 
#01 0x0006b1c5 /system/lib/libc.so (ifree+600) #02 0x0006b3c5 /system/lib/libc.so (je_free+68)
```
Everything is ok on arm64-v8a.

Is anybody affected with similar issue?

**Comment by enh** [comment]
no, we haven't seen this internally, nor have we had other reports of this yet.

**Comment by andreya108** [comment]
I've done some investigations, and can say that it is really due to ndk r20.

We have a private c++ library with unit tests.
Compiled with ndk r19b: tests pass;
Compiled with ndk r19c: tests pass;
Compiled with ndk r20-beta1: tests fail;
Compiled with ndk r20: tests fail;

There are some debug prints in the lib using __PRETTY_FUNCTION__ inside, and looks like severe memory corruption occurs: at first it prints functions names successfully, but after some time it prints garbage instead of function names like:
```\���`�: Self check failed, moving to corrupted state
```
What can I do further to bring more clarity to the issue?

ps: compiled under linux, options: armeabi-v7a, android api 23, libc++_shared, standalone toolchain used (python $NDK/build/tools/make_standalone_toolchain.py --arch arm --api 23 --install-dir toolchain).

**Comment by DanAlbert** [comment]
You can try [ASan](https://github.com/google/sanitizers/wiki/AddressSanitizerOnAndroid) or [malloc debug](https://android.googlesource.com/platform/bionic/+/master/libc/malloc_debug/README.md#for-app-developers). Other than that, we'd need a test case to help.

If you suspect that it might be a compiler bug (cases like these it's more often undefined behavior than a compiler "bug", so ubsan might also help: `-fsanitize=undefined`), you can also try the [canary NDK](https://ci.android.com/builds/branches/aosp-master-ndk/grid?). It's on a newer Clang than r20.

**Comment by andreya108** [comment]
Thanks for support!

I've discovered that our code in some places assumes that data alignment for 32bit cpu is also 32 bit, but ubsan revealed that it is not true in ndk r20+ (it is 8 bytes now).  
So I have a clue to fix the issue.

Meanwhile, why alignment was changed to 8 bytes for armeabi-v7a?

**Comment by DanAlbert** [comment]
Are you sure that changed? I'm not sure what the alignment for arm32 is. It's possible that it has always been 8 (it does depend on the specific data type; not sure which you're referring too) and the undefined behavior is only symptomatic in r20.

@srhines

**Comment by stephenhines** [comment]
What has an alignment of 8 bytes? All allocations? Is this targeting a specific API level where this might have changed (@cferris1000)? We're going to need a bit more information. Can you let us know which data types you think now have a different alignment (and perhaps use `alignof()` to print out those values under both configurations)?

**Comment by cferris1000** [comment]
The alignment of allocations depends on the android platform, the size of the allocation, and the bitness of the compiled code (32 bit or 64 bit).

However, on all known versions of android and bitness, the native memory allocator will always return an allocation aligned to at least 8 bytes (32 bits). Newer versions of the allocator cannot even go below this unless you've found some strange bug.

Looking at your crashes, it looks as though you are freeing an already freed pointer, or freeing an unknown pointer (possibly deleting a bad pointer). I would guess that the new ndk uses a slightly different version of C++ so it might have changed something exposing a previous bug. Another possibility is that the previous code did something undefined and the new compiler is going down a different path, exposing a previous bug.

As Stephen says, we would really need to see the code to determine what's going on.

**Comment by andreya108** [comment]
Looks like there is a bunch of issues here, but for now I can share only the first one discovered.
So here is the problem found by UBSAN:

There is a data structure like:
```
typedef struct {
  union {
    A_t a;
    B_t b;
    C_t c;
    size_t align;
  };
} ABC_t;
```
*_t - types of different length.
Ubsan complained, that access to some members of ABC_t was not aligned to 8 bytes (concrete addresses ended with 0x4 and 0xC).

This has been fixed by changing type of 'align' field from size_t to uint64_t.

p.s.: ABC_t is being allocated statically and in heap (malloc). Not sure about stack.

At the moment, we're still experiencing weird things like heap-usage-after-free (as reported by ASAN) and libc crashing with diagnostics: freeing 'not allocated' memory. Research continues.

**Comment by andreya108** [comment]
We're targeting api level 23.

**Comment by DanAlbert** [comment]
> This has been fixed by changing type of 'align' field from size_t to uint64_t.

You can be explicit rather than trying to trick the compiler into doing the right thing: https://en.cppreference.com/w/cpp/language/alignas

I'm closing this bug since there doesn't appear to be a bug so far, but that's just for tracking reasons. Feel free to continue using it for questions if you find more :)

**Comment by dugsmith** [comment]
@andreya108 : we're seeing a lot of exceptions with `je_free` after upgrading to r20b. Have you tested `r21d` to see if it's fixed there?

**Comment by andreya108** [comment]
We're experiencing no jemallc crashes on 21d, though we skipped r20
entirely since it has math bug affected our code.

ср, 14 окт. 2020 г., 02:27 Doug Smith <notifications@github.com>:

**Comment by dugsmith** [comment]
> We're experiencing no jemallc crashes on 21d, though we skipped r20 entirely since it has math bug affected our code. 

Interesting, thank you! What math bug are you referring to? Do you have a link or reference?

**Comment by andreya108** [comment]
This one:
https://github.com/android/ndk/issues/1010

чт, 15 окт. 2020 г., 16:40 Doug Smith <notifications@github.com>:
