### ISSUE TITLE
[BUG] systool in ndk-build repeated definition when compiled against GDB

### ISSUE THREAD

**Issue by jeremyng123** [android-ndk/ndk#1008]
#### Description
GDB is not included in Android OS.

As such, i used [android-ndk-r20](https://dl.google.com/android/repository/android-ndk-r20-linux-x86_64.zip) standalone toolchain to compile [gdb-8.3](https://ftp.gnu.org/gnu/gdb/).

Replicating the steps to retrieve the bug log:

1. navigate to GDB Built directory `cd ~/gdb-8.3`
2. include toolchain compiling tools to path `PATH=$PATH:/home/jem/Documents/toolchain/bin`
3. run autoconf file with the following parameters: ./configure --target=aarch64-linux-android --host=aarch64-linux-android  --build=x86_64-pc-linux-gnu
4. run make from toolchain `/home/jem/Documents/toolchain/bin/make -j8`. Purely running make will use host's make, which will give us unnecessary errors.
5. During the built, this error will appear:
```bash
linux-low.c:119:3: error: typedef redefinition with different types ('struct Elf32_auxv_t' vs 'struct Elf32_auxv_t')
 } Elf32_auxv_t;
 ^
 /home/jem/Documents/toolchain/bin/../sysroot/usr/include/elf.h:52:3: note: previous definition is here
 } Elf32_auxv_t;
 ^
 linux-low.c:134:3: error: typedef redefinition with different types ('struct Elf64_auxv_t' vs 'struct Elf64_auxv_t')
 } Elf64_auxv_t;
 ^
 /home/jem/Documents/toolchain/bin/../sysroot/usr/include/elf.h:59:3: note: previous definition is here
 } Elf64_auxv_t;
 ^
 2 errors generated.
```

I solved the error by adding the following lines to avoid 're-defining definitions'. 

```bash
$ diff -u /home/jem/Documents/toolchain/bin/../sysroot/usr/include/elf.h.old /home/jem/Documents/toolchain/bin/../sysroot/usr/include/elf.h
--- /home/jem/Documents/toolchain/bin/../sysroot/usr/include/elf.h.old	2019-05-22 12:49:28.000000000 +0800
+++ /home/jem/Documents/toolchain/bin/../sysroot/usr/include/elf.h	2019-06-14 13:00:49.707728918 +0800
@@ -44,19 +44,25 @@
typedef __u64 Elf32_Xword;
typedef __s64 Elf32_Sxword;

+#ifndef HAVE_ELF32_AUXV_T
+#define HAVE_ELF32_AUXV_T
typedef struct {
__u32 a_type;
union {
    __u32 a_val;
} a_un;
} Elf32_auxv_t;
+#endif

+#ifndef HAVE_ELF64_AUXV_T
+#define HAVE_ELF64_AUXV_T
typedef struct {
__u64 a_type;
union {
    __u64 a_val;
} a_un;
} Elf64_auxv_t;
+#endif

/* http://www.sco.com/developers/gabi/latest/ch4.sheader.html */
typedef struct {
```

Please let me know if this solution is viable and preferred. Else, please advise a better solution! Thanks!

#### Environment Details

**Host Device**

```bash
$ uname -a
Linux nzyj 4.18.0-21-generic #22~18.04.1-Ubuntu SMP Thu May 16 15:07:19 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

**Target Device**

```bash
hikey960:/ # uname -a
Linux localhost 4.9.176-12953-g7c09ed7b46a4-dirty #13 SMP PREEMPT Tue Jun 4 10:16:26 +08 2019 aarch64
```

**NDK Version:**

```bash
$ cat /src/android-ndk-r20/source.properties 
Pkg.Desc = Android NDK
Pkg.Revision = 20.0.5594570
```
* ABI: arm64-v8a (AARCH64)
* NDK API level: r20
* Device API level: Android R (API 21)

**Comment by enh** [comment]
no, the fix is for gdb to stop redefining a symbol that exists.
