### ISSUE TITLE
Clang can't find stddef.h

### ISSUE THREAD

**Issue by Tylerflick** [android-ndk/ndk#101]
After updating to NDK r12, Clang can no longer find stddef.h using the [experimental gradle plugin.](http://tools.android.com/tech-docs/new-build-system/gradle-experimental)
I've tried versions 0.7.0-alpha4 through 0.8.0-alpha1 of the plugin with no success.

The build system is looking in the following directories for the header, even though some of them don't exist.
_I swapped out my install path with ANDROID_HOME_

`clang -cc1 version 3.8.256229 based upon LLVM 3.8.256229 default target x86_64-unknown-linux`
`ignoring nonexistent directory "ANDROID_HOME/sdk/ndk-bundle/platforms/android-23/arch-arm64/usr/local/include"`
`ignoring nonexistent directory "ANDROID_HOME/sdk/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/bin/../lib64/clang/3.8.256229/include"`
`ignoring nonexistent directory "ANDROID_HOME/sdk/ndk-bundle/platforms/android-23/arch-arm64/include"`
 
I thought that [this link](http://clang.llvm.org/docs/FAQ.html#id3) may be of some relevance to the issue.
Were there included header files that may have been misplaced to an incorrect directory?

I ended up reverting to NDK r10e as a temporary fix.

**Comment by DanAlbert** [comment]
When did you update? There was a bad version of r12 beta 2 that somehow escaped staging and made it to the canary channel early, but this should be fixed in the currently hosted downloads.

Based on the contents of your bug, it looks like you downloaded via Android Studio? Which version are you on? I think I've found a bug in pre-2.2 where it has some issues deciding which build to serve.

> I ended up reverting to NDK r10e as a temporary fix.

r11c would be a better choice. The core bug that is causing your issue wasn't exposed by that build.

**Comment by Tylerflick** [comment]
> When did you update?

I updated today when I was setting up a new build machine.

> Based on the contents of your bug, it looks like you downloaded via Android Studio?

Yes. I had set the build machine up using the Canary channel of Android Studio as that what I was doing my original development with.

> Which version are you on? 

I was on the Canary channel and have since switched back to the Stable channel.

>  r11c would be a better choice. The core bug that is causing your issue wasn't exposed by that build.

I'll give that a shot tomorrow morning and post the results.

Thanks for the quick reply.

**Comment by DanAlbert** [comment]
> I updated today when I was setting up a new build machine.

When today? It's been a long and exciting one over here :) If it was before https://groups.google.com/forum/#!topic/android-ndk-announce/FasV9NqlC6E, then you probably have a bugged version. Should be sufficient to uninstall and reinstall the NDK via Android Studio to fix it if that's the case.

**Comment by Tylerflick** [comment]
> When today? It's been a long and exciting one over here :) 
I guess I forgot about IO.

Okay I'll give the updated version a shot tomorrow morning then.

**Comment by Tylerflick** [comment]
Just tested the linked download and everything built as expected with passing tests!
*I still haven't tested version that is pulled through the Android Studio SDK manager.

Thanks for your help with the issue.
