### ISSUE TITLE
[BUG] ndk stl std::thread crash

### ISSUE THREAD

**Issue by doyee** [android-ndk/ndk#1017]
NDK Version: all NDK with APP_STL :=c++_static , tested from NDK 13,
Build system: ndk-build
Host OS: Mac OS
ABI:arm64-v8a
NDK API level: APP_PLATFORM := android-24
Device API level: not set
run this demo on android device with current O or P version,
if set APP_STL := c++_static, crash occurred when outside loop i = 128,
if set APP_STL := gnustl_static, there is no crash.
but after NDK r18, there is only c++_static. I have to use NDK R17 with gnustl_static

test demo and so, the flow is：
`demo:
main()
{
for(i=0; i<1000; i++)
{
dlopen so
for(int j=0; j<1; j++)
{
call process_func() in so
}
dlclose so
}
}

so：
process_func()
{
call std::thread and join
}`

please use this link for debug:
git@github.com:doyee/ndk-bug-thread-crash.git

JNITest.cpp dlopen(ThreadTest.so)
ThreadTest.so will use std::thread

**Comment by DanAlbert** [comment]
> tested from NDK 13

We've fixed tons of bugs since then, especially around issues like this. Try with r20.

**Comment by DanAlbert** [comment]
(or do I misunderstand and you mean this bug is present in every version *since* r13?)

**Comment by DanAlbert** [comment]
> dlclose so

Actually, that's probably your problem. Don't call `dlcose` and the bug will go away. See for the gory details. https://github.com/android-ndk/ndk/issues/360

(if that's not the case, lmk and I'll reopen)

**Comment by DanAlbert** [comment]
Another bug that might be the problem (actually seems more likely): https://github.com/android-ndk/ndk/issues/789

**Comment by doyee** [comment]
@DanAlbert I ALREADY use the latest ndk, still has this problem, you can check my code in JNITest.cpp,  if use local DllHelper obj for dlopen dlclose, this crash happen.  if use global DllHelper no crash

**Comment by DanAlbert** [comment]
Yeah, I hadn't fully understood in my first post, but what about the others? I think my most recent post is probably the source of your problems.
