### ISSUE TITLE
[BUG] dynamic_pointer_cast return NULL

### ISSUE THREAD

**Issue by AnaBit** [android-ndk/ndk#1023]
#### Description

I have a problem when I ported the vsomeip protocol stack. When std::dynamic_pointer_cast is used to convert a multi-inherited class, std::dynamic_pointer_cast returns a value of NULL and no exception is thrown. An instance of this multi-inherited class is generated by a function of dysml. I tried to solve this problem using the [-Wl, -E] compilation parameter, but this parameter did not take effect.

Here's a test case:
https://github.com/AnaBit/ndk-dynamic_pointer_cast

Use case runs with this parameter： ./dlopen_test  ./libddlib.so
#### Environment Details
* NDK Version: 20.0.5594570
* Build system: CMake
* Host OS: Ubuntu19.04
* ABI:arm64-v8a
* NDK API level:
* Device API level:

**Comment by DanAlbert** [comment]
Your class doesn't have a key function, so it can't be used for RTTI when loaded dynamically. See https://android.googlesource.com/platform/ndk/+/master/docs/user/common_problems.md, or search here for `dynamic_cast`. There are a handful of other bugs that discuss this.
