### ISSUE TITLE
[BUG] clang in r20 breaks blocks with Objective C

### ISSUE THREAD

**Issue by triplef** [android-ndk/ndk#1025]
#### Description

The updated clang revision in NDK r20 breaks blocks with Objective C code due to the use of @-characters in block descriptors' symbol names.

This was caused by [r340041](https://github.com/llvm-mirror/clang/commit/0e6cfa4e8a86bd9f35d69f44aae209918475e44d) (included in r20) and fixed in [r350157](https://github.com/llvm-mirror/clang/commit/30abdb44ab9b2503694a58bb409e8a8ab898cc62) (not included in r20).

The relevant discussion can be found here:
https://reviews.llvm.org/D50783#1220604

#### Steps to reproduce

The issue can e.g. be reproduced by building the [GNUstep Android toolchain](https://github.com/gnustep/tools-android) with NDK r20, which will cause the following error e.g. when building for arm64-v8a:

```
 Linking library libgnustep-base ...
aarch64-linux-android/bin/ld: ./obj/libgnustep-base.so.1.26.0: version node not found for symbol __block_descriptor_40_e8_32r_e15_v32@?0@8Q16^C24l
aarch64-linux-android/bin/ld: failed to set dynamic section sizes: Bad value
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
```

Building the toolchain with NDK r19c works fine.

#### Environment Details

* NDK Version: 20.0.5594570

**Comment by DanAlbert** [comment]
We don't support objective C.
