### ISSUE TITLE
GCC inlining failed

### ISSUE THREAD

**Issue by chaoren** [android-ndk/ndk#103]
NDK: 12.0.2867246-beta2

This happens only with gcc, but not clang, for all architectures except arm. Since we're deprecating gcc, there's no chance of this getting fixed, is there?

```base
$ cat test.c
int test(int) __attribute__ ((always_inline));

int test(int i) {
        return i;
}

int main() {
        test(0);
}
$ ~/Android/sdk/ndk-bundle/toolchains/x86-4.9/prebuilt/linux-x86_64/bin/i686-linux-android-gcc test.c
test.c:3:5: warning: always_inline function might not be inlinable [-Wattributes]
 int test(int i) {
     ^
test.c: In function 'main':
test.c:3:5: error: inlining failed in call to always_inline 'test': function body can be overwritten at link time
test.c:8:2: error: called from here
  test(0);
  ^
```

**Comment by DanAlbert** [comment]
Declaration needs to be: 

```c
inline int test(int) __attribute__ ((always_inline));
```

The problem is that if it isn't marked `inline` (which apparently isn't implied by `always_inline`), then the location of the function is supposed to be overridable when the module is loaded (such as via `LD_PRELOAD`).
