### ISSUE TITLE
[BUG] NDK-r20 cause SIGBUS with placement new.

### ISSUE THREAD

**Issue by disigma** [android-ndk/ndk#1035]
#### Description

I'm using the placement new in my code. After upgrading NDK, my program fails with a weird error.
```
Signal SIGBUS: illegal alignment
```
The NDK version I used before is r14b, which works properly.

I tried a simple test code and got the same error.

```
#include <unordered_map>

int main() {
    char byte;
    char memory[sizeof(std::unordered_map<int, int>)];
    new (memory) std::unordered_map<int, int>;
    return 0;
}
```
#### Environment Details

* NDK Version: 20.0.5594570
* Build system: Standalone toolchain
* Host OS: Linux (Ubuntu 18.04)
* ABI: armeabi-v7a
* NDK API level: 17
* Device API level: 21

**Comment by enh** [comment]
seems WAI, no, and this was just accidentally working before? the `byte` breaks the alignment of `memory`, so you need to explicitly ensure that that has sufficient alignment, perhaps with https://en.cppreference.com/w/cpp/language/alignas if this is representative of your actual code?
