### ISSUE TITLE
inline asm issue

### ISSUE THREAD

**Issue by salcideon** [android-ndk/ndk#1036]
using the toolchain:

```
static inline float32x4_t
test(float32x4_t _acc_, float32x4_t _op1_, float32x4_t _op2_, int _lane_)
{
    __asm__ __volatile__("fmla %0.4s, %1.4s, %2.s[%3]" : "+w"(_acc_) : "w"(_op1_), "w"(_op2_), "I"(_lane_));
    return _acc_;
}
```

generates `fmla q21.4s, q19.4s, q27.s[#1]` instead of `fmla q21.4s, q19.4s, q27.s[1]` as it should. 

Then compilation fails with error: unexpected token in argument list

**Comment by pirama-arumuga-nainar** [comment]
Below is a simpler repro.  The original fails because _lane_ is a variable instead of a constant (presumably it was a constant once inlined).

```#include <arm_neon.h>

void test() {
  __asm__ ("fmla v2.4s, v0.4s, v1.s[%0]" :: "I"(0x1));
}
```

Fix under review: https://reviews.llvm.org/D65550

**Comment by pirama-arumuga-nainar** [comment]
From the LLVM review linked above, another option is to use the ['c' modifier](https://gcc.gnu.org/onlinedocs/gcc/Extended-Asm.html#InputOperands) for the lane specifier, which is supported by gcc as well.  So if we change the above repro to 
```
void test() {
  __asm__ ("fmla v2.4s, v0.4s, v1.s[%c0]" :: "I"(0x1));
}
```
it [works](https://godbolt.org/z/TMT4pQ).

**Comment by pirama-arumuga-nainar** [comment]
The upstream change was merged and will be part of r21.
