### ISSUE TITLE
[BUG] NDK20 build aarch32 fp16 cause error in llvm backend.

### ISSUE THREAD

**Issue by sethbrin** [android-ndk/ndk#1039]
#### Description
I'm using ndk20, compile following code cause llvm error.
```
#include <arm_neon.h>

int main() {
    __fp16 res[8];
    float16x4_t val = vdup_n_f16(1.0);
    float16x4_t zero = vdup_n_f16(0);
    val = vmax_f16(val, zero);
    vst1_s16((int16_t*)res, (int16x4_t)val);

    return 0;
}
```
compile commands:
```
$ android-ndk-r20/toolchains/llvm/prebuilt/linux-x86_64/bin/armv7a-linux-androideabi16-clang++ ./main.cpp -march=armv8.2-a+fp16 -mfpu=neon-fp16 -mfloat-abi=softfp -c

fatal error: error in backend: Do not know how to split the result of this operator!

clang++: error: clang frontend command failed with exit code 70 (use -v to see invocation)
Android (5220042 based on r346389c) clang version 8.0.7 (https://android.googlesource.com/toolchain/clang b55f2d4ebfd35bf643d27dbca1bb228957008617) (https://android.googlesource.com/toolchain/llvm 3c393fe7a7e13b0fba4ac75a01aa683d7a5b11cd) (based on LLVM 8.0.7svn)
Target: armv7a-unknown-linux-android16
Thread model: posix
InstalledDir: /home/zengping/work/toolchain/android-ndk/android-ndk-r20/toolchains/llvm/prebuilt/linux-x86_64/bin
clang++: note: diagnostic msg: PLEASE submit a bug report to https://github.com/android-ndk/ndk/issues and include the crash backtrace, preprocessed source, and associated run script.
clang++: note: diagnostic msg:
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang++: note: diagnostic msg: /tmp/main-2dddb1.cpp
clang++: note: diagnostic msg: /tmp/main-2dddb1.sh
clang++: note: diagnostic msg:

********************
```

but when i compile in aarch64, it's ok.

```
$ android-ndk-r20/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android21-clang++ ./main.cpp -march=armv8.2-a+fp16 -mfpu=neon -mfloat-abi=softfp
```
#### Environment Details

* NDK Version: NDK20
* Build system: custom
* Host OS: Linux tui 4.9.0-8-amd64 #1 SMP Debian 4.9.130-2 (2018-10-27) x86_64 GNU/Linux
* ABI: armeabi-v7a
* NDK API level: 16
* Device API level: 16

**Comment by DanAlbert** [comment]
The crash needs to be fixed regardless and I doubt this will work, but there definitely aren't any Jelly Bean devices with ARM 8.2 chips. I'm not sure when that was introduced, but does the problem go away if you target 29?

**Comment by pirama-arumuga-nainar** [comment]
This repros in ToT:

```
SplitVectorResult #0: t61: v4f16 = llvm.arm.neon.vmaxs TargetConstant:i32<1180>, t56, t58
fatal error: error in backend: Do not know how to split the result of this operator!
```

I don't think the API level should matter here.  I'll investigate.

**Comment by pirama-arumuga-nainar** [comment]
`-march=armv8.2-a+fp16 -mfpu=neon` doesn't get the full armv8 FPU needed for proper lowering of the `llvm.arm.neon.vmaxs` intrinsic (to the proper FPU instruction).  You need `-mfpu=neon-fp-armv8`.

The backend crash itself is jarring as compared to a compiler error but my guess is that this is quite common in the backend during conflicting -mfpu option and intrinsics that expect a minimum FPU.

**Comment by pirama-arumuga-nainar** [comment]
Upon reading further, it seems that this intrinsic should be supported by the `fullfp16` target feature that does enabled for `-mfpu=neon+fp16`.  I'll dig deeper.

**Comment by pirama-arumuga-nainar** [comment]
Filed upstream bug https://bugs.llvm.org/show_bug.cgi?id=42556.  I think the frontend and backend are inconsistent here (the intrinsic should be enabled iff the required FPU option is provided).

**Comment by sethbrin** [comment]
I tried `clang9` with some target-feature can generate code.
```
clang++-9 --target=armv7a-linux-androideabi16 ./main.cpp -march=armv8.2-a+fp16 -mfpu=neon-fp16 -mfloat-abi=softfp -Xclang -target-feature -Xclang +vfp4d16sp -Xclang -target-feature -Xclang +fp-armv8d16sp
```
The clang version: 9.0.0-svn364485-1~exp1+0~20190626222339.2586~1.gbp8282b6 (trunk)

**Comment by pirama-arumuga-nainar** [comment]
@sethbrin Look at the comment, https://bugs.llvm.org/show_bug.cgi?id=42556#c2, for a detailed explanation.  I think omitting `-mfpu` is a cleaner/simpler fix.

**Comment by pirama-arumuga-nainar** [comment]
As mentioned in the upstream bug, `fp16` feature requires an `armv8` fpu.  Adding `-mfpu=neon-fp-armv8` should also fix this issue.

The backend error is not user-friendly but will get addressed as part of the upstream bug.
