### ISSUE TITLE
[BUG] android_getCpuFeatures doesn't returns ARM crypto extension support on some ARMv8 devices

### ISSUE THREAD

**Issue by makotokato** [android-ndk/ndk#1040]
#### Description

Some ARMv8 devices (ex. Moto G5) suppprts ARM crypto extensions since this uses Cortex-A53.  But since `AT_HWCAP2` isn't implemented, `android_getCpuFeatures` cannot detect some CPU features , although `/proc/cpuinfo` shows "supported"

Google's BoringSSL has the workaround for this issue.  See https://bugs.chromium.org/p/boringssl/issues/detail?id=46 for more detail and workaround code.

#### Environment Details

* NDK Version: r20
* Build system: All.
* Host OS: All.
* ABI: armeabi-v7
* NDK API level: All
* Device API level: All (depends on device.  See https://bugs.chromium.org/p/boringssl/issues/detail?id=46 and Google's internal bug db)

**Comment by DanAlbert** [comment]
Try https://github.com/google/cpu_features. It's usually much better. The NDK cpufeatures isn't maintained beyond keeping it building.

**Comment by enh** [comment]
yeah, we added the missing CTS test to the bionic tests back in 2016, but https://github.com/google/cpu_features are already doing a great job of maintaining all these special cases and workarounds.

i'll fix the docs to make this _much_ clearer than it currently is...

**Comment by DanAlbert** [comment]
Should we add an `__attribute__((deprecated))` to `android_getCpuFeatures`?

**Comment by enh** [comment]
now we have external/cpu_features in the tree *and* they have an NDK source compatibility shim in addition to their "real" API, maybe we should just repackage that in the NDK? @gchatelet

**Comment by gchatelet** [comment]
@makotokato do you have access to a Moto G5?
That would be great if you could run [`list_cpu_features`](https://github.com/google/cpu_features#running-sample-code) on it and check that it works for you.

@enh that's a good idea, we just need to make sure it's a recent enough version. I'm planning to release a new one soon as [requested here](https://github.com/google/cpu_features/issues/85).

**Comment by enh** [comment]
(talking to danalbert, it sounds like we'd rather have cpu_features be one of the first libraries available in the new package manager and keep the NDK one deprecated with an eye to being able to just move people over completely [and eventually removing the NDK copy].)

**Comment by enh** [comment]
okay, https://developer.android.com/ndk/guides/cpu-features should be a lot clearer now. when we have the new package manager, we'll make sure cpu_features is one of the first packages, and work towards removing the legacy NDK cpufeatures...
