### ISSUE TITLE
[BUG] Std::function crashes while calling __f_.destroy_deallocate()

### ISSUE THREAD

**Issue by bhupeshpant19jan** [android-ndk/ndk#1042]
#### std::function crashes during destroy() or destroy_deallocate()
 Our existing code started to fail after I have moved my apps from gnustl-libstdc++ to llvm-libc++.
Upon investigation, I have observed that this is happening whenever std;function object is either moved (using std::move) or goes out of scope. in both the scenarios it is calling __f_.destroy or __f_.destroy_deallocate() and then our app is crashing with following error and 

[Fatal signal 11 (SIGSEGV), code 2 (SEGV_ACCERR), fault addr 0x705b7014 in tid 17562 (ce.xxxxx), pid 17562 (xxxxxxx)

 Build fingerprint: 'OnePlus/OnePlus6T/OnePlus6T:9/PKQ1.180716.001/1905281230:user/release-keys'
07-13 03:55:57.057 17611 17611 F DEBUG   : Revision: '0'
07-13 03:55:57.057 17611 17611 F DEBUG   : ABI: 'arm64'
07-13 03:55:57.057 17611 17611 F DEBUG   : pid: 17562, tid: 17562, name: ce.xxxxxx >>> com.microsoft.office.officehubrow <<<
07-13 03:55:57.057 17611 17611 F DEBUG   : signal 11 (SIGSEGV), code 2 (SEGV_ACCERR), fault addr 0x705b7014
07-13 03:55:57.057 17611 17611 F DEBUG   :     x0  00000000178d48c0  x1  000000737fb24000  x2  0000000000000001  x3  0000000000000001
07-13 03:55:57.057 17611 17611 F DEBUG   :     x4  0000007388441e28  x5  524550ffffffffff  x6  8080800000000000  x7  0000000000808080
07-13 03:55:57.057 17611 17611 F DEBUG   :     x8  0000007fd145b630  x9  00000000178d48c0  x10 00000000705b7014  x11 0000000000000003
07-13 03:55:57.057 17611 17611 F DEBUG   :     x12 0000000000000000  x13 0000000000000028  x14 ffffffffffffffff  x15 0000813f5c948193
07-13 03:55:57.057 17611 17611 F DEBUG   :     x16 000000736161cf18  x17 00000073658db7b4  x18 0000000000000001  x19 0000007388414c00
07-13 03:55:57.057 17611 17611 F DEBUG   :     x20 0000000000000000  x21 0000007388414c00  x22 0000007fd145b980  x23 000000736dbccd85
07-13 03:55:57.057 17611 17611 F DEBUG   :     x24 0000000000000004  x25 000000740e5235e0  x26 0000007388414ca0  x27 0000000000000001
07-13 03:55:57.057 17611 17611 F DEBUG   :     x28 0000007fd145b6b0  x29 0000007fd145b4f0
07-13 03:55:57.057 17611 17611 F DEBUG   :     sp  0000007fd145b4e0  lr  0000007361e8e44c  pc  00000000705b7014
07-13 03:55:57.060 17611 17611 I unwind  : Malformed section header found, ignoring...](url)

The behavior is consistent and is reproing with different scenarios.
Had this been reported by anyone? Or do you suspect anything behind that?

#### Environment Details

Not all of these will be relevant to every bug, but please provide as much
information as you can.

* NDK Version: Value from Pkg.Revision in ndk-bundle/source.properties. If not
  the latest version, check there before filing.
* Build system: ndk-build? CMake? Standalone toolchain? Custom? (If gradle, file
  a bug against Android Studio as specified above.)
* Host OS: Windows, Mac, or Linux? Which Linux?
* ABI:
* NDK API level:
* Device API level:

**Comment by DanAlbert** [comment]
We need a repro case.

**Comment by psionic12** [comment]
I happens to occur this issue as well (by using ndk 18), but the chance is 1/15000, so it's hard to give a reproduced case.

Mean while, I add some logs around the code, and the case doesn't happen anymore, I think the compiler somehow change the machine code which might hide the chance to crash.
