### ISSUE TITLE
[BUG]loop can't exit

### ISSUE THREAD

**Issue by sunzj** [android-ndk/ndk#1045]
**Description**
I encounter a very weird issue when use NDK . There are two loops, but the first loop can't exit,seems it don't check the execution condition. And i write a test case to reproduce that issue. 

**Environment Details**
Build server: Ubuntu 16.04 x86

NDK:
Pkg.Desc = Android NDK
Pkg.Revision = 20.0.5594570

Android.mk
`LOCAL_PATH := $(call my-dir)`
`include $(CLEAR_VARS)`
`LOCAL_SRC_FILES := test_sample.cc`
`LOCAL_MODULE = test_sample`
`LOCAL_CPPFLAGS := -g -O`
`LOCAL_CPP_FEATURES += exceptions`
`LOCAL_ARM_MODE := arm`
`include $(BUILD_EXECUTABLE)`

Application.mk
`APP_STL := c++_shared`
`APP_ABI = armeabi-v7a`
`APP_PLATFORM = android-19`
`APP_CPPFLAGS += -std=c++11 -frtti`

test_sample.cc

`#include <cstdio>`
`#include <iostream>`
`#include <vector>`
   
`typedef struct Object {`
   ` int      cls;`
`} Object;`
   
`std::vector<Object> PostProcess(float* out, const int *size) {`
   
 `  std::vector<Object> objs;`
   `double prob = 0.0;`
   
   `int gridYY = 0;`
   `int gridX = 0;`
   
  `for(gridYY = 0; gridYY < 11; gridYY++) {`
      `for(gridX = 0; gridX < 11; gridX++) { `
          `int _gridY = gridYY;`
           `int _gridX = gridX;`
            `std::cout<<"gridY:"<< gridYY << "  gridX:"<< gridX << std::endl;`
            `if(gridYY == 11) {`
               `std::cout << "error"<<std::endl;`
               `return objs;`
               `break;`
           `}`
      `}`
    `}`
`}` 
         
   
`int main(void) {`
   
  `const int outSizes[] = {5, 25, 11, 11};`
  `std::vector<Object> findObjs = PostProcess(NULL,outSizes);`
  `return 0;`
`}  `

**Output:**
/data/test_binary # ./test_sample                                                                                                            
gridY:0  gridX:0
gridY:0  gridX:1
gridY:0  gridX:2
gridY:0  gridX:3
gridY:0  gridX:4
gridY:0  gridX:5
gridY:0  gridX:6
gridY:0  gridX:7
gridY:0  gridX:8
gridY:0  gridX:9
gridY:0  gridX:10
gridY:1  gridX:0
gridY:1  gridX:1
gridY:1  gridX:2
gridY:1  gridX:3
gridY:1  gridX:4
gridY:1  gridX:5
gridY:1  gridX:6
gridY:1  gridX:7
gridY:1  gridX:8
gridY:1  gridX:9
gridY:1  gridX:10
gridY:2  gridX:0
gridY:2  gridX:1
gridY:2  gridX:2
gridY:2  gridX:3
gridY:2  gridX:4
gridY:2  gridX:5
gridY:2  gridX:6
gridY:2  gridX:7
gridY:2  gridX:8
gridY:2  gridX:9
gridY:2  gridX:10
gridY:3  gridX:0
gridY:3  gridX:1
gridY:3  gridX:2
gridY:3  gridX:3
gridY:3  gridX:4
gridY:3  gridX:5
gridY:3  gridX:6
gridY:3  gridX:7
gridY:3  gridX:8
gridY:3  gridX:9
gridY:3  gridX:10
gridY:4  gridX:0
gridY:4  gridX:1
gridY:4  gridX:2
gridY:4  gridX:3
gridY:4  gridX:4
gridY:4  gridX:5
gridY:4  gridX:6
gridY:4  gridX:7
gridY:4  gridX:8
gridY:4  gridX:9
gridY:4  gridX:10
gridY:5  gridX:0
gridY:5  gridX:1
gridY:5  gridX:2
gridY:5  gridX:3
gridY:5  gridX:4
gridY:5  gridX:5
gridY:5  gridX:6
gridY:5  gridX:7
gridY:5  gridX:8
gridY:5  gridX:9
gridY:5  gridX:10
gridY:6  gridX:0
gridY:6  gridX:1
gridY:6  gridX:2
gridY:6  gridX:3
gridY:6  gridX:4
gridY:6  gridX:5
gridY:6  gridX:6
gridY:6  gridX:7
gridY:6  gridX:8
gridY:6  gridX:9
gridY:6  gridX:10
gridY:7  gridX:0
gridY:7  gridX:1
gridY:7  gridX:2
gridY:7  gridX:3
gridY:7  gridX:4
gridY:7  gridX:5
gridY:7  gridX:6
gridY:7  gridX:7
gridY:7  gridX:8
gridY:7  gridX:9
gridY:7  gridX:10
gridY:8  gridX:0
gridY:8  gridX:1
gridY:8  gridX:2
gridY:8  gridX:3
gridY:8  gridX:4
gridY:8  gridX:5
gridY:8  gridX:6
gridY:8  gridX:7
gridY:8  gridX:8
gridY:8  gridX:9
gridY:8  gridX:10
gridY:9  gridX:0
gridY:9  gridX:1
gridY:9  gridX:2
gridY:9  gridX:3
gridY:9  gridX:4
gridY:9  gridX:5
gridY:9  gridX:6
gridY:9  gridX:7
gridY:9  gridX:8
gridY:9  gridX:9
gridY:9  gridX:10
gridY:10  gridX:0
gridY:10  gridX:1
gridY:10  gridX:2
gridY:10  gridX:3
gridY:10  gridX:4
gridY:10  gridX:5
gridY:10  gridX:6
gridY:10  gridX:7
gridY:10  gridX:8
gridY:10  gridX:9
gridY:10  gridX:10
gridY:11  gridX:0
error

**issue:**
When gridYY is 11, it should exit the loop, but it can't .....

**Comment by rprichard** [comment]
When I compiled the program, the compiler printed a warning:
```
jni/test_sample.cpp:29:1: warning: control may reach end of non-void function [-Wreturn-type]
}
^
```
I fixed the warning by adding a `return objs;` to the end of PostProcess, which also fixed the strange `gridYY == 11` error behavior.

PostProcess needs to return a value -- implicitly returning without one has undefined behavior.

**Comment by sunzj** [comment]
@DanAlbert Thanks very much, i tried your guide ,it fixed! 
But that warning should not causes such weird issue... on the "stable ndk realease"...

**Comment by DanAlbert** [comment]
I agree, but unfortunately C++ doesn't. This isn't something that the NDK does wrong, this is something that C++ compilers do. They don't consider this to be a bug.

If you don't want to be chasing these sorts of things, set `-Werror=return-type` and it'll be a build failure instead of a runtime failure. You'd probably benefit from `-Werror`/`-Wall`, since there are a handful of other warnings that will help you find bugs.
