### ISSUE TITLE
Androidstudio3.4 cannot produce apk with camke 3.6.4111459

### ISSUE THREAD

**Issue by jewelyeah** [android-ndk/ndk#1048]
Software environment:
Window10 X64;AndroidStudio3.4;Camke,NDK is updated to the latest in Settings, as shown in the figure
The new hello-jni demo project clean project is fine, but the generated apk reports the following error:
Build command failed.
Error while executing process C:\back\d\SDK\cmake\3.6.4111459\bin\cmake.exe with arguments {-HC:\workspace\jni-master\app\src\main\java -BC:\workspace\jni-master\app\.externalNativeBuild\cmake\debug\armeabi-v7a -DANDROID_ABI=armeabi-v7a -DANDROID_PLATFORM=android-15 -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\workspace\jni-master\app\build\intermediates\cmake\debug\obj\armeabi-v7a -DCMAKE_BUILD_TYPE=Debug -DANDROID_NDK=C:\workspace\android-ndk-r16b -DCMAKE_CXX_FLAGS=-frtti -fexceptions -DCMAKE_TOOLCHAIN_FILE=C:\workspace\android-ndk-r16b\build\cmake\android.toolchain.cmake -DCMAKE_MAKE_PROGRAM=C:\back\d\SDK\cmake\3.6.4111459\bin\ninja.exe -GAndroid Gradle - Ninja -DANDROID_ARM_NEON=TRUE}
-- Configuring incomplete, errors occurred!

CMake Error: Error in cmake code at
C:/workspace/jni-master/app/src/main/java/CMakeLists.txt:1:
Parse error.  Expected a command name, got unquoted argument with text "�}I".

I reinstall and uninstall cmake,NDK still reports this error, what should I do?Download R14,R16,R19 of NDK X64 separately, select the newly introduced NDK in project Structure-->SDK location -->android NDK location, still report this error, may I ask what went wrong?

**Comment by DanAlbert** [comment]
Can't do anything without a repro case, but it might be that your CMakeLists.txt was saved with the wrong file encoding. It should be UTF-8.

**Comment by jewelyeah** [comment]
This camke was generated by a new project, and I did not set his Encoding. Project settings-> Editor ->File Encodings Global Encoding, project Encoding, Porperties Files Default Encoding is utf-8, where to set this cmakelists. TXT Encoding?

**Comment by DanAlbert** [comment]
Without a repro case, that was my only guess. We can help more if you can provide a repro case.
