### ISSUE TITLE
ndk-build always links libstdc++

### ISSUE THREAD

**Issue by DanAlbert** [android-ndk/ndk#105]
``` bash
$ readelf -d sources/cxx-stl/llvm-libc++/libs/armeabi-v7a/libc++_shared.so
...
0x00000001 (NEEDED)                     Shared library: [libstdc++.so]
...
```

This is actually because `ndk-build` _always_ links libstdc++ since we don't use `-nodefaultlibs`. We should fix this.

**Comment by DanAlbert** [comment]
Went to add `-nostdlib++` to Clang and found that @nico beat me to it: https://reviews.llvm.org/D35780 (thanks!)

@srhines @pirama-arumuga-nainar: Not sure if you've picked a revision for the next update yet. Could you make sure that patch is included?

**Comment by AstralStorm** [comment]
Also affects cmake builds in 16.0.4293906 rc1.

Hacky workaround if you want to patch it in android.toolchain.cmake (replace to ANDROID_*_FLAGS in that case) follows. This workaround doesn't seem to break anything, but might be adding a few too many libs in fact.

Workaround:
if(NOT CMAKE_CXX_FLAGS MATCHES "nostdlib")
    string(CONCAT CMAKE_CXX_FLAGS "-nodefaultlibs " "${CMAKE_CXX_FLAGS}")
    string(CONCAT CMAKE_SHARED_LINKER_FLAGS "-lc -lm -ldl " "${CMAKE_SHARED_LINKER_FLAGS}")
    string(CONCAT CMAKE_EXE_LINKER_FLAGS "-lc -lm -ldl " "${CMAKE_EXE_LINKER_FLAGS}")
endif()

**Comment by java4ada** [comment]
ETA ?

**Comment by DanAlbert** [comment]
Whenever we get a clang update. Probably r17.

**Comment by DanAlbert** [comment]
https://android-review.googlesource.com/#/c/platform/ndk/+/558900

**Comment by wang-bin** [comment]
Why a new option `-nostdlib++`? libstdc++ is the default for clang,  but explicitly setting `-stdlib=libc++` is enough. I use the option since r13 without any problem.

**Comment by DanAlbert** [comment]
That is not equivalent. libc++.so and libc++.a in the NDK are linker scripts that link all their dependencies. These exist to facilitate standalone toolchains. It is not possible for the link order to be exactly correct using this method, and you run the risk of hitting https://github.com/android-ndk/ndk/issues/379.

**Comment by wang-bin** [comment]
> That is not equivalent
Yes. `-nostdlib++` disables both libc++ and libstdc++

>  libc++.so and libc++.a in the NDK are linker scripts that link all their dependencies
I knew it. In fact I wondered why not removing the full path of libc++.so in linker flags. `-stdlib=libc++` will replace `-lstdc++` by `-lc++`, and because of libc++.so is a script, libc++_shared.so and some other libraries are linked. I got exactly the same binary without the full path libc++.so. But I can't remove it without modifying android.toolchain.cmake.

> These exist to facilitate standalone toolchains
I use cmake

> It is not possible for the link order to be exactly correct using this method, and you run the risk of hitting #379
Not sure. No problem found yet

**Comment by thughes** [comment]
@DanAlbert Why does `nostdlib++` not apply when using STLport?
https://android.googlesource.com/platform/ndk.git/+/master/build/cmake/android.toolchain.cmake#332

I don't know much about STLport (and am not using it for my ndk build), but it's not entirely clear to me why it should be special:
https://developer.android.com/ndk/guides/cpp-support.html#stlport
https://developer.android.com/ndk/guides/cpp-support.html#one_stl_per_app

I'm trying to make sure cmake (without using the toolchain file) has the right behavior:
https://gitlab.kitware.com/cmake/cmake/merge_requests/1919
https://gitlab.kitware.com/cmake/cmake/issues/17863

**Comment by cybertk** [comment]
The issue still exists in **NDK r17** while building with `ndk-build`, is there any fix plan or workaround?

**Comment by cybertk** [comment]
**NDK r16b** works fine with same project configuration

```makefile
APP_PLATFORM := android-16
APP_ABI := arm64-v8a
APP_STL := c++_shared
APP_CPPFLAGS += -std=c++11 -fexceptions
```

**Comment by DanAlbert** [comment]
No it doesn't?

```c++
// foo/jni/foo.cpp
int main(int argc, char** argv) {
  return 0;
}
```

```makefile
# foo/jni/Android.mk
LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)
LOCAL_MODULE := foo
LOCAL_SRC_FILES := foo.cpp
include $(BUILD_EXECUTABLE)
```

```makefile
# foo/jni/Application.mk
APP_STL := c++_shared
APP_CPPFLAGS := -std=c++11 -fexceptions
```

```bash
$ android-ndk-r17/ndk-build -C foo APP_ABI=arm64-v8a V=1 APP_LDFLAGS=-v -B
Android NDK: APP_PLATFORM not set. Defaulting to minimum supported version android-14.
make: Entering directory `/work/src/ndk/ndk/foo'
rm -f ./libs/arm64-v8a/* ./libs/armeabi-v7a/* ./libs/x86/* ./libs/x86_64/*
rm -f ./libs/arm64-v8a/gdbserver ./libs/armeabi-v7a/gdbserver ./libs/x86/gdbserver ./libs/x86_64/gdbserver
rm -f ./libs/arm64-v8a/gdb.setup ./libs/armeabi-v7a/gdb.setup ./libs/x86/gdb.setup ./libs/x86_64/gdb.setup
[arm64-v8a] Compile++      : foo <= foo.cpp
/work/src/android-ndk-r17/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++ -MMD -MP -MF ./obj/local/arm64-v8a/objs/foo/foo.o.d -gcc-toolchain /work/src/android-ndk-r17/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64 -target aarch64-none-linux-android -ffunction-sections -funwind-tables -fstack-protector-strong -fpic -Wno-invalid-command-line-argument -Wno-unused-command-line-argument -no-canonical-prefixes
 -g -fno-exceptions -fno-rtti -O2 -DNDEBUG  -I/work/src/android-ndk-r17/sources/cxx-stl/llvm-libc++/include -I/work/src/android-ndk-r17/sources/cxx-stl/llvm-libc++/../llvm-libc++abi/include -Ijni -std=c++11  -std=c++11 -fexceptions  -DANDROID  -D__ANDROID_API__=21 -Wa,--noexecstack -Wformat -Werror=format-security -fpie   --sysroot /work/src/android-ndk-r17/sysroot -isystem /work/src/android-ndk-r17/sysroot/usr/include/aarch64-linux-android -c  jni/foo.cpp -o ./obj/local/arm64-v8a/objs/foo/foo.o
[arm64-v8a] Prebuilt       : libc++_shared.so <= <NDK>/sources/cxx-stl/llvm-libc++/libs/arm64-v8a/
cp -f /work/src/android-ndk-r17/sources/cxx-stl/llvm-libc++/libs/arm64-v8a/libc++_shared.so obj/local/arm64-v8a/libc++_shared.so
[arm64-v8a] Executable     : foo
/work/src/android-ndk-r17/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++ -Wl,--gc-sections -Wl,-z,nocopyreloc --sysroot=/work/src/android-ndk-r17/platforms/android-21/arch-arm64 -Wl,-rpath-link=/work/src/android-ndk-r17/platforms/android-21/arch-arm64/usr/lib -Wl,-rpath-link=./obj/local/arm64-v8a ./obj/local/arm64-v8a/objs/foo/foo.o -lgcc -Wl,--exclude-libs,libgcc.a -latomic -Wl,--exclude-libs,libatomic.a ./obj/local/arm64-v8a/libc++_shared.so  -gcc-toolchain /work/src/android-ndk-r17/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64 -target aarch64-none-linux-android -no-canonical-prefixes   -Wl,--build-id -nostdlib++ -Wl,--no-undefined -Wl,-z,noexecstack -Wl,-z,relro -Wl,-z,now -Wl,--warn-shared-textrel -Wl,--fatal-warnings -fpie -pie -v  -lc -lm -o ./obj/local/arm64-v8a/foo
Android (4691093 based on r316199) clang version 6.0.2 (https://android.googlesource.com/toolchain/clang 183abd29fc496f55536e7d904e0abae47888fc7f) (https://android.googlesource.com/toolchain/llvm 34361f192e41ed6e4e8f9aca80a4ea7e9856f327) (based on LLVM 6.0.2svn)
Target: aarch64-none-linux-android
Thread model: posix
InstalledDir: /work/src/android-ndk-r17/toolchains/llvm/prebuilt/linux-x86_64/bin
Found candidate GCC installation: /work/src/android-ndk-r17/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64/lib/gcc/aarch64-linux-android/4.9.x
Selected GCC installation: /work/src/android-ndk-r17/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64/lib/gcc/aarch64-linux-android/4.9.x
Candidate multilib: .;@m64
Selected multilib: .;@m64
 "/work/src/android-ndk-r17/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64/lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/bin/ld" --sysroot=/work/src/android-ndk-r17/platforms/android-21/arch-arm64 -pie --fix-cortex-a53-843419 --eh-frame-hdr -m aarch64linux -dynamic-linker /system/bin/linker64 -o ./obj/local/arm64-v8a/foo /work/src/android-ndk-r17/platforms/android-21/arch-arm64/usr/lib/crtbegin_dynamic.o -L/work/src/android-ndk-r17/toolchains/llvm/prebuilt/linux-x86_64/lib64/clang/6.0.2/lib/linux/aarch64 -L/work/src/android-ndk-r17/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64/lib/gcc/aarch64-linux-android/4.9.x -L/work/src/android-ndk-r17/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64/lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/lib/../lib64 -L/work/src/android-ndk-r17/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64/lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/lib -L/work/src/android-ndk-r17/platforms/android-21/arch-arm64/usr/lib --gc-sections -z nocopyreloc -rpath-link=/work/src/android-ndk-r17/platforms/android-21/arch-arm64/usr/lib -rpath-link=./obj/local/arm64-v8a ./obj/local/arm64-v8a/objs/foo/foo.o -lgcc --exclude-libs libgcc.a -latomic --exclude-libs libatomic.a ./obj/local/arm64-v8a/libc++_shared.so --build-id --no-undefined -z noexecstack -z relro -z now --warn-shared-textrel --fatal-warnings -lc -lm -lm -lgcc -lgcc -ldl -lc -lgcc -lgcc -ldl /work/src/android-ndk-r17/platforms/android-21/arch-arm64/usr/lib/crtend_android.o
[arm64-v8a] Install        : foo => libs/arm64-v8a/foo
install -p ./obj/local/arm64-v8a/foo ./libs/arm64-v8a/foo
/work/src/android-ndk-r17/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64/bin/aarch64-linux-android-strip --strip-unneeded  ./libs/arm64-v8a/foo
[arm64-v8a] Install        : libc++_shared.so => libs/arm64-v8a/libc++_shared.so
install -p ./obj/local/arm64-v8a/libc++_shared.so ./libs/arm64-v8a/libc++_shared.so
/work/src/android-ndk-r17/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64/bin/aarch64-linux-android-strip --strip-unneeded  ./libs/arm64-v8a/libc++_shared.so
make: Leaving directory `/work/src/ndk/ndk/foo'
$ readelf -dW foo/libs/arm64-v8a/foo | grep stdc
$
```

**Comment by cybertk** [comment]
Here is my error with r17,

```
[arm64-v8a] Executable     : foo
/root/android-ndk-r17/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64/lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/bin/ld: ./obj/local/arm64-v8a/foo: hidden symbol `_Unwind_Resume' in /root/android-ndk-r17/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64/lib/gcc/aarch64-linux-android/4.9.x/libgcc.a(unwind-dw2.o) is referenced by DSO
/root/android-ndk-r17/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64/lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/bin/ld: final link failed: Bad value
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [obj/local/arm64-v8a/foo] Error 1
```

**Comment by DanAlbert** [comment]
That doesn't seem to have anything to do with this bug. You'll need to file a new bug with a test case.

**Comment by pengzhendong** [comment]
> Here is my error with r17,
> 
> ```
> [arm64-v8a] Executable     : foo
> /root/android-ndk-r17/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++ -Wl,--gc-sections -Wl,-z,nocopyreloc --sysroot=/root/android-ndk-r17/platforms/android-21/arch-arm64 -Wl,-rpath-link=/root/android-ndk-r17/platforms/android-21/arch-arm64/usr/lib -Wl,-rpath-link=./obj/local/arm64-v8a ./obj/local/arm64-v8a/objs/foo/main.o -lgcc -Wl,--exclude-libs,libgcc.a -latomic -Wl,--exclude-libs,libatomic.a ./obj/local/arm64-v8a/libA.so ./obj/local/arm64-v8a/libB.so ./obj/local/arm64-v8a/libC.so ./obj/local/arm64-v8a/libc++_shared.so  -gcc-toolchain /root/android-ndk-r17/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64 -target aarch64-none-linux-android -no-canonical-prefixes   -Wl,--build-id -nostdlib++ -Wl,--no-undefined -Wl,-z,noexecstack -Wl,-z,relro -Wl,-z,now -Wl,--warn-shared-textrel -Wl,--fatal-warnings -fpie -pie   -lc -lm -o ./obj/local/arm64-v8a/foo
> /root/android-ndk-r17/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64/lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/bin/ld: ./obj/local/arm64-v8a/foo: hidden symbol `_Unwind_Resume' in /root/android-ndk-r17/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64/lib/gcc/aarch64-linux-android/4.9.x/libgcc.a(unwind-dw2.o) is referenced by DSO
> /root/android-ndk-r17/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64/lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/bin/ld: final link failed: Bad value
> clang++: error: linker command failed with exit code 1 (use -v to see invocation)
> make: *** [obj/local/arm64-v8a/foo] Error 1
> ```

Same error, have you fixed that?

**Comment by enh-google** [comment]
r17 is no longer supported. please try again with a current NDK, and file a new bug if you still have trouble with that.

**Comment by DanAlbert** [comment]
Please file new bugs if you have new bugs. As I responded to the original commenter for that error, it has nothing to do with the topic of this thread. We want to help, but we can't fix r17 and we can't fix bugs we can't see, so we need a bug filed with a repro case to do so.
