### ISSUE TITLE
Function symbol pointer

### ISSUE THREAD

**Issue by RusJJ** [android-ndk/ndk#1050]
Hi there! Older NDK (gnustl) has a feature to get a pointer to the symbol (etc. Player class function from another library) using & (ex: &Player::getSpeed). Now i need to use dlsym. Any alternatives? I dislike dlsym, cuz in my opinion its better to use &.

**Comment by DanAlbert** [comment]
That has nothing to do with the STL. What's the problem? There's not enough information here.

**Comment by RusJJ** [comment]
Using older ndk i can do this:
`#include <jni.h>
#include <substrate.h>

class Player
{
public:
	virtual float getSpeed() const;
};
static float (*ReturnSpeed)();
static float GetSpeed()
{
	return ReturnSpeed();
}

JNIEXPORT jint JNI_OnLoad(JavaVM* vm, void* reserved)
{
	MSHookFunction((void*) &Player::getSpeed, (void*) &GetSpeed, (void**) &ReturnSpeed);
	return JNI_VERSION_1_6;
}`
Since NDK 18 (as i remember) there's an error with &Player::getSpeed and i need to use dlsym(..., "Z6Player...");

**Comment by RusJJ** [comment]
UPD: changed something in project files and it seems to be fixed. idk how 🤔

**Comment by DanAlbert** [comment]
> there's an error

What error?

> changed something in project files and it seems to be fixed.

Okay, probably just needed a clean build then. Closing. If it recurs and you can provide answers to those questions, we can reopen.
