### ISSUE TITLE
[BUG] NDK20, vfmal.f16 inst compile error under arm32

### ISSUE THREAD

**Issue by tianylijun** [android-ndk/ndk#1055]
Please include any context relevant to your question (NDK version, ABI, build system, etc).
NDK R20
/media/psf/Home/Downloads/**android-ndk-r20-linux**/toolchains/llvm/prebuilt/linux-x86_64/bin/clang -target **armv7-none-linux-androideabi29** -gcc-toolchain /media/psf/Home/Downloads/android-ndk-r20-linux/toolchains/llvm/prebuilt/linux-x86_64 --sysroot=/media/psf/Home/Downloads/android-ndk-r20-linux/toolchains/llvm/prebuilt/linux-x86_64/sysroot -g **-DANDROID** -DCORTEXA55 **-march=armv8.2-a+fp16fml+fp16** -fPIC -fPIC -mfpu=neon-fp16 -mfloat-abi=softfp -o sgemm_fp16_a55.S.o -c sgemm_fp16_a55.S

### sgemm_fp16_a55.S:244:5:error: instruction requires: full half-float fml
    vfmal.f16 q12, d7, d1[2]

**Comment by pirama-arumuga-nainar** [comment]
This is similar to #1039 and https://bugs.llvm.org/show_bug.cgi?id=42556.  `fp16` and `fp16ml` are `armv8` extensions and hence need an `armv8` fpu.  Changing to `-mfpu=neon-fp-armv8` fixes this error.
