### ISSUE TITLE
update libc++/libc++abi/libunwind

### ISSUE THREAD

**Issue by DanAlbert** [android-ndk/ndk#106]
libc++ and friends are sorely out of date. Get them updated.

**Comment by sebpop** [comment]
On 05/25/2016 05:16 PM, Dan Albert wrote:
> Do we have an idea of how the current source differs from upstream yet?
>

diffstat says that there are:
 112 files changed, 410 insertions(+), 1100 deletions(-)
with respect to the last merge of libcxx from llvm at r210161.
37 are new tests, 33 test files changed.

diffstat on libcxx/src/
16 files changed, 25 insertions(+), 258 deletions(-)

and libcxx/include/
 20 files changed, 69 insertions(+), 536 deletions(-)

On the other hand libc++ is 1173 patches behind master of today, and libcxxabi is 206 patches behind.

> I'm starting to wonder if the better approach here might be to figure out what our diffs are, burn the existing tree to the ground, import current upstream, and then get those patches applied (where appropriate).

My thinking was to incrementally apply patches one by one and interleave build/testing as we go to minimize breakage.
On the other hand I also like your proposal, as there are not that many changes to be forward-ported, and that would minimize testing.

**Comment by DanAlbert** [comment]
> 37 are new tests

I think all those "new tests" are actually just the same test file with some of the characters escaped. Many of the operator tests in libc++ have the operator characters in the name, so escapes like `s/!=/ne/` were done so the file name could be used as a module name in `ndk-build`.

We should just delete any of those cases. LIT doesn't need them.

> On the other hand I also like your proposal, as there are not that many changes to be forward-ported, and that would minimize testing.

Yeah, my thinking is that a lot of our patches will just go away by updating. The version of libc++ in the NDK is older than all of the patches I upstreamed to support the platform. Some others we have are half baked versions of things that were in review upstream (I think the ARM EHABI support that we have is actually *not* the same as what was finally committed, and I know we don't have the bug fixes that have been made to it, ditto for the GCC support in `<atomic>`). There's also a handful of patches we have that are just a bad idea and should be dropped (incorrectly returning success when asked to change to a locale we don't support).

**Comment by Abe149** [comment]
For the record, here is the count-of-lines from the contents of the archive I sent to Dan [CCd to Sebastian] a little while ago ["upstream_LibC++-to-GNDK_changeset_v11_.tbz2"]...

    55 ./files_to_add/ndk-test.sh
   115 ./files_to_add/src/support/android/locale_android.cpp
    24 ./files_to_add/test/libcxx/android/adb.py
    13 ./files_to_add/test/libcxx/android/build.py
    75 ./files_to_add/test/libcxx/android/compiler.py
    65 ./files_to_add/test/libcxx/android/executors.py
    88 ./files_to_add/test/libcxx/android/test/config.py
    93 ./files_to_add/test/libcxx/android/test/format.py
   163 ./files_to_add/test/libcxx/compiler.py
    91 ./files_to_add/test/libcxx/ndk/test/config.py
    17 ./files_to_add/test/libcxx/selftest/not_test.sh.cpp
    11 ./files_to_add/test/libcxx/selftest/test.fail.cpp
    13 ./files_to_add/test/libcxx/selftest/test.pass.cpp
    16 ./files_to_add/test/libcxx/selftest/test.sh.cpp
   724 ./files_to_add/test/libcxx/test/config.py
   191 ./files_to_add/test/libcxx/test/executor.py
   163 ./files_to_add/test/libcxx/test/format.py
    55 ./files_to_add/test/libcxx/test/target_info.py
    34 ./files_to_add/test/libcxx/test/tracing.py
    46 ./files_to_add/test/libcxx/util.py
    39 ./files_to_add/test/lit.ndk.cfg.in
    41 ./files_to_add/test/re/re.traits/lookup_collatename.xlocale.pass.cpp
    20 ./files_to_add/test/std/iterators/iterators.general/gcc_workaround.pass.cpp
   508 ./files_to_add/test/testit_android
   200 ./upstream-to-NDK_patches/00000001_.patch
    32 ./upstream-to-NDK_patches/00000002_.patch
    19 ./upstream-to-NDK_patches/00000003_.patch
    20 ./upstream-to-NDK_patches/00000004_.patch
    32 ./upstream-to-NDK_patches/00000005_.patch
    29 ./upstream-to-NDK_patches/00000006_.patch
    11 ./upstream-to-NDK_patches/00000007_.patch
    77 ./upstream-to-NDK_patches/00000008_.patch
   397 ./upstream-to-NDK_patches/00000009_.patch
    11 ./upstream-to-NDK_patches/00000010_.patch
    11 ./upstream-to-NDK_patches/00000011_.patch
    18 ./upstream-to-NDK_patches/00000012_.patch
    30 ./upstream-to-NDK_patches/00000013_.patch
    33 ./upstream-to-NDK_patches/00000014_.patch
    19 ./upstream-to-NDK_patches/00000015_.patch
    11 ./upstream-to-NDK_patches/00000016_.patch
    27 ./upstream-to-NDK_patches/00000017_.patch
    11 ./upstream-to-NDK_patches/00000018_.patch
    59 ./upstream-to-NDK_patches/00000019_.patch
    20 ./upstream-to-NDK_patches/00000020_.patch
    14 ./upstream-to-NDK_patches/00000021_.patch
    15 ./upstream-to-NDK_patches/00000022_.patch
   401 ./upstream-to-NDK_patches/00000023_.patch
    79 ./upstream-to-NDK_patches/00000024_.patch
    14 ./upstream-to-NDK_patches/00000025_.patch
    46 ./upstream-to-NDK_patches/00000026_.patch
    18 ./upstream-to-NDK_patches/00000027_.patch
    14 ./upstream-to-NDK_patches/00000028_.patch
   269 ./upstream-to-NDK_patches/00000029_.patch
    18 ./upstream-to-NDK_patches/00000030_.patch
   163 ./upstream-to-NDK_patches/00000031_.patch
    20 ./upstream-to-NDK_patches/00000032_.patch
    58 ./upstream-to-NDK_patches/00000033_.patch
   349 ./upstream-to-NDK_patches/00000034_.patch
    18 ./upstream-to-NDK_patches/00000035_.patch
    18 ./upstream-to-NDK_patches/00000036_.patch
    18 ./upstream-to-NDK_patches/00000037_.patch
    15 ./upstream-to-NDK_patches/00000038_.patch
    18 ./upstream-to-NDK_patches/00000039_.patch
    18 ./upstream-to-NDK_patches/00000040_.patch
    16 ./upstream-to-NDK_patches/00000041_.patch
    11 ./upstream-to-NDK_patches/00000042_.patch
    22 ./upstream-to-NDK_patches/00000043_.patch
    28 ./upstream-to-NDK_patches/00000044_.patch
    25 ./upstream-to-NDK_patches/00000045_.patch
    16 ./upstream-to-NDK_patches/00000046_.patch
    13 ./upstream-to-NDK_patches/00000047_.patch
    13 ./upstream-to-NDK_patches/00000048_.patch
    34 ./upstream-to-NDK_patches/00000049_.patch
    27 ./upstream-to-NDK_patches/00000050_.patch
    31 ./upstream-to-NDK_patches/00000051_.patch
    42 ./upstream-to-NDK_patches/00000052_.patch
    18 ./upstream-to-NDK_patches/00000053_.patch
    35 ./upstream-to-NDK_patches/00000054_.patch
    20 ./upstream-to-NDK_patches/00000055_.patch
    33 ./upstream-to-NDK_patches/00000056_.patch
    43 ./upstream-to-NDK_patches/00000057_.patch
    44 ./upstream-to-NDK_patches/00000058_.patch
    44 ./upstream-to-NDK_patches/00000059_.patch
    44 ./upstream-to-NDK_patches/00000060_.patch
    44 ./upstream-to-NDK_patches/00000061_.patch
    44 ./upstream-to-NDK_patches/00000062_.patch
    44 ./upstream-to-NDK_patches/00000063_.patch
    44 ./upstream-to-NDK_patches/00000064_.patch
    17 ./upstream-to-NDK_patches/00000065_.patch
   291 ./script
  6353 total

**Comment by sebpop** [comment]
I have the impression that the code in android/support needs to be updated:
android_support_c_includes := $(LOCAL_PATH)/../../android/support/include

as otherwise after merging "Add support for BIONIC C library (Android). Patch from Dan Albert" https://github.com/llvm-mirror/libcxx/commit/a64392627edf2f8f1ac80db5cd1cadd082269e13 
we end up with the error "cstdlib:149:9: error: no member named 'at_quick_exit' in the global namespace". I see that bionic/libc/include/stdlib.h has the declaration of at_quick_exit.

**Comment by DanAlbert** [comment]
Yeah, `android/support` is definitely going to need changes. Like I said before, this is the hard part. We have to make things work all the way back to ICS (maybe Gingerbread, but maybe not...)

**Comment by fornwall** [comment]
> Like I said before, this is the hard part. We have to make things work all the way back to ICS (maybe Gingerbread, but maybe not...)

Perhaps it could be possible to demand a higher platform/minSdkVersion version for an updated libc++ (and enforce that in ndk-build and make-standalone-toolchain)?

**Comment by DanAlbert** [comment]
Unfortunately it doesn't get a whole lot easier until the `minSdkVersion` reaches 21 (Lollipop) :(

If it were something like Jelly Bean, that would be the obvious solution, but given that ~60% of users are still pre-Lollipop, that's not really an option.

**Comment by DanAlbert** [comment]
Did this a while ago.

For anyone following along: libc++ in the NDK still hasn't reached the point of being "stable" due to `libandroid_support`. That's the next thing I'm looking at, but there are a surprising number of yaks that need to be shaved to make that happen :)
