### ISSUE TITLE
NDK r11c for Windows can't use precompiled header.

### ISSUE THREAD

**Issue by witchu** [android-ndk/ndk#107]
when use pch on windows this error occurred.

<pre>
C:/Android/android-ndk-r11c/build//../build/core/build-binary.mk:441: *** target pattern contains no `%'.  Stop.
</pre>

because there is no : to _ replacement in get-pch-name

<pre>
get-pch-name = $(strip \
    $(subst ../,__/,\
        $(eval __pch := $1)\
        $(eval __pch := $(__pch:%.h=%.precompiled.h))\
        $(__pch)\
    ))
</pre>

it should be

<pre>
get-pch-name = $(strip \
    $(subst ../,__/,\
        $(subst :,_,\
            $(eval __pch := $1)\
            $(eval __pch := $(__pch:%.h=%.precompiled.h))\
            $(__pch)\
    )))
</pre>

**Comment by DanAlbert** [comment]
What is `LOCAL_PCH` set to in this case? I'm not familiar with this portion of `ndk-build`, so it's not clear to me why we want substitutions at all...

**Comment by witchu** [comment]
Part of my Android.mk
<pre>
LOCAL_PATH := $(call my-dir)
LOCAL_PCH := $(LOCAL_PATH)/include/pch.h
</pre>

the LOCAL_PCH contains full windows path. i.e. C:/Projects/Test/jni/include/pch.h

I think `make` do not like :

**Comment by DanAlbert** [comment]
Started investigating this and I noticed that your use of `LOCAL_PCH` does not match our tests: don't prepend `$(LOCAL_PATH)`. Our tests use simply `LOCAL_PCH := stdafx.h`, so you should probably be using `LOCAL_PCH := include/pch.h`.

**Comment by DanAlbert** [comment]
After further inspecting build/core/build-binary.mk, yes, that's correct. `LOCAL_PCH` will be appended to `LOCAL_SRC_FILES` and so needs to follow the same convention, and `LOCAL_SRC_FILES` should never have `LOCAL_PATH` prepended.
