### ISSUE TITLE
[question]Is sourcecode of native code debugger included in this project

### ISSUE THREAD

**Issue by JustinBobby007** [android-ndk/ndk#1071]
Im just new to android native code development and using intellij idea not android studio.

My intellij idea has installed android plugin with sdks including ndk installed etc, when I import a native c++ project to idea, debug it but there's no debugger tab in "run/debug configurations"

However, using android studio it works normally, so is the sourcecode of native debugger not included in this project?  or something what im missing.

**Comment by DanAlbert** [comment]
This is the wrong place for Studio bugs. https://b.android.com
