### ISSUE TITLE
How to use NDK_ANALYZE when I compiled with cmake ?

### ISSUE THREAD

**Issue by wustwg** [android-ndk/ndk#1072]
I just find how to use NDK_ANALYZE when I compile project with ndk-build ,but I can't find any samples or docs about using NDK_ANALYZE in cmake proj.
I don't know how to using "scan-build" or "NDK_ANALYZE" in android cmake projects,please help me . 
Thank you very much!!!

**Comment by DanAlbert** [comment]
https://stackoverflow.com/a/21785566/632035 seems to be the most sensible solution. We shouldn't be adding any Android-specific workflow for this because we should be getting more like a typical CMake project, not less. If there needs to be a specific CMake affordance for this that should be raised as a CMake bug so it can work for every platform, not just Android.

If you're depending on ndk-build features, why not just stick with ndk-build?

**Comment by wustwg** [comment]
https://stackoverflow.com/a/21785566/632035  
This problem is different from mine. The Android project is special and different from the ordinary Make project.
The reason I use CMake is that CMake supports native code better than android.mk.
Thank you for your answer. I'll go to CMake Project for a question.

**Comment by DanAlbert** [comment]
That example is for CMake.

> The reason I use CMake is that CMake supports native code better than android.mk.

In what ways? Depending on what it is, it might be something we can fix.

**Comment by wustwg** [comment]
The CPP code in our project uses cmake directly, so the CPP code will be prompted when writing the code. And now Android officials also recommend that you use cmake to do CPP support. And cmake is also cross-platform, better portability.

**Comment by DanAlbert** [comment]
> The CPP code in our project uses cmake directly, so the CPP code will be prompted when writing the code.

I don't follow.

> And now Android officials also recommend that you use cmake to do CPP support.

We don't (this is why I asked this question in the first place; somehow a lot of people got the impression that CMake is preferred over ndk-build and that isn't true). We recommend you use whichever works best for you. Given that ndk-build was working for.yoi and you're having trouble with CMake, maybe shouldn't switch?

> And cmake is also cross-platform, better portability.

OTOH if this is something you have to deal with then CMake is a good bet.
