### ISSUE TITLE
[BUG] Cannot select: intrinsic %llvm.instrprof.increment

### ISSUE THREAD

**Issue by myles-android** [android-ndk/ndk#1073]
#### Description

fatal error: error in backend: Cannot select: intrinsic %llvm.instrprof.increment
clang++: error: clang frontend command failed with exit code 70 (use -v to see invocation)
Android (5657785 based on r353983d) clang version 9.0.4 (https://android.googlesource.com/toolchain/llvm-project 2a90cc9d899e6fe6dcf0da193244b25f75735c7b) (based on LLVM 9.0.4svn)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: prebuilts/clang/host/linux-x86/clang-r353983d/bin
clang++: note: diagnostic msg: PLEASE submit a bug report to https://github.com/android-ndk/ndk/issues and include the crash backtrace, preprocessed source, and associated run script.
clang++: note: diagnostic msg: 
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang++: note: diagnostic msg: /ssd/aosp/out/soong/.temp/link_layer_packet_builder-512ba9.cpp
clang++: note: diagnostic msg: /ssd/aosp/out/soong/.temp/link_layer_packet_builder-512ba9.sh

#### Environment Details

Not all of these will be relevant to every bug, but please provide as much
information as you can.

* Build system: ndk-build? CMake? Standalone toolchain? Custom? (If gradle, file
  a bug against Android Studio as specified above.)
AOSP build

* Host OS: Windows, Mac, or Linux? Which Linux? gLinux

I added a .txt extension to both files, so that I could attach them.

[link_layer_packet_builder-512ba9.sh.txt](https://github.com/android-ndk/ndk/files/3571469/link_layer_packet_builder-512ba9.sh.txt)
[link_layer_packet_builder-512ba9.cpp.txt](https://github.com/android-ndk/ndk/files/3571470/link_layer_packet_builder-512ba9.cpp.txt)

**Comment by DanAlbert** [comment]
That compiler is too old to be r20 and too new to be r19. Is this a platform bug?

**Comment by myles-android** [comment]
I don't know.  I filed the bug (following the instructions), then did a
repo sync and make clean ...  Now it works for me.

Thanks,
Myles

**Comment by myles-android** [comment]
The odd thing was that it was working for me, and I can't think of anything
"interesting" that I did to cause it to start failing.  I was making small,
incremental changes to the code.

**Comment by DanAlbert** [comment]
Yeah, if you're using `repo sync` you're working on the platform. They're the same compiler so the instructions point you here either way. @stephenhines @pirama-arumuga-nainar

**Comment by stephenhines** [comment]
> I don't know. I filed the bug (following the instructions), then did a repo sync and make clean ... Now it works for me. Thanks, Myles

Does it work now? Please close the bug if so, or let us know how it is still failing. Thanks.

**Comment by myles-android** [comment]
Done.  No idea how I got to the failing state, but at least I am no longer there.

**Comment by pirama-arumuga-nainar** [comment]
For posterity, the issue is that with clang-353983d, Clang's new pass manager and PGO instrumentation don't work together.  The repo sync either pulled in a workaround for the issue into system/bt or switched to the new Clang where the problem doesn't exist.
