### ISSUE TITLE
[REQUEST] New APIs for Game Controllers and other Input Devices

### ISSUE THREAD

**Issue by cybik** [android-ndk/ndk#109]
I'm porting a game engine from classic Linux to Android, and doing so, I see that the NDK suffers of a dearth of APIs related to Input. More specifically, it appears that there are no facilitation APIs to interrogate the current status of a given input device and get easy access to its information.

Please see https://developer.android.com/training/game-controllers/compatibility.html for an actual example of what I'm talking about. I'd like to be able to call getInputDevice() straight from C++ and get an InputDevice object containing all the info I need, but right now I need to use JNI hacks to do that.

Another way of seeing it: https://developer.android.com/training/game-controllers/multiple-controllers.html - I'd love to verify that the controller I'm receiving an event from is properly connected, *instead* of requiring a user to hit a button on a given controller before being able to say "oh this controller is connected, sweet!".

**Comment by cybik** [comment]
Another fun thing: I don't think input device disconnection and reconnection events are directly implementable using a current NDK; therefore I can't (natively) do what the documentation tells me to do (in Java).

**Comment by DanAlbert** [comment]
Apologies for not responding sooner. I wasn't really sure what to do with this bug yet :)

All the NDK does here is package the Android APIs, we can't actually add new ones ourselves. Looks like there's a new component that was added to b.android.com for exactly this kind of thing: http://code.google.com/p/android/issues/entry?template=New%20NDK%20API%20request

Could I get you to file this request over there?
