### ISSUE TITLE
Support for _POSIX_THREAD_SAFE_FUNCTIONS

### ISSUE THREAD

**Issue by krnekit** [android-ndk/ndk#11]
Though some (or may be all?) posix thread-safe functions is available in Bionic, the toolchain always [undefine](https://android.googlesource.com/platform/development/+/master/ndk/platforms/android-3/include/sys/limits.h?autodive=0%2F%2F%2F%2F%2F%2F%2F%2F%2F#171) _POSIX_THREAD_SAFE_FUNCTIONS. Because of this, software cannot rely, that thread-safe functions available and must use not-safe alternatives, which causes [bugs](https://bugreports.qt.io/browse/QTBUG-51826).

Can you enable this define?

**Comment by DanAlbert** [comment]
Looks like bionic itself (in the platform, not in the NDK) actually does have this fixed. @jmgao is working on syncing the current headers with the NDK (I'm guessing we're going to have to be careful about when this is enabled, as not all platforms have those functions).
