### ISSUE TITLE
Error:(512) *** non-numeric second argument to `wordlist' function: 'N'.  Stop.

### ISSUE THREAD

**Issue by IgorGanapolsky** [android-ndk/ndk#112]
Hello,
I am trying to compile an NDK project with Android.mk, using Android Studio 2.2 Preview 2, gradle 2.2.0-alpha2, and buildToolsVersion '24.0.0-rc3'.  When I go to make my project, it errors out with:
> Error:(512) *** non-numeric second argument to `wordlist' function: 'N'.  Stop.
Error:A problem occurred configuring project ':app'.
> com.android.ide.common.process.ProcessException: Error while executing '/Users/igorganapolsky/Library/Android/sdk/ndk-bundle/ndk-build' with arguments {NDK_PROJECT_PATH=/Users/igorganapolsky/workspace/git/work/AndroidAdobeAirExtension/app/src/main/jni/Android.mk APP_BUILD_SCRIPT=/Users/igorganapolsky/workspace/git/work/AndroidAdobeAirExtension/app/src/main/jni/Android.mk APP_ABI=mips64 NDK_ALL_ABIS=mips64 NDEBUG=1 APP_PLATFORM=android-N NDK_OUT=/Users/igorganapolsky/workspace/git/work/AndroidAdobeAirExtension/app/build/intermediates/ndk-build/prod/debug/obj NDK_LIBS_OUT=/Users/igorganapolsky/workspace/git/work/AndroidAdobeAirExtension/app/build/intermediates/ndk-build/prod/debug/lib -n}

Can you please tell me what's going on?
Igor

**Comment by DanAlbert** [comment]
`APP_PLATFORM` needs to be `android-24`, not `android-N`. If Gradle is setting that for you, you'll need to go file a bug against the Studio folks at http://b.android.com.

It probably shouldn't be setting `NDK_ALL_ABIS=mips64` either... that's an internal variable. Not sure it does any harm, but it shouldn't be needed...

**Comment by IgorGanapolsky** [comment]
But if I follow your advice, I get an error:
> Error:Failed to find target with hash string 'android-24' in: /Android/sdk

**Comment by DanAlbert** [comment]
Okay, definitely an issue with the gradle plugin then. I guess the SDK paths are named N but ours are named 24, and Gradle isn't aware of that difference. File a bug at the link I provided before and they can get it sorted out for you (or maybe not necessary since I think the next push should have the SDK named as 24?)

**Comment by JhonImmanuel** [comment]
this is known problem due to the r8d NDK, update to r15b or latter, its work like a charm
