### ISSUE TITLE
clang r11 libc++ doesn't provides typeinfo for __float128

### ISSUE THREAD

**Issue by ntfshard** [android-ndk/ndk#116]
It looks like an issue in mangling in libc++: 
In libstdc++ it's a 'typeinfo for __float128'  _ZTIg  
In libc++ it's a 'typeinfo for long double'  _ZTIe

architecture: x86_64

I suppose that it's related to the old issue in clang (https://llvm.org/bugs/show_bug.cgi?id=23897). Previously, clang generated _ZTIe for typeinfo for __float128 but now it generates _ZTIg that lead to link error when the fixed compiler is used (with the current version of libc++).

Looks like that libc++ should provide the both symbols for the backward compatibility purpose.

**Comment by DanAlbert** [comment]
Based on the SVN revisions in that bug, this should have been resolved in r12. Please re-open if that's not the case.
