### ISSUE TITLE
ndk-gdb from NDK r12 for Windows x64 can't start the debugging on arm64-v8a device

### ISSUE THREAD

**Issue by nvidiamfilimonov** [android-ndk/ndk#118]
I've tested it on two arm64-v8a devices - one was with Android 6.0 and the other is Nexus 9 running Android N DP2, got the same result for each trial:
>c:\wrk\android\android-ndk-samples\native-activity>f:\work\android-ndk-r12\ndk-gdb.cmd -v -t --launch android.app.NativeActivity
ADB command used: 'adb -s HT4AHJT08522'
ADB version: Android Debug Bridge version 1.0.35 Revision fc2a139a55f5-android
Using project directory: c:\wrk\android\android-ndk-samples\native-activity
Found package name: com.example.native_activity
Selected target activity: 'android.app.NativeActivity'
Application ABIs: arm64-v8a, armeabi, armeabi-v7a, mips, mips64, x86, x86_64
Device ABIs: arm64-v8a, armeabi-v7a, armeabi
Selecting ABI: arm64-v8a
Detected pretty printer: none
Found application data directory: /data/data/com.example.native_activity
App gdbserver not found at /data/data/com.example.native_activity/lib/gdbserver, uploading.
Copying gdbserver to /data/data/com.example.native_activity/arm64-gdbserver.
ERROR: Failed to copy gdbserver to /data/data/com.example.native_activity/arm64-gdbserver.

**Comment by nvidiamfilimonov** [comment]
That's strange as it's possible to copy the same debugger binary into the package directory by hand:
>c:\wrk\android\android-ndk-samples\native-activity>adb shell
flounder:/ $ run-as com.example.native_activity id
uid=10088(u0_a88) gid=10088(u0_a88) groups=10088(u0_a88),1004(input),1007(log),1011(adb),1015(sdcard_rw),1028(sdcard_r),3001(net_bt_admin),3002(net_bt),3003(inet),3006(net_bw_stats),3009(readproc) context=u:r:untrusted_app:s0:c512,c768 flounder:/ $ run-as com.example.native_activity ls /data/data/com.example.native_activity
cache files
flounder:/ $ ls -lah /data/local/tmp/
total 2.1M
drwxrwx--x 3 shell shell 4.0K 2016-06-10 13:02 .
drwxr-x--x 3 root  root  4.0K 2016-04-22 15:21 ..
-rw-rw-rw- 1 shell shell 823K 2016-06-01 23:13 arm64-gdbserver
-rw-rw-rw- 1 shell shell 401K 2016-04-25 16:48 com.example.native_activity
-rw-rw-rw- 1 shell shell    0 2016-04-25 17:29 com.example.native_activity-build-id.txt
flounder:/ $ run-as com.example.native_activity cp /data/local/tmp/arm64-gdbserver /data/data/com.example.native_activity/arm64-gdbserver
flounder:/ $ run-as com.example.native_activity ls -lah  /data/data/com.example.native_activity/arm64-gdbserver
-rw-rw-rw- 1 u0_a88 u0_a88 823K 2016-06-10 13:08 /data/data/com.example.native_activity/arm64-gdbserver

**Comment by nvidiamfilimonov** [comment]
In fact, ndk-gdb seems to not work at all for me. In case of armeabi-v7a it can deploy and launch gdbserver, but gdb executable can't connect to the gdbserver launched on the target

>c:\android-ndk-samples\native-activity>f:\work\android-ndk-r12\ndk-gdb.cmd -v
ADB command used: 'adb -s 015d24a8173c1e12'
ADB version: Android Debug Bridge version 1.0.35 Revision fc2a139a55f5-android
Using project directory: c:\android-ndk-samples\native-activity
Found package name: com.example.native_activity
Attaching to existing application process.
Application ABIs: arm64-v8a, armeabi, armeabi-v7a, mips, mips64, x86, x86_64
Device ABIs: armeabi-v7a, armeabi
Selecting ABI: armeabi-v7a
Detected pretty printer: none
Found application data directory: /data/data/com.example.native_activity
App gdbserver not found at /data/data/com.example.native_activity/lib/gdbserver, uploading.
Uploaded gdbserver to /data/local/tmp/arm-gdbserver
Pulling '/system/bin/linker' to 'c:\android-ndk-samples\native-activity\obj\local\armeabi-v7a\system\bin\linker'
Pulling '/system/lib/libc.so' to 'c:\android-ndk-samples\native-activity\obj\local\armeabi-v7a\system\lib\libc.so'
Pulling '/system/lib/libm.so' to 'c:\android-ndk-samples\native-activity\obj\local\armeabi-v7a\system\lib\libm.so'
Pulling '/system/lib/libdl.so' to 'c:\android-ndk-samples\native-activity\obj\local\armeabi-v7a\system\lib\libdl.so'
Starting gdbserver...
Redirecting gdbserver output to appdata\local\temp\gdbclient.log

Here's gdb output
>GNU gdb (GDB) 7.11
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-w64-mingw32".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word".
Error: unable to connect to device.
Remote communication error.  Target disconnected.: No error.
(gdb)

gdbserver.log contains a single string
>run-as: exec failed for /data/local/tmp/arm-gdbserver Error:Permission denied

**Comment by enh** [comment]
> run-as: exec failed for /data/local/tmp/arm-gdbserver Error:Permission denied

makes sense given

> -rw-rw-rw- 1 shell shell 823K 2016-06-01 23:13 arm64-gdbserver

you'll want to chmod a+x arm64-gdbserver.

**Comment by nvidiamfilimonov** [comment]
@enh I can, but it's makes no sense as the gdbserver that runs under the shell UID can't attach to the package process.
All should be done in case of non-rooted device is to copy the debug server binary from /data/local/tmp directory to the package data root

**Comment by jmgao** [comment]
Whoops, ndk-gdb is completely broken (again). 
Applying [this patch](https://android-review.googlesource.com/#/c/238145/1/ndk-gdb.py) to your ndk-gdb.py should fix it.

**Comment by jmgao** [comment]
Fixed in r12b

**Comment by xloem** [comment]
I'm experiencing this error message on 21.4.7075529 .
