### ISSUE TITLE
NDK r12: I cannot link to libc++ statically with a standalone toolchain

### ISSUE THREAD

**Issue by ngg** [android-ndk/ndk#119]
I created the standalone toolchain with the following command:
``` bash
build/tools/make_standalone_toolchain.py --arch arm --api 14 --stl libc++ --install-dir $HOME/android/tc
```

I have a simple x.cpp file:
``` cpp
// x.cpp
#include <iostream>
int main()
{
	std::cout << "Hello world!" << std::endl;
	return 0;
}
```

I'm trying to compile this with the following command:
``` bash
$HOME/android/tc/bin/arm-linux-androideabi-clang++ -o x x.cpp -lc++_static -lc++abi -landroid_support -lunwind -latomic
```

It compiles successfully, but it still depends on `libc++_shared.so` (as shown by `readelf -d x`).

**Comment by ngg** [comment]
I have found a workaround.
It seems that clang automatically links to `libstdc++.so` which is a linker script with the following content:
```
INPUT(-lunwind -latomic -lc++_shared)
```

There is `libstdc++.a` file with the following content in the same directory:
```
INPUT(-lc++_static -lc++abi -landroid_support -lunwind)
```

If I replace the content of `libstdc++.so` with the content of `libstdc++.a` then it works as expected. (As long as I want to link statically to libc++)

**Comment by DanAlbert** [comment]
The behavior now more closely matches a normal toolchain. What you want is:

```bash
path/to/clang++ -static-libstdc++ $OTHER_ARGS
```

That will select the static version of libstdc++ (which is actually libc++, in this case).

Note that the linker script means you don't actually need to link all those other libraries yourself anymore.

The docs need to be updated to reflect this, but we have a lot of open "the standalone toolchain docs are bad/wrong", so I'm going to close this one.

**Comment by ngg** [comment]
Thanks for the fast reply!
What you suggested almost works for me.
It no longer tries to link to the shared libc++, but it gives undefined reference linker errors for atomic functions.
(`-latomic` is missing from the `libstdc++.a` linker script).
If I try to add `-latomic` it still doesn't work because the static libc++ is linked only after the libraries I specify by hand.

This is the minimal command that is working for me:
```
$HOME/android/tc/bin/arm-linux-androideabi-clang++ -o x -static-libstdc++ x.cpp -lc++_static -lc++abi -latomic
```

If I replace the contents of `libstdc++.a` with the following then it is really working as expected:
```
INPUT(-lc++_static -lc++abi -landroid_support -lunwind -latomic)
```

**Comment by DanAlbert** [comment]
I'll add libatomic to the linker script. Not actually a regression I think (standalone toolchains have always been garbage when it comes to linking libatomic), but definitely an easy quality of life fix.

**Comment by DanAlbert** [comment]
https://android-review.googlesource.com/239291 adds libunwind for ARM. Linker script for the output (should, waiting for a build) is the same as you said above.

One thing to note:

```bash
$HOME/android/tc/bin/arm-linux-androideabi-clang++ -o x -static-libstdc++ x.cpp -lc++_static -lc++abi -latomic
```

In theory you should only need:

```bash
$HOME/android/tc/bin/arm-linux-androideabi-clang++ -o x -static-libstdc++ x.cpp
```

Pending the fix above, of course.

**Comment by DanAlbert** [comment]
FYI, I've cherry-picked this for r12b. Should go out some time later today.
