### ISSUE TITLE
transformNative_libsWithSyncJniLibsFor - compilation error

### ISSUE THREAD

**Issue by boazyag** [android-ndk/ndk#124]
Hi,

When I'm compiling my app that contains a library with NDK calls (Moodstocks) everything is fine.
But when I try to compile my app as a library (ARR extension) I get the following comiplation error:
		Error:Execution failed for task ':sdk:transformNative_libsWithSyncJniLibsFor.....'.
			> java.io.FileNotFoundException: ..... (No such file or directory)
When I searched the web I found only this post about this issue:
	http://dodotrivia.blogspot.co.il

Is there a plan to solve this? If so, when? It prevents me to upgrade my build tools.

Thanks,
Boaz

**Comment by DanAlbert** [comment]
Sounds like a gradle issue? Could you file the bug at b.android.com? We actually don't handle gradle.
