### ISSUE TITLE
win64 and win32 versions tagged incorrectly

### ISSUE THREAD

**Issue by alexcohn** [android-ndk/ndk#127]
On the [download page](https://developer.android.com/ndk/downloads/index.html), the Windows versions seem to be mixed up:

![image](https://cloud.githubusercontent.com/assets/736435/16206862/19e0e2e4-3733-11e6-910e-9dd0e5585012.png)

**Comment by DanAlbert** [comment]
And out of date. Should be r12b now :(

I'll let the people in charge of the site know.

**Comment by vinjn** [comment]
+1 caused lots of trouble...

**Comment by DanAlbert** [comment]
FWIW, the wiki here will always have up to date links, and since I can personally update them things like this can be fixed immediately. The official site should still get fixed for sure, but that might be useful for the future.
