### ISSUE TITLE
Create Function doesn't generate the extern "C" wrapper declaration

### ISSUE THREAD

**Issue by TheFakeMontyOnTheRun** [android-ndk/ndk#128]
As you create a native java method declaration, like:
`public static native void blah();`
Android Studio offers the option to create the function automatically. The library being loaded in the class that was loaded for this method is a module generated from a C++ file. Android Studio does correctly generates the prototype and, in some cases, some code for handling the parameters (very helpful!). But it missed completely the redeclaration that must happen inside the extern "C" block:
```
extern "C" {
//...
}

JNIEXPORT void JNICALL
Java_br_odb_nehe_lesson10_GL2JNILib_blah(JNIEnv *env, jclass type) {
    // TODO
}
```
This should be:

```
extern "C" {
//...
JNIEXPORT void JNICALL
Java_br_odb_nehe_lesson10_GL2JNILib_blah(JNIEnv *env, jclass type);
}

JNIEXPORT void JNICALL
Java_br_odb_nehe_lesson10_GL2JNILib_blah(JNIEnv *env, jclass type) {
    // TODO
}

```

My system: Ubuntu Linux 64 bits 14.04
Android Studio 2.1.2
JRE 1.8.0
Gradle 2.11-all
Gradle-Experimental 0.8.0-alpha3

Project tried: https://github.com/TheFakeMontyOnTheRun/nehe-ndk-gles20/tree/master/lesson10

**Comment by enh** [comment]
wrong bug database. that's an Android Studio bug. see http://b.android.com/ for that.

**Comment by TheFakeMontyOnTheRun** [comment]
Sorry about that!
