### ISSUE TITLE
[r12] Compiling any static executable leads to "error: undefined reference to 'atexit'"

### ISSUE THREAD

**Issue by chenxiaolong** [android-ndk/ndk#132]
Test repo available here: https://github.com/chenxiaolong/ndk_atexit_test

Starting with the r12 release, it's no longer possible to compile static executables (at least with clang). The repo above contains a C program that does nothing except `return EXIT_SUCCESS` and it fails with the an undefined reference to atexit error.

```
[ndk_atexit_test] ./test.sh                                                                                                              13:02:54  ☁  master ☂ ⚡ ✭
--- Testing android-24 ---
[armeabi-v7a] Compile thumb  : main <= main.c
[armeabi-v7a] Executable     : main
external/jemalloc/src/jemalloc.c:707: error: undefined reference to 'atexit'
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [/opt/android-ndk/build/core/build-binary.mk:691: out/ndk_armeabi-v7a/obj/local/armeabi-v7a/main] Error 1
```

This happens with platforms 24, 23, 22, and 21. `r11c` did not have this issue.

**Comment by chenxiaolong** [comment]
It seems like `crtbegin_static.o` is missing the `atexit` symbol in r12:

```
[lib] nm /opt/android-ndk/platforms/android-24/arch-arm/usr/lib/crtbegin_static.o | grep -i atexit
[lib] nm /opt/android-ndk-r11c/platforms/android-24/arch-arm/usr/lib/crtbegin_static.o | grep -i atexit 
00000088 T atexit
00000000 T __atexit_handler_wrapper
         U __cxa_atexit
```

**Comment by DanAlbert** [comment]
I think the breaking change was https://android-review.googlesource.com/#/c/219746/

Found some more skeletons in the closet. Looks like for some inexplicable reason `crtbegin_static.c` was a symlink to `crtbegin_dynamic.c`. The static one expects `atexit` to come from `libc.a`, while the dynamic one includes the implementation via `atexit.h`. Starting with android-21, `atexit` is no longer in `libc.a`.

**Comment by DanAlbert** [comment]
These three changes ought to fix this: https://android-review.googlesource.com/#/q/topic:fix-static-exe

Awaiting review, but unless further testing finds any issues with it this should be good to go for r13.

@chenxiaolong: It's not *quite* all static executables that are broken. If you can target something lower than android-21 then it will build fine. Is that workaround sufficient for you?

**Comment by chenxiaolong** [comment]
@DanAlbert Thanks for the fixes! I won't be able to compile and test until after I return from my business trip on Wednesday though.

Unfortunately, I can't use anything lower than android-21 because I need the xattr functions (fsetxattr, fgetxattr, etc.).

**Comment by DanAlbert** [comment]
Changes are submitted.

**Comment by arielmingrone** [comment]
I have this problem with platform 24 in r14b compiling ffmpeg libs into static one
external/jemalloc/src/jemalloc.c:707: error: undefined reference to 'atexit'
external/jemalloc/src/prof.c:1377: error: undefined reference to 'atexit'
Maybe you can help?
