### ISSUE TITLE
make_standalone_toolchain.py is broken under Python 3

### ISSUE THREAD

**Issue by tavianator** [android-ndk/ndk#134]
On systems where `/usr/bin/python` is Python 3 (Arch Linux only?), `make_standalone_toolchain.py` crashes in the following way:

```
$ /opt/android-ndk/build/tools/make_standalone_toolchain.py --arch=arm --api=19 --install-dir=/tmp/ndk-arm
Traceback (most recent call last):
  File "/opt/android-ndk/build/tools/make_standalone_toolchain.py", line 580, in <module>
    main()
  File "/opt/android-ndk/build/tools/make_standalone_toolchain.py", line 529, in main
    elif args.verbose >= 2:
TypeError: unorderable types: NoneType() >= int()
```

Explicitly running with `python2`, or oddly enough, passing `-v`, works around it.

**Comment by DanAlbert** [comment]
https://android-review.googlesource.com/243580

Heh, interesting. Passing `-v` fixed it because it's only the *ordering* comparisons that are disallowed, so the `>=` check was never executed because it was `== 1`.

**Comment by DanAlbert** [comment]
Fix is in. It'll be available in r13 starting with beta 1.
