### ISSUE TITLE
[r12] release notes list wrong platforms and docs link to non-existent extraction help

### ISSUE THREAD

**Issue by joakim-noah** [android-ndk/ndk#136]
The release notes for r12 say "Removed all sysroots for platform levels prior to Android 2.3 (API level 10)," but in the linux zip, I see `android-9` and then `android-12` and up, no `android-10`.  Unless `unzip` failed me somehow, the platforms need to be changed.

Also, [the Setup guide has a link on how to extract the NDK](https://developer.android.com/ndk/guides/setup.html#install), which goes nowhere now.  I know most will know how to unzip it, but given the NDK has used various different extraction methods in the past, I think it's best that it's documented, particularly for the few noobs that will try it.

**Comment by DanAlbert** [comment]
Thanks for the reports. Sent the CLs yesterday, and it looks like they went live today.
