### ISSUE TITLE
cmake find_path doesn't work

### ISSUE THREAD

**Issue by graph** [android-ndk/ndk#138]
basic example:
NDK R12

```
cmake_minimum_required(VERSION 3.4.1)



if(NOT "${CMAKE_BUILD_TYPE}")
    set(CMAKE_BUILD_TYPE Debug CACHE STRING "only Release/Debug" FORCE)
endif()

project (hello)

find_path(OGRE_INCLUDE_DIR_TEST NAMES "OgreRoot.h" HINTS "/Users/ben/Documents/android/libIconmobile-BeardAR-android/ogreCompiled/x86_64/include/OGRE")
message("test in main = ${OGRE_INCLUDE_DIR_TEST}")
```

It works if I use the cmake binary provided by android. But not if I run it Android Studio Preview 4. Once Android Studio Preview 4 sets up the build directory command line attempts also fails. I have no idea why.

**Comment by DanAlbert** [comment]
The NDK actually doesn't include cmake; that comes from Android Studio. Could you file a bug for them at http://b.android.com?

**Comment by DanAlbert** [comment]
Definitely looks like something specific to Android Studio. Could you file a bug for them at http://b.android.com? This is only for the NDK itself (`ndk-build`, compilers, and libraries).

**Comment by graph** [comment]
ok under which category is best to file this under?

**Comment by DanAlbert** [comment]
> ok under which category is best to file this under?

Sorry, I should have given you this link too: http://tools.android.com/filing-bugs

It'll help you get it filed in the right place.

**Comment by graph** [comment]
Ok thank you. This is like in between NDK/Android Studio  in the supplied cmake tools. I have [submitted here](https://code.google.com/p/android/issues/detail?id=214409&thanks=214409&ts=1467058195)

**Comment by graph** [comment]
I made a mistake can my issue be deleted and I recreate it? it contains some important data I don't want in it.

**Comment by graph** [comment]
https://code.google.com/p/android/issues/detail?id=214409&thanks=214409&ts=1467058195

**Comment by DanAlbert** [comment]
Done.

**Comment by graph** [comment]
Thank you,

I have recreated the issue https://code.google.com/p/android/issues/detail?id=214412&thanks=214412&ts=1467059828
