### ISSUE TITLE
undefined reference to ‘__cxa_bad_typeid'

### ISSUE THREAD

**Issue by kmshih** [android-ndk/ndk#140]
With clang and libc++; gnustl works fine (So I'm guessing this is one of the outstanding issues with libc++ that may or may not be known?):

Error comes from:
clang++ -ggdb -fexceptions -frtti -fvisibility=hidden -std=gnu++14 -fno-omit-frame-pointer -mno-sse -O0 -fno-strict-aliasing -Wall -Wno-format-security -Wno-missing-braces -Wno-unknown-pragmas -Winvalid-pch -Werror=vla -isystem"/Work/formulas/native/ThirdParty/boost" -include /Work/formulas/native/build/android-x86/debug/smsheet/src/stdpch.h -Wl,--fix-cortex-a8 -Wl,--threads -Wl,--build-id -Wl,-z,noexecstack -Wl,-z,relro -shared -Wl,-shared,-Bsymbolic -Wl,--unresolved-symbols=report-all -Lbuild/android-x86/debug/lib -o build/android-x86/debug/bin/libsmsheet-test.so <...long list of .o files here...> -Wl,-Bstatic -lstdc++ -latomic  -lsmcore -lboost -ldoubleconversion -lsmjni -Wl,-Bdynamic -llog -ldl

**Comment by DanAlbert** [comment]
https://android-review.googlesource.com/#/c/239260/

r12b has the fix.
