### ISSUE TITLE
HardFloatAbi.md link in the r12 changelog does not exist

### ISSUE THREAD

**Issue by froydnj** [android-ndk/ndk#141]
The [r12 changelog](https://github.com/android-ndk/ndk/wiki/Changelog-r12), section "NDK", first bullet point, has a purported link to documentation that explains why the hard-float ABI has been removed.  The [target of that link](https://github.com/android-ndk/ndk/wiki/docs/HardFloatAbi.md), `HardFloatAbi.md` on the wiki, doesn't seem to exist, instead redirecting one to the homepage of the wiki.  The `docs/` subdirectory of the project doesn't seem to have a `HardFloatAbi.md` file either, so I'm not entirely sure where the explanation is supposed to reside.

**Comment by DanAlbert** [comment]
Sorry about that. It's a valid link in the git repository, but I have to manually fixup links whenever something makes it into the wiki (should probably toss the wiki and turn it into a github sites page or something).

I'll get the wiki fixed, but in the meantime the doc is here: https://android.googlesource.com/platform/ndk/+/master/docs/HardFloatAbi.md

**Comment by DanAlbert** [comment]
Okay, wiki is fixed.

**Comment by froydnj** [comment]
Thank you!  We've been having questions about why the hard-float ABI shouldn't be used, and the doc is a helpful reference to point people too.  ("It's not supported by the NDK" is also a good reason, I suppose...)
