### ISSUE TITLE
__NDK_FPABI__  is not empty for -mfloat-abi=softfp in r12

### ISSUE THREAD

**Issue by bog-dan-ro** [android-ndk/ndk#142]
As described in #32 ```__NDK_FPABI__``` is still defined as ```__attribute__((pcs("aapcs")))``` for ```-mfloat-abi=softfp```

**Comment by enh** [comment]
is that causing you problems? we haven't gone back and cleaned up the old header files. r13 should have the unified headers which won't contain any of this (since it was never in the platform at all).

**Comment by bog-dan-ro** [comment]
Yes, this is causing some problems, I came with an ugly workaround https://codereview.qt-project.org/#/c/160450/ but a proper fix from NDK will be nicer.

What do you mean by **unified headers** in r13? Please don't tell me that you are going to break the current NDK layout :) .

**Comment by enh** [comment]
see issue #120 for more on unified headers.

**Comment by bog-dan-ro** [comment]
Is this issue fixed in r13 beta1 ?

**Comment by DanAlbert** [comment]
No, but a change is in for beta 2. https://android-review.googlesource.com/#/c/248156/

Though, I just grepped in the sources to check, and it looks like I missed some. I'll get those now.

**Comment by bog-dan-ro** [comment]
I can confirm that beta 2 fixed the problem.
Thanks!
