### ISSUE TITLE
Problems migrating from gcc to clang with OpenSSL assembler files

### ISSUE THREAD

**Issue by schwabe** [android-ndk/ndk#144]
Hi,

my project (@schwabe/ics-openvpn) is using an embedded OpenSSL. Compiling with gcc works fine but with Clang it seems not to recognize the special instructions that crypto instructions are allowed to use and then fails when said instructions are used.

``[arm64-v8a] Compile        : crypto <= armcap.c
openssl/crypto/arm64cpuid.S:4:1: error: unknown directive
.arch armv8-a+crypto
^
openssl/crypto/arm64cpuid.S:24:2: error: instruction requires: crypto
 aese v0.16b, v0.16b
 ^
openssl/crypto/arm64cpuid.S:31:2: error: instruction requires: crypto
 sha1h s0, s0
 ^
openssl/crypto/arm64cpuid.S:38:2: error: instruction requires: crypto
 sha256su0 v0.4s, v0.4s
 ^
openssl/crypto/arm64cpuid.S:44:2: error: instruction requires: crypto
 pmull v0.1q, v0.1d, v0.1d
 ^
make: *** [obj/local/arm64-v8a/objs/crypto/crypto/arm64cpuid.o] Error 1
make: *** Waiting for unfinished jobs....
```

**Comment by kneth** [comment]
I have also tried to compile OpenSSL (1.0.1 series) using clang for one of my component some time ago. As I recall, the file named `Configure` only contains gcc relevant build options. Furthermore, calling `makedepend` is very noisy for Android as `-mandroid` is set. I ended up doing a ugly hack as described in my comment in https://github.com/openssl/openssl/issues/221.

Please also consider that OpenSSL is using `-O3` for the builds, while that optimization level might be buggy (see #110).

**Comment by DanAlbert** [comment]
Are you passing `-fno-integrated-assembler` when using clang? If not, you'll want to do that. `ndk-build` does that by default, but I suspect you're using something like a standalone toolchain for building openssl.

The integrated assembler in clang is really not intended for hand written assembly; it's purpose is just for assembling the code that the compiler generates. `-fno-integrated-assembler` will instruct clang to use GAS instead.

**Comment by schwabe** [comment]
@DanAlbert  I am using (modified) Android build files that originate from the original AOSP build files. The call is acutally quite long and is:

```
/Users/arne/oss/android-ndk-r12/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang -MMD -MP -MF ./obj/local/arm64-v8a/objs/crypto/crypto/aes/asm/aesv8-armx-64.o.d -gcc-toolchain /Users/arne/oss/android-ndk-r12/toolchains/aarch64-linux-android-4.9/prebuilt/darwin-x86_64 -target aarch64-none-linux-android -ffunction-sections -funwind-tables -fstack-protector-strong -fpic -Wno-invalid-command-line-argument -Wno-unused-command-line-argument -no-canonical-prefixes  -g -O2 -DNDEBUG  -Iopenssl/. -Iopenssl/crypto -Iopenssl/crypto/asn1 -Iopenssl/crypto/evp -Iopenssl/crypto/modes -Iopenssl/include -Iopenssl/include/openssl -Iopenssl -DANDROID -DNO_WINDOWS_BRAINDEATH -Wno-missing-field-initializers -Wno-unused-parameter -DDES_UNROLL -DOPENSSL_CPUID_OBJ -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DOPENSSL_THREADS -D_REENTRANT -DL_ENDIAN -DOPENSSL_NO_CAMELLIA -DOPENSSL_NO_CAPIENG -DOPENSSL_NO_CAST -DOPENSSL_NO_DTLS -DOPENSSL_NO_DTLS1 -DOPENSSL_NO_EC_NISTP_64_GCC_128 -DOPENSSL_NO_GMP -DOPENSSL_NO_GOST -DOPENSSL_NO_HEARTBEATS -DOPENSSL_NO_IDEA -DOPENSSL_NO_JPAKE -DOPENSSL_NO_LIBUNBOUND -DOPENSSL_NO_MD2 -DOPENSSL_NO_MDC2 -DOPENSSL_NO_RC5 -DOPENSSL_NO_RDRAND -DOPENSSL_NO_RFC3779 -DOPENSSL_NO_RIPEMD -DOPENSSL_NO_RSAX -DOPENSSL_NO_SCTP -DOPENSSL_NO_SEED -DOPENSSL_NO_SHA0 -DOPENSSL_NO_SSL_TRACE -DOPENSSL_NO_SSL2 -DOPENSSL_NO_SSL3 -DOPENSSL_NO_STATIC_ENGINE -DOPENSSL_NO_STORE -DOPENSSL_NO_UNIT_TEST -DOPENSSL_NO_WEAK_SSL_CIPHERS -DOPENSSL_NO_WHIRLPOOL -DOPENSSLDIR="\"/system/lib/ssl\"" -DENGINESDIR="\"/system/lib/ssl/engines\"" -DOPENSSL_THREADS -D_REENTRANT -DDSO_DLFCN -DHAVE_DLFCN_H -DL_ENDIAN -DOPENSSL_NO_CAMELLIA -DOPENSSL_NO_CAPIENG -DOPENSSL_NO_CAST -DOPENSSL_NO_DTLS -DOPENSSL_NO_DTLS1 -DOPENSSL_NO_EC_NISTP_64_GCC_128 -DOPENSSL_NO_GMP -DOPENSSL_NO_GOST -DOPENSSL_NO_HEARTBEATS -DOPENSSL_NO_IDEA -DOPENSSL_NO_JPAKE -DOPENSSL_NO_LIBUNBOUND -DOPENSSL_NO_MD2 -DOPENSSL_NO_MDC2 -DOPENSSL_NO_RC5 -DOPENSSL_NO_RDRAND -DOPENSSL_NO_RFC3779 -DOPENSSL_NO_RIPEMD -DOPENSSL_NO_RSAX -DOPENSSL_NO_SCTP -DOPENSSL_NO_SEED -DOPENSSL_NO_SHA0 -DOPENSSL_NO_SSL_TRACE -DOPENSSL_NO_SSL2 -DOPENSSL_NO_SSL3 -DOPENSSL_NO_STATIC_ENGINE -DOPENSSL_NO_STORE -DOPENSSL_NO_UNIT_TEST -DOPENSSL_NO_WEAK_SSL_CIPHERS -DOPENSSL_NO_WHIRLPOOL -DOPENSSLDIR="\"/system/lib/ssl\"" -DENGINESDIR="\"/system/lib/ssl/engines\"" -DOPENSSLDIR="\"/system/lib/ssl\"" -DENGINESDIR="\"/system/lib/ssl/engines\"" -Wa,--noexecstack -Wformat -Werror=format-security    -isystem /Users/arne/oss/android-ndk-r12/platforms/android-21/arch-arm64/usr/include -c  openssl/crypto/aes/asm/aesv8-armx-64.S -o ./obj/local/arm64-v8a/objs/crypto/crypto/aes/asm/aesv8-armx-64.o 
```

**Comment by DanAlbert** [comment]
Looks like we don't enable that by default for aarch64. I'll fix that (and check the other architectures while I'm there).

FYI, the openssl in aosp is no longer maintained. We've moved on to boringssl, as has the rest of Google.

**Comment by schwabe** [comment]
@DanAlbert thanks. I know that openssl in aosp is no longer maintained, I ended up fixing and maintaining the makefiles myself (but might move to mbed tls eventually).

Actually ``-fno-integrated-as`` works on armv8 but breaks openssl on armeabi with an error of unknown assembler commands but works without ``-fno-integrated-as``.  So I guess openssl is probably not something that will work out of the box without a lot of fiddling around.

**Comment by DanAlbert** [comment]
> but breaks openssl on armeabi with an error of unknown assembler commands but works without -fno-integrated-as

Hmm. Maybe I shouldn't make the build system change then. I'm going to drop that patch and close this bug then, since it seems to be something that needs to be decided on a case-by-case basis.

> @DanAlbert thanks. I know that openssl in aosp is no longer maintained, I ended up fixing and maintaining the makefiles myself (but might move to mbed tls eventually).

The makefiles aren't your biggest problem. Openssl is a very security sensitive library (remember heartbleed) and since that source isn't being updated your application and your users will be vulnerable.

**Comment by schwabe** [comment]
@DanAlbert with makefile updating I meant updating them to the newest version, OpenVPN for Android ships with OpenSSL 1.0.2h.

**Comment by schwabe** [comment]
Could be possible to have different flags for .S and .c files in one the next ndk build or support ASFLAGS? .asm files get the ASM_FLAGS. I manually patched my /build/core/definitions.mk for that but that is not very nice solution

BoringSSL in the Android AOSP build also uses LOCAL_CLANG_ASFLAGS to have different flags for the .S files than .c (https://android.googlesource.com/platform/external/boringssl/+/master/Android.mk)

**Comment by DanAlbert** [comment]
Huh. Our handling of assembly files is weird.

I think the right thing to do here is add a `LOCAL_ASFLAGS` in addition to `LOCAL_ASMFLAGS`. `.asm` files get passed directly to the assembler rather than to the C compiler, and they don't necessarily support the same set of flags.

So `LOCAL_ASFLAGS` would be passed for `.S`/`.s`, and `LOCAL_ASMFLAGS` would be passed for `.asm`. Sound right to you?
