### ISSUE TITLE
Can't use libc++_static using the standalone toolchains using NDK r12b

### ISSUE THREAD

**Issue by chri7325** [android-ndk/ndk#145]
We have a large project that uses Android.mk as well as the standalone toolchains with make.  We are migrating our compiler from GCC 4.9 to clang38.  Using the android makefiles, we just switch to c++_static and our library that is produced has a dependency on libstdc++.so (I think there is already an issue for that).  However, when using the standalone toolchain and adding -lc++_static -lc++abi, the linker completes just fine but the dependency seems to be linked to using the libc++_shared.so.  If that library isn't there with the app, our app crashes.  I don't want to add the c++_shared lib as a dependency but I can't seem to exclude it.  The command I used to extract the standalone toolchain is
```
python make_standalone_toolchain.py --arch=arm --api=16 --install-dir=~/toolchain --stl=libc++
```

**Comment by DanAlbert** [comment]
> However, when using the standalone toolchain and adding -lc++_static -lc++abi

The standalone toolchains are now much less stupid. They should work more like a normal toolchain now. Just use `-static-libstdc++` instead of the `-lc++_static -lc++abi -levenmorelibs` mess and it'll do the right thing.

If you're using the shared libc++ you don't need `-lc++_shared` any more either. Just invoke the compiler normally.

**Comment by chri7325** [comment]
:+1: That did the trick! I didn't see that option in the linker though.  Is there another place that has the help on that so I can reference it when I add that ld flag?

**Comment by DanAlbert** [comment]
It's a compiler option, not linker (linkers have very dumb drivers and mostly just do what the compiler tells them).

https://gcc.gnu.org/onlinedocs/gcc/Link-Options.html

The option is also supported by clang, but the clang documentation is lacking to put it likely. High level options like that one are generally going to be supported in clang though, so for the most part you can follow the GCC docs when it comes to Clang options.
