### ISSUE TITLE
linux-x86/bin/arm-linux-androideabi-gcc: Command not found

### ISSUE THREAD

**Issue by smaznet** [android-ndk/ndk#146]
i have this error with ndk 11

```
[armeabi-v7a] Compile thumb  : test <= test.c
make: /opt/android-ndk-r11c/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86/bin/arm-linux-androideabi-gcc: Command not found
/opt/android-ndk-r11c/build/core/build-binary.mk:460: recipe for target '/home/xxxx/Desktop/AndroidStudioProjects/xxx/xxx/app/src/main/obj/local/armeabi-v7a/objs/test/test.o' failed
make: *** [/home/xxxx/Desktop/AndroidStudioProjects/xxx/xx/app/src/main/obj/local/armeabi-v7a/objs/test/test.o] Error 127
```

and I am using ubuntu 16.04 x86

and linux-x86 for not availiable in prebuilt folder i also coppied and renamed linux-x86_x64
 to linux-x86 but i got a new error

**Comment by smaznet** [comment]
```
com.intellij.execution.ExecutionException: Compiler exited with error code 2: /opt/android-ndk-r11c/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64/bin/aarch64-linux-android-gcc -xc -v -dD -E
           /opt/android-ndk-r11c/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64/bin/aarch64-linux-android-gcc: 3: /opt/android-ndk-r11c/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64/bin/aarch64-linux-android-gcc: Syntax error: ")" unexpected
```


This is my error in android studio

**Comment by DanAlbert** [comment]
> and I am using ubuntu 16.04 x86

32-bit Linux is no longer supported. You'll have the same issue with new versions of the SDK tools as well.

**Comment by jk2K** [comment]
I am using Debian 8 x86_64,

I have this error with `android-ndk-r12b`
```
 /sdk/android-ndk-r12b/build/ndk-build: 143: /sdk/android-ndk-r12b/build/ndk-build: file: not found
/bin/sh: 1: file: not found
make: /sdk/android-ndk-r12b/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86/bin/aarch64-linux-android-g++: Command not found
```
I have `linux-x86_64` directory
```
root@cd4a6a5d5452:/sdk/android-ndk-r12b# ls toolchains/aarch64-linux-android-4.9/prebuilt/
linux-x86_64
```
What should I do ?

**Comment by akinaru** [comment]
I had this issue in a docker container. `file` command was missing as you can see from the error `file: not found`.

In `android-ndk-root/build/core/init.mk`, the architecture is checked with `file -L /bin/sh | grep 'x86[_-]64'` so if `file` is missing it chooses the default `x86`

**Comment by DanAlbert** [comment]
See https://github.com/android-ndk/ndk/issues/188

**Comment by nguyenxvn** [comment]
https://github.com/OnlyInAmerica/FFmpeg-Android/issues/5#issuecomment-533784577

**Comment by LovableFatty** [comment]
> i have this error with ndk 11
> 
> ```
> [armeabi-v7a] Compile thumb  : test <= test.c
> make: /opt/android-ndk-r11c/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86/bin/arm-linux-androideabi-gcc: Command not found
> /opt/android-ndk-r11c/build/core/build-binary.mk:460: recipe for target '/home/xxxx/Desktop/AndroidStudioProjects/xxx/xxx/app/src/main/obj/local/armeabi-v7a/objs/test/test.o' failed
> make: *** [/home/xxxx/Desktop/AndroidStudioProjects/xxx/xx/app/src/main/obj/local/armeabi-v7a/objs/test/test.o] Error 127
> ```
> 
> and I am using ubuntu 16.04 x86
> 
> and linux-x86 for not availiable in prebuilt folder i also coppied and renamed linux-x86_x64
> to linux-x86 but i got a new error

Having the same issue with NDK r18b. did you ever fix it?
![image](https://user-images.githubusercontent.com/31664445/88245394-e122f700-cc4b-11ea-96c2-51af25e72fd1.png)

**Comment by stephenhines** [comment]
The issue above is because you're missing a `/` in front of the `home` in your commands. It's looking for `home/...` instead of `/home/...`, which is why it can't find the tools.

**Comment by LovableFatty** [comment]
> The issue above is because you're missing a `/` in front of the `home` in your commands. It's looking for `home/...` instead of `/home/...`, which is why it can't find the tools.

![image](https://user-images.githubusercontent.com/31664445/88245631-b71e0480-cc4c-11ea-88f7-b4ef8f59e3ce.png)
![image](https://user-images.githubusercontent.com/31664445/88245650-c2713000-cc4c-11ea-93f0-4753442a6a5f.png)
![image](https://user-images.githubusercontent.com/31664445/88245670-cd2bc500-cc4c-11ea-9d57-413a2596ed19.png)

tried /home/ & HOME/ & /HOME/

**Comment by stephenhines** [comment]
The errors are actually showing you what is wrong. You need to make this `$HOME/Downloads/...` or `/home/noah/Downloads/...`. You keep adjusting it to something else that expands incorrectly.

**Comment by LovableFatty** [comment]
> The errors are actually showing you what is wrong. You need to make this `$HOME/Downloads/...` or `/home/noah/Downloads/...`. You keep adjusting it to something else that expands incorrectly.

Thanks for taking the time to explain it to me.
![image](https://user-images.githubusercontent.com/31664445/88246703-2517fb00-cc50-11ea-87c2-21c1e1c00666.png)
Any idea what I can do to fix these errors?
![image](https://user-images.githubusercontent.com/31664445/88246729-38c36180-cc50-11ea-8822-2ba768c3781c.png)

**Comment by stephenhines** [comment]
I think that those are GCC-specific flags that don't do anything with Clang. See https://github.com/android/ndk/issues/111#issuecomment-305501173 for where I've answered this before. Somewhere you must be passing these flags to Clang directly (either on purpose or by accident).

**Comment by LovableFatty** [comment]
> I think that those are GCC-specific flags that don't do anything with Clang. See [#111 (comment)](https://github.com/android/ndk/issues/111#issuecomment-305501173) for where I've answered this before. Somewhere you must be passing these flags to Clang directly (either on purpose or by accident).

I realized I wrote my make line wrong by having SUB_ARM=arm instead of SUB_ARCH=arm
My current error is the same as before...
![image](https://user-images.githubusercontent.com/31664445/88348535-8e584680-cd02-11ea-945a-12e9983be1ba.png)

**Comment by stephenhines** [comment]
You're working as `root` in the last message. You want to go back to your regular user account. It's expanding `$HOME` to `/root/` when you're running as root, which isn't where your tools live (back in the noah home dir).

**Comment by LovableFatty** [comment]
> You're working as `root` in the last message. You want to go back to your regular user account. It's expanding `$HOME` to `/root/` when you're running as root, which isn't where your tools live (back in the noah home dir).

![image](https://user-images.githubusercontent.com/31664445/88357246-7642f000-cd1f-11ea-8765-6c030d4ec6c7.png)
current problem. resolved the clang input issue by taking out a line according to #111. Tried a solution from http://patchwork.ozlabs.org/project/uboot/patch/1406750096-7281-7-git-send-email-jeroen@myspectrum.nl/
but it resulted in error as well

**Comment by stephenhines** [comment]
I'm not sure how old the kernel you are building is, but that patch is from 2014. Clang can be used to build any modern (i.e. within the last 3+ years) kernel without that patch. It does seem related to you having that patch, because it almost looks like the `->` is being misintrepreted as a single character when it really shouldn't be.

**Comment by LovableFatty** [comment]
> I'm not sure how old the kernel you are building is, but that patch is from 2014. Clang can be used to build any modern (i.e. within the last 3+ years) kernel without that patch. It does seem related to you having that patch, because it almost looks like the `->` is being misintrepreted as a single character when it really shouldn't be.

I'm running Goldfish 3.4 (https://android.googlesource.com/kernel/goldfish/+/android-goldfish-3.4) started 2012, last commit 2017.

**Comment by stephenhines** [comment]
There are newer sources than that for the goldfish kernel (https://android.googlesource.com/kernel/goldfish/+refs). I'd try 4.14 or maybe even 5.4 instead of a legacy version. As for the NDK, you really would be better off using the latest version (NDK r21d from https://developer.android.com/ndk/downloads).
