### ISSUE TITLE
aarch64-linux-android-ld doesn't ignore dependencies of shared libraries

### ISSUE THREAD

**Issue by AnthonyARM** [android-ndk/ndk#148]
When I build a library or program which links against a shared library (let's say "my_lib.so") the build fails if I don't link against my_lib's dependencies too which shouldn't happen (Especially if "my_lib" links against system libraries: it means having to pull all the libraries from a device). 

> || /work/toolchains/aarch64-linux-android-4.9/bin/../lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-> linux-android/bin/ld: warning: liblog.so, needed by android64-lib/my_lib.so, not found (try using -rpath or > -rpath-link)
> || android64-lib/my_lib.so: undefined reference to `__android_log_write'

I've tried various things such as -unresolved-symbols=ignore-in-shared-libs or
LOCAL_ALLOW_UNDEFINED := true in my Android.mk but this keeps happening.

The same project builds just fine for arm 32 bit.

I've tried with toolchains from both ndk-r10d and the latest one (r12b)

**Comment by DanAlbert** [comment]
> (Especially if "my_lib" links against system libraries: it means having to pull all the libraries from a device).

All the libraries that are available to apps are already in the NDK, it should be able to find them just fine. If you're linking against system libraries that *aren't* in the NDK, then I'd call this a feature. Your app won't load on N if you do that.

For the case of non-system libraries being unavailable, what's the use case where that happens? AIUI you shouldn't need to link all the same libraries as `my_lib.so`, it just needs to have all those libraries available via `-L` or `--sysroot`, which we should already be doing.

**Comment by AnthonyARM** [comment]
We're building native test applications during the development of our libraries.

There is no reason whatsoever why the application should know about the dependencies of the library it's linking against as this is an implementation detail (And it shouldn't be necessary to pull the libraries from the device in order to build the application).

The default GCC implementation copes with it just fine on Linux 32 and 64, and even android-32 works fine, somehow only aarch64 behaves differently.

IMHO the restriction should be enforced in the NDK or SDK depending on the targeted API level not by directly breaking the toolchain (At the moment, even the standalone toolchain doesn't work).

**Comment by DanAlbert** [comment]
If your libraries depend on libraries that you'd have to pull off the device (ones that aren't in the NDK) then the toolchain is doing you a favor here. Your application is invalid.

The difference between aarch64 and arm (and x86 and x86_64) is that aarch64 is still using bfd. Does the problem go away if you use `-fuse-ld=gold`?

You should still consider the other part of what I'm saying though. If the libraries in the NDK are not sufficient to build your app then your app will be broken on newer releases.

**Comment by 4eVEROMAP** [comment]
Hello @DanAlbert ,
I am faced with this problem too. 
I'm using a standalone toolchain generated from NDK r12b. I created a simple example to demonstrate the problem:
foo.c:
```c
#include<math.h>

double foo(double a) {

   return sin(a);
}
```
main.c:
```c
#include <stdio.h>
double foo(double);
int main(int argc, char **argv){
   double a = argc * 0.2;
   printf("foo(%d)=%f\n",argc, (float)foo(a));
   return 0;
}
```
Makefile:
```Makefile
CCC=/standalone_toolchains/r12b_android-21_arm64_libc++/bin/aarch64-linux-android-gcc
#CCC=/standalone_toolchains/r12b_android-21_arm_libc++/bin/arm-linux-androideabi-gcc
#CCC=gcc
#USE_GOLD=-fuse-ld=gold
all: main
libfoo.so: foo.c
	$(CCC) -O0 --shared -o libfoo.so foo.c -fPIC -lm

main: main.c libfoo.so
	$(CCC) -o main main.c -L. -lfoo $(USE_GOLD)


clean:
	rm -f main libfoo.so
```
If I compile the example with arm-linux-androideabi-gcc or native gcc it works.
If I use the aarch64-linux-android-gcc with linker flag -fuse-ld=gold it works too.
It works if I add the dependency explicitly (-lm).  
With aarch64-linux-android-gcc and without -fuse-ld=gold it fails with following error:
```
/standalone_toolchains/r12b_android-21_arm64_libc++/bin/aarch64-linux-android-gcc -O0 --shared -o libfoo.so foo.c -fPIC -lm
/standalone_toolchains/r12b_android-21_arm64_libc++/bin/aarch64-linux-android-gcc -o main main.c -L. -lfoo 
/standalone_toolchains/r12b_android-21_arm64_libc++/bin/../lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/bin/ld: warning: libm.so, needed by ./libfoo.so, not found (try using -rpath or -rpath-link)
./libfoo.so: undefined reference to `sin@LIBC'
collect2: error: ld returned 1 exit status
make: *** [main] Error 1
```
Verbose linker output:
[linker_verbose.txt](https://github.com/android-ndk/ndk/files/502765/linker_verbose.txt)
Verbose linker output  (with -fuse-ld=gold):
[linker_verbose_gold.txt](https://github.com/android-ndk/ndk/files/502767/linker_verbose_gold.txt)
The gold-linker seems not to look for libm.so
readelf -d libfoo.so| grep NEEDED
```
 0x0000000000000001 (NEEDED)             Shared library: [libm.so]
 0x0000000000000001 (NEEDED)             Shared library: [libc.so]
 0x0000000000000001 (NEEDED)             Shared library: [libdl.so]
```

**Comment by DanAlbert** [comment]
Ah, thanks! That's something I can work with.

I wonder why it can't find libm. It's on the same path as libc and it's not having trouble linking that. Whatever the case, I'll take a look.

One thing we might do here is just switch aarch64 over to gold. I don't think there have been any issues with that for quite a while now.

**Comment by brian-armstrong** [comment]
I'd like to chime in here. I'm having the exact same problem, that libm.so cannot be found. I'm using a standalone toolchain targeting arm64-v8a on API 21.

I'm ashamed to admit that my linker skills are not especially strong. Is there any easy workaround that will get my toolchain to produce build artifacts? It sounds like adding -fuse-ld=gold might be an easy fix?

**Comment by brian-armstrong** [comment]
I spoke too soon - I should have just tried it. I can confirm that adding `-fuse-ld=gold` gets my build working.

**Comment by fornwall** [comment]
> One thing we might do here is just switch aarch64 over to gold. I don't think there have been any issues with that for quite a while now.

@DanAlbert Do you know of any problem with gold on aarch64, or is this still the plan?

**Comment by enh** [comment]
build/soong/cc/config/arm64_device.go:66 says we're using gold on aarch64 for the platform build...

**Comment by rerlanggas** [comment]
@brian-armstrong where i adding -fuse-ld=gold ?

**Comment by enh** [comment]
(the only arm64 gold bug i'm aware of is that there's a problem with generating useful debug info for static binaries. there's an arm32 gold bug that causes failures to link with some tail calls. but we're still using gold for the platform builds.)

**Comment by DanAlbert** [comment]
I'm guessing bfd won't get fixed and this will be "solved" by moving to gold once the debug info issue is fixed.
