### ISSUE TITLE
Precompiled header is not compiled on LOCAL_ARM_MODE = arm

### ISSUE THREAD

**Issue by ibis-onyk** [android-ndk/ndk#149]
I'm using Android Studio 2.1.2 and NDK for developing Android app on Mac El Capitan.
I'm using a precompiled header in native program.
After I upgraded NDK from r11c to r12b, I have a problem.
The precompiled header is not compiled if I add "LOCAL_ARM_MODE := arm" into Android.mk.
This problem occurs on r12 and r12b but doesn't occur in r11c.
I created a simple app to test this problem: https://github.com/ibis-onyk/NdkLocalArmModeTest
Is my code wrong? Or a bug of NDK?

**Comment by DanAlbert** [comment]
Fix is up for review: https://android-review.googlesource.com/245808

Thanks for the report. Seems our PCH improvements in r12 broke some other cases.

**Comment by ibis-onyk** [comment]
Thank you for your reply and answer.
I'm looking forward to the release of NDK r13.

**Comment by DanAlbert** [comment]
Change was submitted.
