### ISSUE TITLE
Unknown symbols generated by clang r12b, works fine with gcc-4.9 r12b and clang r12

### ISSUE THREAD

**Issue by koral--** [android-ndk/ndk#153]
This project https://github.com/koral--/android-gif-drawable/tree/dev compiles fine with clang r12b but native library loading fails at runtime with `UnsatisfiedLinkError: dlopen failed: cannot locate symbol "__aeabi_memcpy"`.
As mentioned in title issue is specific to clang r12b, it seems that other configurations (clang in different ndk version or different toolchain from r12b) are unaffected.
Error occurs on HTC One M8 which is armeabi-v7a, not tested yet with other ABIs.

Here are the most relevant files:
[Android.mk](https://github.com/koral--/android-gif-drawable/blob/dev/src/main/jni/Android.mk)
[Application.mk](https://github.com/koral--/android-gif-drawable/blob/dev/src/main/jni/Application.mk)

**Comment by DanAlbert** [comment]
Most likely this is a dup of https://github.com/android-ndk/ndk/issues/126

**Comment by koral--** [comment]
Right, thanks.
