### ISSUE TITLE
Intellij ExecutionException

### ISSUE THREAD

**Issue by SinghKaranbir** [android-ndk/ndk#155]
I updated my Android Studio to 2.2 preview 5 and it keeps on giving me execution exception. I haven't changed the code. Now Code Completion for C files is not working and It cannot resolve the JNI types.

it gives following in event log. 
 
com.intellij.execution.ExecutionException: Compiler exited with error code 1: /Users/karanbir/Library/Android/sdk/ndk-bundle/toolchains/aarch64-linux-android-4.9/prebuilt/darwin-x86_64/bin/aarch64-linux-android-gcc -xc -MP -fpic -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -g -O2 -DNDEBUG -I/Users/karanbir/Documents/AndroidStudioProjects/Production/VideoJoiner/app/src/main/jni -DANDROID -Wa,--noexecstack -Wformat -Werror=format-security -isystem /Users/karanbir/Library/Android/sdk/ndk-bundle/platforms/android-21/arch-arm64/usr/include -v -dD -E Using built-in specs. COLLECT_GCC=/Users/karanbir/Library/Android/sdk/ndk-bundle/toolchains/aarch64-linux-android-4.9/prebuilt/darwin-x86_64/bin/aarch64-linux-android-gcc Target: aarch64-linux-android Configured with: /Volumes/Android/buildbot/src/android/gcc/toolchain/build/../gcc/gcc-4.9/configure --prefix=/tmp/118a072655ec599826c2fad30bdf4c73 --target=aarch64-linux-android --host=x86_64-apple-darwin --build=x86_64-apple-darwin --with-gnu-as --with-gnu-ld --enable-languages=c,c++ --with-gmp=/buildbot/tmp/build/toolchain/temp-install --with-mpfr=/buildbot/tmp/build/toolchain/temp-install --with-mpc=/buildbot/tmp/build/toolchain/temp-install --with-cloog=/buildbot/tmp/build/toolchain/temp-install --with-isl=/buildbot/tmp/build/toolchain/temp-install --with-ppl=/buildbot/tmp/build/toolchain/temp-install --disable-ppl-version-check --disable-cloog-version-check --disable-isl-version-check --enable-cloog-backend=isl --with-host-libstdcxx='-static-libgcc -lstdc++ -lm' --disable-libssp --enable-threads --disable-nls --disable-libmudflap --disable-libgomp --disable-libstdc__-v3 --disable-sjlj-exceptions --disable-shared --disable-tls --disable-libitm --enable-bionic-libs --enable-libatomic-ifuncs=no --enable-initfini-array --disable-nls --prefix=/tmp/118a072655ec599826c2fad30bdf4c73 --with-sysroot=/tmp/118a072655ec599826c2fad30bdf4c73/sysroot --with-binutils-version=2.25 --with-mpfr-version=3.1.1 --with-mpc-version=1.0.1 --with-gmp-version=5.0.5 --with-gcc-version=4.9 --with-gdb-version=none --with-gxx-include-dir=/tmp/118a072655ec599826c2fad30bdf4c73/include/c++/4.9.x --with-bugurl=http://source.android.com/source/report-bugs.html --enable-languages=c,c++ --disable-bootstrap --enable-plugins --enable-libgomp --enable-gnu-indirect-function --disable-libsanitizer --enable-gold --enable-ld=default --enable-threads --enable-eh-frame-hdr-for-static --enable-fix-cortex-a53-835769 --enable-graphite=yes --with-isl-version=0.11.1 --with-cloog-version=0.18.0 --program-transform-name='s&^&aarch64-linux-android-&' --enable-gold Thread model: posix gcc version 4.9.x 20150123 (prerelease) (GCC) COLLECT_GCC_OPTIONS='-MP' '-fpic' '-ffunction-sections' '-funwind-tables' '-fstack-protector-strong' '-g' '-O2' '-D' 'NDEBUG' '-I' '/Users/karanbir/Documents/AndroidStudioProjects/Production/VideoJoiner/app/src/main/jni' '-D' 'ANDROID' '-Wformat=1' '-Werror=format-security' '-isystem' '/Users/karanbir/Library/Android/sdk/ndk-bundle/platforms/android-21/arch-arm64/usr/include' '-v' '-dD' '-E' '-D' '___CIDR_IGNORE_DEFINITIONS_START' '-mlittle-endian' '-mabi=lp64' /Users/karanbir/Library/Android/sdk/ndk-bundle/toolchains/aarch64-linux-android-4.9/prebuilt/darwin-x86_64/bin/../libexec/gcc/aarch64-linux-android/4.9.x/cc1 -E -quiet -v -I /Users/karanbir/Documents/AndroidStudioProjects/Production/VideoJoiner/app/src/main/jni -iprefix /Users/karanbir/Library/Android/sdk/ndk-bundle/toolchains/aarch64-linux-android-4.9/prebuilt/darwin-x86_64/bin/../lib/gcc/aarch64-linux-android/4.9.x/ -MP -D NDEBUG -D ANDROID -D ___CIDR_IGNORE_DEFINITIONS_START -isystem /Users/karanbir/Library/Android/sdk/ndk-bundle/platforms/android-21/arch-arm64/usr/include /private/var/folders/w6/_k4hnb0d3qb8gwxrspl_nty80000gn/T/compiler-file2 -mbionic -mlittle-endian -mabi=lp64 -Wformat=1 -Werror=format-security -fpic -ffunction-sections -funwind-tables -fstack-protector-strong -g -fworking-directory -O2 -dD cc1: error: to generate dependencies you must specify either -M or -MM ignoring nonexistent directory "/Users/karanbir/Library/Android/sdk/ndk-bundle/toolchains/aarch64-linux-android-4.9/prebuilt/darwin-x86_64/bin/../lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/include" ignoring duplicate directory "/Users/karanbir/Library/Android/sdk/ndk-bundle/toolchains/aarch64-linux-android-4.9/prebuilt/darwin-x86_64/bin/../lib/gcc/../../lib/gcc/aarch64-linux-android/4.9.x/include" ignoring nonexistent directory "/tmp/118a072655ec599826c2fad30bdf4c73/sysroot/usr/local/include" ignoring duplicate directory "/Users/karanbir/Library/Android/sdk/ndk-bundle/toolchains/aarch64-linux-android-4.9/prebuilt/darwin-x86_64/bin/../lib/gcc/../../lib/gcc/aarch64-linux-android/4.9.x/include-fixed" ignoring nonexistent directory "/Users/karanbir/Library/Android/sdk/ndk-bundle/toolchains/aarch64-linux-android-4.9/prebuilt/darwin-x86_64/bin/../lib/gcc/../../lib/gcc/aarch64-linux-android/4.9.x/../../../../aarch64-linux-android/include" ignoring nonexistent directory "/tmp/118a072655ec599826c2fad30bdf4c73/sysroot/usr/include" #include "..." search starts here: #include ...> search starts here: /Users/karanbir/Documents/AndroidStudioProjects/Production/VideoJoiner/app/src/main/jni /Users/karanbir/Library/Android/sdk/ndk-bundle/platforms/android-21/arch-arm64/usr/include /Users/karanbir/Library/Android/sdk/ndk-bundle/toolchains/aarch64-linux-android-4.9/prebuilt/darwin-x86_64/bin/../lib/gcc/aarch64-linux-android/4.9.x/include /Users/karanbir/Library/Android/sdk/ndk-bundle/toolchains/aarch64-linux-android-4.9/prebuilt/darwin-x86_64/bin/../lib/gcc/aarch64-linux-android/4.9.x/include-fixed End of search list.

Android Studio Version 
: 2.2 Preview 5

NDK version
12.1.2977051

**Comment by DanAlbert** [comment]
Not an NDK issue. Please file against Android Studio at http://b.android.com.

**Comment by SinghKaranbir** [comment]
Thanks. I filed it at both android studio and Ndk
