### ISSUE TITLE
Clang does not recognize mips64el GCC lib directory structure, when building for mips32

### ISSUE THREAD

**Issue by NikolaVeljkovic-Img** [android-ndk/ndk#159]
When checking for lib path, it searches for `mips-r1`, instead of `32/mips-r1`. This leads to Clang not using provided GCC, and defaulting to host's AS.

Until resolved, using `$ clang --sysroot --gcc-toolchain` for mips32 will require an additional flag: 
`-L<mips64el-gcc-path>/lib/gcc/mips64el-linux-android/4.9.x/32/mips-r1`

Workaround for this is:
https://android-review.googlesource.com/247064

Clang bug is tracked on upstream by:
https://dmz-portal.mips.com/bugz/show_bug.cgi?id=2366

**Comment by LazarTrsic-Img** [comment]
This issue is resolved on the upstream (more details could be found on the Clang [bug](https://dmz-portal.mips.com/bugz/show_bug.cgi?id=2366)).
The patch that fixes the problem has been committed at [r275949](https://reviews.llvm.org/rL275949) and [r275951](https://reviews.llvm.org/rL275951).

**Comment by DanAlbert** [comment]
MIPS is deprecated as of r16.
