### ISSUE TITLE
Compile error when using clang and precompiled headers

### ISSUE THREAD

**Issue by DoDoENT** [android-ndk/ndk#16]
In my Application.mk I've set `NDK_TOOLCHAIN_VERSION=clang` and in Android.mk I've defined `LOCAL_PCH` to point header I wish to get precompiled.

With GCC (`NDK_TOOLCHAIN_VERSION` unset), project can be built successfully. With clang I get following errors:

```
clang++: error: treating 'c-header' input as 'c++-header' when in C++ mode, this behavior is deprecated
```

**Comment by DoDoENT** [comment]
It appears this can be fixed by adding following line to `$NDK_DIR/build/core/build-binary.mk`:

Around line 440, below comment `#Build PCH` and above `$(call compile-cpp-source,$(LOCAL_PCH),$(LOCAL_BUILT_PCH).gch)` add this line:

`LOCAL_SRC_FILES_TARGET_CFLAGS.$(LOCAL_PCH) += -x c++-header`

**Comment by DanAlbert** [comment]
Thanks again! Added a test case and uploaded for review: https://android-review.googlesource.com/208223
