### ISSUE TITLE
Error migrating from GCC to Clang - conversion function cannot be redeclared

### ISSUE THREAD

**Issue by 4brunu** [android-ndk/ndk#163]
Hi,

I have a project that uses C++ and I'm using [SQLiteCpp](https://github.com/SRombauts/SQLiteCpp) to manage the database.

Everything was working with GCC, but when I tried to migrate to Clang, I have the following error:
```
Information:Gradle tasks [:app:assembleDebug]
:app:compileExampleArm64-v8aDebugSharedLibraryExampleMainC
:app:compileExampleArm64-v8aDebugSharedLibraryExampleMainCpp
    inline operator int64_t() const
           ^
1 error generated.
    inline operator int64_t() const
           ^
1 error generated.
    inline operator int64_t() const
           ^
1 error generated.
    inline operator int64_t() const
           ^
1 error generated.
/Users/user/Developer/gcc_to_clang_sqlitecpp/deps/SQLiteCpp/include/SQLiteCpp/Column.h
Error:(189, 12) error: conversion function cannot be redeclared
Information:(176, 12) previous declaration is here
Error:(189, 12) error: conversion function cannot be redeclared
Error:(189, 12) error: conversion function cannot be redeclared
Error:(189, 12) error: conversion function cannot be redeclared
Error:(189, 12) error: conversion function cannot be redeclared
    inline operator int64_t() const
           ^
1 error generated.
Error:Execution failed for task ':app:compileExampleArm64-v8aDebugSharedLibraryExampleMainCpp'.
> Multiple build operations failed.
      C++ compiler failed while compiling Backup.cpp.
      C++ compiler failed while compiling Database.cpp.
      C++ compiler failed while compiling Column.cpp.
      C++ compiler failed while compiling Transaction.cpp.
      C++ compiler failed while compiling Statement.cpp.
  See the complete log at: file:///Users/user/Developer/gcc_to_clang_sqlitecpp/android_project/gcc_to_clang_sqlitecpp/app/build/tmp/compileExampleArm64-v8aDebugSharedLibraryExampleMainCpp/output.txt
Information:BUILD FAILED
Information:Total time: 6.205 secs
Information:6 errors
Information:0 warnings
Information:See complete output in console
```

I created a sample project to show my issue.
https://github.com/4brunu/gcc_to_clang_sqlitecpp

I'm using NDK r12b.
Am I doing something wrong, or it's a NDK bug?

**How to build the sample**
Open the Android Studio project, hit run, and you will get some errors.

Check this lines to change between Clang and GCC.
https://github.com/4brunu/gcc_to_clang_sqlitecpp/blob/master/android_project/gcc_to_clang_sqlitecpp/app/build.gradle#L56-L58

Thanks

**Comment by jmgao** [comment]
I'm inclined to think that this is a gcc bug (i.e. that this code shouldn't compile with either gcc or clang). It seems to be specific to inline conversion operators, [a non-inline version](https://godbolt.org/g/j1WFe4) fails to compile in gcc as well as clang and icc.

[The example code](https://github.com/4brunu/gcc_to_clang_sqlitecpp/blob/master/deps/SQLiteCpp/include/SQLiteCpp/Column.h#L174) seems a bit confused. I think what it really wants to do might be something along the lines of the following (but I've only looked at it for 30 seconds or so, so maybe not):

```
inline operator int() {
    return getInt();
}

inline operator long() {
#if sizeof(long) == 8
    return getInt64();
#else
    return getInt();
#endif
}

inline operator long long() {
    return getInt64();
}

inline operator unsigned() {
    return getUInt();
}

#if sizeof(unsigned long) == 4
inline operator unsigned long() {
    return getUInt();
}
#endif
```

I'll file upstream bugs tomorrow morning.

**Comment by 4brunu** [comment]
I'm not sure of that, because I'm using the same library in iOS apps, and Xcode that uses Clang, doesn't show any problem at all.

**Comment by DanAlbert** [comment]
Could be that Xcode is using an older version of Clang that doesn't have this diagnostic.

**Comment by jmgao** [comment]
That's because the check the library uses is `#if !defined(__x86_64__) || defined(__APPLE__)` to guard the definition of `operator long`. Android ARM64 is neither apple nor x86_64, so the function gets defined.

GCC bug filed at https://gcc.gnu.org/bugzilla/show_bug.cgi?id=71919

**Comment by 4brunu** [comment]
The problem is solved with the previous issue.

Thanks for the help.
