### ISSUE TITLE
ADB setprop doesnt work with Android N device attached

### ISSUE THREAD

**Issue by amuscalu2** [android-ndk/ndk#165]
Hello, I am trying to make sense of the following behavior that started with Android N.

While an Android N device (Nexus 5) is attached to the computer, I am trying to set some system properties with the following command:

adb.exe shell setprop myprop value1

There is no error displayed but the setting of the property doesn't get done. Running getprop gets no results.

Has anyone else encountered this error? I used to use this to set debugging levels and now I can't... The problem is not visible with a device not running Android N.

Thank you,
Adrian

**Comment by DanAlbert** [comment]
This isn't an NDK issue. Please file at http://b.android.com.
