### ISSUE TITLE
libc.so for NDK r12(b) platforms/android-19/arch-arm/ doesn't contain arc4random_stir function

### ISSUE THREAD

**Issue by timofey-retailnext** [android-ndk/ndk#166]
all arc4random* stuff exists in both libc.a and libc.so for {NDK-r10e}/platforms/android-19/arch-arm/usr/lib/libc.*
but in case of {NDK-r12} & {NDK-r12b} it exists only in .a version of the library.  .so version doesn't have at least one function: arc4random_stir, therefore I'm unable to build openssh that actively uses it.

**Comment by DanAlbert** [comment]
https://github.com/android-ndk/ndk/issues/42

**Comment by timofey-retailnext** [comment]
Thanks for explanation, 
are ther any specific reasons  why removed arc4random_* functions still exist in stdlib.h ?

ex. {NDK-r12b}/platforms/android-19/arch-arm/include/stdlib.h lines 119-120:
extern void arc4random_stir(void);
extern void arc4random_addrandom(unsigned char *, int);
