### ISSUE TITLE
Need both search.h and timeb.h

### ISSUE THREAD

**Issue by UncleOp** [android-ndk/ndk#167]
In NDK r12b, timeb.h is available in android-9, and android-12 through android-19. Similarly, search.h is available in android-21 through android-24.

Note that the two don't intersect. My (legacy) application depends on both.

Is there a pointer to why these headers are not both available? Thanks.

**Comment by enh** [comment]
<timeb.h> was removed by POSIX in 2008.
<search.h> wasn't implemented until L.

**Comment by jmgao** [comment]
edited enh's comment to escape the angle brackets
