### ISSUE TITLE
CMake3.6 android toolchain: CMAKE_FIND_ROOT_PATH_MODE_* set to BOTH

### ISSUE THREAD

**Issue by degasus** [android-ndk/ndk#172]
The file SDK/cmake/3.6/android.toolchain.cmake contains this lines:
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM BOTH)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY BOTH)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE BOTH)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE BOTH)

But they should all be configured to "ONLY", else cmake will also look for librarys on the host plattform.

**Comment by graph** [comment]
I submitted this bug report for preview4 [here](https://code.google.com/p/android/issues/detail?id=214412&can=1&q=benzakhar%20cmake&colspec=ID%20Status%20Priority%20Owner%20Summary%20Stars%20Reporter%20Opened), I hope they will fix this very soon. It prevents lots of important bug finding.

**Comment by chaoren** [comment]
It was set to `ONLY` before, but people complained that libraries in a local path could not be found. `BOTH` is a compromise to find libraries in the sysroot first, then fall back to local path.

If you want to guarantee that you're using the library from the sysroot only, then you can supply `ONLY_CMAKE_FIND_ROOT_PATH` to `find_*`. Likewise, `NO_CMAKE_FIND_ROOT_PATH` to force a local path.

**Comment by chaoren** [comment]
> The must be a way for cmake to not look the host platform for libraries, I don't know if that exists but I assume there should be.

Yes, `find_library(... ONLY_CMAKE_FIND_ROOT_PATH)` would force cmake to *not* find libraries on the host platform.
And, `find_library(... NO_CMAKE_FIND_ROOT_PATH)` would force cmake to *only* find libraries on the host platform.

**Comment by graph** [comment]
I don't understand the issue by host platform is he referring to /usr/include or the expected cross compiling directory include?

**Comment by degasus** [comment]
@graph The hard point here is that there is no way to get cmake to look for the required librarys on the host but to ignore the undesirabled librarys of the host itself. The librarys of the cross compiler are always found. But not available librarys must not be found, trying to use the x64 librarys in /usr/include is doomed to fail.

**Comment by chaoren** [comment]
@degasus 
> But not available libraries must not be found

If this is what you want, then `find_library(... ONLY_CMAKE_FIND_ROOT_PATH)` does exactly that. It will ignore all host libraries.

**Comment by chaoren** [comment]
I will try to see if there's a way to remove the host `/usr/lib`, `/usr/include` from the search paths. Ideally, it should only search the android sysroot, absolute host paths, or relative host paths to the project.

**Comment by degasus** [comment]
Yes. Here, my application has eg optional pulseaudio support. My host (linux) has pulseaudio installed, and a C++ toolchain with all headers. With CMAKE_FIND_ROOT_PATH_MODE=BOTH, cmake will always report that pulseaudio is available, as there are those headers in the global paths.
CMAKE_FIND_ROOT_PATH_MODE=ONLY is for crosscompiling, as it disallow cmake to look for librarys in the common path. But while this is desired on linux, this option prevent cmake on windows to find librarys. There is usually no global C++ toolchain, and all installed librarys are for the used cross compiler, but at very unexpected paths.

@chaoren I'm sorry for refusing this solution, but I try to find a way without patching all cmake files. I'm talking about an android port which also uses cmake on the desktop. So changing this for all find_* is an error-prone task, and I'm not sure about the impact of this flag while not doing a cross compile.

**Comment by graph** [comment]
BOTH is the default according to [this wikipedia entry](http://www.vtk.org/Wiki/CMake_Cross_Compiling). Yes look for a way to accomplish this without deviating from defaults.  Interesting cmake official docs don't specify what is the defaults for these values. I wonder what (Crystax NDK)[https://www.crystax.net/en/android/ndk]  does.

**Comment by chaoren** [comment]
Looks like this could work: https://cmake.org/cmake/help/v3.6/variable/CMAKE_SYSTEM_IGNORE_PATH.html.

**Comment by graph** [comment]
@chaoren great documentation looks like it's meant for this sort of thing.

**Comment by graph** [comment]
@chaoren I found another interesting thing, the variable `CMAKE_SYSTEM_INCLUDE_PATH` has paths in /usr/include/w32api and others. Looks like things from that variable should be removed.

**Comment by graph** [comment]
and more 

I printed the variables out in a sample android cmake project. Got these results:

```
CMAKE_SYSTEM_PREFIX_PATH = /usr/local;/usr;/;/home/blue/Android/Sdk/cmake/3.6;/usr/local
CMAKE_SYSTEM_LIBRARY_PATH = /usr/lib/w32api;/usr/X11R6/lib;/usr/lib/X11;/usr/pkg/lib;/opt/csw/lib;/opt/lib;/usr/openwin/lib
CMAKE_SYSTEM_PROGRAM_PATH = /usr/pkg/bin
```

I don't know if this has anything to do with this issue.

**Comment by graph** [comment]
`CMAKE_SYSTEM_IGNORE_PATH` seems like the best route.  Thanks @chaoren  for responding on the weekend, so hard core :+1: . Have a great weekend guys.

**Comment by chaoren** [comment]
Bad news. I don't think any of those work as expected.
I'm gonna try to change CMake itself to get the behavior we want.

@degasus I understand your situation now. And you're right, the suggestion I gave before wasn't appropriate for your project. I'm gonna try to get your use case working without compromising the original problem in http://b.android.com/214412.

**Comment by degasus** [comment]
@chaoren My solution is to just overwrite those 4 settings. I'm fine with this way, it's much better than patching all find_*. But in my opinion, the documentation should say that everyone using cmake on android should think about the default behavior.

**Comment by chaoren** [comment]
The CMake doc on cross-compiling actually says to use ONLY.

https://cmake.org/cmake/help/v3.6/manual/cmake-toolchains.7.html#cross-compiling

I'm starting to think that maybe find_library isn't the right thing to use for libraries outside of the sysroot.
Perhaps [imported libraries](https://cmake.org/cmake/help/v3.0/manual/cmake-buildsystem.7.html#imported-targets) are what should be used for regular libraries on the host that must be specified by relative or absolute path.

**Comment by graph** [comment]
So I've been playing around, and noticed when setting everything to ONLY, ogre was not found and compilation fails. But adding this line

```
set(CMAKE_FIND_ROOT_PATH "/home/blue/Documents/tests/android-ogre;${CMAKE_FIND_ROOT_PATH}")
```

see full CMakeLists.txt bellow
```
# Sets the minimum version of CMake required to build the native
# library. You should either keep the default value or only pass a
# value of 3.4.0 or lower.

cmake_minimum_required(VERSION 3.4.1)

# Creates and names a library, sets it as either STATIC
# or SHARED, and provides the relative paths to its source code.
# You can define multiple libraries, and CMake builds it for you.
# Gradle automatically packages shared libraries with your APK.

set(OGRE_STATIC TRUE)
set(CMAKE_MODULE_PATH "/home/blue/Documents/tests/android-ogre/ogre/build/install/lib/OGRE/cmake/;${CMAKE_MODULE_PATH}")

set(OGRE_HOME "/home/blue/Documents/tests/android-ogre/ogre/build/install")

set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)

set(CMAKE_FIND_ROOT_PATH "/home/blue/Documents/tests/android-ogre;${CMAKE_FIND_ROOT_PATH}")
find_package(OGRE REQUIRED)
add_library( # Sets the name of the library.
             native-lib

             # Sets the library as a shared library.
             SHARED

             # Provides a relative path to your source file(s).
             # Associated headers in the same location as their source
             # file are automatically included.
             native-lib.cpp )

# Searches for a specified prebuilt library and stores the path as a
# variable. Because system libraries are included in the search path by
# default, you only need to specify the name of the public NDK library
# you want to add. CMake verifies that the library exists before
# completing its build.

find_library( # Sets the name of the path variable.
              log-lib

              # Specifies the name of the NDK library that
              # you want CMake to locate.
              log )

# Specifies libraries CMake should link to your target library. You
# can link multiple libraries, such as libraries you define in the
# build script, prebuilt third-party libraries, or system libraries.

target_link_libraries( # Specifies the target library.
                       native-lib

                       # Links the target library to the log library
                       # included in the NDK.
                       $\{log-lib} ${OGRE_LIBRARIES})
```



solves it. I have ogre compiled deep inside a directory under there.. Most sources use the CMAKE_FIND_ROOT_PATH_MODE_* to ONLY  except for [this one](http://stackoverflow.com/a/21006590/884893). Looks like I was wrong about BOTH being the correct way. Sorry guys this entire thread is my fault. [CMAKE_FIND_ROOT_PATH](https://cmake.org/cmake/help/v3.6/variable/CMAKE_FIND_ROOT_PATH.html) only the first line in the documentation makes sense to me. It sounds like  CMAKE_FIND_ROOT_PATH is used as a recursive white list for find_* commands.. Not just [prepending various paths](http://www.vtk.org/Wiki/CMake_Cross_Compiling#Searching_and_finding_external_software) as the above example demonstrates no amount of prepending will find Ogre. 

[Reading this](https://cmake.org/Wiki/CMake/Tutorials/Exporting_and_Importing_Targets)
> Imported targets are used to convert files outside the project on disk into logical targets inside a CMake project

I don't think `IMPORTED` is the way to go as the issue is finding correct includes & libs and that document talks in a way that the location is already known.

Reading documentation is so much work v_v.

**Comment by chaoren** [comment]
@graph excellent. I'm going to change these values back to `ONLY` then.
