### ISSUE TITLE
libc++ & C++14

### ISSUE THREAD

**Issue by Zingam** [android-ndk/ndk#174]
I use Nsight Tegra with NDK r10.
When I enable C++14 I get errors like:

`1>C:\sdks\NVPACK\android-ndk-r10e\sources\cxx-stl\llvm-libc++\libcxx\include\tuple(291,72): error : 'constexpr const _Hp& std::__1::__tuple_leaf<_Ip, _Hp, <anonymous> >::get() const' cannot be overloaded
1>       _LIBCPP_INLINE_VISIBILITY _LIBCPP_CONSTEXPR_AFTER_CXX11 const _Hp& get() const _NOEXCEPT {return value;}
1>                                                                          ^
1>C:\sdks\NVPACK\android-ndk-r10e\sources\cxx-stl\llvm-libc++\libcxx\include\tuple(290,72): error : with 'constexpr _Hp& std::__1::__tuple_leaf<_Ip, _Hp, <anonymous> >::get() const'
1>       _LIBCPP_INLINE_VISIBILITY _LIBCPP_CONSTEXPR_AFTER_CXX11       _Hp& get()       _NOEXCEPT {return value;}`

Is C++14/17 a lib specific thing? Isn't libc++ even further ahead of supporting new C++ features?

Which is the preferred C++ lib: libstdc++, libc++ or another one? Why are there so many C++ libs anyway?

**Comment by DanAlbert** [comment]
> NDK r10

There's your problem :)

Not that r11 or r12 will actually help you with this, but r13 will finally have an up to date libc++. The one you're using is too old.

> Why are there so many C++ libs anyway?

They each have problems for the moment.

* stlport is just ancient and lacks even C++11.
* gnustl is GPL (which has a linking exception but still people shy away from it).
* libc++ isn't ready yet (as implemented in the NDK).

In another release or two (don't hold me to that estimate) hopefully the NDK's support for libc++ will be ready and then it will be the only sensible choice, so we'll probably remove the others soon after.

**Comment by Zingam** [comment]
Thank you, Dan,

For clearing this up. I hope that you do that sooner rather than later. As our IDE of choice is Visual Studio. Well, it is actually a requirement as all platforms we develop for require latest VS anyway. So naturally for our Android port I'll have to pick either the Microsoft's Android development solution or Nvidia's Nsight Tegra. Both don't really offer the latest SDKs and tool-chains by default. So it is up to you to force them to update somehow by removing gcc, etc. And switching to libc++ maybe will help them fix intellisense, c++1xyzwfw support too!

**Comment by DanAlbert** [comment]
You'll need to file bugs against MS/Nvidia if you want their tools updated. I have no control over them :)
