### ISSUE TITLE
Invalid DT_NEEDED Entries generated

### ISSUE THREAD

**Issue by scorpeeon** [android-ndk/ndk#177]
Hello!

I'm not sure if this is the right place to report/ask about this problem (if not, please redirect me). The problem is native app related, but not necessarily NDK-related, it can be Android Studio itself (it's new native features), and also can just be user error on my part.

I'm using Android Studio 2.2 Preview 7, NDK r12b on Windows 10 x64, JDK 8 u91.
I'm compiling a native app that uses a prebuilt shared .so library (and it's headers).

I'm starting the app from a fresh new project with included C++ support using the new Android Studio's wizard and add a Basic Activity for it. It works fine so far along with the native parts. From here I add the .so and headers to the project (I'm doing this based on the cmake/hello-libs example found in here: https://github.com/googlesamples/android-ndk) and add them to the gradle file and CMakeLists.txt based on the sample app.
Disclaimer: I'm very new to cmake and the new native build tools in Android Studio.

So the problem is that in the compiled app, for the shared library I'm including, for some reason, the referenced DT_NEEDED entry contains not only the SONAME but also the relative path for it (confirmed by readelf).
So instead of containing just: libname.so, it contains: ../../../../distribution/libname/lib/armeabi-v7a/libname.so
The way I noticed this is that the app crashed on start when using target API >=23 at loadLibrary() with UnsatisfiedLinkError (path/libname.so not found) because of changes in treating DT_NEEDED entries in native libs discussed here: http://android-developers.blogspot.hu/2016/06/android-changes-for-ndk-developers.html

On API levels <=22 the app doesn't crash because Android ignores all the path and regards only the part after the last "/".

On the other hand, the same sample app (cmake/hello-libs) doesn't have this problem with target API >=23, the NEEDED entry there only contains the SONAME as it's supposed to. Since I couldn't find any relevant differences in my app, I tried to move my CMakeLists.txt to src/main/cpp (where it is in the sample, instead of the app's root folder where Android Studio generated it) and somehow that made things even worse: the DT_NEEDED entry now was an absolute path like: C:/path/to/project/NativeCppTest/app/src/main/cpp/../../../distribution/libname/lib/armeabi-v7a/libname.so

So I'm not sure what's the best way to control if the DT_NEEDED entry should contain the (relative or absolute) path or just the SONAME. I'm not even sure if there's any valid scenario for including full (relative or absolute) paths in DT_NEEDED entries on Android (based on what I read, we should only use the SONAME in most cases), if there's no such typical scenario, the default build process in Android Studio might do this and never generate full paths (only SONAMES), or at least the option should be set by default to do so (at least in the samples) - if it's intended to work that way, then this might be a bug.
I did find a way to enforce to only use the SONAME (additionally to just using target API <= 22) by setting this property for the lib in the CMakeLists.txt:
set_target_properties(lib_name PROPERTIES IMPORTED_NO_SONAME 1)

And this seemingly solves the problem.
I found this solution here: http://stackoverflow.com/a/27388570
But they also say making sure that DT_SONAME gets set properly by the external build system would be a cleaner solution.

**Comment by DanAlbert** [comment]
You're right that a full path for the `SONAME` entry is pretty much meaningless on Android. For older platform versions the system's loader would ignore the full path and just use the basename for lookups, which is why you'd see this difference before M. The behavior is incorrect though, so that was changed.

> So the problem is that in the compiled app, **for the shared library I'm including**, for some reason, the referenced DT_NEEDED entry contains not only the SONAME but also the relative path for it (confirmed by readelf).

Where is the library you're including coming from? If this is something that the Android build tools are creating, yeah, that's our bug (if so, is that one also coming from cmake? from reading the docs on `IMPORTED_SO_NAME` it sounds like it might be something prebuilt that's being imported to cmake). If it's a third-party thing you're importing, it was just built wrong. The `SONAME` for an Android library needs to be a basename rather than a path.

**Comment by scorpeeon** [comment]
Thanks for the quick reply!

Well, so it looks like this: I have a library (you can call it a prebuilt library though it was built previously using an NDK r12b toolchain) in the form of a single .so (let's call this inner.so) and multiple header files.
It is placed and referenced in my project pretty much the same way as the gperf lib in the cmake/hello-libs sample here: https://github.com/googlesamples/android-ndk/tree/master/cmake/hello-libs/distribution/gperf
(they're placed in a distribution folder, in a lib and an include folder, and are referenced in CMakeLists.txt and the build.gradle).

I also have my native sources (in src/main/cpp, again similarly to the sample app) in the project where I'm using the prebuilt inner library - which of course also gets compiled to a .so file by the Android Studio build process (let's call it outer.so) which itself depends on and needs the inner.so lib. I think it's the linker's job to correctly link the two libs and I think the way they are linked is that the outer library has the inner lib referenced in one of the ELF header's NEEDED entries. And the problem I see is in the outer.so file's (the one that is generated by Android Studio and is linked against the inner.so) ELF header (where the NEEDED entry for the inner.so has a full relative path, not just it's SONAME as it should be).

You mention SONAME, but just to be clear, the SONAME itself looks to be correct, what seems to be wrong is the DT_NEEDED entries in the ELF headers (the NEEDED entries that are listed when running readelf --dynamic outer.so) of the outer.so file (that is generated by the Android Studio build process) for the inner.so file.

Though I haven't checked the inner.so file separately with the readelf tool, so it's possible that something is wrong there already which gets carried over to the outer.so file when linking against it - I can check this.

Thanks, regards

**Comment by DanAlbert** [comment]
> You mention SONAME, but just to be clear, the SONAME itself looks to be correct, what seems to be wrong is the DT_NEEDED entries in the ELF headers (the NEEDED entries that are listed when running readelf --dynamic outer.so) of the outer.so file (that is generated by the Android Studio build process) for the inner.so file.

> Though I haven't checked the inner.so file separately with the readelf tool, so it's possible that something is wrong there already which gets carried over to the outer.so file when linking against it - I can check this.

I think the way the `DT_NEEDED` is set is based on the `SONAME` of the needed library, so my guess is that outer.so has a bad `SONAME`.

**Comment by scorpeeon** [comment]
Oh I see, that's possible, I currently can't check it, but I will tomorrow.
Thanks!

**Comment by scorpeeon** [comment]
I just checked and your guess was right, in the inner.so the SONAME was actually missing.
I'm not really sure why though. The toolchain was created from the r12b NDK with the command:

./build/tools/make-standalone-toolchain.sh --platform=android-9 --install-dir=/home/youruser/dev/android-ndk-r12b-platform9-toolchain --ndk-dir=.

The build uses arm-linux-androideabi-g++ and also I don't see any usages of the -soname linker option which could mess with the SONAME.. Any idea what could be wrong?

Also: I know that missing SONAME is a problem in the first place, but even in this case, is this normal that when linking against it, the build process by default generates these full paths for DT_NEEDED entries? Wouldn't it be better if it would just use the filename or throw an error?

Regards

**Comment by DanAlbert** [comment]
Unfortunately that's working as intended. Standalone toolchains are supposed to match a plain old cross compiler as closely as possible, and by default the linker will not set the `SONAME`. If you're using a standalone toolchain you need to pass `-soname libinner.so` yourself when building (your build system should be the one doing this).

**Comment by enthusiasticgeek** [comment]
I was getting this error while compiling gstreamer ndk android tutorials

The solution was in the Gstreamer pre-built binary package's share/gst-android/ndk-build/gstreamer-1.0.mk file as follows

Modify the following line
GSTREAMER_LD                  := -fuse-ld=gold

To
GSTREAMER_LD                  := -fuse-ld=gold -Wl,-soname,lib$(GSTREAMER_ANDROID_MODULE_NAME).so
