### ISSUE TITLE
when configuring with qtcreator standard include directories are not found

### ISSUE THREAD

**Issue by graph** [android-ndk/ndk#180]
This is a feature request, I would like android's modifications and toolchains to work well with other IDE's besides Android Studio.

# Reproducing with QTCreator

* Step 1: get android studio to generate the build directory and build .
* Step 2: open qtcreator, Open project. Select CMakeLists.txt in project, and choose one of the build directories android studio has made. for build directory.
* Step 3: let qtcreator run cmake to analyse and etc..

**Expected result:**
standard headers to be parsed and allow me to for example ctrl+click on std::string to jump to definitions and etc..

**Actual Result:**
didn't find the proper directories.

**Work around:**
I had to add this line to the projects CMakeLists.txt

```
include_directories(
    SYSTEM "${CMAKE_CXX_STANDARD_INCLUDE_DIRECTORIES}"
)
```

After that I let qtcreator rerun cmake and it found the proper directories. And I got all the bells and whistles of code completion, compiling, jump to definitions of random things and etc..

Maybe that should be added to the `android.toolchain.cmake` near the end.

Thank you :)

**Comment by chaoren** [comment]
```
include_directories(
    SYSTEM "${CMAKE_CXX_STANDARD_INCLUDE_DIRECTORIES}"
)
```
Is definitely the wrong thing to do, since the include flags are already added by CMake.

`CMAKE_CXX_STANDARD_INCLUDE_DIRECTORIES` is a new variable introduced in CMake 3.6. Depending on how they're currently parsing the flags, I think it might be a bug on QtCreator's side that they're not handling this new variable.

**Comment by graph** [comment]
I see, I should have checked the latest documentation first. 

Thank you.
