### ISSUE TITLE
STL vector crash on Android x86_64

### ISSUE THREAD

**Issue by shuoba** [android-ndk/ndk#182]
https://groups.google.com/forum/#!searchin/android-ndk/vector/android-ndk/fTqwkCqPdB8/htTSOXLPDwAJ

**Comment by DanAlbert** [comment]
This was probably the -mstackrealign (or rather the lack thereof) issue.

**Comment by DanAlbert** [comment]
Actually, I think that one only affected globals.

**Comment by DanAlbert** [comment]
Was fixed in r13.
