### ISSUE TITLE
Missing UBSAN runtime support

### ISSUE THREAD

**Issue by ngg** [android-ndk/ndk#183]
ASAN is working great on ARM as well as i686, but there is a missing static library for UBSAN on ARM.
For i686, there is a `toolchains/llvm/prebuilt/linux-x86_64/lib64/clang/3.8/lib/linux/libclang_rt.ubsan_standalone_cxx-i686.a` file, but the ARM version is missing. ASAN binaries are there for all archs.

**Comment by stephenhines** [comment]
These static libraries are only there for building host binaries. UBSan already works for ARM as a shared library (which is the way that all sanitizers work on the device today).

**Comment by DanAlbert** [comment]
How are you trying to use ubsan? `-fsanitize=undefined`? I wouldn't be surprised if the driver was missing the knowledge that we use the shared libraries rather than the static ones since that's very Android specific.

**Comment by ngg** [comment]
Yes, I'm giving `-fsanitize=undefined` for `clang++` at the linking phase, and separate `-fsanitize=alignment` and similar options for `clang++` at the compiling phase (those are subsets of ubsan).
It gives me linker errors like (but not for this single function):
`x.c:17: error: undefined reference to '__ubsan_handle_type_mismatch'`

ASAN works when using `-fsanitize=address` for both compile and link options.

**Comment by DanAlbert** [comment]
Oh, actually, there's a really obvious reason for this: we don't support the ubsan runtime on the device yet. We use ubsan in the platform, but only via `-fsanitize-trap`.

We should probably fix that since it'll be way more useful that way.

**Comment by DanAlbert** [comment]
@ngg: if you want to use ubsan today you should still be able to by using the `-fsanitize-trap` argument: http://clang.llvm.org/docs/UsersManual.html#controlling-code-generation

It will use `__builtin_trap()` to signal issues rather than printing them. It's not as usable, but it's all we support right now.

**Comment by ngg** [comment]
Thanks, it's working with `-fsanitize-trap=undefined`. It would be great to support the runtime though.

**Comment by butterl** [comment]
@DanAlbert :  Is UBsan already work on ARM device with runtime with -fsanitize-trap=undefined or -fsanitize=undefined?  I tried on my android device with a gtest module. The build is pass but the it's runs as if there being no sanitizer active

**Comment by DanAlbert** [comment]
ubsan support (including the runtime) is in r17 beta 1.
