### ISSUE TITLE
make_standalone_toolchain.py documentation

### ISSUE THREAD

**Issue by gpakosz** [android-ndk/ndk#185]
Release notes for `android-ndk-r12b` say:
> The make-standalone-toolchain.sh script will be removed in r13. Make sure make_standalone_toolchain.py suits your needs.

However, `make_standalone_toolchain.py` is not documented. Documentation page
https://developer.android.com/ndk/guides/standalone_toolchain.html still covers `make-standalone-toolchain.sh` only.

**Comment by DanAlbert** [comment]
Until then, `make_standalone_toolchain.py -h` should cover the interesting pieces.

**Comment by DanAlbert** [comment]
Oh, actually, there's also my draft rewrite of the site page: https://android.googlesource.com/platform/ndk/+/master/docs/user/standalone_toolchain.md

**Comment by gpakosz** [comment]
Well for example, it's not difficult to find (by looking at `make_standalone_toolchain.py` source code) but it's not immediately obvious that `--api` expect a single integer without the `android-` prefix :)

**Comment by DanAlbert** [comment]
Just uploaded https://android-review.googlesource.com/265932 to clarify that a bit. Thanks for the pointer.

**Comment by gpakosz** [comment]
Excellent, thank you.

**Comment by robiwano** [comment]
It's not obvious how the CFLAGS= stuff are to be used with the script, if at all. Doc update on that would be appreciated.

**Comment by DanAlbert** [comment]
Finally got the updated doc onto the official docs site. Apologies for the delays. Future updates should be much quicker though.

@robiwano: That was addressed by removing that bit.`CFLAGS` aren't used with the script. The way you add compiler flags will depend on your build system (if any); `CFLAGS` is really only relevant for autoconf.
