### ISSUE TITLE
ndk-build: file: not found

### ISSUE THREAD

**Issue by jk2K** [android-ndk/ndk#188]
Debian 8, x86_64

``` bash
root@907c06713f24:/sdk/android-ndk-r12b/build# ndk-build -e NDK_LOG=1
HOST_OS=linux
HOST_ARCH=x86_64
/sdk/android-ndk-r12b/build/ndk-build: 143: /sdk/android-ndk-r12b/build/ndk-build: file: not found
HOST_ARCH=x86 (32-bit userland detected)
HOST_TAG=linux-x86
GNUMAKE=/usr/bin/make (system path)
Android NDK: NDK installation path auto-detected: '/sdk/android-ndk-r12b'
Android NDK: GNU Make version 4.0 detected
Android NDK: Host OS was auto-detected: linux
Android NDK:  Host operating system detected: linux
/bin/sh: 1: file: not found
Android NDK: Host CPU was auto-detected: x86
Android NDK: HOST_TAG set to linux-x86
Android NDK: Host tools prebuilt directory not found
Android NDK: Host 'echo' tool: echo
Android NDK: Host 'echo -n' tool: printf %s
Android NDK: Host 'cmp' tool: cmp
Android NDK: Host 'awk' tool: awk
Android NDK: Host 'awk' test returned: Pass
```

**Comment by DanAlbert** [comment]
Interesting that it detected a 32-bit userland. Looks like we determine that based on the `file -L` output of `$SHELL`, and you don't have `file` installed (`/bin/sh: 1: file: not found`): https://android.googlesource.com/platform/ndk/+/master/build/ndk-build#143

I'm not sure if I should remove that check or not. The check is only going to catch cases where people have a 64-bit kernel but a 32-bit userland, and we don't support 32-bit userland anyway. Then again, having the early check for an unsupported system is nice, and without knowing what package provides `file(1)` on Debian I'm a little concerned that there might be a lot more broken when using the NDK on such a system...

I should definitely either remove the check or turn it into a hard failure though.

**Comment by enh** [comment]
(and probably easier to just run one of our own binaries; if it works, we have a working 64-bit userspace :-) )

**Comment by jk2K** [comment]
My workaround is install `file` package


 run `sudo apt-get install file`

**Comment by ehem** [comment]
I believe the correct approach is to instead use: `uname -m | grep -q "x86[-_]64"`

`file` is a utility I **always** install on my machines due to the handiness, but it isn't an absolute Unix _requirement_.  Devuan/Debian/Ubuntu are perfectly adequate systems without it.  Just need to double-check what `uname -m` gives on a amd64 kernel with ia32 userspace (been a while and just got this one worry).

**Comment by enh** [comment]
amusing WTF in that code:
```
        ifneq (,$(findstring Power,$(UNAME)))
            HOST_ARCH := ppc
        endif
```

**Comment by enh** [comment]
since we don't support 32-bit linux/darwin (and i'm not sure we ever supported ppc), https://android-review.googlesource.com/#/c/436040/ tries to remove some of this.

**Comment by nguyenxvn** [comment]
https://github.com/OnlyInAmerica/FFmpeg-Android/issues/5#issuecomment-533784577
