### ISSUE TITLE
Update to r13-beta1 - "file not found"

### ISSUE THREAD

**Issue by HalfdanJ** [android-ndk/ndk#189]
Updated a project to r13-beta1, and getting a bunch of trivial "file not found" for std lib files. Files like 

```
fatal error: 'typeinfo' file not found
        #include <typeinfo>

fatal error: 'list' file not found
fatal error: 'cstdlib' file not found
```

Compiling with clang using the `c++_static` runtime. It was compiling fine under r12b. Is this intended? Am I missing a change in r13?

**Comment by DanAlbert** [comment]
It definitely is not intended. Can you provide an example project that has this issue? It doesn't come up in our tests.

**Comment by DanAlbert** [comment]
Discussed with @HalfdanJ, he's using gradle, and the gradle support for r13 is only in 2.2 (and I don't think that patch has made it to the beta channel just yet).
