### ISSUE TITLE
requires unsupported dynamic reloc R_ARM_REL32; recompile with -fPIC

### ISSUE THREAD

**Issue by love-ginger** [android-ndk/ndk#191]
android-sdk/ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: libcrypto.a(sha512-armv4.o): requires unsupported dynamic reloc R_ARM_REL32; recompile with -fPIC

**Comment by DanAlbert** [comment]
Not a bug. You need to recompile with `-fPIC`.

**Comment by sherpya** [comment]
I've got same problem while linking tensorflow usin clang as toolchain (ndk 15c), using gcc it works fine

**Comment by Mellivora123** [comment]
try add -Wl,Bsymbolic

**Comment by Hwangzhiyoung** [comment]
thanks! @sherpya  I 've got the same problem when I using cmake build the tensorflow project .It works!

**Comment by lamnguyen95** [comment]
> try add -Wl,Bsymbolic

I'm having the same issue when linking by shared library with a static library. Although the static library's makefile was configured with --enable-shared flag, NDK stills complained about "requires unsupported dynamic reloc R_ARM_REL32; recompile with -fPIC" with some object files it.

Adding -Wl,Bsymbolic did suppress these errors, but the app will die at runtime.

I'm still scratching my head over this...

**Comment by vb-mich** [comment]
> > try add -Wl,Bsymbolic
> 
> I'm having the same issue when linking by shared library with a static library. Although the static library's makefile was configured with --enable-shared flag, NDK stills complained about "requires unsupported dynamic reloc R_ARM_REL32; recompile with -fPIC" with some object files it.
> 
> Adding -Wl,Bsymbolic did suppress these errors, but the app will die at runtime.
> 
> I'm still scratching my head over this...

same here, is there any solution?

**Comment by kongsub** [comment]
> > > try add -Wl,Bsymbolic
> > 
> > 
> > I'm having the same issue when linking by shared library with a static library. Although the static library's makefile was configured with --enable-shared flag, NDK stills complained about "requires unsupported dynamic reloc R_ARM_REL32; recompile with -fPIC" with some object files it.
> > Adding -Wl,Bsymbolic did suppress these errors, but the app will die at runtime.
> > I'm still scratching my head over this...
> 
> same here, is there any solution?

same with android-ndk-r21d.

**Comment by hanj73** [comment]
> > > > try add -Wl,Bsymbolic
> > > 
> > > 
> > > I'm having the same issue when linking by shared library with a static library. Although the static library's makefile was configured with --enable-shared flag, NDK stills complained about "requires unsupported dynamic reloc R_ARM_REL32; recompile with -fPIC" with some object files it.
> > > Adding -Wl,Bsymbolic did suppress these errors, but the app will die at runtime.
> > > I'm still scratching my head over this...
> > 
> > 
> > same here, is there any solution?
> 
> same with android-ndk-r21d.

Same with android-ndk-r21e. Any update on this?

**Comment by DanAlbert** [comment]
The answer was posted a long time ago https://github.com/android/ndk/issues/191#issuecomment-245510151

**Comment by hanj73** [comment]
> The answer was posted a long time ago [#191 (comment)](https://github.com/android/ndk/issues/191#issuecomment-245510151)

Recompiling with -fPIC doesn't work for me...

**Comment by DanAlbert** [comment]
If you're getting an error that tells you to recompile with PIC then you either didn't recompile everything with PIC or you have non-PIC assembler code.

**Comment by hanj73** [comment]
For those of you who still have the issue, take a look at this commit (https://github.com/google/boringssl/commit/16e38b2b8f50a3d048f61d2979d5ceddacd70fc3).

**Comment by vb-mich** [comment]
> For those of you who still have the issue, take a look at this commit ([google/boringssl@16e38b2](https://github.com/google/boringssl/commit/16e38b2b8f50a3d048f61d2979d5ceddacd70fc3)).

This is what I love about github community, still manages to solve issues even when owners don't give a f.
Thanks a lot @hanj73

**Comment by DanAlbert** [comment]
Hiding _all_ symbols that don't need to be public is always a good idea. The linker is free to simplify relocations for hidden symbols because they cannot be interposed. You're paying for those symbols in app startup time by not doing that.

The change in the linked commit will not always work. If you encounter this error with a symbol that is part of your library's interface it will not work. If you encounter this issue with a symbol that is a part of your public interface you need a different fix (the fixes I mentioned earlier in this thread).

We're always happy to help where we can, but we can't fix code we don't have access to, and we can't offer advice without context.

**Comment by ospfranco** [comment]
I'm sorry but is there a solution already?

> For those of you who still have the issue, take a look at this commit ([google/boringssl@16e38b2](https://github.com/google/boringssl/commit/16e38b2b8f50a3d048f61d2979d5ceddacd70fc3)).

This says nothing to me. I already recompiled my code with `-fPIC` but whenever I try to package my application I'm still getting the same error.

**Comment by DanAlbert** [comment]
Locking to prevent comments we can't help with. If you're encountering this problem, it's most likely a problem in your project. Wether that's the case, or if it is an NDK bug, we can't help without more information, so please file a new bug with the necessary context (https://github.com/android/ndk/issues/1992 is where this is currently being discussed).
