### ISSUE TITLE
x86_64: posix_memalign has different exception specifiers

### ISSUE THREAD

**Issue by duzy** [android-ndk/ndk#192]
First declaration sysroot/usr/include/stdlib.h:70 :
```c
extern int posix_memalign(void **memptr, size_t alignment, size_t size);
```

Second declaration lib/gcc/x86_64-linux-android/4.9.x/include/mm_malloc.h:43
```c++
extern "C" int posix_memalign (void **, size_t, size_t) throw ();
```

This error should occurs if a C++ source file is including both of the headers. I was building with a standalone toolchain (see: `make_standalone_toolchain.py`).

NDK: *android-ndk-r12b-linux-x86_64.zip*

**Comment by DanAlbert** [comment]
I know I've looked in to this before, but I'm going to have to dig around to remember what I came up with.

Until then, Clang doesn't have this problem.

**Comment by DanAlbert** [comment]
Dup of https://github.com/android-ndk/ndk/issues/91
