### ISSUE TITLE
Include imported libraries in CMakeLists.txt into APK/AAR

### ISSUE THREAD

**Issue by graph** [android-ndk/ndk#193]
The current way is to add the following to build.gradle

```
    sourceSets {
        main {
            // let gradle pack the shared library into apk
            jniLibs.srcDirs = ['../distribution/gperf/lib']
        }
    }
```

I want to keep all the logic inside the CMakeLists.txt file to keep everything in one place. Maybe define a location I can just copy all the shared libraries to will be good.

**Comment by graph** [comment]
I tried in the CMakeLists.txt

``
add_custom_target(customLibShared
    mkdir -p ../obj/${ANDROID_ABI}/
    COMMAND cp ${customLibFile} ../obj/${ANDROID_ABI}/
)
```

Which seams to work, but this is not a documented. And I don't want to use unofficial solutions.

**Comment by DanAlbert** [comment]
Sorry, we're just the NDK itself; we don't work on Gradle. Could you file a bug for the Studio team? http://tools.android.com/filing-bugs

**Comment by graph** [comment]
ok [filed here](https://code.google.com/p/android/issues/detail?id=222123&thanks=222123&ts=1473450731)

I want to file another report. In the [samples under master-cmake](https://github.com/googlesamples/android-ndk/tree/master-cmake) they all use gnustl_static. But I need gnustl_shared. When using shared it is not bundled into the APK. Which gives unsatisfied link error. I hacked and noticed `__libstl` points to the so file so in the CMakeLists.txt I copy it in.

Should this be filed here or http://tools.android.com/filing-bugs ?

Thank you.

**Comment by DanAlbert** [comment]
Thanks.

All their samples are on github, and it looks like they use the bug tracker in that project: https://github.com/googlesamples/android-ndk/issues

**Comment by DanAlbert** [comment]
It does sound like that might be a bug in the packaging process rather than a bug in the sample though, so that one should probably be filed the same as you did for the first one.
