### ISSUE TITLE
NDK12b GCC larger precompile header cc1plus crash

### ISSUE THREAD

**Issue by boostiewj** [android-ndk/ndk#195]
android-ndk-r12b-windows-x86_64.zip 
clang building is successful.  but gcc  cc1plus  crash,
gcc config:
1.Application.mk
APP_ABI := armeabi-v7a
APP_BUILD_SCRIPT := ./Android.mk
APP_PLATFORM := android-14
NDK_TOOLCHAIN_VERSION := 4.9
APP_OPTIM := release
APP_PIE := true
2.Android.mk
LOCAL_PCH :=  pch.h
LOCAL_CPPFLAGS += -DPCH
##pch.h include more boost head files

**Comment by DanAlbert** [comment]
GCC is deprecated and, as you said, this is working fine with Clang.
