### ISSUE TITLE
Change .externalNativeBuild to be in build/

### ISSUE THREAD

**Issue by graph** [android-ndk/ndk#196]
Feature request. Maybe add a variable in `build.gradle` to determine it's location would be better and default it in the build folder.

**Comment by DanAlbert** [comment]
Please file Gradle bugs according to http://tools.android.com/filing-bugs. We don't work on Gradle.

**Comment by graph** [comment]
[ok filed](https://code.google.com/p/android/issues/detail?id=222274). Also submitted feature request [to combine NDK into the regular bug reporting](https://code.google.com/p/android/issues/detail?id=222275). I find it weird that NDK reporting is in a separate location. Thank you.

**Comment by RoundSparrow** [comment]
Is there a way to set .externalNativeBuild in gradle? I want to point it to /tmp RAMdisk.

**Comment by DanAlbert** [comment]
Wrong place to ask. None of us use or work on gradle.
