### ISSUE TITLE
Can't debug inside library project

### ISSUE THREAD

**Issue by graph** [android-ndk/ndk#197]
Setup. 2 projects `app` project and `libModule`. This bug has 2 parts which I think are related so I'm putting both parts here.

**Part 1:** Can't debug library project, setting breakpoints do not work. And when a segfault happens ndk breaks in "unknown function` and nothing useful can be done.

A workaround solution is in the main project do this:

```
        // default config
        externalNativeBuild {
            cmake {
                abiFilters'armeabi-v7a'
                arguments "-DANDROID_PLATFORM=android-${platformVersion}",
                        '-DANDROID_TOOLCHAIN=clang', '-DANDROID_STL=gnustl_shared'
            }
        }
    // in android {}
    externalNativeBuild {
        cmake {
            path "../libModule/src/main/cpp/CMakeLists.txt"
        }
    }
```

and I can debug just fine. So far it's fine. This has the disadvantage of compiling everything twice.

**part 2:** Library project always compiles in the release folder `.externalNativeBuild` regardless what has been specified. Interesting though if I do "Build->build APK" in android studio RC2 it builds the debug build.

Some discussion [here](https://github.com/googlesamples/android-ndk/issues/238#issuecomment-246367381)

Some version specifiers

```
Android Studio 2.2 RC 2
Build #AI-145.3253452, built on September 7, 2016
JRE: 1.8.0_76-release-b03 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

classpath 'com.android.tools.build:gradle:2.2.0-rc2'

compileSdkVersion 24
buildToolsVersion "24.0.2"

            cmake {
                abiFilters'armeabi-v7a'
                arguments "-DANDROID_PLATFORM=android-19",
                        '-DANDROID_TOOLCHAIN=clang', '-DANDROID_STL=gnustl_shared'
            }
```

**Comment by DanAlbert** [comment]
I assume you're debugging with LLDB (via Android Studio) and not GDB (via `ndk-gdb`), right?

**Comment by graph** [comment]
Yes via Android Studio. I'm pressing the `Debug App` button with everything at defaults in android studio RC2. Everything is at defaults:

```
Target channels: lldb process:gdb-remote packets
Debug Type: Hybrid
```
Is there instructions for how to use ndk-gdb with new cmake system? I haven't looked into `ndk-gdb` at all.

**Comment by DanAlbert** [comment]
I think `ndk-gdb` is only set up to work with `ndk-build` projects, but @jmgao can correct me if I'm wrong.

For the Studio and LLDB issues, none of those components are actually in the NDK. Could you file a bug against Android Studio so they can take a look at it? http://tools.android.com/filing-bugs

**Comment by graph** [comment]
Ok filed [under Android Studio](https://code.google.com/p/android/issues/detail?id=222276).

**Comment by mondaugen** [comment]
I know this is closed but I found this when having the same problem. I found a solution that worked for me:
If your external library is built with debugging symbols, you might have to do
`add-dsym /path/to/shared/library`
in the LLDB console to get the debugging info. You can set a breakpoint at some main point that you know is getting called, then use `breakpoint command add` to run commands loading the missing debugger symbols.

**Comment by knumat** [comment]
I spent a few hours trying to make the debugger actually stop on a breakpoint in some native C++ code that was built into a library.  Eventually I got it working by doing the following (under Android Studio 3.3.1).  Hopefully this helps someone else!

- Select Run -> Edit Configurations
- On the left side, select Android App -> app
- On the right side, select the Debugger tab
- Under the Symbol Directories sub-tab, press the + button
- Browse to the following path:
    `libModule/build/intermediates/cmake/debug/obj`
- In the Build Variants window, select the "debug" configuration for the app

**Comment by Amoystyle** [comment]
if you use "set(CMAKE_C_FLAGS/CMAKE_CXX_FLAGS "")" in CMakeLists.txt,  it will overwrite the compiler default mode, causing debug symbols to be lost.

**Comment by JessHolle** [comment]
> I spent a few hours trying to make the debugger actually stop on a breakpoint in some native C++ code that was built into a library. Eventually I got it working by doing the following (under Android Studio 3.3.1). Hopefully this helps someone else!
> 
> * Select Run -> Edit Configurations
> * On the left side, select Android App -> app
> * On the right side, select the Debugger tab
> * Under the Symbol Directories sub-tab, press the + button
> * Browse to the following path:
>   `libModule/build/intermediates/cmake/debug/obj`
> * In the Build Variants window, select the "debug" configuration for the app

Yes, this did help me.  And I see the issue here was closed and one opened in Android Studio -- as I was about to gripe that this should be automatic in Android Studio.

**Comment by alexsorokoletov** [comment]
Thank you, this is the only thing that helped  🥳 
Could not debug C++/native android code, tried everything from SO and other sources I could find and this is the only thing that made the change. I am using Android Studio 4 (4.1) and MacOS
https://github.com/android/ndk/issues/197#issuecomment-468988738

**Comment by JessHolle** [comment]
@alexsorokoletov I should note that I no longer have to do this in Android Studio 4.1.x with the Android Gradle Plugin 4.1.x -- thankfully.

**Comment by maddam124** [comment]
I need a game programmer from Nigeria, I'm legit and trusted all I need is someone I can hire to build game for me and then I pay here is my num 08118026235
