### ISSUE TITLE
Fix -jN race on os x

### ISSUE THREAD

**Issue by kmshih** [android-ndk/ndk#198]
Per https://code.google.com/p/android/issues/detail?id=222255 and http://www.egeek.me/2013/11/23/android-ndk-clean-failed-on-fts-read/ there's a race if you do -jN where N>1.  Let's de-race it.

**Comment by DanAlbert** [comment]
Fix merged into r18.

**Comment by rprichard** [comment]
Fixed by https://android-review.git.corp.google.com/c/platform/ndk/+/728877
