### ISSUE TITLE
C code files Can't link to head files

### ISSUE THREAD

**Issue by CyrilTaylor** [android-ndk/ndk#200]
I have config the right path of NDK, but my C code can't link to the head files, is there any one can tell me how I can solve it ?

![code view](https://cloud.githubusercontent.com/assets/12631466/18568970/863cf1ce-7bd2-11e6-92f0-016378c6ffb1.png)

**Comment by DanAlbert** [comment]
What's the error here?

**Comment by CyrilTaylor** [comment]
the red area, Studio can't find the head files.

**Comment by CyrilTaylor** [comment]
I have copy the head files to E:\Android\android-sdks\ndk-bundle\platforms\android-23\XXX\usr\include, and config the buildversion as 23 in build.gradle

**Comment by DanAlbert** [comment]
Wait, are we talking about the cutils header files, or any header files? cutils is not an NDK API so yeah, it's expected that it shouldn't be able to find those headers.

**Comment by CyrilTaylor** [comment]
I have copied all the header files to NDK haeder files path, but the Studio can't find  them. Even if the NDK API like #include <signal.h>

**Comment by DanAlbert** [comment]
Hmm, that's odd, because that's where the headers should be installed.

Can the compiler find them? i.e. does the project build, or is it just the studio syntax highlighting that isn't working?

What version of the NDK are you using? See ndk-bundle/source.properties.

**Comment by DanAlbert** [comment]
> I have copied all the header files to NDK haeder files path

Where did you copy them from?

**Comment by CyrilTaylor** [comment]
AOSP project

**Comment by CyrilTaylor** [comment]
It is just the studio syntax highlighting that isn't working

**Comment by DanAlbert** [comment]
Ah, in that case you'll need to file a bug against Android Studio. See http://tools.android.com/filing-bugs

**Comment by CyrilTaylor** [comment]
Ok, thanks, Dan Albert. Have a good night.
