### ISSUE TITLE
Building GCC for Windows 64-bit fails on aarch64.cc

### ISSUE THREAD

**Issue by buffer51** [android-ndk/ndk#202]
Hi,

It has come to my attention that building the GCC 4.9 toolchain (using steps provided in the documentation here, and NDK r12b) fails for 64-bit Windows (i.e. `--host windows64`).

The process fails when building `binutils/binutils-2.25/gold/aarch64.cc` (regardless of the target, it occurs when building for armeabi too):

```
$(CODE)/toolchain/build/../binutils/binutils-2.25/gold/aarch64.cc:2028:50: error: integer overflow in expression [-Werror=overflow]
       Insntype adr_insn = adrp_insn & ((1 << 31) - 1);
```

This seems to be [this issue](https://sourceware.org/ml/binutils-cvs/2015-07/msg00148.html) which is simply fixed by replacing `1 << 31` by `1u << 31`.

Can that be integrated in the NDK sources? Also, how comes nobody seems to have encountered this issue; I assume the NDK contains prebuilt toolchains for 64-bit Windows right?

**Comment by DanAlbert** [comment]
Probably a difference in the version of mingw that you have vs what we use. Ours is the `mingw-w64` package from apt in Ubuntu Trusty (our buildbots might be on Precise, I can't remember).

What version of mingw are you using? I can look up exact versions of things later tonight or tomorrow.

**Comment by buffer51** [comment]
I am using `mingw-w64` from apt as well, but on Ubuntu 16.04 LTS.

It ends up using `i686-w64-mingw32-gcc` for `--host windows`,
and `x86_64-w64-mingw32-gcc` for `--host windows64`. It's GCC 5.3.1.

The dummy code
```
int main() {
    return ((1 << 31) - 1);
}
```
gives a warning with both compilers unless `-Werror=overflow` is specified.

Any reason that flag would be set for 64-bit Windows only (or at least my version only)?

**Comment by buffer51** [comment]
I did some digging and you are right about the version issue:
- when building for Linux 64-bit host, it uses the GCC in `prebuilts/gcc/` which is 4.8 (no error)
- for Windows 32-bit host, gold is disabled
- for Windows 64-bit host, mingw-w64 form apt is 5.3.1 and fails.

On your buildbots, you probably still have 4.8. I don't know if you'll consider adding the patch or if we'll have to wait for an updated binutils (2.26 at least).

**Comment by DanAlbert** [comment]
No more GCC
