### ISSUE TITLE
Wrap the Java API's.

### ISSUE THREAD

**Issue by AraHaan** [android-ndk/ndk#203]
It would be nice if the Java API's could be wrapped for easier use if a person wants 100% of their code in C++ in case they only know C++.

**Comment by DanAlbert** [comment]
Just to make sure I understand what you're asking for, you want the NDK to ship some pre-written wrappers that handle the JNI <-> C++ boundary to expose a C++ API?

Unfortunately this can't be done without sacrificing a lot of performance (JNI transitions are expensive) and type safety (all Java objects are just `jobject`, so wrapper types for every Java type would need to be maintained on the C++ side of things, and doing that for every type in a way that would remain compatible with all current and future releases is infeasible).

I'm really not that familiar with JNI, so if people can tell me why I'm wrong I'm open to suggestions :)
