### ISSUE TITLE
Allow Android.mk files for prebuilt libraries to specify C++ STL dependency

### ISSUE THREAD

**Issue by bradking** [android-ndk/ndk#205]
Currently there is no way for Android.mk files using

```makefile
include $(PREBUILT_STATIC_LIBRARY)
```

to specify that the static library depends on C++.  We'd like to have a way to activate `modules-add-c++-dependencies`:

* https://android.googlesource.com/platform/ndk/+/dfc517ad/build/core/definitions.mk#820
* https://android.googlesource.com/platform/ndk/+/dfc517ad/build/core/definitions.mk#2048

via something like a

```makefile
LOCAL_PREBUILT_CPP := 1
```

option.  This is needed so that the Android NDK build process knows how to place the static library at the right place on the link line before the C++ STL library.

**Comment by bradking** [comment]
For reference, CMake 3.7 will add support for generating `Android.mk` files to import CMake-built libraries into Android NDK builds.  See Kitware/cmake@42ce9f1e7178b3535726c0c885cc7c9f760cc8b6 for the initial implementation.  CMake knows when a static library uses C++ but currently has no way to give this information to the Android NDK build system.

**Comment by DanAlbert** [comment]
I'll try to look at this for r14.

**Comment by bradking** [comment]
@DanAlbert thanks!

A possibly better name for the option is `LOCAL_HAS_CPP` or `LOCAL_HAS_CXX`.

**Comment by zackgalbreath** [comment]
We opened a change to address this issue:
https://android-review.googlesource.com/#/c/280341/

**Comment by DanAlbert** [comment]
Change is submitted. Thanks a lot for the help!

**Comment by zackgalbreath** [comment]
Thanks for seeing this through, Dan!  We appreciate your help.
