### ISSUE TITLE
Stopping at cpp breakpoints in Windows but not in MacOS, same environment in both OS

### ISSUE THREAD

**Issue by mowcixo** [android-ndk/ndk#209]
I'm not 100% sure if this is the right place to report this issue, because it could be LLDB/Android Studio issue, but at the end of the day it's related with NDK.

So, the issue is that making a fresh install of:

* Android Studio 2.2.0 (build #AI-145.3276617)
* SDK Build-Tools 24.0.3
* SDK Platform-Tools 24.0.3 (tested with 24.0.4 rc1 too)
* LLDB 2.2.3271982
* NDK 12.1.2977051 (tested with beta channel version 13.0.3214847 rc2 in Mac too)

Tested with same virtual/physical devices in both OS.

In Mac it is ignoring the code breakpoints and stopping in the line 119 of ```_construct.h``` (```ndk-bundle/sources/cxx-stl/stlport/stl/_construct.h```):

```java
template <class _Tp>
__attribute__((always_inline)) inline void _Copy_Construct_aux(_Tp* __p, const _Tp& __val, const __false_type&) {
  new(__p) _Tp(__val);
}
```

In Windows it is stopping correctly in my code breakpoints though.

Any thoughts of what should I do with this?

I can post screenshots/fragments of code or whatever.

Thanks.

**Comment by DanAlbert** [comment]
Could you file a bug against the studio team? They're responsible for lldb. http://tools.android.com/filing-bugs

**Comment by DanAlbert** [comment]
(You're right that it's of course possible that it has to do with the NDK, but they will at least need to do the diagnosis for that)

**Comment by mowcixo** [comment]
Perfect. On my way!

**Comment by mowcixo** [comment]
I've already posted the bug: https://code.google.com/p/android/issues/detail?id=224157
