### ISSUE TITLE
can't used c++_shared with CMake and Gradle's 2.2 plugin

### ISSUE THREAD

**Issue by nguillot** [android-ndk/ndk#218]
Studio Build: #AI-145.3276617
NDK: 13.0.3315539
Version of Gradle Plugin: 2.2.0
Version of Gradle: 2.14.1
Version of Java: 1.8.0_76
OS: Mac OS 10.12

Steps to Reproduce:
1. Download the project https://github.com/nguillot/android-cmake
2. checkout the *c++_shared* branch
3. Build and deploy the project on a x86 device/Emulator (due ti the adb filters in CMake)

Expected result
No crash

Result
crash with the message *couldn't find "libc++_shared.so"*.

**Comment by DanAlbert** [comment]
https://code.google.com/p/android/issues/detail?id=214664

Studio doesn't currently know how to package the shared STLs when using cmake.

**Comment by rschiu** [comment]
Please try updating to 2.2.1.  We have a temporary fix for it.

**Comment by opatry** [comment]
@DanAlbert even if Studio (in fact, Gradle) can't handle that automatically (Gradle Experimental build does), the link should not fail and we could handle this copy of STL in our own CMake files until available.

If I'm right, it works with `gnustl_shared` (not sure to have tried but saw it in doc, but not for `c++_shared`.

@rschiu how temporary?

**Comment by DanAlbert** [comment]
> the link should not fail and we could handle this copy of STL in our own CMake files until available.

The link didn't fail. The *load* failed. You can handle this in your own cmake aiui, you just need to copy it into the library output directory.

**Comment by nguillot** [comment]
Thanks for the response. I also observe that the link fails if I does not specify *-DANDROID_TOOLCHAIN=clang* in Gradle. It seems strange to me, when looking at the idk documentation, clang should be the default value.

**Comment by DanAlbert** [comment]
That's what the cmake toolchain file that we ship in the NDK does, but it's possible studio is passing its own `-DANDROID_TOOLCHAIN` that sets it to GCC if you haven't set anything.

**Comment by nguillot** [comment]
Ok, it's good to know. Thanks for the explanation @DanAlbert.

**Comment by nguillot** [comment]
@rschiu thanks, it works as you said!

**Comment by rschiu** [comment]
@opatry When I said temporary, I meant we might approach it differently in the next 1 or 2 release.  It's a supported use case and will continue to work in the future versions, just that the backend may be implemented differently.
