### ISSUE TITLE
cmake support broken due to dependency on libssl.so.1.0.0

### ISSUE THREAD

**Issue by Huatian** [android-ndk/ndk#221]
I'm using Android Studio 2.2.1 on Fedora 24 x86_64. 
CMake package version 3.6.3155560

when i created a new jni project, there was a error:

External Native Build Issues
             Build command failed.
             Error while executing '/home/wanghuatian/Android/Sdk/cmake/3.6.3155560/bin/cmake' with arguments {-H/home/wanghuatian/AndroidStudioProjects/Jnidemo/app -B/home/wanghuatian/AndroidStudioProjects/Jnidemo/app/.externalNativeBuild/cmake/debug/armeabi -GAndroid Gradle - Ninja -DANDROID_ABI=armeabi -DANDROID_NDK=/home/wanghuatian/Android/Sdk/ndk-bundle -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/home/wanghuatian/AndroidStudioProjects/Jnidemo/app/build/intermediates/cmake/debug/obj/armeabi -DCMAKE_BUILD_TYPE=Debug -DCMAKE_MAKE_PROGRAM=/home/wanghuatian/Android/Sdk/cmake/3.6.3155560/bin/ninja -DCMAKE_TOOLCHAIN_FILE=/home/wanghuatian/Android/Sdk/ndk-bundle/build/cmake/android.toolchain.cmake -DANDROID_NATIVE_API_LEVEL=19 -DCMAKE_CXX_FLAGS=}
                 /home/wanghuatian/Android/Sdk/cmake/3.6.3155560/bin/cmake: error while loading shared libraries: libssl.so.1.0.0: cannot open shared object file: No such file or directory
                Error:executing external native build for cmake /home/wanghuatian/AndroidStudioProjects/Jnidemo/app/CMakeLists.txt

Here's the versions of libssl and libcrypto that Fedora installs:
[wanghuatian@localhost ~]$ ls /lib64/libssl*
/lib64/libssl3.so  /lib64/libssl.so.10  /lib64/libssl.so.1.0.2j

**Comment by DanAlbert** [comment]
Dup of https://github.com/android-ndk/ndk/issues/206
