### ISSUE TITLE
Issue with using C++14 features and CMake toolchain flag ordering

### ISSUE THREAD

**Issue by jrogers** [android-ndk/ndk#223]
When using libc++, the new CMake toolchain unconditionally sets -std=c++11. This makes it difficult to use c++14 features (like std::make_unique) without making sure that when you add the flag it gets appended after the toolchain adds its flag so that it picks it up.

I'm not sure the best way to make this easier, possibly the toolchain could take advantage of the CMAKE_CXX_STANDARD properties?

I've run into issues with this when using Qt's CMake toolchain as well where it automatically adds -std=gnu11, but was able to workaround the issue more easily by specifying "set(CMAKE_CXX_STANDARD 14)" in my project's CMakeLists.txt.

**Comment by DanAlbert** [comment]
> This makes it difficult to use c++14 features (like std::make_unique) without making sure that when you add the flag it gets appended after the toolchain adds its flag so that it picks it up.

We should probably just make sure that default we add for libc++ gets prepended rather than appended. I'm hoping that `CMAKE_CXX_STANDARD` will just end up appending to whatever cflags we provide and so making that change with support that use case too, but that needs testing to be sure.

The default `-std=c++11` is there because that's what libc++ in ndk-build has always done, and the cmake toolchain tries to match a lot of ndk-build's behavior.

**Comment by jrogers** [comment]
I tried changing the "list(APPEND ANDROID_COMPILER_FLAGS_CXX -std=c++11)" line to "set(CMAKE_CXX_STANDARD 11)" but nothing ends up getting set at all in that case. It looks like it's missing some underlying CMake infrastructure for it. I'll try some different solutions to see if I can find anything, otherwise I guess I can just live with it.

**Comment by stevemadsenblippar** [comment]
Also affects `ndkBuild`; w/ndk _r14 (stable)_ project with `std::make_unique`
builds just fine but with _ndk r15rc_ get loads of errors
    error: no member named 'make_unique' in namespace 'std'
(which is not helped by adding `#include <memory>` in affected files)

**Comment by kneth** [comment]
Can you - as a workaround - use the possible implementation in http://en.cppreference.com/w/cpp/memory/unique_ptr/make_unique?

**Comment by DanAlbert** [comment]
Thanks for pinging this. It fell through the cracks :( I'll take a look.

**Comment by DanAlbert** [comment]
Looks like this is fine for CMake starting with r14. Checking ndk-build now.

**Comment by DanAlbert** [comment]
Repro'd the ndk-build issue with r15 beta 2. Opened https://github.com/android-ndk/ndk/issues/403. Closing this one.

**Comment by graph** [comment]
I'm having a related issue in the stable release of r15. It keeps forcing gnu++11 no matter how hard I try to change it to C++14. It's using the libc++_shared. The NDK is appending gnu++11 at the very end. Here is the options when it fails

```
-frtti
-fexceptions
-Wall
-Wextra
-Wno-unknown-pragmas
-Wno-unused-parameter
-fvisibility=hidden
-Wfloat-equal
-ffunction-sections
-fdata-sections
-Werror=return-type
-Werror=init-self
-Werror=uninitialized
-Werror=maybe-uninitialized
-Werror=bad-function-cast
-Werror=parentheses
-Werror=sequence-point
-Werror=return-local-addr
-Werror=address
-DDEBUG=1
-std=c++14
-w
-D__ANDROID__=1
-O0
-fno-limit-debug-info

-fPIC


-std=gnu++11
-MD
-MT
```
No workaround I tried removes the gnu++11. I don't know what variable that is added to in cmake.

**Comment by graph** [comment]
Incase anyone stumbles upon this. Add this for now:

```
set(CMAKE_CXX14_EXTENSION_COMPILE_OPTION -std=c++14)
set(CMAKE_CXX_STANDARD 14)
```

**Comment by DanAlbert** [comment]
Works for me with r15b and the version of CMake in the SDK manager. If you had to modify `CMAKE_CXX14_EXTENSION_COMPILE_OPTION`, maybe there's something wrong with CMake's detection of the compiler features? What version of CMake? What OS?

**Comment by graph** [comment]
build.gradle
```
                cppFlags "-frtti -fexceptions"
                arguments "-DANDROID_PLATFORM=android-${platformVersion}",
                        '-DANDROID_TOOLCHAIN=clang', '-DANDROID_STL=c++_shared',
                        "-DSHARED_BUILD_DIR=${buildDirStr}"
```

cmake version: android-sdk/cmake/3.6.4111459

OS: Mac Sierra
