### ISSUE TITLE
Update NDK Links and Release Notes - 13b

### ISSUE THREAD

**Issue by Brahmasmi** [android-ndk/ndk#226]
The NDK link and release notes at https://developer.android.com/ndk/downloads/index.html still point to 13, whereas Android Studio lists 13.1 (13b as per download link) to be the latest release.

**Comment by DanAlbert** [comment]
I think all the people that can approve my website update are out this week :(

**Comment by danielweck** [comment]
Hello, what's the changelog?
https://dl.google.com/android/repository/android-ndk-r13b-windows-x86_64.zip

**Comment by DanAlbert** [comment]
Official page is up to date now.

> Hello, what's the changelog?
https://dl.google.com/android/repository/android-ndk-r13b-windows-x86_64.zip

Check our wiki: https://github.com/android-ndk/ndk/wiki
