### ISSUE TITLE
Provide cmake and LLDB in the NDK package

### ISSUE THREAD

**Issue by cybik** [android-ndk/ndk#227]
Seeing as the Android SDK team is completely out of touch with automated build environment requirements that, for example, really discourage installing Android Studio and using a UI to install command-line packages, can I request that the NDK team consider bundling cmake and LLDB into the NDK packages? This way, we can get the proper versions of the Native tools more easily than by digging through the Android Studio UI.

(Sorry for the tone)

**Comment by cybik** [comment]
I know that there's XML files at addresses available in Android Studio that I can parse and use to get the tools I need, but I have no insurance that these won't change.

**Comment by DanAlbert** [comment]
I had the cmake side of this conversation with someone recently, but I don't actually remember if we had come up with reasons against it.

Doing this for CMake seems like a no-brainer to me since the cmake toolchain we ship won't actually work with a cmake available in any package manager (afaik no distro has a cmake new enough for our needs).

I hadn't considered doing this for LLDB. It's the first time anyone has asked.

> Seeing as the Android SDK team is completely out of touch with automated build environment requirements that, for example

Yeah, I've actually been asking for this too. We've sent this report along to one of the Studio PMs to see if we can do something about this. If this gets fixed, are there other reasons you'd like lldb to be a part of the NDK package? The advantage of keeping them decoupled is that we don't restrict release timing on either side.

**Comment by cybik** [comment]
I put LLDB in there literally just because it's more of an NDK tool that could, conceivably, be used though command-line for debugging purposes by someone juuuuuuuust crazy enough.

I personally have no use cases for now; in this current issue, I'm the build engineer, not the final user.

As for the cmake tool being bundled with NDK: that would meet our needs perfectly; I don't want to rely on a URL extracted *manually* from an XML I'm not supposed to look at myself, and would much rather just download the latest release tarball that you folks publish :)

**Comment by piwinux** [comment]
> Doing this for CMake seems like a no-brainer to me since the cmake toolchain we ship won't actually work with a cmake available in any package manager (afaik no distro has a cmake new enough for our needs).

Are there specific features used that require the latest version of CMake? I successfully cross-compiled some libraries with CMake 3.3 without any problem by simply lowering the version specified in `cmake_minimum_required()`.

**Comment by DanAlbert** [comment]
Studio did get a command line SDK manager recently: https://developer.android.com/studio/command-line/sdkmanager.html

Does that obsolete this bug, or are there still reasons we should be doing this?

**Comment by enh** [comment]
wasn't the idea to make the NDK download more useful stand-alone for build server usage?

**Comment by DanAlbert** [comment]
I think it was just about making the headless use case work, which it should now (or maybe there's still a UI required part to get the CLI components installed).

**Comment by enh** [comment]
yeah, i guess as long as everything works from the command-line that's fine.

personally i'd still kind of like to get lldb into the NDK as a step towards abandoning gdb, but we should probably worry about getting lldb into the platform first :-/

**Comment by Zingam** [comment]
Shouldn't these be really a part of NDK as they are recommended/required to develop native apps? So the inclusion will complete the tool-chain.

Specifically CMake included in AS is still at version 3.6. And it is not obvious to me how can I set a different version. I'd like to use CMake 3.8.

**Comment by DanAlbert** [comment]
For Studio you can't use a different version. You have to use the bundled one because it has some patches that weren't ready upstream yet. (Removing this requirement is a WIP.)

CMake and LLDB are not required for building native applications.

**Comment by Zingam** [comment]
Well as long as the required CMake is always upstreamed and one can provide a desired version himself it would be fine.

**Comment by Zingam** [comment]
BTW Is there a chance for a newer version of CMake like 3.8 in AS anytime soon?

**Comment by DanAlbert** [comment]
I think this is probably obsolete with the work we have planned to sync up better with CMake. The NDK should be compatible with any version of CMake (isn't yet), in which case I don't think we gain much by doing this given that there's now a command-line friendly sdk manager.

**Comment by DanAlbert** [comment]
> BTW Is there a chance for a newer version of CMake like 3.8 in AS anytime soon?

You'd have to ask the Studio folks (can file a bug with them, they're pretty responsive).
