### ISSUE TITLE
Invoking ndk-build with NDK_TOOLCHAIN_VERSION= selects gcc instead of clang

### ISSUE THREAD

**Issue by gpakosz** [android-ndk/ndk#229]
Hello,

I noticed that when I launch `ndk-build` while setting an empty `NDK_TOOLCHAIN_VERSION` value, `gcc` gets selected instead of `clang`:

```
$ /opt/android-ndk/ndk-build NDK_APPLICATION_MK=./Application.mk NDK_PROJECT_PATH=. V=1 -B NDK_TOOLCHAIN_VERSION=
...

[arm64-v8a] Compile        : foo <= main.c
/opt/android-ndk-r13b/toolchains/aarch64-linux-android-4.9/prebuilt/darwin-x86_64/bin/aarch64-linux-android-gcc -MMD -MP -MF ./obj/local/arm64-v8a/objs/ndk-r13-clang-SIGSEGV/main.o.d -fpic -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes  -g -O2 -DNDEBUG  -I. -DANDROID -ffunction-sections -fdata-sections -Wa,--noexecstack -Wformat -Werror=format-security -fPIE  -fno-strict-aliasing -Werror=implicit-function-declaration  -isystem /opt/android-ndk-r13b/platforms/android-21/arch-arm64/usr/include -c  ./main.c -o ./obj/local/arm64-v8a/objs/foo/main.o

...
```

**Comment by DanAlbert** [comment]
Huh. Make is weird.

Nice catch. I'll take a look.

**Comment by gpakosz** [comment]
Change `core/init.mk` add **`override`** on line 639:

```
ifeq ($(NDK_TOOLCHAIN_VERSION),)
    override NDK_TOOLCHAIN_VERSION := clang
endif
```

**Comment by ehem** [comment]
There is the comment in setup-toolchain.mk for the case of NDK_TOOLCHAIN being undefined:

>     # We default to using GCC, which is the first item in the list.
>     TARGET_TOOLCHAIN := $(firstword $(TARGET_TOOLCHAIN_LIST))

Might you want $(lastword ...) instead?

I'm unsure whether this is a separate problem or a variant of this problem, but it appears 13b _doesn't_ have a version of `strip` for clang; as a result it is using `strip` from GCC.  Perhaps there are other missing binaries?

**Comment by DanAlbert** [comment]
> There is the comment in setup-toolchain.mk for the case of NDK_TOOLCHAIN being undefined:

I guess we have two places that try to set the default. The one in init.mk wins, and seems to be a clearer way to write the default than the one in setup-toolchain.mk IMO. Good find though.

>  it appears 13b doesn't have a version of strip for clang; as a result it is using strip from GCC.

GCC doesn't have `strip` either; binutils does. GCC and binutils are installed to the same directory for historical reasons.

**Comment by gpakosz** [comment]
Closed?

**Comment by DanAlbert** [comment]
https://android-review.googlesource.com/c/304106/

**Comment by DanAlbert** [comment]
Had to revert: https://android-review.googlesource.com/c/314116/1

That broke Application.mk's use of this. Will need to figure out another implementation.

**Comment by DanAlbert** [comment]
Triaging for r17 since it's supposed to be a fixit release, but given that we will most likely be removing GCC in r18 this may not need to happen.

**Comment by DanAlbert** [comment]
Merged into r16.
