### ISSUE TITLE
invalid DT_NEEDED entry

### ISSUE THREAD

**Issue by DhavalThkkar** [android-ndk/ndk#232]
I'm totally new to android as well as android NDK. I have recently been trying to use opencv libraries for facial recognition. The app works fine but always there is an error:"Detected problems with app native libraries"
`11-02 21:13:55.156 23919-23919/? W/linker: library "/data/app/org.opencv.javacv.facerecognition-2/lib/arm/libopencv_core.so" has invalid DT_NEEDED entry "../../lib/libtbb.so"
11-02 21:13:55.227 23919-23919/? W/linker: library "/data/app/org.opencv.javacv.facerecognition-2/lib/arm/libopencv_imgproc.so" has invalid DT_NEEDED entry "../../lib/libopencv_core.so"
11-02 21:13:55.227 23919-23919/? W/linker: library "/data/app/org.opencv.javacv.facerecognition-2/lib/arm/libopencv_imgproc.so" has invalid DT_NEEDED entry "../../lib/libtbb.so"
11-02 21:13:55.271 23919-23919/? W/linker: library "/data/app/org.opencv.javacv.facerecognition-2/lib/arm/libopencv_highgui.so" has invalid DT_NEEDED entry "../../lib/libopencv_core.so"
11-02 21:13:55.271 23919-23919/? W/linker: library "/data/app/org.opencv.javacv.facerecognition-2/lib/arm/libopencv_highgui.so" has invalid DT_NEEDED entry "../../lib/libopencv_imgproc.so"
11-02 21:13:55.272 23919-23919/? W/linker: library "/data/app/org.opencv.javacv.facerecognition-2/lib/arm/libopencv_highgui.so" has invalid DT_NEEDED entry "../../lib/libtbb.so"
11-02 21:13:55.312 23919-23919/? W/linker: library "/data/app/org.opencv.javacv.facerecognition-2/lib/arm/libopencv_flann.so" has invalid DT_NEEDED entry "../../lib/libopencv_core.so"
11-02 21:13:55.312 23919-23919/? W/linker: library "/data/app/org.opencv.javacv.facerecognition-2/lib/arm/libopencv_flann.so" has invalid DT_NEEDED entry "../../lib/libtbb.so"
11-02 21:13:55.385 23919-23919/? W/linker: library "/data/app/org.opencv.javacv.facerecognition-2/lib/arm/libopencv_features2d.so" has invalid DT_NEEDED entry "../../lib/libopencv_core.so"
11-02 21:13:55.385 23919-23919/? W/linker: library "/data/app/org.opencv.javacv.facerecognition-2/lib/arm/libopencv_features2d.so" has invalid DT_NEEDED entry "../../lib/libopencv_imgproc.so"
11-02 21:13:55.385 23919-23919/? W/linker: library "/data/app/org.opencv.javacv.facerecognition-2/lib/arm/libopencv_features2d.so" has invalid DT_NEEDED entry "../../lib/libopencv_flann.so"
11-02 21:13:55.386 23919-23919/? W/linker: library "/data/app/org.opencv.javacv.facerecognition-2/lib/arm/libopencv_features2d.so" has invalid DT_NEEDED entry "../../lib/libopencv_highgui.so"
11-02 21:13:55.386 23919-23919/? W/linker: library "/data/app/org.opencv.javacv.facerecognition-2/lib/arm/libopencv_features2d.so" has invalid DT_NEEDED entry "../../lib/libtbb.so"
11-02 21:13:55.448 23919-23919/? W/linker: library "/data/app/org.opencv.javacv.facerecognition-2/lib/arm/libopencv_calib3d.so" has invalid DT_NEEDED entry "../../lib/libopencv_core.so"
11-02 21:13:55.448 23919-23919/? W/linker: library "/data/app/org.opencv.javacv.facerecognition-2/lib/arm/libopencv_calib3d.so" has invalid DT_NEEDED entry "../../lib/libopencv_imgproc.so"
11-02 21:13:55.449 23919-23919/? W/linker: library "/data/app/org.opencv.javacv.facerecognition-2/lib/arm/libopencv_calib3d.so" has invalid DT_NEEDED entry "../../lib/libopencv_flann.so"
11-02 21:13:55.449 23919-23919/? W/linker: library "/data/app/org.opencv.javacv.facerecognition-2/lib/arm/libopencv_calib3d.so" has invalid DT_NEEDED entry "../../lib/libopencv_highgui.so"
11-02 21:13:55.450 23919-23919/? W/linker: library "/data/app/org.opencv.javacv.facerecognition-2/lib/arm/libopencv_calib3d.so" has invalid DT_NEEDED entry "../../lib/libopencv_features2d.so"
11-02 21:13:55.450 23919-23919/? W/linker: library "/data/app/org.opencv.javacv.facerecognition-2/lib/arm/libopencv_calib3d.so" has invalid DT_NEEDED entry "../../lib/libtbb.so"
11-02 21:13:55.522 23919-23919/? W/linker: library "/data/app/org.opencv.javacv.facerecognition-2/lib/arm/libopencv_objdetect.so" has invalid DT_NEEDED entry "../../lib/libopencv_core.so"
11-02 21:13:55.522 23919-23919/? W/linker: library "/data/app/org.opencv.javacv.facerecognition-2/lib/arm/libopencv_objdetect.so" has invalid DT_NEEDED entry "../../lib/libopencv_imgproc.so"
11-02 21:13:55.523 23919-23919/? W/linker: library "/data/app/org.opencv.javacv.facerecognition-2/lib/arm/libopencv_objdetect.so" has invalid DT_NEEDED entry "../../lib/libopencv_highgui.so"
11-02 21:13:55.523 23919-23919/? W/linker: library "/data/app/org.opencv.javacv.facerecognition-2/lib/arm/libopencv_objdetect.so" has invalid DT_NEEDED entry "../../lib/libtbb.so"
11-02 21:13:55.561 23919-23919/? W/linker: library "/data/app/org.opencv.javacv.facerecognition-2/lib/arm/libopencv_video.so" has invalid DT_NEEDED entry "../../lib/libopencv_core.so"
11-02 21:13:55.561 23919-23919/? W/linker: library "/data/app/org.opencv.javacv.facerecognition-2/lib/arm/libopencv_video.so" has invalid DT_NEEDED entry "../../lib/libopencv_imgproc.so"
11-02 21:13:55.561 23919-23919/? W/linker: library "/data/app/org.opencv.javacv.facerecognition-2/lib/arm/libopencv_video.so" has invalid DT_NEEDED entry "../../lib/libtbb.so"
11-02 21:13:55.606 23919-23919/? W/linker: library "/data/app/org.opencv.javacv.facerecognition-2/lib/arm/libopencv_ml.so" has invalid DT_NEEDED entry "../../lib/libopencv_core.so"
11-02 21:13:55.606 23919-23919/? W/linker: library "/data/app/org.opencv.javacv.facerecognition-2/lib/arm/libopencv_ml.so" has invalid DT_NEEDED entry "../../lib/libtbb.so"
11-02 21:13:55.640 23919-23919/? W/linker: library "/data/app/org.opencv.javacv.facerecognition-2/lib/arm/libopencv_contrib.so" has invalid DT_NEEDED entry "../../lib/libopencv_core.so"
11-02 21:13:55.640 23919-23919/? W/linker: library "/data/app/org.opencv.javacv.facerecognition-2/lib/arm/libopencv_contrib.so" has invalid DT_NEEDED entry "../../lib/libopencv_imgproc.so"
11-02 21:13:55.641 23919-23919/? W/linker: library "/data/app/org.opencv.javacv.facerecognition-2/lib/arm/libopencv_contrib.so" has invalid DT_NEEDED entry "../../lib/libopencv_flann.so"
11-02 21:13:55.641 23919-23919/? W/linker: library "/data/app/org.opencv.javacv.facerecognition-2/lib/arm/libopencv_contrib.so" has invalid DT_NEEDED entry "../../lib/libopencv_highgui.so"
11-02 21:13:55.641 23919-23919/? W/linker: library "/data/app/org.opencv.javacv.facerecognition-2/lib/arm/libopencv_contrib.so" has invalid DT_NEEDED entry "../../lib/libopencv_features2d.so"
11-02 21:13:55.642 23919-23919/? W/linker: library "/data/app/org.opencv.javacv.facerecognition-2/lib/arm/libopencv_contrib.so" has invalid DT_NEEDED entry "../../lib/libopencv_calib3d.so"
11-02 21:13:55.642 23919-23919/? W/linker: library "/data/app/org.opencv.javacv.facerecognition-2/lib/arm/libopencv_contrib.so" has invalid DT_NEEDED entry "../../lib/libopencv_ml.so"
11-02 21:13:55.642 23919-23919/? W/linker: library "/data/app/org.opencv.javacv.facerecognition-2/lib/arm/libopencv_contrib.so" has invalid DT_NEEDED entry "../../lib/libopencv_video.so"
11-02 21:13:55.642 23919-23919/? W/linker: library "/data/app/org.opencv.javacv.facerecognition-2/lib/arm/libopencv_contrib.so" has invalid DT_NEEDED entry "../../lib/libopencv_objdetect.so"
11-02 21:13:55.643 23919-23919/? W/linker: library "/data/app/org.opencv.javacv.facerecognition-2/lib/arm/libopencv_contrib.so" has invalid DT_NEEDED entry "../../lib/libtbb.so"`
Can somebody help?

**Comment by DanAlbert** [comment]
This generally means that the libraries you're linking were built without the `-soname` flag. See https://github.com/android-ndk/ndk/issues/177
