### ISSUE TITLE
Inconsistent LOCAL_MODULE setting for extra modules

### ISSUE THREAD

**Issue by ehem** [android-ndk/ndk#235]
The subject says it all.  For the cpufeatures and ndk_helper libraries you need to add "cpufeatures" or "ndk_helper" to LOCAL_STATIC_LIBRARIES.  For the support and native_app_glue libraries you end up adding "android_support" or "android_native_app_glue" to LOCAL_STATIC_LIBRARIES.

Might help to add a mention to the documentation for import-module that you will need to check LOCAL_MODULE from the Android.mk file for what exactly you need to add to LOCAL_STATIC_LIBRARIES.

**Comment by DanAlbert** [comment]
I hadn't really noticed that before. That's annoying.

Unfortunately since these names are baked into everyone's makefiles by now, I think a doc fix is the only real choice here.

**Comment by ehem** [comment]
Perhaps.  Try entering "Android NDK support iconv" into your favored search engine, _most_ of what comes back will be people needing iconv functionality and trying to figure out how to build GNU's libiconv for Android.  I suspect _very_ few developers have bothered trying to use or been persistent enough to use the iconv functionality from the NDK.  In fact there aren't any mentions of iconv on https://developer.android.com/ndk/

I suspect most of the developers who needed iconv are using GNU iconv and renaming wouldn't effect very many developers at all.

**Comment by DanAlbert** [comment]
The samples should have all of these documented sufficiently.
