### ISSUE TITLE
AndroidRuntime: UnsatisfiedLinkError cannot locate symbol "__aeabi_memclr4" 

### ISSUE THREAD

**Issue by riless** [android-ndk/ndk#237]
_Configuration 1_: works
Device Model: Samsung (SM-T530)
Android version: 5.0.2

_Configuration 2_: works
Device Model: LG (G2)

_Configuration 3_: **don't works**
Device Model: Samsung (SM-T810)
Android version: 6.0.1

Configuration 3 gives me this error at runtime.

```
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: com.company.android.camera, PID: 7188
                  java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "__aeabi_memclr4" referenced by "/data/app/com.company.android.camera-2/lib/arm/libcamera.so"...
                      at java.lang.Runtime.loadLibrary(Runtime.java:372)
                      at java.lang.System.loadLibrary(System.java:1076)
```

**Comment by DanAlbert** [comment]
Dup of https://github.com/android-ndk/ndk/issues/126

**Comment by DanAlbert** [comment]
(most likely anyway, please reopen if that doesn't match your situation)
