### ISSUE TITLE
java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "__aeabi_memcpy" 

### ISSUE THREAD

**Issue by raaviswami** [android-ndk/ndk#239]
java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "__aeabi_memcpy"  

Error in Android 6.0.1 only

**Comment by DanAlbert** [comment]
https://android.googlesource.com/platform/ndk/+/master/docs/user/common_problems.md#Target-API-Set-Higher-Than-Device-API
