### ISSUE TITLE
Error when creating Output Mix in OpenSL ES

### ISSUE THREAD

**Issue by mcemilg** [android-ndk/ndk#246]
#### Description

I edited some parts of native-audio example according to my own project. I encounter this error while creating an output-mix.

```
E/AudioEffect: set(): AudioFlinger could not create effect, status: -1
E/libOpenSLES: Effect initCheck() returned -19
E/libOpenSLES: EnvironmentalReverb effect initialization failed
```
I did not change the create engine part of the project. But the error is out there.

```
// create output mix, with environmental reverb specified as a non-required interface
const SLInterfaceID ids[1] = {SL_IID_ENVIRONMENTALREVERB};
const SLboolean req[1] = {SL_BOOLEAN_FALSE};
result = (*engineEngine)->CreateOutputMix(engineEngine, &outputMixObject, 1, ids, req);
assert(SL_RESULT_SUCCESS == result);
(void)result;

// realize the output mix
result = (*outputMixObject)->Realize(outputMixObject, SL_BOOLEAN_FALSE);
assert(SL_RESULT_SUCCESS == result);
(void)result;
```
#### Environment Details
* NDK Version: 13.1.3345770
* Build sytem: cmake
* Host OS: Windows 10
* Compiler: clang
* Device API level: 23

**Comment by DanAlbert** [comment]
This is most likely a bug in the platform rather than in the NDK (the NDK doesn't actually contain any implementation, just headers and some stub libraries).

Could you file a bug at http://b.android.com? If you post the URL for the bug here I'll make sure it gets passed on to the right person.
