### ISSUE TITLE
Android Studio NDK Wizard Fails with Basic Activity Fragment

### ISSUE THREAD

**Issue by bessermt** [android-ndk/ndk#247]
#### Description

Run Android Studio Wizard to create a new project.

Choose default options except for the following:

- Check "Include C++ Support"
- Create a "Basic Activity"
- Check "Use a Fragment"
- Click "Finish" button

#### Environment Details

There may be other (simpler or more complex) options which also create the problem.

The generated MainActivity.java is:
 
        // Example of a call to a native method
        TextView tv = (TextView) findViewById(R.id.sample_text);
        tv.setText(stringFromJNI());

But R.id.sample_text does not exist, so the wizard generated application does not build. 

Easy to workaround. Just add the missing sample_text id to fragment_main.xml TextView

    android:id="@+id/sample_text"

Using the Android Studio 2.2.2 running Linux Mint 17.2

**Comment by Evisceration** [comment]
You should report that to the Android Studio team.

https://sites.google.com/a/android.com/tools/filing-bugs

**Comment by bessermt** [comment]
That site to report here. I'll go back. Thx.

**Comment by DanAlbert** [comment]
They told you to report here? Could you link that bug? This looks very clearly like not an NDK bug to me.
