### ISSUE TITLE
No support for _FILE_OFFSET_BITS=64 in API 12

### ISSUE THREAD

**Issue by ehem** [android-ndk/ndk#248]
#### Description

SSIA.  While `#define _LARGEFILE64_SOURCE` does in fact appear to work, `#define _FILE_OFFSET_BITS 64` does not.  Also appears _LARGEFILE64_SOURCE was **not** added to api12, despite the fact many of those devices can handle large files due to their micro-SD card slots.

#### Environment Details

* NDK Version: 13.1.3345770
* NDK API level: 22
* Device API level: 22

**Comment by enh** [comment]
you'll want the unified headers in NDK r14. the current platform headers have _FILE_OFFSET_BITS=64 support for all functions, though relatively few of the *64 functions are actually available in old Android releases such as 12 --- you'll need the (to-be-written) compatibility library too before you have that.

**Comment by DanAlbert** [comment]
This is done with r15c.
