### ISSUE TITLE
NDK host-tools module fails to build under Darwin

### ISSUE THREAD

**Issue by anestisb** [android-ndk/ndk#249]
#### Description

Building NDK host-tools under Darwin fails due to `toolchain/xz` build loop. The problem appears to be located in a timestamp based hack from the following code when gdb builds liblzma dep (introduced from patches [here](https://android.googlesource.com/toolchain/gdb/+/87aef1e33cdb0dca0b78b64b7bfecdc7cb7f83cc%5E!/) and [here](https://android.googlesource.com/toolchain/gdb/+/895e961e2cdce2d7a385fc8293c846e3da0a460f%5E!/))

```
toolchain/gdb/build-gdb.sh
160 # $1: host system tag
161 build_lzma ()
...
180     # HACK: git doesn't keep track of file modification date, so autoconf will sometimes (usually?)
181     # want to regenerate itself. Trick it into not doing so by touching all of the source files.
182     case "$BH_BUILD_CONFIG" in
183       *darwin*)
184         # Darwin's touch sucks.
185         run find $SRCDIR -exec touch -t 197001010000 {} +
186         ;;
187
188       *)
189         run find $SRCDIR -exec touch -d "`date`" {} +
190         ;;
191     esac
```

When building against Darwin, timestamp of xz sources is set to Unix Epoch triggering the following configuration warning.

```
config.status: creating po/Makefile
make: Warning: File `/Users/anestisb/Developer/android/aosp_ndk/toolchain/xz/Makefile.in' has modification time 1.8e+19 s in the future
```

Then build process keeps looping around xz configure execution forever since make keeps invoking `/bin/sh ./config.status --recheck`. Also attaching a build log from host tools for more details - [host-tools.log.txt](https://github.com/android-ndk/ndk/files/614666/host-tools.log.txt).

The following patch seems to resolve the issue (tested for both master-ndk & ndk-r13-release branches). However, I'm still curious how Darwin build bots manage to generate NDK build for OS X the past few months without any issues.

```
$ git -C toolchain/gdb diff
diff --git a/build-gdb.sh b/build-gdb.sh
index c3137a5..061355b 100755
--- a/build-gdb.sh
+++ b/build-gdb.sh
@@ -182,7 +182,7 @@ build_lzma ()
     case "$BH_BUILD_CONFIG" in
       *darwin*)
         # Darwin's touch sucks.
-        run find $SRCDIR -exec touch -t 197001010000 {} +
+        run find $SRCDIR -exec touch -t "`date +%Y%m%d%H%M`" {} +
         ;;

       *)
```

#### Environment Details

* Host OS:
  ```
  $ sw_vers
  ProductName:	Mac OS X
  ProductVersion:	10.12.1
  BuildVersion:	16B2657
  ```
* Host Compiler:
  ```
  $ xcode-select -v && clang --version
  xcode-select version 2345.1.
  Apple LLVM version 8.0.0 (clang-800.0.42.1)
  Target: x86_64-apple-darwin16.1.0
  Thread model: posix
  InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
  ```
* NDK branches checked against:
  * ndk-r13-release
  * master-ndk

**Comment by DanAlbert** [comment]
Obsolete. We build this all the time.
