### ISSUE TITLE
NDK 2.0.0 fails to installs as part of Android Studio 1.5.1 (Download finished with wrong size)

### ISSUE THREAD

**Issue by swisspol** [android-ndk/ndk#25]
![image](https://cloud.githubusercontent.com/assets/627915/13827960/693c5722-eb7c-11e5-8470-ced0c82dd9c6.png)

![image](https://cloud.githubusercontent.com/assets/627915/13828008/ab038aae-eb7c-11e5-949b-ade1c9aa4057.png)

Observed on OS X 10.10.5. Tried 3 times to update without success.

**Comment by swisspol** [comment]
The ZIP file on disk in `~/Library/Android/sdk/temp` is indeed 772,313,856 bytes.

**Comment by DanAlbert** [comment]
2.0? What is studio doing?

I've let the studio folks know.

**Comment by swisspol** [comment]
The previous version installed as part of Android Studio was 1.0 - it's the "NDK bundle" for Android Studio though, so I guess that's why it has its own versioning scheme:

![image](https://cloud.githubusercontent.com/assets/627915/13828416/a5b075ec-eb7e-11e5-947d-1600e709cb79.png)

**Comment by swisspol** [comment]
Also note that the old Android SDK Manager does not report that there's an update available for the NDK bundle, contrary to the "Android SDK" pane in Android Studio. This is all very confusing...

**Comment by swisspol** [comment]
I just tried on a completely new Mac running 10.11.3, installing Android Studio from scratch, then attempting to install NDK 2.0.0, same download error.

Finally, it's worth noting that the `android-ndk-r11-darwin-x86_64.zip` file downloaded by Android Studio doesn't match either the file size of the one from http://developer.android.com/ndk/downloads/index.html.

**Comment by DanAlbert** [comment]
Oh, I'm certain the bug is on our end, not yours :) I'm talking with the studio folks about it right now to narrow down where the problem is.

> Finally, it's worth noting that the android-ndk-r11-darwin-x86_64.zip file downloaded by Android Studio doesn't match either the file size of the one from http://developer.android.com/ndk/downloads/index.html.

That's actually https://github.com/android-ndk/ndk/issues/22. Should be fixed tomorrow morning.

**Comment by swisspol** [comment]
OK! BTW side question, my understanding is that the previous NDK bundled with Android Studio was defaulting to GCC. Is the new one going to default to Clang to follow the NDK recommendations? And if that's not the case, how to do I configure the gradle settings file in Android Studio project to use Clang?

Here's my current NDK entry in Gradle's settings file (some lines removed for clarity):
```
android.ndk {
        platformVersion = "18"  // Must be in-sync with minSdkVersion.apiLevel
        moduleName = "jni"
        CFlags.add("-std=c99")

        cppFlags.add("-std=c++11")
        cppFlags.add("-fexceptions")
        cppFlags.add("-frtti")

        stl = "c++_shared"  // http://developer.android.com/ndk/guides/cpp-support.html
        ldFlags.add("-Wl,--gc-sections")
        ldLibs.add("log")
    }
```

**Comment by DanAlbert** [comment]
So, for the main question here: it's actually that older versions of Android Studio are fed from a different set of data (not all packages are going to be valid for every version of Studio), and that data didn't get updated. People are fixing it now, but if you want an immediate fix, update to a newer version of Android Studio.

**Comment by DanAlbert** [comment]
FYI, r11b is now live: http://developer.android.com/ndk/downloads/index.html#download

The data for the older versions of Studio should also be fixed (I know I fixed it, I just don't know if that data goes live on a different schedule), so give that a try.

**Comment by DanAlbert** [comment]
Of course, right after I posted that I was told that those are actually broken right now. Working on a fix...

**Comment by DanAlbert** [comment]
Okay, the new download should be live in 10 minutes. Unfortunately you'll need to manually uninstall and reinstall "r11" to get r11b due to some technical issues with the SDK manager :(

Alternatively, the Studio folks tell me that the version of Studio in the preview channel is getting very close to release, so you could also just update now and avoid the hassle.

**Comment by swisspol** [comment]
I don't understand: I successfully installed 11.0.0 this morning in Android Studio:

![image](https://cloud.githubusercontent.com/assets/627915/13865988/53c0a1e4-ec6e-11e5-920e-b8a5f1839578.png)

Do I need to uninstall and re-install it (what wrong with 11.0.0 anyway?) or is only for direct downloads?

**Comment by DanAlbert** [comment]
Changelog is here: http://developer.android.com/ndk/downloads/index.html It's missing the detail that we fixed issue #6. If you don't use ASAN or `ndk-gdb`, r11 is just fine.

Yes, you'll need to uninstall and reinstall to pick up r11b. Direct downloads are unaffected (the problem is a "bug" in the SDK manager used by Android Studio versions < 2, including the standalone SDK manager).

**Comment by swisspol** [comment]
I just installed updated the NDK on another Android Studio machine which still had 1.0.0. It now says 11.0.0, not 11.0.0b or something. Are you saying you have 2 versions called 11.0.0 for Android Studio, but one is r11 while the other is r11b under the hood?

**Comment by DanAlbert** [comment]
Correct. I know it's ugly and confusing, but it's actually the best we could do with the old SDK manager because the schema (which is a defined interface with the already shipped version of Studio) doesn't allow anything but integer release numbers...
