### ISSUE TITLE
fix ndk_helper's GLContext issue

### ISSUE THREAD

**Issue by DanAlbert** [android-ndk/ndk#250]
https://code.google.com/p/android/issues/detail?id=228354#c10

**Comment by ggfan** [comment]
the consolidated version is in this PR:

**Comment by DanAlbert** [comment]
> it might be better to remove ndk's copy since it is way out of maintenance; for people need it, the latest maintained source is in the samples mentioned above.

That's a lot of unnecessary churn for people. IMO it would be better to get the NDK copy fixed and get the samples to start using that instead of your own fork (and when you find bugs, fix them upstream so they don't go unnoticed by us for years).

**Comment by ggfan** [comment]
make sense. please send me some instructions on how to create a branch for upcoming ndk release, I could help to update it, and probably also for bug https://code.google.com/p/android/issues/detail?id=222601.
