### ISSUE TITLE
STL (-DANDROID_STL=c++_static) support sets wrong CXX Includes in android.toolchain.cmake

### ISSUE THREAD

**Issue by ketanm** [android-ndk/ndk#252]
#### Description

I am compiling C++ based project using android.toolchain.cmake script with intention of using NdkMediaCodec. First, I had to modify android.toolchain.cmake file from Android/sdk/cmake to contain latest NDK version by setting flag as below:
set(ANDROID_NDK_REVISION 13)

Later I used following command to generate my required build environment.
cmake -DCMAKE_TOOLCHAIN_FILE=$ANDROID_CMAKE_HOME/android.toolchain.cmake -DANROID_TOOLCHAIN="clang" \
      -DANDROID_NDK=$ANDROID_NDK \
      -DCMAKE_BUILD_TYPE=Release \
      -DANDROID_NATIVE_API_LEVEL="android-21" -DANDROID_STL="c++_static"

However this results into failing to find <iostream> headers. Looking at include paths it shows that toolchain is setting path as below:
clang++ ....  -isystem /Users/NAME/Library/Android/sdk/ndk-bundle/sources/cxx-stl/llvm-libc++/libcxx/include ...

However actual toolchain layout for llvm-libc++ is different. It contains includes under llvm-clang++ folder but not under llvm-clang++/libcxx.

This is due to incorrect setup in android.toolchain.clang as seen below:
       set(CMAKE_CXX_STANDARD_INCLUDE_DIRECTORIES
                "${ANDROID_NDK}/sources/cxx-stl/${ANDROID_STL_PREFIX}/**libcxx**/include"
                "${ANDROID_NDK}/sources/android/support/include"
                "${ANDROID_NDK}/sources/cxx-stl/${ANDROID_STL_PREFIX}abi/libcxxabi/include")

#### Environment Details
Pkg.Desc = Android NDK
Pkg.Revision = 13.1.3345770
Android Studio = 2.2
system: cmake
Host OS: Mac
Compiler: Clang++
STL: c++_static
API: 21

**Comment by DanAlbert** [comment]
Hmm. That isn't what I see in our cmake toolchain file (the string "libcxx" isn't present at all).

Are you on some old version of Studio? Older versions (not a Studio user or developer, so I don't know which, but I think it was 2.1 or older?) packaged their own cmake toolchain file that will only work with NDK r12 and older. Newer versions use the cmake toolchain file that we ship in the NDK.

**Comment by ketanm** [comment]
Hi Dan,

I updated environment. It is latest 2.2.2 Build on Oct 18 2016. So this is latest version. I have uninstalled and reinstalled Studio + NDK twice.

Based on your comment, I did search on the Android/sdk folder and found that there is another android.toolchain.cmake which is found under sdk/ndk-bundle/build/cmake. This one is correct.

So, conclusion is to install cmake from Android Studio but **don't use sdk/cmake/3.6.x/android.toolchain.cmake** rather use sdk/ndk-bundle/build/cmake.

I think there should be some documentation somewhere stating which one to use. I found lot of confusing information on the net. Hopefully this post helps other people too.

**Comment by DanAlbert** [comment]
I'll reopen this so we remember to get a note added to the docs.

**Comment by DanAlbert** [comment]
@qchong: might be more in Adarsh's territory, but it would be good to add a note along the lines of:

> Note that older Android Studio versions (2.2? confirm with someone on the studio side) would use their own cmake toolchain file rather than the NDK's. This file is not updated. To use the NDK's version, update to a newer version of Studio.

**Comment by chaoren** [comment]
> First, I had to modify android.toolchain.cmake file from Android/sdk/cmake to contain latest NDK version by setting flag as below:
set(ANDROID_NDK_REVISION 13)

Yeah, don't do that. That check is there for a reason. I'm pretty sure the error message says that the cmake file only works for r12. If r12 is deprecated then we should just remove that file from the cmake package to reduce confusion like this.

**Comment by ketanm** [comment]
@chaoren, please see my comment on [29th Nov](https://github.com/android-ndk/ndk/issues/252#issuecomment-263741696). I did find updated cmake installed with NDK after which I didn't had to modify anything.
