### ISSUE TITLE
cmake toolchain file does not set CMAKE_CXX_COMPILER_VERSION

### ISSUE THREAD

**Issue by plabath** [android-ndk/ndk#253]
I've been trying to build llvm with the toolchain file. The first error I've run into is that it tries to check the compiler version (and then aborts, because it thinks the compiler is too old). I am not sure if this is the correct fix, but adding these two defines enabled me to get past that error:

set(CMAKE_CXX_COMPILER_VERSION 3.8)
set(CMAKE_CXX_STANDARD_COMPUTED_DEFAULT 98)

**Comment by plabath** [comment]
ps: I've put that in the `if($compiler == clang)` section. Something similar will probably be needed for gcc too.

**Comment by plabath** [comment]
No changes should be necessary to the gcc branch. It's only necessary for clang because we override standard cmake checks with 
	set(CMAKE_CXX_COMPILER_ID_RUN TRUE)

**Comment by ligfx** [comment]
Related to #222

**Comment by DanAlbert** [comment]
https://android-review.googlesource.com/c/326383/ Thanks @ligfx!
