### ISSUE TITLE
cmake toolchain doesn't work with cmake 3.7+

### ISSUE THREAD

**Issue by hszhsh** [android-ndk/ndk#254]
I'm using cmake with ndkr13b, and have a problem of selecting clang toolchain.
If I provide -DANDROID_TOOLCHAIN=gcc, cmake works fine. But with the default clang toolchain, cmake still shows the message "-- Android: Selected GCC toolchain 'arm-linux-androideabi-4.9'", and won't pass the compiler check.
Here's my cmake command. Did I miss something?
```
cmake -DCMAKE_TOOLCHAIN_FILE=${ANDROID_NDK}/build/cmake/android.toolchain.cmake -DANDROID_ABI=armeabi-v7a  -DANDROID_TOOLCHAIN=clang ${PROJECT_PATH}
```

**Comment by DanAlbert** [comment]
I'll take a closer look tomorrow, but just FYI you shouldn't need to pass `-DANDROID_TOOLCHAIN` at all. Clang is the default. Could be that we don't handle the explicit argument correctly.

**Comment by hszhsh** [comment]
I tried command without -DANDROID_TOOLCHAIN, and got the some result.
My cmake version is 3.7.1.

**Comment by DanAlbert** [comment]
I assumed as much, but was worth a shot.

**Comment by hszhsh** [comment]
I have changed the cmake version to 3.6.3, and It works.

**Comment by xyzz** [comment]
I had the same issue and solved it in the same way (downgrade to 3.6.3), can you perhaps document that cmake 3.7.1 does not work? Although at this point it reminds me of a certain other build system...

**Comment by DanAlbert** [comment]
We should at least document this. I don't know if the Studio team is planning on updating CMake or not.

**Comment by osfans** [comment]
I have the same question when cmake is 3.7.1

**Comment by DanAlbert** [comment]
This is something we're scheduled to talk about in the next Android C++ meeting, but December is a pretty difficult month to actually make meetings happen in :) I'll hopefully have some answers in a couple weeks.

**Comment by DanAlbert** [comment]
FYI, I think for the short term anyway that answer is going to continue being "you need to use the cmake that comes with the SDK", but we should at least get some docs in place to make that clear.

**Comment by DanAlbert** [comment]
Okay, the Studio folks are going to look in to getting support for vanilla (not the Studio fork) cmake. There are some changes that need to get upstreamed and possibly some more work that needs to be done for the new version, so we don't know when this is going to be available, but it is something we're investigating.

**Comment by DanAlbert** [comment]
Okay, we have a tracking bug on the Studio side now: http://b.android.com/231562

Closing this one since afaik there's nothing to actually be done for the NDK on this.

**Comment by xyzz** [comment]
Why is it a studio-only issue? There's a cmake toolchain file: `${ANDROID_NDK}/build/cmake/android.toolchain.cmake` provided with the NDK. You don't need studio installed to attempt to use it.

**Comment by DanAlbert** [comment]
Ah, I thought it was only a problem when used via Studio. I guess I have some work to do then.

**Comment by DanAlbert** [comment]
Merged into r15. Will be in beta 2.
