### ISSUE TITLE
CLEAR VARS typo?

### ISSUE THREAD

**Issue by twaik** [android-ndk/ndk#257]
#### Description

in $(NDK_ROOT_PATH)/build/core/clear-vars.mk

line 19: $(call clear-src-tags)

but clear-src-tags is undeclared. Only clear-all-src-tags is declared in $(NDK_ROOT_PATH)/build/core/definitions.mk line 1160

I don't know what clear-all-src-tags does but maybe it is important.

#### Environment Details

* NDK Version: r13b

**Comment by DanAlbert** [comment]
That line was broken from the moment it was committed. It looks like the correct call was added to build-binary.mk later, so I think everything is working correctly. I'll clean up the misleading line though. Thanks for catching this.

https://android-review.googlesource.com/465057
