### ISSUE TITLE
ndk-r14-beta1, clang error in backend

### ISSUE THREAD

**Issue by 1bsyl** [android-ndk/ndk#259]
Trying the ndk-r14-beta1, it fails compiling with an error in backend

[log.txt](https://github.com/android-ndk/ndk/files/648727/log.txt)
[SDL_wave-762788.c.zip](https://github.com/android-ndk/ndk/files/648725/SDL_wave-762788.c.zip)
[SDL_wave-762788.sh.zip](https://github.com/android-ndk/ndk/files/648726/SDL_wave-762788.sh.zip)

**Comment by 1bsyl** [comment]
It occurs with "armeabi", but not with "armeabi-v7a".

**Comment by pirama-arumuga-nainar** [comment]
The error seems to stem from r273581.  Fixed in upstream, likely by r277439.  The fix is not in the latest Android Clang, but should be included in the next update.

**Comment by 1bsyl** [comment]
Still happening with NDK r14-beta2.

**Comment by stephenhines** [comment]
Yes, unfortunately Pirama was referring to our next platform toolchain update. It was far too late to get that one into NDK r14-beta2. We're hoping that it will be in r15 finally.

**Comment by 1bsyl** [comment]
Ok, I was wondering whether the toolchain had been updated. Thanks for the information.

**Comment by 1bsyl** [comment]
Just want to clarify, that it's a regression: it was compiling with clang in ndk-r13. Maybe there are more side effects than mine.

**Comment by DanAlbert** [comment]
Unfortunately there's essentially no such thing as a compiler update with zero regressions :( As @stephenhines said though, we'll have the fix for this ready for r15.

**Comment by 1bsyl** [comment]
Still happening with NDK r15-beta1.

**Comment by enh** [comment]
yeah, for internal logistical reasons (basically "not destabilizing O") there's no clang update in r15beta1, but we're still aiming to have this fixed in r15 (even if it means breaking our usual rule of having the big scary changes like a new compiler in beta1).

**Comment by DanAlbert** [comment]
From our meeting today it sounds like we'll have an updated compiler pretty soon, so it should be ready for beta 2.

**Comment by DanAlbert** [comment]
FYI we have an updated compiler in master now. I'm working on pushing cherry-picks through presubmit for the r15 branch, but you can always fetch the [canary build of master](https://android.googlesource.com/platform/ndk/+/master/docs/ContinuousBuilds.md) if you want to make sure we fixed it.

There's still going to be another rev of the compiler before r15 beta 2 is ready, but it's not another update, just some build time fixes for openmp.

**Comment by 1bsyl** [comment]
Confirmed it's fixed in r15-beta2
