### ISSUE TITLE
r14 beta 1 regression: can't build sqlite3 on mips

### ISSUE THREAD

**Issue by yan12125** [android-ndk/ndk#261]
#### Description

Since r14 beta1, building sqlite3 fails with mysterious "undefined references" errors.

Steps to reproduce:
```
wget http://www.sqlite.org/2016/sqlite-autoconf-3150200.tar.gz
wget https://gist.githubusercontent.com/yan12125/8f92abad081ae5d7bb92d5569865c9c6/raw/c0c49e70175f2b16e12c5fb56431d5f51afcf28b/build.sh
tar xf sqlite-autoconf-3150200.tar.gz
cd sqlite-autoconf-3150200
bash ../build.sh
```
Linking sqlite3 executable fails with:
```
/bin/sh ./libtool  --tag=CC   --mode=link /home/yen/tmp/android-ndk-r14-beta1/toolchains/llvm/prebuilt/linux-x86_64/bin/clang -target mipsel-none-linux-android -gcc-toolchain /home/yen/tmp/android-ndk-r14-beta1/toolchains/mipsel-linux-android-4.9/prebuilt/linux-x86_64 -D_REENTRANT=1 -DSQLITE_THREADSAFE=1     -DSQLITE_ENABLE_FTS3 -DSQLITE_ENABLE_RTREE -DSQLITE_ENABLE_EXPLAIN_COMMENTS -fno-integrated-as  --sysroot=/home/yen/tmp/android-ndk-r14-beta1/platforms/android-21/arch-mips/usr -o sqlite3 sqlite3-shell.o sqlite3-sqlite3.o  
libtool: link: /home/yen/tmp/android-ndk-r14-beta1/toolchains/llvm/prebuilt/linux-x86_64/bin/clang -target mipsel-none-linux-android -gcc-toolchain /home/yen/tmp/android-ndk-r14-beta1/toolchains/mipsel-linux-android-4.9/prebuilt/linux-x86_64 -D_REENTRANT=1 -DSQLITE_THREADSAFE=1 -DSQLITE_ENABLE_FTS3 -DSQLITE_ENABLE_RTREE -DSQLITE_ENABLE_EXPLAIN_COMMENTS -fno-integrated-as --sysroot=/home/yen/tmp/android-ndk-r14-beta1/platforms/android-21/arch-mips/usr -o sqlite3 sqlite3-shell.o sqlite3-sqlite3.o 
sqlite3-shell.o: In function `main':
shell.c:(.text+0x2428): undefined reference to `$BB1_265'
sqlite3-sqlite3.o: In function `openDirectory':
sqlite3.c:(.text+0x2f6d4): undefined reference to `$BB488_16'
sqlite3-sqlite3.o: In function `sqlite3VdbeHalt':
sqlite3.c:(.text+0x584b8): undefined reference to `$BB832_97'
sqlite3-sqlite3.o: In function `sqlite3CreateIndex':
sqlite3.c:(.text+0xa60ac): undefined reference to `$BB1240_26'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [Makefile:509: sqlite3] Error 1
```
The error occurs when I set ANDROID_NDK to ~/android-ndk-r14-beta1 while things are OK for ~/android-ndk-r13b, so I guess it's a regression.

The error occurs on MIPS only. All other targets, including MIPS64, build fine. See https://travis-ci.org/yan12125/python3-android/builds/183540670 for build log of all targets and https://github.com/yan12125/python3-android/ for complete build scripts.

#### Environment Details

Not all of these will be relevant to every bug, but please provide as much
information as you can.

* NDK Version: 14.0.3529234-beta1. Downloaded from https://dl.google.com/android/repository/android-ndk-r14-beta1-linux-x86_64.zip, sha512=d36567d96339a4662f87aae645e2bb01ecd8c839b69b71fcc8abee7745a9518eece31bf45b762f385250e47147d1927743ce0639fc0103b73d5bd8ced3881704
* Build sytem: custom
* Host OS: Arch Linux latest
* Compiler: Clang
* ABI: mips
* STL: N/A
* NDK API level: 21
* Device API level: N/A

**Comment by pirama-arumuga-nainar** [comment]
This was fixed by LLVM r276361 (https://llvm.org/bugs/show_bug.cgi?id=28634).

Changing the optimization levels helped with a similar issue with v8 on AOSP (https://android-review.googlesource.com/#/c/264078/).  Can you see if a similar WAR helps for sqlite3?

**Comment by DanAlbert** [comment]
@pirama-arumuga-nainar: I take it the fix isn't in any Android clang build yet?

**Comment by pirama-arumuga-nainar** [comment]
@DanAlbert It should be covered by the next Clang build that @stephenhines is preparing.

**Comment by pirama-arumuga-nainar** [comment]
@DanAlbert In other words, no, it is not in any Android clang yet.

**Comment by DanAlbert** [comment]
Assigning to myself for handling the NDK side of the update then. Thanks for the quick analysis.

**Comment by yan12125** [comment]
Adding ```-O2``` to CFLAGS works fine!

**Comment by yan12125** [comment]
The issue is still in NDK r14 beta 2. Is NDK's clang going to be updated in r14?

**Comment by DanAlbert** [comment]
No. We unfortunately don't have the ability to do point fixes of the compiler (we just take whatever compiler the Android platform is using), and we don't make major compiler updates late in a release cycle unless things have gone catastrophically wrong.

**Comment by yan12125** [comment]
Confirmed that build 3981061 fixes the problem, thanks!
