### ISSUE TITLE
Mistake in documentation/error message?

### ISSUE THREAD

**Issue by timatoe** [android-ndk/ndk#264]
Updated to the latest version of the NDK, added the below line to my Application.mk file to revert to the old behavior: (as per the instructions in the CHANGELOG.md file and comments in build-binary.mk file)

`APP_ALLOW_MISSING_DEPS  := false`

I get the following error messages in the Gradle Console:

`Android NDK: Module ffmpegutils depends on undefined modules: x264 c z`   
`Android NDK: Aborting (set APP_ALLOW_MISSING_DEPS=true to allow missing dependencies)`

The error message says to set the flag to true to allow missing dependencies contradicting the instructions in the change log.

Is this correct?

**Comment by DanAlbert** [comment]
Changelog was wrong, error message was right. I just fixed the changelog. Sorry about that!

**Comment by DanAlbert** [comment]
(actually, leaving this open because I need to fix the checked in copy, but tests are running atm)
