### ISSUE TITLE
omp.h not found with gcc

### ISSUE THREAD

**Issue by rcketscientist** [android-ndk/ndk#267]
#### Description

Functional build fails after upgrading to latest r14, cannot find omp.h.  GCC is forced.  Swapping back to r13 works.

#### Environment Details

Not all of these will be relevant to every bug, but please provide as much
information as you can.

Pkg.Revision = 14.0.3529234-beta1

* Build sytem: ndk-build? ndk-build
* Host OS: Windows
* Compiler: GCC.  Clang won't support openMP until r15.  This is a gcc regression with r14.

**Comment by DanAlbert** [comment]
We have a test that shows that this works for ndk-build for the trivial case: https://android.googlesource.com/platform/ndk/+/ndk-r14-release/tests/device/test-openmp/

There's probably some missing information here. You should check that you've passed `-fopenmp` in your cflags (I think `omp.h` is available even without this, but it wouldn't hurt to check). Which ABI were you seeing the issue with?

**Comment by rcketscientist** [comment]
I can swap ndk-bundle from 14b1 to the official 13 and it works fine.  '-fopenmp' is of course set.  The only difference in either run is swapping the ndk-bundle.  14 is installed via AS.  13 is downloaded from the developer front end.  I build for:

abiFilters "armeabi-v7a", "arm64-v8a", "x86", "x86_64"

it failed immediately.

**Comment by DanAlbert** [comment]
Hmm. I wonder if there's an issue with how gradle is invoking ndk-build. It wouldn't be the first time. I'll take a look.

**Comment by DanAlbert** [comment]
Ah, this was caused by https://github.com/android-ndk/ndk/issues/229#issuecomment-267487498

I reverted the breaking change a while ago, so this is already fixed for beta 2.

**Comment by mvitez** [comment]
Same problem (omp.h not found), but with r14beta2 and r13b. r12b works. I've tested directly your test https://android.googlesource.com/platform/ndk/+/ndk-r14-release/tests/device/test-openmp/
I have tested on Windows, Linux and Mac, by simply running ndk-build.

**Comment by rcketscientist** [comment]
Are you sure 13b isn't working?  I've been using 

Pkg.Revision = 13.1.3345770 

without issue.

**Comment by mvitez** [comment]
Yes. That exact version. The test I did was very very simple. Downloaded the NDK, downloaded the openmp test and run ndk-build. Only r12b works.

**Comment by rcketscientist** [comment]
What is failing if you don't mind saving me the time of running it myself?

**Comment by mvitez** [comment]
[arm64-v8a] Compile        : fib <= fib.c
jni/fib.c:4:10: fatal error: 'omp.h' file not found
#include <omp.h>
         ^
1 error generated.
make: *** [obj/local/arm64-v8a/objs/fib/fib.o] Error 1

**Comment by rcketscientist** [comment]
That test will run clang by default. Are you forcing GCC?

**Comment by mvitez** [comment]
No. Ok, so this is the problem. How can I force GCC?

**Comment by mvitez** [comment]
Ok, found, export NDK_TOOLCHAIN_VERSION=4.9 (or whatever).
I think that if clang is not fully working, it should not be the default...

Thanks.

**Comment by DanAlbert** [comment]
> I think that if clang is not fully working, it should not be the default...

No compiler is perfect. GCC is missing a ton of features too.

**Comment by rcketscientist** [comment]
True, but it is a fair point.  It's missing an _existing_ feature set which was undocumented and undoubtedly caused many more like myself to lose many hours debugging clang build scripts when it swapped only to find it wasn't a clean swap and all that time was a dead end.  

Not gonna beat a dead horse, but anytime even a small ball is dropped on a project of this scope it can mean hundreds of hours of lost productivity.  Look at the disaster that AS 2.2 was.  Or the hopeless case of Android 4.4.  I can't even describe how many hours I lost on those nightmares (then multiply that by thousands).  Pretty sure we woulda cured cancer if we applied that time better ;-).

**Comment by DanAlbert** [comment]
> True, but it is a fair point. It's missing an existing feature set which was undocumented and undoubtedly caused many more like myself to lose many hours debugging clang build scripts when it swapped only to find it wasn't a clean swap and all that time was a dead end.

We do have a bug filed. A quick search for "ndk openmp clang" would have saved you a lot of time :( I can add something to the known issues list (https://android-review.googlesource.com/336965), but it just isn't feasible to make that be a list of all currently open issues.

**Comment by rcketscientist** [comment]
I have no desire to be contentious so this is simply a clarification of how this probably went for most.  I didn't even know ndk was public on github and if you search for "android ndk release notes" it's only trending into the top ten recently.  It wasn't even on the first page before.  Since clang supports openmp and developer doc was (still?) very sparse the trail got very confusing until I finally got here.  So that's cool and dandy that it was a known deficiency when clang was forced, but the traceability is hardly foolproof.  Knowing about this, I wouldn't have wasted ten minutes on it, but for most this repo is an unknown.

**Comment by stephenhines** [comment]
Although upstream Clang claims support for OpenMP, true cross-platform OpenMP development is not something that they currently can do (http://lists.llvm.org/pipermail/openmp-dev/2017-February/001659.html). We are working on it, though, and hope that it makes the r15 NDK release.

**Comment by culurciello** [comment]
In order to compile with GCC, not clang. I have to go to:

```
cd apps-android/learner/app/src/main
export NDK_TOOLCHAIN_VERSION=4.9
~/Library/Android/sdk/ndk-bundle/ndk-build V=1
```

Setting `NDK_TOOLCHAIN_VERSION=4.9` in `Application.mk` does not work for me on OS X

**Comment by DanAlbert** [comment]
@culurciello: on NDK r14 beta 1, presumably? There was a bug in that beta that should be resolved in beta 2.

**Comment by culurciello** [comment]
I have updated to say: ndk 13.1 where can I get 14b1?

**Comment by enh** [comment]
you can type "ndk r14" into Google, which will give you https://github.com/android-ndk/ndk/wiki :-)
