### ISSUE TITLE
include bionic/libc/kernel/android/scsi headers in NDK?

### ISSUE THREAD

**Issue by enh** [android-ndk/ndk#269]
#### Description

the toybox eject.c fails to build because there's no <scsi/sg.h> in the NDK. this builds fine in the platform because it's one of the "weird" headers in bionic/libc/kernel/android/. we include most of those in the NDK, but not scsi/ or adf/.

iirc we said there was no point having the scsi headers in the NDK, but in our tree fio, strace, and toybox would all benefit from this (in the sense of "we might be able to build them with the NDK in future".

#### Environment Details

* NDK Version: 14.0.3529234-beta1
* Build sytem: standalone toolchain with unified headers (but find(1) says the headers just aren't in the NDK period)
* Host OS: goobuntu
* Compiler: clang
* ABI: arm64 and x86_64
* NDK API level: unified headers

**Comment by DanAlbert** [comment]
The bionic change actually got made, but because we need to run the versioner over the bionic headers to manually update the prebuilts, this hasn't made it to the NDK yet.

**Comment by DanAlbert** [comment]
Part 1 (preprocessing the headers): https://android-review.googlesource.com/317777

Will still need to update the prebuilts in the NDK after that goes in, and then cherry-pick to r14.
