### ISSUE TITLE
Clang 4.0

### ISSUE THREAD

**Issue by Zingam** [android-ndk/ndk#275]
Can we get Clang 4.0 WITH the C++17 features enabled and OpenMP support in the next beta SDK. I guess it will be r15?

**Comment by DanAlbert** [comment]
We update Clang constantly. A 4.0 based compiler will be in the NDK once the Android Platform adopts one.

OpenMP for Clang covered here: https://github.com/android-ndk/ndk/issues/9

tl;dr: Clang's OpenMP doesn't work for cross-compiler setups yet, and this needs to be fixed upstream.

**Comment by Zingam** [comment]
I see Clang's adoption is not the NDKs team responsibility then.

**Comment by DanAlbert** [comment]
Nope. The compiler team delivers Clang to the platform and I copy it into the NDK.
