### ISSUE TITLE
Swift language

### ISSUE THREAD

**Issue by Zingam** [android-ndk/ndk#276]
Is it true that Google is eyeing Swift?
Are there any plans to include the Swift compiler in the NDK anytime soon. It is an LLVM supported, C compatible language after all. It should be a viable alternative to C/C++ native development.

**Comment by DanAlbert** [comment]
https://www.reddit.com/r/androiddev/comments/4tm8i6/were_on_the_android_engineering_team_and_built/d5ime2a/?context=10000

We have no plans to support additional languages in the NDK (let's make C++ work well first!)

That said, I believe the Swift project supports Android on its own (or at least there was some work going on for it a while back). While there will not be official support for it from us, you might be able to use Swift from their support.
