### ISSUE TITLE
Can't access many OpenGL ES extensions

### ISSUE THREAD

**Issue by mattscar** [android-ndk/ndk#279]
**Description**

In Java, if I run `GLES32.glGetString(GLES32.GL_EXTENSIONS)`, I get a list of 74 supported extensions for OpenGL ES. But if I run `glGetString(GL_EXTENSIONS)` in my NDK code, I only get 38 extensions. I'd like to access the full set of extensions.

Someone recommended linking to GLESv2 instead of GLESv3. When I do that, I get a series of undefined references to OpenGL ES 3.x functions, such as `glMapBufferRange` and `glBindVertexArray`.

**Environment Details**

* NDK Version: 13.1.3345770
* Build sytem: CMake
* Host OS: Windows 7
* Compiler: Clang
* ABI: armeabi-v7a
* STL: c++_static
* Device API level: 24

I'm testing my applications on a Google Pixel.

**Comment by mattscar** [comment]
Sorry for my mistake. It looks like `glGetString(GL_EXTENSIONS)` doesn't return the full list of extensions.

To get the full list, you need to call `glGetIntegerv` with `GL_NUM_EXTENSIONS`. Then you can iterate through the extensions by calling `glGetStringi` with `GL_EXTENSIONS`.

**Comment by critsec** [comment]
I can't reopen this, but glGetString() should return the same list of extensions as you get by iterating with glGetIntegerv (which is only supported in OpenGL ES 3.0 and higher). And you should get the same list of extensions from both Java GLESxx.glGetString and NDK glGetString, assuming the GL context was created with the same options for both of them.

Is it possible that you were using an ES 1.x context in your NDK code path rather than an ES 2+ context? The numbers you give sound about like what I'd expect from that.

Thanks,
Jesse (Android Platform Graphics Team)

**Comment by DanAlbert** [comment]
@critsec: do you want me to reopen this one, or should we file a b.android.com one to track the platform issue?

**Comment by critsec** [comment]
Reopen would be great. We'll file a bug if it wasn't a context version mistake in the app.

**Comment by mattscar** [comment]
My activity sets the EGL context version with `glSurfaceView.setEGLContextClientVersion(3)`. I'm also linking libGLESv3.so into the NDK application. So I should be accessing OpenGL ES 3.x.

To test the issue, I ran the following code in my NDK app:
`__android_log_print(ANDROID_LOG_INFO, TAG, "Extensions: %s", glGetString(GL_EXTENSIONS));`

I've attached the file containing the resulting string, which contains the names of 38 extensions:
[glGetString_extensions.txt](https://github.com/android-ndk/ndk/files/703128/glGetString_extensions.txt)

When I run `glGetIntegerv(GL_NUM_EXTENSIONS, &max)`, the function sets `max` equal to 74, implying that 74 extensions are available. I've tried code to access one of the extra extensions, and it worked. So those extra extensions are available.

**Comment by mattscar** [comment]
I think I see the problem. The string returned by `glGetString(GL_EXTENSIONS)` is being truncated. This may be due to the constraints of `__android_log_print`.

**Comment by enh** [comment]
yeah, android logging is limited to 1024 bytes/line.

**Comment by mattscar** [comment]
Sure enough. I think this can be safely closed now. My apologies for the false alarm.
