### ISSUE TITLE
libandroid_support causes duplicate symbol issues with static executables

### ISSUE THREAD

**Issue by plabath** [android-ndk/ndk#280]
Using NDK r14-beta1. Compiling a simple static executable fails because of multiply defined symbols between libc and libandroid_support. This happens because the toolchain file forces android_support into CMAKE_CXX_STANDARD_LIBRARIES_INIT.

It only does this for c++_static, for reasons which are beyond me. However, removing android_support from this list makes the link succeed.

See below for a repro:

$ cat ../CMakeLists.txt 
cmake_minimum_required(VERSION 3.1)
project(HELLO)
set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} -static")
add_executable(Hello a.cc)
labath4 /tmp/X/b $ cat ../a.cc 
int main () { 
  return 0;
}
labath4 /tmp/X/b $ cmake .. -DANDROID_ABI=armeabi -DCMAKE_TOOLCHAIN_FILE=~/local/android-ndk-r14-beta1/build/cmake/android.toolchain.cmake -DANDROID_STL=c++_static
-- Check for working C compiler: /usr/local/google/home/labath/local/android-ndk-r14-beta1/toolchains/llvm/prebuilt/linux-x86_64/bin/clang
-- Check for working C compiler: /usr/local/google/home/labath/local/android-ndk-r14-beta1/toolchains/llvm/prebuilt/linux-x86_64/bin/clang -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/local/google/home/labath/local/android-ndk-r14-beta1/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++
-- Check for working CXX compiler: /usr/local/google/home/labath/local/android-ndk-r14-beta1/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: /tmp/X/b
labath4 /tmp/X/b $ make VERBOSE=1
/usr/local/google/home/labath/local/cmake/bin/cmake -H/tmp/X -B/tmp/X/b --check-build-system CMakeFiles/Makefile.cmake 0
/usr/local/google/home/labath/local/cmake/bin/cmake -E cmake_progress_start /tmp/X/b/CMakeFiles /tmp/X/b/CMakeFiles/progress.marks
make -f CMakeFiles/Makefile2 all
make[1]: Entering directory `/tmp/X/b'
make -f CMakeFiles/Hello.dir/build.make CMakeFiles/Hello.dir/depend
make[2]: Entering directory `/tmp/X/b'
cd /tmp/X/b && /usr/local/google/home/labath/local/cmake/bin/cmake -E cmake_depends "Unix Makefiles" /tmp/X /tmp/X /tmp/X/b /tmp/X/b /tmp/X/b/CMakeFiles/Hello.dir/DependInfo.cmake --color=
Dependee "/tmp/X/b/CMakeFiles/Hello.dir/DependInfo.cmake" is newer than depender "/tmp/X/b/CMakeFiles/Hello.dir/depend.internal".
Dependee "/tmp/X/b/CMakeFiles/CMakeDirectoryInformation.cmake" is newer than depender "/tmp/X/b/CMakeFiles/Hello.dir/depend.internal".
Scanning dependencies of target Hello
make[2]: Leaving directory `/tmp/X/b'
make -f CMakeFiles/Hello.dir/build.make CMakeFiles/Hello.dir/build
make[2]: Entering directory `/tmp/X/b'
[ 50%] Building CXX object CMakeFiles/Hello.dir/a.cc.o
/usr/local/google/home/labath/local/android-ndk-r14-beta1/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++  -target armv5te-none-linux-androideabi -gcc-toolchain /usr/local/google/home/labath/local/android-ndk-r14-beta1/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64 --sysroot=/usr/local/google/home/labath/local/android-ndk-r14-beta1/platforms/android-9/arch-arm   -isystem /usr/local/google/home/labath/local/android-ndk-r14-beta1/sources/cxx-stl/llvm-libc++/include -isystem /usr/local/google/home/labath/local/android-ndk-r14-beta1/sources/android/support/include -isystem /usr/local/google/home/labath/local/android-ndk-r14-beta1/sources/cxx-stl/llvm-libc++abi/include  -g -DANDROID -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -march=armv5te -mtune=xscale -msoft-float -fno-integrated-as -mthumb -Wa,--noexecstack -Wformat -Werror=format-security -std=c++11 -g -DANDROID -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -march=armv5te -mtune=xscale -msoft-float -fno-integrated-as -mthumb -Wa,--noexecstack -Wformat -Werror=format-security -std=c++11    -o CMakeFiles/Hello.dir/a.cc.o -c /tmp/X/a.cc
[100%] Linking CXX executable Hello
/usr/local/google/home/labath/local/cmake/bin/cmake -E cmake_link_script CMakeFiles/Hello.dir/link.txt --verbose=1
/usr/local/google/home/labath/local/android-ndk-r14-beta1/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++  -target armv5te-none-linux-androideabi -gcc-toolchain /usr/local/google/home/labath/local/android-ndk-r14-beta1/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64 --sysroot=/usr/local/google/home/labath/local/android-ndk-r14-beta1/platforms/android-9/arch-arm  -g -DANDROID -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -march=armv5te -mtune=xscale -msoft-float -fno-integrated-as -mthumb -Wa,--noexecstack -Wformat -Werror=format-security -std=c++11 -g -DANDROID -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -march=armv5te -mtune=xscale -msoft-float -fno-integrated-as -mthumb -Wa,--noexecstack -Wformat -Werror=format-security -std=c++11   -Wl,--build-id -Wl,--warn-shared-textrel -Wl,--fatal-warnings -Wl,--exclude-libs,libunwind.a -Wl,--no-undefined -Wl,-z,noexecstack -Qunused-arguments -Wl,-z,relro -Wl,-z,now -Wl,--gc-sections -Wl,-z,nocopyreloc -Wl,--build-id -Wl,--warn-shared-textrel -Wl,--fatal-warnings -Wl,--exclude-libs,libunwind.a -Wl,--no-undefined -Wl,-z,noexecstack -Qunused-arguments -Wl,-z,relro -Wl,-z,now -Wl,--gc-sections -Wl,-z,nocopyreloc  -static CMakeFiles/Hello.dir/a.cc.o  -o Hello  -lm "/usr/local/google/home/labath/local/android-ndk-r14-beta1/sources/cxx-stl/llvm-libc++/libs/armeabi/libc++_static.a" "/usr/local/google/home/labath/local/android-ndk-r14-beta1/sources/cxx-stl/llvm-libc++/libs/armeabi/libc++abi.a" "/usr/local/google/home/labath/local/android-ndk-r14-beta1/sources/cxx-stl/llvm-libc++/libs/armeabi/libunwind.a" "/usr/local/google/home/labath/local/android-ndk-r14-beta1/sources/cxx-stl/llvm-libc++/libs/armeabi/libandroid_support.a" "-latomic" 
/usr/local/google/home/labath/local/android-ndk-r14-beta1/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: /usr/local/google/home/labath/local/android-ndk-r14-beta1/platforms/android-9/arch-arm/usr/lib/../lib/libc.a(wchar.o): multiple definition of 'wcrtomb'
/usr/local/google/home/labath/local/android-ndk-r14-beta1/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: /usr/local/google/home/labath/local/android-ndk-r14-beta1/sources/cxx-stl/llvm-libc++/libs/armeabi/libandroid_support.a(wcrtomb.o): previous definition here
/usr/local/google/home/labath/local/android-ndk-r14-beta1/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: /usr/local/google/home/labath/local/android-ndk-r14-beta1/platforms/android-9/arch-arm/usr/lib/../lib/libc.a(wchar.o): multiple definition of 'wcsrtombs'
/usr/local/google/home/labath/local/android-ndk-r14-beta1/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: /usr/local/google/home/labath/local/android-ndk-r14-beta1/sources/cxx-stl/llvm-libc++/libs/armeabi/libandroid_support.a(wcsrtombs.o): previous definition here
/usr/local/google/home/labath/local/android-ndk-r14-beta1/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: /usr/local/google/home/labath/local/android-ndk-r14-beta1/platforms/android-9/arch-arm/usr/lib/../lib/libc.a(wchar.o): multiple definition of 'wcstombs'
/usr/local/google/home/labath/local/android-ndk-r14-beta1/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: /usr/local/google/home/labath/local/android-ndk-r14-beta1/sources/cxx-stl/llvm-libc++/libs/armeabi/libandroid_support.a(wcstombs.o): previous definition here
/usr/local/google/home/labath/local/android-ndk-r14-beta1/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: /usr/local/google/home/labath/local/android-ndk-r14-beta1/platforms/android-9/arch-arm/usr/lib/../lib/libc.a(wchar.o): multiple definition of 'mbsrtowcs'
/usr/local/google/home/labath/local/android-ndk-r14-beta1/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: /usr/local/google/home/labath/local/android-ndk-r14-beta1/sources/cxx-stl/llvm-libc++/libs/armeabi/libandroid_support.a(mbsrtowcs.o): previous definition here
/usr/local/google/home/labath/local/android-ndk-r14-beta1/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: /usr/local/google/home/labath/local/android-ndk-r14-beta1/platforms/android-9/arch-arm/usr/lib/../lib/libc.a(wchar.o): multiple definition of 'mbstowcs'
/usr/local/google/home/labath/local/android-ndk-r14-beta1/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: /usr/local/google/home/labath/local/android-ndk-r14-beta1/sources/cxx-stl/llvm-libc++/libs/armeabi/libandroid_support.a(mbstowcs.o): previous definition here
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [Hello] Error 1
make[2]: Leaving directory `/tmp/X/b'
make[1]: *** [CMakeFiles/Hello.dir/all] Error 2
make[1]: Leaving directory `/tmp/X/b'
make: *** [all] Error 2

**Comment by plabath** [comment]
Btw, I don't think this is armv5 specific. I got the same error for armv7

**Comment by DanAlbert** [comment]
Nothing to really be done about this in the short term. These symbols are necessarily defined in both libc.a and libandroid_support.a. libandroid_support fills in some gaps in libc, but it also replaces some functions that were broken.

When we some day have time to look at getting all the static libraries rebuilt, we can probably pre-merge libandroid_support and libc.a to avoid this problem, but until then you'll just need to use `-Wl,--allow-multiple-definition` to get past this.

**Comment by DanAlbert** [comment]
This was fixed a while ago (r17?)
