### ISSUE TITLE
build  openssl for android refer a link error

### ISSUE THREAD

**Issue by chenTest2013** [android-ndk/ndk#281]
I build openssl static library follow the openssl [wiki](https://wiki.openssl.org/index.php/Android) on my ubuntu PC(Linux ubuntu 4.4.0-60-generic 16.04 x86_64 x86_64 x86_64 GNU/Linux)
my build environment is as follows:
openssl-1.0.1g
ndk:android-ndk-r13b
android-api:android-21
android_arch=arch-arm
1:  ./config shared no-ssl2 no-ssl3 no-comp no-hw no-engine --openssldir=/usr/local/ssl/$ANDROID_API
this setp is ok
2:   make depend  this setp is ok
3: make all , 
dhparam.o:dhparam.c:function dhparam_main: error: undefined reference to 'setup_engine'

what can i do fix this problem? Thanks

**Comment by DanAlbert** [comment]
This looks like a bug in the openssl build (or in the docs) than in the NDK. The missing symbol you're seeing is a part of openssl, not a part of the NDK. I'd suggest filing a bug with them or perhaps asking on their mailing list.

**Comment by chenTest2013** [comment]
@DanAlbert ok，thanks

**Comment by kneth** [comment]
@chenTest2013 Building OpenSSL for Android isn't trivial. The `config` step will generate a makefile which cannot be used directly. For inspiration you can take a look at https://github.com/realm/realm-core/blob/master/build.sh#L916.
