### ISSUE TITLE
$(LOCAL_C_INCLUDES) doesn't appear to work with 12b through 14-beta1

### ISSUE THREAD

**Issue by ehem** [android-ndk/ndk#282]
#### Description

The $(LOCAL_C_INCLUDES) value from Android.mk doesn't appear to have any effect.  Notably setting the value doesn't cause additional include directories to be passed to the compiler.  In my case the line I'd _like_ to use is:
`LOCAL_C_INCLUDES := $(LOCAL_PATH)/include`

#### Environment Details

* NDK Version: 12.1.2977051 or 14.0.3529234-beta1
* Build sytem: ndk-build
* Host OS: Linux, Debian/GNU stable
* Compiler: Either; build system/Makefile problem

**Comment by ehem** [comment]
Hmm, upon looking at other encounters with $(LOCAL_C_INCLUDES) I'm really wondering what the heck is going on.  Was $(LOCAL_C_INCLUDES) working with 13b, but was broken in 12b and rebroken in 14-beta1?

**Comment by DanAlbert** [comment]
Can you provide an example? If the trivial case of this were broken everything would be broken and most of our tests wouldn't pass.

**Comment by ehem** [comment]
Appears the example I provided was what did it. According to [the documentation](https://developer.android.com/ndk/guides/android_mk.html) the below _should_ work:
`LOCAL_C_INCLUDES := $(LOCAL_PATH)/include`

Instead that appears to be being filtered out somewhere.  While the below _does_ work:
`LOCAL_C_INCLUDES := include`

Guessing the NDK is filtering everything which begins with "/" out of the include path.

**Comment by DanAlbert** [comment]
Filtering it sounds surprising, but the cause makes sense. There are only a handful of places where `LOCAL_PATH` can be used, and I guess this isn't one of them. I'll take a closer look to see what's going on, but the resolution for this might just be a doc fix.

**Comment by ehem** [comment]
Being able to give absolute paths for include files can be useful, even though in many cases it may be a bad idea.  I'd tend to fix this to conform to the documentation since the alternative is developers are going to generate _worse_ hacks.

**Comment by DanAlbert** [comment]
I think any project depending on absolute paths is generally relying too much on that developer's particular workspace setup and definitely non-hermetic, right? Are there cases I'm not thinking of right now? What I'm thinking of is people hard coding things like `LOCAL_C_INCLUDES := /home/danalbert/boost/include` or similar.

Either way, agreed. If it looks simple to make this Just Work I'll do that, but given the above I think it'll be low priority if it will require more effort than I can spare at the moment (I'm much more interested in getting libc++ into good shape atm).

**Comment by ehem** [comment]
A more useful case would be a program needing some outside tool/library and directing people to set $(TOOL_DIR) to that location and then including from it.  Meanwhile the case you're thinking of is the same bad thing I was thinking of.

**Comment by alexcohn** [comment]
Works for me with r14β2 (actually, r13b works, too).

It is dangerous to define LOCAL_C_INCLUDES as relative path (e.g. `LOCAL_C_INCLUDES := include`), because you can ndk-build with different current directories. Anchoring it to $(LOCAL_PATH) is the easiest way to keep the builds consistent. 

With that, `LOCAL_C_INCLUDES := include` is equivalent to `LOCAL_C_INCLUDES := $(LOCAL_PATH)/include` if ndk-build is run from the **jni** directory, but usually we (and Android Studio) run ndk-build from **jni/..**. Maybe, this caused the confusion in the first place?

**Comment by DanAlbert** [comment]
TIL `jni` is a valid cwd for ndk-build. I was under the impression that only `jni/..` worked. Even better:

```bash
$ cat foo/jni/Android.mk
LOCAL_PATH := $(call my-dir)
$(info LOCAL_PATH=$(LOCAL_PATH))
$ ndk-build -C foo
LOCAL_PATH=jni
$ ndk-build -C foo/jni
LOCAL_PATH=/work/src/ndk/ndk/bar/jni
```

So whether or not `LOCAL_PATH` is a relative or absolute path changes depending on your cwd.

In that case, yes, prefixing with `LOCAL_PATH` seems to be the right choice. As with @alexcohn, doing so works fine for me, so I think we're still missing something about your environment.

**Comment by ehem** [comment]
Okay then, seems we've got yet another documentation issue.  Usually references to the directory point to the base of the project ("foo" in your example) and not a subdirectory ("foo/jni").  I'd been expecting $(LOCAL_PATH) and $(call my-dir) to point to "foo" not "foo/jni".  This is highly surprising since this is _highly_ unconventional.  Guess this does work, but got tripped up by the NDK being very weird.
