### ISSUE TITLE
Gnu Make spurious CreateProcess during -n run.

### ISSUE THREAD

**Issue by jomof** [android-ndk/ndk#284]
#### Description

This is related to:
b.android.com232163:	Latest Gradle plugin fails to generate native libraries

This is a request to take the two patches described here:
http://gnu-make.2324884.n4.nabble.com/process-begin-CreateProcess-NULL-quot-quot-failed-td13819.html

#### Environment Details

Not all of these will be relevant to every bug, but please provide as much
information as you can.

* NDK Version: Any
* Build sytem: ndk-build
* Host OS: Windows
* Compiler: Any
* ABI: Any
* STL: Any
* NDK API level: Any
* Device API level: Any

**Comment by DanAlbert** [comment]
In case I forget why this is important: this will break Studio being able to process an ndk-build project on Windows if the project can change based on `$(shell)` output (something like `LOCAL_SRC_FILES := $(shell ls jni/*.cpp)`).

**Comment by suikki** [comment]
I see the `process_begin: CreateProcess(NULL, "", ...) failed.` message multiple times every time when building a native project that uses ndkBuild from gradle. My project still builds OK, but It's pretty annoying and confusing when you see it for the first time.

Can't you upgrade to a newer make or something?

**Comment by DanAlbert** [comment]
Upgrading to a new version of make can introduce different bugs, and this one is relatively harmless. Some day, yes, but right now there are many higher priority issues for us to be spending our time on.

**Comment by suikki** [comment]
Sure, this is definitely not high priority (while I do think that irrelevant error messages leave a pretty bad taste in the user's mouth). I do appreciate getting a response, as I'm having a hard time getting a response to any of my Android Studio/Gradle plugin issues.

**Comment by DanAlbert** [comment]
> while I do think that irrelevant error messages leave a pretty bad taste in the user's mouth

Totally understand.

> as I'm having a hard time getting a response to any of my Android Studio/Gradle plugin issues.

If you want to send me bug URLs (danalbert@google.com), I can try to help get them directed to the right people for you. Sometimes things just get assigned to the wrong person and get lost.

**Comment by DanAlbert** [comment]
Master (r21) now has make 4.2.1.
