### ISSUE TITLE
Don't use -isystem or -isysroot for yasm

### ISSUE THREAD

**Issue by DanAlbert** [android-ndk/ndk#288]
#### Description

https://groups.google.com/d/topic/android-ndk/AKo1afwyAdI/discussion

We pass `--sysroot` and `-isystem` to yasm, and it can't handle those options. The warning is harmless, but we should clean it up anyway.

#### Environment Details

Not all of these will be relevant to every bug, but please provide as much
information as you can.

* NDK Version: master
* Build sytem: ndk-build
* Host OS: All
* Compiler: yasm

**Comment by DanAlbert** [comment]
Fix that will need rebasing to cover unified headers: https://android-review.googlesource.com/c/278302/

**Comment by DanAlbert** [comment]
https://android-review.googlesource.com/c/356674/

**Comment by enh** [comment]
fix now available in r15beta1.
