### ISSUE TITLE
Clang error in NDK 14.0.3529234 rc1 error in backend: Undefined temporary symbol

### ISSUE THREAD

**Issue by ntrrgc** [android-ndk/ndk#290]
#### Description

My project stopped building after updating to NDK 14.0.3529234 rc1. This is the error shown:

```
/hdd/home/ntrrgc/Android/Sdk/cmake/3.6.3155560/bin/cmake: /usr/lib/libcrypto.so.1.0.0: no version information available (required by /hdd/home/ntrrgc/Android/Sdk/cmake/3.6.3155560/bin/cmake)
/hdd/home/ntrrgc/Android/Sdk/cmake/3.6.3155560/bin/cmake: /usr/lib/libssl.so.1.0.0: no version information available (required by /hdd/home/ntrrgc/Android/Sdk/cmake/3.6.3155560/bin/cmake)
/hdd/home/ntrrgc/Android/Sdk/cmake/3.6.3155560/bin/cmake: /usr/lib/libssl.so.1.0.0: no version information available (required by /hdd/home/ntrrgc/Android/Sdk/cmake/3.6.3155560/bin/cmake)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:externalNativeBuildDebug'.
> Build command failed.
  Error while executing '/hdd/home/ntrrgc/Android/Sdk/cmake/3.6.3155560/bin/cmake' with arguments {--build /hdd/home/ntrrgc/Documentos/Dropbox/JSVM/app/.externalNativeBuild/cmake/debug/mips --target native-lib}
  [1/10] Building C object CMakeFiles/native-lib.dir/src/main/cpp/duktape/duktape.c.o
  [2/10] Building CXX object CMakeFiles/native-lib.dir/src/main/cpp/jsvm/exceptions.cpp.o
  [3/10] Building CXX object CMakeFiles/native-lib.dir/src/main/cpp/jsvm/javaClasses.cpp.o
  [4/10] Building CXX object CMakeFiles/native-lib.dir/src/main/cpp/jsvm/JSVM.cpp.o
  [5/10] Building CXX object CMakeFiles/native-lib.dir/src/main/cpp/jsvm/JSValue.cpp.o
  [6/10] Building CXX object CMakeFiles/native-lib.dir/src/main/cpp/jsvm/JSObject.cpp.o
  [7/10] Building CXX object CMakeFiles/native-lib.dir/src/main/cpp/jsvm/JSFunction.cpp.o
  [8/10] Building CXX object CMakeFiles/native-lib.dir/src/main/cpp/jsvm/utils.cpp.o
  [9/10] Building CXX object CMakeFiles/native-lib.dir/src/main/cpp/jsvm/invokeSafe.cpp.o
  FAILED: /hdd/home/ntrrgc/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/bin/clang  -target mipsel-none-linux-android -gcc-toolchain /hdd/home/ntrrgc/Android/Sdk/ndk-bundle/toolchains/mips64el-linux-android-4.9/prebuilt/linux-x86_64 --sysroot=/hdd/home/ntrrgc/Android/Sdk/ndk-bundle/platforms/android-15/arch-mips -DENABLE_EMBEDDED_NULL_INTEROP -Dnative_lib_EXPORTS -I../../../../src/main/cpp -g -DANDROID -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -mips32 -Wa,--noexecstack -Wformat -Werror=format-security -g -DANDROID -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -mips32 -Wa,--noexecstack -Wformat -Werror=format-security  -fstrict-aliasing -fomit-frame-pointer -ffunction-sections -fdata-sections -fvisibility=hidden  -O0 -fno-limit-debug-info -O0 -fno-limit-debug-info  -fPIC -MD -MT CMakeFiles/native-lib.dir/src/main/cpp/duktape/duktape.c.o -MF CMakeFiles/native-lib.dir/src/main/cpp/duktape/duktape.c.o.d -o CMakeFiles/native-lib.dir/src/main/cpp/duktape/duktape.c.o   -c /hdd/home/ntrrgc/Documentos/Dropbox/JSVM/app/src/main/cpp/duktape/duktape.c
  fatal error: error in backend: Undefined temporary symbol
  ninja: build stopped: subcommand failed.
  /hdd/home/ntrrgc/Android/Sdk/cmake/3.6.3155560/bin/cmake: /usr/lib/libcrypto.so.1.0.0: no version information available (required by /hdd/home/ntrrgc/Android/Sdk/cmake/3.6.3155560/bin/cmake)
  /hdd/home/ntrrgc/Android/Sdk/cmake/3.6.3155560/bin/cmake: /usr/lib/libssl.so.1.0.0: no version information available (required by /hdd/home/ntrrgc/Android/Sdk/cmake/3.6.3155560/bin/cmake)
  /hdd/home/ntrrgc/Android/Sdk/cmake/3.6.3155560/bin/cmake: /usr/lib/libssl.so.1.0.0: no version information available (required by /hdd/home/ntrrgc/Android/Sdk/cmake/3.6.3155560/bin/cmake)
```

No error is shown if I revert to NDK 13.

#### Environment Details

* Build sytem: cmake
* Host OS: Arch Linux
* Compiler: Clang

**Comment by enh** [comment]
we'll need some source to help us reproduce this... on the assumption you can't just give us all your source, can you reduce the project to just enough to (fail to) compile duktape.c?

you might also want to try not using clang's built-in assembler: add "-no-integrated-as" to your cflags.

**Comment by ntrrgc** [comment]
Hi, thanks for replying.

Actually you can check out the project from GitHub, it should compile in Android Studio as is. https://github.com/ntrrgc/jsvm

**Comment by stephenhines** [comment]
Does this only fail for MIPS compilation? Is there some way to skip/disable that from cmake and see if the other target ABIs are working?

**Comment by DanAlbert** [comment]
> Is there some way to skip/disable that from cmake and see if the other target ABIs are working?

`-DANDROID_ABI=armeabi-v7a` (or whatever) is how to set that for cmake directly. For invoking from gradle you want something like https://github.com/googlesamples/android-ndk/blob/master/native-media/app/build.gradle#L12

**Comment by Fimagena** [comment]
I just submitted a [very similar issue](https://github.com/android-ndk/ndk/issues/314) - had missed this one before. For me, the problem is MIPS-specific and it's due to clang breaking on a set of empty brackets (`{}`) after an `if` statement.

**Comment by rainwolf** [comment]
I had a similar issue just now with some legacy code that used to compile fine. My temporary fix is to set 'NDK_DEBUG=0' in the build task in the app gradle. It compiled fine after that.

**Comment by iuraiura879** [comment]
Downgrading to ndk 13b makes it work fine. Will this issue be getting a fix, or should we stick to 13b?

**Comment by gjpc** [comment]
An empty if statement is a great TODO marker in the code, commenting the empty if is no biggie. Please fix this bug, it added more jolt to my morning than a cup of espresso.

**Comment by scribe777** [comment]
This bug is also driving me nuts. @rainwolf , how exactly to you "set 'NDK_DEBUG=0' in the build task in the app gradle." ?  I see the "Gradle" tab in android-studio, and can select my project/Tasks/build/build, but then what?  There is no right-click option to change any settings or anything like this that I've found.  Thanks for any help

**Comment by kneth** [comment]
Is it related to https://code.google.com/p/android/issues/detail?id=223793

**Comment by rainwolf** [comment]
@scribe777 Not sure what you mean by gradle tab, but I have 2 gradle files, both named build.gradle, the app's gradle file is the top one (the inner most one). In there I have the relevant section that I screenshotted below. I hope this helps.

<img width="241" alt="screen shot 2017-03-30 at 30 mar 10 03 26" src="https://cloud.githubusercontent.com/assets/3620534/24493756/3c3194a2-1530-11e7-8687-ae1906a77c8b.png">
<img width="808" alt="screen shot 2017-03-30 at 30 mar 10 03 40" src="https://cloud.githubusercontent.com/assets/3620534/24493755/3c30b546-1530-11e7-8283-6644a27c569c.png">

**Comment by scribe777** [comment]
@rainwolf Thank you.  I found my build.gradle files, but the closest thing in any of them is this:
`    externalNativeBuild {
        cmake {
            path "CMakeLists.txt"
        }
    }
`

**Comment by ntrrgc** [comment]
Still present in NDK 14.1.3816874. It's quite disappointing to find that 4 months later something as inocuous as an empty `if` block still crashes the build process.

**Comment by DanAlbert** [comment]
Have you tried r15? r15 updated Clang and fixed a ton of Clang issues.

**Comment by ntrrgc** [comment]
@DanAlbert Indeed, thankfully this is fixed in r15. Thanks for the hint.
