### ISSUE TITLE
Unified headers link not working

### ISSUE THREAD

**Issue by Zingam** [android-ndk/ndk#291]
Currently when I click on "Unified Headers" on this page: https://github.com/android-ndk/ndk/wiki/Changelog-r14-beta2. The browser displays the wiki page: https://github.com/android-ndk/ndk/wiki

**Comment by enh** [comment]
fixed (by correcting the page manually). i'm assuming we leave the checked-in CHANGELOG.md alone?

**Comment by DanAlbert** [comment]
Oops. We just copy the changelog from our source so it has links that work when viewed in gitiles, and I always forget to fix them when I copy it over to the wiki. Perhaps I'll just stop copying them in the future...
