### ISSUE TITLE
cxx-stl adds unnecessary modules

### ISSUE THREAD

**Issue by alexcohn** [android-ndk/ndk#293]
#### Description

Building a shared library with **c++_shared** in NDK r14b (traced back to r12) adds unexpected modules to the list: **c++_static c++abi**

#### Environment Details

For a trivial project, I run `ndk-build APP_STL=c++_shared APP_ABI=x86 NDK_DEBUG_MODULES=1`, and here is what I see:

    Modules [x86]: android_support c++_shared c++_static c++abi test
    … 
    Top modules: test
    --- end of modules list
    module test [./obj/local/x86/libtest.so]
    .  all_libs='android_support c++_shared'
    .  shared_libs='c++_shared'
    .  static_libs='android_support'
    .  whole_static_libs=''
    .  built_shared_libs='./obj/local/x86/libc++_shared.so '
    .  built_static_libs='/Users/alexc/Library/Android/sdk/ndk-bundle/sources/android/support/../../cxx-stl/llvm-libc++/libs/x86/libandroid_support.a'
    .  built_whole_static_libs=''

The extra **c++_static c++abi** modules are added in **sources/cxx-stl/llvm-libc++/Android.mk**. This script adds shared and static prebuilt STL libraries without checking the `APP_STL` variant. I haven't fully investigated what undesired effect these extra modules may have, but they get executed, e.g. when I run `ndk-build clean`.

* NDK Version:  14.0.3675639-beta2.
* Build sytem: ndk-build
* Host OS: Mac Sierra 10.12.3
* Compiler: default (Clang).
* ABI: all
* STL: c++_shared
* NDK API level: default
* Device API level: default

**Comment by DanAlbert** [comment]
The first line is just all discovered modules. Below it, "Top modules", is the list of modules defined in *your* makefiles (anything not discovered via `import-module`). Unless `APP_MODULES` is set, we build all top modules that are executables or shared libraries. If you don't have an executables or shared libraries, then we force build your static libraries (by default, static libraries will only be built if they are used).

The more debug-looking variables below show what is being linked into libtest.so. `all_libs` is the list of all modules that will be linked, and the others are just a breakdown of those by type. libc++_static and libc++abi aren't in the list, so no harm done :)

> but they get executed, e.g. when I run ndk-build clean.

As in we try to clean things that weren't built? That's probably for the best, otherwise if you were to depend on c++_shared, build, then switch to libc++_static, then clean, libc++_shared.so wouldn't get cleaned. I guess we're not perfect on this though, because if you were to switch to gnustl_shared (or any other non-libc++ stl) we wouldn't clean libc++ anyway.

**Comment by alexcohn** [comment]
Thanks for clarification. I guess this may have non-trivial effect when STL libs are rebuilt. "Clean" for the prebuilt static libs is interpreted as `rm -rf $(TARGET_OBJS)`:

**`ndk-build APP_STL=gnustl_static APP_ABI=x86 clean -n`**
```
echo [x86] "Clean          ": "gnustl_shared [x86]"
rm -rf ./obj/local/x86/libgnustl_shared.so ./obj/local/x86/objs
echo [x86] "Clean          ": "gnustl_static [x86]"
rm -rf ./obj/local/x86/objs
echo [x86] "Clean          ": "test [x86]"
rm -rf ./obj/local/x86/libtest.so ./obj/local/x86/objs
```

**`ndk-build APP_STL=gnustl_static APP_ABI=x86 clean -n`**
```
echo [x86] "Clean          ": "android_support [x86]"
rm -rf ./obj/local/x86/objs
echo [x86] "Clean          ": "c++_shared [x86]"
rm -rf ./obj/local/x86/libc++_shared.so ./obj/local/x86/objs
echo [x86] "Clean          ": "c++_static [x86]"
rm -rf ./obj/local/x86/objs
echo [x86] "Clean          ": "c++abi [x86]"
rm -rf ./obj/local/x86/objs
echo [x86] "Clean          ": "test [x86]"
rm -rf ./obj/local/x86/libtest.so ./obj/local/x86/objs
```
But I see no artifacts of **c++static** or **gnustl_static** in `$(TARGET_OBJS)` directory, only the copies of `libc++_shared.so` and `libgnustl_shared.so`. Actually, I don't see any reason to copy the prebuilt shared libs from their safe haven in `<NDK>/sources/cxx-stl/` to `$(TARGET_OBJS)`, but at least this behavior is consistent for all prebuilt shared libraries.

Correct me if I miss something, but even if the prebuilt shared library is not deleted from **./obj/local/x86/**, it is not used for linking and not installed, unless explicitly referenced in "Top modules" or their dependencies.

**Comment by DanAlbert** [comment]
> Actually, I don't see any reason to copy the prebuilt shared libs from their safe haven in `<NDK>/sources/cxx-stl/` to `$(TARGET_OBJS)`

There isn't one, really, but as you say it matches the behavior for other shared libraries (they're all basically the same thing under the hood).

> Correct me if I miss something, but even if the prebuilt shared library is not deleted from ./obj/local/x86/, it is not used for linking and not installed

No, but it would need to be cleaned from libs/x86.

**Comment by alexcohn** [comment]
>  it would need to be cleaned from libs/x86

which happens anyways, as part of every install, `rm -rf ./libs` (or wherever $(NDK_LIBS_OUT) happens to point).

**Comment by DanAlbert** [comment]
Ah, well then yes, I suppose this is unnecessary. I don't believe it's causing any harm though, right?

**Comment by alexcohn** [comment]
I have not found any specific harm yet. I was wondering why this behavior was adopted in the first place, and whether this may result in some problems later, if neglected.

Our native build (which brings 5 independent NDK "applications", imported as separate sets of "libraries") to a single app does take this behavior into account, otherwise it simply fails. But this should not matter for 99% of developers who use NDK.

**Comment by DanAlbert** [comment]
Okay, I'm going to go ahead and close this then since I don't see anything here that could be acted on (aside from maybe cleaning up how we handle `clean`, but if that's not causing any problems it's not something we should actually devote time to imo).
