### ISSUE TITLE
No __unorddf2 in NDK for aarch64

### ISSUE THREAD

**Issue by DanAlbert** [android-ndk/ndk#294]
__unorddf2 isn't in libgcc for aarch64, but clang emits calls for it when compiling some libc++ tests. One possible solution for this would be to switch to compiler-rt instead of libgcc, but that's not something that will happen for r15.

One such test: sources/cxx-stl/llvm-libc++/test/std/numerics/complex.number/complex.transcendentals/atan.pass.cpp

**Comment by DanAlbert** [comment]
Anyone else landing here: only real workaround would be to add a definition of these things to your code. The compiler-rt versions are dual MIT/University of Illinois Open Source licensed: https://android.googlesource.com/platform/external/compiler-rt/+/master/lib/builtins/muloti4.c

The only things that should be missing are some of the less commonly needed builtins (128-bit math).

**Comment by DanAlbert** [comment]
Upstream bug about this: https://llvm.org/bugs/show_bug.cgi?id=16404

**Comment by DanAlbert** [comment]
Good news is that the newer Clang (the one I'm verifying for r15 right now) doesn't emit `__unorddf2` for the libc++ tests. There was some talk upstream of trying to avoid using things not available in libgcc, so maybe that happened? Or maybe those calls are just being inlined now. @stephenhines @pirama-arumuga-nainar, any idea?

**Comment by stephenhines** [comment]
They are probably just generating different code. I didn't spot anything that makes me believe that "inlining" is happening, since the calls would still be to a nonexistent compiler-rt set of builtins. This is a tricky problem that will likely keep recurring until we can properly switch over to using compiler-rt for builtins.

**Comment by pirama-arumuga-nainar** [comment]
We added unorddf2 to compiler_rt-extras (https://android-review.googlesource.com/#/c/243673/).  Is that not included with the NDK?

**Comment by DanAlbert** [comment]
> They are probably just generating different code.

Okay, I figured as much.

> We added unorddf2 to compiler_rt-extras (https://android-review.googlesource.com/#/c/243673/). Is that not included with the NDK?

No, it isn't. We don't have control of our users' build systems, so something like compiler_rt-extras doesn't really work for us (we can try doing something with a linker script, but haven't yet).

**Comment by DanAlbert** [comment]
Moving to compiler-rt is somewhat non-trivial because it's difficult to get building for ICS. Moving to r17.

**Comment by fornwall** [comment]
@DanAlbert Is the plan still to move from libgcc to compiler-rt for r17?

**Comment by DanAlbert** [comment]
I think if we don't manage to fully migrate in this release, we're going to have to at least perform some tricks like we do in the platform to provide the missing symbols.

**Comment by DanAlbert** [comment]
(the trick we do is link a libcompiler-rt-extras into everything alongside libgcc; it only contains a handful of symbols that libgcc doesn't provide)

**Comment by DanAlbert** [comment]
Not far along enough with testing for this for me to be happy with it for r17. As I said above though, the main case where this was causing issues is no longer occurring.

**Comment by DanAlbert** [comment]
NDK r17 includes libcompiler_rt-extas.a which includes the missing libcalls. Should be able to work around issues with `-lcompiler_rt-extas` until we manage to get fully switched to compiler-rt.

**Comment by DanAlbert** [comment]
I don't remember the current status here. We definitely have libcompiler_rt-extas in the NDK, but I think it's not used. Will check in on this before r19 beta 1, but if there's much work that needs to be done for it then it may land as part of beta 2.

**Comment by DanAlbert** [comment]
Looks like it's still in the same state as r17: libcompiler_rt-extras is present but not used.

https://android-review.googlesource.com/c/platform/ndk/+/793579 adds libcompiler_rt-extras to the libgcc linker script to make this transparent from the user's perspective.

**Comment by DanAlbert** [comment]
Submitted to master. Leaving this open because I'm not sure when the r19 branch point is and I want to make sure it gets into that branch.

**Comment by DanAlbert** [comment]
In r19.
