### ISSUE TITLE
Incomplete library list for "-DANDROID_STL=c++_shared". 

### ISSUE THREAD

**Issue by serhiihuralniksc** [android-ndk/ndk#299]
#### Description

`libandroid_support.a` is missed in linker library list when using CMake build with `c++_shared`.

#### Environment Details

Here is CMake config:
```
externalNativeBuild {
            cmake {
                arguments "-DANDROID_STL=c++_shared"
            }
 }
```
`CMakeLists.txt` is a typical one that is autogenerated by Android Studio. And here are few lines from generated `build.ninja`:
```
build CMakeFiles/native-lib.dir/src/main/cpp/native-lib.cpp.o: CXX_COMPILER__native-lib ../../../../src/main/cpp/native-lib.cpp
  ...
  INCLUDES = -isystem /Users/sergeyguralnik/tools/android-ndk-r13b/sources/cxx-stl/llvm-libc++/include -isystem /Users/sergeyguralnik/tools/android-ndk-r13b/sources/android/support/include -isystem /Users/sergeyguralnik/tools/android-ndk-r13b/sources/cxx-stl/llvm-libc++abi/include
  ...

build ../../../../build/intermediates/cmake/release/obj/armeabi-v7a/libnative-lib.so: CXX_SHARED_LIBRARY_LINKER__native-lib CMakeFiles/native-lib.dir/src/main/cpp/native-lib.cpp.o | /Users/sergeyguralnik/tools/android-ndk-r13b/platforms/android-15/arch-arm/usr/lib/liblog.so
  ...
  LINK_LIBRARIES = -llog -lm "/Users/sergeyguralnik/tools/android-ndk-r13b/sources/cxx-stl/llvm-libc++/libs/armeabi-v7a/libunwind.a" "/Users/sergeyguralnik/tools/android-ndk-r13b/sources/cxx-stl/llvm-libc++/libs/armeabi-v7a/libc++_shared.so"
  ...
```

As you see NDK support library headers are available to the compiler but no corresponding library is provided to the linker. 

* NDK Version: r13b
* Build sytem: Cmake (via gradle plugin 2.2.3) 
* Host OS: Mac
* Compiler: any
* ABI: any
* STL: c++_shared
* NDK API level: any
* Device API level: any

**Comment by DanAlbert** [comment]
Actually already fixed this in r14: https://android-review.googlesource.com/c/325274/ (in beta 2 for sure, I don't think it's in beta 1)
