### ISSUE TITLE
Missing 64 bit FILE stream functions

### ISSUE THREAD

**Issue by bog-dan-ro** [android-ndk/ndk#30]
The NDK doesn't have fopen64, fseeko64, ftello64, fgetpos64, fsetpos64 functions so needed to manipulate files larger than 4Gb (though it provides truncate64, lseek64, etc.).

**Comment by DanAlbert** [comment]
Should just be a matter of updating the headers.

**Comment by bog-dan-ro** [comment]
Are they added to r13 beta1?

**Comment by enh** [comment]
many of these were only added to the platform in N, so having new headers doesn't buy you anything unless you're also targeting N. (i think fopen64 is the only one on your list, since on Android fopen==fopen64.)

**Comment by n00ner** [comment]
Why lseek64 not working? I try add define _FILE_OFFSET_BITS 64, but still now works.

**Comment by enh** [comment]
please file a new bug, including all the information that the new bug template asks for.
