### ISSUE TITLE
Android Studio + CMake doesn't pack C++ STL (libc++_shared.so)

### ISSUE THREAD

**Issue by Sumenia** [android-ndk/ndk#306]
#### Description
When building my project with CMake + Android Studio, it doesn't pack libc++_shared.so even if ANDROID_STL is set to "c++_shared" in the CMakeLists.txt.

To fix the problem, I have to specify it in the gradle.build :
``` 
        externalNativeBuild {
            cmake {
                arguments '-DANDROID_STL=c++_shared'
            }
        }
```

Is that a correct behaviour?

#### Environment Details

Not all of these will be relevant to every bug, but please provide as much
information as you can.

* NDK Version:  tested with android-ndk-r14-beta1 and android-ndk-r14-beta2
* Build sytem: Cmake + Android Studio to build the APK
* Host OS:  Both linux and macOS
* Compiler: clang
* ABI: arm64-v8a
* STL: c++_shared

**Comment by DanAlbert** [comment]
Are you on an old version of studio by any chance? This would be https://code.google.com/p/android/issues/detail?id=214664

Closing because it's a studio issue and not an NDK one.

**Comment by saveman71** [comment]
FYI this is still not resolved by studio, even on the latest build. But yes it is studio related indeed. Thanks!

**Comment by DanAlbert** [comment]
I was under the impression that it had a partial fix, but re-reading that bug I think maybe it was just the known workaround of using `jniLibs`... You might want to chime in on that bug.

**Comment by rschiu** [comment]
Doing this automatically when it is specified in Gradle *is* the partial fix.  At the moment, we don't have a good way to figure out what STL is used by cmake otherwise.
