### ISSUE TITLE
LOCAL_CFLAGS do not disable warnings in Clang

### ISSUE THREAD

**Issue by alexcohn** [android-ndk/ndk#307]
#### Description

Switching to Clang from GCC in r14, we have a problem with compilation of some 3<sup>rd</sup> party libraries, e.g. gumbo-query. See https://github.com/google/gumbo-parser/issues/377 for details. 

The problem specific to NDK is that when we switch to Clang, we cannot silence the warnings by tuning **LOCAL_CFLAGS** for the specific library the way we used to, with GCC. The reason is that when I turn on the warnings with `APP_CFLAGS+=-Wall`, this goes _after_ the `LOCAL_CFLAGS`, and with Clang, **-Wall** overrides **-Wno-unused-variable**.

#### Environment Details

* NDK Version: 14.0.3675639-beta2
* Build sytem: ndk-build
* Host OS: Mac
* Compiler: Clang
* ABI: checked with x86, but is probably relevant to the others.

**Comment by DanAlbert** [comment]
Is this actually unique to r14?

**Comment by alexcohn** [comment]
I believe it is Clang-specific, we never tried to switch from gcc before.

**Comment by DanAlbert** [comment]
https://android-review.googlesource.com/356722

**Comment by DanAlbert** [comment]
Merged into master and I've cherry-picked to r15. It probably won't be in r15 beta 1, but if I need to respin that yet again it will be.

**Comment by DanAlbert** [comment]
FYI, I sent an email to one of the owners of the gumbo lib to see if we can get those warnings fixed rather than just suppressed.

**Comment by alexcohn** [comment]
Cool, I did not see reaction from **gumbo** on my request, and the [pull request](https://github.com/google/gumbo-parser/pull/348) that fixes this specific warning is pending since Oct 2015.

But **gumbo** is definitely not the only/last library on GitHub that compiles with warnings in Clang, or will compile with warnings in the next version of Clang. That's why a fix for Clang or NDK is required.

I believe that it is very important to encourage use of `-Wall` in **APP_CFLAGS**.

**Comment by DanAlbert** [comment]
Turns out we are respinning beta 1, so I've cherry-picked this. Should be available some time next week.

**Comment by enh** [comment]
fix now available in r15beta1...
