### ISSUE TITLE
NDK r14 breaks Android Studio "clion" integration

### ISSUE THREAD

**Issue by stevemadsenblippar** [android-ndk/ndk#309]
Android Studio "clion" feature provides syntax highlighting, typeahead prediction,
ctrl/cmd-click navigation etc. in C++ code.

If NDK 13.1.3345770 is used, everything works properly.

But if either
 * NDK 14.0.3529234rc1
 * NDK 14.0.3770861
are used, the C++ symbol resolution/navigation features break.

As explained here: [https://code.google.com/p/android/issues/detail?id=231382](url),
this is down solely to NDK version, not Android Studio/gradle/gradle plugin version
i.e. upgrading/downgrading just the NDK version will break or fix the issue.

**Comment by enh** [comment]
the folks who can debug clion problems are all on the other bug tracker, though, so treating  https://code.google.com/p/android/issues/detail?id=231382 as the canonical bug... (and i've made sure that someone from the relevant team now has that bug assigned to them.)
