### ISSUE TITLE
Standalone toolchain for mips is missing a system include dir on ndk r14

### ISSUE THREAD

**Issue by N-Bz** [android-ndk/ndk#310]
#### Description

Standalone mips 32bits c++ toolchains are missing a system include dir.

Compiling this simple c++ program with standalone mips toolchain with ndk-r14 fails:
```c++
#include <bits/c++config.h>

int main() {
    return 0;
}
```

Toolchains were generated with the following command lines:

 * `./build/tools/make-standalone-toolchain.sh --arch=mips64 --install-dir=/tmp/toolchain_mips64/ --platform=android-21` for the mips64 toolchain (working reference)
* `./build/tools/make-standalone-toolchain.sh --arch=mips --install-dir=/tmp/toolchain_mips/ --platform=android-21` for the mips32 toolchain (with the build issue)

Program was built with the following command line:

* `/tmp/toolchain_mips64/bin/mips64el-linux-android-clang++ /tmp/test.cpp -o /tmp/64.out` : This causes no issue.
* `/tmp/toolchain_mips/bin/mips64el-linux-android-clang++ /tmp/test.cpp -o /tmp/32.out` : This fails with the following error (adding `-mips32` flag does not change the result):
```
/tmp/test.cpp:1:10: fatal error: 'bits/c++config.h' file not found
#include <bits/c++config.h>
         ^
1 error generated.
```

When looking at the system include paths (by adding `-Wp,-v` to the build lines), we notice that the mips32 toolchain is lacking the `include/c++/4.9.x/mips64el-linux-android` directory.

Here is an output of the build with `-Wp,-v` mips64 toolchain:
```
clang -cc1 version 3.8.275480 based upon LLVM 3.8.275480 default target x86_64-unknown-linux
ignoring nonexistent directory "/tmp/toolchain_mips64/bin/../sysroot/usr/local/include"
ignoring nonexistent directory "/tmp/toolchain_mips64/bin/../sysroot/include"
#include "..." search starts here:
#include <...> search starts here:
 /tmp/toolchain_mips64/bin/../lib/gcc/mips64el-linux-android/4.9.x/../../../../include/c++/4.9.x
 /tmp/toolchain_mips64/bin/../lib/gcc/mips64el-linux-android/4.9.x/../../../../include/c++/4.9.x/mips64el-linux-android
 /tmp/toolchain_mips64/bin/../lib/gcc/mips64el-linux-android/4.9.x/../../../../include/c++/4.9.x/backward
 /tmp/toolchain_mips64/bin/../lib64/clang/3.8.275480/include
 /tmp/toolchain_mips64/bin/../sysroot/usr/include
End of search list.
```
And the same for the mips32 toolchain:
```
clang -cc1 version 3.8.275480 based upon LLVM 3.8.275480 default target x86_64-unknown-linux
ignoring nonexistent directory "/tmp/toolchain_mips/bin/../lib/gcc/mips64el-linux-android/4.9.x/../../../../include/mips64el-linux-android/c++/4.9.x/mips-r1"
ignoring nonexistent directory "/tmp/toolchain_mips/bin/../lib/gcc/mips64el-linux-android/4.9.x/../../../../include/mipsel-none-linux-android/c++/4.9.x"
ignoring nonexistent directory "/tmp/toolchain_mips/bin/../sysroot/usr/local/include"
ignoring nonexistent directory "/tmp/toolchain_mips/bin/../sysroot/include"
#include "..." search starts here:
#include <...> search starts here:
 /tmp/toolchain_mips/bin/../lib/gcc/mips64el-linux-android/4.9.x/../../../../include/c++/4.9.x
 /tmp/toolchain_mips/bin/../lib/gcc/mips64el-linux-android/4.9.x/../../../../include/c++/4.9.x/backward
 /tmp/toolchain_mips/bin/../lib64/clang/3.8.275480/include
 /tmp/toolchain_mips/bin/../sysroot/usr/include
End of search list.
```

This issue is not present on the ndk-r13b (Pkg.Revision = 13.1.3345770), which did not use the mips64el toolchain but the mipsel toolchain for 32 bits mips.

#### Environment Details

* NDK Version: 14.0.3770861
* Build sytem: standalone toolchain
* Host OS: Linux (Ubuntu 14.04.05 LTS) & MacOS Sierra
* Compiler: Same issue with GCC (g++) &  Clang (clang++)
* ABI: mips32
* STL: gnustl
* NDK API level: 21

**Comment by DanAlbert** [comment]
Sorry, I'd typed out a response to this before I left work yesterday but forgot to hit send.

I'm going to give r14 a few more days to gather feedback before I kick off r14b.

I think you can work around this for now by reverting the following two patches (didn't have time to test this yesterday, but it should work):
https://android.googlesource.com/platform/ndk/+/8a20465396fdcbfe48cdaee9aceb4cea1fec3160%5E%21/#F0
https://android.googlesource.com/platform/ndk/+/6a47a9e5de4949318bd277fc05dcef9e89a3da30%5E%21/#F3

Another workaround would be to use `--stl libc++`, but that's a bigger hammer :)

**Comment by davidshen84** [comment]
@DanAlbert I am from https://github.com/android-ndk/ndk/issues/312.

I updated my build script to use `mips64el-linux-android-` tool prefix, and added `-m32` to **CFLAGS**. I kick off the build again, and got this error:

```
/var/jenkins_home/android-16-mips-toolchain/bin/../lib/gcc/mips64el-linux-android/4.9.x/../../../../mips64el-linux-android/bin/ld: cannot find crtbegin_dynamic.o: No such file or directory
/var/jenkins_home/android-16-mips-toolchain/sysroot/usr/lib/libz.so: error adding symbols: File in wrong format
```

I checked the generated toolchain directory, and the file is there.

Probably the same issue?

**Comment by N-Bz** [comment]
@davidshen84 I guess the CFLAG to pass is `-mips32`, not `-m32` (At least that what I pass, and it seems to work fine for plain C)

**Comment by davidshen84** [comment]
@N-Bz Tried `-mips32`, still got the same error.

I switched back to **r13b**, and my builds work well.

**Comment by DanAlbert** [comment]
I've just uploaded a stack of patches to revert the broken pieces and increase our test coverage. If you want to apply the revert locally, https://android-review.googlesource.com/c/349275/ is the change that contains the fix.

**Comment by DanAlbert** [comment]
Cherry-picked into r14.
