### ISSUE TITLE
make_standalone_toolchain installs mips64 when --arch=mips

### ISSUE THREAD

**Issue by davidshen84** [android-ndk/ndk#312]
--------------------------------------------------------------------------------

#### Description

1. Execute
```sh
android-ndk/build/tools/make_standalone_toolchain.py --arch mips --api 16 --stl libc++ --install-dir /opt/output/mips-toolchain
```

2. Observe files created in `/opt/output/mips-toolchain/bin`

Expected: It creates *mipsel-linux-android-\** files.
Actual: It creates *mips64el-linux-android-\** files.

#### Environment Details

Not all of these will be relevant to every bug, but please provide as much
information as you can.

* NDK Version: 14.0.3770861
* Build sytem:  standalone toolchain? 
* Host OS:  Linux
* Compiler: *not related*
* ABI: mpis
* STL: libc++
* NDK API level: 16
* Device API level: ??

**Comment by kneth** [comment]
Similar to #310?

**Comment by DanAlbert** [comment]
Yep. This is actually intentional, FYI. We install the mips64 toolchain and pass -m32 when building so it generates 32-bit code.

**Comment by enh** [comment]
(this is how x86 and x86-64 work too. arm/aarch64 is actually the odd one out.)

**Comment by DanAlbert** [comment]
We haven't actually made that change for x86 yet. mips32 was the trial run (they helpfully volunteered to do it for us)  and it has yet to stick :)

**Comment by davidshen84** [comment]
@DanAlbert  Does it means the `--arch mips` and `--arch mips64` for *make_standalone_toolchain.py* have the same effect? And we should add `-m32` to **CFLAGS** and **CXXFLAGS** to distinguish the architecture?

**Comment by DanAlbert** [comment]
If you're using Clang, it's something we do for you. I think if you haven't migrated off GCC yet you need to do so yourself, but I'd have to check to be sure (I'll do that when I'm looking at this on Monday).

**Comment by davidshen84** [comment]
@DanAlbert Yes, I am still using GCC. Because OpenSSL build script only support GCC. If I change the compiler to clang, I got hit by https://github.com/android-ndk/ndk/issues/5.

Any suggestion for me?
