### ISSUE TITLE
clang error: "fatal error: error in backend: Undefined temporary symbol" - reduced example

### ISSUE THREAD

**Issue by Fimagena** [android-ndk/ndk#314]
#### Description

After upgrading Android Studio from 2.2 to 2.3, my cmake project compiles fine for mips64 but breaks for mips (haven't tried other ABIs) with "fatal error: error in backend: Undefined temporary symbol". It used to work with AS 2.2.

I have reduced the problem to the following. Clang break on the empty brackets `{}`.

*a.cpp:*
```c++
void function(int b) {
    if (b == 0) {}
} 
```

Compiling with `~/Library/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang++  --target=mipsel-none-linux-android -o a.cpp.o -c a.cpp` leads to above error (under mips only). 

#### Environment Details
* NDK Version: 14.0.3770861
* Host OS: macOS 10.12.3 (Sierra)
* Compiler: clang++
* ABI: mips

**Comment by pirama-arumuga-nainar** [comment]
This failure doesn't happen in the latest clang in AOSP (which is on track for r15).

**Comment by DanAlbert** [comment]
Assigning to me until the update gets pulled into the NDK then. Thanks for checking.

**Comment by whvirgil2015** [comment]
I met this problem when using "gradle build" in command . Whatever, Android-Studio works well. Which makes me a bit confused.

**Comment by iuraiura879** [comment]
Downgrading to ndk 13b makes it work fine. Will this issue be getting a fix, or should we stick to 13b?

**Comment by evanova** [comment]
I can confirm that setting NDK_DEBUG to 0 eliminates the issue.

**Comment by DanAlbert** [comment]
> Downgrading to ndk 13b makes it work fine. Will this issue be getting a fix, or should we stick to 13b?

https://github.com/android-ndk/ndk/issues/314#issuecomment-284538680

**Comment by pdefreitas** [comment]
debugging is broken this way, how can we debug properly with the most recent release?

**Comment by enh** [comment]
this only affects mips, though, right. can't you debug with one of the other ABIs?

**Comment by pdefreitas** [comment]
why is this closed? still present in current ndk r14b

**Comment by evanova** [comment]
I am still experiencing this issue.

**Comment by DanAlbert** [comment]
See the milestone. The fix is in r15. I can't do anything to fix the bits you've already downloaded :)

**Comment by 0M1D** [comment]
'clang' gets stuck on empty brackets in mips architectures. 
two ways to prevent this from happening.

1. fill your empty brackets with a neutral line of code like 
void function(int b) {
    if (b == 0) {
         int foo = 0;
    }
}

2. try r15
3. dont use mips at all with the help command 'abiFilters' in gradle

hope that will do!
