### ISSUE TITLE
Standalone toolchain: mips ships mips64el-linux-android

### ISSUE THREAD

**Issue by wongsyrone** [android-ndk/ndk#316]
#### Description

```
./make_standalone_toolchain.py --arch mips --unified-headers --install-dir /home/wong/mips-unifi
./make_standalone_toolchain.py --arch mips64 --unified-headers --install-dir /home/wong/mips64-unifi
ls mips64-unifi

AndroidVersion.txt  COPYING   COPYING3.LIB  COPYING.RUNTIME  lib/    libexec/              mips64el-linux-android/  MODULE_LICENSE_GPL  NOTICE     share/    test/
bin/                COPYING3  COPYING.LIB   include/         lib64/  manifest_3362437.xml  MODULE_LICENSE_BSD_LIKE  MODULE_LICENSE_MIT  repo.prop  sysroot/  tools/

ls mips-unifi

AndroidVersion.txt  COPYING   COPYING3.LIB  COPYING.RUNTIME  lib/    libexec/              mips64el-linux-android/  MODULE_LICENSE_GPL  NOTICE     share/    test/
bin/                COPYING3  COPYING.LIB   include/         lib64/  manifest_3362437.xml  MODULE_LICENSE_BSD_LIKE  MODULE_LICENSE_MIT  repo.prop  sysroot/  tools/
```
As you can see, both mips and mips64 ship `mips64el-linux-android/`.

I found this when preparing unified headers for libsodium: https://github.com/jedisct1/libsodium/issues/505

#### Environment Details

Not all of these will be relevant to every bug, but please provide as much
information as you can.

* NDK Version: Pkg.Revision = 14.0.3770861
* Build sytem: standalone toolchain
* Host OS: Archlinux
* Compiler: Not applicable
* ABI:Not applicable
* STL:Not applicable
* NDK API level:Not applicable
* Device API level:Not applicable

**Comment by Evisceration** [comment]
Duplicate, see #310.

Actually x86 and mips have 64 files but pass ```-m32``` so it generates 32 bit code.
