### ISSUE TITLE
android-ndk-r14: build-binary.mk

### ISSUE THREAD

**Issue by AbhirojPanwar** [android-ndk/ndk#319]
I ma trying to build a project based on AndroidNDK: On running ndk-build in the directory, I am getting following error. 

```
C:/android-ndk-r14/build//../build/core/build-binary.mk:687: Android NDK: Module
 pngt depends on undefined modules: z
C:/android-ndk-r14/build//../build/core/build-binary.mk:700: *** Android NDK: Ab
orting (set APP_ALLOW_MISSING_DEPS=true to allow missing dependencies)    .  Sto
p.
```
Please suggest a stable fix.

**Comment by kneth** [comment]
Did you include `-lz` in `LD_FLAGS`?

**Comment by AbhirojPanwar** [comment]
@kneth  No, I am afraid to tell you that but I did not know about. Please tell me where exactly shouldd I put the flags??

**Comment by kneth** [comment]
@AbhirojPanwar You might have a line like `LOCAL_LDLIBS     := -llog -landroid` in `build-binary.mk`. You should add `-lz` to it.

**Comment by AbhirojPanwar** [comment]
@kneth There is this line in build-binary.mk 

`LOCAL_LDLIBS := $(LOCAL_LDLIBS) $(call host-path,$(NDK_ROOT)/sources/cxx-stl/gnu-libstdc++/4.9/libs/$(TARGET_ARCH_ABI)/libsupc++$(TARGET_LIB_EXTENSION))`

I have searched it though , but `LOCAL_LDLIBS := -llog -landroid` is not there. Any insights on what I might be missing?

**Comment by kneth** [comment]
@AbhirojPanwar Looks like you have found the right line (I copied `LOCAL_LDLIBS` from another project as an example).

**Comment by AbhirojPanwar** [comment]
@kneth  Oh, that happens :) but what can be the fix for the problem?

**Comment by kneth** [comment]
You should probably change the line to `LOCAL_LDLIBS := $(LOCAL_LDLIBS) $(call host-path,$(NDK_ROOT)/sources/cxx-stl/gnu-libstdc++/4.9/libs/$(TARGET_ARCH_ABI)/libsupc++$(TARGET_LIB_EXTENSION)) -lz` to include the library when linking.

**Comment by AbhirojPanwar** [comment]
Hi @kneth , It is still showing the same error. Is there any other download I am missing to run the repo?

**Comment by AbhirojPanwar** [comment]
@kneth I have tried the buil again, still showing the same error.  Please suggest a fix. :)

**Comment by DanAlbert** [comment]
In your Android.mk:

```makefile
LOCAL_LDLIBS := -lz
```

**Comment by AbhirojPanwar** [comment]
@DanAlbert  where to look for Android.mk? It is not in the android ndk folder

**Comment by DanAlbert** [comment]
It's your project's build file.

**Comment by AbhirojPanwar** [comment]
Yes, added the following line here `C:\Users\APnaturals\AndroidStudioProjects\tess\tess-two\jni\Android.mk` ,   Error still persists. @DanAlbert  @kneth

**Comment by DanAlbert** [comment]
Sorry, you need to add that and remove the `LOCAL_SHARED_LIBRARIES := libz` or `LOCAL_STATIC_LIBRARIES := libz`.

**Comment by AbhirojPanwar** [comment]
@DanAlbert  this line is not in Android.mk. where to look for it?? thank you.

**Comment by AbhirojPanwar** [comment]
Sharing Android.mk :- 

```
LOCAL_PATH := $(call my-dir)
TESSERACT_PATH := $(LOCAL_PATH)/com_googlecode_tesseract_android/src
LEPTONICA_PATH := $(LOCAL_PATH)/com_googlecode_leptonica_android/src
LIBJPEG_PATH := $(LOCAL_PATH)/libjpeg
LIBPNG_PATH := $(LOCAL_PATH)/libpng
LOCAL_LDLIBS := -lz
# Just build the Android.mk files in the subdirs
include $(call all-subdir-makefiles)

```

**Comment by DanAlbert** [comment]
> `include $(call all-subdir-makefiles)`

Presumably it's in one of those.

**Comment by DanAlbert** [comment]
Also, adding `LOCAL_LDLIBS := -lz` there doesn't do anything. It needs to be added to the module definition.

**Comment by AbhirojPanwar** [comment]
@DanAlbert  I have added `LOCAL_LDLIBS := -lz`  in tess-two's Android.mk , where exactly should I put it?? 

for this, `include $(call all-subdir-makefiles)`  I will have to search all the sub directories Android.mk right?

**Comment by DanAlbert** [comment]
> @DanAlbert I have added LOCAL_LDLIBS := -lz in tess-two's Android.mk , where exactly should I put it??

ndk-build module definitions look like this:

```makefile

include $(CLEAR_VARS)
LOCAL_MODULE := foo
LOCAL_SRC_FILES := foo.cpp

# This is the line that would be wrong. It might also be LOCAL_STATIC_LIBRARIES
# or LOCAL_WHOLE_STATIC_LIBRARIES.
LOCAL_SHARED_LIBRARIES := libz

# This is what it should be.
LOCAL_LDLIBS := -lz

# BUILD_ something, anyway.
include $(BUILD_SHARED_LIBARY)
```

> for this, `include $(call all-subdir-makefiles)` I will have to search all the sub directories Android.mk right?

Yes. That searches for other Android.mk files in subdirectories and includes them.

**Comment by AbhirojPanwar** [comment]
>ndk-build module definitions look like this:

Where to look for  ndk-build module, I have currently two folders relating to the context of the issue, one is android-ndk-r14 and other is tess-two?? I apologize for not getting clear at first, but unable to locate the desired file to make the correct changes.

**Comment by AbhirojPanwar** [comment]
@DanAlbert @kneth

**Comment by DanAlbert** [comment]
Not in the android-ndk-r14 directory. I assume tess-two is the project you're trying to build? They'll be in the Android.mk files for the project.

**Comment by AbhirojPanwar** [comment]
@DanAlbert  Yes, That is the one I am trying to build. So, I may have to search not only in the main Android.mk of tess-two, but also in the Android.mk of sub-directories.

**Comment by AbhirojPanwar** [comment]
@DanAlbert  @kneth  Solved by putting  APP_ALLOW_MISSING_DEPS=true to application.mk , 

Beneficial for future readers. :)

**Comment by SwatGuard** [comment]
How unsafe is using APP_ALLOW_MISSING_DEPS= true ? 

Thanks

**Comment by DanAlbert** [comment]
It's not exactly unsafe, it's just likely to waste your time when you try to add a new library and have a typo because ndk-build will continue as if nothing went wrong.

**If you're getting this error, just remove the libraries it's referring to. You aren't using them.**
