### ISSUE TITLE
Unresolved stderr on android 5.0 with ndk14 and unified headers

### ISSUE THREAD

**Issue by jpharvey** [android-ndk/ndk#321]
#### Description

Building our library with NDK 14 on windows results in an unresolved symbol when loading our shared library of stderr on Android 5.0/5.1. It is ok on 6 & above

We used the following command to create the standalone toolchain
python build\tools\make_standalone_toolchain.py --arch arm --api 21 --unified-headers --install-dir=e:\compilers\android\android-ndk-r14-arm --stl=libc++

The result of this is that the bash scripts bin/clang & bin/clang++ pass -D __ANDROID_API__=21 to clang38
but the bin/clang.cmd & bin/clang++.cmd do not add the define. I think this is a bug in the generation scripts and I don't believe from the documentation of unified headers that we are supposed to pass that  define to the compiler when using the standalone toolchain.

#### Environment Details

Not all of these will be relevant to every bug, but please provide as much
information as you can.

* NDK Version: Value: 14
* Build sytem:standalone toolchain/ custom?
  * Host OS: Windows,
* Compiler: clang.
* ABI:
* STL: libc++
* NDK API level: 21
* Device API level:

**Comment by jpharvey** [comment]
Just a quick followup
I believe the fix for this is at line 280  of make_standalone_toolchaing.py

add
    if unified_headers:
        flags += ' -D__ANDROID_API__={}'.format(api)

after 
    if windows:
        flags = '-target {} --sysroot %~dp0\\..\\sysroot'.format(target)

**Comment by DanAlbert** [comment]
Merged into r14. Thanks!
