### ISSUE TITLE
android studio :The file is not part of the project.Please include it ...

### ISSUE THREAD

**Issue by Yufeikang** [android-ndk/ndk#322]
#### Description
android studio 对cpp和c文件提示：
android studio :The file is not part of the project.Please include it ...

这个问题和android和gradle无关。升级ndk版本后出现的。只要是ndk 14 ，无论使用那个版本的android studio和gradle都会出现上面的提示。

#### Environment Details

version:14

**Comment by DanAlbert** [comment]
Please report Studio issues against the Studio team: http://tools.android.com/filing-bugs
