### ISSUE TITLE
Colored output from Ninja

### ISSUE THREAD

**Issue by kkaefer** [android-ndk/ndk#326]
It'd be useful to have colored output from Clang. When forcing colored output with

```cmake
if (CMAKE_CXX_COMPILER_ID STREQUAL "Clang" AND CMAKE_GENERATOR STREQUAL "Ninja")
    set(CMAKE_C_FLAGS "-fcolor-diagnostics ${CMAKE_C_FLAGS}")
    set(CMAKE_CXX_FLAGS "-fcolor-diagnostics ${CMAKE_CXX_FLAGS}")
endif()
```

in `CMakeLists.txt`, invoking Ninja directly (or via `cmake --build`) produces colored output. However, Gradle invokes Ninja in such a way that makes it think that it doesn't write to a color-capable Terminal, since [Ninja requires the output pipe to be a TTY](https://github.com/ninja-build/ninja/blob/0b0374e831d9c050c6c9eb2ef48b73bc62a0f084/src/line_printer.cc#L33). Can Gradle simulate a TTY to receive colored output?

**Comment by DanAlbert** [comment]
I'm pretty sure gradle just invokes ninja via a pipe (a tty isn't required for ninja, it's just required for the more user friendly output).

Best to file it with the Studio folks and see if they can do something about it. I unfortunately have no powers over gradle :) http://tools.android.com/filing-bugs

**Comment by kkaefer** [comment]
I believe this ticket is still valid and should be reopened.

> I'm pretty sure gradle just communicates with ninja via a pipe (a tty isn't required for ninja, it's just required for the more user friendly output).

Exactly, and this is what this ticket is about: Without Gradle finding a way to forward colored output, Studio doesn't have any chance of ever getting colored output. The two paths forward I see is to either make Gradle open a TTY instead of a plain pipe to get Ninja to forward colored output, or to add a flag to ninja (e.g. as proposed in https://github.com/ninja-build/ninja/pull/1230 or https://github.com/ninja-build/ninja/issues/916), and then invoke Ninja with that flag enabled. Since Studio invokes Gradle, Gradle has to actually forward the color so that Studio can display it (but this is of course a ticket in the realm of Studio).

**Comment by enh** [comment]
as danalbert said: "Best to file it with the Studio folks and see if they can do something about it. I unfortunately have no powers over gradle :) http://tools.android.com/filing-bugs"

**Comment by kkaefer** [comment]
yeah, but that can only ever be part of the solution: Android Studio invokes Gradle, and if Gradle isn't able to output color, Android Studio certainly can't. So getting color support for Ninja/Gradle is the first step towards supporting color in Android Studio.

**Comment by enh** [comment]
and is Gradle part of the NDK, or part of Studio?

**Comment by gapspt** [comment]
@kkaefer did you got to fill in a bug report to the Android Studio / Android Gradle plugin?
I would like to track it status but I can't find it...

**Comment by kkaefer** [comment]
No

**Comment by gapspt** [comment]
Created https://issuetracker.google.com/37496484
