### ISSUE TITLE
Warn somehow if CMAKE_LIBRARY_OUTPUT_DIRECTORY is set in the CMakeLists.txt

### ISSUE THREAD

**Issue by hrydgard** [android-ndk/ndk#328]
#### Description

I was tearing out my hair for hours trying to figure out why my .so files compiled using CMake with the gradle integration would not appear in the .APK. After much digging I finally realized that CMAKE_LIBRARY_OUTPUT_DIRECTORY was being set in my CMakeLists.txt, overriding the one from cmake_build_command.txt and causing the .so files to be written to the wrong directory, so they were not picked up by the system.

To prevent others from having this debugging experience, it would be nice if there was some way to warn the user about this. If not possible to do by changing the NDK somehow, could take this to Android Studio and add a linter for CMakeLists.txt files?

#### Environment Details

* NDK Version: any
* Build system: cmake
* Host OS: any
* Compiler: any

**Comment by DanAlbert** [comment]
@jomof, think this is something Studio could do?

**Comment by DanAlbert** [comment]
(closing here because it's not something we could or actually should do in the NDK proper since our toolchain file is expected to be used *outside* Studio as well, but we can wait for Jomo to respond before you go file it with Studio)

**Comment by jomof** [comment]
I opened b.android.com/250967. Thanks for pointing it out hyrdgard
