### ISSUE TITLE
Unified Headers: openSLES.h is NOT included inside OpenSLES_Android.h ( which should)

### ISSUE THREAD

**Issue by ggfan** [android-ndk/ndk#330]
This is only concerning the unified headers:   for OpenSLES headers, the type macros are inside    
    OpenSLES.h  <--- this is top level header, used by other headers
It is used to be included inside header file:
   OpenSLES_Android.h

Not it is NOT, but <jni.h> was included instead.  It is not strictly a bug, user would just need to know the header file hierarchy and include them in his application in the right order, otherwise it will not compile

Also if user has not include the OpenSLES.h explicitly before, application MUST include it explicitly AND before including any other OpenSLES header files: otherwise, it will not compile.

Could this OpenSLES.h be added back into OpenSLES_Android.h?

Another question:
is <jni.h> necessary inside OpenSLES_Android.h file?

**Comment by DanAlbert** [comment]
Filed http://b/36362923 internally.

**Comment by gkasten** [comment]
Recommended practice is to include both headers, in order ...ES.h followed by ES_Android.h.

Will not fix.

**Comment by DanAlbert** [comment]
Thanks, @gkasten
