### ISSUE TITLE
RenderScript NDK weird bugs

### ISSUE THREAD

**Issue by coroner4817** [android-ndk/ndk#331]
#### Description
Struggled whole night with these errors.

## 1, `rsDebug` not working

```
03-17 14:19:25.331 20929-21040/com.yingnanwang.rskernelstest W/Adreno-RS: <rsdLoadMetaAndObjectFromCache:419>: Header check (sourceCheckSum) failed for /data/user/0/com.yingnanwang.rskernelstest/cache/Utils-adreno.meta
03-17 14:19:25.356 20929-21040/com.yingnanwang.rskernelstest W/Adreno-RS: <init:978>: ERROR: __BuildProgram returned -11
```

Kernel:
```
#include "ip.rsh"
#include "rs_debug.rsh"

void root(const float* in, float* out)
{
    rsDebug("DEBUG::", *in);
    *out += *in;
}
```

## 2, `invoke_*` func not working

```
03-17 14:21:10.129 22225-22334/com.yingnanwang.rskernelstest V/RenderScript: Successfully loaded runtime: libRSDriver_adreno.so
03-17 14:21:10.138 22225-22334/com.yingnanwang.rskernelstest W/Adreno-RS: <rsdLoadMetaAndObjectFromCache:419>: Header check (sourceCheckSum) failed for /data/user/0/com.yingnanwang.rskernelstest/cache/Utils-adreno.meta
03-17 14:21:10.199 22225-22340/com.yingnanwang.rskernelstest E/rsC++: RS Error The invokable index is out of bounds
03-17 14:21:10.199 22225-22340/com.yingnanwang.rskernelstest E/rsC++: RS CPP error: Error returned from runtime
03-17 14:21:10.200 22225-22225/com.yingnanwang.rskernelstest E/rsC++: RS CPP error (masked by previous error): Allocation creation failed
03-17 14:21:10.200 22225-22340/com.yingnanwang.rskernelstest E/rsC++: RS Error The invokable index is out of bounds
03-17 14:21:10.200 22225-22340/com.yingnanwang.rskernelstest E/rsC++: RS CPP error (masked by previous error): Error returned from runtime
03-17 14:21:10.200 22225-22225/com.yingnanwang.rskernelstest A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x14 in tid 22225 (g.rskernelstest)
                                                                     
                                                                     [ 03-17 14:21:10.201   270:  270 W/         ]
                                                                     debuggerd: handling request: pid=22225 uid=10274 gid=10274 tid=22225
```
kernel:
```
#include "ip.rsh"

void root(const float* in, float* out)
{
    *out += *in;
}

void test()
{

}
```
call:
`            sc->invoke_test();
`

## 3, Sometimes it give me this warning:

```
03-17 14:15:37.718 18159-18277/? W/Adreno-RS: <rsdLoadMetaAndObjectFromCache:419>: Header check (sourceCheckSum) failed for /data/user/0/com.yingnanwang.rskernelstest/cache/Utils-adreno.meta
03-17 14:15:37.854 18159-18171/? W/Binder: Binder call failed.
                                           java.lang.NullPointerException: Attempt to read from field 'android.view.ThreadedRenderer android.view.View$AttachInfo.mHardwareRenderer' on a null object reference
                                               at android.view.WindowManagerGlobal.dumpGfxInfo(WindowManagerGlobal.java:553)
                                               at android.app.ActivityThread$ApplicationThread.dumpGfxInfo(ActivityThread.java:1158)
                                               at android.app.ApplicationThreadNative.onTransact(ApplicationThreadNative.java:576)
                                               at android.os.Binder.execTransact(Binder.java:565)
```

#### Environment Details

* NDK Version: r14 release
* Build sytem: ndk-build + gradle
* Host OS: Mac
* Compiler: Clang
* ABI: arm
* STL: gnustl_shared
* NDK API level: 24
* Device API level: 25

**Comment by miaowang14** [comment]
Sorry to hear that. The issues look weird. Two questions:

What is the APP_PLATFORM defined in Application.mk?
How you compile the native module with RenderScript?

**Comment by coroner4817** [comment]
My Application.mk is:
```
APP_ABI := armeabi-v7a x86
APP_PLATFORM := android-24
APP_STL := gnustl_shared
```

I have update the above description. Remove some due to my mistakes. But the remaining issues can be reproduced.

**Comment by miaowang14** [comment]
Do you still have issues launching non "root" foreach kernels?

I tried to replicate your invoke_test in https://android.googlesource.com/platform/ndk.git/+/903809f8435ee96a6960e3589bedc0851f0b5bc1/tests/device/rs-cpp-basic/jni/mono.rs. And it works fine.

Before I dive in deeper: No need to include the internal RS headers like rs_debug.rsh, they are automatically handled.

**Comment by stephenhines** [comment]
For 1), it is possible (and likely) that the Adreno driver is rejecting your program because of the rsDebug() call. Those generally require tighter integration with the CPU side (because actual logcat I/O). When you execute the forEach(), does it actually show entries in the logcat? I am going to assume that it does, since I have seen similar 

For 3), are you talking about the Adreno warning (line 1) or the Binder warning (on line 2). I think line 2 is completely unrelated to RS, while line 1 looks like internal debugging info from the Adreno driver. It would probably be better if Qualcomm doesn't print that on user builds, since it seems harmless.

**Comment by coroner4817** [comment]
@miaowang14 I think that `root` function is for override, so If I don't specific `RS_KERNEL` I should override the `root` right?

@stephenhines 
For 1) I don't see any entries from `forEach`. I don't know whether this is because it's inside the overrided `root` function or NDK or other reason. Since I can see logs when I launch from Java and it's inside a `RS_KERNEL` function. 

For 2) I am still having this issue. I am using a Nexus 6. 
cpp:
```
    sp<ScriptC_utils> sc = new ScriptC_utils(rs);
    sc->invoke_test();
```
rs:
```
#pragma version(1)
#pragma rs java_package_name(com.yingnanwang.rskernelstest)
#pragma rs_fp_relaxed

void root(const float* in, float* out)
{
    *out += *in;
}

void test()
{

}
```

**Comment by miaowang14** [comment]
Actually, even if you don't specify RS_KERNEL, you should still be able to have kernels with different names, but similar signatures as the root function.

Did your application run well on the emulator?
Also, did you run ndk-build to build RenderScript and use the binary output in you application? Did you specify anything related to RenderScript in gradle?

**Comment by miaowang14** [comment]
I modified the code example (https://android.googlesource.com/platform/ndk.git/+/903809f8435ee96a6960e3589bedc0851f0b5bc1/tests/device/rs-cpp-basic/jni/) and added similar usages as yours (changing "root" to "sumalloc", etc), built with ndk r14 release on mac. And it runs well on Nexus6. So I guess something is wrong with your build environment.

**Comment by coroner4817** [comment]
@miaowang14 my build environment is same as this project: https://github.com/EE202B/RenderScriptNDK

I use gradle to run the `ndk-build` and link the generated libs.

**Comment by coroner4817** [comment]
My gradle build file is:

```
apply plugin: 'com.android.application'

def ndk_build_root = android.ndkDirectory.toString() + '/ndk-build'

android {
    compileSdkVersion 25
    buildToolsVersion "25.0.2"
    defaultConfig {
        applicationId "com.yingnanwang.rskernelstest"
        minSdkVersion 24
        targetSdkVersion 25
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
        ndk {
            abiFilters 'x86', 'armeabi-v7a'
        }
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    sourceSets {
        main {
            jni.srcDirs = []
            jniLibs.srcDirs = ['./libs/rsKernels_jni/obj/local']
        }
    }
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    compile 'com.android.support:appcompat-v7:25.2.0'
    compile 'com.android.support.constraint:constraint-layout:1.0.0-beta4'
    testCompile 'junit:junit:4.12'
}

task buildNative(type:Exec, description: "Task to run ndk-build") {
    workingDir './libs/rsKernels_jni'
    commandLine ndk_build_root, '-B'
}
tasks.withType(JavaCompile) {
    compileTask -> compileTask.dependsOn buildNative
}
clean {
    delete './libs/rsKernels_jni/libs'
    delete './libs/rsKernels_jni/obj'
}
```

**Comment by miaowang14** [comment]
The build.gradle looks a little bit convoluted. Even though it still works fine on my mac.

I simplified the makefile a bit to make sure gradle correctly call ndk build to get things done:
```
apply plugin: 'com.android.application'

android {
    compileSdkVersion 25
    buildToolsVersion "25.0.2"
    defaultConfig {
        applicationId "com.yingnanwang.cmakerstest4"
        minSdkVersion 23
        targetSdkVersion 25
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"

        ndk {
            abiFilters 'x86', 'armeabi-v7a'
        }
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }

    externalNativeBuild {
        ndkBuild {
            path 'libs/hellocomputendk/jni/Android.mk'
        }
    }
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    compile 'com.android.support:appcompat-v7:25.2.0'
    testCompile 'junit:junit:4.12'
}
```

Here is my sdk & ndk dirs:
ndk.dir=/Users/miaowang/Library/Android/sdk/ndk-bundle
sdk.dir=/Users/miaowang/Library/Android/sdk

**Comment by coroner4817** [comment]
@miaowang14 This really strange. I have wrote an [error reproduce project](https://github.com/EE202B/RenderScriptNDK/tree/error-reproduce). Can you try to run that on your phone? 

This one build success but completely failed on my Nexus6 at runtime and errors are:
```
03-17 23:39:06.712 16040-16094/? E/rsC++: RS Error The invokable index is out of bounds
03-17 23:39:06.712 16040-16094/? E/rsC++: RS CPP error: Error returned from runtime
03-17 23:39:06.712 16040-16094/? E/rsC++: RS Error The forEach kernel index is out of bounds
03-17 23:39:06.712 16040-16094/? E/rsC++: RS CPP error (masked by previous error): Error returned from runtime
```
My NDK version is 14.0.3770861. Thank you very much!

**Comment by miaowang14** [comment]
Just tried, it works well.

Maybe try clear your entire out dir and uninstall the app from your phone and try again?
Also did you try the build.gradle I posted?

**Comment by coroner4817** [comment]
OK after I uninstall the app from phone and reinstall it, it finally works again.

So does this means that I need to uninstall app every time I change my rs files?

**Comment by miaowang14** [comment]
When I use my build.gradle, I don't need to reinstall it.
(and if you enable InstantRun, it could complicate things)

Anyway, I am glad that things are working again. I will close this bug, but please let us know if you have any other questions.

**Comment by coroner4817** [comment]
Again Thank you very much for your helpful reply!

**Comment by coroner4817** [comment]
@miaowang14 Could you please help me on another issue? I don't know why my `BLAS->BNNM` always gives me all 0 result.

My function is [rsMatmul_bnnm](https://github.com/EE202B/RenderScriptOps/blob/master/app/libs/rsKernels_jni/jni/rsMatmul.h#L47) and function call is [BNNM smallTest](https://github.com/EE202B/RenderScriptOps/blob/master/app/libs/rsKernels_jni/jni/rsMatmul_test.h#L117)

I did the same as I did for SGEMM and also have transposed the B for BNNM. SGEMM works fine but BNNM failed.

**Comment by miaowang14** [comment]
the all 0 return value is expected because c_mult is 1 in smallTest.

Here is why:
[BNNM]( https://developer.android.com/reference/android/renderscript/ScriptIntrinsicBLAS.html#BNNM) does the following:
1. Calculate C = A * Transpose(B) in 1.10.21 fixed-point format.
2. C *= c_mult.
3. Shift the result right by 21 bits before return to make sure the results in C fit in 8-bit.

If the results of each intermediate 32 bit value in C is too small, the returned value will be 0 after (>>21).

To preserve these small values, you need to have a sufficiently large c_mult. You could probably refer to this [example](https://android.googlesource.com/platform/cts/+/master/tests/tests/rsblas/src/android/renderscript/cts/BNNMTest.java#158).

**Comment by coroner4817** [comment]
THX it works!

**Comment by coroner4817** [comment]
@miaowang14 Can we have an option of disabling the third step: `Shift result right by 21 bits` of BNNM in the next update?

I basically want to hijack the original Tensorflow `quantized_matmul_op` and replace the `gemmlowp::QuantizedGemm` with `RenderScript::BNNM`. But the output type of the `QuantizedGemm` is `int32_t` while `BNNM` output type is `uint8_t`. So there is a mismatch.

**Comment by miaowang14** [comment]
Thanks for the suggestion. I will discuss with my teammates internally to see if we could have a better story about BNNM, stay tuned. :)

**Comment by coroner4817** [comment]
@miaowang14 Thanks for your help I finally manage to run TensorFlow with RenderScript. 

However, although the computation speed is faster [Ops time consumption](https://github.com/EE202B/tensorflow/blob/RenderScript/tensorflow/contrib/android_renderscript_ops/doc/test-result.txt), the overall speed is slower (1.5sec per forward path) in comparison with the default Eigen computation (0.6sec per forward path). 

I notice that when RS is running, the CPU frequency is decrease and unstable. Is this cause by the RenderScript framework? Is there anyway I can do to maximized the efficiency? 

For more details you can see at [Issue](https://github.com/EE202B/tensorflow/tree/RenderScript/tensorflow/contrib/android_renderscript_ops#issue). Thanks.
