### ISSUE TITLE
Broken feature detection with unified headers

### ISSUE THREAD

**Issue by mperepelitsyn** [android-ndk/ndk#332]
#### Description

I've encountered a couple of issues with unified headers in r14 that I didn't see using r13b.

1. Boost Log
Missing: `pthread_spin_init`
Detection: `#if defined(_POSIX_SPIN_LOCKS) && _POSIX_SPIN_LOCKS > 0`
Code: https://github.com/boostorg/log/blob/boost-1.58.0/include/boost/log/detail/spin_mutex.hpp#L198
Available in API >= 24

2. Boost Thread 
Missing: `pthread_mutex_timedlock`
Detection: `#if _POSIX_TIMEOUTS >= 0 && _POSIX_TIMEOUTS>=200112L`
Code: https://github.com/boostorg/thread/blob/develop/include/boost/thread/pthread/mutex.hpp#L251
Available in API >= 21

3. Sqlite3
Missing: `mmap`
Detection: 
    ```
    # if defined(__linux__) \
      || defined(_WIN32) \
      || (defined(__APPLE__) && defined(__MACH__)) \
      || defined(__sun) \
      || defined(__FreeBSD__) \
      || defined(__DragonFly__)
    #   define SQLITE_MAX_MMAP_SIZE 0x7fff0000  /* 2147418112 */
    # else
    #   define SQLITE_MAX_MMAP_SIZE 0
    # endif
    ```
    Available in API >= 21

#### Environment Details
* NDK Version: 14.0.3770861
* Build sytem: custom
* Host OS: Linux
* Compiler: Clang
* ABI: x86
* STL: gnustl_shared
* NDK API level: 19
* Device API level: 19

**Comment by enh** [comment]
for the _POSIX_* stuff, does boost do the right thing and fall back to sysconf if we leave them undefined (since deleting these lines would be the quick fix)? i'm assuming not.

the sqlite one doesn't make sense. did you copy & paste the wrong section of the file?

**Comment by DanAlbert** [comment]
@jmgao: think you could use the versioner to apply guards to all the sysconf stuff?

**Comment by jmgao** [comment]
Don't think so, this probably has to be annotated by hand.

**Comment by DanAlbert** [comment]
I'm guessing no volunteers for that...

**Comment by mperepelitsyn** [comment]
@enh updated the description to include links to relevant code. If those macros are undefined, the features won't be used even if they are available for the API level.

Regarding sqlite3, it just assumes that `mmap` is here if `__linux__` is defined.

sys/mman.h:
```
#if defined(__USE_FILE_OFFSET64)

#if __ANDROID_API__ >= 21
void* mmap(void*, size_t, int, int, int, off_t) __RENAME(mmap64) __INTRODUCED_IN(21);
#endif /* __ANDROID_API__ >= 21 */

#else
void* mmap(void*, size_t, int, int, int, off_t);
#endif
```
And in my case I think I happen to have `__USE_FILE_OFFSET64` defined but `__ANDROID_API__` is 19.

**Comment by DanAlbert** [comment]
Ah, so same problem as we had in #324 for `mmap`. That one should at least be easy to fix.

**Comment by enh** [comment]
https://android-review.googlesource.com/355702 should fix these and others.

**Comment by 4brunu** [comment]
I'm also having an error building [SQLite](https://github.com/SRombauts/SQLiteCpp/blob/master/sqlite3/sqlite3.c) in [SQLiteCpp](https://github.com/SRombauts/SQLiteCpp).

Not sure if it's the same issue, or if I should open another issue.

```
Information:(11708, 38) expanded from macro 'ArraySize'
#define ArraySize(X)    ((int)(sizeof(X)/sizeof(X[0])))
                                     ^~~
/Users/user/Developer/MobileCPPBaseProject/deps/SQLiteCpp/sqlite3/sqlite3.c:29693:14: error: invalid application of 'sizeof' to an incomplete type 'struct unix_syscall []'
  for(i++; i<ArraySize(aSyscall); i++){
             ^~~~~~~~~~~~~~~~~~~
/Users/user/Developer/MobileCPPBaseProject/deps/SQLiteCpp/sqlite3/sqlite3.c:11708:38: note: expanded from macro 'ArraySize'
#define ArraySize(X)    ((int)(sizeof(X)/sizeof(X[0])))
                                     ^~~
6 errors generated.
ninja: build stopped: subcommand failed.
:app:externalNativeBuildDebug FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:externalNativeBuildDebug'.
> Build command failed.
  Error while executing process /Applications/android-sdk/cmake/3.6.3155560/bin/cmake with arguments {--build /Users/user/Developer/MobileCPPBaseProject/android_project/MobileCPPAndroid/app/.externalNativeBuild/cmake/debug/armeabi-v7a --target mobilecpp}
  [1/40] Building CXX object deps/json11/CMakeFiles/json11.dir/json11.cpp.o
  [2/40] Building CXX object deps/SQLiteCpp/CMakeFiles/SQLiteCpp.dir/src/Backup.cpp.o
  [3/40] Building CXX object deps/SQLiteCpp/CMakeFiles/SQLiteCpp.dir/src/Column.cpp.o
  [4/40] Building CXX object deps/SQLiteCpp/CMakeFiles/SQLiteCpp.dir/src/Database.cpp.o
  [5/40] Building CXX object deps/SQLiteCpp/CMakeFiles/SQLiteCpp.dir/src/Exception.cpp.o
  [6/40] Building CXX object deps/SQLiteCpp/CMakeFiles/SQLiteCpp.dir/src/Statement.cpp.o
  [7/40] Building CXX object deps/SQLiteCpp/CMakeFiles/SQLiteCpp.dir/src/Transaction.cpp.o
  [8/40] Building C object deps/SQLiteCpp/sqlite3/CMakeFiles/sqlite3.dir/sqlite3.c.o
  [9/40] Building CXX object deps/djinni/support-lib/CMakeFiles/djinni.dir/jni/djinni_support.cpp.o
  [10/40] Building CXX object deps/djinni/support-lib/CMakeFiles/djinni.dir/jni/djinni_main.cpp.o
  /Users/user/Developer/MobileCPPBaseProject/deps/SQLiteCpp/src/Database.cpp:31:13: warning: unused variable 'OPEN_MEMORY' [-Wunused-const-variable]
1 warning generated.
[11/40] Linking CXX static library deps/SQLiteCpp/libSQLiteCpp.a
[12/40] Linking CXX shared library ../../../../build/intermediates/cmake/debug/obj/armeabi-v7a/libdjinni.so
FAILED: /Users/user/Developer/MobileCPPBaseProject/android_project/MobileCPPAndroid/app/.externalNativeBuild/cmake/debug/armeabi-v7a/launch-c /Applications/android-sdk/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang  --target=armv7-none-linux-androideabi --gcc-toolchain=/Applications/android-sdk/ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64 --sysroot=/Applications/android-sdk/ndk-bundle/sysroot -DSQLITE_ENABLE_COLUMN_METADATA -I../../../../../../../deps/SQLiteCpp/include -I../../../../../../../deps/SQLiteCpp/sqlite3 -isystem /Applications/android-sdk/ndk-bundle/sysroot/usr/include/arm-linux-androideabi -D__ANDROID_API__=14 -g -DANDROID -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -march=armv7-a -mfloat-abi=softfp -mfpu=vfpv3-d16 -fno-integrated-as -mthumb -Wa,--noexecstack -Wformat -Werror=format-security -isystem /Applications/android-sdk/ndk-bundle/sysroot/usr/include/arm-linux-androideabi -D__ANDROID_API__=14 -g -DANDROID -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -march=armv7-a -mfloat-abi=softfp -mfpu=vfpv3-d16 -fno-integrated-as -mthumb -Wa,--noexecstack -Wformat -Werror=format-security  -Wall -O0 -fno-limit-debug-info -O0 -fno-limit-debug-info    -fstack-protector -Wall -Winit-self -Wswitch-enum -Wshadow -Winline -MD -MT deps/SQLiteCpp/sqlite3/CMakeFiles/sqlite3.dir/sqlite3.c.o -MF deps/SQLiteCpp/sqlite3/CMakeFiles/sqlite3.dir/sqlite3.c.o.d -o deps/SQLiteCpp/sqlite3/CMakeFiles/sqlite3.dir/sqlite3.c.o   -c /Users/user/Developer/MobileCPPBaseProject/deps/SQLiteCpp/sqlite3/sqlite3.c
/Users/user/Developer/MobileCPPBaseProject/deps/SQLiteCpp/sqlite3/sqlite3.c:29559:42: error: use of undeclared identifier 'mmap'
{ "mmap",         (sqlite3_syscall_ptr)mmap,            0 },
^
/Users/user/Developer/MobileCPPBaseProject/deps/SQLiteCpp/sqlite3/sqlite3.c:29636:22: error: invalid application of 'sizeof' to an incomplete type 'struct unix_syscall []'
for(i=0; i<sizeof(aSyscall)/sizeof(aSyscall[0]); i++){
^~~~~~~~~~
/Users/user/Developer/MobileCPPBaseProject/deps/SQLiteCpp/sqlite3/sqlite3.c:29645:22: error: invalid application of 'sizeof' to an incomplete type 'struct unix_syscall []'
for(i=0; i<sizeof(aSyscall)/sizeof(aSyscall[0]); i++){
^~~~~~~~~~
/Users/user/Developer/MobileCPPBaseProject/deps/SQLiteCpp/sqlite3/sqlite3.c:29672:20: error: invalid application of 'sizeof' to an incomplete type 'struct unix_syscall []'
for(i=0; i<sizeof(aSyscall)/sizeof(aSyscall[0]); i++){
^~~~~~~~~~
/Users/user/Developer/MobileCPPBaseProject/deps/SQLiteCpp/sqlite3/sqlite3.c:29689:16: error: invalid application of 'sizeof' to an incomplete type 'struct unix_syscall []'
for(i=0; i<ArraySize(aSyscall)-1; i++){
^~~~~~~~~~~~~~~~~~~
/Users/user/Developer/MobileCPPBaseProject/deps/SQLiteCpp/sqlite3/sqlite3.c:11708:38: note: expanded from macro 'ArraySize'
#define ArraySize(X)    ((int)(sizeof(X)/sizeof(X[0])))
^~~
/Users/user/Developer/MobileCPPBaseProject/deps/SQLiteCpp/sqlite3/sqlite3.c:29693:14: error: invalid application of 'sizeof' to an incomplete type 'struct unix_syscall []'
for(i++; i<ArraySize(aSyscall); i++){
^~~~~~~~~~~~~~~~~~~
/Users/user/Developer/MobileCPPBaseProject/deps/SQLiteCpp/sqlite3/sqlite3.c:11708:38: note: expanded from macro 'ArraySize'
#define ArraySize(X)    ((int)(sizeof(X)/sizeof(X[0])))
^~~
6 errors generated.
ninja: build stopped: subcommand failed.
```

**Environment Details**

NDK Version: 14.0.3770861
Build sytem: CMake
Host OS: macOS
Compiler: Clang
ABI: x86
STL: c++_static

**Comment by mperepelitsyn** [comment]
@4brunu, looks the same, you are missing `mmap`

**Comment by DanAlbert** [comment]
Just a heads up: this is going to be in r15 but won't be in beta 1. We've got a bunch of new code in the headers (better `FORTIFY` support) that requires a Clang newer than the one we have in the NDK right now and the new Clang has some issues with arm5, so we're not taking that update just yet. We should have another update really soon, but it won't be in time for beta 1. Apologies for the inconvenience!

**Comment by Zingam** [comment]
r16 - Remove deprecated headers <- Does this imply that the specific
  per version duplicated header files and sets in "platforms" will disappear?

**Comment by enh** [comment]
@Zingam yes, the duplicated headers will be removed as soon as we can get folks switched over to the up-to-date unified headers (which are basically the same headers we use to build the OS itself).

**Comment by alexcohn** [comment]
FWIW, we build SQlite3 adding `-D_FILE_OFFSET_BITS=32`

**Comment by astha-garg123** [comment]
@alexcohn , how Adding -D_FILE_OFFSET_BITS=32 solves the issue ? This solution is working but how ?

**Comment by enh** [comment]
he means it fixes "missing mmap" problems, because there *was* a 32-bit `off_t` mmap in old API levels. you only need new API levels if you want a 64-bit `off_t`.

**Comment by noangel** [comment]
updated to NDK 16 release today and got this in sqlite.c:

sqlite3.c:27147:14: error: call to 'mmap' declared with attribute error: mmap is not available with _FILE_OFFSET_BITS=64 when using GCC until android-21. Either raise your minSdkVersion, disable _FILE_OFFSET_BITS=64, or switch to Clang.
         pMem = mmap(0, szRegion,

solved by adding
 
#ifdef __ANDROID__
#define SQLITE_DISABLE_LFS
#endif

to head of sqlite.c.

**Comment by enh** [comment]
switching to clang would be a better choice. we're removing GCC in r18, so the sooner you switch the better. (we might want to change the error message to just say "switch to clang"...)
