### ISSUE TITLE
find and fix other _FILE_OFFSET_BITS=64 unified headers breakage

### ISSUE THREAD

**Issue by enh** [android-ndk/ndk#333]
https://github.com/android-ndk/ndk/issues/332 had mmap, but anywhere where we have an #if defined(__USE_FILE_OFFSET64) around a function that _doesn't_ have an __INTRODUCED_IN, we have a similar problem.

stdio.h:
```
int fgetpos(FILE*, fpos_t*);
int fsetpos(FILE*, const fpos_t*);
int fseeko(FILE*, off_t, int);
off_t ftello(FILE*);
...
FILE* funopen(const void*,
              int (*)(void*, char*, int),
              int (*)(void*, const char*, int),
              fpos_t (*)(void*, fpos_t, int),
              int (*)(void*));
```

sys/sendfile.h:
```
ssize_t sendfile(int out_fd, int in_fd, off_t* offset, size_t count);
```

unistd.h:
```
off_t lseek(int __fd, off_t __offset, int __whence);
```

**Comment by enh** [comment]
actually, lseek is okay because lseek64 has been here forever too...

**Comment by enh** [comment]
https://android-review.googlesource.com/354934 fixes sys/sendfile.h.

**Comment by enh** [comment]
https://android-review.googlesource.com/354857 fixes stdio.h.

**Comment by DanAlbert** [comment]
Just a heads up: this is going to be in r15 but won't be in beta 1. We've got a bunch of new code in the headers (better `FORTIFY` support) that requires a Clang newer than the one we have in the NDK right now and the new Clang has some issues with arm5, so we're not taking that update just yet. We should have another update really soon, but it won't be in time for beta 1. Apologies for the inconvenience!
