### ISSUE TITLE
gradle - ExternalNativeBuild breaks on copying STL if directory does not exist

### ISSUE THREAD

**Issue by Fimagena** [android-ndk/ndk#334]
_[not sure if to report here or on b.android.com?]_

When using the CMake toolchain and specifying an STL in `build.gradle` with 

    externalNativeBuild {
                cmake { arguments "-DANDROID_STL=c++_shared" }
    } 

...executing `gradlew ExternalNativeBuildDebug` (or building from Android Studio) will compile and link the code and will then copy the requested STL to the lib-directory. Using `--info` shows

    externalNativeBuildDebug: check expected build outputs
    externalNativeBuildDebug: copy STL shared object files
    externalNativeBuildDebug: copy file /Users/<user>/Library/Android/sdk/ndk-bundle/sources/cxx-stl/llvm-libc++/libs/x86/libc++_shared.so to <dir>/build/intermediates/cmake/debug/obj/x86/libc++_shared.so

However, the copying fails if the target directory does not exist! This can happen if I use `set_target_properties( <target> PROPERTIES LIBRARY_OUTPUT_DIRECTORY <dir> )` within my `CMakeLists.txt` to write my libs to another dir.  Unfortunately, the failed copying then breaks the full build!

    FAILURE: Build failed with an exception.

    * What went wrong:
    Execution failed for task ':<module>:externalNativeBuildDebug'.
    > java.io.FileNotFoundException: <dir>/build/intermediates/cmake/debug/obj/x86/libc++_shared.so (No such file or directory)

If I create the `build/intermediates/cmake/debug/obj/x86`-dir manually, the build completes. The `ExternalNativeBuild`-task should create missing directories when copying the `<STL>.so` file.

#### Environment Details

Not all of these will be relevant to every bug, but please provide as much
information as you can.

* NDK Version: V14.0.3770861
* Build system: gradle
* Host OS: Mac

**Comment by DanAlbert** [comment]
> [not sure if to report here or on b.android.com?]

Yep, the folks at b.android.com will be able to help you out (follow http://tools.android.com/filing-bugs). If you post back here with a link to the bug you file I can make sure it gets triaged quickly though.

**Comment by Fimagena** [comment]
Thanks for clarifying. I have posted it [here](https://code.google.com/p/android/issues/detail?id=256515).

**Comment by DanAlbert** [comment]
Triaged.

**Comment by boyw165** [comment]
Hi, so is there any workaround?

**Comment by DanAlbert** [comment]
See the Studio bug in the comment above.

**Comment by chinaminiren** [comment]
I encounter too

**Comment by chinaminiren** [comment]
by my test just android library will arise this problem

**Comment by DanAlbert** [comment]
See the linked Studio bug then.
