### ISSUE TITLE
standalone toolchain: -mthumb and -lsupc++ doesn't work when combined

### ISSUE THREAD

**Issue by fornwall** [android-ndk/ndk#335]
Steps to reproduce (tested on NRK r14 on a Linux host):

```sh
$ $NDK/build/tools/make_standalone_toolchain.py --arch arm --api 21 --install-dir=toolchain
$ echo 'int main() { return 0; }' > test.cpp

$ # This works:
$ ./toolchain/bin/arm-linux-androideabi-clang++ test.cpp -lsupc++

$ # This doesn't work:
$ ./toolchain/bin/arm-linux-androideabi-clang++ -mthumb test.cpp -lsupc++
ld: error: cannot find -lsupc++
```

Is it still so that if GNU libstdc++  is used with RTTI and exceptions one needs to explicitly link with libsupc++ as stated [here](https://developer.android.com/ndk/guides/standalone_toolchain.html#exceptions_rtti_and_stl)?

**Comment by DanAlbert** [comment]
> Is it still so that if GNU libstdc++ is used with RTTI and exceptions one needs to explicitly link with libsupc++ as stated here?

I don't believe it is. The goal was for standalone toolchains to Just Work. If it is still needed, it should be obvious because things wouldn't build at all.

**Comment by fornwall** [comment]
> I don't believe it is.

Great! This issue can then be closed unless you want to use it to track updating the documentation at https://developer.android.com/ndk/guides/standalone_toolchain.html#exceptions_rtti_and_stl.

As a general rule, should documentation issues under https://developer.android.com/ndk/ be reported here or at b.android.com?

**Comment by DanAlbert** [comment]
For the NDK docs site they mostly will come here. I'll get the docs fixed up. Thanks for spotting this!

**Comment by DanAlbert** [comment]
https://android-review.googlesource.com/c/356872/
