### ISSUE TITLE
Clang blocks until manually being killed

### ISSUE THREAD

**Issue by gapspt** [android-ndk/ndk#338]
#### Description

On MacOS, when using Objective-C properties of type "float" and compiling for arm with some optimization flag enabled, clang blocks forever (or until manually killed).
This happened originally when performing a CMake build, but it extends into clang itself.

How to reproduce:

- Step 1: Invoke the following commands to create two files that contain an Objective-C "float" property (but only the second file synthesizes it).
$ echo "@interface A               @property float f; @end @implementation A                     @end" > a.m
$ echo "@interface B { float _f; } @property float f; @end @implementation B @synthesize f = _f; @end" > b.m

- Step 2: Run 3 distinct clang commands on both files (the commands are described bellow)
a) The first command is a short version of what cmake invokes, containing only the minimum necessary arguments
b) The second command uses -cc1 and is derived from the first command (by using the -v), and also trimmed to the minimum necessary arguments
c) The third command is the same as the second, but without specifying -fobjc-runtime=gcc

Commands applied to the first file:
$ android-ndk-r14/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang --target=armv5te-none-linux-androideabi -O1 -c a.m
$ android-ndk-r14/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang -cc1 -triple armv5e-none-linux-android -emit-obj -O1 -fobjc-runtime=gcc a.m
$ android-ndk-r14/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang -cc1 -triple armv5e-none-linux-android -emit-obj -O1 a.m

Commands applied to the second file:
$ android-ndk-r14/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang --target=armv5te-none-linux-androideabi -O1 -c b.m
$ android-ndk-r14/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang -cc1 -triple armv5e-none-linux-android -emit-obj -O1 -fobjc-runtime=gcc b.m
$ android-ndk-r14/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang -cc1 -triple armv5e-none-linux-android -emit-obj -O1 b.m

Results:
First and second command actually work fine and compile the a.m but the third command blocks forever, only returning when you kill the clang process.
For the b.m file however, all the commands block forever, only returning if you kill the clang process.

Expected results:
All the commands should return (even if with errors), and not block forever.

Things that prevent the issue from happening in all of the above cases:
a) Not having an Objective-C property
b) Changing the property type from "float" to "int" or even to "double".
c) Compiling for armv7a
d) Not using the -O1 optimization flag (and not using any other than -O0)
e) Using another NDK version (such as 13b)

#### Environment Details

* NDK Version: 14.0.3770861
* Build sytem: cmake (but the problem extends into clang, not actually the cmake build system)
* Host OS: mac
* Compiler: clang
* ABI: arm
* STL: N/A
* NDK API level: N/A
* Device API level: N/A

**Comment by pirama-arumuga-nainar** [comment]
This seems to be due to lack of atomic support for `float` in `armv5`.  The following snippet can also be compiled for `armv7`:

> define float @foo(float* %f) {
  %load1 = load atomic float, float* %f unordered, align 4
  ret float %load1
}

but throws a backend error for `armv5`:

> Do not know how to soften the result of this operator!
UNREACHABLE executed at /ssd1/pirama/llvm-upstream/llvm/lib/CodeGen/SelectionDAG/LegalizeFloatTypes.cpp:60!

The backend should be able to translate this to the integer load, if it is supported.

**Comment by pirama-arumuga-nainar** [comment]
I'm sorry, the above comment has a few missing details.  The clang commands from the original bug report also throw the same error as my previous comment on an assertion-enabled LLVM build.

**Comment by gapspt** [comment]
@pirama-arumuga-nainar Any clue on why only on NDK 14?

**Comment by stephenhines** [comment]
NDK-14 updated the version of Clang in use by the NDK, hence why this is only appearing as an issue now. I am not sure that the NDK officially supports the use of Objective-C. Even though this is Clang, we don't test ObjC at all, so we make no guarantees about using it for non-NDK use. We can try to get this fixed for r15, but it is low priority.

**Comment by DanAlbert** [comment]
> I am not sure that the NDK officially supports the use of Objective-C

We do not.

Odds are this will be fixed by chance by the next clang update, but I'm going to close this since I don't plan for us to do any work on it.
