### ISSUE TITLE
Unified Headers: Is strerror_r really __ANDROID_API__ >= 23 ?

### ISSUE THREAD

**Issue by gershnik-smartsheet** [android-ndk/ndk#339]
Code that uses it and used to compile (arm and x86) for API 19 now breaks with unified headers.
Didn't do any actual investigation whether the function is physically there below 23 but either the old headers have a bug or the new ones do.

**Comment by DanAlbert** [comment]
Dup of https://github.com/android-ndk/ndk/issues/324

The fix for this was released in r14b earlier today (it's only in the beta channel of the SDK manager for the moment, but we expect to push it to stable shortly).

**Comment by gershnik-smartsheet** [comment]
Oh, the blog post didn't make it clear so I assumed I already have the latest and greatest :)

**Comment by DanAlbert** [comment]
Yeah, that was actually the blog post for r14 (not r14b). It just took a long time to get it published. Sorry for the confusion!

It should be perfectly safe to update to r14b even though it's in the beta channel. It's a really small set of changes.

**Comment by gershnik-smartsheet** [comment]
No problem at all and will try now. I won't complain about the other issue I see with Boost threads and missing pthread_mutex_timedlock until I check with r14b then :)

**Comment by enh** [comment]
(neither of those are fixed in r14b. the fixes went into bionic yesterday, but aren't even in a nightly NDK yet.)
