### ISSUE TITLE
AAudio header/lib missing

### ISSUE THREAD

**Issue by hrydgard** [android-ndk/ndk#343]
#### Description

The new Android-O developer preview supports a new native audio API, AAudio, and there's even a code sample: https://github.com/googlesamples/android-audio-high-performance

However, as far as I can find, there are no headers nor a library to link to in the NDK so we can't actually experiment with it yet.  (```find . -name "*.h" | xargs grep AAudioStream_write``` in the NDK returns nothing)

Will it be in NDK 15? Or is there a preview NDK to download somewhere?

#### Environment Details

* NDK Version: 14b

**Comment by DanAlbert** [comment]
Yeah, sorry about this. We've had a couple logistics SNAFUs so the build of the NDK with these is still coming. AAudio is actually in the canary NDKs now: https://android.googlesource.com/platform/ndk/+/master/docs/ContinuousBuilds.md

I'm working on getting r15 beta 1 ready for this ASAP. The first build of the r15 branch is happening as we speak.

**Comment by hrydgard** [comment]
Alright, thanks for the info!

**Comment by DanAlbert** [comment]
The r15 branch is now live in the public build site, FYI. There was a bit of a mix up and the shared libs for the O APIs actually weren't in the build earlier, but the one that's churning right now should be good.

**Comment by hrydgard** [comment]
Nice, thank you! I'll close this.
