### ISSUE TITLE
Amalgamation compile error for Android

### ISSUE THREAD

**Issue by PKUEcho** [android-ndk/ndk#344]
Cannot build Amalgamation on my Mac 10.10.

This is how I build the standalone toolchain
`python build/tools/make_standalone_toolchain.py --stl=libc++ --arch arm --api 21 --install-dir /tmp/my-android-toolchain`

And I change the OPENBLAS_ROOT, SYS_ROOT, CXX, CC following the instructions. But when I compiled I got errors like this
`/Users/echo/Library/Android/my-android-toolchain/include/c++/4.9.x/cstddef:43:25: fatal error: stddef.h: No such file or directory`

Then I read [this thread](https://github.com/android-ndk/ndk/issues/215), and add this to makefile
`# DEFS+=-isystem /Users/echo/Library/Android/my-android-toolchain/include/c++/4.9.x`

Then the error becomes following
`jni/../mxnet_predict-all.cc:53:36: fatal error: src/c_api/c_api_error.cc: No such file or directory`

I also tried Clang, as I change the makefile like this
`export SYS_ROOT=/Users/echo/Library/Android/my-android-toolchain/sysroot`
`export CXX=/Users/echo/Library/Android/my-android-toolchain/bin/arm-linux-androideabi-clang++`
`export CC=/Users/echo/Library/Android/my-android-toolchain/bin/arm-linux-androideabi-clang`

But the error remains
`jni/../mxnet_predict-all.cc:53:10: fatal error: 'src/c_api/c_api_error.cc' file not found`

Anyone can help me to compile this?

**Comment by enh** [comment]
seems like you're trying to build https://github.com/apache/incubator-mxnet/tree/master/amalgamation ? do the instructions on their page not work?

https://developer.android.com/ndk/guides/standalone_toolchain explains how to build a standalone toolchain, with an example at the end.

**Comment by tangxinfa** [comment]
@enh I trying to build nginx with pcre, and i found the reason:
    standalone toolchain's gcc is broken, i use clang instead.

See https://github.com/android-ndk/ndk/issues/215 for more information.

Finally, i give up to build nginx with NDK, because NDK's libc is NOT glibc,
missing "crypt.h" which required by nginx.
