### ISSUE TITLE
OpenSL ES SLPrefetchStatusItf underflow assert aborts application on new audio data after completely emptying, desired?

### ISSUE THREAD

**Issue by Gundersanne** [android-ndk/ndk#345]
#### Description

It concerns this assert in https://android.googlesource.com/platform/frameworks/wilhelm/+/master/src/android/AudioPlayer_to_android.cpp around line 2402.
```
void android_audioPlayer_bufferQueue_onRefilled_l(CAudioPlayer *ap) {
    ...
    assert(SL_PREFETCHSTATUS_UNDERFLOW == ap->mPrefetchStatus.mStatus);
    ...
}
```

This assert fails when using the SLPrefetchStatusItf in OpenSL ES when you requeue new data after the buffer underflows and empties, and thus aborts the entire application. My question is simply, is this desired behaviour?

As I understand it correctly the OpenSL ES specification states that when you fail to enqueue enough data, the playback should simply stop, and not abort the entire application (as defined in https://www.khronos.org/registry/OpenSL-ES/specs/OpenSL_ES_Specification_1.0.1.pdf on page 176 of the document, under comments of SLBufferQueueItf's Enqueue method).

Now the OpenSL ES implementation works fine on without the SLPrefetchStatusItf; even the underflows +emptying of the buffers don't abort the entire application but simply stop playback and resume when more data is available.

As soon as you instantiate this Interface (which I'd like to, to pass some buffer underflow information to the user), the underflow and more precisely the emptying of the buffer + requeueing new data crash the app.

#### Environment Details

* NDK Version: 14.1.3816874 
(and ndk r9b)
* Build sytem: standalone toolchain
* Host OS: Ubuntu 16.04 LTS
* Compiler: gcc and clang tested
* ABI: android-19-armeabi-v7a and android-14-armeabi-v7a
* STL: gnustl_shared
* NDK API level: 19, 14
* Device API level: 19

**Comment by Gundersanne** [comment]
Woops, I realized this should probably be filed under the android platform, not in the android-ndk. Apologies.

**Comment by enh** [comment]
(that bug is https://code.google.com/p/android/issues/detail?id=265204, and i've added audio folks to it.)
