### ISSUE TITLE
Removal of linux/android_alarm.h from NDK 14 onwards

### ISSUE THREAD

**Issue by mikebarber** [android-ndk/ndk#347]
#### Description

Building PJSIP's Open source multimedia communication library and when moving to the latest NDK 14b found it did not build as linux/android-alarm.h was missing. Had been using NDK 14 beta2 with no problem

The function used from that header is  ANDROID_ALARM_GET_TIME(ANDROID_ALARM_ELAPSED_REALTIME)

Is this an omission from the NDK or has access to this functionality been removed and if so is there a workaround

#### Environment Details

* NDK Version: 14.0.3770861 and 14.1.3816874
* Build sytem:  standalone toolchain
* Host OS: Mac
* Compiler: Clang
* ABI: Armv7a, Arm64, x86, x86_64
* STL:c++_static
* NDK API level:21
* Device API level:24

**Comment by enh** [comment]
this functionality has been removed from the kernel for a while now.

it looks like the Android-specific code in pjlib/src/pj/os_timestamp_posix.c should just be deleted; Android should be fine with the POSIX section below that instead.

**Comment by enh** [comment]
(the Android code basically has a copy of the POSIX code as its fallback path, so you're just running a slow version of the POSIX code right now on the latest devices :-) )

**Comment by mikebarber** [comment]
Thanks enh for the info I have patched as above and passed this info on to PJSIP support

**Comment by dailijun** [comment]
thanks
