### ISSUE TITLE
Cmake in android studio links to libsupc++.a when using ANDROID_STL=system, even when RTTI and exceptions are explicitly disabled.

### ISSUE THREAD

**Issue by mUfoq** [android-ndk/ndk#349]
#### Description

I'm using AS2.3 with cmake 3.6.3155560. I set cppFlags to "-fno-exceptions", "-fno-rtti" and arguments to "-DANDROID_STL=system". 
However I can see in build.ninja that AS still adds path to libsupc++.a to LINK_LIBRARIES what makes my *.so files 3x bigger.

I can get rid of it by explicitly setting arguments like "-DANDROID_STL=system", "-DCMAKE_CXX_STANDARD_LIBRARIES=-Lm", but I don't know if it is ok to do so, afaik supc++ is used for rtti and exceptions features that I don't use anyway (or am I wrong?). Idk why it is linked when it looks like it's not dependency. There is no linker errors and it look like everything works.

So am I missing something or it is bug and it shouldn't be linked when using system STL?

Thanks.

#### Environment Details

* NDK Version: Pkg.Revision = 14.0.3770861
* Build sytem: cmake 3.6.3155560 (bundled in AS2.3)
* Host OS: Ubuntu 14.04
* Compiler: clang and gcc
* ABI: armeabi, armeabi-v7a (may be for more but i didn't check)
* STL: system
* NDK API level: I tested with 14,16,25, so I guess it doesn't matter
* Device API level: 25

#### More

I tested it again with sample Cmake project generated with AS added only config for cmake:
```
        externalNativeBuild {
            cmake {
                cppFlags "-std=c++11", "-fno-exceptions", "-fno-rtti"
                arguments "-DANDROID_STL=system"
            }
        }
        ndk {
            abiFilters 'armeabi', 'armeabi-v7a'
        }
```
and changed c++ string to c strings in code because it doesn't find <string> header when i change STL to system (or it is another bug), so native-lib.cpp looks like:
```
#include <jni.h>

extern "C"
JNIEXPORT jstring JNICALL
Java_com_demo_cmaketest_MainActivity_stringFromJNI(
        JNIEnv* env,
        jobject /* this */) {
    return env->NewStringUTF("Hello from C++");
}
```
also I made cmakelists minimal so it doesn't even include log lib:
```
cmake_minimum_required(VERSION 3.4.1)
add_library(native-lib SHARED src/main/cpp/native-lib.cpp )
```
but still it includes supc++ (which ndkBuild and deprecated ndk don't with similiar settings):
`LINK_LIBRARIES = -lm "/home/ufoq/tools/android-sdk/ndk-bundle/sources/cxx-stl/gnu-libstdc++/4.9/libs/armeabi-v7a/libsupc++.a"`

**Comment by DanAlbert** [comment]
https://android-review.googlesource.com/413384
