### ISSUE TITLE
Provide at least two versions of NDK

### ISSUE THREAD

**Issue by Alexander--** [android-ndk/ndk#351]
I have just updated to ndk-bundle 14.1.3816874 and everything is utterly unusable: calling functions from linux_syscall-support results in segfaults, there are stack corruptions everywhere, crashes out of blue etc. etc. Please consider shipping updates simultaneously with older versions instead of removing them.

Thanks.

**Comment by enh** [comment]
https://github.com/android-ndk/ndk/wiki

**Comment by DanAlbert** [comment]
> everything is utterly unusable: calling functions from linux_syscall-support results in segfaults, there are stack corruptions everywhere, crashes out of blue etc. etc.

Have you filed bugs? We've had no reports of issues this severe.

**Comment by Alexander--** [comment]
@enh Those downloads aren't available in sdkmanager.

**Comment by DanAlbert** [comment]
Being able to install multiple NDKs fromt he SDK manager is something the Studio team is working on (it's not part of the NDK, which is the only part we do).

Could you please file some bugs about the issues you're seeing? If you don't report them we can't fix them.

**Comment by Alexander--** [comment]
@DanAlbert Thanks for explanation. I suppose, that can also be added to FAQ.

> Could you please file some bugs about the issues you're seeing? If you don't report them we can't fix them

 If sdkmanager downloads are outside of your control, you probably won't be able to fix them anyway.

**Comment by stephenhines** [comment]
Dan was talking about your original request mentioning that r15 is "utterly unusable". Can you file bugs about those issues? Thanks.

**Comment by stephenhines** [comment]
r14, not r15
