### ISSUE TITLE
cmake : find_package(OpenGL)

### ISSUE THREAD

**Issue by cdemez** [android-ndk/ndk#353]
#### Description

I'm using cmake to build my C++ code, but the cmake function:
    find_package(OpenGL REQUIRED)

output an error message : Could NOT find OpenGL (missing: OPENGL_gl_LIBRARY OPENGL_INCLUDE_DIR)

From what I understand cmake is not targeted for Android/Android studio at all !!!

All the files are there, except that FindOpenGL.cmake has no Android section.

I also see the following example : [https://github.com/googlesamples/android-ndk/tree/master/gles3jni]

But they don't use any Find... feature ! Is it a missing feature ?

**Comment by DanAlbert** [comment]
Use `find_library` instead of `find_package`.
