### ISSUE TITLE
abi::_cxa_demangle` on `type_info` doesn't work with clang and libc++ and last NDK (r14b).

### ISSUE THREAD

**Issue by schweitzer** [android-ndk/ndk#355]
#### Description
Hi everyone,

I'm using the `abi::_cxa_demangle` to demangle type name ( `typeid::name`), but it doesn't work with latest NDK r14b (14.1.3816874) it was working at least with the NDK r12 (12.0.2931149).

Here's a simple c++ example:

```
#include <cxxabi.h>
#include <cstdlib>
#include <iostream>

class A
{
};

void main(void)
{
    A a;
    char const * mangled = typeid( a ).name();
    char * c_demangled;
    int status = 0;
    c_demangled = abi::__cxa_demangle( mangled, nullptr, nullptr, &status);

    std::string res;
    if (c_demangled)
    {
        res = c_demangled;
        free(c_demangled);
    }
    else
    {
        res = mangled;
    }

    free(c_demangled);

    std::cout<< "---- MANGLED : " << mangled <<std::endl;
    std::cout<< "---- DEMANGLED : " << res <<std::endl;
}
```

it returns:
---- MANGLED : 1A
---- DEMANGLED : 1A

if we do the same with `c++filt -t` it returns **A**.

It seems that the issue may come from the *cxa_demangle.cpp* file, the test line **4983** is quite suspicious as the mangled name of type will not start with "_Z".

```
...

extern "C" _LIBCXXABI_FUNC_VIS char *
__cxa_demangle(const char *mangled_name, char *buf, size_t *n, int *status) {
    if (mangled_name == nullptr || (buf != nullptr && n == nullptr))
    {
        if (status)
            *status = invalid_args;
        return nullptr;
    }

    size_t len = std::strlen(mangled_name);
--> if (len < 2 || strncmp(mangled_name, "_Z", 2))
    {
        if (len < 4 || strncmp(mangled_name, "___Z", 4))
        {
            if (status)
                *status = invalid_mangled_name;
            return nullptr;
        }
    }
...
```

Is there something I missed ?

#### Environment Details

* NDK Version: 14.1.3816874
* Build sytem: CMake
* Host OS: Linux Mint 18.1.
* Compiler: Clang
* ABI: armeabi-v7
* STL: libc++
* NDK API level: 23
* Device API level: 23

**Comment by schweitzer** [comment]
I investiguated a bit more on this issue, and the bug was introduced by llvm team with this commit http://llvm.org/viewvc/llvm-project?view=revision&revision=286793

And was resolved 2 months ago by this one: http://llvm.org/viewvc/llvm-project?view=revision&revision=292418

The ndk r14 was released just before the fix.

**Comment by DanAlbert** [comment]
Thanks for tracking down the commit. I'll make sure to pull a libc++abi update for r15.

**Comment by DanAlbert** [comment]
https://android-review.googlesource.com/403115

**Comment by DanAlbert** [comment]
Cherry-picked into r15.
