### ISSUE TITLE
Linking CXX shared library complaining about a missing include file

### ISSUE THREAD

**Issue by intelzombi** [android-ndk/ndk#356]
--------------------------------------------------------------------------------

#### Description
My blocking issue is that the Build seems to compile everything for this library but it fails to link.  It is complaining about a missing header file which makes no sense for a linking phase.  Why is the Linker phase trying to find a header file? Why is the build system pulling over the -include compile flag for linking?  On inspection it appears that all the .o files are created in the app/externalNativeBuild/cmake/debug/armeabi-v7a/src/main/jni/<projcet>/CMakeFiles/MyCore.dir/code/*.o

I get the same result using either Android Studio Make or the cmd line ./gradlew app:assemble
below is the best editing I can do for the error output.  I've included as much as I can and still maintain some obfuscation on our project. 

[1/1] Linking CXX shared library ../../../../build/intermediates/cmake/debug/obj/armeabi-v7a/libMyCore.so
/<PathToToolChain>/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang++  --target=armv7-none-linux-androideabi --gcc-toolchain=/<PathToSDK>/sdk/ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64 --sysroot=/<PathToSDK>/sdk/ndk-bundle/platforms/android-21/arch-arm -fPIC -g -DANDROID -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -march=armv7-a -mfloat-abi=softfp -mfpu=vfpv3-d16 -fno-integrated-as -mthumb -Wa,--noexecstack -Wformat -Werror=format-security -std=c++11 -g -DANDROID -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -march=armv7-a -mfloat-abi=softfp -mfpu=vfpv3-d16 -fno-integrated-as -mthumb -Wa,--noexecstack -Wformat -Werror=format-security -std=c++11 -std=c++11 -frtti -fexceptions -isystem /<DesignatedSystemOverrideFiles>/MS/DX/June2010 -isystem /<DesignatedSystemOverrideFiles>/MS/Win/8.0/um -isystem /<DesignatedSystemOverrideFiles>/MS/Win/8.0/shared -isystem /<DesignatedSystemOverrideFiles>/MS/Win/8.0 -include /<SomeImportantPrefixHeaderDir>/MyPrefix.h -DTonsOf-DCompileArguments=1  ... -DYetMore-DArguments -fsigned-char  -Wno-format -x c++  -O0 -fno-limit-debug-info -O0 -fno-limit-debug-info  -Wl,--build-id -Wl,--warn-shared-textrel -Wl,--fatal-warnings -Wl,--fix-cortex-a8 -Wl,--exclude-libs,libunwind.a -L/Users/hsmith/dk/adt-bundle-mac-x86_64-20140702/sdk/ndk-bundle/sources/cxx-stl/llvm-libc++/libs/armeabi-v7a -Wl,--no-undefined -Wl,-z,noexecstack -Qunused-arguments -Wl,-z,relro -Wl,-z,now -Wl,--build-id -Wl,--warn-shared-textrel -Wl,--fatal-warnings -Wl,--fix-cortex-a8 -Wl,--exclude-libs,libunwind.a -L/<PathToSDK>/sdk/ndk-bundle/sources/cxx-stl/llvm-libc++/libs/armeabi-v7a -Wl,--no-undefined -Wl,-z,noexecstack -Qunused-arguments -Wl,-z,relro -Wl,-z,now -shared -Wl,-soname,libMyCore.so -o ../../../../build/intermediates/cmake/debug/obj/armeabi-v7a/libMyCore.so src/main/jni/<AllMySourceFiles>/OneOfMany.cpp.o
.... LOTS of .o files
src/main/jni/<AllMySourceFiles>/ManyMore.cpp.o
  ../../../../../<myPreBuiltLibs>/libs/armeabi-v7a/libOneOfMany.a ../../../../../<myPreBuiltLibs>/libs/armeabi-v7a/libYetAnother.a -llog -landroid -ldl -lGLESv1_CM -lOpenSLES ../../../../../external/libs/armeabi-v7a/libc++_shared.so ../../../../../external/libs/armeabi-v7a/libiconv.so ../../../../../external/libs/armeabi-v7a/libObbVfs.so ../../../../../<myPreBuiltLibs>/libs/armeabi-v7a/libSomeShareLibrary.so ../../../../src/main/jni/<thirdPartyPrebuilt>/arm/lib3rdParty_prebuilt.a  -lm "/<PathToSDK>/sdk/ndk-bundle/sources/cxx-stl/llvm-libc++/libs/armeabi-v7a/libc++.so"
In file included from <built-in>:1:
In file included from /<SomeImportantPrefixHeaderDir>/MyPrefix.h:5:
/<SomeOtherHeaderDir>/SomeIncludedFile.h:5:10: fatal error: 'AnotherIncludedFile.h' file not found
#include <AnotherIncludedFile.h>
         ^
1 warning and 2 errors generated.
ninja: build stopped: subcommand failed.
:app:externalNativeBuildDebug FAILED

Please note: the offending Header "MyPrefix.h" is NOT a precompiled header. CMake doesn't accommodate the creation of precompiled headers.
The -include for this file is a needed switch and is the same switch we used for the ndk-build version of Android.mk for this application

I have two CMakeLists.txt files
The top level one that  is in the app directory and a core library one in the app/src/main/jni/<project> directory
Top Level CMakeLists.txt
cmake_minimum_required(VERSION 3.4.1)

project("MyCore")
#set all my Path information
set(SOME_PATH "${CMAKE_SOURCE_DIR}/src/main/jni")
set ... set .. set
#add all my prebuilt library info
add_library(lib_OneOfMany STATIC IMPORTED)
set_target_properties(lib_OneOfMany PROPERTIES IMPORTED_LOCATION
    ${distribution_DIR}/libs/${ANDROID_ABI}/libOneOfMany.a)

add_library(lib_LotsOf SHARED IMPORTED)
set_target_properties(lib_LotsOf PROPERTIES IMPORTED_LOCATION
    ${distribution_DIR}/libs/${ANDROID_ABI}/libLotsOf.so)

# note this is commented out but if I do include this prebuilt library from the ndk-build I 
# successfully get a working version of my application.
#add_library(lib_MyCore SHARED IMPORTED)
#                set_target_properties(lib_MyCore PROPERTIES IMPORTED_LOCATION
#                    ${distribution_DIR}/libs/${ANDROID_ABI}/libMyCore.so)

#attempt to build the library rather than import a prebuilt version
add_subdirectory(src/main/jni/myCore)

Project CMakeLists.txt
cmake_minimum_required(VERSION 3.4.1)
project(MyProj C CXX)
file(GLOB_RECURSE myCoreSources "${CMAKE_CURRENT_LIST_DIR}/code/*.c" "${CMAKE_CURRENT_LIST_DIR}/code/*.cpp" "${CMAKE_CURRENT_LIST_DIR}/code/*.cp")

SET(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -isystem ${PathDXSDK}" )
SET(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -isystem ${PathWinSDK}/um" )
SET(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -isystem ${PathWinSDK}/shared" )
SET(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -isystem ${PathWinSDK}" )
SET(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -include ${SomeImportantPrefixHeaderDir}/MyPrefix.h" )

SET(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -DLotsOf-DFlags=1 -D... ")
set( CMAKE_CXX_FLAGS            "${CMAKE_CXX_FLAGS} -fsigned-char  -Wno-format -x c++ " )

add_library( MyCore
             SHARED
             ${myCoreSources} )

set(mCoreIncludes "")
list(APPEND mCoreIncludes "${Some_PATH}/include")
list(APPEND mCoreIncludes "${SomeOtherIncludePath}")
...

target_include_directories(MyCore PUBLIC ${myCoreIncludes})
find_library( log-lib
              log )
find_library( android-lib
              android )
find_library( dl-lib
              dl )
find_library( GLESv1_CM-lib
              GLESv1_CM )
find_library( GLESv2-lib
              GLESv2 )
string(APPEND CMAKE_${lang}_STANDARD_LIBRARIES " -latomic")
find_library( OpenSLES-lib
              OpenSLES )

target_link_libraries( 
                      MyCore
                      lib_Private
                      lib_One
                      ${log-lib}
                      ${android-lib}
                      ${dl-lib}
                      ${GLESv1_CM-lib}
                      ${atomic-lib}
                      ${OpenSLES-lib}
                      lib_Two
                      lib_Three
                      lib_Four
                      lib_Five
                      lib_c++_shared
                      lib_Six
                      lib_Eight
                      lib_Nine
                      lib_Ten
                      lib_Eleven
                      )

The only thing else I can think to add is the gradle.build info
android {
	compileSdkVersion 25
	buildToolsVersion "25.0.2"
	useLibrary 'org.apache.http.legacy'
	defaultConfig {
		applicationId "com.us.mycore"
		minSdkVersion 21
		targetSdkVersion 25
		versionCode 1
		versionName "1.0"
		testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
		multiDexEnabled true
		externalNativeBuild {
			cmake {
				cppFlags "-std=c++11 -frtti -fexceptions "
				abiFilters "armeabi-v7a"
				arguments "-DANDROID_STL=c++_shared"
			}
		}
	}
	buildTypes {
		release {
			minifyEnabled false
			proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
		}
		debug {
			//jniDebuggable true
		}
	}
	sourceSets {
		main {
			// let gradle pack the shared library into apk
			jniLibs.srcDirs = ['../external/libs']
		}
	}
	
	externalNativeBuild {
		cmake {
			path "CMakeLists.txt"
		}
	}

Some background.  We have successfully used the ndk-build system to produce and publish several large Android applications.  This is our first attempt at a migration from a working ndk-build project using *.mk files to convert to the CMake Android Studio build system.  This project has 5 .so shared libraries,  7 .a static libraries and 3 prebuilt .a 3rd party libraries.  This is the typical dependency complexity for our projects. 
For this task I've decided to pull over and use all but the main core library as prebuilt libraries that I built with the ndk-build.   Therefore I only need to compile and build the mainCore.so file.  I then will just link in the prebuilt libraries.  Once this is successful my intent is then to migrate all the other shared and static libraries to cmake for inclusion in the gradle build.  

#### Environment Details

I've updated to the most current  versions available before submitting

* NDK Version: Pkg.Desc = Android NDK
Pkg.Revision = 14.1.3816874
* Build sytem: cmake  (also pulling in and using prebuilt libraries from ndk-build)
* Host OS: Mac
* Compiler: Clang
* ABI:  armeabi-v7
* STL: c++shared
* NDK API level:
* Device API level:

ANDROID_TOOLCHAIN clang
ANDROID_ABI armeabi-v7a
ANDROID_PLATFORM android-21
ANDROID_STL c++_shared
ANDROID_PIE TRUE
ANDROID_CPP_FEATURES 
ANDROID_ALLOW_UNDEFINED_SYMBOLS FALSE
ANDROID_ARM_MODE thumb
ANDROID_ARM_NEON 
ANDROID_DISABLE_NO_EXECUTE FALSE
ANDROID_DISABLE_RELRO FALSE
ANDROID_DISABLE_FORMAT_STRING_CHECKS 
ANDROID_CCACHE

**Comment by enh** [comment]
looks like a question for the Studio/gradle folks over at b.android.com...

**Comment by intelzombi** [comment]
OK.  I'll file it there.  I don't really think you actually looked at the bug though.  This an ndk clang tool compiler link error.

**Comment by intelzombi** [comment]
submitted to b.android.com
https://code.google.com/p/android/issues/detail?id=329650&thanks=329650&ts=1491423586

**Comment by DanAlbert** [comment]
Not actually clear to me whose bug this is, but since it might involve Studio and possibly the clang folks at this point I think buganizer is the easiest place to discuss this anyway.
