### ISSUE TITLE
sys/atomics.h and unified headers

### ISSUE THREAD

**Issue by alexcohn** [android-ndk/ndk#358]
I understand that `<sys/atomics.h>` is missing from the unified headers not as an oversight, but rather a conscious decision, and we are all expected to rewrite our code and use `<stdatomic.h>` instead. It's a pity this change is not mentioned in the documentation. I believe that this shift begs for a migration guide as well.

* NDK Version: *15.0.3869609-beta1* and earlier.

**Comment by enh** [comment]
you don't _have_ to rewrite your code to use <stdatomic.h> --- you can always just have your own copy of the old cruft if you're happy with it. but, yes, we should probably explicitly mention this change in the documentation.

**Comment by alexcohn** [comment]
This header was documented some while ago, then removed at NDK r10, then restored... And it is still there when I disable unified headers.

Personally, I think that the change is for good, I don't like the way it was introduced.

**Comment by DanAlbert** [comment]
I'll try to make a broad list of things that we know changed between the old headers and the new ones (I'd done this at some point, but neglected to document them) and get that added to the docs.

**Comment by DanAlbert** [comment]
https://android-review.googlesource.com/c/409326/
