### ISSUE TITLE
pthread_mutex_timedlock __INTRODUCED_IN(21) is wrong [unified headers]

### ISSUE THREAD

**Issue by alexcohn** [android-ndk/ndk#359]
#### Description
**sysroot/usr/include/pthread.h** wrongly attributes `pthread_mutex_timedlock()` as available for API 21 and higher; this function is defined even in
**platforms/android-9/arch-arm/usr/include/pthread.h**

* NDK Version: 15.0.3869609-beta1 and earlier.
* NDK API level: 14

**Comment by enh** [comment]
i think grep might have mislead you here?

development/ndk/platforms/android-9/include/pthread.h:172:

#if 0 /* MISSING FROM BIONIC */
int pthread_mutex_timedlock(pthread_mutex_t *mutex, struct timespec*  ts);
#endif /* MISSING */

looking back through the bionic source, the oldest release with an implementation is L, which was 21.

**Comment by alexcohn** [comment]
_Mea culpa._ It was another compilation flag with boost headers that went wrong when I switched to r15 with unified headers and Clang.

**Comment by enh** [comment]
danalbert: when you've cherrypick the various pending header fixes, let me know and i'll try building boost with a standalone NDK to make sure we've found everything.

**Comment by alexcohn** [comment]
Another related bug, surfaced in WebRTC compilation on r15 (see e.g. [event_timer_posix.c:99](https://chromium.googlesource.com/external/webrtc/+/f9784f23d7b95db426626c340690f7592a1a7f46/webrtc/system_wrappers/source/event_timer_posix.cc#99)).

platform headers for **android-9** till **android-19** define `HAVE_PTHREAD_COND_TIMEDWAIT_MONOTONIC`. It is not defined in unified headers, but simply adding this with condition `__ANDROID_API__ < 21` does not help; we also need to declare  `pthread_cond_timedwait_monotonic_np()` and her kin.

As a workaround, I have added the file **pthread.h** high on our includes search path:
```
#include_next <pthread.h>

// work around a bug with Unified Headers in NDK r.15 (see 

#if defined __ANDROID_API__ && (__ANDROID_API__ < 21)

/* BIONIC: same as pthread_cond_timedwait, except the 'abstime' given refers
 *         to the CLOCK_MONOTONIC clock instead, to avoid any problems when
 *         the wall-clock time is changed brutally
 */
int pthread_cond_timedwait_monotonic_np(pthread_cond_t         *cond,
                                        pthread_mutex_t        *mutex,
                                        const struct timespec  *abstime);

/* BIONIC: DEPRECATED. same as pthread_cond_timedwait_monotonic_np()
 * unfortunately pthread_cond_timedwait_monotonic has shipped already
 */
int pthread_cond_timedwait_monotonic(pthread_cond_t         *cond,
                                     pthread_mutex_t        *mutex,
                                     const struct timespec  *abstime);

#define HAVE_PTHREAD_COND_TIMEDWAIT_MONOTONIC 1

/* BIONIC: same as pthread_cond_timedwait, except the 'reltime' given refers
 *         is relative to the current time.
 */
int pthread_cond_timedwait_relative_np(pthread_cond_t         *cond,
                                     pthread_mutex_t        *mutex,
                                     const struct timespec  *reltime);

#define HAVE_PTHREAD_COND_TIMEDWAIT_RELATIVE 1



int pthread_cond_timeout_np(pthread_cond_t *cond,
                            pthread_mutex_t * mutex,
                            unsigned msecs);

/* same as pthread_mutex_lock(), but will wait up to 'msecs' milli-seconds
 * before returning. same return values than pthread_mutex_trylock though, i.e.
 * returns EBUSY if the lock could not be acquired after the timeout
 * expired.
 */
int pthread_mutex_lock_timeout_np(pthread_mutex_t *mutex, unsigned msecs);

#endif
```

**Comment by rcdailey** [comment]
@alexcohn: What was your solution to this problem? Boost thread won't compile because of this (we're on API 15). Is there some preprocessor definition that boost needs?

**Comment by alexcohn** [comment]
@rcdailey As I show in the linked issue, I added the missing parts of `<pthread.h>` to my private location. But I didn't try **boost** with this workaround.
