### ISSUE TITLE
NDK_ANALYZE=1 is broken

### ISSUE THREAD

**Issue by andreya108** [android-ndk/ndk#362]
#### Description

NDK_ANALYZE feature is completely broken in ndk r14

It uses clang static code analyzer tool and scan-build utility.
But all invocation scripts are out of date.

1) android-ndk-r14b/build/ndk-build does not even try to setup C++ analyzer, it always assume C and gcc as toolchain
2) clang toolchain's setup.mk overrides TARGET_CXX, so there are no chances for scan-build to get any results
...

#### Environment Details

* NDK Version: r14b
* Build sytem: ndk-build
* Host OS: Ubuntu 16.04
* Compiler: clang
* ABI: arm64-v8a

**Comment by andreya108** [comment]
I've made patches fixing NDK_ANALYZE:

Every clang toolchain's setup.mk should be patched like this:
```
--- a/build/core/toolchains/aarch64-linux-android-clang/setup.mk	2017-04-11 17:56:17.813103033 +0300
+++ b/build/core/toolchains/aarch64-linux-android-clang/setup.mk	2017-04-11 17:58:09.925105404 +0300
@@ -36,7 +36,11 @@
 TOOLCHAIN_PREFIX := $(TOOLCHAIN_ROOT)/bin/$(TOOLCHAIN_NAME)-

 TARGET_CC := $(LLVM_TOOLCHAIN_PREFIX)clang$(HOST_EXEEXT)
+ifeq ($(CXX),)
 TARGET_CXX := $(LLVM_TOOLCHAIN_PREFIX)clang++$(HOST_EXEEXT)
+else
+TARGET_CXX := $(CXX)
+endif

 LLVM_TRIPLE := aarch64-none-linux-android

```
And ndk-build script should be patched like this:
```
--- a/build/ndk-build	2017-04-11 18:06:34.000000000 +0300
+++ b/build/ndk-build	2017-04-11 18:06:24.005115849 +0300
@@ -264,10 +264,11 @@
         TOOLCHAIN_PREFIX=`get_build_var_for_abi TOOLCHAIN_PREFIX $ABI`
         LLVM_PATH=$ANDROID_NDK_ROOT/toolchains/llvm/prebuilt/$HOST_TAG
         perl $LLVM_PATH/tools/scan-build/bin/scan-build \
-            --use-analyzer $LLVM_PATH/bin/${ABI}/analyzer \
-            --use-cc ${TOOLCHAIN_PREFIX}gcc \
-            --use-c++ ${TOOLCHAIN_PREFIX}g++ \
+            --use-analyzer $LLVM_PATH/bin/${ABI}/analyzer++ \
+            --use-cc $LLVM_PATH/bin/clang \
+            --use-c++ $LLVM_PATH/bin/clang++ \
             --status-bugs \
+			 -v -o clang-analyzer-report/$ABI \
             $GNUMAKE -f $PROGDIR/core/build-local.mk "$@" APP_ABI=$ABI
     done
 else
```
Also report dir is changed here from /tmp to <CURRENT_BUILD_DIR>/clang-analyzer-report and splitted by ABI.

**Comment by DanAlbert** [comment]
Thanks for the report (and thanks even more for the patches!). I'm still catching up on the past couple weeks, but I'll take a look at this some time before r15 goes to stable.

**Comment by andreya108** [comment]
I've noticed than NDK_CCACHE feature works fine (and saves a lot of my time). It seems that NDK_ANALYZE implementation can be reworked to be very similar and less complicated... Just an idea...

**Comment by DanAlbert** [comment]
Finally had a chance to look at this. Did some cleanup while I was at it:

https://android-review.googlesource.com/405992 Remove Clang toolchain path from setup.mk.
https://android-review.googlesource.com/405993 Make NDK_ANALYZE work with both GCC and Clang.
https://android-review.googlesource.com/405994 Add NDK_ANALYZER_OUT, expand the test.

Now our test will actually catch issues here, and the analyzer will work with both Clang and GCC.

I don't think I'll be cherry-picking these into r15. We're very late in the release cycle and this isn't a regression. This actually works as well as it ever has, it's just that it never got updated to allow compilation using Clang.

**Comment by DanAlbert** [comment]
Merged into r16.

**Comment by wustwg** [comment]
do you  have any android  cmake projects using  NDK_ANALYZE=1 demos? Now our company has migarate our project from ndk-build to cmake ,but  I can't find any samples or docs about how to use analyzer in cmake , can you help me ? thanks!!!!

**Comment by DanAlbert** [comment]
Responded on https://github.com/android-ndk/ndk/issues/1072
