### ISSUE TITLE
error with FindBoost.cmake

### ISSUE THREAD

**Issue by steven5401** [android-ndk/ndk#369]
my linux cmake version is 3.2 and cmake in AS is 3.6
with `find_package(Boost 1.55 REQUIRED COMPONENTS system thread filesystem)` command
cmake3.2(/usr/share/cmake-3.2/Modules/FindBoost.cmake) run successfully
cmake3.6(~/Android/Sdk/cmake/3.6.3155560/share/Modules/FindBoost.cmake) run failed

Can you tell me the reason? How to fix the problem?

**Comment by DanAlbert** [comment]
`find_package` finds system libraries for you. Boost is not included in the NDK, so there's nothing to find.
