### ISSUE TITLE
sensor.h having "bool" type as C interface

### ISSUE THREAD

**Issue by ggfan** [android-ndk/ndk#370]
android/sensor.h defines a C interface, but it has a "bool" in it
   bool ASensor_isWakeUpSensor(ASensor const* sensor);

  ASensor const* ASensorManager_getDefaultSensorEx(ASensorManager* manager, int type,
        bool wakeUp);

causing error if not defining "bool" somewhere in the C application.

**Comment by enh** [comment]
i was wondering why this hadn't been noticed before. turns out L44 of the old hacked-about headers was:

#include <stdbool.h>

but this never made it back to the platform headers :-(

**Comment by DanAlbert** [comment]
https://android-review.googlesource.com/379777 up for review

**Comment by DanAlbert** [comment]
Merged into r15.
