### ISSUE TITLE
Building Boost 1.58

### ISSUE THREAD

**Issue by Asubayo** [android-ndk/ndk#371]
#### Description

Hello, I am on windows 10 and I try to build boost library (version 1.58) for android NDK r14b with clang.
But I ran into errors in signal.h : 

![image](https://cloud.githubusercontent.com/assets/5774471/25345306/bbd0d5c2-28e2-11e7-9bc6-73e491250e3f.png)

#### Environment Details

* NDK Version: r14b
* Build sytem:  custom
* Host OS: Windows
* Compiler: Clang 
* NDK API level: 24

#### To produce it : 
* I downloaded/extracted boost 1.58 and android NDK at the same folder level.
* I created a folder named make inside boost.
* I created to script inside the make folder : "build_android.bat" and "build_config.bat"
* At the boost root, I launched the command : `bootstrap.bat --with-toolset=clang`
* And I launched from the console my .bat script `build_android.bat`

#### Content of `build_android.bat`: 

```batch
@echo on

set androidNDKRoot=%~dp0..\..\android-ndk-r14b
set "androidNDKRoot=%androidNDKRoot:\=/%"

set JAM=%~dp0..\tools\build\src\build\user-config.jam

echo import os ; > %JAM%
echo androidNDKRoot = %androidNDKRoot% ; # put the relevant path >> %JAM% 
echo using clang : android : >> %JAM%
echo 	$(androidNDKRoot)/toolchains/llvm/prebuilt/windows-x86_64/bin/clang++  : >> %JAM%
echo	^<compileflags^>--sysroot=$(androidNDKRoot)/platforms/android-24/arch-arm >> %JAM%
echo 		 ^<compileflags^>-I$(androidNDKRoot)/sources/cxx-stl/llvm-libc++/include >> %JAM%
echo 		 ^<compileflags^>-I$(androidNDKRoot)/sources/cxx-stl/llvm-libc++abi/include >> %JAM%
echo 		 ^<compileflags^>-I$(androidNDKRoot)/sources/android/support/include >> %JAM%
echo	     ^<compileflags^>-D_GLIBCXX__PTHREADS >> %JAM%
echo	     ^<compileflags^>-D__arm__ >> %JAM%
echo	     ^<compileflags^>-D_REENTRANT >> %JAM%
echo 		 ^<compileflags^>-D__ANDROID__ >> %JAM%
echo 		 ^<compileflags^>-DANDROID >> %JAM%
echo	         ; >> %JAM%

call %~dp0build_config.bat

if "%HAS_EXCEPTION%"=="1" (
	set EXCEPTION_DEFINE=define="_HAS_EXCEPTIONS=1"
	set EXCEPTION=exceptions
	set LIBRARY_PACKAGE=%LIBRARIES_WITH_EXCEPTIONS%
) else (
	set EXCEPTION_DEFINE=define="_HAS_EXCEPTIONS=0"
	set EXCEPTION=noexceptions
	set LIBRARY_PACKAGE=%LIBRARIES_WITHOUT_EXCEPTIONS%
)

set STAGE=stage\lib\android\arm\%EXCEPTION%

SET cxxflags="-std=c++11 --stdlib=libc++ -Os -O2 -fno-strict-aliasing -g -Wno-unused-local-typedefs"

set  %EXCEPTION_DEFINE% architecture=arm target-os=linux threadapi=pthread threading=multi link=static runtime-link=static %LIBRARY_PACKAGE%

pushd %~dp0..
b2 -a -j6 --stagedir=%STAGE% variant=debug define="_DEBUG" toolset=clang-android cxxflags=%CXXFLAGS% %OPTIONS%
b2 -a -j6 --stagedir=%STAGE% variant=release define="NDEBUG" toolset=clang-android cxxflags=%CXXFLAGS% %OPTIONS%

move %STAGE%\lib\* %STAGE%
popd
```

#### Content of `build_config.bat`:
```batch 
set LIBRARIES=--with-atomic --with-chrono --with-date_time --with-exception --with-filesystem --with-system --with-test --with-timer --with-regex --with-signals --with-program_options --with-thread
set LIBRARIES_WITH_EXCEPTIONS=%LIBRARIES%
set LIBRARIES_WITHOUT_EXCEPTIONS=%LIBRARIES%
```

**Comment by enh** [comment]
the struct sigaction definition around L87 of signal.h is guarded by __LP64__, but the #define of sa_sigaction is arm-only, so something doesn't seem quite right here. i'm guessing you're actually building for arm64 but manually setting various arm-specific flags (as shown in your build_android.bat file)?

**Comment by Asubayo** [comment]
Thanks for your answer. Actually I would like to make a building for arm by using clang instead of gcc. I had a previous "build_android.bat" which used gcc (it works well to build boost): 

@echo on

set androidNDKRoot=%~dp0..\..\android-ndk-r14b
REM Changing backslash to slashes
set "androidNDKRoot=%androidNDKRoot:\=/%"

set JAM=%~dp0..\tools\build\src\build\user-config.jam

echo import os ; > %JAM%
echo androidNDKRoot = %androidNDKRoot% ; # put the relevant path >> %JAM% 
echo using gcc : android : >> %JAM%
echo 	$(androidNDKRoot)/toolchains/arm-linux-androideabi-4.9/prebuilt/windows-x86_64/bin/arm-linux-androideabi-g++  : >> %JAM%
echo	^<compileflags^>--sysroot=$(androidNDKRoot)/platforms/android-21/arch-arm >> %JAM%
echo	     ^<compileflags^>-I$(androidNDKRoot)/sources/cxx-stl/gnu-libstdc++/4.9/include >> %JAM%
echo	     ^<compileflags^>-I$(androidNDKRoot)/sources/cxx-stl/gnu-libstdc++/4.9/libs/armeabi/include >> %JAM%
echo	     ^<compileflags^>-D__GLIBC__ >> %JAM%
echo	     ^<compileflags^>-D_GLIBCXX__PTHREADS >> %JAM%
echo	     ^<compileflags^>-D__arm__ >> %JAM%
echo	     ^<compileflags^>-D_REENTRANT >> %JAM%
echo	     ^<archiver^>$(androidNDKRoot)/toolchains/arm-linux-androideabi-4.9/prebuilt/windows-x86_64/bin/arm-linux-androideabi-ar >> %JAM%
echo	     ^<ranlib^>$(androidNDKRoot)/toolchains/arm-linux-androideabi-4.9/prebuilt/windows-x86_64/bin/arm-linux-androideabi-ranlib >> %JAM%
echo	         ; >> %JAM%

call %~dp0build_config.bat

if "%HAS_EXCEPTION%"=="1" (
	set EXCEPTION_DEFINE=define="_HAS_EXCEPTIONS=1"
	set EXCEPTION=exceptions
	set LIBRARY_PACKAGE=%LIBRARIES_WITH_EXCEPTIONS%
) else (
	set EXCEPTION_DEFINE=define="_HAS_EXCEPTIONS=0"
	set EXCEPTION=noexceptions
	set LIBRARY_PACKAGE=%LIBRARIES_WITHOUT_EXCEPTIONS%
)

set STAGE=stage\lib\android\arm\%EXCEPTION%

SET cxxflags="-std=c++11 -lstdc++ -mthumb -Os -O2 -fno-strict-aliasing -g -Wno-unused-local-typedefs "

set OPTIONS=define="_LITTLE_ENDIAN" define="BOOST_TEST_NO_MAIN" %EXCEPTION_DEFINE% architecture=arm target-os=linux threadapi=pthread threading=multi link=static runtime-link=static %LIBRARY_PACKAGE%

pushd %~dp0..
b2 -a -j6 --stagedir=%STAGE% variant=debug define="_DEBUG" toolset=gcc-android cxxflags=%CXXFLAGS% %OPTIONS%
b2 -a -j6 --stagedir=%STAGE% variant=release define="NDEBUG" toolset=gcc-android cxxflags=%CXXFLAGS% %OPTIONS%

move %STAGE%\lib\* %STAGE%
popd


But I have some troubles to change this version of my script with clang.

**Comment by DanAlbert** [comment]
I successfully built 1.64 by doing the following:

```bash
$ ./bootstrap.sh --with-toolset=clang
$ build/tools/make_standalone_toolchain.py --arch arm --api 23 --unified-headers \
    --install-dir=toolchain
$ PATH=`realpath toolchain/bin`:$PATH ./b2 -j48 -q \
    toolset=clang \
    link=static \
    target-os=android \
    --with-atomic \
    --with-chrono \
    --with-date_time \
    --with-exception \
    --with-filesystem \
    --with-system \
    --with-test \
    --with-timer \
    --with-regex \
    --with-signals \
    --with-program_options \
    --with-thread
```

There are definitely other boost components that don't build (there's an unsupported.cpp that is used by b2 to signal a failure, but I can't figure out why it's used), but the components indicated by your script work at least.

**Comment by Asubayo** [comment]
Okay, so the problem is relative to my usage ... 
I tried to do the same on windows (just a build of atomic lib): 
From **boost_1_64_0/** : 

- `bootstrap.bat --with-toolset=clang`

From **androidNDK/** : 

- `python build/tools/make_standalone_toolchain.py --arch arm --api 21 --stl libc++ --unified-headers --install-dir=toolchain `

- `set PATH=%PATH%;E:\androidNDK\toolchain\bin`

- `b2.exe -j48 -q toolset=clang link=static target-os=android -lstdc++ --with-atomic `

But I still fail to make it running : 

> ...found 125 targets...
...updating 4 targets...
clang-linux.compile.c++.without-pth bin.v2\libs\atomic\build\clang-linux-3.8.275480\release\link-static\target-os-android\threading-multi\lockpool.o
'E:\boost_1_64_0\clang38++.exe' is not recognized as an internal or external command.
  "clang++" -c -x c++ -O3 -Wno-inline -Wall  -DBOOST_ALL_NO_LIB=1 -DBOOST_ATOMIC_SOURCE -DBOOST_ATOMIC_STATIC_LINK=1 -DNDEBUG -I"." -o "bin.v2\libs\atomic\build\clang-linux-3.8.275480\release\link-static\target-os-android\threading-multi\lockpool.o" "libs\atomic\src\lockpool.cpp"
...failed clang-linux.compile.c++.without-pth bin.v2\libs\atomic\build\clang-linux-3.8.275480\release\link-static\target-os-android\threading-multi\lockpool.o...
...failed updating 1 target...

Do I have to put the generated toolchain dir to a specific location ?

**Comment by DanAlbert** [comment]
> 'E:\boost_1_64_0\clang38++.exe' is not recognized as an internal or external command.

I'm not sure where it got that path from, but that doesn't match your standalone toolchain.

**Comment by Asubayo** [comment]
Okay, thanks, indeed I don't know why but I had some errors on some paths.
I succeed to build all boost libs that I need except thread. I got : 

> ...patience...
...found 1090 targets...
...updating 4 targets...
clang-linux.compile.c++.without-pth bin.v2\libs\thread\build\clang-linux-3.8.275480\release\link-static\target-os-android\threading-multi\win32\thread.o
libs\thread\src\win32\thread.cpp:27:10: fatal error: 'process.h' file not found
#include <process.h>
         ^
1 error generated.
  "clang++" -c -x c++ -Wextra -Wno-long-long -Wno-unused-parameter -Wno-variadic-macros -Wunused-function -O3 -Wno-inline -Wall -Wextra -Wno-long-long -Wno-unused-parameter -Wno-variadic-macros -Wunused-function -DBOOST_ALL_NO_LIB=1 -DBOOST_CHRONO_STATIC_LINK=1 -DBOOST_SYSTEM_NO_DEPRECATED -DBOOST_SYSTEM_STATIC_LINK=1 -DBOOST_THREAD_BUILD_LIB=1 -DBOOST_THREAD_USES_CHRONO -DNDEBUG -I"." -o "bin.v2\libs\thread\build\clang-linux-3.8.275480\release\link-static\target-os-android\threading-multi\win32\thread.o" "libs\thread\src\win32\thread.cpp"
...failed clang-linux.compile.c++.without-pth bin.v2\libs\thread\build\clang-linux-3.8.275480\release\link-static\target-os-android\threading-multi\win32\thread.o...
...failed updating 1 target...

You didn't get any errors about boost lib thread ?

**Comment by enh** [comment]
<process.h> is a Windows header file. i think you've misconfigured boost and it thinks it's building for Windows...

**Comment by DanAlbert** [comment]
Run `b2.exe -h`. It had a list of configuration options. One of them was something like "threading type" (I don't remember the exact name). Set that to "pthreads".

**Comment by Asubayo** [comment]
Yes, my mistake, I forgot to add the option : threadapi=pthread

**Comment by trashoverride** [comment]
I don't know if this topic is already open , but i can compile the boost, but i am taking a problem in the compilation : 

```
/home/asilva/boost-android/arm/lib/libboost_system.a(error_code.o):libs/system/src/error_code.cpp:function boost::system::(anonymous namespace)::generic_error_category::message(int) const: error: undefined reference to 'std::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(char const*, std::allocator<char> const&)'
/home/asilva/boost-android/arm/lib/libboost_system.a(error_code.o):libs/system/src/error_code.cpp:function boost::system::(anonymous namespace)::generic_error_category::message(int) const: error: undefined reference to 'std::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(char const*, std::allocator<char> const&)'
/home/asilva/boost-android/arm/lib/libboost_system.a(error_code.o):libs/system/src/error_code.cpp:function boost::system::(anonymous namespace)::generic_error_category::message(int) const: error: undefined reference to 'std::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(std::string const&)'
/home/asilva/boost-android/arm/lib/libboost_system.a(error_code.o):libs/system/src/error_code.cpp:function boost::system::(anonymous namespace)::generic_error_category::message(int) const: error: undefined reference to 'std::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()'

```

I am comping with android NDK 16 and the Android Studio follow the line:

/home/asilva/Android/Sdk/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++
--target=armv5te-none-linux-androideabi --gcc-toolchain=/home/asilva/Android/Sdk/ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64 --sysroot=/home/asilva/Android/Sdk/ndk-bundle/sysroot -fPIC -isystem /home/asilva/Android/Sdk/ndk-bundle/sysroot/usr/include/arm-linux-androideabi -D__ANDROID_API__=15 -g -DANDROID -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -march=armv5te -mtune=xscale -msoft-float -fno-integrated-as -mthumb -Wa,--noexecstack -Wformat -Werror=format-security -std=c++11 -O0 -fno-limit-debug-info  -Wl,--exclude-libs,libgcc.a -Wl,--exclude-libs,libatomic.a --sysroot /home/asilva/Android/Sdk/ndk-bundle/platforms/android-15/arch-arm -Wl,--build-id -Wl,--warn-shared-textrel -Wl,--fatal-warnings -Wl,--exclude-libs,libunwind.a -L/home/asilva/Android/Sdk/ndk-bundle/sources/cxx-stl/llvm-libc++/libs/armeabi -Wl,--no-undefined -Wl,-z,noexecstack -Qunused-arguments -Wl,-z,relro -Wl,-z,now -shared -Wl,-soname,libnative-lib.so -o ../../../../build/intermediates/cmake/debug/obj/armeabi/libnative-lib.so CMakeFiles/native-lib.dir/src/main/cpp/native-lib.cpp.o CMakeFiles/native-lib.dir/src/main/cpp/Rest/RestConnector.cpp.o CMakeFiles/native-lib.dir/src/main/cpp/Rest/Applications.cpp.o CMakeFiles/native-lib.dir/src/main/cpp/Rest/CaCert.cpp.o CMakeFiles/native-lib.dir/src/main/cpp/Rest/EmvTags.cpp.o CMakeFiles/native-lib.dir/src/main/cpp/Rest/HASH.cpp.o CMakeFiles/native-lib.dir/src/main/cpp/Rest/JasonManager.cpp.o CMakeFiles/native-lib.dir/src/main/cpp/Rest/JavaSettings.cpp.o CMakeFiles/native-lib.dir/src/main/cpp/Rest/MakeRequest.cpp.o CMakeFiles/native-lib.dir/src/main/cpp/Rest/Settings.cpp.o CMakeFiles/native-lib.dir/src/main/cpp/Rest/Terminal.cpp.o CMakeFiles/native-lib.dir/src/main/cpp/Rest/TmpKey.cpp.o CMakeFiles/native-lib.dir/src/main/cpp/Rest/Transaction.cpp.o  /home/asilva/Android/Sdk/ndk-bundle/platforms/android-15/arch-arm/usr/lib/liblog.so /home/asilva/boost-android/arm/lib/libboost_system.a /home/asilva/boost-android/arm/lib/libboost_filesystem.a /home/asilva/boost-android/arm/lib/libboost_exception.a /home/asilva/android-openssl/jni/openssl/arch-armeabi/lib/libssl.a /home/asilva/android-openssl/jni/openssl/arch-armeabi/lib/libcrypto.a -latomic -lm "/home/asilva/Android/Sdk/ndk-bundle/sources/cxx-stl/llvm-libc++/libs/armeabi/libc++.a"


some tip ?

**Comment by DanAlbert** [comment]
You built boost with gnustl or stlport but are using libc++ in your app. You have to use the same STL throughout your app.

**Comment by trashoverride** [comment]
Hello Dan Albert,
Sorry to the long time to  answer you,  i was in holydays. I only took out the library because she  wasn't use because the previous developer added without to be needed. I will try to fix and i will post a feedback.
Kind regards,
Antonio

**Comment by Humorly** [comment]
@trashoverride hello. goodafternoon, same question with you, how can i solve the problems now ?

**Comment by Humorly** [comment]
../../../../libs/jni/x86/libboost_system.a(error_code.o):libs/system/src/error_code.cpp:function boost::system::(anonymous namespace)::generic_error_category::message(int) const: error: undefined reference to 'std::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(char const*, std::allocator<char> const&)'
../../../../libs/jni/x86/libboost_system.a(error_code.o):libs/system/src/error_code.cpp:function boost::system::(anonymous namespace)::generic_error_category::message(int) const: error: undefined reference to 'std::basic_string<char, std::char_traits<char>, std::allocator<char> >::~basic_string()'
../../../../libs/jni/x86/libboost_system.a(error_code.o):libs/system/src/error_code.cpp:function boost::system::(anonymous namespace)::generic_error_category::message(int) const: error: undefined reference to 'std::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(char const*, std::allocator<char> const&)'
../../../../libs/jni/x86/libboost_system.a(error_code.o):libs/system/src/error_code.cpp:function boost::system::(anonymous namespace)::generic_error_category::message(int) const: error: undefined reference to 'std::basic_string<char, std::char_traits<char>, std::allocator<char> >::basic_string(std::string const&)'
clang++.exe: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.


I don't know how to make my android studio compile .so file when formulating c++ type

**Comment by trashoverride** [comment]
Hi man, how are you :) so its a long time ago, but if i am not wrong i remember that :  The problem is the GLIB C used for your system was different. I found this information in other site.

**Comment by Humorly** [comment]
@trashoverride okay,I will try to compile boost lib on linux again with clang, thank you very much!

**Comment by trashoverride** [comment]
This of @DanAlbert  helped me 

"You built boost with gnustl or stlport but are using libc++ in your app. You have to use the same STL throughout your app."

Could you describe all the process ? that you are trying to make ?

**Comment by enh** [comment]
see [this gist](https://gist.github.com/enh/b2dc8e2cbbce7fffffde2135271b10fd) for how to build boost on Linux or Mac. (on Windows you'll have to basically run the same commands by hand.) it's set up for 1.68.0 (the current version), but you can just change the first line to build other versions.

**Comment by enh** [comment]
> @enh I think the problem is after the guy compile. I think he can compile but after he is trying to use the library and can not.

ah, i see. NDK r18 makes fixing that problem easier, because gnustl and stlport have been removed and only libc++ remains :-)

**Comment by Humorly** [comment]
@enh yes, i have used ndk15 to compile boost_1_64_0,but now the android studio version was 3.2.1 & the ndk 16b. so i get this error

**Comment by Humorly** [comment]
https://github.com/moritz-wundke/Boost-for-Android ; use this , very simple to build boost for android

**Comment by DanAlbert** [comment]
Those errors look completely unrelated and look like you're just not linking your dependencies correctly.

**Comment by ils-aashishj** [comment]
@DanAlbert  can you please tell me more about this what linking problem is there?
