### ISSUE TITLE
Where is api android-25 in folder 'platforms' in ndk r14b or r15b?

### ISSUE THREAD

**Issue by skanti** [android-ndk/ndk#372]
In the ndk folder in subfolder 'platforms' the api android-25 does not exist. Does it have a particular reason? In ndk r15b (beta) there is api android-24 and android-26 but not version 25.

**Comment by DanAlbert** [comment]
There were no new native APIs in android-25.

**Comment by alexcohn** [comment]
Well, we don't need `platforms/android-25` folder; but **setup-app-platform.mk** must accept APP_PLATFORM=android-25 (or at least `target=android-25` in **project.properties**), and step down to **`android-24`**, shouldn't it?

On **r14** this was irrelevant, since **`android-24`** was NDK_MAX_PLATFORM_LEVEL.

**Comment by DanAlbert** [comment]
Why not just set `APP_PLATFORM := android-24` instead? `APP_PLATFORM := android-25` just cuts one more release unnecessarily off the bottom of your `minSdkVersion`.

... or is gradle sharing some target API variable between Java and the NDK, and using android-25 Java APIs forces this? It should really just be using `minSdkVersion` for the NDK target API, but idk if that's the case.

**Comment by alexcohn** [comment]
I don't know if the TS had this specific issue, but yes, if someone has `minSdkVersion=25` in **build.gradle**,  which is fully legitimate, then **ndk-build** will fail for NDK r15.

**Comment by DanAlbert** [comment]
Yeah, okay, that makes sense. Reopening.

**Comment by DanAlbert** [comment]
https://android-review.googlesource.com/c/455206

**Comment by DanAlbert** [comment]
Merged into r16.
