### ISSUE TITLE
elf.h missing ELF64_ST_INFO defenition which cause error when building ICU (even from android sources repo)

### ISSUE THREAD

**Issue by ivankarpey** [android-ndk/ndk#377]
There was [question on stackoverflow](http://stackoverflow.com/q/38151227/1888017) regarding this, which wasn't answered. However issue is still actual at the current moment with latest available NDK (r15 rc1)

**Comment by DanAlbert** [comment]
Was removed in https://android-review.googlesource.com/c/81751, where we moved over to relying on the kernel's elf.h. @enh: is this a definition we should put back? From what I can tell searching the tree, most open source projects just define this themselves.

**Comment by enh** [comment]
not quite: that change removed ELF_ST_INFO (which glibc doesn't define). ELF32_ST_INFO and ELF64_ST_INFO had been removed years before by https://android-review.googlesource.com/#/c/33420/.

but, yeah, that was a mistake. https://android-review.googlesource.com/384598 adds them back with tests.

**Comment by DanAlbert** [comment]
+2. Thanks for the report. There should still be time to get this in to r15 beta 2.

**Comment by ivankarpey** [comment]
Thanks for such a quick reaction. That's awesome.

**Comment by DanAlbert** [comment]
Merged into r15.
