### ISSUE TITLE
Clang toolchains are still named *-clang3.6

### ISSUE THREAD

**Issue by azharudd** [android-ndk/ndk#38]
In build/core/toolchains , the clang toolchain dir names still end in '-clang3.6' . Either '3.6' should be removed from these names or it should be updated to '3.8' as that is the version of llvm in toolchains/ .

**Comment by DanAlbert** [comment]
Yeah, I need to finish this cleanup. 3.6 should be gone from all the user facing pieces though.

**Comment by DanAlbert** [comment]
https://android-review.googlesource.com/#/c/214082/
