### ISSUE TITLE
ANativeActivity_onCreate not found (with solution)

### ISSUE THREAD

**Issue by twaik** [android-ndk/ndk#381]
#### Description

I got an error "W/NativeActivity(18489): ANativeActivity_onCreate not found" in Android after building a large NativeActivity application. I tried to use LOCAL_WHOLE_STATIC_LIBRARIES, but it still didn't work. Command "nm -D -C -g libs/armeabi-v7a/libNativeActivity.so" told me ANativeActivity_onCreate had not been exported.

#### Solution
I think found a solution that can solve the problem in general. gcc can export functions with using version-script. NativeActivity application doesn't need any functions to be exported except ANativeActivity_onCreate, so I think using this wouldn't cause any problems. If I am right it can be committed to project tree. 
native_app_glue Android.mk
```
LOCAL_PATH:= $(call my-dir)

include $(CLEAR_VARS)

LOCAL_MODULE:= android_native_app_glue
LOCAL_SRC_FILES:= android_native_app_glue.c
LOCAL_EXPORT_C_INCLUDES := $(LOCAL_PATH)
LOCAL_EXPORT_LDFLAGS:= -Wl,--version-script=$(LOCAL_PATH)/exports.txt
LOCAL_EXPORT_LDLIBS := -llog

include $(BUILD_STATIC_LIBRARY)

```
native_app_glue exports.txt
```
{
	global:
		ANativeActivity_onCreate;
	local: *;         # hide everything else
};
```
Please, correct me if I am not right.

**Comment by alexcohn** [comment]
If you follow the official [sample](https://developer.android.com/ndk/samples/sample_na.html#mac), this won't happen: a call to `app_dummy()` will keep `ANativeActivity_onCreate` in your **libandroid_native_app_glue.so**

**Comment by twaik** [comment]
I've seen many posts at 4pda and stackoverflow about the problem. In all the cases ANativeActivity was not exported even if it was built. That solution not for problem when the ANativeActivity was stripped but for problem where it was build as a local function.

**Comment by alexcohn** [comment]
If your **xxx_CFLAGS** include `-fvisibility=hidden` (which is a good practice), it would be enough to add **JNIEXPORT** to its [definition in android_native_app_glue.c](https://android.googlesource.com/platform/development/+/gingerbread/ndk/sources/android/native_app_glue/android_native_app_glue.c#418)

This is defined in `<jni.h>`:

    #define JNIEXPORT  __attribute__ ((visibility ("default")))

**Comment by DanAlbert** [comment]
@alexcohn's solution LGTM, but I want to make sure there isn't something weird going on first.

@twaik: do you have `APP_CFLAGS := -fvisibility=hidden` set? I was able to repro this if I did that, but without that it was exported properly as long as I used `LOCAL_WHOLE_STATIC_LIBRARIES` (which the sample doesn't say to use, *sigh*).

I also noticed that `android_native_app_glue` doesn't export `-landroid` like it should. I'll get both of these things fixed in r15 and see if I can find some time to clean up the sample.

Thanks for reporting this (and thanks @alexcohn for doing the initial analysis!)

**Comment by DanAlbert** [comment]
https://android-review.googlesource.com/392595 Export libandroid from android_native_app_glue.        
https://android-review.googlesource.com/392596 Ensure that ANativeActivity_onCreate isn't hidden.

**Comment by twaik** [comment]
```
__attribute__((visibility("default")))
void ANativeActivity_onCreate(ANativeActivity* activity,
        void* savedState, size_t savedStateSize) {
    LOGV("Creating: %p\n", activity);
```
android_native_app_glue.c includes <jni.h>, which defines JNIEXPORT, isn't it?
```
JNIEXPORT void ANativeActivity_onCreate(ANativeActivity* activity,
        void* savedState, size_t savedStateSize) {
    LOGV("Creating: %p\n", activity);
```
And -fvisibility=hidden flag may be not useful in project which doesn't use native_app_glue, so
```
LOCAL_PATH:= $(call my-dir)

include $(CLEAR_VARS)

LOCAL_MODULE:= android_native_app_glue
LOCAL_SRC_FILES:= android_native_app_glue.c
LOCAL_EXPORT_CFLAGS := APP_CFLAGS := -fvisibility=hidden //THIS LINE
LOCAL_EXPORT_C_INCLUDES := $(LOCAL_PATH)
LOCAL_EXPORT_LDLIBS := -llog -landroid

include $(BUILD_STATIC_LIBRARY)
```

**Comment by DanAlbert** [comment]
@twaik: so is that a yes then? Did you have `APP_CFLAGS := -fvisibility=hidden`? Otherwise there may be another bug here (which those patches will conveniently hide, but not fix).

> android_native_app_glue.c includes <jni.h>, which defines JNIEXPORT, isn't it?

Good point. I'll fix that.

> And -fvisibility=hidden flag may be not useful in project which doesn't use native_app_glue, so

That's just a test. The point is to make sure we're tolerant of people putting that in `APP_CFLAGS`.

**Comment by twaik** [comment]
Tried to add it to project. What I did:
0. Added JNIEXPORT to void ANativeActivity_onCreate definition (in both lower cases).
1. Tried to add LOCAL_EXPORT_CFLAGS := -fvisibility=hidden to Android.mk of native_app_glue. It didn't work.
2. Tried to add APP_CFLAGS := -fvisibility=hidden to Application.mk and that didn't work too. 
In both cases ANativeActivity_onCreate was not exported.

Maybe variant with LOCAL_EXPORT_LDFLAGS:= -Wl,--version-script=$(LOCAL_PATH)/exports.txt is the one which works.

**Comment by DanAlbert** [comment]
What I'm asking is what you did to cause this in the first place. What did your test case that caused you to file the bug look like?

**Comment by twaik** [comment]
I don't sure know. I tried to build X KDrive server with NDK, it has hundreds of files with thousands function definitions. Result library exports list consists of function names called from the library, but it doesn't contain function names defined in the library. Maybe a project with the bug must contain a lot of function definitions. I can send the bug project via email.

**Comment by alexcohn** [comment]
@twaik you probably got `android_native_app_glue.o` stripped away, if you used neither `LOCAL_EXPORT_WHOLE_STATIC_LIBRARIES` nor **app_dummy()** trick.

@DanAlbert I don't think NDK supports `LOCAL_EXPORT_WHOLE_STATIC_LIBRARIES`; that's why the [app_dummy trick](https://github.com/android-ndk/ndk/issues/381#issuecomment-300104413) is easier.

**Comment by twaik** [comment]
My android_main starts from 
```
void android_main( struct android_app * app ) {
    app_dummy();
    app->onAppCmd     = android_handle_cmd;
    app->onInputEvent = android_handle_input;

	chdir(app->activity->internalDataPath);
```
And my project has this line in Android.mk
`LOCAL_WHOLE_STATIC_LIBRARIES := android_native_app_glue android-shmem libpixman`
But ANativeActivity_onCreate still is not exported

**Comment by DanAlbert** [comment]
Could you share your Android.mk/Application.mk?

> @DanAlbert I don't think NDK supports LOCAL_EXPORT_WHOLE_STATIC_LIBRARIES; that's why the app_dummy trick is easier.

Why is `LOCAL_EXPORT_WHOLE_STATIC_LIBRARIES` needed? I'm having trouble coming up with a test case that makes this needed (given that I've already added the `__attribute__((visibility("default")))`).

I was thinking maybe we didn't handle `LOCAL_WHOLE_STATIC_LIBRARIES` properly for static libraries, but it looks like we already do the smart thing and export those to consumers. To be fair, I would not have guessed that we had support for that :)

**Comment by alexcohn** [comment]
@DanAlbert that's good! So, the following **Android.mk** will include **android_native_app_glue.o** even without call **app_dummy()**?

```
LOCAL_PATH:= $(call my-dir)

include $(CLEAR_VARS)

LOCAL_MODULE:= android_native_app_glue
LOCAL_SRC_FILES:= android_native_app_glue.c
LOCAL_EXPORT_C_INCLUDES := $(LOCAL_PATH)
LOCAL_EXPORT_LDLIBS := -llog -landroid
LOCAL_WHOLE_STATIC_LIBRARIES := android_native_app_glue

include $(BUILD_STATIC_LIBRARY)

include $(CLEAR_VARS)
LOCAL_MODULE:= libNativeActivity
LOCAL_SRC_FILES:= ...
LOCAL_STATIC_LIBRARIES := android_native_app_glue

include $(BUILD_SHARED_LIBRARY)
```

**Comment by alexcohn** [comment]
@twaik maybe you can push the minimal representative sample here on GitHub?

**Comment by DanAlbert** [comment]
I'd tried a modified version of the test I uploaded:

```make
LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)
LOCAL_MODULE := libnativeactivity
LOCAL_SRC_FILES := android_main.cpp
LOCAL_WHOLE_STATIC_LIBRARIES := android_native_app_glue
include $(BUILD_STATIC_LIBRARY)

include $(CLEAR_VARS)
LOCAL_MODULE := oncreate_visible
LOCAL_SRC_FILES := oncreate.cpp
LOCAL_STATIC_LIBRARIES := libnativeactivity
include $(BUILD_EXECUTABLE)

$(call import-module,android/native_app_glue)
```

The `ANativeActivity_onCreate` symbol was still available in `oncreate_visible`.

**Comment by alexcohn** [comment]
@DanAlbert you don't need LOCAL_WHOLE_STATIC_LIBRARIES if call to app_dummy is there. Please check that it is enough to use either one.

**Comment by DanAlbert** [comment]
Ah, I see what you mean now. No, that doesn't work. I'm not sure why that's important though. What's the problem with using `LOCAL_WHOLE_STATIC_LIBRARIES`?

I suppose we will have the problem that this is a user facing change, given that our sample said to do it the other way. I fixed the sample earlier. I can still make this a little better and just avoid breaking the `app_dummy` use case too.

**Comment by alexcohn** [comment]
Sincerely, I don't see a single reason to keep `android_native_app_glue.c` out of **libandroid.so**. After all, if somebody is not happy with the default `ANativeActivity_onCreate()`, they [can](https://developer.android.com/ndk/reference/group___native_activity.html#ga02791d0d490839055169f39fdc905c5e) specify **`"android.app.func_name"`** string meta-data in the manifest to use a different function.

**Comment by twaik** [comment]
If somebody is not happy with default ANativeActivity_onCreate(), they can specify his own ANativeActivity_onCreate() and not include native_app_glue library. And like I said before NativeActivity Application shared library needs to be compiled with only ANativeActivity_onCreate() exported, any other functions are no matter. Just try to build project with version-script exporting from native_app_glue Android.mk. That solution will revoke the need to call app_dummy, because the onCreate function will be important for compiler. You even don't need to apply any other patches to solve "ANativeActivity_onCreate() not found" issue. Or that patch will only mask the real problem?

**Comment by alexcohn** [comment]
@twaik, unfortunately your version-script does not mark `ANativeActivity_onCreate()` as 'needed', and either LOCAL_WHOLE_STATIC_LIBRARIES or app_dummy is still necessary. Furthermore, it may cause harm: if for whatever reason the people need some other symbol to be exported, they will need to edit this `exports.txt` or find another way to override its policy. Simply adding `JNIEXPORT` or even `__attribute__((visibility("default")))` will not help.

I daresay there is some other problem with your project, and `JNIEXPORT` did not work as expected. If you run `ndk-build V=1` you will see all build commands echoed to console; I believe that you will find that `-fvisibility=hidden` is passed to the compiler while **libandroid_native_app_glue** is built.

**Comment by alexcohn** [comment]
I believe that I have found the ultimate fix for the core problem. The missing part is actually very simple and innocent.

Here is the suggested [**Android.mk**](https://android.googlesource.com/platform/development/+/gingerbread/ndk/sources/android/native_app_glue/Android.mk):

```
LOCAL_PATH:= $(call my-dir)

include $(CLEAR_VARS)

LOCAL_MODULE:= android_native_app_glue
LOCAL_SRC_FILES:= android_native_app_glue.c
LOCAL_EXPORT_C_INCLUDES := $(LOCAL_PATH)
LOCAL_EXPORT_LDFLAGS := -u ANativeActivity_onCreate
LOCAL_EXPORT_LDLIBS := -llog -landroid

include $(BUILD_STATIC_LIBRARY)
```

Adding **-u ANativeActivity_onCreate** will force the linker not to strip `android_native_app_glue.o` even if `LOCAL_WHOLE_STATIC_LIBRARIES` is not used for **libandroid_native_app_glue**.

*And attribute `ANativeActivity_onCreate` with `JNIEXPORT`* in the C file.

**Comment by twaik** [comment]
I tried -u flag. That doesn't solve the main problem: ANativeActivity_onCreate is not exported by linker

**Comment by twaik** [comment]
`Furthermore, it may cause harm: if for whatever reason the people need some other symbol to be exported, they will need to edit this exports.txt or find another way to override its policy. `
Can you give an example when the user? libandroid_support checks LIBCXX_FORCE_REBUILD to know if user wants to use prebuilt library or to rebuild it from scratch. native_app_glue can check somethng like  LIBGLUE_FORCE_EXPORT_SYMBOLS or DONT_EXPORT_ANYTHING_PLEASE_I_BEG_YOU_DONT.

**Comment by alexcohn** [comment]
@twaik thanks for testing; it was expected. `-u` performs no miracles. As I said before, something is broken in your project, which hides the symbol for **ANativeActivity_onCreate**. 

Maybe you want to switch to private chat so that I could help you resolve the problem?

**Comment by twaik** [comment]
@alexcohn thanks. I solved it with version-script. But there are many users with sama problem. 
Like I said before, Android Runtime doesn't need any symbols except ANativeActivity_onCreate. If user wants to export some symbols to Java he will not use native_app_glue.

**Comment by alexcohn** [comment]
Regarding prebuilt native_app_glue - it is so small it does not matter if it is recompiled every time. `libandroid_support` is different because it is used by/with `libc++_static` and nobody wants to waste time rebuilding STL.

**Comment by twaik** [comment]
I didn't want to propose prebuilt native_app_glue. I meant NDK should check LIBGLUE_FORCE_EXPORT_SYMBOLS to decide use version script or not. Like that:
```
LOCAL_PATH:= $(call my-dir)

include $(CLEAR_VARS)

LOCAL_MODULE:= android_native_app_glue
LOCAL_SRC_FILES:= android_native_app_glue.c
LOCAL_EXPORT_C_INCLUDES := $(LOCAL_PATH)
LOCAL_EXPORT_LDLIBS := -llog -landroid

//THERE
ifneq($(LIBGLUE_FORCE_EXPORT_SYMBOLS),false)
   LOCAL_EXPORT_LDFLAGS:= -Wl,--version-script=$(LOCAL_PATH)/exports.txt
endif

include $(BUILD_STATIC_LIBRARY)
//END_THERE
```

**Comment by twaik** [comment]
Can this help? 
`LOCAL_LDFLAGS += -Wl,--export-all-symbols`

**Comment by DanAlbert** [comment]
Cherry-picked into r15.

**Comment by alexcohn** [comment]
@DanAlbert Let me add few words of code review to your commits.

https://android.googlesource.com/platform/ndk/+/f45a8f5f3373efa88df9a848c38031de1dee4971

I believe that `LOCAL_EXPORT_LDFLAGS := -u ANativeActivity_onCreate` is much easier for integration than requiring `LOCAL_WHOLE_STATIC_LIBRARIES += android_native_app_glue`

https://android.googlesource.com/platform/ndk/+/f8d5dd14ceb5563d9768614e561028003c07ce24

I believe that `JNIEXPORT` is cleaner than explicit `__attribute__ ((visibility ("default")))`. For one, it's more readable; but more important, if the compiler changes its attribute processing, you only need to deal with it once, in **jni.h**.

Please excuse me if you find my intervention inappropriate, I didn't mean any harm.

**Comment by DanAlbert** [comment]
> I believe that LOCAL_EXPORT_LDFLAGS := -u ANativeActivity_onCreate is much easier for integration than requiring LOCAL_WHOLE_STATIC_LIBRARIES += android_native_app_glue

From the conversation above, I thought `-u` hadn't worked (I see now that it just didn't work for @twaik's use case). Semantically I prefer `LOCAL_WHOLE_STATIC_LIBRARIES` here because that's the normal way to do this sort of thing, but pragmatically both work and `-u` doesn't require people to mess with makefiles that have worked forever.

https://android-review.googlesource.com/407372

> I believe that JNIEXPORT is cleaner than explicit __attribute__ ((visibility ("default"))). For one, it's more readable; but more important, if the compiler changes its attribute processing, you only need to deal with it once, in jni.h.

https://android-review.googlesource.com/407153

(I'm usually not writing JNI specific stuff so I always forget about `JNIEXPORT`. Thanks.)

**Comment by DanAlbert** [comment]
Fixes to the fixes have been merged into r15.

**Comment by nileshshah89** [comment]
Still see the issue of "ANativeActivity_onCreate not found" after this fix. Hacked the code by commenting
`__attribute__((
    deprecated("Calls to app_dummy are no longer necessary. See "
               "https://github.com/android-ndk/ndk/issues/381.")))`

**Comment by alexcohn** [comment]
Well, definitely the comment above is wrong. **app_dummy()** is not necessary not because of `visibility("default")`, but thanks to `LOCAL_EXPORT_LDFLAGS := -u ANativeActivity_onCreate` in **Android.mk**.

**Comment by alexcohn** [comment]
@nileshshah89, if you build your project with **ndk-build**, please run **ndk-build V=1** to expose the actual build commands that were performed.

**Comment by ggfan** [comment]
set the flag when building the shared lib (not for app_glue static lib).  CMake build could use
```
set(CMAKE_SHARED_LINKER_FLAGS "${CMAKE_SHARED_LINKER_FLAGS} -u ANativeActivity_onCreate")
```
or
```
set_property(TARGET ${shared-lib-name}   APPEND_STRING PROPERTY LINK_FLAGS " -u ANativeActivity_onCreate")
```
