### ISSUE TITLE
NdkMediaCodec_dequeueInputBuffer always return -1

### ISSUE THREAD

**Issue by joole** [android-ndk/ndk#382]
#### Description

I want to use NDK to encode YUV raw data to H264,simplely only restore in file, compile the code in executable then push to android phone. I use the method steps which sample with java,but NdkMediaCodec_dequeueIntputBuffer always return -1, how to solve it ?

#### Environment Details

* NDK Version: r14b,r15
  the latest version, check there before filing.
* Build sytem: standalone toolchain
* Host OS: Ubuntu 16.04
* Compiler: CLANG
* ABI:
* STL: libc++_shared
* NDK API level: android-21
* Device API level: android-21

**Comment by DanAlbert** [comment]
Oops. I didn't mean to ignore this all this time. Sorry about that!

This isn't the right bug tracker for platform issues. You'll need to go to http://b.android.com for this.

**Comment by joole** [comment]
Thanks

**Comment by enh** [comment]
(if you link to the b.android.com bug here, though, we can try to help it find its way to the right engineers...)
