### ISSUE TITLE
NDK r14b on Windows miscompiles/misoptimizes code for AArch64 occasionally

### ISSUE THREAD

**Issue by mstorsjo** [android-ndk/ndk#383]
#### Description

NDK r14b can miscompile/misoptimize code when targeting AArch64, when running on Windows (reproduced in the x86_64 NDK). This is a regression from r13. The same issue is present in r15-beta1 as well. The same versions on Linux and OS X work fine.

#### Environment Details

Not all of these will be relevant to every bug, but please provide as much
information as you can.

* NDK Version: r14b, r15 beta1
* Build sytem: ndk-build
* Host OS: Windows
* Compiler: Clang

The root cause has been debugged to be a bug in LLVM: https://bugs.llvm.org/show_bug.cgi?id=32917
This has been fixed already in LLVM: https://reviews.llvm.org/D32850
https://github.com/llvm-project/llvm/commit/623692ec9cd5fd1dd90ef0fb66846430134111f9

Please backport this fix to the version of Clang used within the NDK.

**Comment by enh** [comment]
@pirama-arumuga-nainar

**Comment by DanAlbert** [comment]
@pirama-arumuga-nainar is ooo until I/O.

@stephenhines: how would you feel about cherry-picking this? The fix looks safe and fixes what looks like a pretty easy to trip bug. It might be tough for us to hit r15 at this point, but if I get the okay to cherry-pick this today I can still do that.

**Comment by DanAlbert** [comment]
Cherry-pick is up: https://android-review.googlesource.com/c/388996/

@mstorsjo: thanks a lot for finding and fixing this!

**Comment by DanAlbert** [comment]
Merged into r15.
