### ISSUE TITLE
atexit reference problem compiling static ffmpeg

### ISSUE THREAD

**Issue by arielmingrone** [android-ndk/ndk#385]
--------------------------------------------------------------------------------

#### Description

I have this problem with platform 24 in r14b compiling ffmpeg libs into static one

cmdline

$PREBUILT/bin/arm-linux-androideabi-ld -rpath-link=$PLATFORM/usr/lib -L$PLATFORM/usr/lib  -soname libffmpeg.so -static -nostdlib -noexecstack -Bsymbolic --whole-archive --no-undefined -o $PREFIX/libffmpeg.so libavcodec/libavcodec.a libavformat/libavformat.a libavutil/libavutil.a libswscale/libswscale.a libavfilter/libavfilter.a x264/libx264.a -lc -lm -lz --dynamic-linker=/system/bin/linker $PREBUILT/lib/gcc/arm-linux-androideabi/4.9.x/libgcc.a

external/jemalloc/src/jemalloc.c:707: error: undefined reference to 'atexit'
external/jemalloc/src/prof.c:1377: error: undefined reference to 'atexit'

I tried with platform 19 with no lucky, so much errors... 
Maybe you can help?

#### Environment Details

* NDK Version: Pkg.Revision = 14.1.3816874
* Build sytem: toolchain arm-linux-androideabi-4.9
* Host OS: Linuxmint 17
* Compiler: GCC
* ABI: arm
* NDK API level: 24

**Comment by DanAlbert** [comment]
Can you provide repro instructions?

**Comment by arielmingrone** [comment]
[build_scripts.zip](https://github.com/android-ndk/ndk/files/979166/build_scripts.zip)
I'm compiling with latest ffmpeg lib and latest x264 lib.

http://ffmpeg.org/releases/ffmpeg-3.3.tar.bz2
ftp://ftp.videolan.org/pub/x264/snapshots/last_x264.tar.bz2

 Attached my build scripts. If you need more tell me please. Thanks

**Comment by DanAlbert** [comment]
I don't think that build script does what you want it to do.

```
$PREBUILT/bin/arm-linux-androideabi-ld -rpath-link=$PLATFORM/usr/lib -L$PLATFORM/usr/lib\
    -soname libffmpeg.so -static -nostdlib -noexecstack -Bsymbolic --whole-archive \
    --no-undefined -o $PREFIX/libffmpeg.so libavcodec/libavcodec.a \
    libavformat/libavformat.a libavutil/libavutil.a libswscale/libswscale.a \
    libavfilter/libavfilter.a x264/libx264.a -lc -lm -lz \
    --dynamic-linker=/system/bin/linker \
    $PREBUILT/lib/gcc/arm-linux-androideabi/4.9.x/libgcc.a
```

`-static` letts the linker to link only static libraries, so you're linking libc.a and libm.a into your libffmpeg.so. You probably don't want to do that.

> I have this problem with platform 24 in r14b compiling ffmpeg libs into static one

Are you trying to make a static library, or a shared library? `ld` plays no part in making a static library.

**Comment by arielmingrone** [comment]
It's strange, I'm not an expert compiling but the same script works in the past. I need a lib that contains al the code of static libs into only one, to redistribute with my app. Suppose that it's not a problem with the NDK, can you help me with this command to compile and test if compilation works fine?

**Comment by DanAlbert** [comment]
> but the same script works in the past.

The static libraries in the NDK haven't been updated in a while (this is a bug, but it's a rare enough use case that we haven't had time to fix it yet). You're using android-24 headers with android-21 libraries, essentially.

> can you help me with this command to compile and test if compilation works fine?

Instead of `-static`, use `-Wl,--whole-archive $ALL_YOUR_STATIC_LIBS -Wl,--no-whole-archive`.

**Comment by arielmingrone** [comment]
I tried with platform 19 21 and 24, nkd 11c too, with your suggestion and with -static modifier, and never compiles...same error, if you think that can provide me any solution or suggestion it's welcome. Thanks

**Comment by DanAlbert** [comment]
Try what I said _without_ `-static`?

**Comment by arielmingrone** [comment]
Yes, and never works, do you test this case?

**Comment by DanAlbert** [comment]
I couldn't get your build scripts to work. After fixing the hard coded paths (and removing the `sudo` calls!) I still get:

```
$ ./build_android.sh 
ERROR: libx264 not found

If you think configure made a mistake, make sure you are using the latest
version from Git.  If the latest version fails, report the problem to the
ffmpeg-user@ffmpeg.org mailing list or IRC #ffmpeg on irc.freenode.net.
Include the log file "config.log" produced by configure as this will help
solve the problem.
Makefile:2: config.mak: No such file or directory
Makefile:67: /common.mak: No such file or directory
Makefile:114: /libavutil/Makefile: No such file or directory
Makefile:114: /library.mak: No such file or directory
Makefile:116: /doc/Makefile: No such file or directory
Makefile:206: /tests/Makefile: No such file or directory
make: *** No rule to make target `/tests/Makefile'.  Stop.
Makefile:2: config.mak: No such file or directory
Makefile:67: /common.mak: No such file or directory
Makefile:114: /libavutil/Makefile: No such file or directory
Makefile:114: /library.mak: No such file or directory
Makefile:116: /doc/Makefile: No such file or directory
Makefile:206: /tests/Makefile: No such file or directory
make: *** No rule to make target `/tests/Makefile'.  Stop.
```

**Comment by arielmingrone** [comment]
Ohhhh...it's very simple to work with this script, location of x264 lib is
very clear in the script.
Don't worry anymore, we make it works after a week.
Next time...

Regards...

2017-05-15 16:37 GMT-03:00 Dan Albert <notifications@github.com>:

**Comment by faisal00813** [comment]
@arielmingrone Can you share how did you make this work?

**Comment by xiaopengs** [comment]
i have the same question when link openssl in ffmpeg.  Can you share how did you make this work?
