### ISSUE TITLE
Fetching images of AIMAGE_FORMAT_JPEG fails

### ISSUE THREAD

**Issue by skanti** [android-ndk/ndk#387]
When fetching images I encounter something strange:

``` c++
ASSERT(AIMAGE_FORMAT_JPEG == src_format, "Failed to get format");
AImage_getHeight(image, &height);
AImage_getWidth(image, &width);
AImage_getPlaneData(image, 0, &pixel, &y_len);

AImage_getPlaneRowStride(image, 0, &stride); // <-- NOT SUPPORTED FOR JPEG
AImage_getPlanePixelStride(image, 0, &pixel_stride); // <-- NOT SUPPORTED FOR JPEG
```

Note, that the last 2 commands return `AMEDIA_ERROR_UNSUPPORTED` for that format.

---

Now writing on the buffer:

``` c++
  uint8_t *out = buf.data;
    for (int y = 0; y < height; y++) {
        const uint8_t *pY = pixel + width*3*y;

        for (int x = 0; x < width; x++) {
            out[x*3 + 0] = pY[x*3 + 0];
            out[x*3 + 1] = pY[x*3 + 1];
            out[x*3 + 2] = pY[x*3 + 2];
        }
        out += width*3;
    }
```

fails for some reason. The `logcat` does not output something meaningful to me - at least not readable.

**Comment by alexcohn** [comment]
[getPlaneData()](https://android.googlesource.com/platform/frameworks/av/+/master/media/ndk/NdkImage.cpp#336) for JPEG gives you the undecoded buffer. You can see that the returned size is much smaller than `width*height*3`.

**Comment by DanAlbert** [comment]
Sorry for not responding sooner. This tab got lost.

Follow https://source.android.com/source/report-bugs if you need to report bugs for any of the frameworks APIs. All we do is ship them.
