### ISSUE TITLE
stlport broken in 15beta1

### ISSUE THREAD

**Issue by schwabe** [android-ndk/ndk#390]
#### Description
inclduing string from stport gives an error:

```
In file included from openvpn//src/openvpn/breakpad.cpp:3:
In file included from breakpad/src/client/linux/handler/exception_handler.h:38:
In file included from /Users/arne/oss/android-ndk-r15-beta1/sources/cxx-stl/stlport/stlport/string:29:
In file included from /Users/arne/oss/android-ndk-r15-beta1/sources/cxx-stl/stlport/stlport/stl/_string.h:23:
In file included from /Users/arne/oss/android-ndk-r15-beta1/sources/cxx-stl/stlport/stlport/stl/_alloc.h:47:
In file included from /Users/arne/oss/android-ndk-r15-beta1/sources/cxx-stl/stlport/stlport/stl/_new.h:114:
/Users/arne/oss/android-ndk-r15-beta1/sources/cxx-stl/stlport/stlport/stl/_cstdio.h:97:26: error: no member named 'gets' in the global namespace
using _STLP_VENDOR_CSTD::gets;
```

expection_handler.h to this point is only copyright header and:

```

#include <signal.h>
#include <stdint.h>
#include <stdio.h>
#include <sys/ucontext.h>

#include <string>
```

#### Environment Details

Not all of these will be relevant to every bug, but please provide as much
information as you can.

* NDK Version: 15beta1
* Build sytem: ndk-build
* Host OS: Mac 10.12.4
* Compiler: Clang
* ABI: arm64-v8a
* STL: stlport_static
* NDK API level: 14
* Device API level: 25

**Comment by enh** [comment]
gets was removed from C11 but stlport hasn't been updated correspondingly. danalbert: let me know if you want me to hack stlport to add the __STDC_VERSION__ check around this.

**Comment by enh** [comment]
looks like gnu stl might have the same problem. (see _GLIBCXX_HAVE_GETS, which ought to be the solution, but seems like it's always #defined to 1?)

**Comment by DanAlbert** [comment]
I think we still have time to get this fix into r15 beta 2, and that seems worth doing since this would cause quite the headache for unified headers.

**Comment by DanAlbert** [comment]
The scope of this is a bit different than we first thought. This only comes up if you're using stlport but also using C++14, which should be a pretty uncommon use case. I'd be holding back testing for I/O if I delayed to pick this up for beta 2, so this won't make it into that release, but we'll pick this up for r15 final.

@schwabe: Why do you have this mix of C++14 stlport, anyway? gnustl should be able to provide some of the C++14 language features, whereas stlport doesn't even provide C++11. Is switching an option for you? (libc++ would be even better, but that still needs some more testing for me to really recommend it)

**Comment by enh** [comment]
fix here: https://android-review.googlesource.com/394082

turns out gnustl is unaffected (but i've included the test for both stls anyway).

**Comment by DanAlbert** [comment]
Thanks to a well timed infrastructure outage, we're going to get this in r15 beta 2 after all.

**Comment by schwabe** [comment]
That -std=c++1y is something I had only as test, completely forgot about that, sorry for missing that in the issue.

**Comment by DanAlbert** [comment]
No worries, it was pretty easy to infer.

We've merged the fix, so closing this.
