### ISSUE TITLE
'uchar.h' file not found

### ISSUE THREAD

**Issue by charmeleon2** [android-ndk/ndk#391]
#### Description

when i build ffmpeg ,it report 
/Users/admin/android-ndk-r14b/toolchains/llvm/prebuilt/darwin-x86_64/bin/../lib64/clang/3.8.275480/include/stdatomic.h:150:11: fatal error: 'uchar.h' file not found
# include <uchar.h>  /* For char16_t and char32_t.              */

#### Environment Details

Not all of these will be relevant to every bug, but please provide as much
information as you can.

* NDK Version: r14b
* Build sytem: ndk-build
* Host OS:  mac os sierra
* Compiler: 
* ABI:
* STL:
* NDK API level:
* Device API level:

**Comment by DanAlbert** [comment]
Obsolete with r15. You can opt into the fix in r14 by using [unifed headers](https://android.googlesource.com/platform/ndk/+/ndk-r14-release/docs/UnifiedHeaders.md) (on by default in r15).

**Comment by oncealong** [comment]
> Obsolete with r15. You can opt into the fix in r14 by using [unifed headers](https://android.googlesource.com/platform/ndk/+/ndk-r14-release/docs/UnifiedHeaders.md) (on by default in r15).

In ndk14 [Unified Headers](https://android.googlesource.com/platform/ndk/+/ndk-r14-release/docs/UnifiedHeaders.md), it shows "use `--unified-headers`" if my build system is `Standalone Toolchains`.
```
$NDK/build/tools/make_standalone_toolchain.py --unified-headers ...
```
But it didn't work.
"$NDK14/sysroot/usr/include/uchar.h" is exists. 
Then I use `$NDK14/build/tools/make_standalone_toolchain.py 		--install-dir=$NDK14-toolchain         --arch arm   --api 16         --unified-headers         --force` to make standalone toolchain.
But I found ''$NDK14-toolchain/sysroot/usr/include/uchar.h" not exists.

I read `make_standalone_toolchain.py`, and found input "unified-headers" is not used.

![image](https://user-images.githubusercontent.com/5340073/61587267-4cf5fe00-abb9-11e9-822d-b1dd06e91b50.png)

Now I build openssl_1_1_1-stable with ndk14，use `Standalone Toolchains`. But it report the error, how can I fix this?
```
$NDK14-toolchain/bin/../lib64/clang/3.8.275480/include/stdatomic.h:150:11: fatal error:
      'uchar.h' file not found
# include <uchar.h>  /* For char16_t and char32_t.              */
          ^
1 error generated.
make[1]: *** [crypto/asn1/a_sign.o] Error 1
make[1]: Leaving directory `/Users/along/EduAppDev/ARMPlayer/thirdparty/openssl/src'
make: *** [build_libs] Error 2
```

**Comment by DanAlbert** [comment]
NDK r14 is no longer supported. If you see a problem with r20 please open a new bug.
