### ISSUE TITLE
Unified headers breaks code which defines any function called major(), minor() or makedev()

### ISSUE THREAD

**Issue by aiusepsi** [android-ndk/ndk#398]
#### Description

sys/sysmacros.h defines `int major(dev_t)`, `int minor(dev_t)`, and `dev_t makedev(int, int)`. In the deprecated headers, these are inline functions. In the unified headers, they are function-like macros.

The inline functions would only collide with another function called major, minor etc. but the macros will replace anything with a function-like form, e.g. definitions of class methods called major, minor, or makedev. This will cause code which has such definitions to fail to compile when moving from the deprecated headers to the unified headers.

A work-around is to define `_SYS_SYSMACROS_H_` as this prevents the definition of the macros.

As an example of code that will fail to compile:
```c++
#include <stdio.h>

class test {
public:
  int major() const;
  int minor;
};

int test::major() const {
  return minor;
}

int main(void) {
  test t;
  t.minor = 0;
  return t.major();
}
```

In my case, this issue prevented compilation of the generated C++ code for the protocol buffer: 
```protobuf
message VersionNum {
	uint32 major = 1;
	uint32 minor = 2;
	uint32 rev = 3;
	string git_hash = 4;
}
```
as the accessors for the major and minor fields were broken by getting macro-expanded.

#### Environment Details

* NDK Version: 14.1.3816874 and 15.0.3869609-beta1 
* Build system: Standalone toolchain with unified headers

Toolchains generated with:
```bash
$NDK14/build/tools/make_standalone_toolchain.py --arch arm --install-dir ./toolchain_14_unified --unified-headers
$NDK15/build/tools/make_standalone_toolchain.py --arch arm --install-dir ./toolchain_15_unified --unified-headers
```

* Host OS: Mac 10.12.4
* Compiler: Clang
* ABI: arm

**Comment by enh** [comment]
my first thought was "why are you including <sys/sysmacros.h> if you don't want what it contains?" but then i realized you're being bitten by this in <sys/types.h>:

#if defined(__USE_BSD) || defined(__BIONIC__) /* Historically bionic exposed these. */
#include <sys/sysmacros.h>

ugh. i'll look into this...

**Comment by enh** [comment]
https://android-review.googlesource.com/402242 needs to be cherrypicked into r15...
