### ISSUE TITLE
r15 beta2 -g broken on MIPS and MIPS64

### ISSUE THREAD

**Issue by yan12125** [android-ndk/ndk#399]
#### Description

Since Android r15 beta2, -g is broken on MIPS and MIPS64. There are 4 scenarios:
1. MIPS64 without -fno-integrated-as: failed
```
$ /opt/android-ndk-beta/toolchains/llvm/prebuilt/linux-x86_64/bin/clang -target mips64el-none-linux-android -gcc-toolchain /opt/android-ndk-beta/toolchains/mips64el-linux-android-4.9/prebuilt/linux-x86_64 --sysroot=/opt/android-ndk-beta/sysroot/usr -I/opt/android-ndk-beta/sysroot/usr/include/mips64el-linux-android -D__ANDROID_API__=21 -fPIC -g test.c -save-temps
test.s: Assembler messages:
test.s:6: Warning: unrecognized section type
test.s:6: Warning: entity size for SHF_MERGE not specified
test.s:6: Error: junk at end of line, first unrecognized character is `0'
test.s:13: Warning: unrecognized section type
test.s:13: Error: junk at end of line, first unrecognized character is `0'
test.s:14: Warning: unrecognized section type
test.s:14: Error: junk at end of line, first unrecognized character is `0'
test.s:31: Warning: unrecognized section type
test.s:31: Error: junk at end of line, first unrecognized character is `0'
test.s:43: Warning: unrecognized section type
test.s:43: Error: junk at end of line, first unrecognized character is `0'
test.s:44: Warning: unrecognized section type
test.s:44: Error: junk at end of line, first unrecognized character is `0'
test.s:51: Warning: unrecognized section type
test.s:51: Error: junk at end of line, first unrecognized character is `0'
clang: error: assembler command failed with exit code 1 (use -v to see invocation)
```
2. MIPS64 with -fno-integrated-as: failed
```
$ /opt/android-ndk-beta/toolchains/llvm/prebuilt/linux-x86_64/bin/clang -target mips64el-none-linux-android -gcc-toolchain /opt/android-ndk-beta/toolchains/mips64el-linux-android-4.9/prebuilt/linux-x86_64 --sysroot=/opt/android-ndk-beta/sysroot/usr -I/opt/android-ndk-beta/sysroot/usr/include/mips64el-linux-android -D__ANDROID_API__=21 -fPIC -g test.c -save-temps -fno-integrated-as
test.s: Assembler messages:
test.s:6: Warning: unrecognized section type
test.s:6: Warning: entity size for SHF_MERGE not specified
test.s:6: Error: junk at end of line, first unrecognized character is `0'
test.s:13: Warning: unrecognized section type
test.s:13: Error: junk at end of line, first unrecognized character is `0'
test.s:14: Warning: unrecognized section type
test.s:14: Error: junk at end of line, first unrecognized character is `0'
test.s:31: Warning: unrecognized section type
test.s:31: Error: junk at end of line, first unrecognized character is `0'
test.s:43: Warning: unrecognized section type
test.s:43: Error: junk at end of line, first unrecognized character is `0'
test.s:44: Warning: unrecognized section type
test.s:44: Error: junk at end of line, first unrecognized character is `0'
test.s:51: Warning: unrecognized section type
test.s:51: Error: junk at end of line, first unrecognized character is `0'
clang: error: assembler command failed with exit code 1 (use -v to see invocation)
```
3. MIPS without -fno-integrated-as: works
```
$ /opt/android-ndk-beta/toolchains/llvm/prebuilt/linux-x86_64/bin/clang -target mipsel-none-linux-android -gcc-toolchain /opt/android-ndk-beta/toolchains/mipsel-linux-android-4.9/prebuilt/linux-x86_64 --sysroot=/opt/android-ndk-beta/sysroot/usr -I/opt/android-ndk-beta/sysroot/usr/include/mipsel-linux-android -D__ANDROID_API__=21 -fPIC -g -c test.c -save-temps           
```
4. MIPS64 with -fno-integrated-as: failed
```
$ /opt/android-ndk-beta/toolchains/llvm/prebuilt/linux-x86_64/bin/clang -target mipsel-none-linux-android -gcc-toolchain /opt/android-ndk-beta/toolchains/mipsel-linux-android-4.9/prebuilt/linux-x86_64 --sysroot=/opt/android-ndk-beta/sysroot/usr -I/opt/android-ndk-beta/sysroot/usr/include/mipsel-linux-android -D__ANDROID_API__=21 -fPIC -g -c test.c -save-temps -fno-integrated-as
test.s: Assembler messages:
test.s:8: Warning: unrecognized section type
test.s:8: Warning: entity size for SHF_MERGE not specified
test.s:8: Error: junk at end of line, first unrecognized character is `0'
test.s:15: Warning: unrecognized section type
test.s:15: Error: junk at end of line, first unrecognized character is `0'
test.s:16: Warning: unrecognized section type
test.s:16: Error: junk at end of line, first unrecognized character is `0'
test.s:33: Warning: unrecognized section type
test.s:33: Error: junk at end of line, first unrecognized character is `0'
test.s:45: Warning: unrecognized section type
test.s:45: Error: junk at end of line, first unrecognized character is `0'
test.s:46: Warning: unrecognized section type
test.s:46: Error: junk at end of line, first unrecognized character is `0'
test.s:53: Warning: unrecognized section type
test.s:53: Error: junk at end of line, first unrecognized character is `0'
clang: error: assembler command failed with exit code 1 (use -v to see invocation)
```

I need -fno-integrated-as on MIPS due to #286, which is still an issue with the recent Clang update.

For now I disable debugging flags as a workaround.

#### Environment Details

Not all of these will be relevant to every bug, but please provide as much
information as you can.

* NDK Version: 15.0.3996722-beta2
* Build sytem: custom
* Host OS: Arch Linux x86_64 latest
* Compiler: Clang
* ABI: MIPS, MIPS64
* STL: N/A
* NDK API level: 21
* Device API level: N/A

**Comment by yan12125** [comment]
PS: test.c in above tests is an empty file

**Comment by DanAlbert** [comment]
Whoops. I fixed this in ndk-build and cmake but forgot to add a note to the changelog for those of you with custom build systems. Sorry about that. I'll get the changelog updated.

You need to explicitly pass `-fintegrated-as` for mips64, btw. `-fno-integrated-as` is the default for that target.

**Comment by yan12125** [comment]
Thanks! How about document ndk-build and cmake default flags? For example armeabi* uses -fno-integrated-as and mips64 uses -fintegrated-as.

**Comment by DanAlbert** [comment]
> For example armeabi* uses -fno-integrated-as and mips64 uses -fintegrated-as.

That's a clang default, not a ndk-build or cmake default. Those are under the control of upstream clang, so I don't know when they change (they should only rarely).

The ndk-build defaults can be found in the various setup.mk files in the build source: https://android.googlesource.com/platform/ndk/+/master/build/core/toolchains/arm-linux-androideabi-clang/setup.mk. CMake flags can be found in the toolchain file.

**Comment by yan12125** [comment]
Sorry if I was unclear. What I was referring to is the following code segment in ```android.toolchain.cmake```:
```CMake
if(ANDROID_ABI STREQUAL "mips64" AND ANDROID_TOOLCHAIN STREQUAL clang)
  list(APPEND ANDROID_COMPILER_FLAGS "-fintegrated-as")
endif()
if(ANDROID_ABI MATCHES "^armeabi" AND ANDROID_TOOLCHAIN STREQUAL clang)
	# Disable integrated-as for better compatibility.
	list(APPEND ANDROID_COMPILER_FLAGS
		-fno-integrated-as)
endif()
```
Those flags are added by NDK build systems. Documenting them can help custom build system implementers.

**Comment by DanAlbert** [comment]
Ah, yeah. I have a bug open to document things that build system maintainers should know: https://github.com/android-ndk/ndk/issues/125

**Comment by yan12125** [comment]
Great! I guess this issue can be closed in favor of #125?

**Comment by DanAlbert** [comment]
Now that I've gotten the changelog updates pushed to the wiki, yes.

**Comment by yan12125** [comment]
Thanks!

**Comment by xiangzhai** [comment]
@DanAlbert 

> You need to explicitly pass -fintegrated-as for mips64, btw. -fno-integrated-as is the default for that target.

Thanks for your teaching! `-fintegrated-as` fix the binutils/gas compatibility issue, but [lead another bug](https://bugs.llvm.org/show_bug.cgi?id=38221) when compiling OpenJDK8 with LLVM toolchain, could you give me some hint? thanks a lot!

Regards,
Leslie Zhai

**Comment by yan12125** [comment]
Looks like @xiangzhai is building stuffs for a MIPS chip from China instead of Android, and he is not using NDK but their customized LLVM toolchain.

**Comment by xiangzhai** [comment]
@DanAlbert Thanks for your response!

@yan12125 It is not Android or NDK issue.

And it is [not a customzied toolchain](https://www.leetcode.cn/2018/05/loongson-llvm.pdf) just the original one.
But I prefer to [merge by upstream](https://reviews.llvm.org/p/xiangzhai/) sorry that unimplemented Loong-ISA or Machine Scheduler yet.

Regards,
Leslie Zhai
