### ISSUE TITLE
ctype_base.h error

### ISSUE THREAD

**Issue by steven5401** [android-ndk/ndk#404]
#### Description

I'm building android app using caffe-opencl(https://github.com/BVLC/caffe/tree/opencl).
Gradle externalNativeBuild with cmake is fine. After build project, the error is shown below.

`
Information:Gradle tasks [clean, :app:generateDebugSources, :app:mockableAndroidJar, :app:prepareDebugUnitTestDependencies, :app:generateDebugAndroidTestSources, :app:compileDebugSources, :app:compileDebugUnitTestSources, :app:compileDebugAndroidTestSources]`
`/home/laplace/Android/Sdk/ndk-bundle/sources/cxx-stl/gnu-libstdc++/4.9/libs/mips64/include/bits/ctype_base.h`
`Error:(36, 2) error: Bionic header ctype.h does not define either _U nor _CTYPE_U`
`Error:(62, 35) error: use of undeclared identifier '_CTYPE_U'`
`Information:(38, 12) expanded from macro '_U'`
......etc.

What causes this error? How to fix it?

#### Environment Details

* NDK Version: 14.1.3816874
* Build sytem: cmake
* Host OS: Ubuntu 14.04
* Compiler: I don't know
* build.gradle:
```
apply plugin: 'com.android.application'

android {
    compileSdkVersion 25
    buildToolsVersion "25.0.2"
    defaultConfig {
        applicationId "com.euphoria5401.cmlab"
        minSdkVersion 15
        targetSdkVersion 25
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    externalNativeBuild {
        cmake {
            path 'src/main/caffe/CMakeLists.txt'
        }
    }
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    compile 'com.android.support:appcompat-v7:25.3.1'
    testCompile 'junit:junit:4.12'
}
```

**Comment by DanAlbert** [comment]
Probably try using the [updated headers](https://android.googlesource.com/platform/ndk/+/ndk-r14-release/docs/UnifiedHeaders.md#CMake). These were opt-in for r14 since it was a pretty big jump.

**Comment by DanAlbert** [comment]
Please reopen if you're still seeing this problem with r15c.

**Comment by tsirolnik** [comment]
Hi, I do experience this issue. From what I understand is that it happens due to using libraries which are on the OS level (libuv for example on CentOS).

Any way to solve this problem? Updated headers option doesn't help.


Using CMake and NDK 16.1 on Android Studio 3.0.1

**Comment by DanAlbert** [comment]
We can't do anything without a repro case.
