### ISSUE TITLE
libcxx. std::shared_ptr memory leak.

### ISSUE THREAD

**Issue by serhiihuralniksc** [android-ndk/ndk#406]
#### Description
There is a bug in libcxx bundled with NDK. It causes leaked control blocks for the next code
```
class Foo : public std::enable_shared_from_this<Foo> {
};

static void test() {
    LOGI("begin");
    Foo *p = new Foo;
    for (int i = 0; i < 5; i++) {
        auto del = [] (Foo* p) {
            /* no-op */
        };
        std::shared_ptr<Foo> sp(p, del);
    }
    delete p;
    LOGI("end");
}
```
(To be more clear: this snippet represents a pattern that is used by the pool of reusable objects, where deleter doesn't perform actual teardown but instead moves ownership on managed object to some internal temporary owner.)

Minimal working example is available here https://github.com/serhiihuralniksc/NDK-libcxx-leak-demo. It produces next output:
```
begin
void *operator new(std::size_t): 8 bytes 0xf349a0c0
void *operator new(std::size_t): 16 bytes 0xf3498660
void *operator new(std::size_t): 16 bytes 0xf34986b0
void *operator new(std::size_t): 16 bytes 0xf34986c0
void *operator new(std::size_t): 16 bytes 0xf34986d0
void *operator new(std::size_t): 16 bytes 0xf34986e0
void operator delete(void *): 0xf34986e0
void operator delete(void *): 0xf349a0c0
end
```
Actually this bug was fixed in libcxx a long time ago: http://lists.llvm.org/pipermail/cfe-commits/Week-of-Mon-20160530/160792.html. But it is still not ported to NDK.

#### Environment Details
* NDK Version: 13.1.3345770
* Build sytem: N/A
* Host OS: Mac
* Compiler: clang
* ABI: armeabi-v7a
* STL: llvm-libcxx
* NDK API level: N/A
* Device API level: N/A

**Comment by enh** [comment]
yeah, the platform libc++ does have this patch, but this is still missing in r15.

(dan: this is an example where it would be good to have the libc++ revision in the release notes --- the r14 release notes say "updated", but not to what. even with access to codesearch i wasn't able to answer that question.)

**Comment by DanAlbert** [comment]
I finished a libc++ update yesterday, so we're good on this now.

**Comment by bhupeshpant19jan** [comment]
What is the revision number for r16 with this fix?

**Comment by DanAlbert** [comment]
Revision of what?

**Comment by bhupeshpant19jan** [comment]
Version when this fix has been merged to r16

**Comment by enh** [comment]
the fix is in r16 and r16b.
