### ISSUE TITLE
Cannot locate symbol "__cxa_bad_typeid"

### ISSUE THREAD

**Issue by ivan-ushakov** [android-ndk/ndk#408]
Hello,

I faced with same problem as here https://github.com/android-ndk/ndk/issues/175 but I decided to open new issue because I use newer NDK version. I'm trying to create debug version for shared library. I follow official guild for building and build procedure looks like this:

1. Create standalone toolchain.

        android-ndk-r14-beta1/build/tools/make_standalone_toolchain.py --api 21 --stl=libc++ --arch arm64 --install-dir /opt/android/tool64

2. Set path priority for toolchain.

        PATH=/opt/android/tool64/aarch64-linux-android/bin:/opt/android/tool64/bin:$PATH

3. Run cmake.

        CC=clang CXX=clang++ cmake <library options here>

When I run app with release build type I can use C++ API but it crashes when I call one of API functions. So I decided to build debug version to see stacktrace. When I try to run app with debug library I'm getting this exception: 

    /com... W/linker: /data/app/com...-1/lib/arm64/lib...so: unused DT entry: type 0xf arg 0x45291f
    /com... D/AndroidRuntime: Shutting down VM
    /com... E/AndroidRuntime: FATAL EXCEPTION: main
                              Process: com..., PID: 1527
                              java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "__cxa_bad_typeid" referenced by "/data/app/com....-1/lib/arm64/lib...so"...
                                    at java.lang.Runtime.loadLibrary0(Runtime.java:989)
                                    at java.lang.System.loadLibrary(System.java:1562)

* Build system: cmake 
* Host OS: Built on Linux, used on OS X
* Compiler: clang
* ABI: armv8-a
* STL: libc++
* NDK API level: 21
* Device API level: 25
* NDK version: r14 beta1

**Comment by enh** [comment]
are you actually using r14beta1? have you tried the actual r14b release or r15beta2?

**Comment by ivan-ushakov** [comment]
Yes, it was r14beta1. Now I tested with r14 and result is the same. I can provide .so file since it is a github project.

**Comment by ivan-ushakov** [comment]
For some reason then I removed this flag `arguments "-DANDROID_STL=c++_shared"` from my gradle file it started to work. Would be nice to know what is wrong with flag.

**Comment by DanAlbert** [comment]
> For some reason then I removed this flag arguments "-DANDROID_STL=c++_shared" from my gradle file it started to work. Would be nice to know what is wrong with flag.

> Am I right that `__cxa_bad_typeid` is about RTTI?

Yep, that's for RTTI. The reason you're seeing this with `c++_shared` and not with `c++_static` is presumably because libc++ itself is built with RTTI, but if you use the static library you're not making use of any of the pieces that require `__cxa_bad_typeid`, so the linker strips those and you end up not needing the symbol.

> I can provide .so file since it is a github project.

.so file would help, but if it's open source then giving the link to the project and some repro instructions is even better.

**Comment by DanAlbert** [comment]
Side note: why are you using a standalone toolchain *and* CMake. We ship CMake support now. There's a toolchain file you can use at `$NDK/build/cmake/android.toolchain.cmake`.

**Comment by ivan-ushakov** [comment]
I'm using standalone toolchain because I try to follow this [guide](https://forum.getmonero.org/5/support/87643/building-monero-v0-10-3-1-for-android) . Project name is [Monero](https://github.com/monero-project/monero). The only thing I changed was switching to shared libraries instead of static.
I can provide you shared libraries to save your time because building shared libraries require some changes in current CMake files.

**Comment by DanAlbert** [comment]
Okay, let's start with that and I can move on to trying source if that's needed.

**Comment by ivan-ushakov** [comment]
[Here is](https://www.dropbox.com/s/pmlp4mteba0prbh/MoneroTest_2017.zip?dl=0) test project with shared libraries for arm64. All I mentioned above was only about arm64, I haven't tested with other architectures.

**Comment by DanAlbert** [comment]
Your project doesn't build.

```
$ ./gradlew build
Incremental java compilation is an incubating feature.
:app:preBuild UP-TO-DATE
:app:preDebugBuild UP-TO-DATE
:app:checkDebugManifest
:app:preReleaseBuild UP-TO-DATE
:app:prepareComAndroidSupportAnimatedVectorDrawable2340Library
:app:prepareComAndroidSupportAppcompatV72340Library
:app:prepareComAndroidSupportConstraintConstraintLayout102Library
:app:prepareComAndroidSupportSupportV42340Library
:app:prepareComAndroidSupportSupportVectorDrawable2340Library
:app:prepareDebugDependencies
:app:compileDebugAidl
:app:compileDebugRenderscript
:app:generateDebugBuildConfig
:app:generateDebugResValues
:app:generateDebugResources
:app:mergeDebugResources
:app:processDebugManifest
:app:processDebugResources
:app:generateDebugSources
:app:incrementalDebugJavaCompilationSafeguard
:app:javaPreCompileDebug
:app:compileDebugJavaWithJavac
:app:compileDebugJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
:app:generateJsonModelDebug
:app:externalNativeBuildDebug
Build native-lib arm64-v8a
ninja: error: 'src/main/jniLibs/arm64-v8a/libblockchain_db.so', needed by '../../../../build/intermediates/cmake/debug/obj/arm64-v8a/libnative-lib.so', missing and no known rule to make it
:app:externalNativeBuildDebug FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:externalNativeBuildDebug'.
> Build command failed.
  Error while executing process /usr/local/google/home/danalbert/Android/Sdk/cmake/3.6.3155560/bin/cmake with arguments {--build /work/src/monero/MoneroTest_2017/app/.externalNativeBuild/cmake/debug/arm64-v8a --target native-lib}
  ninja: error: 'src/main/jniLibs/arm64-v8a/libblockchain_db.so', needed by '../../../../build/intermediates/cmake/debug/obj/arm64-v8a/libnative-lib.so', missing and no known rule to make it


* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED
```

Another question though, since there are a handful of prebuilt libraries involved: were all the libraries generated with the same version of the NDK? If one of them is built with an old NDK (one that still had this bug), that would explain the issue.

**Comment by DanAlbert** [comment]
Actually, do you know if `libc++_shared.so` is making it on to the device? You need to ship that too, and Studio doesn't know anything about standalone toolchains, so I really doubt it will do that for you.

I'd expect a different error if that were the case, but maybe some old `libc++_shared.so` is being shipped instead of a current one?

**Comment by ivan-ushakov** [comment]
> I'd expect a different error if that were the case, but maybe some old libc++_shared.so is being shipped instead of a current one?
No, I don't ship `libc++_shared.so` in my project.

**Comment by ivan-ushakov** [comment]
> Your project doesn't build.

All libraries including `libblockchain_db.so` are in `arm64-v8a` folder. Maybe I did mistake in CMake file because in my local project I use absolute path to `.so` files.

> Another question though, since there are a handful of prebuilt libraries involved: were all the libraries generated with the same version of the NDK?

Yes, they where built all at once using provided manual.

**Comment by DanAlbert** [comment]
>> I'd expect a different error if that were the case, but maybe some old libc++_shared.so is being shipped instead of a current one?
> No, I don't ship libc++_shared.so in my project.

I think read something backwards, I think. Which STL are you trying to use? With c++_shared, you need to ship the shared library, but it sounds like you're trying to get away from that. Which are you trying to use instead?

**Comment by ivan-ushakov** [comment]
I just use this argument in gradle: `arguments "-DANDROID_STL=c++_shared"`. So I expect that gradle ship something, right?

**Comment by DanAlbert** [comment]
That's my understanding, yes, but I don't actually know how the logic around that works (Studio decides what to package; the NDK only builds things).

If you're passing `-DANDROID_STL=c++_shared`, and you're getting "libc++_shared.so not found" on the device, then that's the question to answer. What version of Studio are you using? If you unzip the APK, do you see libc++_shared.so in the app?

**Comment by DanAlbert** [comment]
> I checked more carefully and found that first time I need to set that flag because otherwise I'm getting error c++_shared.so not found.

Basing the "not found" on this comment. That wasn't in the original report though, so maybe it's not an error that's present any more?

**Comment by DanAlbert** [comment]
> As I understand device already has one.

No, it doesn't.

**Comment by ivan-ushakov** [comment]
> What version of Studio are you using?

Android Studio 2.3.2
Build #AI-162.3934792, built on April 21, 2017
JRE: 1.8.0_112-release-b06 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

> If you unzip the APK, do you see libc++_shared.so in the app?

    $ ls -l ~/Downloads/com.lunarkey.monerotest/base.apk/lib/arm64-v8a/
    total 65024
    -rw-r--r--  1 ivan_ushakov  staff   1393816 Nov 30  1979 libblockchain_db.so
    -rw-r--r--  1 ivan_ushakov  staff    972552 Nov 30  1979 libc++_shared.so
    -rw-r--r--  1 ivan_ushakov  staff    296096 Nov 30  1979 libcncrypto.so
    -rw-r--r--  1 ivan_ushakov  staff   2731712 Nov 30  1979 libcommon.so
    -rw-r--r--  1 ivan_ushakov  staff   1142672 Nov 30  1979 libcrypto.so
    -rw-r--r--  1 ivan_ushakov  staff   3324832 Nov 30  1979 libcryptonote_basic.so
    -rw-r--r--  1 ivan_ushakov  staff   5311912 Nov 30  1979 libcryptonote_core.so
    -rw-r--r--  1 ivan_ushakov  staff    696088 Nov 30  1979 libeasylogging.so
    -rw-r--r--  1 ivan_ushakov  staff    116976 Nov 30  1979 liblmdb.so
    -rw-r--r--  1 ivan_ushakov  staff   3332536 Nov 30  1979 libmnemonics.so
    -rw-r--r--  1 ivan_ushakov  staff     14096 Nov 30  1979 libnative-lib.so
    -rw-r--r--  1 ivan_ushakov  staff    575696 Nov 30  1979 libp2p.so
    -rw-r--r--  1 ivan_ushakov  staff    491304 Nov 30  1979 libringct.so
    -rw-r--r--  1 ivan_ushakov  staff    239608 Nov 30  1979 libssl.so
    -rw-r--r--  1 ivan_ushakov  staff    899352 Nov 30  1979 libunbound.so
    -rw-r--r--  1 ivan_ushakov  staff  11728088 Nov 30  1979 libwallet.so

Here is how it is located on device:

    $ ./adb shell pm path com.lunarkey.monerotest
    package:/data/app/com.lunarkey.monerotest-1/base.apk
    package:/data/app/com.lunarkey.monerotest-1/split_lib_dependencies_apk.apk
    package:/data/app/com.lunarkey.monerotest-1/split_lib_slice_0_apk.apk
    package:/data/app/com.lunarkey.monerotest-1/split_lib_slice_1_apk.apk
    package:/data/app/com.lunarkey.monerotest-1/split_lib_slice_2_apk.apk
    package:/data/app/com.lunarkey.monerotest-1/split_lib_slice_3_apk.apk
    package:/data/app/com.lunarkey.monerotest-1/split_lib_slice_4_apk.apk
    package:/data/app/com.lunarkey.monerotest-1/split_lib_slice_5_apk.apk
    package:/data/app/com.lunarkey.monerotest-1/split_lib_slice_6_apk.apk
    package:/data/app/com.lunarkey.monerotest-1/split_lib_slice_7_apk.apk
    package:/data/app/com.lunarkey.monerotest-1/split_lib_slice_8_apk.apk
    package:/data/app/com.lunarkey.monerotest-1/split_lib_slice_9_apk.apk

**Comment by ivan-ushakov** [comment]
> Basing the "not found" on this comment. That wasn't in the original report though, so maybe it's not an error that's present any more?

Problem still the same: when I build project from Android Studio and try to run it I see error from my first message. And as you see `libc++_shared.so` is present in apk.

**Comment by DanAlbert** [comment]
Can you share the APK?

**Comment by ivan-ushakov** [comment]
[com.lunarkey.monerotest.zip](https://github.com/android-ndk/ndk/files/1065336/com.lunarkey.monerotest.zip)

**Comment by DanAlbert** [comment]
The libc++_shared.so in your APK does not match the one in r14b.

```bash
$ adb pull /data/app/com.lunarkey.monerotest-1/lib/arm64/libc++_shared.so
$ readelf -sW libc++_shared.so | grep __cxa_bad_cast
$ readelf -sW android-ndk-r14b/sources/cxx-stl/llvm-libc++/libs/arm64-v8a/libc++_shared.so | grep __cxa_bad_cast
   965: 0000000000096980    52 FUNC    GLOBAL DEFAULT   10 __cxa_bad_cast
$
```

**Comment by DanAlbert** [comment]
```bash
$ readelf -sW android-ndk-r15/sources/cxx-stl/llvm-libc++/libs/arm64-v8a/libc++_shared.so | grep __cxa_bad_cast                                         
   946: 000000000009956c    52 FUNC    GLOBAL DEFAULT   10 __cxa_bad_cast
$ readelf -sW android-ndk-r13b/sources/cxx-stl/llvm-libc++/libs/arm64-v8a/libc++_shared.so | grep __cxa_bad_cast
  1385: 0000000000096b4c    52 FUNC    GLOBAL DEFAULT    8 __cxa_bad_cast
$ readelf -sW android-ndk-r12b/sources/cxx-stl/llvm-libc++/libs/arm64-v8a/libc++_shared.so | grep __cxa_bad_cast
$
```

**Comment by DanAlbert** [comment]
Are you sure your NDK it up to date? It definitely looks like ndk.dir=/Users/ivan_ushakov/Library/Android/sdk/ndk-bundle is r12. Try `cat ndk.dir=/Users/ivan_ushakov/Library/Android/sdk/ndk-bundle/source.properties`.

**Comment by ivan-ushakov** [comment]
Yes, you are right. It was old version of NDK inside Android Studio.  Thank you for this help.
Now with r15 it shows another link error.

    java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "_Unwind_Resume" referenced by "/data/app/com.lunarkey.monerotest-1/lib/arm64/libblockchain_db.so"...

May I open another issue for this?

**Comment by DanAlbert** [comment]
That's after rebuilding those libs with r15? If so, yeah, open another bug. Could you upload the rebuilt artifacts when you do?

**Comment by alizx** [comment]
> Yes, you are right. It was old version of NDK inside Android Studio. Thank you for this help.
> Now with r15 it shows another link error.
> 
> ```
> java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "_Unwind_Resume" referenced by "/data/app/com.lunarkey.monerotest-1/lib/arm64/libblockchain_db.so"...
> ```
> 
> May I open another issue for this?

Have you been able to resolve this issue? I am facing the same problem.

**Comment by pengzhendong** [comment]
> Have you been able to resolve this issue? I am facing the same problem.

Have you been able to resolve this issue? I am facing the same problem.
