### ISSUE TITLE
make-standalone-toolchain.sh doesn't work with Cygwin

### ISSUE THREAD

**Issue by azharudd** [android-ndk/ndk#41]
The variable SYSTEM gets computed from "$HOST_OS-$HOST_ARCH" as "cygwin-x86_64" or cygwin-x86" and no such dir exists in toolchains/arm-linux-androideabi-4.9/prebuilt/ (obviously, windows or windows-x86_64 will be present)

Earlier, this script supported the option "--system=", which could be set to select the host and this wasn't an issue. This option is now removed causing it to error out. 

Any pointers on this ?

**Comment by DanAlbert** [comment]
I'll add a check for cygwin and rewrite to windows, that way you won't need `--system` anyway.

I don't have the ability to test this easily, so when I have a patch I'll post it here. It would be really helpful if you could test it for me.

**Comment by DanAlbert** [comment]
Fix looks trivial. Give it a shot and let me know: https://android-review.googlesource.com/209970
