### ISSUE TITLE
[r14b][API 24] Undefined reference to stdin/stdout/stderr when linking against libc.a with unified headers

### ISSUE THREAD

**Issue by chenxiaolong** [android-ndk/ndk#410]
With NDK r14b, API 24, and unified headers, when linking a static executable, the `stdin`/`stdout`/`stderr` symbols cannot be found. It seems that `libc.a` is really missing those symbols:

```
[ndk_unified_static_test] nm $ANDROID_NDK/platforms/android-24/arch-arm/usr/lib/libc.a | grep stdout
[ndk_unified_static_test]
```

However, `__sF` does exist:

```
[ndk_unified_static_test] nm $ANDROID_NDK/platforms/android-24/arch-arm/usr/lib/libc.a | grep __sF
         U __sF
...
[ndk_unified_static_test]
```

This doesn't match what is specified in the unified headers: https://github.com/android/platform_bionic/blob/ndk-r14-release/libc/include/stdio.h#L69

It seems that `libc.a` is the same for API 21, 22, 23, and 24.

Is there a good way to work around this without disabling the unified headers or doing something ugly like this?

```
#pragma once

// NDK ships API 21 libc.a
#if __ANDROID_API__ > 21
#  define UNIFIED_STDIO_HACK
#endif

#ifdef UNIFIED_STDIO_HACK
#  pragma push_macro("__ANDROID_API__")
#  undef __ANDROID_API__
#  define __ANDROID_API__ 21
#endif

#include_next <stdio.h>

#ifdef UNIFIED_STDIO_HACK
#  pragma pop_macro("__ANDROID_API__")
#  undef UNIFIED_STDIO_HACK
#endif
```

---

Sample test project: https://github.com/chenxiaolong/ndk_unified_static_test

**Comment by DanAlbert** [comment]
Dup of https://github.com/android-ndk/ndk/issues/272
