### ISSUE TITLE
string wstring assignment in different modules 

### ISSUE THREAD

**Issue by beifengche** [android-ndk/ndk#414]
#### Description
In the module a.so  

```c++
void fun1(string& str)
{
     str = "test";
}
```

In the module b.so call fun1 of the a.so

```c++
void fun2()
{
       
      string str;  //str is not value is not ok
     fun1(str) // is not ok  bug log A/libc Inavlid address 0xe66fec1c passed to free:value not allocted
     
     string str1 = "test";  //str1 is initialize by "test"
     fun1(str1) // call fun1 is ok
}
```

It happens in The fun1 and fun2 in different moudles .
#### Environment Details

Not all of these will be relevant to every bug, but please provide as much
information as you can.

* NDK Version: 14.1.3816874
* Build sytem:  cmake  
* Host OS: Ubuntu
* Compiler: Clang 
* ABI: armeabi-v7a
* STL: gnustl_shared
* NDK API level: 
* Device API level:

**Comment by stephenhines** [comment]
The "Environment Details" say you were using gnustl_shared, but to me it seems like you are using a static STL, since that would cause exactly this kind of problem. Did you compile both of these .so files with the same NDK also, or is one from somewhere else?

**Comment by beifengche** [comment]
Thank you ,stephenhines

**Comment by DanAlbert** [comment]
Taking that as a yes then.
