### ISSUE TITLE
strtof doesn't set ERANGE for pre-L targets

### ISSUE THREAD

**Issue by DanAlbert** [android-ndk/ndk#415]
Calling `strtof` when targeting anything below android-21 won't set ERANGE for values that aren't representable as `float` but are representable as `double` because `strtof` is an inline function that calls `strtod` (`strtof` somehow wasn't added until L).

**Comment by DanAlbert** [comment]
This one we should just be able to fix in the existing inline rather than having to pull in a whole strtof implementation.

**Comment by rprichard** [comment]
Fixed by https://android-review.git.corp.google.com/c/platform/bionic/+/2080270
