### ISSUE TITLE
URL for yasm documentation on NDK 15 is broken.

### ISSUE THREAD

**Issue by pjmlp** [android-ndk/ndk#416]
#### Description

yasm documentation about how to use it with CMake on the NDK 15 release notes points a web site called MOMA which requires authentication, instead of actual documentation.

The link https://android-dot-devsite.googleplex.com/ndk/guides/cmake.html#yasm-cmake gets redirected into https://login.corp.google.com/request?s=android-dot-devsite.googleplex.com:443/uberproxy/&d=https://android-dot-devsite.googleplex.com/ndk/guides/cmake.html%3Fupxsrf%3DADBfK3aoYtM_MqEDGA6T:1496986663916&maxAge=1200&authLevel=2000000&keyIds=MIG,ubk,kY-,Q3b#yasm-cmake

#### Environment Details

* NDK Version: 15

**Comment by DanAlbert** [comment]
... not sure how that got there. Of course when *I* tested it, I could access it :)

Fixed now.
