### ISSUE TITLE
Unified sys/stat.h doesn't match the one in platforms/android-23/arch-arm

### ISSUE THREAD

**Issue by nargus** [android-ndk/ndk#417]
#### Description

The unified sys/stat.h header file has differing struct variables from the same header in deprecated folder at platforms/android-23/arch-arm/usr/sys/stat.h.

This causes error "error: no member named 'st_atime_nsec' in 'stat'" when switching from older NDK to r15.

I checked with API android-26, and it has the same issue.

#### Environment Details

* NDK Version: 15.0.4075724
* Build sytem: android.toolchain.cmake
* Host OS: Mac
* Compiler: Clang
* ABI: armeabi-v7a
* STL: c++_static
* NDK API level: android-23

**Comment by choury** [comment]
I got an error:
android-sdk-linux/ndk-bundle/sysroot/usr/include/linux/types.h:21:23: fatal error: asm/types.h: No such file or directory
#include <asm/types.h>

**Comment by DanAlbert** [comment]
@choury: file another bug, that has nothing to do with this one

@nargus: Looks like the change was mandated by POSIX: https://android.googlesource.com/platform/bionic/+/0ac0df84c7e96cca6abb800488462b7dfba86622%5E%21

The stat struct now has timespec structs holding both the sec and nsec values, and there are macros (`st_atime` and `st_atimensec`) to access those directly. Unfortunately, those macros that were added for compatibility don't have an underscore between atime and nsec. According to the comment, we used the new names for compatibility with glibc?

@enh: any reason we shouldn't just have both?

**Comment by gqjjqg** [comment]
@choury 
I got the same error.
have any solution?

**Comment by choury** [comment]
@gqjjqg

**Comment by gqjjqg** [comment]
@choury 
solved, thanks very much.

**Comment by DanAlbert** [comment]
FYI, you'll want to turn that back off once r15b ships some time next week

**Comment by DanAlbert** [comment]
The fix has been merged into r15b. I'm sending build 4113355 of ndk-r15-release off to QA here in a bit if you want to grab the RC from the build server (https://android.googlesource.com/platform/ndk/+/master/docs/ContinuousBuilds.md), otherwise it should be out some time this week.
