### ISSUE TITLE
Is <tuple> included by default in libc++?

### ISSUE THREAD

**Issue by Zingam** [android-ndk/ndk#418]
The following code will not compile in r15 with GNU STL but does comiple with libc++. Also AS 3.0 reports that `#include <tuple>` is unused (if uncommented). Shouldn't all C++ library headers be included in a project explicitly?

```
#include <jni.h>
#include <string>
//#include <tuple>

std::tuple<int, std::string> getData()
{
    return std::tuple<int, std::string> (5, "17");
};

extern "C"
JNIEXPORT jstring

JNICALL
Java_com_roccoor_myapplication_MainActivity_stringFromJNI(
        JNIEnv *env,
        jobject /* this */) {
    std::string hello = "Hello from C++";

    auto [a, b] = getData();
    //hello += std::to_string(a);
    hello += b;
    return env->NewStringUTF(hello.c_str());
}
```

**Comment by jmgao** [comment]
libc++'s `<string>` includes `<utility>` which brings in the definition of tuple. There's all sorts of leakage that can be different between implementations, and that's probably going to be true for a long time (modules might help if/when they actually get standardized, but that's still years out).

Including `<tuple>` is the correct thing to do, Android Studio shouldn't emitting a warning for it.

**Comment by DanAlbert** [comment]
> Shouldn't all C++ library headers be included in a project explicitly?

Yeah, that's the better approach (a handful of tools exist to actually do the opposite of what Studio apparently does).

I refiled this against Studio: https://issuetracker.google.com/62489734
