### ISSUE TITLE
Clang crash with MIPS64 target.

### ISSUE THREAD

**Issue by glslang** [android-ndk/ndk#419]
--------------------------------------------------------------------------------

#### Description

Clang crash with MIPS64 target.

#### Environment Details

* NDK Version: r15
* Build sytem: standalone toolchain
* Host OS: Linux - Ubuntu 17.04
* Compiler: Clang
* ABI: MIPS64
* NDK API level: 21

Zipped files because don't seem to be able to upload the .c and .sh separately.

[clang-crash.zip](https://github.com/android-ndk/ndk/files/1066401/clang-crash.zip)

clang50: error: unable to execute command: Segmentation fault (core dumped)
clang50: error: clang frontend command failed due to signal (use -v to see invocation)
Android clang version 5.0.300080  (based on LLVM 5.0.300080)
Target: mips64el-none-linux-android
Thread model: posix
InstalledDir: /home/goncalo/greenaddress/GreenBits/app/libwally-core/toolchain/bin
clang50: note: diagnostic msg: PLEASE submit a bug report to http://llvm.org/bugs/ and include the crash backtrace, preprocessed source, and associated run script.
clang50: note: diagnostic msg: 
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang50: note: diagnostic msg: /tmp/secp256k1-a76f04.c
clang50: note: diagnostic msg: /tmp/secp256k1-a76f04.sh
clang50: note: diagnostic msg:

**Comment by glslang** [comment]
As a further note we had no issues on r14 while compiling this code.

**Comment by pirama-arumuga-nainar** [comment]
I was able to reproduce this.  https://bugs.llvm.org/show_bug.cgi?id=33424 is the upstream bug with a simplified test case.
