### ISSUE TITLE
Add support for Kotlin/Native to the NDK, when it gets stable

### ISSUE THREAD

**Issue by pjmlp** [android-ndk/ndk#427]
Now that Kotlin has become an official Android language, and given that the backed is based in LLVM, just like clang, it would be an improvement to NDK developer experience by supporting it.

The rationale would be making it easier to write the complete application in Kotlin, regardless of the parts being executed at ART or NDK level, even with the possible differences regarding memory management or available libraries.

**Comment by DanAlbert** [comment]
Let's make sure C++ works before we take on any new languages.

**Comment by kmshih** [comment]
Dan's definitely right that we wouldn't do this right now.. but what are you looking to accomplish with Kotlin in the NDK that you cannot do with the existing Kotlin support?  You can already write your application in Kotlin, except for the extent to which you explicitly prefer to use the C++ or Java languages.

**Comment by DanAlbert** [comment]
I assume it's a performance concern?

**Comment by DanAlbert** [comment]
To clarify: it's unlikely that performance would be any different with Kotlin Native (you'll probably see better perf with normal Kotlin, for that matter).

**Comment by pjmlp** [comment]
Nothing special just wanted to point out the issue, with hope that Kotlin could eventually be a possibility also for the NDK.

As mentioned on the ticket this would allow to easily move the code between Java and NDK space, without having to rewrite it.

As for the NDK I am perfectly fine with C++, just would like for the APIs to be more C++ friendly instead of C like and access to device libraries like libpng or Skia, instead of being forced to increase APK size or going through JNI.

But that doesn't belong on this issue anyway.

Perfectly fine with having this issue closed.
