### ISSUE TITLE
Clang crashes when compiling for armeabi

### ISSUE THREAD

**Issue by Abestanis** [android-ndk/ndk#429]
#### Description

I wanted to compile [tcl](https://en.wikipedia.org/wiki/Tcl) for armeabi, but clang crashes:

```
[armeabi] Compile thumb  : tcl <= tclTest.c
Wrote crash dump file "C:\Users\SEBAST~1\AppData\Local\Temp\clang.exe-afae09.dmp"
0x0000000001D48735 (0x0000000003B8D280 0x0000000003B8D3A0 0x0000000003B8D740 0x00000000001C0000)
0x0000000001D47B6D (0x0000000000000003 0x0000000000000000 0x0000000003B8D3D8 0x0000000000000190)
0x0000000001D4D446 (0x0000000005FD5538 0x0000000000000010 0x0000000006CAC9B8 0x0000000000000040)
0x0000000001D5037C (0x0000000003B8D9B0 0x00000000065F0438 0x0000000006896CF8 0x0000000006D8DA80)
0x0000000001D53097 (0x0000000003B8DD60 0x0000000000000005 0x0000000003B8DD90 0x00000000023E0834)
0x00000000023E3214 (0x00000000042B7530 0x0000000006DC87F0 0x00000000065C0920 0x0000000000000001)
0x00000000023E32E3 (0x0000000006171928 0x00000000042B7530 0x00000000042B7548 0x0000000000000000)
0x00000000023E3DE5 (0x0000000003B8E2C0 0x000000000135E8FD 0x0000000000000000 0x0000000003B8DFA0)
0x00000000006E3BF2 (0x0000000003B8E470 0x00000000009C7A6D 0x00000000042650D0 0x0000000000000000)
0x00000000028A8C02 (0x0000000004390000 0x000000000676BBB8 0x000000000000001B 0x000000000000000B)
0x0000000000932867 (0x0000000003B8E6D0 0x0000000004277C00 0x000000000427BAE0 0x00007FF999CECFB6)
0x000000000087E221 (0x0000000002CCF4D8 0x000000000000000D 0x0000000002CCF4D8 0x00000000036BF7FF)
0x000000000045C916 (0x000000000000000A 0x0000000002A91256 0x0000000000000008 0x0000000004276350)
0x0000000000438905 (0x0000000000000000 0x0000000003B80000 0x000000000265BDB0 0x0000000002A91256)
0x00000000004093C4 (0x0000000004274180 0x00000000043988D0 0x0000000004274900 0x0000000004274500)
0x0000000000402948 (0x0000000000000001 0x0000000000000000 0x000000000009C320 0x000000000000014A)
0x0000000002A93610 (0x000000000000008A 0x000000000000001B 0x0000000000000000 0x0000000000000000)
0x00000000004013B5 (0x0000000000000000 0x0000000000000000 0x0000000000000000 0x0000000000000000)
0x00000000004014E8 (0x0000000000000000 0x0000000000000000 0x0000000000000000 0x0000000000000000)
0x00007FF997488364 (0x0000000000000000 0x0000000000000000 0x0000000000000000 0x0000000000000000), BaseThreadInitThunk() + 0x14 bytes(s)
0x00007FF999D170D1 (0x0000000000000000 0x0000000000000000 0x0000000000000000 0x0000000000000000), RtlUserThreadStart() + 0x21 bytes(s)
clang.exe: error: clang frontend command failed due to signal (use -v to see invocation)
Android clang version 5.0.300080  (based on LLVM 5.0.300080)
Target: armv5te-none-linux-android14
Thread model: posix
InstalledDir: D:\ProgramData\Android\sdk\ndk-bundle\toolchains\llvm\prebuilt\windows-x86_64\bin
clang.exe: note: diagnostic msg: PLEASE submit a bug report to http://llvm.org/bugs/ and include the crash backtrace, preprocessed source, and associated run script.
clang.exe: note: diagnostic msg:
********************

PLEASE ATTACH THE FOLLOWING FILES TO THE BUG REPORT:
Preprocessed source(s) and associated run script(s) are located at:
clang.exe: note: diagnostic msg: C:\Users\SEBAST~1\AppData\Local\Temp\tclTest-2d75b8.c
clang.exe: note: diagnostic msg: C:\Users\SEBAST~1\AppData\Local\Temp\tclTest-2d75b8.sh
clang.exe: note: diagnostic msg:

********************
make: *** [NDK-Temp/local/armeabi/objs/tcl/generic/tclTest.o] Error 1
```

It does not crash when I compile the same sources for the other abis.
tclTest.c is not the only file producing a crash, if I exclude it from the build tclTestObj.c tclTestProcBodyObj.c tclThreadTest.c and tclUnixTest.c will also cause clang to crash.

Here are the sources to reproduce the crash as well es the complete output and the crash files:
[ClangCrashRepo.zip](https://github.com/android-ndk/ndk/files/1089905/ClangCrashRepo.zip)

I also managed to remove a lot of unnecessary code and compiler arguments. This is the smallest I could make it, if I remove anything else, the error does not show up:
[ClangCrashRepoSingle.zip](https://github.com/android-ndk/ndk/files/1089907/ClangCrashRepoSingle.zip)

#### Environment Details

* NDK Version: 15.0.4075724
* Build sytem: ndk-build
* Host OS: Windows 10
* Compiler: Clang
* ABI: armeabi
* NDK API level: 14

**Comment by DanAlbert** [comment]
@Abestanis: do you have instructions for building Tcl with the NDK? @enh has been trying a ton of open source projects to try to find the sharp edges for building things with the NDK, and I don't think Tcl was on his list.

**Comment by Abestanis** [comment]
Well, I pretty much just downloaded the [sources](https://sourceforge.net/projects/tcl/files/Tcl/), handcrafted an Android.mk and a tclConfig.h and tweaked them until it compiled.
The files can be found in ClangCrashRepo.zip.

**Comment by DanAlbert** [comment]
Yeah, the zip you uploaded should be enough to repro the crash. Was just wondering how to go about building this ourselves so we can fix any portability issues.

**Comment by pirama-arumuga-nainar** [comment]
Constant hoisting, enabled by -Os, exposes an issue in the backend.  Filed upstream bug: https://bugs.llvm.org/show_bug.cgi?id=33538.

**Comment by Abestanis** [comment]
@pirama-arumuga-nainar Thank you for the fast investigation!

**Comment by pirama-arumuga-nainar** [comment]
Sorry about the noise while I tried unsuccessfully to assign this to @leeleo3x.

@leeleo3x has a fix for this at https://reviews.llvm.org/D34576.  We'll pull in the fix the next time Clang is updated.

**Comment by Abestanis** [comment]
@pirama-arumuga-nainar Awesome! Thank you very much!

**Comment by Leeleo3x** [comment]
Sorry for the late update. I was having a problem uploading the patch. The patch rL306704 was submitted and will be available next time Clang is updated.

**Comment by DanAlbert** [comment]
Unfortunately Android hasn't finished with the Clang update yet, and this has been holding r16 up long enough. This is going to have to wait for r17.

**Comment by jsutdolph** [comment]
Do you have a work-around? I have a customer who wants an armeabi build of my library

**Comment by enh** [comment]
An earlier comment said this was tickled by -Os, so not using -Os should help.

**Comment by DanAlbert** [comment]
Better yet, just stop building for ARM5 :) Play store can tell you how many more devices your arm5 APK is reaching than your ARM7 one.

**Comment by kneth** [comment]
How will Play Store react when you remove an architecture? Can you publish the new version as an upgrade or do you have to publish a brand new app?

**Comment by Falken42** [comment]
Google Play doesn't place any restrictions on the native architectures inside an .apk, so you can remove/add them at will and simply push out a updated version.  I once had an odd crash bug (of my own fault) in arm64-specific code and temporarily removed that arch while I worked on a fix.

**Comment by alexcohn** [comment]
@kneth: from devices incompatible with ARM7 you will see the older version in Play Store.

**Comment by kneth** [comment]
@alexcohn Thank you for clarifying. We had users who didn't wanted to upgrade to Realm Java 2.0.0 because of that: https://github.com/realm/realm-java/issues/3506#issuecomment-252805533

**Comment by DanAlbert** [comment]
Obsolete with the removal of armeabi.
