### ISSUE TITLE
r11 clang: undefined reference to 'dladdr'

### ISSUE THREAD

**Issue by osfans** [android-ndk/ndk#43]
/usr/local/google/buildbot/out_dirs/aosp-ndk-r11-release/build/tmp/build-5996/build-libc++/ndk/sources/cxx-stl/llvm-libc++/../llvm-libc++abi/libcxxabi/src/Unwind/AddressSpace.hpp:448: error: undefined reference to 'dladdr'

```
NDK_TOOLCHAIN_VERSION := clang
APP_PLATFORM := android-4
APP_STL := c++_static
```

**Comment by dimitry-** [comment]
dladdr was introduced in android-8 (arm) and android-9 for x86 and mips. Try compiling against android-9 instead of android-4. Unless you need your code to work on the devices with android version < 8 in which case - there is no dladdr, and you will have to work around this.

**Comment by osfans** [comment]
OK,  thanks!

**Comment by DanAlbert** [comment]
Also note that android-4 is no longer supported. The earliest supported version is android-9.
