### ISSUE TITLE
Clang's STL not compatible with API less than 21

### ISSUE THREAD

**Issue by rcdailey** [android-ndk/ndk#430]
#### Description

Arch: armeabi-v7a
Toolchain: clang
STL: shared C++ stl (llvm)
API level: 15

Using the specified settings above, it seems that clang's STL won't work since the sysroot headers are missing important symbols that are only introduced in API 21. I noticed many of these compiler errors when building Boost for android.

Is there a workaround to allowing Clang's STL be used for API levels lower than 21? Am I misunderstanding the problem?

**Comment by DanAlbert** [comment]
The libc++ test suite says otherwise. Can you provide an example?

**Comment by alexcohn** [comment]
Maybe the point is that both **libc++** and **boost** must be built for same API level. You can't use API-15 STL with boost compiled for API-21, and vice versa.

The other side of this story is that some features of **boost** may require symbols available for API-21 and higher.

**Comment by DanAlbert** [comment]
You *should* be able to do that as long as your `minSdkVersion` is 21.

**Comment by rcdailey** [comment]
Closing, not able to reproduce ATM. If I can get it to happen again I'll reopen. Sorry for the confusion.

**Comment by rcdailey** [comment]
Also our min SDK is 15, not 21. I've run into a lot of problems with that in the past since if you grep the NDK directory for missing symbols, they're all introduced in 21.

Again if I run into the issue again I'll reopen, but it sounds like I'm getting confirmation that most stuff won't work with API 15 since it's missing core stuff.
