### ISSUE TITLE
llvm no llc tool, ndk android-ndk-r11c/toolchains/llvm/prebuilt/darwin-x86_64/bin

### ISSUE THREAD

**Issue by radxe** [android-ndk/ndk#432]
Hello, After ndk r11, r12,r13,..., I can't find the llc command line tool, from like android-ndk-r11c/toolchains/llvm/prebuilt/darwin-x86_64/bin , there are llvm-link, llvm-as, but no llc, 
and which is difference between clang and clang++?
my question is where I can find the llc, if no, which command line should I use?

thanks!

**Comment by stephenhines** [comment]
We don't really distribute llc as part of the NDK. The NDK is really intended as a C/C++ compiler, and those other commands are there for use as part of LTO. llc is mostly a debugging tool for LLVM. The difference between clang and clang++ is nothing really, although clang++ defaults to C++ compilation, while clang is for C compilation (of course file extensions can force it down a different path too). For C/C++, please use clang/clang++.
