### ISSUE TITLE
where can I find the llc from ndk r14 llvm?

### ISSUE THREAD

**Issue by radxe** [android-ndk/ndk#434]
Hello, from ndk r10e, we can find the llc from the llvm/bin, but after ndk r10e, I can't find the llc, I can find llvm-link, llvm-as, clang, clang++.
so my question is 1: where can I find the llc from the ndk r14 ?
                                2: what's difference between clang and clang++?
                               3: where is the llvm clang on android documents?

thanks!

**Comment by enh** [comment]
dupe of #432
