### ISSUE TITLE
default to -ffunction-sections -fdata-sections in clang?

### ISSUE THREAD

**Issue by DanAlbert** [android-ndk/ndk#436]
I noticed that ndk-build only has `-ffunction-sections` on by default and not `-fdata-sections`. I can fix that easily enough, but these flags are generally something people want, right? Should we just make them on by default in the driver (for Android at least)? Is this already the case?

The advantage of doing it in the driver is that we can fix all the build systems (even third party ones we don't control), rather than having to fix this in the four or five we own and hope people fix the ones we don't.

@stephenhines @pirama-arumuga-nainar: thoughts?

**Comment by pirama-arumuga-nainar** [comment]
I'm not sure if this is a good idea.  From what I could read, both `-ffunction-sections` and `-fdata-sections` can reduce final executable/shared-object size if `--gc-sections` is also passed to the linker.  For `--gc-sections` to work without surprises, the set of exported symbols be explicitly specified.  We may not want to force this on our developers.

Does ndk-build also specify `--gc-sections` to the linker?  If not, `-ffunction-sections` may increase sizes of object files (not sure about .so or executables).

**Comment by pirama-arumuga-nainar** [comment]
I take that back.  I think `--gc-sections` will still retain visible symbols and anything referenced from them when building a shared object.

So the question is whether we want to also include `--gc-sections` in addition?

**Comment by pirama-arumuga-nainar** [comment]
Stepping back, since these options seem to be common techniques to trim code and don't solve anything specific to Clang or Android, I feel the compiler shouldn't be setting this.  I am not sure if setting this in the ndk-build is right either.

**Comment by stephenhines** [comment]
There is already precedent for other ABIs to default to -ffunction-sections and -fdata-sections. Both CloudABI and WebAssembly turn these features on by default (https://clang.llvm.org/doxygen/CommonArgs_8cpp_source.html#l00366). I think most people do want this feature, but I also think that some people might get upset by having this change default value (particularly those people who are not using ndk-build). Any thoughts about that, Dan? Any interested NDK users have an opinion?

**Comment by kneth** [comment]
I think it makes sense to have `-ffunction-sections`, `-fdata-sections` and `--gc-sections` on by default. In order to take full advantage of it, you need to combine everything into one big `.so` file - and not everybody likes that idea.

**Comment by DanAlbert** [comment]
Should do this in the clang driver. Doubtful that if I were to upload the change today that it would make it back to Android in time for r18. Possible, but most likely r19.

**Comment by DanAlbert** [comment]
This was discussed more thoroughly in https://github.com/android-ndk/ndk/issues/748, and based on that discussion we probably shouldn't be lifting this into the driver. There's no one right answer so the build system really needs to be the one making the decision.

https://android-review.googlesource.com/c/platform/ndk/+/792619 at least brings our CMake toolchain in sync with ndk-build, but I don't think we should be altering the driver for this.
