### ISSUE TITLE
Missing header machine/cpu-features.h

### ISSUE THREAD

**Issue by suikki** [android-ndk/ndk#443]
#### Description
I'm trying to compile SDL_image (that contains the jpeg-9 library). It was working fine on NDK r14 but
after updating to NDK r15b compiling fails with:

    SDL_image/external/jpeg-9/jidctfst.S:17:10: fatal error: 'machine/cpu-features.h' file not found
    #include <machine/cpu-features.h>

I'm guessing this is due to to the new unified headers, but I have no idea if the header was removed on purpose or not.

#### Environment Details

* NDK Version: 15.1.4119039
* Build sytem: both ndk-build and cmake/gradle
* Host OS: Windows
* Compiler: Clang
* ABI: armeabi-v7a
* NDK API level: 14

**Comment by enh** [comment]
yes, the 32-bit arm <machine/cpu-features.h> was removed deliberately. users should use the standard __VFP_FP__ and __ARM_NEON__ macros provided automatically by the compiler instead.

the kernel's <asm/cpu-features.h> headers were also removed deliberately (they're not UAPI headers).

neither of these should be confused with <cpu-features.h> from the cpu-features module for _run-time_ feature detection, which is alive and well.
