### ISSUE TITLE
Is it possible to call RenderScript in NDK WITH "-frtti"

### ISSUE THREAD

**Issue by adhere** [android-ndk/ndk#444]
#### Description

I want to call RenderScript in NDK, and use cmake to manage the C++ code. I found a demo [Call_RenderScript_from_NDK](https://github.com/uelordi01/Call_RenderScript_from_NDK), which works. But for me, I need "-frtti" because of using protobuf in the project. If I change "-fno-rtti" to "-frtti" (which locating at the app/build.gradle file), I got " undefined reference to `typeinfo for android::RSC::BaseObj' " error too.

I had view this [ISSUE](https://github.com/android-ndk/ndk/issues/304) and this at stackoverflow [g-undefined-reference-to-typeinfo](https://stackoverflow.com/questions/307352/g-undefined-reference-to-typeinfo).

"This can also happen when you mix -fno-rtti and -frtti code. Then you need to ensure that any class, which type_info is accessed in the -frtti code, have their key method compiled with -frtti. Such access can happen when you create an object of the class, use dynamic_cast etc. "

So It is RenderScript libRScpp_static.a compiled with "-fno-rtti" ?
#### Environment Details

* NDK Version: 15.1.4119039
* Build sytem:cmake
* Host OS: Ubuntu 14.04
* Compiler: Clang

Here is my build.gradle file:

apply plugin: 'com.android.application'

android {
    compileSdkVersion 26
    buildToolsVersion "26.0.0"
    defaultConfig {
        applicationId "learn.renderscript.ndk"
        minSdkVersion 21
        targetSdkVersion 26
        renderscriptTargetApi 19
        renderscriptSupportModeEnabled true
        renderscriptNdkModeEnabled true

        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
        externalNativeBuild {
            cmake {
//                cppFlags "-std=c++11 -frtti -fexceptions"
                cppFlags "-std=c++11 -fno-rtti -fexceptions"
            }
        }

        ndk {
            // Specifies the ABI configurations of your native
            // libraries Gradle should build and package with your APK.
            abiFilters  'armeabi-v7a'
        }

    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    externalNativeBuild {
        cmake {
            path "CMakeLists.txt"
        }
    }
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    compile 'com.android.support:appcompat-v7:26.+'
    compile 'com.android.support.constraint:constraint-layout:1.0.2'
    testCompile 'junit:junit:4.12'
}

**Comment by adhere** [comment]
I test this demo [RenderScriptNDK](https://github.com/EE202B/RenderScriptNDK). Add "-frtti"  LOCAL_CFLAGS := -std=c++11 -frtti (add to Android.mk file). It is success to compile. So, It is the problem of cmake to manage the C++ source or I should put add some other so to CMakeLists.txt?
I try`find $NDK_ROOT_DIR -type f | xargs grep -i "BaseObj"` and try to add the match so to  CMakeLists.txt, but I still can't solve that.

**Comment by miaowang14** [comment]
Thanks for reporting this.

AFAIK, RenderScript NDK APIs currently only support ndk-build. We haven't tried using CMake for RenderScript, but we are looking into it. I would suggest you take a try with ndk-build, as a workaround for RenderScript related modules?

**Comment by adhere** [comment]
Thanks for your suggestions.
But I hopefully use CMake to manage my C++ code. With CMake, I can debug from Java code to C++ code step by step(Maybe with ndk-build can also do that? I have not found a demo. if that works. I will use that).
It seems that is the problem of CMake which can't parse the dependencies properly. Because both ndk-build or CMake, they finally call Clange to compile the code(right?).

**Comment by adhere** [comment]
@miaowang14 With mixing ndk-build and CMake, now I call build my project and debug properly. Later I will post the configuration. Thanks!

**Comment by adhere** [comment]
@miaowang14 Using ndk-build to build RenderScript, while the RenderScript filename with UpperCase, that alse have problems. Such as, while the RenderScript filename is Mone.rs, the intermediate bc file will name "mono.bc". So it will be fail. `E/bcc     (30154): Failed to load bitcode from path ./obj/local/armeabi-v7a/objs/hellocomputendk/Mono.bc! (No such file or directory)`. 
Actually It generates a file "./obj/local/armeabi-v7a/objs/hellocomputendk/mono.bc"

**Comment by miaowang14** [comment]
@adhere The problem with UpperCase .rs files definitely looks like a bug.
I filed an internal bug tracking this issue. Thanks for reporting this.

(Since this bug is probably irrelevant with ndk-build / CMake, could you also file a github bug tracking this? and just assign it to me)

**Comment by adhere** [comment]
I just create a demo, [NDKCallRenderScriptDemo](https://github.com/adhere/NDKCallRenderScriptDemo). Using the ndk-build to build RenderScript file and put then as the CMake dependencies, It can debug step by step.
Thank you @miaowang14 !

**Comment by miaowang14** [comment]
@adhere Thank you for the demo. It looks really good.

**Comment by LiewJunTung** [comment]
I like to thank @adhere for the working sample. But I like to know if we will get RenderScript NDK APIs for CMake without going through ndk-build? @miaowang14
