### ISSUE TITLE
Android NDK r15 not supported by CMake 3.6.4111459

### ISSUE THREAD

**Issue by Ekt0s** [android-ndk/ndk#446]
Hello!

With my team, we've had faced some troubles while building one of our project that uses **Android NDK** (version 13r).

As soon as my teammates installed/updated their versions of the NDK to the version 15, and the version cmake bundled within *Android Studio*, the application built crash automatically when it calls one of the JNI methods embedded with our c++ library.

We didn't really look under the hood why, but it seems the libraries (.so files) are packaged within the apk but not installed on the devices once the apk installed.

----------
**The trick we found:**

To make it work, you can change the version of the NDK used by cmake 

    # In  ~ANDROID_HOME/cmake/3.6.4111459/android.toolchain.cmake
    #
    # Change this
    set(ANDROID_NDK_REVISION 12)

    # Into this
    set(ANDROID_NDK_REVISION 15)

**Comment by DanAlbert** [comment]
> We didn't really look under the hood why, but it seems the libraries (.so files) are packaged within the apk but not installed on the devices once the apk installed.

All the same files in exactly the same places? If there's any difference at all you might be installing a different architecture (i.e. arm64 instead of arm32, or even arm5 instead of arm7).

Either way, without a test case or a specific missing (or new) file in the out directory, there's nothing I can investigate here.

**Comment by ketanm** [comment]
I had filed one defect earlier about correct cmake version usage. Make sure you are using - Android/sdk/cmake/3.xxxx if you are writing your own CMake scripts and building NDK C++ plugin, that script is actually maintained and has correct NDK version.

**Comment by DanAlbert** [comment]
Oh, re-reading the original post, you're using the wrong cmake toolchain. Use the one in the NDK.

`cmake -DCMAKE_TOOLCHAIN_FILE=$NDK/build/cmake/android.toolchain.cmake`

The one in the cmake install in the SDK is ancient and is only there for supporting pre-r13 NDKs.
