### ISSUE TITLE
Invalid toolchain path for Windows x86

### ISSUE THREAD

**Issue by seongsoosim** [android-ndk/ndk#45]
The function of 'host-toolchain-path' defined in 'init.mk' uses $(HOST_TAG64) variable.
And this value represents as "windows-x86" on Windows 32 bit OS.
The problem is that all the toolchain doesn't have 'windows-x86' directory in android-ndk-r11b-windows-x86.zip  package. It has only 'windows' directory.
So, it make a compile failure.

When I changed the directory name from "\toolchains\aarch64-linux-android-4.9\prebuilt\windows" to " "\toolchains\aarch64-linux-android-4.9\prebuilt\windows-x86", then the building was successful.

**Comment by DanAlbert** [comment]
https://android-review.googlesource.com/#/c/210174/

**Comment by DanAlbert** [comment]
My patch is no good. Will have another once my machine isn't bogged down running the test suite.
