### ISSUE TITLE
NDK Clang compile times are much slower than expected

### ISSUE THREAD

**Issue by erikmchut** [android-ndk/ndk#450]
#### Description

The prebuilt version of clang/llvm that ships with the NDK compiles slowly, taking 15x longer compared to the clang/llvm included in XCode.  This was discovered empirically, after noticing that Android builds take surprisingly long to build the same sources that we build for iOS.

To provide a benchmark, I timed compilation of a small piece of our build -- a CBLAS library containing ~150 .c sources.

Using Clang in the NDK:
  - this takes ~7min to compile for armeabi-v7a

Using Clang that is installed with XCode
  - takes 25s to build for armv7 (iOS)

#### Environment Details

Not all of these will be relevant to every bug, but please provide as much
information as you can.

* NDK Version: 15.0.4075724
* Build system: bazel, with custom CROSSTOOL rules that provide full Android support
* Host OS: Mac
* Compiler:  Clang
* ABI: armeabi-v7a  and arm64-v8a
* STL: libc++
* NDK API level: 23
* Device API level: 23

**Comment by pirama-arumuga-nainar** [comment]
Can you share more details on how to reproduce?  Here's what I tried:

With cblas.tgz from http://www.netlib.org/blas/#_cblas:

> $ cd CBLAS/src
> $  find . -iname "*.c" | wc -l
>      145
> $  find . -iname "*.o" | wc -l
>      0
> $ time for f in `find . -iname "*.c"`; do /Volumes/android/aosp/prebuilts/clang/host/darwin-x86/clang-4053586/bin/clang.real -O3 -DADD_ $f -I../include -c -I /Volumes/android/aosp/prebuilts/ndk/r10/platforms/android-23/arch-arm/usr/include -target armv7a-linux-android ; done
> ...
> <bunch-of-warnings>
> real    0m5.485s
> user    0m3.338s
> sys     0m1.264s
> 
> $  find . -iname "*.o" | wc -l
>      145
>

**Comment by DanAlbert** [comment]
Are you using the same build system for both targets? Both on Mac, right? (I assume so, but just checking)

Finding a specific compile step that is slower would help narrow this down. If there isn't one, then it's not the compiler.

**Comment by Zingam** [comment]
Gradle + cmake even for the Hello world is really, really much slower than anything else.

**Comment by stephenhines** [comment]
Can you time just the compile portion of the command with gradle+cmake (and/or give us a reproducible command line + sample file)? Perhaps this is actually a gradle issue, or something with the flags that you are using.

**Comment by DanAlbert** [comment]
Yeah, "gradle is slow" is a pretty common refrain. Why do you suspect that it's the compiler?

**Comment by erikmchut** [comment]
@pirama-arumuga-nainar and @DanAlbert thanks for looking into this. I can reproduce your timing tests, which appear to exonerate the NDK as the source of my build timing issues.

I'm closing this bug as it is not longer the right venue, but for anyone encountering similar issues, it looks like we are running into a potential issue with Bazel that surprisingly only repros with our Android crosstool.

------------------
For anyone interested, here is our Bazel profile information for an Android Build -- 8.7s compile, 3.5s link, and yet a 343.9s total build!?

bazel profile:
```
Execution Phase Information:

Total preparation time	15.5 ms
Total execution time	343.866 s
Total finish time	24.0 ms
Action dependency map creation	0.00 ms
Actual execution time	343.866 s
Total time (across all threads) spent on:
Type		Total	Count	Average
ACTION		0.01%	154	1.73 ms
ACTION_CHECK	0.00%	1	13.1 ms
ACTION_EXECUTE	22.11%	154	3.403 s
ACTION_UPDATE	0.00%	152	0.02 ms
ACTION_COMPLETE	0.00%	154	0.23 ms
INFO		0.00%	1	0.00 ms
VFS_STAT	8.40%	21974880 0.01 ms
VFS_DIR		0.38%	85836	0.11 ms
VFS_READLINK	0.47%	1478287	0.01 ms
VFS_MD5		0.13%	410	7.39 ms
VFS_DELETE	10.82%	1072831	0.24 ms
VFS_OPEN	0.00%	308	0.16 ms
VFS_READ	0.00%	304	0.01 ms
VFS_WRITE	0.00%	156	0.11 ms
WAIT		0.25%	295	19.9 ms
SKYFRAME_EVAL	14.50%	1	343.690 s
SKYFUNCTION	42.92%	25029	40.6 ms
Critical path (12.359 s):
Id	Time	Share	Description
34697	3.571 s	28.89%	action 'Linking third_party/clapack/libcblas.a'
34696	8.788 s	71.10%	action 'Compiling third_party/clapack/BLAS/SRC/dsymv.c'
34695	0.08 ms	0.00%	null for //third_party/clapack cblas
34694	0.90 ms	0.01%	null for //third_party/clapack clapack-common-hdrs
```

**Comment by jmgao** [comment]
Can you [file this against bazel](https://github.com/bazelbuild/bazel/issues/new)?
