### ISSUE TITLE
android/sensor.h: ASensorManager_getInstanceForPackage() should be guarded inside ANDROID_O?

### ISSUE THREAD

**Issue by ggfan** [android-ndk/ndk#451]
--------------------------------------------------------------------------------

#### Description
(unified headers related)
android/sensor.h, the following 2 functions are meant for android-o only?: 
__attribute__ ((deprecated)) ASensorManager* ASensorManager_getInstance();
ASensorManager* ASensorManager_getInstanceForPackage(const char* packageName);

it was not inside platforms/android-24 and before. in earlier platforms, sensor.h having just
  ASensorManager* ASensorManager_getInstance();

this affects building applications for platforms earlier than android-O with NDK-r15+: on those platforms, there is no ASensorManager_getInstanceForPackage() to use;  but if uses ASensorManager_getInstance(), NDK will complain for deprecation, which may not be intentional.

put them under API level guard would help:
 #if __ANDROID_API__ >= 26
  __attribute__ ((deprecated)) ASensorManager* ASensorManager_getInstance();
ASensorManager* ASensorManager_getInstanceForPackage(const char* packageName);
#else 
 ASensorManager* ASensorManager_getInstance();
#endif 

#### Environment Details

Not all of these will be relevant to every bug, but please provide as much
information as you can.

* NDK Version: NDK-r15x, NDK-r16.
* Build sytem: cmake
* Host OS: Mac
* Compiler: clang.
* ABI: unified headers under sysroot/usr/include/android/sensor.h
* STL: N/A
* NDK API level:  < 26
* Device API level: n/A

**Comment by DanAlbert** [comment]
Could you file this against the platform? We don't own the frameworks headers; we just ship them.
