### ISSUE TITLE
document all the intricacies of `_FILE_OFFSET_BITS` for LP32

### ISSUE THREAD

**Issue by DanAlbert** [android-ndk/ndk#453]
`_FILE_OFFSET_BITS=64` was completely ignored in the deprecated headers, and its behavior can be pretty non-obvious for anything but the latest API level (for r15, some functions are just broken, for r16, they won't be able to build, etc). We should document all this since a handful of people have been bitten by this lately.

**Comment by DanAlbert** [comment]
@enh has a draft of this here: https://android-review.googlesource.com/c/434181/

Assign it to me once it's submitted so I remember to get it to a more visible place.

**Comment by enh** [comment]
(submitted)

**Comment by alexcohn** [comment]
Note https://github.com/madler/zlib/issues/254

**Comment by DanAlbert** [comment]
Added to our r16 blog post draft. The 32-bit ABI bugs doc is already linked from our ABIs doc.
