### ISSUE TITLE
[?] collecting native crash stacktrace

### ISSUE THREAD

**Issue by andreya108** [android-ndk/ndk#454]
Sorry, this is not actually NDK issue, but it is closely connected, and since there are NDK developers here I hope to get an answer to my question, since it can be helpful for many other NDK users.

So, what is the best method to gather native crash stack trace in the recent android versions?

On pre-M there was a possibility to read system logcat, where debuggerd place stacktrace, but on the newer androids one cannot get system messages.

Moreover, we cannot use popular crash reporting systems like crashlytics and firebase (prohibited by our company's NDA policy).

On the older android versions (32-bit) we had a solution utilizing libcorkrew library for unwinding (used custom signal handlers), but it is obsolete and does not preset for arm64.

The goal is pretty simple - get native crash stacktrace (debuggerd format is very desirable since it is supported by ndk-stack) on the recent android versions (M,N,O) to add it to problem report generated by an application.

**Comment by DanAlbert** [comment]
The crash should be in logcat. @enh: is that still off by default for user apps unless they do the prctl thing?

**Comment by jmgao** [comment]
They're trying to get the logs from inside the app, which on M+, only lets you see logcat messages sent by the app. (IIRC, the check is UID-based, so this approach probably just works on O?)

**Comment by enh** [comment]
your crashes should be visible in the Play Store developer console.

**Comment by andreya108** [comment]
Unfortunately, 99% of our clients use version not distributed via Play Store since our country laws prohibit publishing strong cryptography to the foreign markets, adopted version (published in Play Market) use only ~1% of our clients, but that is not enough to cover issues.
So, custom problem reporting is the only choice for us currently.

**Comment by andreya108** [comment]
I've found a suitable solution: google breakpad library. The only drawback is compatibility - it could be built only for API 21+, but it is ok, just another reason to drop Android 4.x support.
