### ISSUE TITLE
NdkMediaCodec.h: Issue with off_t in signature and use of __USE_FILE_OFFSET64

### ISSUE THREAD

**Issue by koying** [android-ndk/ndk#459]
#### Description

`NdkMediaCodec.h` defines:
```
media_status_t AMediaCodec_queueInputBuffer(AMediaCodec*,
        size_t idx, **off_t** offset, size_t size, uint64_t time, uint32_t flags);
media_status_t AMediaCodec_queueSecureInputBuffer(AMediaCodec*,
        size_t idx, **off_t** offset, AMediaCodecCryptoInfo*, uint64_t time, uint32_t flags);
```

When arm32 is built with `__USE_FILE_OFFSET64`, the `off_t`'s above are defined as `off64_t`, leading to a non functional MediaCodec (no crashes, though).

Manually changing the off_t to `size_t`workarounds the issue (haven't tried arm64, yet, but it *should* work, too).

#### Environment Details

Not all of these will be relevant to every bug, but please provide as much
information as you can.

* NDK Version:15.1.4119039, unified headers
* Build sytem: Standalone
* Host OS: Linux Mint x86_64
* Compiler: GCC
* ABI: arm32
* STL: gnu
* NDK API level: 21
* Device API level: 24

**Comment by DanAlbert** [comment]
Good timing, was just getting to cherry-picking `_FILE_OFFSET_BITS=64` fixes into r15c. I'll include a fix for this as well.

I grepped the sysroot for any other cases of this outside libc, looks like we have one in asset_manager.h too.

**Comment by DanAlbert** [comment]
NdkMediaCodec.h: https://android-review.googlesource.com/c/437595/
asset_manager.h: https://android-review.googlesource.com/c/437635/
plumbing: https://android-review.googlesource.com/c/437636/

**Comment by koying** [comment]
Thanks already.

Am I correct reading that the chosen solution is to enforce undef'ing __USE_FILE_OFFSET64?
Commented on Gerrit.

Regarding the asset manager part, do you confirm the 64 bits version are available on arm32 as well?
Otherwise, that probably won't work...

**Comment by enh** [comment]
no, asset_manager.h actually has both off_t and off64_t variants, so we can make _FILE_OFFSET_BITS=64 do the right thing there. for NdkMediaCodec.h, we're suggesting doing the same as we do for the bionic headers, where you get everything you can have (which in this case means you _lose_ the off_t functions, because there still aren't off64_t variants).

**Comment by koying** [comment]
Ok, but it make little sense to remove just those 2 functions, though, as it makes the api unusable.
Those mandatory functions being "hidden" will probably scratch more than a few people heads, so I'd suggest to the `#error`path altogether, whith an explicit message.

Now, there is still the `size_t`path ;)

**Comment by enh** [comment]
yeah, that's why we need to chase down the API owner. if they are mandatory then, yes, #error if _FILE_OFFSET_BITS=64 is defined for LP32 probably makes more sense (and is certainly closer to previous behavior).
