### ISSUE TITLE
ndk-gdb.py script is not working on Windows

### ISSUE THREAD

**Issue by dosvidos** [android-ndk/ndk#46]
On Windows ndk-gdb.py script from android-ndk-r11b always fails with the following error message:
c:\wrk\android-ndk-r11b\prebuilt\windows\bin>python ndk-gdb.py --launch-list --adb c:\wrk\android-sdk\platform-tools\adb.exe
WARNING: Failed to find jdb on your path, defaulting to --nowait
Traceback (most recent call last):
  File "ndk-gdb.py", line 704, in <module>
    main()
  File "ndk-gdb.py", line 583, in main
    args.props = device.get_props()
  File "c:\wrk\android-ndk-r11b\python-packages/adb/device.py", line 459, in get
_props
    raise RuntimeError('invalid getprop line: "{}"'.format(line))
RuntimeError: invalid getprop line: ""
ndk-gdb.cmd script located in root NDK directory fails with another error:
$ ./ndk-gdb.cmd
  File "C:\wrk\android-ndk-r11b\prebuilt\windows\bin\ndk-gdb", line 2
    NDK_BIN_DIR=$(dirname $0)
                ^
SyntaxError: invalid syntax

**Comment by sosocanfix** [comment]
i have the same problem on windows,how could i fix it?
