### ISSUE TITLE
NDK samples lock-up

### ISSUE THREAD

**Issue by PelicanPete** [android-ndk/ndk#461]
#### Description

The Teapot sample and the Native-Activity exhibit the same problem.   If the programs are opened and closed a few times using the Square symbol, then they lock-up.  

The Teapot sample doesn't respond to pinch and flick, but it still spins, and the Native-Activity sample doesn't respond to taps and the colors freeze.  In both cases restarting the App fixes it.

This pre-built APK also locks on my 2 phones and tablet in the same way as explained above.  It says updated Jun 1, but can't find what year: 

https://github.com/joakim-noah/android/releases/tag/tea

Another broken tea pot in the Google App Store at this link:

 https://play.google.com/store/apps/details?id=com.duongnx.ndk.examples

My own builds using MSVS have the same problem as above.
Thanks.

**Comment by DanAlbert** [comment]
Probably refile this with the samples folks: https://github.com/googlesamples/android-ndk. This sounds like either a samples issue or a platform bug (and either way, the samples should probably be accounting for it).
