### ISSUE TITLE
For mips64 platform getting  undefined reference to `Backtrace::Create(int, int, BacktraceMap*)' 

### ISSUE THREAD

**Issue by satishc4u** [android-ndk/ndk#464]
#### Description

I am using Android studio to compile native .cpp source. Using CMakeLists.txt in gradle file to compile. I want to compile native executable and native library for both armeabi-v7a and mips64 platforms, the compiled native executable(testservice) and library(libnative-lib.so) will  depend on few prebuilt libraries (libcutils.so, libutils.so and libbinder.so ).

I am able to generate executable and library for armeabi-v7a platform. But for mips64 platform it is throwing the following error ,

 **.**./../../../src/main/JniLibs/mips64/libutils.so: undefined reference to `Backtrace::Create(int, int, BacktraceMap*)'**

  [2/2] Linking CXX executable testservice
  FAILED: : && /android-ndk-r15b/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++  --target=mips64el-none-linux-android --gcc-toolchain=/android-ndk-r15b/toolchains/mips64el-linux-android-4.9/prebuilt/linux-x86_64 --sysroot=/android-ndk-r15b/sysroot  -isystem /android-ndk-r15b/sysroot/usr/include/mips64el-linux-android **-D__ANDROID_API__=23 -g -DANDROID -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -fintegrated-as -Wa,--noexecstack -Wformat -Werror=format-security  -std=c++11 -fno-rtti -fexceptions -O0 -fno-limit-debug-info  -Wl,--exclude-libs,libgcc.a -**-sysroot eclipse/android-ndk-r15b/platforms/android-23/arch-mips64 -Wl,--build-id -Wl,--warn-shared-textrel -Wl,--fatal-warnings -Wl,--no-undefined -Wl,-z,noexecstack -Qunused-arguments -Wl,-z,relro -Wl,-z,now -Wl,--gc-sections -Wl,-z,nocopyreloc -pie -fPIE CMakeFiles/testservice.dir/src/main/cpp/testdaemon/libtestservice/src/testservice.cpp.o  -o testservice  ../../../../build/intermediates/cmake/debug/obj/mips64/libnative-lib.so ../../../../src/main/JniLibs/mips64/libutils.so ../../../../src/main/JniLibs/mips64/libcutils.so ../../../../src/main/JniLibs/mips64/libbinder.so ../../../../src/main/JniLibs/mips64/libtinycompress.so ../../../../src/main/JniLibs/mips64/libtinyalsa.so /android-ndk-r15b/platforms/android-23/arch-mips64/usr/lib64/liblog.so -lm "/android-ndk-r15b/sources/cxx-stl/gnu-libstdc++/4.9/libs/mips64/libgnustl_static.a" && :
  /android-ndk-r15b/toolchains/mips64el-linux-android-4.9/prebuilt/linux-x86_64/lib/gcc/mips64el-linux-android/4.9.x/../../../../mips64el-linux-android/bin/ld: warning: libbacktrace.so, needed by ../../../../src/main/JniLibs/mips64/libutils.so, not found (try using -rpath or -rpath-link)
  /eclipse/android-ndk-r15b/toolchains/mips64el-linux-android-4.9/prebuilt/linux-x86_64/lib/gcc/mips64el-linux-android/4.9.x/../../../../mips64el-linux-android/bin/ld: warning: libc++.so, needed by ../../../../src/main/JniLibs/mips64/libutils.so, not found (try using -rpath or -rpath-link)
  .**./../../../src/main/JniLibs/mips64/libutils.so: undefined reference to `Backtrace::Create(int, int, BacktraceMap*)'
  clang++: error: linker command failed with exit code 1 (use -v to see invocation)
  ninja: build stopped: subcommand failed.**

Find the attachment [CMakeLists_.txt]

[CMakeLists_.txt](https://github.com/android-ndk/ndk/files/1164910/CMakeLists_.txt)

**I have the following code in build.gradle file,**

externalNativeBuild {
            cmake {
                targets "native-lib","clmrservice"
                cppFlags "-std=c++11 -fno-rtti -fexceptions"
                //abiFilters 'armeabi-v7a','armeabi','mips'
                abiFilters 'armeabi-v7a', 'mips64'

            }
        }

externalNativeBuild {
        cmake {
            path "CMakeLists.txt"
        }
    }
    sourceSets {
        main {
            jniLibs.srcDir('src/main/JniLibs/')
        }
    }
#### Environment Details

* NDK Version:  15.1.4119039
* Build sytem: cmake 
* Host OS:  Linux. ubuntu 12.04
* Compiler: If GCC, check Clang before filing. GCC is no longer supported.
* ABI: 
* STL:
* NDK API level:
* Device API level:

**Comment by enh** [comment]
looks like you mismatched versions of libutils and libbacktrace (or you're missing libbacktrace completely and your arm libutils is too old to require it).
