### ISSUE TITLE
 undefined reference to 'typeinfo for xxx‘ when upgrade from r14 to r15

### ISSUE THREAD

**Issue by nangonghuang** [android-ndk/ndk#465]
after i upgrade ndk from r14 to r15 by Android Studio's sdkmanager,this error happened .When i retried to build with r14.compile finished with no error ,and no crash in apk runtime .
"xxx" is a class defined in .so/.a libs.When i check code in AS ,Code assist shows this method declared in header but not implement.

**Comment by DanAlbert** [comment]
There's nothing we can do without a test case.
