### ISSUE TITLE
mmap() declaration wrong for 32-bit targets with 64-bit off_t

### ISSUE THREAD

**Issue by oleavr** [android-ndk/ndk#468]
#### Description

When compiling a 32-bit target with `-D_FILE_OFFSET_BITS=64` this
results in the NDK's `mmap()` prototype not matching Bionic's, which
means the caller pushes a 64-bit value on the stack, whilst the callee
expects a 32-bit value there. This in turn means `mmap()` likely sees
a bogus `offset` argument and returns `MAP_FAILED`.

#### Environment Details

* NDK Version: 15.1.4119039
* Build system: Meson
* Host OS: Mac
* Compiler: Clang
* ABI: armeabi-v7a
* NDK API level: 14
* Device API level: 24

**Comment by oleavr** [comment]
Looks like another case of #459. /cc @DanAlbert

**Comment by enh** [comment]
actually #449 is a closer match. fixed in r15c. in the meantime, you should probably turn off _FILE_OFFSET_BITS if you're targeting API 14.

**Comment by oleavr** [comment]
Oops, missed that one – sorry about the dupe!
