### ISSUE TITLE
Simpleperf: exception when use command "python annotate.py -s"  for project 'SimpleExamplePureJava '.

### ISSUE THREAD

**Issue by LightSun** [android-ndk/ndk#469]
--------------------------------------------------------------------------------

#### Description

i want to study about simpleperf, but when i use the demo with commands in order.
i found a problem when i use cmd "python annotate.py -s ../demo/SimpleperfExamplePureJava" for project SimpleperfExamplesPureJava .  here is the log :

E:\study\simpleperf\scripts>python annotate.py -s ../demo/SimpleperfExamplePureJava
python.exe W 07-25 15:41:57  8460  7864 dso.cpp:357] binary_cache//system/lib64/libEGL.so doesn't contain symbol table
python.exe W 07-25 15:41:57  8460  7864 dso.cpp:357] binary_cache//system/lib64/libutils.so doesn't contain symbol table
python.exe W 07-25 15:41:57  8460  7864 dso.cpp:264] failed to read min virtual address of unknown: File not found
python.exe W 07-25 15:41:57  8460  7864 dso.cpp:360] failed to read symbols from unknown: File not found
addr2line: binary_cache\system/framework/arm64/boot.oat: File format not recognized
Traceback (most recent call last):
  File "annotate.py", line 675, in <module>
    main()
  File "annotate.py", line 671, in main
    annotator.annotate()
  File "annotate.py", line 319, in annotate
    self._convert_addrs_to_lines()
  File "annotate.py", line 376, in _convert_addrs_to_lines
    self.addr2line.convert_addrs_to_lines()
  File "annotate.py", line 86, in convert_addrs_to_lines
    self._convert_addrs_to_lines(dso_name, self.dso_dict[dso_name])
  File "annotate.py", line 107, in _convert_addrs_to_lines
    log_fatal("addr2line didn't output enough lines")
  File "E:\study\simpleperf\scripts\utils.py", line 56, in log_fatal
    raise Exception(msg)
Exception: addr2line didn't output enough lines

 --- command of  ' find annotated_files -name "MainActivity.java" ' also has problem.
log:
E:\study\simpleperf\scripts>find annotated_files -name "MainActivity.java"
拒绝访问 - ANNOTATED_FILES
找不到文件 - -NAME

#### Environment Details

Not all of these will be relevant to every bug, but please provide as much
information as you can.

* NDK Version: android-ndk-r12b-windows-x86_64
* Host OS: Windows 10 ,
* Device API level: nexus 6p with android 7.1

**Comment by DanAlbert** [comment]
> NDK Version: android-ndk-r12b-windows-x86_64

We didn't have simpleperf in this NDK version.

**Comment by LightSun** [comment]
from here : https://android.googlesource.com/platform/system/extras/+/master/simpleperf/README.md
it tell me can submit bug here.

**Comment by LightSun** [comment]
which version of ndk i should use ?

**Comment by enh** [comment]
> which version of ndk i should use ?

the answer to that is always "the latest", which is currently r15. but danalbert's point was actually "you say you're using the r12 version, but there was no simpleperf in r12, so you can't be".

**Comment by qchong** [comment]
The version of Simpleperf bundled in NDK r15 does not have the most up-to-date python scripts.

You can get the latest version of Simpleperf (including python scripts) from AOSP as a prebuilt:
`git clone https://android.googlesource.com/platform/prebuilts/simpleperf`

You can also find additional Simpleperf documentation on developer.android.com:
https://developer.android.com/ndk/guides/simpleperf.html

**Comment by yabinc** [comment]
I can't reproduce the problem. I guess you download simpleperf scripts directly from https://android.googlesource.com/platform/system/extras, even newer than prebuilts/simpleperf. I also tried addr2line in ndk r12b, it works fine for this example.
You can use --addr2line option to annotate.py to make sure it uses addr2line from ndk. It should be like below, but use path in your environment:
python annotate.py -s ../demo/SimpleperfExamplePureJava --addr2line C:\Users\splin\Desktop\simpleperf\android-ndk-r12b\toolchains\aarch64-linux-android-4.9\prebuilt\windows-x86_64\bin\aarch64-linux-android-addr2line.exe

If the error still happens, can you add one line before L107 to show the output. It helps us debugging:
log_debug("addr2line_path = %s, dso_path = %s, addrs = %s, stdoutdata = %s." % (self.addr2line_path, dso_path, addrs, stdoutdata)

You can also try skipping the error check as below. It may work.
#log_fatal("addr2line didn't output enough lines")
...
#assert addr_pos == len(addrs)

**Comment by LightSun** [comment]
@yabinc @all  I  use simpleperf scripts directly from [https://android.googlesource.com/platform/system/extras](https://android.googlesource.com/platform/system/extras) really, i will try as you see. Thanks for all of you.

**Comment by LightSun** [comment]
@yabinc  when i use this command 'python annotate.py -s ../demo/SimpleperfExamplePureJava --addr2line 
 '  .  happened  another error. see logs.
![2](https://user-images.githubusercontent.com/6840323/28600759-c4df1eba-71e6-11e7-916b-1ac40b27f5fc.png)

**Comment by yabinc** [comment]
They actually both successes. The error messages are all warning for missing shared libraries. And here we just want to annotate MainActivity.java, and it successes. And the last line shows annotate finish successfully.
I guess the original error was because the addr2line in your PATH doesn't support the options needed by annotate.py. It is fine when you use the addr2line contained in the ndk.

**Comment by LightSun** [comment]
@yabinc  oh, I see thanks.
