### ISSUE TITLE
x86_64 prebuilt libraries are not linking correctly

### ISSUE THREAD

**Issue by cmaster11** [android-ndk/ndk#47]
While building a x86_64 app, with following settings:

```
// Toolchain config
-DANDROID_TOOLCHAIN_NAME=x86_64-4.9 -DANDROID_ABI=x86_64

// CMake config
set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -Wall -O3 -march=x86-64 -msse4.2 -mpopcnt -m64 -mtune=intel -fPIC")
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wall -O3 -march=x86-64 -msse4.2 -mpopcnt -m64 -mtune=intel -std=c++0x -fPIC")
```

Following errors appear:
```
/opt/android/ndk/android-ndk-r11/toolchains/x86_64-4.9/prebuilt/linux-x86_64/bin/../lib/gcc/x86_64-linux-android/4.9/../../../../x86_64-linux-android/bin/ld: warning: skipping incompatible /opt/android/ndk/android-ndk-r11/platforms/android-21/arch-x86_64/usr/lib/libm.so while searching for m
/opt/android/ndk/android-ndk-r11/toolchains/x86_64-4.9/prebuilt/linux-x86_64/bin/../lib/gcc/x86_64-linux-android/4.9/../../../../x86_64-linux-android/bin/ld: warning: skipping incompatible /opt/android/ndk/android-ndk-r11/platforms/android-21/arch-x86_64/usr/lib/libc.so while searching for c
/opt/android/ndk/android-ndk-r11/toolchains/x86_64-4.9/prebuilt/linux-x86_64/bin/../lib/gcc/x86_64-linux-android/4.9/../../../../x86_64-linux-android/bin/ld: warning: skipping incompatible /opt/android/ndk/android-ndk-r11/platforms/android-21/arch-x86_64/usr/lib/libdl.so while searching for dl
```

If I create a symlink pointing to `/opt/android/ndk/android-ndk-r11/platforms/android-21/arch-x86_64/usr/lib64`, named `/opt/android/ndk/android-ndk-r11/platforms/android-21/arch-x86_64/usr/lib` (so, replacing the `lib` folder with the `lib64` one), errors disappear and compile process works fine. 

Is it just a toolchain config error, or am I missing something in the config?

**Comment by DanAlbert** [comment]
Did this work with r10e? I think this is something that should work, but knowing that would help track down the problem.

As a temporary workaround, you can use `build/tools/make-standalone-toolchain.sh`. It'll build a toolchain that can be used in this way. There are some known issues (read: it's pretty much broken) if you're using libc++ though.

**Comment by cmaster11** [comment]
My bad, obsolete build system.
