### ISSUE TITLE
NDK binaries are missing

### ISSUE THREAD

**Issue by navi63** [android-ndk/ndk#470]
Hii
I'm trying to build ' linphone-android ' . 
[](https://github.com/BelledonneCommunications/linphone-android)

Somehow i manged to resolv all the bugs but now i'm stuck at when i try to run ' ./prepare.py' commanad in terminal it giving me **NDK ERROR** i.e **ERROR: The following binaries are missing: ndk-build. Please install them**.

I have ndk path in .bash file also but unable to resolve this error.

Please share some solution
Thanks :)

**Comment by DanAlbert** [comment]
Not sure what we can do here. Sounds like either a configuration issue or perhaps an issue with linphone, not the NDK.

Please reopen if there's something showing this to be an NDK issue.
