### ISSUE TITLE
Casting result of strstr to char * required by compiler, seems random

### ISSUE THREAD

**Issue by miguellan** [android-ndk/ndk#471]
--------------------------------------------------------------------------------

#### Description

After running latest updates to Android studio, I have had to cast the result of strstr to a char *, even though that's the return type.  Strangely enough this behavior is picky it seems, as in the following code snipped it made me do it for location, but not the subsequent call.  This is a minor issue of course, but I thought I would report it and let you decide.

```
char *location = NULL,
         *substring = NULL;

if (buffer && key) {
        location = (char *)strstr(buffer, key);
        if (location) {
            substring = strstr(location, colon);
```

Here's the definition of strstr, in string.h
```
char* strstr(const char* _Nonnull, const char* _Nonnull) __attribute_pure__;
```

Here's the error that will occur if I remove the cast before the first call to strstr.

```
...20: error: assigning to 'char *' from incompatible type 'const char *'
        location = strstr(buffer, key);
                   ^~~~~~~~~~~~~~~~~~~
1 error generated.
```

#### Environment Details

Not all of these will be relevant to every bug, but please provide as much
information as you can.

* NDK Version: 15.1.4119039
* Build sytem: ndk-build
* Host OS: macOS
* Compiler: clang
* ABI: armeabi-v7a
* STL: stlport_shared
* NDK API level: android-14
* Device API level: N/A - Won't build no matter device

**Comment by DanAlbert** [comment]
I *think* this is the expected behavior, but I'm missing one detail: the type of `buffer`.

You stopped reading that file just a bit too soon. Later down we provide const-correct overloads of `strstr` if you're in C++ mode: https://android.googlesource.com/platform/bionic/+/master/libc/include/string.h#663. This conforms to the C++ standard.

Essentially, if your argument is const, so is the return type. What is the type of `buffer` in your example? Am I correct in assuming it's `const char*`?

**Comment by miguellan** [comment]
Ah yes, my fault, I should've read further.  It is a const char *

**Comment by miguellan** [comment]
Were those just added, cause this is some code that is quite old and it never reported a problem before?

**Comment by DanAlbert** [comment]
They're new to the NDK, yes. The NDK headers went un-updated for a really long time. We started shipping updated headers in r14, but they were opt-in. r15 makes them the default.

**Comment by miguellan** [comment]
Ok, good to know.  Thank you for the help Dan.
