### ISSUE TITLE
CMake: NDK toolchain file does not respect ANDROID_NDK set from outside

### ISSUE THREAD

**Issue by rcdailey** [android-ndk/ndk#473]
#### Description

Sometimes, the NDK-provided `android.toolchain.cmake` is fixed in the NDK repository but not yet shipped in an official NDK release. In these cases, I like to copy the toolchain file out to my own repository and use it temporarily until the NDK provides that version.

To accomplish this, I essentially do this in my own toolchain file:

```
set( ANDROID_NDK "the path to the NDK here" )
include( ${CMAKE_CURRENT_LIST_DIR}/android.toolchain.cmake ) # this is my copy of the NDK's toolchain file from `master`.
```

This fails because the `ANDROID_NDK` is being calculated regardless of if it was set from outside:

```
# Android NDK
get_filename_component(ANDROID_NDK "${CMAKE_CURRENT_LIST_DIR}/../.." ABSOLUTE)
file(TO_CMAKE_PATH "${ANDROID_NDK}" ANDROID_NDK)
```

My fix for this was simple:

```
# Android NDK
if(NOT ANDROID_NDK)
    get_filename_component(ANDROID_NDK "${CMAKE_CURRENT_LIST_DIR}/../.." ABSOLUTE)
endif()

file(TO_CMAKE_PATH "${ANDROID_NDK}" ANDROID_NDK)
```

If you're OK with this change, would you mind applying it to your official version? This change doesn't really benefit the production release of NDK, but makes the toolchain more configurable and can work in different locations in the filesystem outside of the NDK itself.

**Comment by DanAlbert** [comment]
Probably a good idea for us to also emit a warning when this is the case since it's likely to lead to weird behaviors if the NDK and toolchain file have diverged by much, but otherwise sounds like a good idea.

**Comment by DanAlbert** [comment]
https://android-review.googlesource.com/#/c/platform/ndk/+/500132

**Comment by DanAlbert** [comment]
Cherry picked to r16.

**Comment by nneonneo** [comment]
The warning message that this patch introduces now fires on _every_ CMake reconfigure, even though I don't set `ANDROID_NDK` anywhere in my code. The culprit seems to be the fact that the variable gets stored in the CMakeCache and subsequent reconfigures see the cached value.

```
CMake Warning at /Users/brx/devel/android/sdk/ndk-bundle/build/cmake/android.toolchain.cmake:63 (message):
  Using custom NDK path (ANDROID_NDK is set):
  /Users/brx/devel/android/sdk/ndk-bundle
Call Stack (most recent call first):
  /Users/brx/devel/android/sdk/cmake/3.6.4111459/share/cmake-3.6/Modules/CMakeDetermineSystem.cmake:98 (include)
  CMakeLists.txt
```

This warning is irritating - can it either be turned off, or the underlying problem fixed so that it isn't treating `ANDROID_NDK` as set?

I am using Android Studio 3.0.1.

**Comment by rcdailey** [comment]
Or rather than it being a warning, make it a STATUS message. It'll be a
little more subtle that way.
