### ISSUE TITLE
Incorrect doc about using deprecated headers in r15

### ISSUE THREAD

**Issue by yan12125** [android-ndk/ndk#475]
#### Description

In doc for NDK r15 [1], it's said Android.mk should be modified to force deprecated headers:
```
Add the following to your Android.mk:

APP_DEPRECATED_HEADERS := true
```
It should be Application.mk

https://android.googlesource.com/platform/ndk/+/ndk-r15-release/docs/UnifiedHeaders.md#ndk_build

#### Environment Details

Not all of these will be relevant to every bug, but please provide as much
information as you can.

* NDK Version: 15.1.4119039
* Build sytem: ndk-build
* Host OS: Arch Linux x86_64 latest
* Compiler: clang
* ABI: all
* STL: N/A
* NDK API level: N/A
* Device API level: N/A

**Comment by enh** [comment]
on the assumption there won't be another r15 release and r16 _removes_ the deprecated headers, i don't think there's anything to be done here?

**Comment by DanAlbert** [comment]
Easy enough to fix the doc on the site in the meantime though: https://android-review.googlesource.com/455796

**Comment by enh** [comment]
oh, duh, yeah. i forgot about the whole internet thing :-)

**Comment by DanAlbert** [comment]
https://www.youtube.com/watch?v=Q9A0Vufw3NQ
