### ISSUE TITLE
use __LP64__ instead of __LP32__ in pthread.h

### ISSUE THREAD

**Issue by zhuzeitou** [android-ndk/ndk#481]
#### Description

In r15c, legacy pthread API declarations have been added, but compile with them will fail unless you declare `__LP32__` manually
`error: use of undeclared identifier 'pthread_cond_timedwait_relative_np'`

pthread.h looks like
`#if defined(__LP32__) && __ANDROID_API__ < 21`
and __LP32__ is not declared.

what about change it into 
`#if !defined(__LP64__) && __ANDROID_API__ < 21`

#### Environment Details

* NDK Version: 15.2.4203891
* Build sytem: ndk-build
* Host OS: Windows
* Compiler: clang
* ABI: armeabi-v7a
* STL:
* NDK API level: android-14
* Device API level:

**Comment by alexcohn** [comment]
1. On Android, **__LP64__** should not be defined, either, becasue `sizeof(int)==sizeof(long)`.
2. The condition in **ptheread.h** does not make sense, since there were no 64-bit builds for `__ANDROID_API__ < 21`.

**Comment by enh** [comment]
ugh. __LP32__ and __x86__ --- two #defines that feel like they ought to exist but don't.

https://android-review.googlesource.com/453060

**Comment by DanAlbert** [comment]
Merged into r16.
