### ISSUE TITLE
SimplePerf cp perf.data: Permission denied

### ISSUE THREAD

**Issue by brok85** [android-ndk/ndk#489]
#### Description
NOTE: I get the following problem with all the apps and devices I have (all running Android 7.x.x).

I setup the configuration file and execute "python app_profiler.py". Datas are collected but then when is time to copy the perf.data file I get this error:

INFO:root:collect profiling data

DEBUG:root:run adb cmd: ['adb', 'shell', 'run-as', 'chat.rocket.android', 'chmod', 'a+rw', 'perf.data']
DEBUG:root:run adb cmd: ['adb', 'shell', 'run-as', 'chat.rocket.android', 'chmod', 'a+rw', 'perf.data']  [result True]

DEBUG:root:run adb cmd: ['adb', 'shell', 'cp', '/data/data/chat.rocket.android/perf.data', '/data/local/tmp']
cp: /data/data/chat.rocket.android/perf.data: Permission denied
cp: bad '/data/data/chat.rocket.android/perf.data': Permission denied
DEBUG:root:run adb cmd: ['adb', 'shell', 'cp', '/data/data/chat.rocket.android/perf.data', '/data/local/tmp']  [result False]

Traceback (most recent call last):
  File "app_profiler.py", line 302, in <module>
    profiler.profile()
  File "app_profiler.py", line 75, in profile
    self.collect_profiling_data()
  File "app_profiler.py", line 275, in collect_profiling_data
    '/data/data/%s/perf.data' % self.config['app_package_name'], '/data/local/tmp'])
  File "/Users/brok85/Library/Android/sdk/ndk-bundle/simpleperf/utils.py", line 104, in check_run
    self.check_run_and_return_output(adb_args)
  File "/Users/brok85/Library/Android/sdk/ndk-bundle/simpleperf/utils.py", line 110, in check_run_and_return_output
    log_fatal('run "adb %s" failed' % adb_args)
  File "/Users/brok85/Library/Android/sdk/ndk-bundle/simpleperf/utils.py", line 48, in log_fatal
    raise Exception(msg)

Exception: run "adb ['shell', 'cp', '/data/data/chat.rocket.android/perf.data', '/data/local/tmp']" failed

What can I do?

Thanks a lot for any help.
#### Environment Details

Not all of these will be relevant to every bug, but please provide as much
information as you can.

* NDK Version: 15.1.4119039
* Build sytem: ndk-build? cmake? standalone toolchain? custom? (if gradle, file
  a bug against studio as specified above)
* Host OS: MacOS Sierra
* Device API level: Android 7.0

**Comment by yabinc** [comment]
This is because an error in app_profiler.py, see https://android.googlesource.com/platform/prebuilts/simpleperf/+/ndk-r15-release#the-correct-way-to-pull-perf_data-on-host. This was fixed in ndk r15c, you can download it at
https://developer.android.com/ndk/downloads/index.html.
