### ISSUE TITLE
NDK r11b contains duplicated file

### ISSUE THREAD

**Issue by rmtheis** [android-ndk/ndk#49]
It looks like at least one file is duplicated in the Linux NDK r11b zip file.

    theis@ubuntu5:~/tmp2$ unzip -vl android-ndk-r11b-linux-x86_64.zip | grep --ignore-case xt_DSCP.h
    1548  Defl:X      575  63% 2016-03-15 13:25 8d4f8e17  android-ndk-r11b/platforms/android-24/arch-arm/usr/include/linux/netfilter/xt_dscp.h
    1422  Defl:X      559  61% 2016-03-15 13:25 bfd72029  android-ndk-r11b/platforms/android-24/arch-arm/usr/include/linux/netfilter/xt_DSCP.h
    1548  Defl:X      575  63% 2016-03-15 13:25 8d4f8e17  android-ndk-r11b/platforms/android-24/arch-x86/usr/include/linux/netfilter/xt_dscp.h
    1422  Defl:X      559  61% 2016-03-15 13:25 bfd72029  android-ndk-r11b/platforms/android-24/arch-x86/usr/include/linux/netfilter/xt_DSCP.h
    1548  Defl:X      575  63% 2016-03-15 13:25 8d4f8e17  android-ndk-r11b/platforms/android-24/arch-mips/usr/include/linux/netfilter/xt_dscp.h
    1422  Defl:X      559  61% 2016-03-15 13:25 bfd72029  android-ndk-r11b/platforms/android-24/arch-mips/usr/include/linux/netfilter/xt_DSCP.h
    1548  Defl:X      575  63% 2016-03-15 13:25 8d4f8e17  android-ndk-r11b/platforms/android-24/arch-x86_64/usr/include/linux/netfilter/xt_dscp.h
    1422  Defl:X      559  61% 2016-03-15 13:25 bfd72029  android-ndk-r11b/platforms/android-24/arch-x86_64/usr/include/linux/netfilter/xt_DSCP.h
    1548  Defl:X      575  63% 2016-03-15 13:25 8d4f8e17  android-ndk-r11b/platforms/android-24/arch-mips64/usr/include/linux/netfilter/xt_dscp.h
    1422  Defl:X      559  61% 2016-03-15 13:25 bfd72029  android-ndk-r11b/platforms/android-24/arch-mips64/usr/include/linux/netfilter/xt_DSCP.h
    1548  Defl:X      575  63% 2016-03-15 13:25 8d4f8e17  android-ndk-r11b/platforms/android-24/arch-arm64/usr/include/linux/netfilter/xt_dscp.h
    1422  Defl:X      559  61% 2016-03-15 13:25 bfd72029  android-ndk-r11b/platforms/android-24/arch-arm64/usr/include/linux/netfilter/xt_DSCP.h
    1548  Defl:X      575  63% 2016-03-15 13:25 8d4f8e17  android-ndk-r11b/platforms/android-21/arch-arm/usr/include/linux/netfilter/xt_dscp.h
    1422  Defl:X      559  61% 2016-03-15 13:25 bfd72029  android-ndk-r11b/platforms/android-21/arch-arm/usr/include/linux/netfilter/xt_DSCP.h
    1548  Defl:X      575  63% 2016-03-15 13:25 8d4f8e17  android-ndk-r11b/platforms/android-21/arch-x86/usr/include/linux/netfilter/xt_dscp.h
    1422  Defl:X      559  61% 2016-03-15 13:25 bfd72029  android-ndk-r11b/platforms/android-21/arch-x86/usr/include/linux/netfilter/xt_DSCP.h
    1548  Defl:X      575  63% 2016-03-15 13:25 8d4f8e17  android-ndk-r11b/platforms/android-21/arch-mips/usr/include/linux/netfilter/xt_dscp.h
    1422  Defl:X      559  61% 2016-03-15 13:25 bfd72029  android-ndk-r11b/platforms/android-21/arch-mips/usr/include/linux/netfilter/xt_DSCP.h
    1548  Defl:X      575  63% 2016-03-15 13:25 8d4f8e17  android-ndk-r11b/platforms/android-21/arch-x86_64/usr/include/linux/netfilter/xt_dscp.h
    1422  Defl:X      559  61% 2016-03-15 13:25 bfd72029  android-ndk-r11b/platforms/android-21/arch-x86_64/usr/include/linux/netfilter/xt_DSCP.h
    1548  Defl:X      575  63% 2016-03-15 13:25 8d4f8e17  android-ndk-r11b/platforms/android-21/arch-mips64/usr/include/linux/netfilter/xt_dscp.h
    1422  Defl:X      559  61% 2016-03-15 13:25 bfd72029  android-ndk-r11b/platforms/android-21/arch-mips64/usr/include/linux/netfilter/xt_DSCP.h
    1548  Defl:X      575  63% 2016-03-15 13:25 8d4f8e17  android-ndk-r11b/platforms/android-21/arch-arm64/usr/include/linux/netfilter/xt_dscp.h
    1422  Defl:X      559  61% 2016-03-15 13:25 bfd72029  android-ndk-r11b/platforms/android-21/arch-arm64/usr/include/linux/netfilter/xt_DSCP.h
    1548  Defl:X      575  63% 2016-03-15 13:25 8d4f8e17  android-ndk-r11b/platforms/android-23/arch-arm/usr/include/linux/netfilter/xt_dscp.h
    1422  Defl:X      559  61% 2016-03-15 13:25 bfd72029  android-ndk-r11b/platforms/android-23/arch-arm/usr/include/linux/netfilter/xt_DSCP.h
    1548  Defl:X      575  63% 2016-03-15 13:25 8d4f8e17  android-ndk-r11b/platforms/android-23/arch-x86/usr/include/linux/netfilter/xt_dscp.h
    1422  Defl:X      559  61% 2016-03-15 13:25 bfd72029  android-ndk-r11b/platforms/android-23/arch-x86/usr/include/linux/netfilter/xt_DSCP.h
    1548  Defl:X      575  63% 2016-03-15 13:25 8d4f8e17  android-ndk-r11b/platforms/android-23/arch-mips/usr/include/linux/netfilter/xt_dscp.h
    1422  Defl:X      559  61% 2016-03-15 13:25 bfd72029  android-ndk-r11b/platforms/android-23/arch-mips/usr/include/linux/netfilter/xt_DSCP.h
    1548  Defl:X      575  63% 2016-03-15 13:25 8d4f8e17  android-ndk-r11b/platforms/android-23/arch-x86_64/usr/include/linux/netfilter/xt_dscp.h
    1422  Defl:X      559  61% 2016-03-15 13:25 bfd72029  android-ndk-r11b/platforms/android-23/arch-x86_64/usr/include/linux/netfilter/xt_DSCP.h
    1548  Defl:X      575  63% 2016-03-15 13:25 8d4f8e17  android-ndk-r11b/platforms/android-23/arch-mips64/usr/include/linux/netfilter/xt_dscp.h
    1422  Defl:X      559  61% 2016-03-15 13:25 bfd72029  android-ndk-r11b/platforms/android-23/arch-mips64/usr/include/linux/netfilter/xt_DSCP.h
    1548  Defl:X      575  63% 2016-03-15 13:25 8d4f8e17  android-ndk-r11b/platforms/android-23/arch-arm64/usr/include/linux/netfilter/xt_dscp.h
    1422  Defl:X      559  61% 2016-03-15 13:25 bfd72029  android-ndk-r11b/platforms/android-23/arch-arm64/usr/include/linux/netfilter/xt_DSCP.h

**Comment by DanAlbert** [comment]
Those are the Linux kernel headers. They aren't duplicates on a proper file system, but Windows and Darwin have case insensitive file systems by default. Nothing we can do about it.

If you're on Darwin, you can follow [the aosp setup instructions](https://source.android.com/source/initializing.html#creating-a-case-sensitive-disk-image), but I think on Windows this is just the way things are.
