### ISSUE TITLE
default to neon for new enough API levels

### ISSUE THREAD

**Issue by DanAlbert** [android-ndk/ndk#490]
In L (I think it was L, I need to check the CDD) NEON became a requirement for ARM32 devices. We should default to enabling NEON whenever the target API is at least that version.

Would be best to do this in the Clang driver so we don't need to replicate this in a thousand build systems.

**Comment by hrydgard** [comment]
Are there really any to worry about? Nearly all ARMv7 devices (with the notable exception of some early Tegras) support NEON. Even Nexus One had NEON support, and that's several major Android versions back...

**Comment by unverbraucht** [comment]
I second this. We switched to using NEON in our recent embedded v8 build and had to disable the app for a few select Tegra 2 devices manually, but these would all have been running 4.2, tops. The only possible way for a non-NEON device to run L would be to use a custom rom and a lot of black magic. Activating it for L+ seems very fine to me.

**Comment by kneth** [comment]
More than a fifth of all active Android devices are running API <= 19: https://developer.android.com/about/dashboards/index.html

**Comment by unverbraucht** [comment]
@kneth true, but they are not affected as no device running a Tegra 2 has ever been updated beyond 4.1 as far as I know (LG P990 and Acer A1 ended at 4.0.4). And even the custom roms would have a very hard time pushing a 512MB Tegra 2 system above Kitkat, I'd wager it would be technically impossible or at least nobody would wait even for the first boot ;)

**Comment by DanAlbert** [comment]
Probably safe to do this with some documentation showing how to blacklist bad CPUs.

**Comment by DanAlbert** [comment]
https://android-review.googlesource.com/#/c/platform/ndk/+/700024

**Comment by DanAlbert** [comment]
Slight touch up because this was actually done in M, not L: https://android-review.googlesource.com/c/platform/ndk/+/714584 (thanks @rprichard for catching that).
