### ISSUE TITLE
Native crypto api / access to boringssl

### ISSUE THREAD

**Issue by youaresoomean** [android-ndk/ndk#491]
Hi,

currently every native app with some kind of crypto functionality is burdened with the task of building, shipping and updating it`s own copy of OpenSSL. Apart from maintainance this also means it has to be mentioned in every documentation of an app etc. 
- Either provide a native API to crypto functionality / certificate store access similar to iOS (CommonCrypto..)
- Or provide access to system BoringSSL

**Comment by DanAlbert** [comment]
Platform API requests belong on b.android.com.

**Comment by enh** [comment]
(add a link to your b.android.com bug here so we can make sure it gets to the right people)

it would also be interesting to know what part(s) of CommonCrypto you actually want.

**Comment by youaresoomean** [comment]
Hi, link in bug tracker is: https://issuetracker.google.com/issues/65035431

Functionality-wise the api should provide all common cypher-suites currently in use ("low-level") and a robust TLS-stack out of the box. "Simply" providing OpenSSL/BoringSSL would be perfect to build safe communcations ontop.
