### ISSUE TITLE
python report.py Warnings: failed to read symbols from...

### ISSUE THREAD

**Issue by brok85** [android-ndk/ndk#494]
#### Description

When I execute the python report.py, I often see the following warnings:

simpleperf W 08-25 16:26:32  5698 372663 dso.cpp:360] failed to read symbols from /system/lib64/libc.so: File not found
simpleperf W 08-25 16:26:32  5698 372663 dso.cpp:360] failed to read symbols from /system/lib64/libart.so: File not found
simpleperf W 08-25 16:26:32  5698 372663 dso.cpp:360] failed to read symbols from /system/framework/arm64/boot-framework.oat: File not found
simpleperf W 08-25 16:26:32  5698 372663 dso.cpp:360] failed to read symbols from /system/lib64/libbinder.so: File not found
simpleperf W 08-25 16:26:32  5698 372663 dso.cpp:360] failed to read symbols from [fm_drv]: File not found
simpleperf W 08-25 16:26:32  5698 372663 dso.cpp:360] failed to read symbols from /system/lib64/libcutils.so: File not found
simpleperf W 08-25 16:26:32  5698 372663 dso.cpp:360] failed to read symbols from /system/lib64/libutils.so: File not found
simpleperf W 08-25 16:26:32  5698 372663 dso.cpp:360] failed to read symbols from /system/lib64/libhwui.so: File not found

Is there any way I can fix these warnings? 

Thanks a lot for all your valuable help.

#### Environment Details

* NDK Version: r15-c.
* Host OS: Mac
* Device API level: 24

**Comment by yabinc** [comment]
No need to fix. It will disappear in ndk r16.
