### ISSUE TITLE
native-media sample crashes on fread() for arm64 with NDK r15+

### ISSUE THREAD

**Issue by ggfan** [android-ndk/ndk#496]
#### Description
SIGSEGV(signal SIGSEGV: invalid address (fault address: 0x60)
when performing:
     bytesRead = fread(dataCache, 1, BUFFER_SIZE * NB_BUFFERS, file);
in sample [native-media](https://github.com/googlesamples/android-ndk/tree/master/native-media). 

The problem seems only starts with NDK-r15+, it ONLY affects 64 bit builds ( arm64 )

#### Environment Details
In order to avoid the run-time permission, the video clip is put inside assets folder and using Asset_*() functions to performs the [file access](https://github.com/googlesamples/android-ndk/blob/master/native-media/app/src/main/cpp/android_fopen.c) ( inside assets folder ):
`FILE* android_fopen(const char* fname, const char* mode) {
    if(mode[0] == 'w') return NULL;

    AAsset* asset = AAssetManager_open(android_asset_manager, fname, 0);
    if(!asset) return NULL;

    return funopen(asset, android_read, android_write, android_seek, android_close);
}`

the mechanism does not work on newer NDK, may you check it out?  thanks

* NDK Version: ndk-r15, ndk-r16
* Build sytem: cmake + gradle
* Host OS: Mac
* Compiler: Clang before filing
* ABI: ARM64
* STL:
* NDK API level: 14 ( also tried 24)
* Device API level: 14 ( running on Android-26)

**Comment by dosvidos** [comment]
I've observed that bug on Nexus 9 running Android 5.1 and Nexus 6P running Android 8.0

**Comment by DanAlbert** [comment]
The NDK libraries are just stubs. This needs to be filed against the platform. http://b.android.com
