### ISSUE TITLE
clang++ from NDK r15c won't link LTO executables for arm64

### ISSUE THREAD

**Issue by tavianator** [android-ndk/ndk#497]
```
$ /opt/android-ndk/build/tools/make_standalone_toolchain.py --arch=arm64 --api=21 --stl=libc++ --install-dir=/tmp/ndk-arm64 --force -v
$ cat foo.cpp
int main() {
  return 0;
}
$ /tmp/ndk-arm64/bin/aarch64-linux-android-clang++ -std=c++11 -O3 -pie -static-libstdc++ -flto foo.cpp
/tmp/foo-142c40.o: file not recognized: File format not recognized
clang50++: error: linker command failed with exit code 1 (use -v to see invocation)
```

If I pass `-fuse-ld=gold` it works though.

**Comment by amartinz** [comment]
As far as i know you are required to use gold for LTO.

https://llvm.org/docs/GoldPlugin.html

```LTO support on Linux systems requires that you use the gold linker or ld.bfd from binutils >= 2.21.51.0.2, as they support LTO via plugins.```

**Comment by tavianator** [comment]
```
$ /tmp/ndk-arm64/bin/aarch64-linux-android-ld.bfd --version
GNU ld (binutils-2.25-0666073) 2.25.51.20141117
```

which should be new enough to support LTO.  It works for arm, just not arm64.

**Comment by stephenhines** [comment]
We don't ship (or test) the plugin with ld.bfd. This would only be supported for ld.gold, so you need to pass the -fuse-ld=gold flag. I'll leave this open for Dan to comment on whether make_standalone_toolchain.py should be inserting that flag for you during link steps.

**Comment by pirama-arumuga-nainar** [comment]
Like Steve mentions, this is not what we support or plan to support.  In fact, Clang LTO with ld.bfd is not tested in upstream either (http://lists.llvm.org/pipermail/llvm-dev/2016-October/105698.html proposes doing so, but I couldn't find anything in http://lab.llvm.org:8011/builders).

If you do want to troubleshoot, here are some things that you can try:
1. pass -v to clang and make sure it passes LLVMgold.so as a plugin to the linker.
2. Invoke the linker command under LD_DEBUG to catch any diagnostics that the plugin might issue.

**Comment by DanAlbert** [comment]
You really don't want to use LTO with arm64 right now: https://groups.google.com/d/topic/android-ndk-announce/u8v7eIegIpM/discussion

> [This version of bfd] should be new enough to support LTO.  It works for arm, just not arm64.

No it doesn't. ld.gold is the default linker for arm/x86/x86_64 on Android. If you add `-fuse-ld=bfd` to your ldflags then LTO won't work.

It's not the version of bfd that's the issue, it's that Clang only supports LTO with gold. AFAIK there's no plan to change this (though we do plan to make gold the default for arm64, but that's a different issue), so closing this.
