### ISSUE TITLE
clang LTO is broken with __thread variables

### ISSUE THREAD

**Issue by tavianator** [android-ndk/ndk#498]
Seems similar to #156:

```
$ /opt/android-ndk/build/tools/make_standalone_toolchain.py --arch=arm --api=21 --stl=libc++ --install-dir=/tmp/ndk-arm --force -v
$ cat foo.c
#include <stdio.h>

__thread int x;

int main() {
  x = 1;
  asm("" ::: "memory");
  printf("%d\n", x);
  return 0;
}
$ /tmp/ndk-arm/bin/arm-linux-androideabi-clang -O3 -pie -flto foo.c
$ adb push a.out /data/local/tmp/ && adb shell /data/local/tmp/a.out
a.out: 1 file pushed. 0.3 MB/s (4100 bytes in 0.012s)
CANNOT LINK EXECUTABLE "/data/local/tmp/a.out": cannot locate symbol "" referenced by "/data/local/tmp/a.out"...
$ nm a.out | grep U
         U __cxa_atexit
         U __libc_init
         U printf
         U __tls_get_addr
```

I'm guessing it's the `__tls_get_addr` that isn't resolved, and it should be more like `__emutls_get_address`?

**Comment by tavianator** [comment]
Interestingly `-x c++` is enough to suppress the issue.  But if I then add `__attribute__((used))` to `x`, I get this:

```
CANNOT LINK EXECUTABLE "/data/local/tmp/a.out": unknown reloc type 17 @ 0xba6a038c (5)
```

**Comment by enh** [comment]
that's one of the TLS relocations, suggesting you're not building for emutls, which is all Android supports.

```
/* TLS relocations */
#define R_ARM_TLS_DTPMOD32	17	/* ID of module containing symbol */
#define R_ARM_TLS_DTPOFF32	18	/* Offset in TLS block */
#define R_ARM_TLS_TPOFF32	19	/* Offset in static TLS block */
```

pirama: any idea why emutls isn't being used here?

**Comment by pirama-arumuga-nainar** [comment]
Which version of Android do you have on your device?  `a.out` prints `1` on a Nexus 6P running O.

**Comment by tavianator** [comment]
@pirama-arumuga-nainar 8.0 running on a Pixel.  I'd be very surprised if this was an Android platform issue though, are you running the same NDK version as me (r15c) with a standalone arm (not arm64) toolchain?

**Comment by pirama-arumuga-nainar** [comment]
@tavianator I used standalone ARM from the r15 beta 2 that I had previously set up.  I'll try with r15c.

**Comment by pirama-arumuga-nainar** [comment]
@tavianator  Aah, never mind.  I wasn't adding `__attribute__((used))`.

@enh Looks like the bionic linker doesn't handle R_ARM_TLS_DTPMOD32 (https://android.googlesource.com/platform/bionic/+/master/linker/linker.cpp#2829).

**Comment by tavianator** [comment]
@pirama-arumuga-nainar That's true, but I believe LLVM is supposed to be working around it through `-femulated-tls`.  You can see with `-v` that it gets passed down, but seems to be ignored in concert with `-flto`.

**Comment by pirama-arumuga-nainar** [comment]
@tavianator Yea, that's right.  -femulated-tls should be passed to the backend through the Gold plugin.  @srhines and I discussed this and it'd be better to put this in the IR (foo.o) rather than add an option to the plugin.

This'd need some plumbing through LLVM/Clang.  It'll probably not make into r16, but we'll plan for r17.

**Comment by tavianator** [comment]
The plugin already has such an option, so actually `-Wl,-plugin-opt=-emulated-tls` serves as a workaround (thanks for the hint!).  I agree though that it makes the most sense to tag the variable itself in the IR.

**Comment by pirama-arumuga-nainar** [comment]
If an option already exists, we can change Clang to pass it to the plugin.  For some reason I thought only the options in [gold-plugin.cpp](https://github.com/llvm-mirror/llvm/blob/master/tools/gold/gold-plugin.cpp#L184) were exported by the plugin.

This should also be simpler than baking it in the IR.

**Comment by DanAlbert** [comment]
@pirama-arumuga-nainar: did this every get fixed upstream?

**Comment by pirama-arumuga-nainar** [comment]
Chih-hung fixed it upstream (https://android-review.googlesource.com/c/toolchain/llvm/+/631496).  It should be included in the upcoming Clang.

**Comment by DanAlbert** [comment]
Alright, should be in r18 then. Thanks!

**Comment by rprichard** [comment]
This looks fixed in the r18 canary clang (4751641 based on r328903).

**Comment by preth-2018** [comment]
Hi @pirama-arumuga-nainar,

I am facing issue with NDK16.

CANNOT LINK EXECUTABLE: cannot locate symbol "__emutls_get_address" referenced by "/data/tmp/android-23/armeabi-v7a/install/lib/libAVSCommon.so"...
page record for 0xb6e6004c was not found (block_size=64)

Is there a workaround?
I am not understanding where to pass the -Wl,-plugin-opt=-emulated-tls or -femulated-tls that you guys are taking about. Could you please help?

**Comment by ravarora** [comment]
Facing similar issue with NDK 17 as well as NDK 18 beta 1. This happens while creating x86 builds. For ARM builds it works fine.
