### ISSUE TITLE
r16-beta 1: cygwin: asm/types.h not found with $NDK/build/ndk-build

### ISSUE THREAD

**Issue by vpatilvasu** [android-ndk/ndk#510]
#### Description

- Compiling with `$NDK/build/ndk-build` fails with error: `C:/cp/tools/ndk-r16-beta1/sysroot/usr/include\linux/types.h:21:10: fatal error: 'asm/types.h' file not found`
whereas the same code compiles with `$NDK/ndk-build.cmd`

- ndk-build verbose output is [here](https://gist.github.com/vpatilvasu/aec80783b8d101bb31476ca18022347d)

#### Environment Details

* **NDK Version:** r16 Beta 1
* **Build sytem:** ndk-build and ndk-build.cmd
* **Host OS:** Windows 7 with Cygwin
* **Compiler:** Clang
* **ABI:** armeabi-v7a arm64-v8a
* **STL:** c++_static
* **NDK API level:** 23

**Comment by alexcohn** [comment]
I see `-isystem /cygdrive/c/cp/tools/ndk-r16-beta1/sysroot/usr/include/arm-linux-androideabi`, and probably this is the line that fails. Try to run **ndk-build** without Cygwin, it isn't necessary since NDK r10, IIRC.

**Comment by vpatilvasu** [comment]
**$NDK/ndk-build.cmd** using Windows command prompt and Cygwin works fine.

However, we use Cygwin to build several projects, apps and also, native code using ``$NDK/build/ndk-build``. Is Cygwin not going to be supported by NDK?

Also, ``-isystem`` points to correct include directory in my build configuration, then why is it not able to find ``asm/types.h``?

**Comment by alexcohn** [comment]
> `-isystem` points to correct include directory in my build configuration, then why is it not able to find `asm/types.h`?

Unfrotunately, **clang** has no way to know this. Android toolchains have been compiled without cygwin support for the last 4 years.

**Comment by alexcohn** [comment]
I believe that the fix for [setup-toolchain.mk](https://android.googlesource.com/platform/ndk/+/master/build/core/setup-toolchain.mk#147) could be 

```
--- a/build/core/setup-toolchain.mk
+++ b/build/core/setup-toolchain.mk
@@ -144,7 +144,7 @@
 header_triple_x86 := i686-linux-android
 header_triple_x86_64 := x86_64-linux-android
 SYSROOT_ARCH_INC_ARG := \
-    -isystem $(SYSROOT_INC)/usr/include/$(header_triple_$(TARGET_ARCH))
+    -isystem $$(call host-path,$(SYSROOT_INC)/usr/include/$(header_triple_$(TARGET_ARCH)))
 
 clean-installed-binaries::

```

**Comment by Nercury** [comment]
We got the same issue compiling C++ code because include directory is set over `CMAKE_C_FLAGS`, which is obviously not used when compiling C++ files.

**Comment by alexcohn** [comment]
set(CMAKE_CXX_FLAGS "${CMAKE_C_FLAGS} ${CMAKE_CXX_FLAGS}")

can be bad: e.g. `-std=c99` and `-std=c++11` cannot coexist in CFLAGS.

**Comment by stephenhines** [comment]
> Unfrotunately, clang has no way to know this. Android toolchains have been compiled without cygwin support for the last 4 years.

Can you explain what we would do differently to support Cygwin? We use mingw to build our Windows toolchains, so that might limit what we can do, but I am happy to try to make this better.

**Comment by alexcohn** [comment]
> what we would do differently to support Cygwin?

Personally I don't think there is a single reason to worry about this. If **ndk-build** and **cmake** never use cygwin-style paths, nobody would even ask about this.

**Comment by DanAlbert** [comment]
Just use the Windows NDK from Cygwin. Use ndk-build.cmd instead of the bash script and it all just works.

**Comment by DanAlbert** [comment]
(if that's not the case, I'll reopen, but last time I checked this was the case)

**Comment by alexcohn** [comment]
> Just use the Windows NDK from Cygwin

Maybe drop `ndk-build` from the Windows distribution, only leaving `ndk-build.cmd` ? I cannot think of some build scenario where this could cause troubles.

Speaking about this, many people would benefit if on Linux and Mac, you could set `ndk-build.cmd` to be a synonym of `ndk-build`. This could void all the ugly solutions that involve sniffing the OS to choose between the two scripts.

**Comment by DanAlbert** [comment]
Both scripts get installed to $NDK/build, but only one of them is installed directly to $NDK (depending on OS), which is the one that should be used (do they work if invoked from the other location? that's definitely not tested).

**Comment by alexcohn** [comment]
> only one of them is installed directly to $NDK 

This is a relatively recent change that I oversaw.
