### ISSUE TITLE
NdkMediaCodec.h: static_assert does not compile with -std=c11

### ISSUE THREAD

**Issue by mpoullet** [android-ndk/ndk#511]
#### Description

Including NdkMediaCodec.h in C only projects using `-std=c11` results in errors:

```
/Users/mpoullet/android-sdks/ndk-bundle/sysroot/usr/include/media/NdkMediaCodec.h:152:15: error: expected parameter declarator
static_assert(sizeof(_off_t_compat) == sizeof(long),
              ^
/Users/mpoullet/android-sdks/ndk-bundle/sysroot/usr/include/media/NdkMediaCodec.h:152:15: error: expected ')'
/Users/mpoullet/android-sdks/ndk-bundle/sysroot/usr/include/media/NdkMediaCodec.h:152:14: note: to match this '('
static_assert(sizeof(_off_t_compat) == sizeof(long),
             ^
```

`#include <assert.h>` is needed to compile this with C11 enabled ( `__STDC_VERSION__ >= 201112L)`, as it declares static_assert in C11.

#### Environment Details
* NDK Version: 15.2.4203891
* Build sytem: ndk-build
* Host OS: Mac
* Compiler: Clang
* ABI: -
* STL: only relevant for C11
* NDK API level: -
* Device API level: -

**Comment by enh** [comment]
https://android-review.googlesource.com/#/c/platform/frameworks/av/+/481697/

**Comment by mpoullet** [comment]
Thanks.

**Comment by DanAlbert** [comment]
Hasn't been pulled into the NDK yet, so not fixed.

**Comment by enh** [comment]
(change merged to AOSP master, but waiting for r16beta2 header update...)

**Comment by DanAlbert** [comment]
This is in r16 beta 2.
