### ISSUE TITLE
mmap no define in sysroot when __USE_FILE_OFFSET64 define and android api < 21

### ISSUE THREAD

**Issue by owen200008** [android-ndk/ndk#512]
Pkg.Desc = Android NDK Pkg.Revision = 15.2.4203891
mmap no define in sysroot->usr->include->sys->mman.h
when __USE_FILE_OFFSET64 define and android api < 21

**Comment by owen200008** [comment]
low ndk version is success. update to 15 it compile fail.

**Comment by enh** [comment]
duplicate of #477
