### ISSUE TITLE
Type FILE is not not declared correctly for API level 24 and higher with Unified Headers

### ISSUE THREAD

**Issue by aivchenk** [android-ndk/ndk#513]
#### Description

cat $NDK_DIR/r16b1/sysroot/usr/include/stdio.h
```
<…>
#if __ANDROID_API__ < __ANDROID_API_N__   
#include <bits/struct_file.h>             //  Needed header is included only with API level lower then Android N API (24).
#endif
<…> 
```

How to reproduce:
$ cat test.c
```
#include <stdio.h>

extern FILE *ppp()
{
        FILE *ppp;
        size_t = sizeof(FILE);
        return ppp;
}
```

$NDK_DIR/ndk-build V=1

> rm -f <...>/ndk/r16b1/test/libs/arm64-v8a/* <...>/ndk/r16b1/test/libs/armeabi/* <...>/ndk/r16b1/test/libs/armeabi-v7a/* <...>/ndk/r16b1/test/libs/mips/* <...>/ndk/r16b1/test/libs/mips64/* <...>/ndk/r16b1/test/libs/x86/* <...>/ndk/r16b1/test/libs/x86_64/*
> rm -f <...>/ndk/r16b1/test/libs/arm64-v8a/gdbserver <...>/ndk/r16b1/test/libs/armeabi/gdbserver <...>/ndk/r16b1/test/libs/armeabi-v7a/gdbserver <...>/ndk/r16b1/test/libs/mips/gdbserver <...>/ndk/r16b1/test/libs/mips64/gdbserver <...>/ndk/r16b1/test/libs/x86/gdbserver <...>/ndk/r16b1/test/libs/x86_64/gdbserver
> rm -f <...>/ndk/r16b1/test/libs/arm64-v8a/gdb.setup <...>/ndk/r16b1/test/libs/armeabi/gdb.setup <...>/ndk/r16b1/test/libs/armeabi-v7a/gdb.setup <...>/ndk/r16b1/test/libs/mips/gdb.setup <...>/ndk/r16b1/test/libs/mips64/gdb.setup <...>/ndk/r16b1/test/libs/x86/gdb.setup <...>/ndk/r16b1/test/libs/x86_64/gdb.setup
> [x86_64] Compile        : test <= test.c
> <...>/ndk/r16b1/toolchains/llvm/prebuilt/linux-x86_64/bin/clang -MMD -MP -MF <...>/ndk/r16b1/test/obj/local/x86_64/objs/test/test.o.d -gcc-toolchain <...>/ndk/r16b1/toolchains/x86_64-4.9/prebuilt/linux-x86_64 -target x86_64-none-linux-android -ffunction-sections -funwind-tables -fstack-protector-strong -fPIC -Wno-invalid-command-line-argument -Wno-unused-command-line-argument -no-canonical-prefixes  -g -O2 -DNDEBUG  -I<...>/ndk/r16b1/test/jni   -DANDROID  -D__ANDROID_API__=26 -Wa,--noexecstack -Wformat -Werror=format-security  --sysroot <...>/ndk/r16b1/sysroot -isystem <...>/ndk/r16b1/sysroot/usr/include/x86_64-linux-android -c  <...>/ndk/r16b1/test/jni/test.c -o <...>/ndk/r16b1/test/obj/local/x86_64/objs/test/test.o
> <...>/ndk/r16b1/test/jni/test.c:6:10: error: invalid application of 'sizeof' to an incomplete type 'FILE' (aka 'struct __sFILE')
>         size_t t = sizeof(FILE);
>                 ^     ~~~~~~
> <...>/ndk/r16b1/sysroot/usr/include/stdio.h:58:8: note: forward declaration of 'struct __sFILE'
> struct __sFILE;
>        ^
> 1 error generated.
> make: *** [<...>/ndk/r16b1/test/obj/local/x86_64/objs/test/test.o] Error 1

**Comment by enh** [comment]
this is intentional. we've been hiding more of the stdio implementation details over many releases now. POSIX does not guarantee anything about the type of FILE.

**Comment by enh** [comment]
(note that the details of struct FILE have already changed slightly over the years, so it's dangerous to make assumptions about them even now. we intended to make more changes in future.)
