### ISSUE TITLE
NDK r16 README.md was not updated after the transition to unified headers

### ISSUE THREAD

**Issue by dosvidos** [android-ndk/ndk#514]
Current README for r16 published at https://android.googlesource.com/platform/ndk/+/ndk-release-r16/README.md#target-headers-and-binaries states that
>platforms/android-$VERSION/arch-$ARCH_NAME/ contains headers and libraries for each API level.

That is no longer true after the transition to https://android.googlesource.com/platform/ndk/+/ndk-release-r16/docs/UnifiedHeadersMigration.md in r15 and removal of legacy headers in r16

**Comment by enh** [comment]
looks like this needs to be cherrypicked to the r16 branch:
```
commit 38069516997a82cb8200494c15777dcd422de0f7
Author: Dan Albert <danalbert@google.com>
Date:   Tue Aug 29 23:42:27 2017 -0700

    Update readme regarding sysroots.
    
    Test: None, markdown only
    Bug: None
    Change-Id: Ie5fb921e9a523c78ec02958386ba0989ed0c300c
```

**Comment by enh** [comment]
https://android-review.googlesource.com/#/c/platform/ndk/+/479481/ is the cherrypick to the r16 release branch.

**Comment by enh** [comment]
will be in r16beta2.
