### ISSUE TITLE
Missing libgcc in libc++.a breaks clang c++_static build

### ISSUE THREAD

**Issue by AstralStorm** [android-ndk/ndk#515]
Libunwind is missing for x86, x86_64 and arm64-v8a ABI preventing correct static linking with c++_static when exceptions are enabled.
This is caused by libc++abi directly referencing \_Unwind\_\* symbols.

Results in errors like:
undefined reference to "_Unwind_Resume" etc.

Tested with NDK 16 beta 1, clang c++_static build of a shared library, ANDROID_CPP_FEATURES=exceptions and actually used exception handling.
Build is fine on armeabi-v7a and armeabi which provide libunwind.
Fails on x86, x86_64 and arm64-v8a. (Probably mips etc. as well but haven't checked.)

**Comment by AstralStorm** [comment]
After some more digging, it seems that older Android.mk properly linked libunwindbacktrace into libc++abi on non-armeabi, but the new soong Android.bp is missing the link instructions and is thus completely broken.

**Comment by DanAlbert** [comment]
Those platforms don't use libunwind. They use libgcc. Can you share your CMake configuration command?

**Comment by AstralStorm** [comment]
Oh that changes things. It is related to https://github.com/android-ndk/ndk/issues/504 and ancient android.toolchain.cmake then. It doesn't add libc++abi etc. on its own.

However new setup from CMake 3.9.2 seems to attempt to link libunwind not libgcc after source code inspection.

**Comment by AstralStorm** [comment]
Another error that finally showed up on armeabi-v7a is missing __aeabi_uldivmod etc. This is due to missing libgcc lin libc++.a while it is depended upon. (Note that adding -lgcc there does not work as it is not in the same directory.)

**Comment by DanAlbert** [comment]
> Another error that finally showed up on armeabi-v7a is missing __aeabi_uldivmod etc.

It's not supposed to.

Can you share your CMake configuration command?

**Comment by AstralStorm** [comment]
First, there's https://github.com/android-ndk/ndk/issues/105 which masks the problem as libstdc++.so contains the required symbols. Once you work around it (e.g. with -nodefaultlibs) and link like so:
    string(CONCAT CMAKE_CXX_FLAGS "-nodefaultlibs " "${CMAKE_CXX_FLAGS}")
    string(CONCAT CMAKE_CXX_STANDARD_LIBRARIES "-lc -ldl " "${CMAKE_CXX_STANDARD_LIBRARIES}")

You will find you're missing libgcc. Upcoming -nostdlibc++ flag will probably not link libgcc as well in the new unreleased upcoming Clang. Adding -static-libgcc does not work either for some reason. Neither does CMake 3.9.2.

**Comment by DanAlbert** [comment]
Can you share your CMake configuration command?

**Comment by AstralStorm** [comment]
It is ran by gradle plugin 3.0.0-beta5, externalNativeBuild, the options are:
externalNativeBuild {
            cmake {
                cFlags "-std=c11"
                cppFlags "-std=c++14 -D_LIBCPP_STD_VER=14"
                abiFilters "armeabi-v7a", "arm64-v8a", "x86", "x86_64"
                arguments "-DANDROID_ARM_MODE=arm", "-DANDROID_ARM_NEON=TRUE", "-DANDROID_STL=c++_static",
                        "-DCMAKE_TOOLCHAIN_FILE=${android.ndkDirectory}/build/cmake/android.toolchain.cmake",
                        "-DANDROID_CPP_FEATURES=rtti exceptions", "-DANDROID_TOOLCHAIN=clang",
            }
}
The define is to force older versions of NDK to actually use the right CMAKE_TOOLCHAIN_FILE and is likely redundant for r16 beta1.

Slightly anonymized output of one of cmake_build_command.txt:
Executable : android/sdk/cmake/3.6.4111459/bin/cmake
arguments : 
-HabsoluteProjectPath
-BabsoluteProjectPath/.externalNativeBuild/cmake/debug/armeabi-v7a
-DCMAKE_SYSTEM_NAME=Android
-DANDROID_ABI=armeabi-v7a
-DANDROID_PLATFORM=android-21
-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=absoluteProjectPath/build/intermediates/cmake/debug/obj/armeabi-v7a
-DCMAKE_BUILD_TYPE=Debug
-DCMAKE_MAKE_PROGRAM=android/sdk/cmake/3.6.4111459/bin/ninja
-DCMAKE_C_FLAGS=-std=c11
-DCMAKE_CXX_FLAGS=-std=c++14 -D_LIBCPP_STD_VER=14
-DANDROID_ARM_MODE=arm
-DANDROID_ARM_NEON=TRUE
-DANDROID_STL=c++_static
-DCMAKE_TOOLCHAIN_FILE=android/sdk/ndk-bundle/build/cmake/android.toolchain.cmake
-DANDROID_CPP_FEATURES=rtti exceptions
-DANDROID_TOOLCHAIN=clang
-DCMAKE_TOOLCHAIN_FILE=android/sdk/ndk-bundle/build/cmake/android.toolchain.cmake
-DANDROID_NDK=android/sdk/ndk-bundle
-GAndroid Gradle - Ninja
jvmArgs :

**Comment by DanAlbert** [comment]
Works fine for me. My guess is that you're using some prebuilt libraries that need to be rebuilt.

Everything reported here so far is actually things working as expected (using libgcc instead of libunwind, static libs not having libgcc symbols in them). Without a repro case there's nothing more we can do here.

**Comment by AstralStorm** [comment]
Hmm, no idea why would I need libraries to be rebuilt at all. The problem really shows up only with armeabi-v7a (unwind included) and std::chrono use (in my specific case, std::timed_mutex::wait_for(..., 1min) for me.

**Comment by DanAlbert** [comment]
Closing for lack of a repro case. Will reopen if we get something actionable.
