### ISSUE TITLE
truncate function not available for Android Level 19

### ISSUE THREAD

**Issue by Jakouf** [android-ndk/ndk#516]
#### Description

When using the truncate function from the unistd.h library compile errors will appear.

I looked already in the unistd.h file. For me it seems there was a mistake in line 216:

```
#if __ANDROID_API__ >= 21
int truncate(const char* __path, off_t __length) __RENAME(truncate64) __INTRODUCED_IN(21);
#endif /* __ANDROID_API__ >= 21 */


#if __ANDROID_API__ >= 12
ssize_t pread(int __fd, void* __buf, size_t __count, off_t __offset)
  __overloadable __RENAME(pread64) __INTRODUCED_IN(12);
ssize_t pwrite(int __fd, const void* __buf, size_t __count, off_t __offset)
  __overloadable __RENAME(pwrite64) __INTRODUCED_IN(12);
int ftruncate(int __fd, off_t __length) __RENAME(ftruncate64) __INTRODUCED_IN(12);
#endif /* __ANDROID_API__ >= 12 */

#else
int truncate(const char* __path, off_t __length);
ssize_t pread(int __fd, void* __buf, size_t __count, off_t __offset)
    __overloadable __RENAME_CLANG(pread);
ssize_t pwrite(int __fd, const void* __buf, size_t __count, off_t __offset)
    __overloadable __RENAME_CLANG(pwrite);
int ftruncate(int __fd, off_t __length);
#endif


#if __ANDROID_API__ >= 21
int truncate64(const char* __path, off64_t __length) __INTRODUCED_IN(21);
#endif /* __ANDROID_API__ >= 21 */
```

I read it that way, that between API Level 12 and API Level 21 the function truncate will not be defined. In my environment I cannot currently upgrade to Level 21, so I'm stuck at API Level 19 :/

possible Fix could be to check if API Level is between 12 and 21 and add there the truncate function, because the truncate function will be calling the truncate64 at API Level 21+

#### Environment Details

Not all of these will be relevant to every bug, but please provide as much
information as you can.

* NDK Version: 16.0.4293906-beta1
* Build sytem: cmake
* Host OS: macOS 10.12.6
* Compiler: Clang
* ABI: armeabi-v7a
* STL: libc++
* NDK API level: 19
* Device API level: 26

**Comment by enh** [comment]
i'm assuming you're building with _FILE_OFFSET_BITS=64? previously this was a no-op, but now it actually means something. and we'll refuse to build if the 64-bit versions of the functions you're trying to use don't exist at the API level you're targeting.

see https://android-developers.googleblog.com/2017/09/introducing-android-native-development.html for more.

**Comment by Jakouf** [comment]
Actually I'm not using _FILE_OFFSET_BITS=64.

These are the defines I have from the compiler output:

```
-isystem /Users/jakouf/Library/Android/sdk/ndk-bundle/sources/cxx-stl/llvm-libc++/include -isystem /Users/jakouf/Library/Android/sdk/ndk-bundle/sources/android/support/include -isystem /Users/jakouf/Library/Android/sdk/ndk-bundle/sources/cxx-stl/llvm-libc++abi/include -isystem /Users/jakouf/Library/Android/sdk/ndk-bundle/sysroot/usr/include/arm-linux-androideabi -D__ANDROID_API__=19 -g -DANDROID -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -march=armv7-a -mfloat-abi=softfp -mfpu=vfpv3-d16 -fno-integrated-as -mthumb -Wa,--noexecstack -Wformat -Werror=format-security -std=c++11  -std=c++14 -frtti -fexceptions -ftemplate-depth=192 -Os -DNDEBUG  -fPIC -MD
```

The thing is still, that the function `truncate` is not defined when building with API Level 19.

**Comment by enh** [comment]
i think you're missing the most important line in your original quote:
```
#if defined(__USE_FILE_OFFSET64)

#if __ANDROID_API__ >= 21
int truncate(const char* __path, off_t __length) __RENAME(truncate64) __INTRODUCED_IN(21);
#endif /* __ANDROID_API__ >= 21 */


#if __ANDROID_API__ >= 12
ssize_t pread(int __fd, void* __buf, size_t __count, off_t __offset)
  __overloadable __RENAME(pread64) __INTRODUCED_IN(12);
ssize_t pwrite(int __fd, const void* __buf, size_t __count, off_t __offset)
  __overloadable __RENAME(pwrite64) __INTRODUCED_IN(12);
int ftruncate(int __fd, off_t __length) __RENAME(ftruncate64) __INTRODUCED_IN(12);
#endif /* __ANDROID_API__ >= 12 */

#else
int truncate(const char* __path, off_t __length);
ssize_t pread(int __fd, void* __buf, size_t __count, off_t __offset)
    __overloadable __RENAME_CLANG(pread);
ssize_t pwrite(int __fd, const void* __buf, size_t __count, off_t __offset)
    __overloadable __RENAME_CLANG(pwrite);
int ftruncate(int __fd, off_t __length);
#endif
```

so the `#else` is where you'd be if __FILE_OFFSET_BITS wasn't set. sure you're not setting it in your source? or the underlying implementation detail `__USE_FILE_OFFSET64`?

**Comment by Jakouf** [comment]
I just copied the defines, which where given to cmake from the gradle build. I was also just building for armeabi-v7. So if I understand that correctly. The gradle tool should normally define the __USE_FILE_OFFSET64 for cmake?

**Comment by enh** [comment]
no, __USE_FILE_OFFSET64 is _normally_ set internally by <sys/cdefs.h> if the public __FILE_OFFSET_BITS is set to 64. (but there's nothing we can do to prevent you from setting it directly manually, and we've seen cases where people do.)

i think if you put
```
#if defined(__USE_FILE_OFFSET64)
#error told you so
#endif
```
in the relevant source file you'll see it's getting set somewhere.

**Comment by Jakouf** [comment]
I found the issue: __USE_FILE_OFFSET64 gets defined by the Boost Library (1.56) I was using. Therefore I was running into the `#if defined(__USE_FILE_OFFSET64)` and there it is only available for API Level 21. Sorry for the inconvenience. Now I know where to find the issue and try to fix it. Thanks a lot.

**Comment by enh** [comment]
no worries. boost 1.64 is known to work fine, fwiw.
