### ISSUE TITLE
Old NDK download links not available

### ISSUE THREAD

**Issue by MarkVillacampa** [android-ndk/ndk#52]
In the NDK website, I can see download links for the latest version, and a revision history for old versions.

http://developer.android.com/intl/es/ndk/downloads/revision_history.html
http://developer.android.com/intl/es/ndk/downloads/index.html

However there is no way to download old versions.

As a workaround, you can construct the download link for older versions from the current one. E.g. for the Mac version of NDK r10e:

http://dl.google.com/android/repository/android-ndk-r10e-darwin-x86_64.zip

There should be a download link in the revision history.

**Comment by DanAlbert** [comment]
I've filed the bug internally. Until then I suppose we could add a wiki page here with links to the old NDKs.

**Comment by DanAlbert** [comment]
Posted links for r10e at https://github.com/android-ndk/ndk/wiki

**Comment by DanAlbert** [comment]
Sounds like we probably won't ever get these onto the official site. It should be sufficient for me to maintain the old links here though.

**Comment by MarkVillacampa** [comment]
Thanks for following up. I understand the need to not confuse users by having multiple versions in the official website.

As long as the files don't get removed from the server, and I have somewhere to point to when someone needs to download an old version, I'm fine with that :)
