### ISSUE TITLE
large (>60x) compile-time regression for x86 target with clang vs. gcc

### ISSUE THREAD

**Issue by froydnj** [android-ndk/ndk#522]
#### Description

We have (at least one) file in Firefox that shows a severe compile time regression when switching from gcc to clang when targeting x86.  Time to compile with gcc:

```
real	0m12.226s
user	0m12.008s
sys	0m0.596s
```

Time to compile with clang:

```
real	14m9.045s
user	14m8.656s
sys	0m0.376s
```

To emphasize: I can build all of Firefox on my machine (several million lines of C++) faster than clang can compile this one file.

https://github.com/froydnj/nsContentUtils-compile-regression contains preprocessed output from each compiler.  It also contains the output from invoking the compilers with `-v` so that command-line options, etc. can be seen.

Please let me know if you need any more details.

#### Environment Details

* NDK Version: 15c
* Build sytem: custom
* Host OS: Ubuntu 16.04
* Compiler: Clang, regression from GCC
* STL: libc++

**Comment by pirama-arumuga-nainar** [comment]
I was able to reproduce with the clang from r15c.  It does not reproduce in the next clang we are planning to update to (which is based on r307457).

@stephenhines or @DanAlbert may be able to comment on plans re: clang for r16.

**Comment by DanAlbert** [comment]
Spoke with @pirama-arumuga-nainar and he says the new Clang should be checked in tomorrowish, so we should be able to pick it up for r16 beta 2. It's a little risky to pick up a new compiler after beta 1, but given the number of outstanding Clang issues from r15 I think we should give it a shot.

**Comment by froydnj** [comment]
That's excellent, thank you!  I'll try r16b2 when it comes out to see how it does with Firefox.

**Comment by froydnj** [comment]
> Spoke with @pirama-arumuga-nainar and he says the new Clang should be checked in tomorrowish, so we should be able to pick it up for r16 beta 2.

Do you have an estimate of when r16 beta 2 is coming out?

**Comment by stephenhines** [comment]
The new clang will not be in r16 beta 2. We are looking at having it available in r17 at this point. It was too late and risky to change the compiler so late in the r16 process.

**Comment by froydnj** [comment]
> The new clang will not be in r16 beta 2. We are looking at having it available in r17 at this point.

😞  Thanks for the update!

**Comment by DanAlbert** [comment]
Fix is in master (r17).
