### ISSUE TITLE
An APK process crashes with SIGILL if automatic symbol loading is disabled in GDB by 'set auto-solib-add 0' before connecting to a target

### ISSUE THREAD

**Issue by dosvidos** [android-ndk/ndk#523]
#### Description

An APK process crashes with SIGILL if automatic symbol loading is disabled in GDB by 'set auto-solib-add 0' before connecting to a target

#### Environment Details

Not all of these will be relevant to every bug, but please provide as much
information as you can.

* NDK Version: 14.1.3816874 x64
* Build sytem: ndk-build
* Host OS: Windows
* NDK API level: 19
* Device API level: 21

**Comment by DanAlbert** [comment]
I've now triaged a ton of ndk-gdb things to r18. If they're going to eat into time that you think would be better spent on other issues, feel free to punt to r19.

**Comment by DanAlbert** [comment]
No follow up, closing. We'll reopen if we get the information we need.
