### ISSUE TITLE
Some redunant files in release

### ISSUE THREAD

**Issue by twaik** [android-ndk/ndk#524]
#### Redunant files in $NDK_ROOT/prebuilt/linux-x86_64/lib

Is $NDK_ROOT/prebuilt/linux-x86_64/lib/pkgconfig is actual for NDK?

#### Environment Details

* NDK Version: Latest.

**Comment by DanAlbert** [comment]
It's part of the Python distribution afaict. I'm not sure I understand the question.

**Comment by twaik** [comment]
Sorry. I thought it is needed for building NDK projects with configure/automake :)
