### ISSUE TITLE
Cross compiling grpc using android NDK  but stuck in pollset_work function

### ISSUE THREAD

**Issue by boyiliao9102** [android-ndk/ndk#526]
## ***Question**
I use ndk r15 standalone toolchain and am porting "google assistant-sdk-cpp with grpc" to android arm platform.

I also ported the curl and ssl packages to make it work. after got the run_assistant to run on the ARM Android platform, I found it stuck in

std::shared_ptr<ClientReaderWriter<ConverseRequest, ConverseResponse>>
stream(std::move(assistant->Converse(&context)));
in run_assistant.cc

I kept tracing the source, and found it stuck at

r = grpc_poll_function(pfds, pfd_count, timeout);
in the pollset_work() function in ev_poll_posix.c. Because grpc_poll_function is from the system poll point.

Is this an Android limitation, or porting issue?

## ***Host OS , ndk sdk version**
 ubuntu 14.04 as host , and porting using android-ndk-r15c-linux-x86_64.zip SDK

**## standalone toolchain**
./make_standalone_toolchain.py --arch arm --api 21 --force --install-dir pega_tmp/

because using Clang will cause error, so using  "arm-linux-androideabi-gcc , arm-linux-androideabi-g++"

**Comment by DanAlbert** [comment]
What's the question/bug here? This doesn't look like an NDK issue.
