### ISSUE TITLE
AMediaCodec and related types aren't defined when targeting an older API

### ISSUE THREAD

**Issue by rcombs** [android-ndk/ndk#529]
It's fairly reasonable for an application to want to make use of a feature that's not available in the OS version it's targeting. This can usually be done via runtime calls to `dlopen()` and `dlsym()`, or by using weak linking on platforms that support it.
The Android NDK makes this somewhat more difficult than necessary by removing the definitions of structs, enums, and other non-symbol definitions when targeting Android versions older than the one that introduced the APIs that make use of those types. It's possible to work around this by copying the type and macro definitions into consumer code, but this creates additional maintenance difficulties. Is there a reason these definitions need to be gated?

Relatedly, it'd be convenient if the NDK provided function-pointer typedefs for functions that a user could reasonably want to `dlsym()`.

**Comment by rcombs** [comment]
Actually, it'd be convenient for the function definitions to be provided as well, if only to expose their types to the GNU `typeof` operator. For instance:
```
typeof(AMediaCodec_start)* start = NULL;
void *handle = dlopen("libmediandk.so", RTLD_LOCAL);
if (handle)
  start = dlsym(handle, "AMediaCodec_start");
if (start)
  start(…);
```

Obviously this is very simplified, but it's distinctly more convenient than having to copy large potions of NDK into my own code.

**Comment by DanAlbert** [comment]
Agreed. I don't think it was intentional to hide all the types.

**Comment by DanAlbert** [comment]
Covered all the things in the media subdirectory: https://android-review.googlesource.com/#/c/platform/frameworks/av/+/503461

**Comment by alexcohn** [comment]
It will probably be easier to build a dummy stub for **libmediandk.so** and load it instead of the real library on API<21. You don't need **dlsym** then. You still don't want to call these dummy methods, and need a fallback plan.

**Comment by DanAlbert** [comment]
This is actually in r16 beta 2.
