### ISSUE TITLE
android-ndk-r15c\toolchains\llvm\prebuilt\windows director change breaks windows build

### ISSUE THREAD

**Issue by ggfan** [android-ndk/ndk#532]
**Note**: Bugs against Android Studio or Gradle should be filed at
http://b.android.com, not here.

Before filing a bug, check that you are using the latest version of the NDK. The
latest stable version and the preview release of the next stable version are
listed on our wiki: https://github.com/android-ndk/ndk/wiki#downloads.

Make sure your issue isn't on the list of common problems before filing a bug:
https://android.googlesource.com/platform/ndk/+/master/docs/user/common_problems.md

Delete everything above this line before submitting.

--------------------------------------------------------------------------------

#### Description
ndk-r15 changed the directory to:
  android-ndk-r15c\toolchains\llvm\prebuilt\windows
( int 14 it was ....\windows_x86-64)

seems other parts of NDK still expecting it to be at NDK-r14's location:

process_begin: CreateProcess(NULL, c:/Android/android-ndk-r15c/build//../toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe

in which case, none ndk-build under window + llvm will be able to build for ndk-r15

**Comment by DanAlbert** [comment]
Don't use the 32-bit NDK on a 64-bit system.

**Comment by ggfan** [comment]
this is all coming from fresh download, compile a hello-world application, and it could not compile. 
OS is 64 bit windows.

**Comment by ggfan** [comment]
Ok, yeah downloaded the 32 bit file
