### ISSUE TITLE
build error after upgraded to the latest ndk

### ISSUE THREAD

**Issue by hszhsh** [android-ndk/ndk#534]
--------------------------------------------------------------------------------

#### Description

I upgraded to the latest ndk(r15c and r16-beta1), and the following error occurred when building x86 libraries (arm libraries were built successfully):
Error:error: cannot open crtbegin_so.o: No such file or directory
Error:error: cannot open crtend_so.o: No such file or directory
Error:error: cannot find -lGLESv2
Error:error: cannot find -llog
Error:error: cannot find -landroid
Error:error: cannot find -lEGL
Error:error: cannot find -ldl
Error:error: cannot find -lm
Error:error: cannot find -lm
Error:error: cannot find -ldl
Error:error: cannot find -lc
Error:error: cannot find -ldl

#### Environment Details

Not all of these will be relevant to every bug, but please provide as much
information as you can.

* NDK Version: r15c and r16-beta1.
* Build sytem: cmake.
* Host OS: Mac.
* Compiler: clang.
* ABI: x86
* STL: default
* NDK API level: 19
* Device API level: 19

**Comment by DanAlbert** [comment]
We can't do anything without a repro case.

**Comment by Slion** [comment]
Same issue here.
`error: cannot open crtbegin_so.o: No such file or directory`
Building with GCC for armeabi.
Can't help much with repro I'm afraid cause our 3M C++ code lines repository is proprietary.
It was building fine with NDK 15.

**Comment by DanAlbert** [comment]
What about with clang?

**Comment by Slion** [comment]
I don't know, I did not get a chance to try it. I needed to implement something so I've switched back to NDK 15 for now. Hoping I can look at this again in the coming weeks.
