### ISSUE TITLE
Functions using off_t are inaccessible on 32-bit Android with largefile enabled on pre-API21

### ISSUE THREAD

**Issue by rcombs** [android-ndk/ndk#537]
The definition of mmap (for example):
```
void* mmap(void*, size_t, int, int, int, off_t);
```
Is hidden on 32-bit NDK pre-21 when `__USE_FILE_OFFSET64` is defined. This isn't entirely unreasonable, since `off_t` is 64-bit instead of 32-bit in that case, so leaving the definition as-is wouldn't match the library. Doing something like this:
```
void* mmap(void*, size_t, int, int, int, __kernel_off_t);
```
works fine for applications that hardcode 0 for the last arg, but could introduce truncation issues for other applications.

I'd like to propose adding unconditionally-declared prototypes like this:
```
void* mmap32(void*, size_t, int, int, int, __kernel_off_t) __RENAME(mmap);
```
This should allow applications that don't need 64-bit offsets to use mmap32() on 32-bit Android, without having to resort to hacks like this: https://ffmpeg.org/pipermail/ffmpeg-devel/2017-September/216828.html

* NDK Version: r15c
* Build system: N/A
* Host OS: N/A
* Compiler: N/A
* ABI: All 32-bit
* STL: N/A
* NDK API level: Pre-21
* Device API level: N/A

**Comment by fornwall** [comment]
> This should allow applications that don't need 64-bit offsets

Out of interest: If they don't need 64-bit offsets, why do they define `__USE_FILE_OFFSET64`?

**Comment by rcombs** [comment]
In the use-case I'm coming from (ffmpeg), the offset parameter is used in seeks, but not in `mmap()` (all calls to it have the offset parameter as a literal 0). So, in the general case, if it's using 64-bit offsets in some calls but doesn't need them in others.

**Comment by alexeikh-promon** [comment]
> If they don't need 64-bit offsets, why do they define __USE_FILE_OFFSET64?

I guess, because software can be cross-platform (not Android-centric) and it was always harmless to define `__USE_FILE_OFFSET64` on systems not supporting it, but useful on systems supporting it.

BTW, Boost.Filesystem defines `__USE_FILE_OFFSET64` for long time and thus can not be compiled for lower Android APIs with NDK r15.

There is a bug submitted to Boost about it: https://svn.boost.org/trac10/ticket/13230 .

**Comment by alexeikh-promon** [comment]
In case of Boost.Filesystem, it is even minimum API 24 that is needed, not API 21.

**Comment by DanAlbert** [comment]
iirc @enh had a reason why this wouldn't work, but idr what it was (sorry for not responding sooner, I thought he had).

**Comment by enh** [comment]
it wasn't that it wouldn't work so much as that i think anyone sophisticated enough to use that correctly is sophisticated enough to just add their own wrapper. i don't think it should be in the standard headers.

**Comment by McEmily** [comment]
What about the non-"sophisticated" users? Are we just stuck then because of our lack of sophistication?

**Comment by enh** [comment]
no, but you will need to upgrade to NDK r16 where good guy dan has you covered with a working 64-bit mmap for old API levels: https://android-review.googlesource.com/#/c/platform/bionic/+/503563/

**Comment by McEmily** [comment]
Oh, excellent! Thank you!

**Comment by enh** [comment]
and r16 was released yesterday, so you should be able to use this now.
