### ISSUE TITLE
Check how many hardware counters are available in my phone

### ISSUE THREAD

**Issue by brok85** [android-ndk/ndk#539]
Hi,
I have a couple of questions:

1) can I use simpleperf to know how many hardware counters are available on my device? To clarify, I am not talking about listing the available events, I am referring to how many counters can be programmed to keep track of some events.

2) Who exactly updates those counters? If I change the options -f and -c, am I affecting also the counting stored in the counter or just how often I read that counter?

Thanks a lot for the clarifications!

**Comment by yabinc** [comment]
1. can I use simpleperf to know how many hardware counters are available on my device?
If simpleperf stat --group option works correctly, the number of hardware counters is the max number of raw events you can attach to one --group option. But unfortunately, a bug makes --group option works as -e option, so this method doesn't work currently.
If you just want to know how many counters you can use freely without competition with the system (the kernel may use counters internally to do some statistic work), you can do as below:
a. use `simpleperf list raw` to show all raw events from arm pmu.
b. use `simpleperf stat -e xxx,xxx,xxx sleep 1`, add the number of used raw events until the time percentage isn't 100%.

2. Who exactly updates those counters? If I change the options -f and -c, am I affecting also the counting stored in the counter or just how often I read that counter?

Briefly, the kernel sets a initial value for a counter, then it is automatically decreased each time a corresponding event happens. And an irq is generated when the counter is zero. Then the kernel generates a samples and resets the initial value for the counter. It is similar to a timer. By -f or -c option, you are actually setting the initial value for the counter.

**Comment by brok85** [comment]
> a. use simpleperf list raw to show all raw events from arm pmu.
b. use simpleperf stat -e xxx,xxx,xxx sleep 1, add the number of used raw events until the time percentage isn't 100%.

I tried this method and it gives me 100% even with just 1 raw event. Does this mean that my device has only 1 counter?

**Comment by yabinc** [comment]
When running the stat command, if the number of hardware events is larger than the number of hardware counters available in the PMU, the kernel shares hardware counters between events, so each event is only monitored for part of the total time. In the example below, there is a percentage at the end of each row, showing the percentage of the total time that each event was actually monitored.
So if it is 100%, a hardware counter is fully allocated for an event. If it is < 100%, it means there are more events than hardware counters.

**Comment by brok85** [comment]
Sorry I didn't read carefully. My device has 6 counters then because whew I have 6 events I get all 100% but when I add 7 or more I get less than 100% for some of them.

Thanks a lot for the patience and explanation.
