### ISSUE TITLE
copy ASAN library to app install directory

### ISSUE THREAD

**Issue by DanAlbert** [android-ndk/ndk#540]
Now that Android has wrap.sh, we need to ship the ASAN runtime (or whatever sanitizer runtime) with the other shared libraries that are a part of the app. ndk-build should install this in the out directory with the rest of the shared libs.

cc @eugenis

**Comment by eugenis** [comment]
Yes, please! And it should also generate wrap.sh script.

**Comment by DanAlbert** [comment]
I was uncertain about that. I was thinking maybe it would be better to let the user do that so they can add any of their own behaviors, but I suppose as long as we allow them to do that as well then there's no problem with us providing a sensible default.

Probably will add an `APP_WRAP_SH_SCRIPT` or something. Will need to confirm that ndk-build is the sensible place to handle this though, since ndk-build doesn't do any of the app packaging. Might make more sense to do it in gradle.

**Comment by DanAlbert** [comment]
This actually ended up being a lot easier than I expected: https://android-review.googlesource.com/#/c/platform/ndk/+/618842

Too late for beta 1, but it will be in beta 2.

Note that I haven't looked into the wrap.sh generation yet, but this handles the more involved part of the work.

**Comment by DanAlbert** [comment]
Will be in beta 1 after all since we're still waiting for gradle fixes.

**Comment by eugenis** [comment]
I'd be happy to update that page or accept a pull request, but I don't know much about Gradle.

**Comment by enh** [comment]
@yabinc is probably our wrap.sh + gradle expert...

**Comment by yabinc** [comment]
Here is the part of doc in simpleperf showing how to add wrap.sh, https://android.googlesource.com/platform/prebuilts/simpleperf/+/master/doc/#prepare-an-android-application.
Here is an example of gradle code adding wrap.sh, https://android.googlesource.com/platform/system/extras/+/master/simpleperf/demo/SimpleperfExampleOfKotlin/app/profiling.gradle.
Hopefully that can give some help.
