### ISSUE TITLE
Android Studio NDK built has mixed end error results during build and apk execution

### ISSUE THREAD

**Issue by cmeng-git** [android-ndk/ndk#543]
## Description
Android Studio NDK built has mixed end error results during build and apk execution

I am using Windows 7 64-bit system and Ubuntu 16.04 64-bit system, both installed with Android Studio 2.3.3 and android-sdk/ndk version 15.2.4303891 (see below for details)

Most of time, I am using Windows 7 environment for android application development i.e. aTalk-android. 
aTalk-android uses either JNI share libraries built from source or pre-built static libraries downloaded  from online if available. The aTalk is using couples of native JNI build libraries including
a. libvpx - Standalone-chaintool on ubuntu (1.6.1+ i.e. master repository dated 10/12/2017)
b. opus - AS with NDK from source (v1.2.1)
c. openssl - standalone-chaintool on ubuntu (sourc -v1.0.2l) and pre-built static library (v1.0.2k online)
d. speex - AS with NDK from source (v1.2rc1)

Both opus and libvpx seem to be independent of the problems experienced as reported below.
The observed problem for
## openssl:
Using tool downloaded from https://github.com/leenjewel/openssl_for_ios_and_android
and source 1.0.2l from https://www.opus-codec.org/downloads
using standalone-chain running on ubuntu 16.04
I found that I have to set APP_PLATFORM = android-23 to build; otherwise facing problem with many undefined symbols e.g. stderr, stdin, stdout, atof, signal, tcsetattr , tcgetattr etc with api < 23.

With the static pre-built libraries (libcrypto.a and libss.a) from ubuntu, using them for aTalk apk build with AS (NDK) on windows 7. I found that I have also need to set to API-23, otherwise faced with undefined references to stderr, stdin and stdout during ndk built with API-21.

aTalk apk built ok, but when use, it throws undefined symbol i.e. stderr reference to by jnopenssl and fall back to use bouncycastle instead.

Eventually, I have to use v1.0.2k pre-built libraries releases (https://github.com/ahnan4arch/OpenSSL-for-Android-Prebuilt-1). Then it works with both API-21 or API-23 NDK linkage.

## speex
Using AS NDK (with build.gradle) and source (v1.2rc1); it is able built and linked into apk with either API-21 or API-23. However on application execution, it failed with API-23 build with the following error:
dlopen("/data/app/org.atalk.android-4/lib/arm/libjnspeex.so", RTLD_LAZY) failed: dlopen failed: cannot locate symbol "stderr" referenced by "libjnspeex.so"...

aTalk-android works ok when the speex is built with android-21.

## Conclusion:
static libraries for openssl and speex need contradicting requirements during NDK build i.e. android-23 and android-21; and gives undefined symbol "stderr" during execution.

What is the root cause for the undefined sysmbol "stderr when using android-23?
Appreciate for any proposed solution? 

##  ====== NDK Settings =====
* NDK Version: version 15.2.4303891
* Build sytem: ndk-build, standalone toolchain and gradle.build on windows 7 i.e.
    commandLine "$ndkDir/ndk-build.cmd",
            '-C' + projectDir + '/jni',
            '-j', Runtime.runtime.availableProcessors(),
            'all',
            'NDK_OUT=' + project.buildDir + '/obj',
            'NDK_LIBS_OUT=' + projectDir + '/libs/$(TARGET_ARCH_ABI)',
            'NDK_TOOLCHAIN_VERSION=4.9',
            'APP_PLATFORM=android-23'

* Host OS: Windows 7 and Ubuntu 16.04 (both 64-bits)
* Compiler: If GCC, check Clang before filing. GCC is no longer supported (tools default to use gcc on stanalone-toolchain).
* ABI: armeabi armeabi-v7a x86 mips
* STL: gnustl_static
* NDK API level: API-21 or API-23 with mixed results
* Device API level: Samsung SII 4.0.3 API-15 and 5.0 API-21

##  ====== APK build.gradle Settings =====
    minSdkVersion = 15
    compileSdkVersion = 25
    buildToolsVersion = '25.0.3'
    supportLibraryVersion = '25.3.1'
    gmsPlayServicesVersion = '11.0.4'

**Comment by DanAlbert** [comment]
https://android.googlesource.com/platform/ndk/+/master/docs/user/common_problems.md#using-mismatched-prebuilt-libraries

**Comment by cmeng-git** [comment]
Many thanks for the link and the information. I have checked my configuration setting against your provided link. Yes it did explain the problem for speex but not for other problems that I have encountered.

As for the openssl static library built using standalone toolchain on ubuntu, I just cannot set api < 23 as it gives may undefined references during built i.e. stdin, stdout, stderr, atof, signal tccsetattr, tcgetattr etc. Are there some options or library that I need to enable. Also using API < 21, other jni sources during AS NDK e.g. opus will also start to given similar undefined references during the build process.

Actually I would like to build all final jni libraries using api-15 for aTalk-android. Appreciate any suggestion to build the library using  api-15 without getting undefined references problem during build.

**Comment by enh** [comment]
Here's how stdin/stdout/stderr work on Android:
```
#if __ANDROID_API__ >= __ANDROID_API_M__
extern FILE* stdin __INTRODUCED_IN(23);
extern FILE* stdout __INTRODUCED_IN(23);
extern FILE* stderr __INTRODUCED_IN(23);

/* C99 and earlier plus current C++ standards say these must be macros. */
#define stdin stdin
#define stdout stdout
#define stderr stderr
#else
/* Before M the actual symbols for stdin and friends had different names. */
extern FILE __sF[] __REMOVED_IN(23);

#define stdin (&__sF[0])
#define stdout (&__sF[1])
#define stderr (&__sF[2])
#endif
```

so if you build >= M you'll get references to stdin/stdout/stderr. if you build < M, you'll get references to __sF instead.

glibc (afaik) only has stdin/stdout/stderr symbols. BSDs (afaik) only have __sF symbols.

Android < M only has __sF. Android >= has both stdin/stdout/stderr and __sF.

so if you're getting undefined references to stdin/stdout/stderr, you're *not* building for < 23 even if you think you are.

similarly functions like atof are provided as static inlines for < L --- see `<android/legacy_stdlib_inlines.h>`. so you've screwed up somewhere and you're not really building for the API level you think you are (and/or you're not even using our header files!).

btw, openssl is a real bastard to build. libressl builds out of the box.

i'll try speex later today, but i have to run to the dentist now :-)

**Comment by enh** [comment]
speex 1.2.0 builds out of the box for me for API level 15.

**Comment by cmeng-git** [comment]
Many thanks to all for the information to enlightened me on the NDK built. Actually I have already spent more than 3 weeks struggling to get info online and built JNI shared libraries with various API settings. The information provided are really helpful. 

Below are the latest test results on aTalk-android.
###  libvpx (v1.6.1+/master)
Able to build static library with API-15 using standalone toolchain running on Ubuntu

### speex (v1.2rc1)
NDK build within Android Studio with API-15 is OK

### openssl (1.0.2l) - aTalk openssl java wrapper is only compatible with v1.0.2x 
Build static library with API-15 using standalone toolchain running on Ubuntu failed with following linkage errors (only with API >=23 is ok):
```
openssl.o:openssl.c:function lock_dbg_cb: error: undefined reference to 'stderr'
openssl.o:openssl.c:function do_cmd: error: undefined reference to 'stdout'
openssl.o:openssl.c:function main: error: undefined reference to 'signal'
openssl.o:openssl.c:function main: error: undefined reference to 'stderr'
openssl.o:openssl.c:function main: error: undefined reference to 'stdout'
openssl.o:openssl.c:function main: error: undefined reference to 'stdin'
verify.o:verify.c:function cb: error: undefined reference to 'stdout'
verify.o:verify.c:function check: error: undefined reference to 'stdout'
verify.o:verify.c:function verify_main: error: undefined reference to 'signal'
verify.o:verify.c:function verify_main: error: undefined reference to 'stderr'
asn1pars.o:asn1pars.c:function asn1parse_main: error: undefined reference to 'signal'
asn1pars.o:asn1pars.c:function asn1parse_main: error: undefined reference to 'stderr'
asn1pars.o:asn1pars.c:function asn1parse_main: error: undefined reference to 'stdin'
req.o:req.c:function req_main: error: undefined reference to 'signal'
req.o:req.c:function req_main: error: undefined reference to 'stdin'
req.o:req.c:function req_main: error: undefined reference to 'stdin'
speed.o:speed.c:function speed_main: error: undefined reference to 'atof'
speed.o:speed.c:function speed_main: error: undefined reference to 'atof'
speed.o:speed.c:function speed_main: error: undefined reference to 'atof'
speed.o:speed.c:function speed_main: error: undefined reference to 'atof'
../libcrypto.a(ui_openssl.o):ui_openssl.c:function read_string_inner: error: undefined reference to 'tcsetattr'
../libcrypto.a(ui_openssl.o):ui_openssl.c:function read_string_inner: error: undefined reference to 'tcsetattr'
../libcrypto.a(ui_openssl.o):ui_openssl.c:function open_console: error: undefined reference to 'tcgetattr'
collect2: error: ld returned 1 exit status
make[2]: *** [link_app.] Error 1
```

Using v1.0.2k pre-built static libraries releases (https://github.com/ahnan4arch/OpenSSL-for-Android-Prebuilt-1) failed to build the shared library linking in java wrapper on AS when API-15 is used. 
```
openssl/android/armeabi/lib/libcrypto.a(ui_openssl.o):ui_openssl.c:function read_string_inner: error: undefined reference to 'signal'
openssl/android/armeabi/lib/libcrypto.a(ui_openssl.o):ui_openssl.c:function read_string_inner: error: undefined reference to 'tcsetattr'
openssl/android/armeabi/lib/libcrypto.a(ui_openssl.o):ui_openssl.c:function read_string_inner: error: undefined reference to 'tcsetattr'
openssl/android/armeabi/lib/libcrypto.a(ui_openssl.o):ui_openssl.c:function open_console: error: undefined reference to 'tcgetattr

```
I have to set AS NDK to API-21 in order to get it to build the shared library without error. Look likes the online openssl static library v.1.0.2k may had built with API-21. 

### Conclusion
Wtih the NDK built for openssl support disabled on aTalk apk build; and using libvpx and speex shared/static libraries built with API-15, both the codec's i.e. speex and vpx are tested working on both the Note 3 and Samsung SII (- previously not working when build with api-21) .

In order to get openssl support on aTalk, I really need to build the static library from source on ubuntu with API-15.

enh,
Thanks for the explanation. my understanding from your previous comment is that it explains on how android internally handle <M> case for some of the stadlib references etc. There is no actual solution given for the undefined symbols for openssl static library built with API-15.

Appreciate if you or someone is able to offer some solution to build openssl static library with API-15.

**Comment by cmeng-git** [comment]
Finally resolved all the problems and got the openssl source to compile and build  the shared library with NDK under Android Studio 2.3 environment and with API-15

a. With the source downloaded from the following link:
https://github.com/aosp-mirror/platform_external_openssl/tree/android-5.1.1_r38
b. unzip the source into AS project sub-directory jni 
c. Modified all the .mk files so it builds the static libraries for libcrypto.a and libssl.a
   I also merged the various -32.mk/-64.mk files of the same into one file for easy future maintenance.
d. Build shared library with the java API wrapper together with the two static *.a libraries.

However  I have to perform the build with Android Studio 2.3 running under ubuntu 16.04. When build under Windows 7, I faced the following problem:
NDK builds libssl.a without problem. However it throws the following error when linking libcrypto.a i.e. Error 87. I believe it is the NDK argument list too long when run under Windows 7.

```
process_begin: CreateProcess(NULL, C:/Android/android-sdk/ndk-bundle/build//../toolchains/arm-linux-androideabi-4.9/prebuilt/windows-x86_64/bin/arm-linux-androideabi-gcc-ar crsD
 D:\workspace\Android\atalk-android\aTalk\build/local/armeabi-v7a/libcrypto.a
 D:\workspace\Android\atalk-android\aTalk\build/local/armeabi-v7a/objs/crypto/crypto/aes/aes_cbc.o
 D:\workspace\Android\atalk-android\aTalk\build/local/armeabi-v7a/objs/crypto/crypto/aes/aes_cfb.o
 D:\workspace\Android\atalk-android\aTalk\build/local/armeabi-v7a/objs/crypto/crypto/aes/aes_ctr.o 
 .....
 D:\workspace\Android\atalk-android\aTalk\build/local/armeabi-v7a/objs/crypto/crypto/sha/asm/sha1-armv4-large.o
 D:\workspace\Android\atalk-android\aTalk\build/local/armeabi-v7a/objs/crypto/crypto/sha/asm/sha256-armv4.o
 D:\workspace\Android\atalk-android\aTalk\build/local/armeabi-v7a/objs/crypto/crypto/sha/asm/sha512-armv4.o, ...) failed.

make: *** [D:\workspace\Android\atalk-android\aTalk\build/local/armeabi-v7a/libcrypto.a] Error 87
make: *** Waiting for unfinished jobs....
```
So I add the option to crypto.mk i.e.
LOCAL_SHORT_COMMANDS := true
However after 1 hours of building, it throws error. Actually the OPENSSLDIR  is defined in jni/android.mk as OPENSSL_DIR := openssl.

```
openssl/crypto/cversion.c: In function 'SSLeay_version':
<command-line>:0:12: error: invalid operands to binary / (have 'char *' and 'int (*)(const char *)')
openssl/crypto/cversion.c:105:27: note: in expansion of macro 'OPENSSLDIR'
   return "OPENSSLDIR: \"" OPENSSLDIR "\"";
                           ^
<command-line>:0:20: error: 'lib' undeclared (first use in this function)
openssl/crypto/cversion.c:105:27: note: in expansion of macro 'OPENSSLDIR' is defined in the jni/android.mk file as OPENSSL_DIR := openssl
   return "OPENSSLDIR: \"" OPENSSLDIR "\"";
                           ^
<command-line>:0:20: note: each undeclared identifier is reported only once for each function it appears in
openssl/crypto/cversion.c:105:27: note: in expansion of macro 'OPENSSLDIR'
   return "OPENSSLDIR: \"" OPENSSLDIR "\"";
                           ^
<command-line>:0:24: error: 'ssl' undeclared (first use in this function)
openssl/crypto/cversion.c:105:27: note: in expansion of macro 'OPENSSLDIR'
   return "OPENSSLDIR: \"" OPENSSLDIR "\"";
                           ^
openssl/crypto/cversion.c:105:38: error: expected ';' before string constant
   return "OPENSSLDIR: \"" OPENSSLDIR "\"";
```
When build under Ubuntu, I do not have to set the option LOCAL_SHORT_COMMANDS := true and the build took only ~62 seconds.

Look like I may have to switch my android studio development environment to run under ubuntu.
