### ISSUE TITLE
Sha1.h disappeared from all the platforms on NDK r11b ?

### ISSUE THREAD

**Issue by TimonLio** [android-ndk/ndk#55]
On NDK r10e, all the platforms provide sha1.h.
After upgrade to r11, seems the sha1.h was removed from all platforms, and my project will failed to compile.
Must I compile and link with OpenSSL or BoringSSL from now on ?

**Comment by DanAlbert** [comment]
Yes, you'll need to get checksum functions from a proper place (it was a bug that they were ever in libc).
