### ISSUE TITLE
NDK shared library build for libvpx with x86 static library has undefined reference to 'rand'

### ISSUE THREAD

**Issue by cmeng-git** [android-ndk/ndk#557]
#### Description
I am building the libvpx.so shared libraries from multiple pre-built static libraries using standalone-toolchains on Ubuntu 16.04; Library source is based on libvpx version 1.6.1+ (master downloaded on Oct 13, 2017)

The shared libraries are built using NDK running on Android Studio 3.0 for ABI: armeabi armeabi-v7a x86. For the armeabi and armeabi-v7a, the shared libraries compiled and built without any problem and tested working on both Android API-15 and API-21 devices. However for x86 shared library built, NDK throws the following errors:
```
vpx/android/x86/lib/libvpx.a(add_noise.c.o):function vpx_plane_add_noise_c: error: undefined reference to 'rand'
vpx/android/x86/lib/libvpx.a(add_noise.c.o):function vpx_setup_noise: error: undefined reference to 'rand'
collect2: error: ld returned 1 exit status
make: *** [/home/cmeng/workspace/android/atalk-android/aTalk/build/local/x86/libjnvpx.so] Error 1
```
The errors are due to apx_dsp/add_noise.c which makes call to rand() function. My understanding is that the rand() function call should have been replaced with inline macro during the x86 static library built for API android-15 platform. I tried some of the proposed fixed from online site:
https://stackoverflow.com/questions/28010753/android-ndk-returns-an-error-undefined-reference-to-rand
  
I managed to fix the rand() call from asm sources with "export ASFLAGS=-D__ANDROID__". However I did not make any progress on the add_noise.c source rand() call. Is there some parameters I need to specify during the x86 static library built?

The static libvpx.a is built with the following configuration using standalone-toolchains on ubuntu-16.04

```
**********************************************
use ANDROID_API=15
use NDK=/opt/android/android-sdk/ndk-bundle
export ARCH=android-x86
export NDK_TOOLCHAIN_BASENAME=/usr/local/src/android/libvpx.git/libvpx/x86-android-toolchain/bin/i686-linux-android
export SYSROOT=/usr/local/src/android/libvpx.git/libvpx/x86-android-toolchain/sysroot
export CC=/usr/local/src/android/libvpx.git/libvpx/x86-android-toolchain/bin/i686-linux-android-gcc
export CXX=/usr/local/src/android/libvpx.git/libvpx/x86-android-toolchain/bin/i686-linux-android-g++
export LINK=/usr/local/src/android/libvpx.git/libvpx/x86-android-toolchain/bin/i686-linux-android-g++
export LD=/usr/local/src/android/libvpx.git/libvpx/x86-android-toolchain/bin/i686-linux-android-ld
export AR=/usr/local/src/android/libvpx.git/libvpx/x86-android-toolchain/bin/i686-linux-android-ar
export RANLIB=/usr/local/src/android/libvpx.git/libvpx/x86-android-toolchain/bin/i686-linux-android-ranlib
export STRIP=/usr/local/src/android/libvpx.git/libvpx/x86-android-toolchain/bin/i686-linux-android-strip
export CPPFLAGS=
export CFLAGS=-march=i686 -mtune=intel -msse3 -mfpmath=sse -m32 -fpic -ffunction-sections -funwind-tables -fstack-protector -fno-strict-aliasing -finline-limit=64
export CXXFLAGS=-march=i686 -mtune=intel -msse3 -mfpmath=sse -m32 -fpic -ffunction-sections -funwind-tables -fstack-protector -fno-strict-aliasing -finline-limit=64 -std=c++11 -frtti -fexceptions
export LDFLAGS=
export LIBS=
export ASFLAGS=-D__ANDROID__
**********************************************
./configure --target=x86-android-gcc --disable-runtime-cpu-detect --disable-examples --disable-tools --sdk-path=/opt/android/android-sdk/ndk-bundle/ --prefix=/usr/local/src/android/libvpx.git/libvpx/libs/x86
  disabling examples
  disabling tools
  enabling vp8_encoder
  enabling vp8_decoder
  enabling vp9_encoder
  enabling vp9_decoder
Configuring for target 'x86-android-gcc'
  enabling x86
  enabling runtime_cpu_detect
  enabling mmx
  enabling sse
  enabling sse2
  enabling sse3
  enabling ssse3
  enabling sse4_1
  enabling avx
  enabling avx2
  using yasm
  enabling postproc
  enabling webm_io
  enabling libyuv
Creating makefiles for x86-android-gcc libs
```

#### Environment Details
    NDK Version: version 15.2.4203891
    Build sytem: ndk-build with static libraries generated using standalone toolchains on Ubuntu 16.04
    using build.gradle i.e.
  ```
  commandLine "$ndkDir/ndk-build",
    '-C' + projectDir + '/jni',
    '-j', Runtime.runtime.availableProcessors(),
    'all',
    'NDK_OUT=' + project.buildDir,
    'NDK_LIBS_OUT=' + projectDir + '/libs/$(TARGET_ARCH_ABI)',
    'NDK_TOOLCHAIN_VERSION=4.9'
```
    Host OS: Ubuntu 16.04 64-bits
    Compiler: tools default to use gcc on stanalone-toolchain
    ABI: armeabi armeabi-v7a x86
    STL: system
    NDK API level: API-15
    Device API level: API-15 and API-21

    Android Studio: 3.0 on Ubuntu 16.04

**Comment by alexcohn** [comment]
An easy fix would be to set `-Drand=(int)lrand48` in CFLAGS.

**Comment by rprichard** [comment]
It looks like the standalone toolchain's gcc compiler defines `__ANDROID__` to 1, but leaves `__ANDROID_API__` undefined. The standalone clang compiler, OTOH, defines both; `__ANDROID_API__` is defined to the API level used to create the standalone toolchain.

This might be expected behavior -- see https://github.com/android-ndk/ndk/wiki/Changelog-r14:

> Standalone toolchains using GCC do not work out of the box with unified headers. They can be made to work by passing -D__ANDROID_API__=21 (replacing 21 with the same API level you passed to make_standalone_toolchain.py) when compiling.

If `__ANDROID_API__` is undefined, then we define it to 10000 in sysroot/usr/include/android/api-level.h:

```
#ifndef __ANDROID_API_FUTURE__
#define __ANDROID_API_FUTURE__ 10000
#endif

#ifndef __ANDROID_API__
#define __ANDROID_API__ __ANDROID_API_FUTURE__
#else
#define __ANDROID_NDK__ 1
#endif
```

(Aside: api-level.h isn't going to define `__ANDROID_NDK__` in this situation.)

stdlib.h will declare `rand` here:

```
#if __ANDROID_API__ >= __ANDROID_API_L__
...
int rand(void) __INTRODUCED_IN(21);
...
#else
// Implemented as static inlines before 21.
#endif
```

I think adding ` -D__ANDROID_API__=15` to `CFLAGS` and `CXXFLAGS` will fix the problem. vpx's build system doesn't appear to use `CPPFLAGS`, so adding the option there has no effect.

**Comment by rprichard** [comment]
I agree this issue is invalid. A few other random things I noticed:

 * We aren't supporting GCC anymore, so a better fix may be to switch to Clang.

 * When I tried to build vpx, it complained that yasm wasn't installed. I installed it, but you might want to use the NDK yasm.

 * I don't think `ARCH`, `NDK_TOOLCHAIN_BASENAME`, or `CPPFLAGS` need to be exported.

 * When I tried building it with Clang, I noticed that add_noise.c.o had a non-global `rand` and an undefined `lrand48`. That's fine, but it indicates that the compiler isn't optimizing. Add -O2, etc.

Here's what I used:

```
    NDK_TOOLCHAIN_BASENAME=$HOME/standalone-x86-15
    export SYSROOT=$NDK_TOOLCHAIN_BASENAME/sysroot
    export CC=$NDK_TOOLCHAIN_BASENAME/bin/clang
    export CXX=$NDK_TOOLCHAIN_BASENAME/bin/clang++
    export LINK=$NDK_TOOLCHAIN_BASENAME/bin/clang++
    export LD=$NDK_TOOLCHAIN_BASENAME/bin/i686-linux-android-ld
    export AR=$NDK_TOOLCHAIN_BASENAME/bin/i686-linux-android-ar
    export AS=$NDK_TOOLCHAIN_BASENAME/bin/yasm
    export RANLIB=$NDK_TOOLCHAIN_BASENAME/bin/i686-linux-android-ranlib
    export STRIP=$NDK_TOOLCHAIN_BASENAME/bin/i686-linux-android-strip
    export CFLAGS='-O2 -march=i686 -mtune=intel -msse3 -mfpmath=sse -m32 -fpic -ffunction-sections -funwind-tables -fstack-protector -fno-strict-aliasing -finline-limit=64'
    export CXXFLAGS='-O2 -march=i686 -mtune=intel -msse3 -mfpmath=sse -m32 -fpic -ffunction-sections -funwind-tables -fstack-protector -fno-strict-aliasing -finline-limit=64 -std=c++11 -frtti -fexceptions'
    export LDFLAGS=
    export LIBS=
    export ASFLAGS=-D__ANDROID__

    ./configure --target=x86-android-gcc --disable-runtime-cpu-detect --disable-examples --disable-tools --sdk-path=$HOME/android-sdk/ndk-bundle --prefix=$PWD/out
```

**Comment by cmeng-git** [comment]
Thanks for the information and recommendations. I have moved to use clang as recommended. Everything is now working with rprichard's proposed export parameters.

Bu the way the below option is only applicable to armeabi; and is being ignored in other architectures.
"-finline-limit=64"

Also earlier standalone toolchains options defined in the my script i.e.
"-march=armv7-a -Wl,--fix-cortex-a8" is no more applicable when moving to clang/clang++
