### ISSUE TITLE
Typo in regex match in NDK 16b2 toolchain file

### ISSUE THREAD

**Issue by nargus** [android-ndk/ndk#558]
In android.toolchain.cmake, line# 167 of NDK 16b2. The line currently contains:

`if(ANDROID_PLATFORM MATCHES "^android-([0-8]|1[0-13])$")`

This appears to be a typo? As the second block would only match against 10, 11, and 13, skipping 12. Unless I'm missing something?

#### Environment Details

* NDK Version: 16.0.4414007-beta2

**Comment by rprichard** [comment]
It's also skipping 9. Looks like a typo to me. Here's the relevant commit:

https://android.git.corp.google.com/platform/ndk/+/8a4961a0fc90791dec132cabedd2931f3acc4405%5E%21/

**Comment by DanAlbert** [comment]
Merged the fix into r16.
