### ISSUE TITLE
error: unknown type name 'ACameraDevice_StateCallbacks'

### ISSUE THREAD

**Issue by 0xFelix** [android-ndk/ndk#559]
#### Description

When including the Camera2 API NdkCameraManager.h header the following error is thrown:

`C:/Users/fmatouschek/AppData/Local/Android/sdk/ndk-bundle/sysroot/usr/include/camera/NdkCameraManager.h:273:9: error: unknown type name 'ACameraDevice_StateCallbacks'
         ACameraDevice_StateCallbacks* callback,`

I think the type `ACameraDevice_StateCallbacks` is misspelled, renaming it to `ACameraDevice_stateCallbacks` resolves the error.

#### Environment Details

* NDK Version: 15.2.4203891
* Build sytem: Custom build for ffmpeg (https://github.com/0xFelix/avbuild)
* Host OS: Windows
* Compiler: GCC
* ABI: armeabi-v7a
* STL: gnustl
* NDK API level: 24
* Device API level: 25

**Comment by enh** [comment]
looking at the .cpp source i think they actually intended S but screwed up the typedef:
```
typedef struct ACameraDevice_StateCallbacks {
...
} ACameraDevice_stateCallbacks;
```
none of the other typedefs differ in case like this, but i'll forward this to the engineer responsible to check...

**Comment by DanAlbert** [comment]
Merged into r17.
