### ISSUE TITLE
ndk-which should work with different ABIs

### ISSUE THREAD

**Issue by tux-mind** [android-ndk/ndk#56]
`ndk-which` [uses only the armeabi ABI](https://android.googlesource.com/platform/ndk.git/+/ndk-r11b/ndk-which#48).

in my specific case `ndk-which strip` gives `$NDK_ROOT/toolchains/arm-linux-androideabi-4.8/prebuilt/linux-x86_64/bin/arm-linux-androideabi-strip` when what I want is `$NDK_ROOT/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64/bin/aarch64-linux-android-strip`.

I think that ndk-which shall accept an optional argument or change it's behaviour from the current environment.

Best regards.

**Comment by enh** [comment]
maybe add "--abi x86" or something. should probably move to python at the same time to benefit Windows users (rather than do bash argument parsing).

**Comment by enh** [comment]
https://android-review.googlesource.com/c/platform/ndk/+/722891 added --abi and switched the default.

https://android-review.googlesource.com/c/platform/ndk/+/723009 cherrypicked this for r18 beta 2.

**Comment by DanAlbert** [comment]
Merged into r18.
