### ISSUE TITLE
'catopen' undeclared. Test case provided.

### ISSUE THREAD

**Issue by hoodar** [android-ndk/ndk#560]
#### Description

While compiling any cpluplus code concerned with STL locale header file, an error will 
occur like below.
`include/c++/4.9.x\locale:3548:30: error: use of undeclared identifier 'catopen'
    catalog __cat = (catalog)catopen(__nm.c_str(), NL_CAT_LOCALE);`

catopen is used because _LIBCPP_HAS_CATOPEN is defined.
`#ifdef _LIBCPP_HAS_CATOPEN
    catalog __cat = (catalog)catopen(__nm.c_str(), NL_CAT_LOCALE);
    if (__cat != -1)
        __cat = static_cast<catalog>((static_cast<size_t>(__cat) >> 1));
    return __cat;
#else // !_LIBCPP_HAS_CATOPEN
    return -1;
`
But, in nl_types.h, catopen is not declared since __ANDROID_API__ =14
`
#if __ANDROID_API__ >= 26
nl_catd catopen(const char* __name, int __flag) __INTRODUCED_IN(26);
char* catgets(nl_catd __catalog, int __set_number, int __msg_number, const char* __msg) __INTRODUCED_IN(26);
int catclose(nl_catd __catalog) __INTRODUCED_IN(26);
#endif /* __ANDROID_API__ >= 26 */`

#### Environment Details
* NDK Version: 16b2
* Build sytem:  standalone toolchain
* Host OS: Windows 32bit
* Compiler: clang
* STL: libc++
* NDK API level: 14
* Device API level: NA

**Comment by enh** [comment]
seems like `_LIBCPP_HAS_CATOPEN` shouldn't be set...

```
#if defined(__unix__) || (defined(__APPLE__) && defined(__MACH__))
// Most unix variants have catopen.  These are the specific ones that don't.
#if !defined(__BIONIC__) && !defined(_NEWLIB_VERSION)
#define _LIBCPP_HAS_CATOPEN 1
#endif
#endif
```

**Comment by DanAlbert** [comment]
The bug as titled is working as intended. There was no `catopen` in android-14. Do you have a test case?

**Comment by hoodar** [comment]
test.cpp has just one line:
`#include <istream>`

Compiling command line:
clang50.exe  --sysroot=/ndk/ndk16b2/sysroot -target armv7-none-linux-androideabi  -D__ANDROID_API__=14  -Ijson test.cpp -o test.o

json is the subpath of header files from jsoncpp: [https://github.com/open-source-parsers/jsoncpp/tree/master/include/json](url)

**Comment by DanAlbert** [comment]
Works for me if I invoke the compiler correctly. If I use the command line you provided I get a different set of errors (can't find `asm/types.h` and things since that sysroot is wrong).

> -target armv7-none-linux-androideabi

Why are you passing this? The whole point of standalone toolchains is that you don't have to do this.

> --sysroot=/ndk/ndk16b2/sysroot

Is that the path to your standalone toolchain, or is that $NDK/sysroot? The latter would be incorrect, and the former is completely unnecessary.

> clang50.exe

For `C++` code you want clang++. For C you want `clang`. `clang50` is the non-wrapped binary that doesn't do any of the standalone toolchain things for you.

> -D__ANDROID_API__=14

Harmless, but unnecessary for Clang.

**Comment by DanAlbert** [comment]
If you can show me the exact steps you used to generate your toolchain and build, I won't have to guess and we can get you an answer...

**Comment by hoodar** [comment]
The root cause for this issue is the same header file named features.h in libjsoncpp and libcxx. clang uses the file in libjson instead of the one in libcxx since -Ijson is specified in command line. 

I solved this problem by changing features.h in libcxx to libxx_features.h.

**Comment by DanAlbert** [comment]
That doesn't sound like the right fix. That header shouldn't be shadowed. You've probably just created some new problems for yourself.

Looking at jsoncpp, theirs is supposed to be json/features.h, not features.h. You want `-Ijsoncpp/include`, not `-Ijsoncpp/include/json`.

**Comment by theawless** [comment]
I had been scratching my head over a similar problem for a long time before I ended up here. For me too, the error was caused by my features.h and the libcxx one.
Thanks for pointing that out!

**Comment by sbytov** [comment]
Thanks, that was my problem too

**Comment by leanid** [comment]
Several hours of investigations and here is solution, Thanks!

**Comment by loohoo** [comment]
I am compile cocos2d-x android project with ndk-r16b.  
once include iostream into header file， the compile will fail like below:
![Screen Shot 2019-11-30 at 10 56 28 AM](https://user-images.githubusercontent.com/7367421/69946876-66279780-1527-11ea-8de9-d24875a2bfb4.png)

I don't know how to fix it.

**Comment by enh-google** [comment]
upgrade to a current NDK.

**Comment by loohoo** [comment]
> upgrade to a current NDK.
upgrade to a current NDK（r20b） didn't help.
I try to mod PROP_MIN_SDK_VERRSION=16 to 26 in gradle.properties file can fix the problem.
but I am afraid old version android os could not run my app .

**Comment by enh-google** [comment]
this in libc++ should be keeping you safe:
```
#if defined(__unix__) || (defined(__APPLE__) && defined(__MACH__))
// Most unix variants have catopen.  These are the specific ones that don't.
#  if !defined(__BIONIC__) && !defined(_NEWLIB_VERSION)
#    define _LIBCPP_HAS_CATOPEN 1
#  endif
#endif
```
you can check with readelf whether your .so file has any references to catopen().
