### ISSUE TITLE
fseeko() undeclared identifier error if (__ANDROID_API__ < 24)

### ISSUE THREAD

**Issue by nargus** [android-ndk/ndk#563]
On NDK 16b2, in /sysroot/usr/include/stdio.h, functions fseeko() and ftello() appears to only be defined if (__ANDROID_API__ >= 24). While previously, both functions can be found in the platform-specific stdio.h of API version 23, e.g.:-

File /platforms/android-23/arch-arm/usr/include/stdio.h contains the function definitions on line 291 and 292.

This causes compiler error in <fstream> while compiling on non-Windows platform using API<24, due to _LIBCPP_HAS_NO_OFF_T_FUNCTIONS being undefined.

#### Environment Details

* NDK Version: 16.0.4414007-beta2
* Build sytem: cmake with android toolchain
* Host OS: Mac
* Compiler: Clang
* ABI: armeabi-v7a
* STL: c++_static
* NDK API level: android-23

**Comment by DanAlbert** [comment]
Read the section about `_FILE_OFFSET_BITS=64`: https://android-developers.googleblog.com/2017/09/introducing-android-native-development.html

**Comment by nargus** [comment]
I've read the section. And I think I'm missing something here; I've checked, and my problem isn't about _FILE_OFFSET_BITS, but rather; According to __config file in cxx-stl/llvm-libc++, _LIBCPP_HAS_NO_OFF_T_FUNCTIONS is only defined if either _LIBCPP_MSVCRT or _NEWLIB_VERSION are defined.

_LIBCPP_MSVCRT is only defined on Windows with MSVC compiler, and I can't find anywhere in the library where _NEWLIB_VERSION is defined. Nowhere in it does it seem to check for _FILE_OFFSET_BITS?

So, unless I'm missing something, <fstream> will always use the off_t version even on 32-bits build and without _FILE_OFFSET_BITS, unless it is being compiled on Windows?

**Comment by enh** [comment]
try reading it again... if you look at stdio.h (https://android.googlesource.com/platform/bionic/+/master/libc/include/stdio.h) you'll see (with all the noise removed):
```
#if defined(__USE_FILE_OFFSET64)
int fseeko(FILE* __fp, off_t __offset, int __whence) __RENAME(fseeko64) __INTRODUCED_IN(24);
#else
int fseeko(FILE* __fp, off_t __offset, int __whence);
#endif
```
and `__USE_FILE_OFFSET64` is only set if `__FILE_OFFSET_BITS=64`.
