### ISSUE TITLE
Question "undeclared identifier 'atomic_dec' or "atomic_inc'"

### ISSUE THREAD

**Issue by superbderrick** [android-ndk/ndk#565]
HI, I'm using ndk-r15c-darwin-x86_64, Currently I am trying to change my build configuration from GCC Compiler to Clang with latest NDK Version .

But I have met compile error regarding of Linux Thread synchronize APIs..

 **error: use of undeclared identifier '__atomic_inc'
        return __atomic_inc( pValue );
               ^
error: use of undeclared identifier '__atomic_dec'
        return __atomic_dec( pValue );**

Actually I declare below headers, Is there any way to avoid this error? 

>---

#include <errno.h>
#include <unistd.h>
#include <stdatomic.h>
#include <string.h>
#include <stdlib.h>    
>---

NDK Version: ndk-r15c-darwin-x86_64
Build sytem: ndk-build
Host OS: Mac Sierra 10.12.6
Compiler: Clang
ABI: armeabi-v7a
STL: gnustl_static

Thanks.
Best Regards.
Derrick.

**Comment by DanAlbert** [comment]
> error: use of undeclared identifier '__atomic_inc'

What file is this coming from? There's no such thing as `__atomic_inc` in a modern NDK, regardless of GCC or Clang. That's the old sys/atomics.h stuff that was dropped in favor of stdatomic.h.

**Comment by superbderrick** [comment]
Thanks good reply, I misinterpreted Api's origin.
I fixed my problem ,
Thanks
