### ISSUE TITLE
as-needed

### ISSUE THREAD

**Issue by alexcohn** [android-ndk/ndk#568]
Why doesn't NDK set `-Wl,--as-needed` by default? There seem to be no negative effects expected, but the clutter in ELF headers may be reduced.

**Comment by DanAlbert** [comment]
I can't think of any compelling reasons not to off the top of my head. @colincross: is this something you've considered enabling in the platform?

**Comment by colincross** [comment]
IIRC, the concerns with -Wl,--as-needed are shared libraries that are not used directly but whose static constructors affect global state (for example adding a signal handler), or if symbols are moved to different libraries at runtime.  Neither seems common though.  I would like to do an experiment in the platform where I add -Wl,--as-needed and see what gets removed.

**Comment by enh** [comment]
FWIW, gentoo seems to claim that they found no examples of that class of failure (https://wiki.gentoo.org/wiki/Project:Quality_Assurance/As-needed#Initializers_and_Deconstructors), but that doesn't mean it's not a common mistake amongst Android developers.

**Comment by rprichard** [comment]
Is this something we'd enable in the ndk-build/CMake build systems or in the driver?

**Comment by stephenhines** [comment]
I would advocate for not putting this in the driver. This can indeed have correctness implications which I don't think we should alter at this point.

**Comment by alexcohn** [comment]
IMHO, there is no justification in putting this in the driver. The [entry](https://wiki.gentoo.org/wiki/Project:Quality_Assurance/As-needed#Initializers_and_Deconstructors) in gentoo wiki explains why this flag should not be enforced. OTOH, I am aware of no negative effect of *not using* `--as-needed` (except esthetical). So, I guess Elliott answered my question, and no further action is actually necessary.

**Comment by rprichard** [comment]
Ok, so if we did add this flag, we'd put it in the build systems, but maybe there's no good reason to add it?

FWIW: I noticed some behavioral differences in `--as-needed` between bfd and gold on a test project with solibs that didn't declare dependencies. e.g.:
 - main exe: calls `f`
 - libtest2.so: defines `f`, which calls `g`. (no DT_NEED of libtest3.so)
 - libtest3.so: defines `g`
 - linking main with the command line: -ltest3 -ltest2
    - without --as-needed: links OK, main needs libtest3.so, libtest2.so
    - bfd --as-needed: doesn't link
    - gold --as-needed: links OK, main needs libtest2.so
 - linking main with the command line: -ltest2 -ltest3
    - without --as-needed: links OK, main needs libtest2.so, libtest3.so
    - bfd --as-needed: links OK, main needs libtest2.so, libtest3.so
    - gold --as-needed: links OK, main needs libtest2.so

Maybe `--as-needed` is consistent as long as solibs have correct DT_NEEDED entries, though.

(I thought of this issue while looking at `libc.so` / `libdl.so` in the platform, which have a circular dependency, and only one of them declares DT_NEEDED on the other. I think(?) linking with `--as-needed` would still be fine, though. https://android-review.googlesource.com/c/platform/ndk/+/642743)

**Comment by alexcohn** [comment]
@rprichard Why did you link **main** with `-ltest2 -ltest3`? I would expect it to be linked with `-ltest2` only. The intimate dependency of **ibtest2.so** on **ibtest3.so** is by no means a concern of a consumer of **ibtest2.so**. 

With platform libs, which are not packaged into the APK, but are placeholders, this is even more so. At link time, we have no idea what the true dependencies on each version of platform will be.

What if on a device built by QQQ Corporation, `libc.so` depends on `libQQQ.so`? (It will hopefully have this in DT_NEEDED, though).

**Comment by rprichard** [comment]
> Why did you link main with -ltest2 -ltest3?

I was illustrating a difference between bfd and gold that could potentially affect some program if it were linked with `--as-needed`.

> What if on a device built by QQQ Corporation, libc.so depends on libQQQ.so? (It will hopefully have this in DT_NEEDED, though).

Yes, in that case, I think a DT_NEEDED entry would be more-or-less required. A typical Android binary using libc.so wouldn't have libQQQ.so as a DT_NEEDED entry.

**Comment by DanAlbert** [comment]
Yeah, probably better to leave this decision up to the user.
