### ISSUE TITLE
implicit instantiation of undefined template problem

### ISSUE THREAD

**Issue by 445615105** [android-ndk/ndk#569]
3>  C:\NVPACK\android-ndk-r12b\sources\cxx-stl\llvm-libc++\libcxx\include\functional(474): includes this header:
3>C:\NVPACK\android-ndk-r12b\sources\cxx-stl\llvm-libc++\libcxx\include\type_traits(962,38): error : implicit instantiation of undefined template 'std::__ndk1::hash<im::app::network::EWebSocketMsgType>'
3>      : public integral_constant<bool, __is_empty(_Tp)> {};
3>                                       ^

I'm using android-ndk-r12b.Whats wrong?

**Comment by DanAlbert** [comment]
Without a test case, no idea. Try updating to a more modern NDK. You're almost a year and a half out of date.

**Comment by DanAlbert** [comment]
Closing for lack of a repro case. Will reopen if we get something actionable.
