### ISSUE TITLE
GDB 7.10 from NDK r11b crashes while debugging Unreal Engine 4.10 demo

### ISSUE THREAD

**Issue by dosvidos** [android-ndk/ndk#57]
I'm using NDK R10B for Windows, target device is AARCH64.
During the debugging session I've used GDB MI interface to integrate the debugger with IDE frontend.
Initial debugging experience is good, it hits the BP's and works okay, but after a few minutes of debugging GDB crashed with the following output:
>2016-03-30 14:58:48.3592[GDB] cmd: "782-var-create --thread 10 --frame 0 - * "World""
>2016-03-30 14:58:48.3592[GDB] stdout: 782^done,name="var11",numchild="4",value="0x7048e280",type="UWorld *",thread-id="10",has_more="0"
>2016-03-30 14:58:48.3592[GDB] cmd: "783-var-list-children --all-values var11"
>2016-03-30 14:58:48.4024[GDB] stdout: 783^done,numchild="4",children=[child={name="var11.UObject",exp="UObject",numchild="1",value="{...}",type="UObject",thread-id="10"},child={name="var11.FNetworkNotify",exp="FNetworkNotify",numchild="0",value="{...}",type="FNetworkNotify",thread-id="10"},child={name="var11.public",exp="public",numchild="86",value="",thread-id="10"},child={name="var11.private",exp="private",numchild="29",value="",thread-id="10"}],has_more="0"
>2016-03-30 14:58:48.4024|GDB] cmd: "784-var-list-children --all-values var11.public"
>2016-03-30 14:58:48.4024|GDB] cmd: "785-var-show-attributes var11.UObject"
>2016-03-30 14:58:48.4024|GDB] cmd: "786-var-show-attributes var11.FNetworkNotify"
>2016-03-30 14:58:48.5206|GDB] stdout: ~"/usr/local/google/buildbot/src/android/ndk-r11-release/toolchain/gdb/gdb-7.10/gdb/utils.c:1065: internal-error: virtual memory exhausted: can't allocate 4194392 bytes.\nA problem internal to GDB has been detected,\nfurther debugging may prove unreliable.\nQuit this debugging session? "
>2016-03-30 14:58:48.5206|GDB] stdout: ~"(y or n) [answered Y; input not from terminal]\n"
>2016-03-30 14:58:48.5206|GDB] stdout: &"\nThis is a bug, please report it."
>2016-03-30 14:58:48.5206|GDB] stdout: &"  For instructions, see:\n<http://www.gnu.org/software/gdb/bugs/>."
>2016-03-30 14:58:48.5206|GDB] stdout: &"\n\n"
>2016-03-30 14:58:48.5206|GDB] stdout: ~"/usr/local/google/buildbot/src/android/ndk-r11-release/toolchain/gdb/gdb-7.10/gdb/utils.c:1065: internal-error: virtual memory exhausted: can't allocate 4194392 bytes.\nA problem internal to GDB has been detected,\nfurther debugging may prove unreliable.\nCreate a core file of GDB? "
>2016-03-30 14:58:48.5206|GDB] stdout: ~"(y or n) [answered Y; input not from terminal]\n"
>2016-03-30 14:58:48.5206|GDB: This application has requested the Runtime to terminate it in an unusual way.
>2016-03-30 14:58:48.5206|GDB: Please contact the application's support team for more information.
>2016-03-30 14:59:08.4126|[GDB] Does not return a response to "-var-show-attributes var11.UObject" command in 20000 ms. Command timed out.
>2016-03-30 14:59:08.4126|[GDB] Does not return a response to "-var-show-attributes var11.FNetworkNotify" command in 20000 ms. Command timed out.
>2016-03-30 14:59:08.4126|[GDB] Does not return a response to "-var-list-children --all-values var11.public" command in 20000 ms. Command timed out.

That crash happened after I've stepped into a method UNetDriver* AActor::GetNetDriver() const
defined in a module UnrealEngine-4.10\Engine\Source\Runtime\Engine\Private\Actor.cpp
and tried to examine the local variables.
I can't find a core dump, but could share a UE4 demo APK & binaries.

**Comment by jmgao** [comment]
> 2016-03-30 14:58:48.5206|GDB] stdout: ~"/usr/local/google/buildbot/src/android/ndk-r11-release/toolchain/gdb/gdb-7.10/gdb/utils.c:1065: internal-error: virtual memory exhausted: can't allocate 4194392 bytes.

Are you using the 64 bit version of the ndk? If not, and you have gigantic unstripped libraries, this might just be address space exhaustion.

> I can't find a core dump, but could share a UE4 demo APK & binaries.

If you're seeing this on 64 bit, please do so.

**Comment by dosvidos** [comment]
@jmgao Nice catch, actually I'm using the 32-bit version of NDK - so GDB process is 32-bit.
Though unstripped library is not that big, only about 721 Mb.
Engine/Binaries/Android/UE4Game-Android-Debug-armv7-es31.so: ELF 32-bit LSB shared object, ARM, EABI5 version 1 (SYSV), dynamically linked, interpreter /system/bin/linker, not stripped
$ du -h Engine/Binaries/Android/UE4Game-Android-Debug-armv7-es31.so
721M    Engine/Binaries/Android/UE4Game-Android-Debug-armv7-es31.so
I'll try the 64-bit version of NDK r11b

**Comment by jmgao** [comment]
Closing under the assumption that it's either due to 32-bit. If it isn't (and it isn't fixed by 7.11), please reopen.
