### ISSUE TITLE
ndk-build with clang does not use llvm-as

### ISSUE THREAD

**Issue by AstralStorm** [android-ndk/ndk#578]
If ndk-build is set to use clang, it does not use llvm assembler.
This results in assembly failure if, for example, -mllvm -asan-use-private-alias is enabled.

Tested with NDK r16.

**Comment by DanAlbert** [comment]
Is the following what you're looking for?

```makefile
LOCAL_CFLAGS += -fintegrated-as
```

If that is the solution, it's not something we can change in the NDK. We've defaulted to the non-integrated assembler for far too long to change that without breaking a lot of projects.

**Comment by AstralStorm** [comment]
No, it's definitely not what I meant.
Non-integrated assembler is fine, as long as it is the llvm assembler and not gcc assembler.
I specifically mentioned the linker and compiler options that break.

**Comment by pirama-arumuga-nainar** [comment]
llvm-as converts LLVM IR from a textual form (with .ll extension) to the LLVM bitcode representation.  Its dual is the LLVM disassembler (llvm-dis).  They don't covert between assembly (.s) and object files.

-fintegrated-as is the way to invoke LLVM/Clang's assembler.

**Comment by DanAlbert** [comment]
> I specifically mentioned the compiler options that break

How did you use them? I added them to my cflags and it was fine. This is why we ask for a test case. Your configuration might be obvious to you, but it isn't to us.

**Comment by AstralStorm** [comment]
LOCAL_CFLAGS += -march=armiv7ve -mtune=generic-armv7-a -Og -g3 -mfpu=neon-vfpv4 -fsanitize=address -fsanitize-use-after-release -mllvm -asan-use-private-alias
LOCAL_LDFLAGS += -fsanitize=address -fsanitize-use-after-release -mllvm -asan-use-private-alias

Somehow I get errors with "invalid assembly: _" etc. errors which suggest wrong assembler is used.

**Comment by DanAlbert** [comment]
So all of your source files are C++ files, right? Or do you have some assembly files too?

**Comment by AstralStorm** [comment]
Indeed, C++ only.

**Comment by pirama-arumuga-nainar** [comment]
Without much information, it's hard to guess what's going on.

Can you share a repro case?  Is there inline assembly involved?  If you add '-v' to the failing clang command, you should be able to see which assembler gets invoked.

**Comment by AstralStorm** [comment]
You are right, there is actually a bit of inline assembly involved. Never mind then, the issue is invalid. Thank you for the workaround.
