### ISSUE TITLE
Bug in r16 stdio.h preprocessor logic

### ISSUE THREAD

**Issue by weableandbob** [android-ndk/ndk#581]
#### Description

The current preprocessor logic in r16's sysroot/usr/include/stdio.h results in fgetpos, fsetpos, fseeko, and ftello not being defined if __USE_FILE_OFFSET64 is defined and __ANDROID_API__ < 24. This seems like a bug, as some version of those functions should always be defined.

The workaround we have for Chromium is available at https://chromium-review.googlesource.com/c/android_ndk/+/784230/6/sysroot/usr/include/stdio.h, which just shuffles the preprocessor checks around to always have the functions defined.

#### Environment Details

* NDK Version: r16
* Build sytem: Custom? (Chromium)
* Host OS: Ubuntu 14.04
* Compiler: Clang
* NDK API level: 16-23

**Comment by DanAlbert** [comment]
This is the correct behavior. https://android-developers.googleblog.com/2017/09/introducing-android-native-development.html

**Comment by enh** [comment]
i'll add comments in the header files pointing to the docs, and explicitly state that "if your code built before, stop defining `_FILE_OFFSET_BITS=64` as a behavior-preserving fix with NDK >= r15): https://android-review.googlesource.com/#/c/platform/bionic/+/549625/
