### ISSUE TITLE
Add helpful error message for projects using ABIs removed in r17

### ISSUE THREAD

**Issue by rprichard** [android-ndk/ndk#583]
r17 removes the armeabi, mips, and mips64 ABIs. I'm wondering if we should add a brief error message for the ndk-build / CMake build systems explaining that these ABIs have gone away. If they built armeabi, they should build armeabi-v7a instead if they aren't already.

FWIW, if users were previously using `abiFilters` with Gradle, they should see an error like this:

```
Error:ABIs [armeabi] are not supported for platform. Supported ABIs are [armeabi-v7a, arm64-v8a, x86, x86_64].
```

Here's the current ndk-build error:
```
rprichard@cashew:~/ndk-samples-mk/hello-jni$ ~/android/ndk/out/android-ndk-r17-canary/ndk-build
Android NDK: Found platform level in ./default.properties. Setting APP_PLATFORM to android-14.    
Android NDK: NDK Application 'local' targets unknown ABI(s): armeabi    
Android NDK: Please fix the APP_ABI definition in ./jni/Application.mk    
/usr/local/google/home/rprichard/android/ndk/out/android-ndk-r17-canary/build/core/setup-app.mk:75: *** Android NDK: Aborting    .  Stop.
```

**Comment by enh** [comment]
yeah, the gradle error seems a lot clearer.

**Comment by rprichard** [comment]
https://android-review.googlesource.com/c/platform/ndk/+/599873
