### ISSUE TITLE
how about "native_handle" api

### ISSUE THREAD

**Issue by enduringstack** [android-ndk/ndk#585]
we have provided a *.so to developer, but in the *.so, we used native_handle api in the libcutils.so。

the issue is from N, app developer can not use libcutils.so。any open api can i use for native_handle_t?

Looking forward your reply,

**Comment by enh** [comment]
you mean you've written your own API that uses native_handle_t? in that case, just copy the native_handle_t implementation into your own library? (and ideally rename it!)

**Comment by enduringstack** [comment]
Are there any other api which i use instead of native_handle_t？

**Comment by enh** [comment]
there is no public API corresponding to native_handle_t, no.
