### ISSUE TITLE
stlport/stlport/time.h:32:43: fatal error: ../include/time.h: No such file or directory

### ISSUE THREAD

**Issue by jjcf89** [android-ndk/ndk#588]
stlport/stlport/time.h looks for ../include/time.h which was removed.

NDK 16
./sources/cxx-stl/stlport/stlport

NDK 15
```
./sources/android/support/include/time.h
./sources/cxx-stl/stlport/stlport/time.h
```

```
/export/space/jcormier/android_sdk/ndk-bundle/sources/cxx-stl/stlport/stlport/time.h:32:43: fatal error: ../include/time.h: No such file or directory
 #    include _STLP_NATIVE_C_HEADER(time.h)
```

* NDK Version: 16.1.4479499
* Build sytem: Android studio
* Host OS: Ubuntu 16.04
* Compiler: How do I tell?
* ABI:
* STL:
* NDK API level: 25
* Device API level: 17

**Comment by DanAlbert** [comment]
Do you have a test case?

FYI, you may just want to switch to libc++. stlport is going to be removed in r18.

> NDK API level: 25
> Device API level: 17

https://android.googlesource.com/platform/ndk/+/master/docs/user/common_problems.md#target-api-set-higher-than-device-api

**Comment by jjcf89** [comment]
NDK API level: 25
Device API level: 17
I could just be reading the build.gradle wrong.

```
    android {
        compileSdkVersion = 25
        buildToolsVersion = "25.0.3"

        defaultConfig.with {
            applicationId = "com.hygiena.ensure5"
            minSdkVersion.apiLevel = 17
            targetSdkVersion.apiLevel = 25
            versionCode = 1
            versionName = "1.07"

            testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
        }
    }
```

> Do you have a test case?
I'll see what I can create.

> FYI, you may just want to switch to libc++. stlport is going to be removed in r18.
I'm trying but I'm getting a bunch of include errors. Some that make no sense.

Like it can't find <time.h>, <jni.h>, <linux/types.h> which now appear to be located in './ndk-bundle/sysroot/usr/include/'. But I can't figure out why it isn't looking there.

**Comment by DanAlbert** [comment]
> I could just be reading the build.gradle wrong.

You were. `minSdkVersion` is your NDK API level.

If you're not using `externalNativeBuild` at all this is the wrong place to file a bug. Try http://b.android.com

**Comment by jjcf89** [comment]
Okay thanks for the heads up.

**Comment by jjcf89** [comment]
Ended up switching to cmake build in android studio which solved the missing includes problems.  Then switched to libc++.
