### ISSUE TITLE
Missed java-to-native converters for android.view.KeyEvent, android.view.MotionEvent

### ISSUE THREAD

**Issue by serhiihuralniksc** [android-ndk/ndk#590]
#### Description

It is easy to imagine situation where user needs to handle some input events in native code and at the same time doesn't have a chance to stick to `NativeActivity` for attaching to `AInputQueue`.
The only way to solve this - implement own mappers that convert java land input entities to some custom native equivalents.
As far as I see - platform already has such converters but they are not exported via NDK
In this situation would be nice to have access to them, so user can later benefit from already existing `AKeyEvent_*` `AMotionEvent_*` methods:
```
AInputEvent* AKeyEvent_fromJava(JNIEnv* env, jobject keyEvent /* android.view.KeyEvent */);
AInputEvent* AMotionEvent_fromJava(JNIEnv* env, jobject motionEvent /* android.view.MotionEvent */);
```
Probably there will be some restrictions like do not recycle java objects until user finishes with native counterparts.

#### Environment Details
* NDK Version: 16.0.4442984
* Build sytem: N/A
* Host OS: N/A
* Compiler:N/A
* ABI: N/A
* STL: N/A
* NDK API level: 26
* Device API level: 26

**Comment by DanAlbert** [comment]
Will need to file a platform bug at http://b.android.com for this. For anything in the frameworks we only ship the API, not write them.
