### ISSUE TITLE
inline static default constructor never called, or cause ICE

### ISSUE THREAD

**Issue by tower120** [android-ndk/ndk#594]
#### Description

The following code:

[Live](https://godbolt.org/g/ficjJX)

```c++
#include <iostream>
#include <thread>
#include <mutex>
#include <functional>
#include <string>
#include <unordered_map>

    template<class Derived>
    struct Initializable {
        Initializable(){
            Derived::init();
        }
    };

    template<class Derived, class ...Args>
    class SignalSenderBase{
    protected:
        inline static struct MethodIds : Initializable<MethodIds>{
            static void init(){
                std::cout << "init called" << std::endl;
            }
        } methodIds;

        static int link(const std::string& id){
            methodIds;      // odr use
            return 0;
        }

        int id;

    public:
        SignalSenderBase(const std::string& id)
            : id (link(id))
        {}
    };

    class SignalSenderVoid : public SignalSenderBase<SignalSenderVoid>{
    public:
        using SignalSenderBase::SignalSenderBase;
    };

// ...
// Somewhere later in the same compilation unit
// ...
    SignalSenderVoid<> g("aa");
```

Does compiles in the current NDK r16b clang. BUT! `MethodIds.init()` never ever called.
On the other clang 5.x.x cause ICE

Changing 
```c++
        inline static struct MethodIds : Initializable<MethodIds>{
            static void init(){
                std::cout << "init called" << std::endl;
            }
        } methodIds;
```

to 

```c++
        inline static struct MethodIds : Initializable<MethodIds>{
            static void init(){
                std::cout << "init called" << std::endl;
            }
        } methodIds{};   // !!!!
```

Do fix both  wrong behavior and ICE.

Relative:
 * https://bugs.llvm.org/show_bug.cgi?id=35599
 * https://github.com/android-ndk/ndk/issues/591

#### Environment Details

* NDK Version: r16b
* Build sytem: any
* Host OS: Windows
* Compiler: clang
* STL: c++1z

**Comment by DanAlbert** [comment]
Still causes an ICE in r17 and master. Triaging for r18.

@stephenhines @gburgessiv @pirama-arumuga-nainar: might be worth checking with the WIP clang update, but given that the bug is still open upstream I'm guessing it hasn't been fixed yet.

**Comment by gburgessiv** [comment]
Confirmed that it repros on trunk at r327572. I'll see if it's a simple fix upstream.

**Comment by gburgessiv** [comment]
r327945 should fix it. Please let me know if not.

**Comment by DanAlbert** [comment]
Awesome, thanks for the quick fix!

@stephenhines: assign over to me once we have a prebuilt with this patch.
