### ISSUE TITLE
Provide an API to call ProcessState::self()->startThreadPool()

### ISSUE THREAD

**Issue by rcombs** [android-ndk/ndk#597]
#### Description

Native code calling into NDK functions often needs the Binder thread pool to be running, sometimes in a process that wasn't forked from Zygote and doesn't have one of its own (e.g. if it was started using the usual fork/execve calls). For this to work, we need a function that calls `ProcessState::self()->startThreadPool()`. Simply running this from a C++ file isn't acceptable, since it requires use of private headers and libs, and (AFAIK) isn't ABI-stable across versions.

Currently, I'm working around this by having vendor partners provide a shared lib that calls this function, which I can `dlopen` and call into, but this limits me to the vendors that I work with directly to provide this functionality.

Please provide a function to call this; if possible, including a legacy inline.

#### Environment Details

* NDK Version: 16.0.4442984

**Comment by enh** [comment]
this isn't something that's supported for apps. (if by "vendor" you mean code on /vendor, then you can just use the Treble libbinder.)
