### ISSUE TITLE
CMake always throws "Using custom NDK path" warning now

### ISSUE THREAD

**Issue by nneonneo** [android-ndk/ndk#599]
#### Description

After upgrading to NDK 16.1.4479499, every CMake reconfigure on my native project throws the following warning:

```
CMake Warning at /Users/brx/devel/android/sdk/ndk-bundle/build/cmake/android.toolchain.cmake:63 (message):
  Using custom NDK path (ANDROID_NDK is set):
  /Users/brx/devel/android/sdk/ndk-bundle
Call Stack (most recent call first):
  /Users/brx/devel/android/sdk/cmake/3.6.4111459/share/cmake-3.6/Modules/CMakeDetermineSystem.cmake:98 (include)
  CMakeLists.txt
```

This warning was added by the fix to #473. However, I am not using a custom NDK toolchain path - the NDK path in the message (`/Users/brx/devel/android/sdk/ndk-bundle`) is just the one set from Android Studio. This warning appears eight times, once per ABI+build type combo.

The problem seems to be that Android Studio is setting `ANDROID_NDK` in the command line passed to CMake. Here's the command line:

```
app/.externalNativeBuild/cmake/release/x86$ cat cmake_build_command.txt 
Executable : /Users/brx/devel/android/sdk/cmake/3.6.4111459/bin/cmake
arguments : 
-H/private/tmp/issue473/app
-B/private/tmp/issue473/app/.externalNativeBuild/cmake/release/x86
-DANDROID_ABI=x86
-DANDROID_PLATFORM=android-24
-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/private/tmp/issue473/app/build/intermediates/cmake/release/obj/x86
-DCMAKE_BUILD_TYPE=Release
-DANDROID_NDK=/Users/brx/devel/android/sdk/ndk-bundle
-DCMAKE_CXX_FLAGS=
-DCMAKE_TOOLCHAIN_FILE=/Users/brx/devel/android/sdk/ndk-bundle/build/cmake/android.toolchain.cmake
-DCMAKE_MAKE_PROGRAM=/Users/brx/devel/android/sdk/cmake/3.6.4111459/bin/ninja
-GAndroid Gradle - Ninja
jvmArgs : 
```

Android Studio realistically needs to pass the `ANDROID_NDK` to CMake, so it shouldn't be considered a "custom" NDK path - that's why this is filed as an NDK bug not an Android Studio bug. I'll file an Android Studio bug if there's some other "proper" way to pass in the NDK path that Android Studio is not doing.

#### Steps to Reproduce
In Android Studio 3.0.1 with NDK 16.1.4479499, create a new project, add C++ support, and build the project. Then make some trivial change to CMakeFiles.txt (e.g. add a comment) and rebuild. Warnings will appear.

#### Environment Details

* NDK Version: 16.1.4479499
* Build sytem: cmake (under Android Studio/Gradle)
* Host OS: macOS 10.12.6
* Compiler: clang
* ABI: *all*
* Android Studio: 3.0.1

**Comment by tsirolnik** [comment]
Getting the same message for no apparent reason

**Comment by anutin544** [comment]
Ok

**Comment by DanAlbert** [comment]
https://android-review.googlesource.com/c/platform/ndk/+/623926
