### ISSUE TITLE
NDK R16b - i686-linux-android Link error: unsupported reloc 43 against global symbol

### ISSUE THREAD

**Issue by mciarcia-nav** [android-ndk/ndk#604]
--------------------------------------------------------------------------------

#### Description
Linking on Linux machine for android using ndk-r16b toolchain fails with error: unsupported reloc 43 against global symbol.
Same code can be successfully built on Mac OS with same toolchain
Log:
/opt/android-ndk/toolchains/x86-4.9/prebuilt/linux-x86_64/bin/../lib/gcc/i686-linux-android/4.9/../../../../i686-linux-android/bin/ld: error: <path>/x86/libcrypto.a(pem_all.o): unsupported reloc 43 against global symbol i2d_DHparams
/opt/android-ndk/toolchains/x86-4.9/prebuilt/linux-x86_64/bin/../lib/gcc/i686-linux-android/4.9/../../../../i686-linux-android/bin/ld: error: <path>/x86/libcrypto.a(pem_all.o): unsupported reloc 43 against global symbol i2d_DHxparams
/opt/android-ndk/toolchains/x86-4.9/prebuilt/linux-x86_64/bin/../lib/gcc/i686-linux-android/4.9/../../../../i686-linux-android/bin/ld: error: <path>/x86/libcrypto.a(pem_all.o): unsupported reloc 43 against global symbol i2d_DHxparams
where <path> is the path containing the libraries
#### Environment Details
Linux machine 64 bit

* NDK Version: r16b
* Build sytem: ndk-build
* Host OS: Linux x86 64 bit
* Compiler: GCC
* ABI: x86
* STL:
* NDK API level:
* Device API level:

**Comment by enh** [comment]
we'll need some code that actually causes this error, because we haven't seen it and it doesn't happen in any of our tests...

**Comment by DanAlbert** [comment]
But step one would be to switch to Clang and see if it still happens.

**Comment by mciarcia-nav** [comment]
Issue was caused by linking with prebuilt library build with a previous version of the ndk toolchain
