### ISSUE TITLE
android-msm-marlin-3.18-oreo fails to build using latest aarch64-linux-android-gcc

### ISSUE THREAD

**Issue by atulprak** [android-ndk/ndk#605]
#### Description

To reproduce:

Download the Linux kernel for Android (msm):
``` bash
git clone https://android.googlesource.com/kernel/msm
cd msm
git checkout -b android-msm-marlin-3.18-oreo origin/android-msm-marlin-3.18-oreo
```

Assuming you already have $NDK pointing to the latest NDK  directory (e.g., ~/ndk/android-ndk-r16b), 
do the following to build the kernel:

``` bash
export ARCH=arm64
export CROSS_COMPILE=$NDK/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64/bin/aarch64-linux-android-
export ARCH=arm64
export CROSS_COMPILE=$NDK/toolchains/aarch64-linux-android-4.9/prebuilt/linux-86_64/bin/aarch64-linux-android-
make mrproper
make marlin_defconfig
make -j40
```

I get the following error at the end of the build:

```
MODPOST vmlinux.o
ERROR: modpost: Found 10 section mismatch(es).
To see full details build your kernel with:
'make CONFIG_DEBUG_SECTION_MISMATCH=y'
To build the kernel despite the mismatches, build with:
'make CONFIG_NO_ERROR_ON_MISMATCH=y'
(NOTE: This is not recommended)
scripts/Makefile.modpost:97: recipe for target 'vmlinux.o' failed
make[1]: *** [vmlinux.o] Error 1
Makefile:941: recipe for target 'vmlinux' failed
make: *** [vmlinux] Error 2
```

_The build works if NDK points to android-ndk-r15c._

There is an incompatibility somewhere.

Host OS: Linux 4.9.0-4-amd64 #1 SMP Debian 4.9.65-3 (2017-12-03) x86_64 GNU/Linux

**Comment by stephenhines** [comment]
Is this using GCC or Clang to build? We switched the NDK default over to Clang, but I don't believe we necessarily support using Clang to build the marlin kernel (although I believe they got that working at some point too, but it might not be released, since we are still using GCC-compiled kernels for non-Pixel2 devices). It would help to know a bit more about that, so you can either point this back to GCC for the build, or if this is some other kind of regression.

**Comment by atulprak** [comment]
I believe GCC is being used. Setting V=1 in make prints out the compiler being used. Here is what it reports:

/usr/local/google/home/atulp/ndk/android-ndk-r16/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64/bin/aarch64-linux-android-gcc

Switching to android-ndk-r15c goes through fine. Also, each file compiles fine. The error happens at the following command that is executed by make when building the linux kernel:

`Executed by make:
 scripts/mod/modpost -m -a -o ./Module.symvers -S -E vmlinux.o 
`
Output from above: 
ERROR: modpost: Found 10 section mismatch(es).

**Comment by pirama-arumuga-nainar** [comment]
We saw the error internally back in July, when switching to a new binutils.  The resolution was the kernel patch at https://android.googlesource.com/kernel/msm/+/3c719844365c84d69222c6fec2a4eb85dc14f2a5.   You can apply this patch or try the android-msm-marlin-3.18-oreo-mr1 branch, which seems to have the fix.

**Comment by atulprak** [comment]
That works. Thanks.
