### ISSUE TITLE
how to debug native executable build with standalone toolchain aarch64-linux-android-4.9, no aarch64-linux-android-gdb provided

### ISSUE THREAD

**Issue by joshuafc** [android-ndk/ndk#606]
#### Description
Please help me, in summary， I am a algorithm developer using C++, be familiar with GCC , know very  few about Java, Android Application Develop, JNI and ndk-build . I  am focus on developer high performance and high accuracy algorithm shared libraries, deliver libraries to my various platform (Android, Linux, Windows, IOS) APP develop colleagues. I build my project using cmake, and standalone toolchain aarch64-linux-android-4.9. I want to find an easy way to debug my unit test ( Android Native Executable Binary build with -pie ) and shared libraries with a rooted Android device IN GDB WAY. 
I know adb shell, gdbservice and aarch64-linux-android-gdb can do it well, and I can found everything needed in android-ndk-r10e package, but can not found aarch64-linux-android-gdb in android-ndk-r14b package, is aarch64-linux-android-gdb unsupported now?  
To my situation, any best practice advice PLEASE, thank you.

https://developer.android.com/ndk/guides/ndk-gdb.html show how to debug with ndk-gdb, but it require build project with ndk-build, My project is closs-platform and it just use c++11 and opencv, I don't want to create build scripts for every OS, I want to use cmake solve them all.

https://developer.android.com/ndk/guides/standalone_toolchain.html show how to make standalone toolchain and build with c++ stl, but nothing about how to debug native librarys and executable by adb shell.

These is no test case. just click https://developer.android.com/ndk/downloads/index.html and download android-ndk-r14b-linux-x86_64.zip, follow https://developer.android.com/ndk/guides/standalone_toolchain.html make a standalone toolchain aarch64-linux-android-4.9 , then find ./ -iname "aarch64-linux-android-gdb", nothing found.

#### Environment Details

Not all of these will be relevant to every bug, but please provide as much
information as you can.

* NDK Version: android-ndk-r14b
* Build sytem: cmake with costum cmake_toolchain_file use standalone toolchain aarch64-linux-android-4.9 .
* Host OS: Ubuntu 16.04
* Compiler: If GCC, check Clang before filing. GCC is no longer supported.
* ABI: aarch64
* STL: gnustl_shared
* NDK API level: 21
* Device API level: sure above 21

**Comment by enh** [comment]
i think in modern NDK releases we just have a single multiarch gdb binary, don't we? in r16: 
```
$ ./prebuilt/linux-x86_64/bin/gdb
GNU gdb (GDB) 7.11
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word".
(gdb) set architecture 
Requires an argument. Valid arguments are i386, i386:x86-64, i386:x64-32, i8086, i386:intel, i386:x86-64:intel, i386:x64-32:intel, i386:nacl, i386:x86-64:nacl, i386:x64-32:nacl, arm, armv2, armv2a, armv3, armv3m, armv4, armv4t, armv5, armv5t, armv5te, xscale, ep9312, iwmmxt, iwmmxt2, aarch64, aarch64:ilp32, mips, mips:3000, mips:3900, mips:4000, mips:4010, mips:4100, mips:4111, mips:4120, mips:4300, mips:4400, mips:4600, mips:4650, mips:5000, mips:5400, mips:5500, mips:5900, mips:6000, mips:7000, mips:8000, mips:9000, mips:10000, mips:12000, mips:14000, mips:16000, mips:16, mips:mips5, mips:isa32, mips:isa32r2, mips:isa32r3, mips:isa32r5, mips:isa32r6, mips:isa64, mips:isa64r2, mips:isa64r3, mips:isa64r5, mips:isa64r6, mips:sb1, mips:loongson_2e, mips:loongson_2f, mips:loongson_3a, mips:octeon, mips:octeon+, mips:octeon2, mips:octeon3, mips:xlr, mips:micromips, auto.
(gdb) 
```

**Comment by rprichard** [comment]
Yes, the NDK provides a single `gdb` binary for all target architectures. There's still a separate `gdbserver` binary for each architecture.

The `gdb` binary is packaged into standalone toolchains, but `gdbserver` isn't yet (https://github.com/android-ndk/ndk/issues/567).

`ndk-gdb` assumes it's working with an Android app (with an `AndroidManifest.xml`, and using an old project format), so I don't think it'll be useful here out-of-the-box. The `gdb` and `gdbserver` binaries should work. It's probably not that hard to make `ndk-gdb` work for a standalone executable.

Aside: The NDK provides a CMake toolchain file (in `build/cmake/android.toolchain.cmake`). It uses the NDK directly--if you can use it, then there's no need to create a standalone toolchain first.
