### ISSUE TITLE
Looks like bug in  clang++ or arm-linux-androideabi-g++.exe of ndk-r16b

### ISSUE THREAD

**Issue by mun24** [android-ndk/ndk#607]
ndk (project having around 20 assembly files .s, 2 c++ files and around 2000 c) files compiles fine with ndk r14b(gcc), r15c(gcc), r16b(gcc or clang). Gradle select by itself arm-linux-androideabi-g++ or clang++ for linking.
Same project run fine when compile with ndk r14b or r15c. But it crashes when used r16b(gcc or clang). If replace r16b file: arm-linux-androideabi-g++.exe with from prev version of ndk. Then it do not crash and works fine.

Also on mac system same project never worked with any version ndk. It compiles fine on mac too. 

I suspect something change in the arm-linux-androideabi-g++.exe for r16b which creates the crash. Also looks like crash occurs interoperation between assembly code and c code.

compileSdkVersion 25
minSdkVersion 19
targetSdkVersion 25
cmake build system
Host: windows or Mac
abiFilters 'armeabi-v7a'
Tried on Device API level 19 or 21

**Comment by enh** [comment]
there's no actionable information here. provide a reproduceable test case and we can reopen.
