### ISSUE TITLE
ndk16b: clang intrinsic __builtin_cpu_supports( "sha" ) is absent

### ISSUE THREAD

**Issue by andreya108** [android-ndk/ndk#608]
According to https://github.com/llvm-mirror/clang/blob/release_50/include/clang/Basic/BuiltinsX86.def it should exist, but is absent actually when building for x86 (api 21).
```
src/cpu_features_x86_linux.c:67:15: error: invalid cpu feature string for builtin
      return !!__builtin_cpu_supports( "sha" );
                ^                       ~~~~~
1 error generated.
```
___
**Environment Details**

NDK Version: r16b
Build sytem: standalone toolchain (clang)
Host OS: Ubuntu 16.04
Compiler: Clang C
ABI: x86, x86_64
STL: libc++
NDK API level: 21 (used for build)

**Comment by pirama-arumuga-nainar** [comment]
The file you linked doesn't imply that `__builtin_cpu_supports( "sha" )` works.  It's not one of the supported features, based on [1](https://github.com/llvm-mirror/clang/blob/master/lib/Basic/Targets/X86.cpp#L1334), [2](https://github.com/llvm-mirror/llvm/blob/master/include/llvm/Support/X86TargetParser.def#L37), [3](https://github.com/llvm-mirror/compiler-rt/blob/master/lib/builtins/cpu_model.c#L503) - note that bit 29 is not checked.

GCC and ICC don't seem to support this either: https://godbolt.org/g/TbQtbL and Clang seems to want compatiblity with GCC in this aspect (see [this commit message](https://github.com/llvm-mirror/compiler-rt/commit/5ebaa70bf9a2b2a8faa0cf0c19159d4f8e24c01c#diff-cc6d10965d3dd924a796f2e066e54b06)).

An alternative is to use the check in the "Using the Intel SHA Extensions" section in https://software.intel.com/en-us/articles/intel-sha-extensions.

**Comment by pirama-arumuga-nainar** [comment]
Closing this because any attempted fix should be initiated and discussed upstream.
