### ISSUE TITLE
CMake project compilation fails if -Wl,--threads is specified

### ISSUE THREAD

**Issue by VioletGiraffe** [android-ndk/ndk#611]
Apparently, the first step of the CMake build sequence is checking the compiler for sanity, and it fails if the project specifies `-Wl,--threads`. But this is only one of the possible symptoms; the problem boils down to the test compile using "Treat warnings as errors". See the full build output below:

> External Native Build Issues
> Build command failed.
> Error while executing process C:\Development\Android\sdk\cmake\3.6.4111459\bin\cmake.exe with arguments {-HC:\Development\guieditor\editor\android\app -BC:\Development\guieditor\editor\android\app\.externalNativeBuild\cmake\debug\armeabi-v7a -DANDROID_ABI=armeabi-v7a -DANDROID_PLATFORM=android-16 -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\Development\guieditor\editor\android\app\build\intermediates\cmake\debug\obj\armeabi-v7a -DCMAKE_BUILD_TYPE=Debug -DANDROID_NDK=C:\Development\Android\sdk\ndk-bundle -DCMAKE_C_FLAGS=-Wno-deprecated-register -funwind-tables -Wl,--threads -Wl,--no-merge-exidx-entries -DCMAKE_CXX_FLAGS=-std=c++14 -frtti -fexceptions -DCMAKE_TOOLCHAIN_FILE=C:\Development\Android\sdk\ndk-bundle\build\cmake\android.toolchain.cmake -DCMAKE_MAKE_PROGRAM=C:\Development\Android\sdk\cmake\3.6.4111459\bin\ninja.exe -GAndroid Gradle - Ninja -DANDROID_STL=c++_static -DANDROID_ARM_MODE=arm}
> -- Check for working C compiler: C:/Development/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe
> -- Check for working C compiler: C:/Development/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe -- broken
>   It fails with the following output:
>    Change Dir: C:/Development/guieditor/editor/android/app/.externalNativeBuild/cmake/debug/armeabi-v7a/CMakeFiles/CMakeTmp
>   Run Build
>   Command:"C:\Development\Android\sdk\cmake\3.6.4111459\bin\ninja.exe"
>   "cmTC_f614a"
>   [1/2] Building C object CMakeFiles/cmTC_f614a.dir/testCCompiler.c.o
> Warning:warning: -Wl,--threads: 'linker' input unused
>   [-Wunused-command-line-argument]
> Warning:warning: -Wl,--no-merge-exidx-entries: 'linker' input unused
>   [-Wunused-command-line-argument]
>   [2/2] Linking C executable cmTC_f614a
>   FAILED: cmd.exe /C "cd .  &&
>   C:\Development\Android\sdk\ndk-bundle\toolchains\llvm\prebuilt\windows-x86_64\bin\clang.exe
>   --target=armv7-none-linux-androideabi
>   --gcc-toolchain=C:/Development/Android/sdk/ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/windows-x86_64
>   --sysroot=C:/Development/Android/sdk/ndk-bundle/sysroot -isystem
>   C:/Development/Android/sdk/ndk-bundle/sysroot/usr/include/arm-linux-androideabi
>   -D__ANDROID_API__=16 -g -DANDROID -ffunction-sections -funwind-tables
>   -fstack-protector-strong -no-canonical-prefixes -march=armv7-a
>   -mfloat-abi=softfp -mfpu=vfpv3-d16 -fno-integrated-as -marm
>   -Wa,--noexecstack -Wformat -Werror=format-security -Wno-deprecated-register
>   -funwind-tables -Wl,--threads -Wl,--no-merge-exidx-entries
>   -Wl,--exclude-libs,libgcc.a -Wl,--exclude-libs,libatomic.a --sysroot
>   C:/Development/Android/sdk/ndk-bundle/platforms/android-16/arch-arm
>   -Wl,--build-id -Wl,--warn-shared-textrel -Wl,--fatal-warnings
>   -Wl,--fix-cortex-a8 -Wl,--exclude-libs,libunwind.a
>   -LC:/Development/Android/sdk/ndk-bundle/sources/cxx-stl/llvm-libc++/libs/armeabi-v7a
>   -Wl,--no-undefined -Wl,-z,noexecstack -Qunused-arguments -Wl,-z,relro
>   -Wl,-z,now -Wl,--gc-sections -Wl,-z,nocopyreloc -pie -fPIE
>   CMakeFiles/cmTC_f614a.dir/testCCompiler.c.o -o cmTC_f614a -latomic -lm &&
>   cd ."
>   C:/Development/Android/sdk/ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/windows-x86_64/lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin\ld:
> Warning:ignoring --threads:
>   C:/Development/Android/sdk/ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/windows-x86_64/lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin\ld
>   was compiled without thread support
>   C:/Development/Android/sdk/ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/windows-x86_64/lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin\ld:
> Error:treating warnings as errors
> Error:error: linker command failed with exit code 1 (use -v to see
>   invocation)
>   ninja: build stopped: subcommand failed.
>   CMake will not be able to correctly generate this project.
> Call Stack (most recent call first):
>   CMakeLists.txt
> -- Configuring incomplete, errors occurred!
> See also "C:/Development/guieditor/editor/android/app/.externalNativeBuild/cmake/debug/armeabi-v7a/CMakeFiles/CMakeOutput.log".
> See also "C:/Development/guieditor/editor/android/app/.externalNativeBuild/cmake/debug/armeabi-v7a/CMakeFiles/CMakeError.log".
> Build command failed.
> Error while executing process C:\Development\Android\sdk\cmake\3.6.4111459\bin\cmake.exe with arguments {-HC:\Development\guieditor\editor\android\app -BC:\Development\guieditor\editor\android\app\.externalNativeBuild\cmake\release\armeabi-v7a -DANDROID_ABI=armeabi-v7a -DANDROID_PLATFORM=android-16 -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=C:\Development\guieditor\editor\android\app\build\intermediates\cmake\release\obj\armeabi-v7a -DCMAKE_BUILD_TYPE=Release -DANDROID_NDK=C:\Development\Android\sdk\ndk-bundle -DCMAKE_C_FLAGS=-Wno-deprecated-register -funwind-tables -Wl,--threads -Wl,--no-merge-exidx-entries -DCMAKE_CXX_FLAGS=-std=c++14 -frtti -fexceptions -DCMAKE_TOOLCHAIN_FILE=C:\Development\Android\sdk\ndk-bundle\build\cmake\android.toolchain.cmake -DCMAKE_MAKE_PROGRAM=C:\Development\Android\sdk\cmake\3.6.4111459\bin\ninja.exe -GAndroid Gradle - Ninja -DANDROID_STL=c++_static -DANDROID_ARM_MODE=arm}
> -- Check for working C compiler: C:/Development/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe
> -- Check for working C compiler: C:/Development/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe -- broken
>   It fails with the following output:
>    Change Dir: C:/Development/guieditor/editor/android/app/.externalNativeBuild/cmake/release/armeabi-v7a/CMakeFiles/CMakeTmp
>   Run Build
>   Command:"C:\Development\Android\sdk\cmake\3.6.4111459\bin\ninja.exe"
>   "cmTC_7310d"
>   [1/2] Building C object CMakeFiles/cmTC_7310d.dir/testCCompiler.c.o
> Warning:warning: -Wl,--threads: 'linker' input unused
>   [-Wunused-command-line-argument]
> Warning:warning: -Wl,--no-merge-exidx-entries: 'linker' input unused
>   [-Wunused-command-line-argument]
>   [2/2] Linking C executable cmTC_7310d
>   FAILED: cmd.exe /C "cd .  &&
>   C:\Development\Android\sdk\ndk-bundle\toolchains\llvm\prebuilt\windows-x86_64\bin\clang.exe
>   --target=armv7-none-linux-androideabi
>   --gcc-toolchain=C:/Development/Android/sdk/ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/windows-x86_64
>   --sysroot=C:/Development/Android/sdk/ndk-bundle/sysroot -isystem
>   C:/Development/Android/sdk/ndk-bundle/sysroot/usr/include/arm-linux-androideabi
>   -D__ANDROID_API__=16 -g -DANDROID -ffunction-sections -funwind-tables
>   -fstack-protector-strong -no-canonical-prefixes -march=armv7-a
>   -mfloat-abi=softfp -mfpu=vfpv3-d16 -fno-integrated-as -marm
>   -Wa,--noexecstack -Wformat -Werror=format-security -Wno-deprecated-register
>   -funwind-tables -Wl,--threads -Wl,--no-merge-exidx-entries
>   -Wl,--exclude-libs,libgcc.a -Wl,--exclude-libs,libatomic.a --sysroot
>   C:/Development/Android/sdk/ndk-bundle/platforms/android-16/arch-arm
>   -Wl,--build-id -Wl,--warn-shared-textrel -Wl,--fatal-warnings
>   -Wl,--fix-cortex-a8 -Wl,--exclude-libs,libunwind.a
>   -LC:/Development/Android/sdk/ndk-bundle/sources/cxx-stl/llvm-libc++/libs/armeabi-v7a
>   -Wl,--no-undefined -Wl,-z,noexecstack -Qunused-arguments -Wl,-z,relro
>   -Wl,-z,now -Wl,--gc-sections -Wl,-z,nocopyreloc -pie -fPIE
>   CMakeFiles/cmTC_7310d.dir/testCCompiler.c.o -o cmTC_7310d -latomic -lm &&
>   cd ."
>   C:/Development/Android/sdk/ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/windows-x86_64/lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin\ld:
> Warning:ignoring --threads:
>   C:/Development/Android/sdk/ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/windows-x86_64/lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin\ld
>   was compiled without thread support
>   C:/Development/Android/sdk/ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/windows-x86_64/lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin\ld:
> Error:treating warnings as errors
> Error:error: linker command failed with exit code 1 (use -v to see
>   invocation)
>   ninja: build stopped: subcommand failed.
>   CMake will not be able to correctly generate this project.
> Call Stack (most recent call first):
>   CMakeLists.txt
> -- Configuring incomplete, errors occurred!
> See also "C:/Development/guieditor/editor/android/app/.externalNativeBuild/cmake/release/armeabi-v7a/CMakeFiles/CMakeOutput.log".
> See also "C:/Development/guieditor/editor/android/app/.externalNativeBuild/cmake/release/armeabi-v7a/CMakeFiles/CMakeError.log".
> C:\Development\Android\sdk\ndk-bundle\build\cmake\android.toolchain.cmake
> Warning:(63, 98)  (include)   CMakeLists.txt 
> Warning:(63, 98)  (include)   CMakeLists.txt 
> C:\Development\Android\sdk\cmake\3.6.4111459\share\cmake-3.6\Modules\CMakeTestCCompiler.cmake
> Error:(61, 0) /Development/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe"   is not able to compile a simple test program. 
> <a href="openFile:C:\Development\Android\sdk\cmake\3.6.4111459\share\cmake-3.6\Modules\CMakeTestCCompiler.cmake">Open File</a>
> Error:(61, 0) /Development/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe"   is not able to compile a simple test program. 
> <a href="openFile:C:\Development\Android\sdk\cmake\3.6.4111459\share\cmake-3.6\Modules\CMakeTestCCompiler.cmake">Open File</a>

**Comment by DanAlbert** [comment]
Sorry, missed this one somehow (anyone know of a github bot that will auto-ping a thread if we've ignored it?)

Works for me:

```bash
$ cat ../CMakeLists.txt
cmake_minimum_required(VERSION 3.6.0)

set(CMAKE_EXE_LINKER_FLAGS
  "${CMAKE_EXE_LINKER_FLAGS} -Wl,--threads -fuse-ld=gold")

add_executable(foo foo.cpp)
$ cmake -DCMAKE_TOOLCHAIN_FILE=$NDK/build/cmake/android.toolchain.cmake -DANDROID_ABI=arm64-v8a -GNinja ..
-- Check for working C compiler: /usr/local/google/home/danalbert/src/ndk/out/android-ndk-r18-canary/toolchains/llvm/prebuilt/linux-x86_64/bin/clang
-- Check for working C compiler: /usr/local/google/home/danalbert/src/ndk/out/android-ndk-r18-canary/toolchains/llvm/prebuilt/linux-x86_64/bin/clang -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/local/google/home/danalbert/src/ndk/out/android-ndk-r18-canary/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++
-- Check for working CXX compiler: /usr/local/google/home/danalbert/src/ndk/out/android-ndk-r18-canary/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: /usr/local/google/home/danalbert/src/ndk/ndk/foo/build
$ ninja
[1/2] /usr/local/google/home/danalbert/src/ndk/out/android-ndk-r18-canary/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++  --target=aarch64-none-linux-android --gcc-toolchain=/usr/local/google/home/danalbert/src/ndk/out/android-ndk-r18-canary/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64 --sysroot=/usr/local/google/home/danalbert/src/ndk/out/android-ndk-r18-canary/sysroot   -isystem /usr/local/google/home/danalbert/src/ndk/out/android-ndk-r18-canary/sources/cxx-stl/llvm-libc++/include -isystem /usr/local/google/home/danalbert/src/ndk/out/android-ndk-r18-canary/sources/android/support/include -isystem /usr/local/google/home/danalbert/src/ndk/out/android-ndk-r18-canary/sources/cxx-stl/llvm-libc++abi/include -isystem /usr/local/google/home/danalbert/src/ndk/out/android-ndk-r18-canary/sysroot/usr/include/aarch64-linux-android -D__ANDROID_API__=21 -g -DANDROID -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -Wa,--noexecstack -Wformat -Werror=format-security -std=c++11  -fPIE -MD -MT CMakeFiles/foo.dir/foo.cpp.o -MF CMakeFiles/foo.dir/foo.cpp.o.d -o CMakeFiles/foo.dir/foo.cpp.o -c /usr/local/google/home/danalbert/src/ndk/ndk/foo/foo.cpp
[2/2] : && /usr/local/google/home/danalbert/src/ndk/out/android-ndk-r18-canary/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++  --target=aarch64-none-linux-android --gcc-toolchain=/usr/local/google/home/danalbert/src/ndk/out/android-ndk-r18-canary/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64 --sysroot=/usr/local/google/home/danalbert/src/ndk/out/android-ndk-r18-canary/sysroot  -isystem /usr/local/google/home/danalbert/src/ndk/out/android-ndk-r18-canary/sysroot/usr/include/aarch64-linux-android -D__ANDROID_API__=21 -g -DANDROID -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -Wa,--noexecstack -Wformat -Werror=format-security -std=c++11  -Wl,--exclude-libs,libgcc.a -Wl,--exclude-libs,libatomic.a -nostdlib++ --sysroot /usr/local/google/home/danalbert/src/ndk/out/android-ndk-r18-canary/platforms/android-21/arch-arm64 -Wl,--build-id -Wl,--warn-shared-textrel -Wl,--fatal-warnings -L/usr/local/google/home/danalbert/src/ndk/out/android-ndk-r18-canary/sources/cxx-stl/llvm-libc++/libs/arm64-v8a -Wl,--no-undefined -Wl,-z,noexecstack -Qunused-arguments -Wl,-z,relro -Wl,-z,now -Wl,--gc-sections -Wl,-z,nocopyreloc -pie -fpie  -Wl,--threads -fuse-ld=gold CMakeFiles/foo.dir/foo.cpp.o  -o foo  -latomic -lm "/usr/local/google/home/danalbert/src/ndk/out/android-ndk-r18-canary/sources/cxx-stl/llvm-libc++/libs/arm64-v8a/libc++_static.a" "/usr/local/google/home/danalbert/src/ndk/out/android-ndk-r18-canary/sources/cxx-stl/llvm-libc++/libs/arm64-v8a/libc++abi.a" && :
$ echo $?
0
```

**Comment by DanAlbert** [comment]
If you can provide a failing test case I'll reopen.
