### ISSUE TITLE
NDK app crash with -fexceptions, -Os and -fsanitize=address

### ISSUE THREAD

**Issue by dxin2015** [android-ndk/ndk#615]
Similar to 
https://github.com/android-ndk/ndk/issues/573 
and 
https://github.com/android-ndk/ndk/issues/360
but this happens without -Oz and does not do dlclose, either.

Removing -fsanitize=address would pass the test

This is a further investigation of 
https://github.com/android-ndk/ndk/issues/613
with isolated code and minimal example.

Demo code:

https://github.com/dxin2015/Asan_test_exception
Output:

> ASAN:DEADLYSIGNAL
>=================================================================
>==11865==ERROR: AddressSanitizer: SEGV on unknown address 0x0000000c (pc 0xaefad620 bp >0xbebdbfd8 sp 0xbebdbec8 T0)
>==11865==The signal is caused by a READ memory access.
>==11865==Hint: address points to the zero page.
>ASAN:DEADLYSIGNAL
>AddressSanitizer: nested bug in the same thread, aborting.

NDK Version: 16.1.4479499
Build sytem: cmake triggered by gradle, gradle=4.1, gradle plugin=3.0.0, cmake=3.6.4111459
Host OS: Ubuntu 16.04
Compiler: clang++
ABI: armeabi-v7a
STL: libc++_shared
NDK API level: 26
Device API level: 25

**Comment by rprichard** [comment]
Further reduction: https://github.com/rprichard/Asan_test_exception

I think I'll close this issue in favor of the earlier issue https://github.com/android-ndk/ndk/issues/613.
