### ISSUE TITLE
fix pthread key leak when dlclosing libraries that use __thread

### ISSUE THREAD

**Issue by DanAlbert** [android-ndk/ndk#620]
Refiling [internal bug 71814577](http://b/71814577) so we don't lose track of it.

`__emutls_get_address` in libgcc creates a pthread key per opened shared library the first time a variable with `__thread` storage duration is accessed. If the library is then `dlclose`d, that pthread key isn't released.

We should fix the underlying leak, but in the short term we should move libandroid_support's `g_current_locale` off `thread_local ` so this doesn't appear in the STL.

Note for any readers: this is only a problem if you call `dlclose`, which you're better off not doing anyway.

**Comment by rprichard** [comment]
This should be fixed in r17 beta 1:

https://android-review.googlesource.com/c/toolchain/gcc/+/594297
https://android-review.googlesource.com/c/platform/prebuilts/ndk/+/601016
https://android-review.googlesource.com/c/platform/prebuilts/ndk/+/601094
