### ISSUE TITLE
possible CMake 3.10 incompatibility

### ISSUE THREAD

**Issue by DanAlbert** [android-ndk/ndk#626]
Filing for @feliwir from https://github.com/android-ndk/ndk/issues/480:

> @DanAlbert try using CMake 3.10 with Android NDK r16, libc++_static and API version 14. As soon as i define __ANDROID_API__=14, the entire build is breaking, because of missing fseeko (and friends) in the universal headers. This got fixed by the macro i pasted above.
>
> And no, i can't use the toolchain file provided with the NDK for good reasons.

**Comment by DanAlbert** [comment]
https://github.com/DanAlbert/ndk-cmake-3.10-test-case works for me. You'll need to provide a test case before we can do anything.

**Comment by feliwir** [comment]
Let me fork your issue and make some required changes. Will take me some time, since i need to get back to the machine where i have everything installed

**Comment by feliwir** [comment]
@DanAlbert i can' really reproduce the error with that sample right now, but i've noticed that the flags are different. For some reason "-isystem D:/android-ndk-r16/sources/cxx-stl/gnu-libstdc++/4.9/include/backward" is missing in my configuration.

**Comment by DanAlbert** [comment]
That shouldn't be present if you're using libc++.

**Comment by feliwir** [comment]
@danalbert

It certainly is present in your example. You forgot to define  __ANDROID_API__ in your example repo.

**Comment by DanAlbert** [comment]
> It certainly is present in your example.

Where?

> You forgot to define `__ANDROID_API__` in your example repo.

No, I intentionally did not define it. The build system does that. It doesn't need to be in your build files. If you run `ninja -v` to see the build commands used, you can see that CMake sets this for you:

> /work/src/android-ndk-r16b/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++ --target=armv7-none-linux-androideabi --gcc-toolchain=/work/src/android-ndk-r16b/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64 --sysroot=/work/src/android-ndk-r16b/sysroot   -isystem /work/src/android-ndk-r16b/sources/cxx-stl/llvm-libc++/include -isystem /work/src/android-ndk-r16b/sources/android/support/include -isystem /work/src/android-ndk-r16b/sources/cxx-stl/llvm-libc++abi/include -isystem /work/src/android-ndk-r16b/sysroot/usr/include -isystem /work/src/android-ndk-r16b/sysroot/usr/include/arm-linux-androideabi -march=armv7-a -mthumb -mfpu=vfpv3-d16 -mfloat-abi=softfp -funwind-tables -no-canonical-prefixes **-D__ANDROID_API__=14** -fexceptions -frtti -g -MD -MT CMakeFiles/foo.dir/foo.cpp.o -MF CMakeFiles/foo.dir/foo.cpp.o.d -o CMakeFiles/foo.dir/foo.cpp.o -c ../foo.cpp

**Comment by feliwir** [comment]
It’s not set for me without using add_definitions(-D...)

**Comment by DanAlbert** [comment]
Did you change the test case? I'm using CMake built from the v3.10.2 tag.

**Comment by anutin544** [comment]
Ok

**Comment by anutin544** [comment]
Ok

**Comment by DanAlbert** [comment]
Closing for lack of a repro case. Will reopen if we get something actionable.

**Comment by anutin544** [comment]
Ok
