### ISSUE TITLE
asm generic termbits.h macro "B0" collides with other macros

### ISSUE THREAD

**Issue by matthewn4444** [android-ndk/ndk#630]
#### Description

Compiling with libraries such as (newest) FFMPEG with arm64-v8a collides with several functions of the macro B0 (such as hevc_mvs.c). You can see how it may cause issues in this person's blog:  http://alientechlab.com/how-to-build-ffmpeg-for-android/

Basically what happens is **sysroot/usr/include/asm-generic/termbits.h** defines a macro definition of 

``#define B0 0000000000``

and FFMPEG uses variables such as 

     is_available_B0 = AVAILABLE(cand_up_right, B0) &&
                xb0 < s->ps.sps->width &&
                PRED_BLOCK_AVAILABLE(B0) &&
                !is_diff_mer(s, xB0, yB0, x0, y0);

And then replaces them with 0000000000 as

     is_available_0000000000  = AVAILABLE(cand_up_right, 0000000000 ) &&
                x0000000000  < s->ps.sps->width &&
                PRED_BLOCK_AVAILABLE(0000000000 ) &&
                !is_diff_mer(s, x0000000000 , y0000000000 , x0, y0);

Which then leads to compile issues like

    libavcodec/hevc_mvs.c: In function 'derive_spatial_merge_candidates':
    libavcodec/hevc_mvs.c:368:23: error: 'y0000000' undeclared (first use in this function)
    libavcodec/hevc_mvs.c:368:23: note: each undeclared identifier is reported only once for each function it appears in
    libavcodec/hevc_mvs.c:368:23: error: 'x0000000' undeclared (first use in this function)
    libavcodec/hevc_mvs.c: In function 'ff_hevc_luma_mv_mvp_mode':
    libavcodec/hevc_mvs.c:683:24: error: 'y0000000' undeclared (first use in this function)
    libavcodec/hevc_mvs.c:683:24: error: 'x0000000' undeclared (first use in this function)
    ffbuild/common.mak:60: recipe for target 'libavcodec/hevc_mvs.o' failed

Sorry for my ignorance but does *B0* have some special reason for being 00000000? Could this be changed in the future since this could potentially have collisions with other libraries (for only being 2 letters). (I am not sure if FFMPEG wants to rewrite their variables).

For now, I am using a script to comment that line out (from the termbits.h).

To reproduce you can follow the instructions in that blog (clone FFMPEG, configure, make and make install)

#### Environment Details

* NDK Version: r16b
* Build sytem: ndk-build, standalone tool chain
* Host OS: Linux (Windows 10 Ubuntu shell, I think it is 16.04)
* Compiler: Clang
* ABI:  arm64-v8a
* STL: libc++
* NDK API level: 27
* Device API level: N/A, not compiling for device

**Comment by rprichard** [comment]
From the blog post, the issue appears to be:
 - FFMPEG has a `B0` local variable.
 - It includes `sys/ioctl.h`, which includes `asm/termbits.h`.
 - `asm/termbits.h` defines a `B0` macro.

This code doesn't compile with Bionic, but it does with glibc, musl, and FreeBSD:

```c
#include <sys/ioctl.h>
int main() {
  int B0 = 0;
}
```

Maybe `sys/ioctl.h` shouldn't include `asm/termbits.h`.

**Comment by enh** [comment]
> Maybe sys/ioctl.h shouldn't include asm/termbits.h.

sounds plausible to me, based on what that `#include` gets us. there was no motivation in the git history either.

the only issue will be compatibility with ourselves. testing that for the platform now: https://android-review.googlesource.com/#/c/platform/bionic/+/600968/

**Comment by enh** [comment]
> Sorry for my ignorance but does B0 have some special reason for being 00000000?

(it's one of a number of baud rate constants for serial lines. there's B0, B300, B2400, et cetera. it's a legit POSIX constant, but POSIX says it's in `<termios.h>`.)

**Comment by matthewn4444** [comment]
Cool, would the change make it in the next version of NDK?

**Comment by enh** [comment]
that's more of a problem because `<sys/ioctl.h>` should expose `struct winsize` and the `TIOCM_` constants, and they come from `#include <linux/termios.h>`. i'm not sure there's anything we can do about that, other than suggest that ffmpeg shouldn't try to reuse names reserved by POSIX. (`<sys/ioctl.h>` isn't a POSIX header, so there are no guarantees about which other headers it causes to be included.) closing this bug as "infeasible" unless someone has a clever idea...

btw, that page you linked to isn't the right way to build configure-based projects with the NDK (you can tell because it installs a different compiler). see https://developer.android.com/ndk/guides/standalone_toolchain.html#building_open_source_projects_using_standalone_toolchains for how it should actually work.

**Comment by matthewn4444** [comment]
For anyone reading this in the future, to prevent this without modifying the ndk or ffmpeg code, you can go to /ffmpeg/ffbuild/config.mak, find the line ``CONFIG_LINUX_PERF`` and comment out or type "no" instead of yes. This prevents the code in /libavutil/timer.h to include the header ``<sys/ioctl.h>`` and it will build (which impoorts ``<linux/termios.h>`` and has the B0 constant).

**Comment by JadenJiang** [comment]
@matthewn4444  Very good solution
