### ISSUE TITLE
Sensor accuracy info in C++

### ISSUE THREAD

**Issue by tam2016** [android-ndk/ndk#631]
How would one get information about sensor accuracy in C++? 

I see it's defined in the ASENSOR_STATUS enum, and I see I can get that from the 'status' member of ASensorVector, which I see I can get from ASensorEvent. The problem is it only works for some sensor types (I suppose for those which provide a 3-dimensional vector as sensor information). For example, it seems to work fine with ASENSOR_TYPE_ACCELEROMETER, but not working with ASENSOR_TYPE_ROTATION_VECTOR.

Is this a valid way of getting sensor accuracy data?
How do I get accuracy data for the other sensor types?
Did I miss something about this in the documentation?

**Comment by enh** [comment]
(i've reached out to the sensors team...)

**Comment by tam2016** [comment]
(anything?)

**Comment by DanAlbert** [comment]
@enh: I can't find your email to the sensors team. Have they responded?

**Comment by enh** [comment]
/me checks thread, finds that the engineer in question left Google. i'll find someone else...

**Comment by enh** [comment]
from the sensors team:

The "status" field is primarily relevant for physical sensors that have runtime calibration applied, to indicate the estimated quality of the calibration. For example, the geomagnetic field sensor can be significantly affected by moving around everyday objects, but this can be compensated for once the calibration algorithm collects enough data. However, this concept does not necessarily apply to something like a light sensor, which is generally only calibrated in the factory. This is why Android devices generally only report accuracy for a subset of the available sensors, and why the NDK API does not expose a "status" field for sensor data coming from all sensor types.

Rotation vector has a different way of reporting its accuracy, which is more detailed than what can be exposed through the "status" field. Details on the how accuracy is reported for this and other sensor types can be found in the AOSP documentation at https://source.android.com/devices/sensors/sensor-types. The relevant excerpt for rotation vector is copied below for reference:

In addition, this sensor reports an estimated heading accuracy:

  sensors_event_t.data[4] = estimated_accuracy (in radians)

The heading error must be less than estimated_accuracy 95% of the time.

**Comment by tam2016** [comment]
Thank you.
