### ISSUE TITLE
Windows LTO does not work with bfd

### ISSUE THREAD

**Issue by DanAlbert** [android-ndk/ndk#632]
See https://github.com/android-ndk/ndk/issues/556#issuecomment-361396112

The workaround is simple: add `-fuse-ld=gold.exe` to your ldflags (`-fuse-ld=gold` for other platforms).

**Comment by DanAlbert** [comment]
Tentatively r17, but depends on what your investigation turns up.

**Comment by rprichard** [comment]
I'm not sure why it currently works on 32-bit Windows, but we probably just need to port this change to ld/plugin.c:

https://android-review.googlesource.com/c/toolchain/binutils/+/460597

i.e. Copying `libwinpthread-1.dll` into the `aarch64-linux-android\bin` directory fixes the problem.
```
C:\src\w64\stand-arm64-21\aarch64-linux-android\bin>copy ..\..\lib64\libwinpthread-1.dll .
```

**Comment by rprichard** [comment]
> I'm not sure why it currently works on 32-bit Windows ...

This file was on my PATH: `Android\Sdk\platform-tools\libwinpthread-1.dll`. Most of the SDK binaries are 32 bits.

**Comment by rprichard** [comment]
The fix should be in r17 beta 1.

https://android-review.googlesource.com/c/toolchain/binutils/+/603514
https://android-review.googlesource.com/c/platform/prebuilts/ndk/+/604774
https://android-review.googlesource.com/c/platform/prebuilts/ndk/+/604794
