### ISSUE TITLE
bug in ndk-stack.cmd 

### ISSUE THREAD

**Issue by alexcohn** [android-ndk/ndk#633]
#### Description

The `ndk-stack` command [refers](https://stackoverflow.com/questions/48560120/cant-find-ndk-stack-html-in-sdk-ndk-bundle-folder) to non-existent local `docs/NDK-STACK.html`. It should point to the online guilde https://developer.android.com/ndk/guides/ndk-stack.html. See 

#### Environment Details

* NDK Version: `16.1.4479499` *(and earlier)*.

**Comment by enh** [comment]
https://android-review.googlesource.com/#/c/platform/ndk/+/606276

i've also sent out a patch to fix the %gt;%gt;%gt; in those docs...

**Comment by enh** [comment]
submitted. won't be in r17beta1 but should be in r17beta2 when it comes...
