### ISSUE TITLE
Simpleperf does not work with interval option

### ISSUE THREAD

**Issue by bmanoj125** [android-ndk/ndk#638]
--------------------------------------------------------------------------------

#### Description
Simpleperf stat does not work with the "--interval <samplePeriod>" option. The program simply exits.
If "--interval <samplePeriod>" is not mentioned, there is no problem. I am able to see batch statistics. 

./simpleperf stat -a --interval 100       ------> Does NOT work
./simpleperf stat -a                              ------> Does work

#### Environment Details

I downloaded simpleperf from the r16b NDK Linux 64bit (x86) (https://developer.android.com/ndk/downloads/index.html)

Using it on a rooted Nexus 6P with (API level 25) running Android 7.1

**Comment by yabinc** [comment]
Thanks for reporting the problem. I just fixed it in https://android-review.googlesource.com/c/platform/system/extras/+/618253. Probably will appear in ndk r18.

**Comment by yabinc** [comment]
Simpleperf is part of aosp. You can compile it as below:
1. Follow https://source.android.com/setup/downloading to download AOSP sources. It should be on a linux or darwin machine, having at least 100GB disk space.
2. Run below shell cmds in aosp source directory:
$ . build/envsetup.sh
$ lunch aosp_arm64-eng
$ mmma system/extras/simpleperf -j24
3. If building successfully, the new simpleperf binary should appear at out/target/product/generic_arm64/system/xbin/simpleperf. Note that simpleperf is switching to the new unwinder, so some bugs need to be fixed for -g option of record cmd. So if you only use stat cmd, that's fine. But if you want to run record -g option, please use simpleperf released in ndk.
