### ISSUE TITLE
New Spectre/Meltdown compiler support (flags) in NDK need?

### ISSUE THREAD

**Issue by oscarbg** [android-ndk/ndk#641]
Hi Google NDK team and  @DanAlbert,
after seeing news among most major compilers related to Specte/meltdown attacks:
GCC,LLVM, even Visual Studio C++ compiler:
https://www.phoronix.com/scan.php?page=news_item&px=LLVM-Retpoline-Added
"The LLVM switches are slightly different from GCC's -mindirect-branch options with LLVM opting for -mretpoline and -mretpoline-external-thunk if wanting to use a custom thunk. "
https://blogs.msdn.microsoft.com/vcblog/2018/01/15/spectre-mitigations-in-msvc/

still surprised to see no comments from Android world only update to latest "5january" security updates
on Google phones..

NDK including GCC, LLVM compilers I will want to know if we as developers can pass some recommended compiler flags (for mitigating possible Spectre/Meltdown) when compiling native Android x86 or ARM64 apps..

after all seems OS level mitigation isn't enough as even browsers have done some changes to mitigate possible attacks after all.. altough don't know if this affects also his mobile versions..

anyway clearly at least on Linux world seems these compiler flags are used in compiling the kernel and his modules and if Google patched Android kernel with the 5january security update it may have some GCC or LLVM compiler with support for some of the flags " -mindirect-branch options with LLVM opting for -mretpoline and -mretpoline-external-thunk"..
so question is will backport this flags support from LLVM 7 and GCC 8 to the NDK shipping compilers eventually?
as NDK r17 beta seems around the corner.. changes will be ready for r17? or will have to wait for r18..

or after all this doesn't make much sense on Android world and all needed is Android sceurity updates and no intervention from developers?
thanks..

**Comment by stephenhines** [comment]
App developers do not require retpoline (which is an x86-specific kernel mitigation in any case). We do have retpoline-enabled GCC for building x86 kernels, and a retpoline-enabled Clang will be available in the next few weeks. There are no compiler-specific mitigations (or flags) needed for ARM-based devices at this point. We do work closely with Android Security to ensure that our toolchains have all the necessary patches/features for Android developers, but there isn't anything else needed here right now.

**Comment by oscarbg** [comment]
@stephenhines @DanAlbert 
ok thanks for info..
just one thing to note..
can you help http://www.android-x86.org/ project developers delivering fully mitigated versions of his ISOs by providing access to  **retpoline-enabled GCC for building x86 kernels**..
you will notice that right now this builds use old kernels (4.9.x) but anyway from your AOSP branch:
https://android.googlesource.com/kernel/common/+/android-4.9
so perhaps have the mitigations included and need only an updated GCC as you say..
better yet I have been in contact with @maurossi which provides Android x86 ISOs with  bleeding edge components and also using bleeding edge kernels (4.16rc2 right now) to enable new kernel flags for Spectre/Meltdown to  both Oreo 8.1 and Nougat ISOs:
you can download here they are public:
nougat:
https://drive.google.com/drive/folders/0B_OFHiIqgpSFMlk4bkhaMnAwbDA
oreo 8.1 ISOs:
https://drive.google.com/drive/folders/0B_OFHiIqgpSFTFpkQWc1eXV3ME0
for example you download oreo_x86_64_k416rc2-_amd_dc_llvm60_mesa-18.1.0devel_vulkan.anv.ISO
and can give a try it by yourself if you wish..
anyway as I have been in contact with that developer and to it to enable in latest build:
kernel flag CONFIG_PAGE_TABLE_ISOLATION=y
and now from terminal (Alt+F1) can do a 
grep . /sys/devices/system/cpu/vulnerabilities/*
/sys/devices/system/cpu/vulnerabilities/meltdown:Mitigation: PTI
/sys/devices/system/cpu/vulnerabilities/spectre_v1:Mitigation: __user pointer sanitization
/sys/devices/system/cpu/vulnerabilities/spectre_v2:Vulnerable: Minimal generic ASM retpoline..
instead of :
/sys/devices/system/cpu/vulnerabilities/spectre_v2:Mitigation: Full generic retpoline
with the needed compiler..
All I'm trying to do is motivate enough to Google to share also this GCC retpoline build if not to broad public yes for Android-x86 project devs like @maurossi ..
don't know if should open a separate issue as doesn't exactly is the original issue..
anyway thanks for your support..

**Comment by DanAlbert** [comment]
We've already made those compilers available: https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/x86/x86_64-linux-android-4.9/

**Comment by oscarbg** [comment]
Ok thats pretty nice.. didn't know about it..
many thanks..

**Comment by stephenhines** [comment]
Also, https://support.google.com/androidpartners_security/answer/7625134?hl=en&ref_topic=7064840 was the official Android Partner Security Advisory notice from January. It points to a repository containing retpoline-enabled GCC, but Dan already showed that Android has built new toolchains for use with the kernel.

**Comment by oscarbg** [comment]
thanks @stephenhines can't acccess from my google account  https://support.google.com/androidpartners_security/answer/7625134?hl=en&ref_topic=706484
but anyway no problem now..

**Comment by enh** [comment]
(that link will only be accessible to Android OEMs, not app developers.)
