### ISSUE TITLE
Simpleperf: the result of cpu frequency is different from perf tool

### ISSUE THREAD

**Issue by magicse7en** [android-ndk/ndk#645]
Refer to #644 , one more question:

I disabled DVFS, hotplug and keep all cpus on-line. 
I  guess the simpleperf uses below formula to calculate cpu frequency:
`frequency = cycles / time` ? 

But I use linux-tool perf, the result is correct:
> Performance counter stats for 'ls':
         25.190308      task-clock (msec)         #    0.939 CPUs utilized          
                 0      context-switches          #    0.000 K/sec                  
                 0      cpu-migrations            #    0.000 K/sec                  
               331      page-faults               #    0.013 M/sec                  
          **42514492      cycles                    #    1.688 GHz**                
   <not supported>      stalled-cycles-frontend  
   <not supported>      stalled-cycles-backend   
          27491753      instructions              #    0.65  insns per cycle        
           3803236      branches                  #  150.980 M/sec                  
            272886      branch-misses             #    7.18% of all branches
       0.026814000 seconds time elapsed

**Comment by yabinc** [comment]
I think it's already answered and fixed in https://github.com/android-ndk/ndk/issues/644.
