### ISSUE TITLE
Question: NDK support for Android P DP1 new APIs like Neural Neworks 1.1 in r17 beta1?

### ISSUE THREAD

**Issue by oscarbg** [android-ndk/ndk#646]

**Comment by DanAlbert** [comment]
Really sorry for the delay! r17 hit a lot of bumps with gradle compatibility (now fixed in the current 3.1 gradle plugin, 3.0 more or less works but requires a workaround if you use ABI splits; I'll dig up the doc later) and then a last minute Windows clang bug we wanted to sort out. I just handed the finished build off to QA so it should be out soon 🤞 

If you're feeling adventurous, you can grab the build that I've sent to QA from our build servers: https://android.googlesource.com/platform/ndk/+/master/docs/ContinuousBuilds.md. Build 4640043 of the r17 branch is the one you want.

**Comment by Zingam** [comment]
To avoid starting a new thread. What about Vulkan 1.1 support? Every vendors says they've got the drivers ready already.
Will the Vulkan 1.1 headers etc be available from Android P onwards or also for whatever versions support Vulkan.

**Comment by DanAlbert** [comment]
The headers for NDK r17 are in AOSP now: https://android.googlesource.com/platform/prebuilts/ndk/+/dev/platform/sysroot/usr/include/vulkan/vulkan_core.h

If I'm reading that correctly, that's still 1.0, but I'm really not that up to date on what's happening with vulkan. @critsec would know better.

**Comment by Zingam** [comment]
It was announced yesterday: https://www.khronos.org/news/press/khronos-group-releases-vulkan-1-1
And they also claim to have  the drivers for their SHIELD TV ready as a preview.

**Comment by critsec** [comment]
The r17 header does include Vulkan 1.1 (search for VK_VERSION_1_1). If the r17 P libvulkan.so doesn't include Vulkan 1.1 symbols, a later release for P will. Support for 1.1 on any given device, like 1.0, will depend on the device's GPU driver. But runtime support will be there, so e.g. vkEnumerateInstanceVersion will be present on all P devices and will report 1.1.

**Comment by DanAlbert** [comment]
Spoke with @critsec to confirm and yes we have the symbols for Vulkan 1.1 in NDK r17 beta 1, but the DP1 system images do not have a vulkan 1.1 enabled driver.

**Comment by DanAlbert** [comment]
r17 beta 1 is out now. More details will be mailed to https://groups.google.com/forum/#!forum/android-ndk-announce soon.

**Comment by oscarbg** [comment]
Hi @DanAlbert,
sorry for asking again but seems retpoline support isn't on Clang for x86_64 on build 4640043 you linked me before..
just a quick test:
android-ndk-4640043-windows-x86_64\android-ndk-r17-beta1\toolchains\llvm\prebuilt\windows-x86_64\bin\clang.exe   -mretpoline  -c hello.c
clang.exe: error: unknown argument: '-mretpoline'
just showing version used here:
Android (4639204 based on r316199) clang version 6.0.1 (https://android.googlesource.com/toolchain/clang 279c0d3a962121a6d1d535e7b0b5d9d36d3c829d) (https://android.googlesource.com/toolchain/llvm aadd87ffb6a2eafcb577913073d46b20195a9cdc) (based on LLVM 6.0.1svn)
has this been fixed on final beta1 build or is the same as 4640043??
will be in final r17 builds coming in next months?
also may be stupid question but G++ supports indirect branch mitigation (mindirect-branch=thunk) but GCC not :
android-ndk-4640043-windows-x86_64\android-ndk-r17-beta1\toolchains\aarch64-linux-android-4.9\prebuilt\windows-x86_64\bin\aarch64-linux-android-gcc -mindirect-branch=thunk hello.c
aarch64-linux-android-gcc: error: unrecognized command line option '-mindirect-branch=thunk'

android-ndk-4640043-windows-x86_64\android-ndk-r17-beta1\toolchains\x86_64-4.9\prebuilt\windows-x86_64\bin\x86_64-linux-android-g++.exe -mindirect-branch=thunk hello.c

**Comment by stephenhines** [comment]
@oscarbg That Clang is expected. We did not ship a retpoline-enabled Clang yet, as retpoline is only needed for Intel-based kernel development. It is not intended for general usage. We will have a retpoline-enabled Clang in the next NDK release, although whether that one gets into the final r17 is not known at this point. It all comes down to how quickly we can stabilize and validate it.

**Comment by oscarbg** [comment]
thanks!
