### ISSUE TITLE
r11c for linux lacks x86 toolchain

### ISSUE THREAD

**Issue by tux-mind** [android-ndk/ndk#65]
NDK [download page] show only one downloadable content for Linux.
It's platform is *Linux 64-bit (x86)*, but no x86 toolchiain is available inside.

This make me unable to use it a i686 machine.

Thank you for your help and the great work :blush: 

[download page]: http://developer.android.com/ndk/downloads/index.html

**Comment by DanAlbert** [comment]
WAI. We don't support 32-bit Linux. The SDK tools don't either (or won't very soon).
