### ISSUE TITLE
simplify STL link flags

### ISSUE THREAD

**Issue by wang-bin** [android-ndk/ndk#650]
#### Description

When libc++ becomes the only STL, STL library absolute paths can be removed from linker flags, and standard linker flags `-stdlib=libc++` with linker scripts `libc++.{a,so}` should be used. `ANDROID_STL` can be removed too, because additional linker flags for `ANDROID_STL=c++_static` is simply `-static-libstdc++`.

Considering a cmake project has multiple targets, some are linked to shared libc++, the others are linked to static libc++.  With the new toolchain file, shared libc++ is linked by default, and static libc++ is used if `-static-libstdc++` is added for the target. But it's not easy if STL absolute path is used like current ndk, we have to manually remove the path from `CMAKE_CXX_STANDARD_LIBRARIES` then add shared/static libc++ flags for **all** targets.

#### Environment Details

* NDK Version: 18
* Build sytem:  cmake
* Host OS: all
* Compiler: clang
* ABI: all
* STL: libc++
* NDK API level: all
* Device API level: all

**Comment by wang-bin** [comment]
another effect is libstdc++.so will be disappeared from dependency

**Comment by DanAlbert** [comment]
I've actually already written most of the Clang patches for this. Waiting for our compiler folks to give them a once-over before I send them upstream. From there it's just a matter of getting the updates into the NDK (and drastically reshaping the NDK so the compiler can find things, but again, that work is already done).

> another effect is libstdc++.so will disappear from dependency

This is already the case. We use `-nostdlib++` in ndk-build and CMake when appropriate.

**Comment by DanAlbert** [comment]
Stack of WIP clang patches are here, if anyone is curious: https://android-review.googlesource.com/c/toolchain/clang/+/635808

**Comment by DanAlbert** [comment]
And the roadmap item this tracks (been there for ages, but I've never opened a bug for it): https://android.googlesource.com/platform/ndk/+/master/docs/Roadmap.md#make-standalone-toolchains-obsolete

**Comment by DanAlbert** [comment]
r18 might be ambitious given that these changes haven't even been sent upstream yet, but I'll optimistically triage for that and we'll see...

**Comment by wang-bin** [comment]
since `-nostdlib++` was added, I'm not able to link static libc++ with `-static-libstdc++ -stdlib=libc++` in a cmake project. So how can i link to shared libc++ for some targets and static libc++ for others?
btw, i find some changes of libc++ ld script in the latest ndk. They have api level suffix, for example libc++.so.21, how are they used? I didn't see them in command line.

**Comment by DanAlbert** [comment]
Sorry for the temporary breakage. I didn't realize that configuration was working before.

I've actually incidentally fixed this already in master (patches are not submitted yet since we're waiting for a Clang update that makes them work) as part of the r19 toolchain rework (CMake will be using `-stdlib=libc++` rather than `-nostdlib++` and explicit paths in r19).

> So how can i link to shared libc++ for some targets and static libc++ for others?
btw, i find some changes of libc++ ld script in the latest ndk. They have api level suffix, for example libc++.so.21, how are they used? I didn't see them in command line.

They're not used by CMake. They're for standalone toolchains and third-party build systems.

**Comment by DanAlbert** [comment]
CMake no longer uses `-nostdlib++` except when `ANDROID_STL` is `none`.
