### ISSUE TITLE
Simpleperf build fails on master branch

### ISSUE THREAD

**Issue by bmanoj125** [android-ndk/ndk#654]
Not sure if this is the right place for this. Please provide direction if not.

**Trying to compile simpleperf from master branch results in error:**

Copy: /simpleperf_unit_test/simpleperf_unit_test.configninja: error: mkdir(/simpleperf_unit_test): Permission denied

This seems like a simple fix, but I am not sure how to do this.
This has been the case for a week now.

I tried reverting back to the changeID for simpleperf that I want (Ida90ecd465e5c63f0f813cde63d70acfeb1281da) but this version does not seem to gel well with current master branch.

I am compiling for lunch configuration aosp_arm64

error: external/perf_data_converter/src/quipper/Android.bp:163:1: dependency "libsimpleperf_elf_read" of "quipper_unit_tests" missing variant:
  arch:linux_glibc_x86_64, link:static
available variants:
  arch:android_arm64_armv8-a, image:core, link:static
  arch:android_arm_armv8-a, image:core, link:static

Any help will be appreciated!

#### Environment Details
AOSP master branch (03/16/18)
lunch aosp_arm64 (For use on Nexus 6P)
Ubuntu 16.04 build system

**Comment by DanAlbert** [comment]
I think the closest thing to what you want is https://groups.google.com/forum/#!forum/android-building, but I'll CC @yabinc here anyway. Going to close this bug though.

**Comment by bmanoj125** [comment]
So this is not a problem with the simpleperf_unit_test build scripts?

**Comment by DanAlbert** [comment]
It could be, but if it happened outside the NDK then it's not an NDK bug :)

**Comment by yabinc** [comment]
I also met with first problem one or two days ago: /simpleperf_unit_test/simpleperf_unit_test.configninja: error: mkdir(/simpleperf_unit_test): Permission denied
I didn't change the way building simpleperf_unit_test recently. So it looks like a build problem. Instead of looking into this, I used a dirty solution:
create simpleperf_unit_test directory under /, and chown it to your user and group.

For the second problem, you can try sync external/perf_data_converter and system/extras directory.

**Comment by yabinc** [comment]
I will try the simpleperf_unit_test.config thing, and if fails on a clean build, will assign a bug to the build team.

**Comment by bmanoj125** [comment]
Thank you @yabinc 
I will try your dirty solution now and see what happens.
I also posted in the build group that Dan pointed out, just in case.
Hope it gets resolved.

**Comment by DanAlbert** [comment]
@colincross

**Comment by colincross** [comment]
Thanks, this is fixed by https://android-review.googlesource.com/c/platform/build/+/642759

**Comment by yabinc** [comment]
After sync build/make, the /simpleperf_unit_test problem no longer exist.
