### ISSUE TITLE
zlib: use hardware-accelerated crc32

### ISSUE THREAD

**Issue by landfillbaby** [android-ndk/ndk#658]
the Pixel, and most other ARMv8-based devices, include support for the ARM CRC32 instruction set (optional in ARMv8-A, mandatory in ARMv8.1-A onward), but it isn't utilized in either `/system/lib[64]/libz.so`'s crc32 function.
clang and gcc both support intrinsics for these instructions, so it would be simple enough to implement; see [Cloudflare's fork](https://github.com/cloudflare/zlib/blob/94652610e8cb2334440f03b4248ed26b53322d3d/crc32.c#L24-53) for example. the `#ifdef __aarch64__` could be changed to`#if defined(__aarch64__)||defined(__arm__)` to account for 32-bit `libz.so` builds, the intrinsics are the same either way

**Comment by enh** [comment]
have you tried upstreaming this to zlib? we're much more likely to take it then.
