### ISSUE TITLE
libatomic.a contains relocs unknown to old android linker

### ISSUE THREAD

**Issue by cjhopman** [android-ndk/ndk#66]
Android linker <5.0 does not understand R_386_IRELATIVE. The gcc toolchain will use this for functions with ifunc attribute.

The ndk's libatomic uses the ifunc attribute and thus this relocation. Code like the following:

  uint64_t a = 0, b = 0;
  __atomic_store(&a, &b, __ATOMIC_SEQ_CST);

compiled w/ clang will fail to load on android <5.0 with error like:
java.lang.UnsatisfiedLinkError: dlopen failed: unknown reloc type 42 @ 0xa869f454 (75)

**Comment by DanAlbert** [comment]
Dup of https://github.com/android-ndk/ndk/issues/31
