### ISSUE TITLE
-march=armv8.2a+fp16 doesn't seem to turn on the +fp16 part

### ISSUE THREAD

**Issue by mtklein** [android-ndk/ndk#660]
I'd expect that when compiling for -march=armv8.2a+fp16, half-float NEON support should be enabled and that we'd be able to detect this with #if defined(__ARM_FEATURE_FP16_VECTOR_ARITHMETIC).  I can get this to work with a Homebrew-built Clang 6 (clang version 6.0.0 (tags/RELEASE_600/final)) but not with the Clang in either NDK 16b or NDK 17 beta1.

To reproduce,

   $ clang -target aarch64-linux-android -march=armv8.2a+fp16 -dM -E - </dev/null | grep __ARM_FEATURE_FP16_VECTOR_ARITHMETIC

Ideally you see

   #define __ARM_FEATURE_FP16_VECTOR_ARITHMETIC 1

Using android-ndk-r17-beta1/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang or the clang from NDK 16b instead doesn't find __ARM_FEATURE_FP16_VECTOR_ARITHMETIC defined.  16b appears to be based on Clang 5.0, but the r17-beta1 build looks newer[1] than the Homebrew Clang that's working above.

[1] Android (4639204 based on r316199) clang version 6.0.1 (https://android.googlesource.com/toolchain/clang 279c0d3a962121a6d1d535e7b0b5d9d36d3c829d) (https://android.googlesource.com/toolchain/llvm aadd87ffb6a2eafcb577913073d46b20195a9cdc) (based on LLVM 6.0.1svn)

**Comment by pirama-arumuga-nainar** [comment]
This macro was added in r321294, which is in neither of the NDK clangs you tested.  I checked that the Clang update under test (which will likely make r18) has this macro defined..

**Comment by mtklein** [comment]
Ah, thanks.  No chance to make this into r17?

**Comment by pirama-arumuga-nainar** [comment]
@DanAlbert can comment on the NDK roadmap.

I believe the policy is to not take Clang updates after beta 1 to avoid surprises during QA/testing.

**Comment by mtklein** [comment]
Thanks, that sounds totally reasonable.

**Comment by DanAlbert** [comment]
Leaving this open until we actually do get the updated clang in r18.

**Comment by pirama-arumuga-nainar** [comment]
We switched the platform to clang-4679922 (based on upstream r326829) today.

**Comment by DanAlbert** [comment]
We have this clang in r18 (master branch) now.

> Ideally you see
>
> #define __ARM_FEATURE_FP16_VECTOR_ARITHMETIC 1

Confirmed.
