### ISSUE TITLE
dlopen failed: cannot locate symbol "__libc_current_sigrtmin" 

### ISSUE THREAD

**Issue by hoodar** [android-ndk/ndk#662]
# Description
1. __ANDROID_API__=14 is defined while compiling.
2. SIGRTMIN is used in code.
3. dlopen will fail on Android 4.4.4 which sdk level is 19

The definition for SIGRTMIN caused this issue.
`/* We take a few real-time signals for ourselves. May as well use the same names as glibc. */
**#define SIGRTMIN (__libc_current_sigrtmin())**
#define SIGRTMAX (__libc_current_sigrtmax())

#if __ANDROID_API__ >= 21
int __libc_current_sigrtmin(void) __INTRODUCED_IN(21);
int __libc_current_sigrtmax(void) __INTRODUCED_IN(21);
#endif /* __ANDROID_API__ >= 21 */
`

# Environment Details
NDK Version: 17beta1
Build sytem: standalone toolchain
Host OS: Windows 64bit
Compiler: clang
STL: libc++
NDK API level: 14
Device API level: 19

**Comment by enh** [comment]
that's weird because we claimed to have fixed this in https://github.com/android-ndk/ndk/issues/536 (see `<android/legacy_signal_inlines.h>` for the fix).

what's the actual error you saw from dlopen? are you *sure* `__ANDROID_API__` is 14?

**Comment by hoodar** [comment]
sysroot is wrong while compiling. Sorry for bothering.
