### ISSUE TITLE
wallet for hybrid mobile application

### ISSUE THREAD

**Issue by SandraMason** [android-ndk/ndk#663]
Hell everyone,

I'm trying to make a hybrid mobile application using PhoneGap (html, css, JavaScript) and i'm planning to add payment feature to the application, it should generate a QR code that contains user's information (regarding payment-the amount, the service that he's paying for), this wallet also should provide a QR code that shows a certain document for the user once it's get scanned.

I have been searching for wallet/passbook (which is available for ios only) but I didn't find a plugin that is suitable for both. 

I will be thankful if anyone could provide me with information on how to solve this issue.

**Comment by DanAlbert** [comment]
Try our mailing list: https://groups.google.com/forum/#!forum/android-ndk.

**Comment by SandraMason** [comment]
Hello,

Can I know why did you close my post?

Regards,
Sara

**Comment by SandraMason** [comment]
which mailing list?
I have added my issue as a new topic to the link that you sent but it's not
added yet?

**Comment by DanAlbert** [comment]
The one I linked to. It's a moderated list and was pending approval. It's there now.
