### ISSUE TITLE
"libcxx" static link with "-fno-exception" uses exception enabled flavor

### ISSUE THREAD

**Issue by DarkZeros** [android-ndk/ndk#667]
#### Description

Currently libc++ in static linkage is being linked with exception handling enabled.
Even if the final library does explicitly compile with "-fno-exceptions".

The issue is very minor, since is just functionality "unused", but there should be a pre-compiled variant of the library without exceptions to save some exception handling code in the final library output.

Apparently it is possible to compile "libcxx" in that flavor:

> LIBCXX_ENABLE_EXCEPTIONS:BOOL
> 
>     Default: ON
> 
>     Build libc++ with exception support.

#### Example

In a production library, I currently have 509kB of library of which:
  .ARM.extab + .ARM.exidx (unwinding code) occupies 43kB (8.5% space)
All the library has been compiled with "-fno-exceptions", the functionality is the same with or without exceptions, but still those sections remain.

NOTE: I know this is a minor issue, but it is still something good to have for the future, so we can save space in apps and in the downloading process of those apps.
  
#### Example

* NDK Version: r16b
* Build sytem: ndk-build being triggered from gradle (Android Studio)
* Host OS: Linux, ubuntu 16.04 LTS 
* Compiler: clang (default 16b)
* ABI: armeabi-v7a
* STL: libc++_static

**Comment by rprichard** [comment]
> .ARM.extab + .ARM.exidx (unwinding code) occupies 43kB (8.5% space)

FWIW: The next major Clang update in the NDK should reduce the size of these tables by about half: https://reviews.llvm.org/D43001. I think we're expecting it in r18.

**Comment by DanAlbert** [comment]
libc++ doesn't support being built without exceptions.
