### ISSUE TITLE
[Doc] - Links on NDK documentation are broken

### ISSUE THREAD

**Issue by ketanm** [android-ndk/ndk#668]
Hi,
Not sure if this is the right platform but for past week, all inter-page cross-links on NDK documentation page are broken - https://developer.android.com/ndk/reference/ndk_media_extractor_8h.html

No link on that page appears to work.

**Comment by enh** [comment]
looks like the underscores problem:

https://developer.android.com/ndk/reference/_ndk_media_extractor_8h.html#a1527204eef21df57f7d75300c7800040

i thought that was fixed?

**Comment by DanAlbert** [comment]
> i thought that was fixed?

No, I was under the impression that this was broken for prior updates to the site as well and we just needed to wait until we migrated to the new doxygen import tool, but Quddus sent me his update scripts and it looks like they do the necessary rewriting. Working on updating them now.

**Comment by DanAlbert** [comment]
Published.

**Comment by ketanm** [comment]
Thanks for fixing it fast.
I noticed that it has some methods (AMediaCodecActionCode_isTransient) which do not appear in the Android codebase (https://android.googlesource.com/platform/frameworks/av/+/master/media/ndk/NdkMediaCodec.cpp). 

Are those methods expected to be in latest/beta or somewhere?

Ketan
