### ISSUE TITLE
r18 and API 15

### ISSUE THREAD

**Issue by rcdailey** [android-ndk/ndk#670]
I got word from [another issue](https://issuetracker.google.com/issues/75993790#comment10) that API 15 support will be dropped (*not* deprecated) in NDK r18. For my own education, I'd like to understand why API 15 is being removed. What are the technical hurdles? Secondly, is there any possibility of deprecating it instead? In a situation similar to the linked Google issue, dropping API 15 support will result in being stuck on r17 as well as any issues and toolchain versions with it. This means I will not be able to use newer versions of libraries and tools going forward.

I'm sure discussions happened about this but I don't see them on record anywhere. So I'd like to raise an issue here to see if we can rescind the decision.

**Comment by DanAlbert** [comment]
PIE vs non-PIE support is the non-trivial technical burden for supporting releases older than API 16 in the NDK. We do maintain download links for old NDKs, so anyone that needs to continue supporting old releases can still use those.

Another reason is the desire to continue reducing libandroid_support. Each additional API level that we can drop reduces APK bloat (even if you're targeting android-21+ and not linking it directly, libc++ itself still uses it).

If anyone is really intent on using r18+ to target ICS, you can possibly target android-16 and wire up the PIE support (if you have executables in your project; it's not needed for shared libraries) and add your own shims for any missing libc APIs you may need. This is generally against our guidance, but it's not impossible to do.

**Comment by rcdailey** [comment]
Thanks for the detailed feedback. I'm not familiar with PIE. I also do not care for executables (I only build shared libraries). Is it probable that given only the need for shared libraries, that I can specify a minimum SDK version of 16 and my shared libraries will still load on API 15?

**Comment by DanAlbert** [comment]
> Is it probable that given only the need for shared libraries, that I can specify a minimum SDK version of 16 and my shared libraries will still load on API 15?

I think so. ICS and JB (android-16, that is) were very similar in libc/libm. The laoder is the thing that had the big changes, and I don't think it had any big changes for shared libraries. That's not the case once you start considering JB MR1 and JB MR2 (androids 17 and 18), but that shouldn't be a concern for your use case.

**Comment by rcdailey** [comment]
I will bookmark this issue and try upgrading our minimum API to 16 when r18 is released. I'll come back here and let you know how it went. Thanks again for all the great info!
