### ISSUE TITLE
How to redirect stdout and stderr to android logcats?

### ISSUE THREAD

**Issue by rcdailey** [android-ndk/ndk#671]
I apologize that I'm starting a discussion in the issue section, however I am not aware of any other place I can go to ask actual Google developers for answers to difficult questions.

I have seen many different attempts to redirect stdout and stderr to android logcats in native code. Most involve `fork()` which isn't appropriate, at least in my case, because it spawns my service processes multiple times and they are not designed to be reentrant/cloned.

I have many system libraries I load that print logs using `printf()` and such. Right now I do not see these diagnostics unless I pipe them to android logcats. Do the NDK developers have a recommended method of doing this? Is there built-in support? Note that for my specific case, I'm guaranteed to have root access so I'm perfectly OK with solutions that require that.

Thanks in advance. Note I'm using the latest NDK.

**Comment by enh** [comment]
all the variants boil down to either `fork` or "use a better logging system than printf".

the logging system we use internally is `<android-base/logging.h>` from the non-NDK `libbase` library (https://android.googlesource.com/platform/system/core/+/master/base/). it has one C++ `operator<<` interface, but a variety of backends for stderr, files, dmesg, or logcat (or, indeed, your own custom destination). a large part of the motivation for this (over the historical Android `ALOGE`-style macros) was the pluggable backends.

if you were desperate you could probably freopen stdout/stderr to files, and then fork+exec something that basically does the same as `logwrapper tail -f` on the files.

**Comment by DanAlbert** [comment]
> I apologize that I'm starting a discussion in the issue section, however I am not aware of any other place I can go to ask actual Google developers for answers to difficult questions.

I watch our mailing list, but I think most of the others don't. Posting here is totally fine with us.

**Comment by alexcohn** [comment]
@rcdailey have you tried [this solution](https://codelab.wordpress.com/2014/11/03/how-to-use-standard-output-streams-for-logging-in-android-apps/) with only one extra thread overhead?
