### ISSUE TITLE
Program behavior is not correct when i change the compiler gcc to clang under armeabi ABI

### ISSUE THREAD

**Issue by garryyan** [android-ndk/ndk#675]
#### Description

I found I get the wrong result when i change the compiler gcc to clang under armeabi ABI.

The result is correct If I compiler it under armeabi-v7a ABI or I use "volatile" keyword.

```
int main()
{
    uint64_t a = 1327766428005490377U, b = 11288243973786793369U, c = 2605551527157454794U,
             d = 10827106727145494102U, e = 2828362429283368417U, f = 16757676330087486975U, 
             g = 3683907821240050138U, h =17769778546089854903U;
   
    printf("\nno volatile var, wrong result:\n");
    for (int i = 0; i < 2; ++i) {
        mix(a,b,c,d,e,f,g,h);
        printf("a:%llu b:%llu c:%llu d:%llu e:%llu f:%llu g:%llu h:%llu\n", a, b, c, d, e, f, g, h);
    }

    printf("\nvolatile var, correct result: \n");
    volatile uint64_t aa = 1327766428005490377U, bb = 11288243973786793369U, cc = 2605551527157454794U,
                      dd = 10827106727145494102U, ee = 2828362429283368417U, ff = 16757676330087486975U,
                      gg = 3683907821240050138U, hh =17769778546089854903U;
   
    for (int i = 0; i < 2; ++i) {
        mix(aa,bb,cc,dd,ee,ff,gg,hh);
        printf("aa:%llu bb:%llu cc:%llu dd:%llu ee:%llu ff:%llu gg:%llu hh:%llu\n", aa, bb, cc, dd, ee, ff, gg, hh);
    }

    return 0;
}

```

Test Case:
[test.zip](https://github.com/android-ndk/ndk/files/1934405/test.zip)

#### Environment Details

* NDK Version: 
Pkg.Desc = Android NDK
Pkg.Revision = 16.1.4479499
* Build sytem: ndk-build
* Host OS: Windows && Mac
* Compiler:  Clang 
* ABI: armeabi
* STL:
* NDK API level:
* Device API level:

**Comment by DanAlbert** [comment]
ARM5 is not supported. Do you see this issue on any other ABIs?

**Comment by DanAlbert** [comment]
I'm guessing not since it doesn't appear on ARM7, but will reopen if for some reason it shows up on one of the others.

**Comment by garryyan** [comment]
I did not see this issue on other ABIs.
I know armeabi will be removed since ndk-r17.  I just wonder why is it. I guessed the cause is "Memory Ordering at Compile Time", but I am not sure.
Also I have to support armeabi in my project.  I will resolve this issue by using gcc compiler. Thanks a lot.

**Comment by DanAlbert** [comment]
GCC is also not supported and will be removed in r18.

> Also I have to support armeabi in my project.

Are you sure? armeabi covers roughly zero devices that aren't also covered by armeabi-v7a.

**Comment by garryyan** [comment]
> GCC is also not supported and will be removed in r18.

I know it. I think we won't support armeabi be long. I will change gcc to clang in the near future.


>Android itself doesn't support ARM versions below ARMv7 from Android 4.4 (API level 19). Since Android 4.0 (API level 15), it doesn't support ARMv5/ARMv6 by default but can be modified to build for those platforms

But we have 1.3% users using android-18 and android-17. Or if our app's minSdkVersion is android-19, I will remove armeabi support.  I can't be too careful.
