### ISSUE TITLE
Building a specific module with ndk-build doesn't trigger install

### ISSUE THREAD

**Issue by gpakosz** [android-ndk/ndk#677]
Hello,

I observed the following: when trying to build a specific module, instead of all the modules defined, with `ndk-build`, then the module is not installed.

Assuming my `Android.mk` defines
```
LOCAL_MODULE := Foo
```

Then doing
```
$ ndk-build NDK_APPLICATION_MK=./Application.mk NDK_PROJECT_PATH=. APP_OPTIM=release
```

builds `libFoo.so` but doesn't install it.

I suspect this is because `build-binary.mk` defines
```
$(LOCAL_INSTALLED): $(LOCAL_BUILT_MODULE) clean-installed-binaries
	$(call host-echo-build-step,$(PRIVATE_ABI),Install) "$(PRIVATE_NAME) => $(call pretty-dir,$(PRIVATE_DST))"
	$(hide) $(call host-install,$(PRIVATE_SRC),$(PRIVATE_DST))
	$(hide) $(PRIVATE_STRIP_CMD)
```
but `$(LOCAL_MODULE)` doesn't depend on `$(LOCAL_INSTALLED)`.

Is there a way to build **and** install a specific module?

**Comment by DanAlbert** [comment]
I think you accidentally left off part of the command line, because what you've show should build and install all modules (it doesn't explicitly name a target).

> Is there a way to build and install a specific module?

`ndk-build ... libs/$ABI/libFoo.so`

Going to leave this open because I think there's still a missing piece of info that might change the answer...

**Comment by gpakosz** [comment]
My bad you're right. I'm doing
```
$ ndk-build ... Foo
```

I'll try what you suggest but I'm afraid `$ABI` will just expand to the empty string so I'm not sure you what you mean exactly

**Comment by gpakosz** [comment]
For some reason I totally forgot about `APP_MODULES`. It's perfect and clearly documented already. 

Thank you Dan. Sorry for the noise.

**Comment by DanAlbert** [comment]
Not a problem. I'd forgotten about it too :)
