### ISSUE TITLE
AStorageManager unable to mount unencrypted expansion file

### ISSUE THREAD

**Issue by Van-der-Deken** [android-ndk/ndk#678]
### Description

Native StorageManager - AStorageManager constantly failing to mount unencrypted expansion file by `AStorageManager_mountObb (AStorageManager *mgr, const char *filename, const char *key, AStorageManager_obbCallbackFunc cb, void *data)` call. At callback I always recieves AOBB_STATE_ERROR_INTERNAL (code 20). Expansion file correctness checked by StorageManager, in both cases path was the same (key for Java - null, for native - "").

Despite of this, AStorageManager can successfully load encrypted file, so it isn't completely broken.

**Comment by DanAlbert** [comment]
The NDK only includes stub definitions of the platform APIs. You'll need to file a platform bug at http://b.android.com. Make sure to include your platform details, both your NDK API level (`minSdkVersion`) as well as the OS and model of the device.
