### ISSUE TITLE
If your code #defines uint and includes stdio.h compiling will fail

### ISSUE THREAD

**Issue by meepingsnesroms** [android-ndk/ndk#679]
I am trying to compile my palm os emulator(libretro version and qt version) with the android ndk:
https://github.com/meepingsnesroms/libretro-palmm515emu

stdio.h is including sys/types.h and it trys "typedef unsigned int uint" after I "#define uint unsigned int", this breaks std C compatibility and prevents it from compiling.

Even worse, this is a library I am compiling into my project, I cant modify whats breaking or I wont be able to update it in the future.

This is the error I get:
In file included from /Users/Hoppy/Desktop/projects/PalmEmuRedo/libretro-palmm515emu/libretroBuildSystem/jni/../../src/m68k/m68kcpu.c:42:0:
/Users/Hoppy/Desktop/projects/PalmEmuRedo/libretro-palmm515emu/libretroBuildSystem/jni/../../src/m68k/m68kcpu.h:75:16: error: duplicate 'unsigned'
 #define uint   unsigned int
                ^
/Volumes/compHDD/AndroidSDK/android-ndk-r10e/platforms/android-21/arch-arm64/usr/include/sys/types.h:142:29: note: in expansion of macro 'uint'
 typedef unsigned int        uint;
                             ^
/Users/Hoppy/Desktop/projects/PalmEmuRedo/libretro-palmm515emu/libretroBuildSystem/jni/../../src/m68k/m68kcpu.h:75:25: error: two or more data types in declaration specifiers
 #define uint   unsigned int
                         ^
/Volumes/compHDD/AndroidSDK/android-ndk-r10e/platforms/android-21/arch-arm64/usr/include/sys/types.h:142:29: note: in expansion of macro 'uint'
 typedef unsigned int        uint;
                             ^
In file included from /Volumes/compHDD/AndroidSDK/android-ndk-r10e/platforms/android-21/arch-arm64/usr/include/stdio.h:50:0,
                 from /Users/Hoppy/Desktop/projects/PalmEmuRedo/libretro-palmm515emu/libretroBuildSystem/jni/../../src/m68k/m68kcpu.c:565:
/Volumes/compHDD/AndroidSDK/android-ndk-r10e/platforms/android-21/arch-arm64/usr/include/sys/types.h:142:1: warning: useless type name in empty declaration
 typedef unsigned int        uint;
 ^
make: *** [/Users/Hoppy/Desktop/projects/PalmEmuRedo/libretro-palmm515emu/libretroBuildSystem/obj/local/arm64-v8a/objs/retro/__/__/src/m68k/m68kcpu.o] Error 1
PuffedCheek:jni Hoppy$

**Comment by meepingsnesroms** [comment]
Also when testing use this version: https://github.com/meepingsnesroms/libretro-palmm515emu/commit/8cb1533b30b980572452071e5ffca30d95eda36b

I temporarily commented out stdio.h to get it to compile in newer versions.

**Comment by enh** [comment]
this isn't a new change. `<sys/types.h>` on Android has had these BSD types since before cupcake. glibc has them too. i think we'd break more code than we'd fix if we changed this...

we're more likely to go in the opposite direction and add the other similar types (see https://android-review.googlesource.com/c/platform/bionic/+/451457), though that's stalled because it broke renderscript.

we could probably put `uint`/`uint_t` behind `_BSD_SOURCE`/`_GNU_SOURCE` guards without breaking anything, and that would match glibc. (macos has it behind `_DARWIN_C_SOURCE`.)

https://android-review.googlesource.com/c/platform/bionic/+/674973

**Comment by rprichard** [comment]
AFAICT, `sys/types.h` declares a `uint` typedef on glibc even without `_{BSD,GNU,DEFAULT}_SOURCE`.

glibc's `stdio.h`, on the other hand, doesn't declare `uint`, even with `_{BSD,GNU,DEFAULT}_SOURCE`. Maybe the complaint is that Bionic's `stdio.h` shouldn't include `sys/types.h`.

**Comment by enh** [comment]
reality disagrees...
```
system/core/trusty/storage/lib/storage.c:105:55: error: unknown type name 'uint'
const struct iovec *tx_iovs, uint tx_iovcnt,
```

i think this is going to have to be considered WAI.
