### ISSUE TITLE
compile failed because of duplicated signal.h in ndk-bundle

### ISSUE THREAD

**Issue by EvanLee2048** [android-ndk/ndk#681]
* NDK Version: latest version
* Build sytem: cmake
* Host OS: Mac
* Compiler: Clang
* ABI: armeabi
* STL: gnustl_static
* NDK API level: 
* Device API level: minimum 21

I recently try to reimport a legacy c++ library to new app.
The c++ library was ok with ndk-build and cmake.
I successfully build .so with cmake standalone with this 
cmakeList : 
```
cmake_minimum_required(VERSION 3.8)
include(GNUInstallDirs)
set(CMAKE_CXX_STANDARD 11)
find_package(JNI REQUIRED)
include_directories(${JNI_INCLUDE_DIRS})
set(CMAKE_BUILD_TYPE Release)
set(CMAKE_SYSTEM_NAME Android)
set(CMAKE_ANDROID_ARCH_ABI armeabi)
set(CMAKE_ANDROID_NDK ~/Android/Sdk/ndk-bundle)
set(CMAKE_ANDROID_STL_TYPE gnustl_static)
set(CMAKE_ANDROID_API_MIN 21)
set(CMAKE_CXX_FLAGS "-g")
set(CMAKE_CXX_FLAGS "-shared")
set(CMAKE_CXX_FLAGS "-fPIC")
```

Then I make a new app in android studio 3.0, I click C++ support
so I have default CMakeLists.txt and default setting in gradle.
I try to compile the library but failed. It seems cmake imported duplicated
signal.h from ndk-bundle, one with path : sysroot/usr/include/signal.h,
another one : sysroot/usr/include/arm-linux-androideabi/asm/signal.h

I spent 2 day on stackoverflow and add & removal in cmake but still no progress.

some part of cmakelist : 

```
cmake_minimum_required(VERSION 3.4.1)
include(GNUInstallDirs)
set(CMAKE_CXX_STANDARD 11)
set(CMAKE_BUILD_TYPE Release)
set(CMAKE_SYSTEM_NAME Android)
set(CMAKE_ANDROID_ARCH_ABI armeabi-v7a)
set(CMAKE_ANDROID_NDK ~/Library/Android/sdk/ndk-bundle)
set(CMAKE_ANDROID_STL_TYPE gnustl_static)
set(CMAKE_ANDROID_API_MIN 21)
set(CMAKE_CXX_FLAGS "-g")
set(CMAKE_CXX_FLAGS "-shared")
set(CMAKE_CXX_FLAGS "-fPIC")
set(CMAKE_ASM_COMPILER "${ANDROID_TOOLCHAIN_PREFIX}gcc${ANDROID_TOOLCHAIN_SUFFIX}" )

if(${ANDROID_ABI} STREQUAL "arm64-v8a")
    include_directories(${ANDROID_SYSROOT}/usr/include/aarch64-linux-android)
else()
    include_directories(${ANDROID_SYSROOT}/usr/include/arm-linux-androideabi)
endif()
```

some stacktrace : 

> In file included from /Users/e/Project/app/src/main/cpp/Decoder/Exception.h:24:
> In file included from /Users/e/Library/Android/sdk/ndk-bundle/sources/cxx-stl/gnu-libstdc++/4.9/include/string:40:
> In file included from /Users/erickwok/Library/Android/sdk/ndk-bundle/sources/cxx-stl/gnu-libstdc++/4.9/include/bits/char_traits.h:40:
> In file included from /Users/erickwok/Library/Android/sdk/ndk-bundle/sources/cxx-stl/gnu-libstdc++/4.9/include/bits/postypes.h:40:
> In file included from /Users/e/Library/Android/sdk/ndk-bundle/sources/cxx-stl/gnu-libstdc++/4.9/include/cwchar:44:
> In file included from /Users/e/Library/Android/sdk/ndk-bundle/sysroot/usr/include/wchar.h:37:
> In file included from /Users/e/Library/Android/sdk/ndk-bundle/sysroot/usr/include/time.h:33:
> In file included from /Users/e/Library/Android/sdk/ndk-bundle/sysroot/usr/include/sys/time.h:37:
> In file included from /Users/e/Library/Android/sdk/ndk-bundle/sysroot/usr/include/sys/select.h:36:
> /Users/e/Library/Android/sdk/ndk-bundle/sysroot/usr/include/signal.h:96:18: error: expected ';' at end of declaration list
>     sighandler_t sa_handler;
>                  ^
> /Users/e/Library/Android/sdk/ndk-bundle/sysroot/usr/include/arm-linux-androideabi/asm/signal.h:85:22: note: expanded from macro 'sa_handler'
> #define sa_handler _u._sa_handler
>

**Comment by DanAlbert** [comment]
> It seems cmake imported duplicated
signal.h from ndk-bundle, one with path : sysroot/usr/include/signal.h,
another one : sysroot/usr/include/arm-linux-androideabi/asm/signal.h

The second one should have the include path of `<asm/signal.h>`, not `<signal.h>`. It sounds like this is probably using the vanilla CMake NDK support.

> if(${ANDROID_ABI} STREQUAL "arm64-v8a")
    include_directories(${ANDROID_SYSROOT}/usr/include/aarch64-linux-android)
else()
    include_directories(${ANDROID_SYSROOT}/usr/include/arm-linux-androideabi)
endif

This should be unnecessary.

**Comment by DanAlbert** [comment]
>> Just to clarify: is this using our cmake toolchain file, or the vanilla cmake NDK support?
>
> For simplicity I attempted to keep things default as much as possible. So, I don't know as
I should have not configured this part.

Did you invoke CMake with `-DCMAKE_TOOLCHAIN_FILE=path/to/ndk/build/cmake/android.toolchain.cmake`?

**Comment by EvanLee2048** [comment]
> Did you invoke CMake with -DCMAKE_TOOLCHAIN_FILE=path/to/ndk/build/cmake/android.toolchain.cmake?

I doubt that before. And I found no difference with or without it

**Comment by EvanLee2048** [comment]
> If you're seeing the same behavior with that flag, we'll need a test case.

How can I help?

**Comment by DanAlbert** [comment]
Tell us how to reproduce the issue.

**Comment by DanAlbert** [comment]
Though actually most of what's in your CMakeLists.txt isn't something we normally use, so it's possible one of those is causing the issue. I'll try that on Monday, but if you have a sample that you can upload then that really simplifies things.

**Comment by EvanLee2048** [comment]
do you have email?
I send the app to you
