### ISSUE TITLE
r17-beta2: ASurfaceTexture: missing setOnFrameAvailableListener function ?

### ISSUE THREAD

**Issue by tguillem** [android-ndk/ndk#682]
By reading the last r17 headers of the [ASurfaceTexture](https://developer.android.com/ndk/reference/group/surface-texture) interface, I found out there was no equivalent of the  [setOnFrameAvailableListener](https://developer.android.com/reference/android/graphics/SurfaceTexture.html#setOnFrameAvailableListener(android.graphics.SurfaceTexture.OnFrameAvailableListener,%20android.os.Handler)) method.

Is this intentional ? What NDK API are we supposed to use in order to get notified when a new image frame becomes available ? Or maybe it's not needed anymore. In that case, Is the image available immediately after a AMediaCodec_releaseOutputBuffer() call (for example) ?

**Comment by quink-black** [comment]
I'm interested on this issue too.

**Comment by DanAlbert** [comment]
Missed this one. You'll have to ask someone else. We don't know these APIs, we only ship them.

Try asking on our mailing list.
