### ISSUE TITLE
ship lld

### ISSUE THREAD

**Issue by DanAlbert** [android-ndk/ndk#683]
May not be ready for a real endorsement, but it sounds like this is probably at least good enough to be included in the NDK with a beta label on it. We need to remove the code in checkbuild.py that removes it from the package and do some initial testing.

**Comment by DanAlbert** [comment]
In r18 (master branch, currently).

We need to sort out the issue of `--fix-cortex-a8`. Namely: LLD doesn't support the errata workaround, but it isn't clear if that matters any more. Waiting on data.

**Comment by rprichard** [comment]
FWIW: http://b/73768157 is the internal issue for switching the platform to LLD. We recently changed Soong to pass `--no-rosegment` to lld to avoid an unwinder issue. https://android-review.googlesource.com/c/platform/build/soong/+/703112.

**Comment by rprichard** [comment]
The ld.lld.exe in r18 beta 1 can sometimes hang (http://b/111813862).
