### ISSUE TITLE
exit() just restarts Native Activity

### ISSUE THREAD

**Issue by twaik** [android-ndk/ndk#684]
#### exit() just restarts an activity

Ported application uses exit often and it is not possible to stop an activity using ANativeActivity_finish() without breaking program logic.

The solution I am trying is to register android_app_atexit function which does that:
```
static void android_app_atexit(void){
	if (pthread_equal(cached_android_app->thread, pthread_self())){
		ANativeActivity_finish(cached_android_app->activity);
		pthread_exit(0);
	}
}
```
But it does not work. For now I am looking for other ways to make exit work properly in Native Activity.

#### Environment Details

* NDK Version: r16b
* NDK API level: 22
* Device API level: 22

**Comment by DanAlbert** [comment]
Nothing we can do in the NDK. NativeActivity is implemented in the platform. File a bug at b.android.com.

**Comment by twaik** [comment]
Maybe there is a way to call NativeActivity_finish and break the current exit() call using atexit() in native_app_glue to prevent activity restarting. Or maybe native_app_glue can hook exit() function to prevent exit@libc.so calling.

**Comment by enh** [comment]
> The solution I am trying is to register android_app_atexit function which does that:

i'm not sure what you mean here. did you mean http://man7.org/linux/man-pages/man3/atexit.3.html instead?

**Comment by twaik** [comment]
Yes, that's it. It looks like nobody listens to zygote's forked process for exit code, so hooking exit to native_app_glue function that runs code like that code 
```
		ANativeActivity_finish(cached_android_app->activity);
		pthread_exit(0);
```
would be more correct than using atexit().

**Comment by alexcohn** [comment]
As a workaround, can't you override the ported application to call *your* version of **exit()**?

**Comment by enh** [comment]
> It looks like nobody listens to zygote's forked process for exit code, so hooking exit to native_app_glue function that runs code like ... would be more correct than using atexit().

this makes no sense. just use atexit.

**Comment by twaik** [comment]
> As a workaround, can't you override the ported application to call your version of exit()?

That's a good question... I found this solution much later than I closed the project. 

> this makes no sense. just use atexit.

The Activity just restarts in a loop.

**Comment by twaik** [comment]
For now I have runtime hooks to fix exit() and abort() behaviour inside the Activity and let activity close itself. It is useful for ported apps. I think it should be included to android_native_app_glue.
```
struct android_app* android_app_state;
#define jniMethodCheck(name) if (name##ID == NULL) { LOGE("Method %s can not be loaded", #name); return; }
static void activity_force_finish(void) {
	JavaVM* vm = android_app_state->activity->vm;
	JNIEnv* env; // = android_app_state->activity->env;
    jclass classActivity;
    jmethodID activityFinishID;

    (*vm)->AttachCurrentThread(vm, &env, 0);

    classActivity = (*env)->GetObjectClass(env, android_app_state->activity->clazz);
    activityFinishID = (*env)->GetMethodID(env, classActivity, "finish", "()V");
    jniMethodCheck(activityFinish);
    
    signal(SIGABRT, SIG_DFL);

    (*env)->CallVoidMethod(env, android_app_state->activity->clazz, activityFinishID);

	pthread_exit(NULL);
}

void exit(int __status) {
	if (android_app_state){
		ANativeActivity_finish(android_app_state->activity);
		activity_force_finish();
	} else _exit(0);
}

void abort(void){
	exit(3);
}
```

**Comment by alexcohn** [comment]
There seem to be two problems with this hook. I don't think you need to call `Activity.finish()` twice (once through **ANativeActivity_** and second time explicitly via JNI). And you may need a to call **DetachCurrentTread()** before **pthread_exit()**.

**Comment by twaik** [comment]
ANativeActivity_finish does not finish activity on my devices. It just lets my app to close itself after onDestroy signal.

**Comment by alexcohn** [comment]
> It just lets my app to close itself after onDestroy signal.

That's strange. You don't need **Activity.finish()** to shutdown the app, see e.g. *[Difference between finish() and System.exit(0)](https://stackoverflow.com/questions/18292016/difference-between-finish-and-system-exit0)*.

But still why call it through JNI again?

**Comment by twaik** [comment]
OK, got it. ANativeActivity_finish can be removed from the code. I think System.exit(0) is not suitable in this situations because NativeActivity can be not the only activity in the app and/or the app can contain Java activities, not the only activity. I used _exit(0) here because my libnativeactivity.so was developed to be used as library for elf executable too, not only in Native Activity. But it can be kept here for compatibility.
