### ISSUE TITLE
NDK doesn't bundle libc++ header with standalone toolchain

### ISSUE THREAD

**Issue by paul70078** [android-ndk/ndk#686]
#### Description

After creating the standalone toolchain, it isn't possible to compile applications using std with libc++ because the std header files for libc++ are missing (e.g. `<string>`)

Command I use to create standalone toolchain:

`SDK/ndk-bundle/build/tools/make_standalone_toolchain.py --arch arm --api 26 --install-dir standalone/ --stl=libc++`

#### Environment Details

* NDK Version: 16.1.4479499
* Build sytem: standalone toolchain
* Host OS: Linux, Ubuntu
* Compiler: Clang
* ABI:
* STL: libc++
* NDK API level: 26
* Device API level: -

**Comment by DanAlbert** [comment]
Yes it does. Our tests show as much.

Your test case is incomplete. How are you invoking clang?

**Comment by paul70078** [comment]
```
/mnt/d/Programme/Android/standalone/bin/arm-linux-androideabi-clang++  -O2 -g -Wall -Wno-unused-parameter -shared  -DADB_HOST=1 -DHAVE_FORKEXEC=1 -DHAVE_SYMLINKS -DHAVE_TERMIO_H -DHAVE_SYS_SOCKET_H -D_GNU_SOURCE -D_XOPEN_SOURCE -std=c++14 -stdlib=libc++ -v -Isystem/core/adb -Isystem/core/base/include -Isystem/core/libcutils/include -Isystem/core/libutils/include -Isystem/core/liblog/include -Isystem/core/fs_mgr/include -Isystem/core/libcrypto_utils/include -Isystem/extras/libfec/include -Iexternal/boringssl/src/include -Iexternal/libusb system/core/adb/adb.cpp -o build/system/core/adb/adb.o
```
I

**Comment by DanAlbert** [comment]
Remove `-stdlib=libc++`.

**Comment by paul70078** [comment]
works now, thanks. Had problems with creating the standalone toolchain without `--stl=libc++` before and forget to try compiling without `-stdlib=libc++`
