### ISSUE TITLE
c++11 thread_local objects don't get their destructors called on devices lower than android M

### ISSUE THREAD

**Issue by martinbonaciugome** [android-ndk/ndk#687]
#### Description

c++11 thread_local objects don't get their destructors called on devices lower than android M.

put this code in a thread and destroy it.

```
    struct aa
    {
      aa()
      {
        std::cout << "ctr " << std::uintptr_t(this);
      }
      ~aa()
      {
        std::cout << "dtr " << std::uintptr_t(this);
      }
    };
    static thread_local aa a{};
```

on api 23 the destructor gets called, on api 22 it does not.

#### Environment Details

* NDK Version: 16b and 17-beta2
* Build sytem: cmake
* Host OS: Windows
* Compiler: Clang
* ABI:
* STL: c++_static and c++_shared
* NDK API level:
* Device API level: 22

**Comment by rprichard** [comment]
It looks like the libcxxabi [`__cxa_thread_atexit` fallback](https://github.com/llvm-mirror/libcxxabi/blob/05a73941f3fb177c4a891d4ff2a4ed5785e3b80c/src/cxa_thread_atexit.cpp#L86) suffers from the same issue recorded internally as http://b/78022094:
 - It's using `pthread_key_create` to register a per-thread call to `run_dtors`.
 - `run_dtors` accesses the `__thread DtorList* dtors` variable allocated by emutls, which deallocates storage using another pthread key destructor.

If the fallback destructor is called after the emutls destructor, then it will use deallocated storage.

The workaround for the internal issue (delay the emutls deallocation a few rounds) probably fixes this issue, too.

Android M adds `__cxa_thread_atexit_impl`, which ensures that C++ destructors are called before pthread key destructors. [[Link]](https://android.googlesource.com/platform/bionic/+/e219cefc173bf93b8ff710431784e5de30ffab8f/libc/libc.map.txt#16)  [[Link]](https://android.googlesource.com/platform/bionic/+/e219cefc173bf93b8ff710431784e5de30ffab8f/libc/bionic/pthread_exit.cpp#75)

**Comment by martinbonaciugome** [comment]
Is this something a new ndk can fix, or are we totally hooped on older api's?

**Comment by enh** [comment]
(the details of the problems with the various thread local choices seem like they should be added to the docs, given the number of folks hitting these now...)

**Comment by rprichard** [comment]
Currently, I think this bug can be fixed in libgcc (and/or compiler-rt, if we upgrade to it), which is packaged with the NDK and linked into app shared libs. You'd need a new NDK, and then apps would work correctly on pre-M platforms.

**Comment by martinbonaciugome** [comment]
that's good news, thanks

**Comment by rprichard** [comment]
gnustl (which is deprecated) can fail on any Android version because, unlike libc++, its `__cxa_thread_atexit` fallback implementation doesn't defer to `__cxa_thread_atexit`  on newer platforms.

Like Android gnustl, mingw-w64 uses both emutls and libsupc++'s `__cxa_thread_atexit`, so it has the same bug. Apparently there was a mingw-w64 bug filed about this issue two weeks ago: https://sourceforge.net/p/mingw-w64/bugs/727/. Here's a test case that fails on all three configs (Android gnustl, Android libc++, mingw-w64): https://gist.github.com/rprichard/d0fad2161a3e2b7474b561d040ec5b40

**Comment by rprichard** [comment]
https://android-review.googlesource.com/c/toolchain/gcc/+/683601

**Comment by rprichard** [comment]
The NDK's libgcc.a prebuilts were updated in https://android-review.googlesource.com/c/platform/prebuilts/ndk/+/708782.
