### ISSUE TITLE
Missing library  #include <features.h>

### ISSUE THREAD

**Issue by gerardogc2378** [android-ndk/ndk#688]
Compiling urho sharp for Android I have this output:

```
/home/ggc/android_home/ndk-bundle/sources/cxx-stl/llvm-libc++/include/__config:169:22: fatal error: features.h: No such file or directory
 #include <features.h>
```

#### Environment Details

Not all of these will be relevant to every bug, but please provide as much
information as you can.

* NDK Version: Value from Pkg.Revision in ndk-bundle/source.properties. If not
  the latest version, check there before filing.
* Build sytem: ndk-build? cmake? standalone toolchain? custom? (if gradle, file
  a bug against studio as specified above)
* Host OS: ArchLinux
* Compiler: clang from ndk latest using sdkmanager to install
* NDK API level: ndk-bundle           | 16.1.4479499 | NDK                            | ndk-bundle

**Comment by gerardogc2378** [comment]
I have the same issue with this file https://github.com/urho3d/Urho3D/blob/master/CMake/Toolchains/Android.cmake (Urho3D Game Engine) maybe it needs some changes like you said, these are obsolete makefiles and need upgrade...

**Comment by rprichard** [comment]
As @weitjong said in https://github.com/urho3d/Urho3D/issues/2311#issuecomment-386780390, the Urho3D build system needs to be updated for NDK r16. I think this issue can be closed in favor of the Urho3D issue.
