### ISSUE TITLE
clang3.4 and clang3.5 toolchains are gone

### ISSUE THREAD

**Issue by gpakosz** [android-ndk/ndk#69]
Contrary to what http://developer.android.com/ndk/guides/application_mk.html says, it's no more possible to set `NDK_TOOLCHAIN_VERSION` to `clang3.4` or `clang3.5`.

Those toolchains are gone, leaving only the `clang3.6` toolchain which is selected when setting `NDK_TOOLCHAIN_VERSION=clang`:

```
android-ndk-r11c/build/core/toolchains
├── aarch64-linux-android-4.9
├── aarch64-linux-android-clang3.6
├── arm-linux-androideabi-4.9
├── arm-linux-androideabi-clang3.6
├── mips64el-linux-android-4.9
├── mips64el-linux-android-clang3.6
├── mipsel-linux-android-4.9
├── mipsel-linux-android-clang3.6
├── x86-4.9
├── x86-clang3.6
├── x86_64-4.9
└── x86_64-clang3.6
```

**Comment by DanAlbert** [comment]
The behavior is WAI (trust me, you do not want those compilers), but I'll leave the bug open until the docs are fixed.

**Comment by gpakosz** [comment]
Fine with me. I expected it to be labeled `docs`. Thanks for the triage.

**Comment by qchong** [comment]
Closing since https://developer.android.com/ndk/guides/application_mk.html does not mention clang 3.4 or 3.5 as a valid setting for `NDK_TOOLCHAIN_VERSION`.
