### ISSUE TITLE
x264 build error on x86 with NDK 17

### ISSUE THREAD

**Issue by aberaud** [android-ndk/ndk#690]
This error happens when building x264 on x86 with NDK 17:
```
In file included from encoder/me.c:28:
In file included from ./common/common.h:1016:
./common/x86/util.h:131:9: error: inline assembly requires more registers than available
        "movq       (%2), %%mm5 \n"
        ^
./common/x86/util.h:194:9: error: inline assembly requires more registers than available
        "movq       (%2), %%mm5 \n"
        ^
1 warning generated.
1 warning and 2 errors generated.
make[1]: *** [encoder/me.o] Error 1
```
It was already reported in 2014:
https://mailman.videolan.org/pipermail/x264-devel/2014-February/010374.html
According to this ML thread it's a clang bug.

**Comment by enh** [comment]
that's x86 code. you meant to say that you're targeting x86, right?

**Comment by aberaud** [comment]
yes

**Comment by enh** [comment]
(see also https://github.com/android-ndk/ndk/issues/693)

**Comment by DanAlbert** [comment]
Duping into #693 since that one has the response from Pirama.

**Comment by pirama-arumuga-nainar** [comment]
@aberaud Can you check if this issue is triggered by 'mstackrealign' or if there's something else to investigate?

As I mentioned in #693, https://bugs.llvm.org/show_bug.cgi?id=37542 was closed as expected behavior. 
 Unfortunately, I didn't find a source-level woarkaround for h264.
