### ISSUE TITLE
NDK17, "LLVM ERROR: Unexpected end of file" when using LTO

### ISSUE THREAD

**Issue by gershnik-smartsheet** [android-ndk/ndk#695]
#### Description

Attempting to build a shared library with LTO results in

LLVM ERROR: Unexpected end of file

when linking.
There is no more info (which file is the problem??) or anything else to do more troubleshooting.
Disabling LTO makes the problem go away. Previously everything worked fine on NDK 16. No changes were made to compile or link flags compared to NDK 16 build.

The relevant parts of link command line (formatted as Python list)

[/Work/android-ndk-r17/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang++',  '-O3', '-flto', '-ggdb',  '-gcc-toolchain', '/Work/android-ndk-r17/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64', '--sysroot=/Work/android-ndk-r17/platforms/android-23/arch-arm', '-Wl,--build-id', '-Wl,-z,noexecstack', '-Wl,--fix-cortex-a8', '-Wl,--exclude-libs,libunwind.a', '-Wl,--gc-sections', '-Wl,--warn-shared-textrel', '-Wl,--exclude-libs,libgcc.a', '-Wl,--exclude-libs,libatomic.a', '-shared', '-Wl,-shared,-Bsymbolic', '-Wl,--unresolved-symbols=report-all', '-Wl,-z,relro', '-Wl,-z,now']
 
#### Environment Details

Not all of these will be relevant to every bug, but please provide as much
information as you can.

* NDK Version: 17.0.4754217
* Build sytem: custom
* Host OS: Mac
* Compiler: clang
* ABI: armv7a
* STL: libc++
* NDK API level: 23

**Comment by gershnik-smartsheet** [comment]
Adding -v I get a more descriptive error:
/Work/android-ndk-r17/platforms/android-23/arch-arm/usr/lib/../lib/crtend_so.o
LLVM ERROR: Unexpected end of file

Sounds like something is wrong with crtend_so.o

**Comment by pirama-arumuga-nainar** [comment]
@gershnik-smartsheet The reference to crtend_so.o is most likely a red herring.  It's just the linker printing that it found the library from its search path.

The "Unexpected end of file" means one of the LTO-ed object files, which are actually LLVM IR files, is corrupt.

I take it that creating a reduced reproducer is difficult?  If so, you can try a few things to get more clarity:
1. Pass all of the LTO-ed object files through llvm-dis (should be in the same directory as clang) and see if any of them raises an error.
2. Bisect and find the single or minimal set of sources that need LTO enabled to reproduce.
3. Try the option -Wl,-plugin-opt=-save-temps and see if that shows anything interesting.

**Comment by gershnik-smartsheet** [comment]
@pirama-arumuga-nainar Thank you, this was very helpful!
Trying to bisect link command line turns out that the problem was static libs, not individual object files. The static libs appear to be corrupted. Looking into how static libs are generated, under NDK 16 we were doing
`llvm-ar`
`ranlib`
This worked just fine. Under NDK 17 it appears that this combination produces broken archives.
Trying to not do ranlib at all (just rely on llvm-ar 's' flag) doesn't work - linker complains that there is no index.
Switching to 
`ar`
`ranlib`
appears to work fine - the link succeeds. This unblocks us but still curious
a. Whether it is wrong to use llvm-ar with ranlib (note that there is no llvm-ranlib in NDK)?
b. What *is* the canonical way to create an archive with clang/LLVM on NDK?
c. Why doesn't llvm-ar with s flag alone (without ranlib) work?

Thank you!

**Comment by DanAlbert** [comment]
ndk-build and CMake both use plain old ar, not llvm-ar and not ranlib (the NDK includes GNU's are, which automatically performs ranlib actions).

**Comment by DanAlbert** [comment]
(nor is `--plugin` required for `ar` in the NDK, since we package the plugins in the right path for them to be loaded automatically)

**Comment by gershnik-smartsheet** [comment]
'-format-gnu' was the missing piece. Without it the linker doesn't understand the archive.
Thanks!
