### ISSUE TITLE
NDK17: ABIs [armeabi] are not supported for platform.

### ISSUE THREAD

**Issue by aa86799** [android-ndk/ndk#696]
before that, ndk version may be 16.xxx; 

when updated to 17.xxx, compile error: 
ABIs [armeabi] are not supported for platform. Supported ABIs are [armeabi-v7a, arm64-v8a, x86, x86_64].

i tried by some ways: make app/project;  clean project; reinstall ndk/lldb/cmke; reboot computer。。。。  but, it doesn't work

* NDK Version: 17.0.4xxx
* Build system: cmake(version 3.6.4111459); default toolchain
* Host OS: Mac
* Compiler: default Clang
* ABI: armeabi, armeabi-v7a
* STL: default
* NDK API level: 18
* Device API level: 20

**Comment by DanAlbert** [comment]
The error message says it all. armeabi is no longer supported.
