### ISSUE TITLE
Unable to generate protobuf c++ code with Android Studio

### ISSUE THREAD

**Issue by ldesegur** [android-ndk/ndk#698]
Android Studio's cmake doesn't seem to know about protobuf while if I use it from the command line I can compile the following CMakeList.txt:

include(FindProtobuf)
 find_package(Protobuf REQUIRED)
 include_directories(${PROTOBUF_INCLUDE_DIR})

Running the same script inside Android Studio, I get:

-- Could NOT find Protobuf (missing: Protobuf_LIBRARIES Protobuf_INCLUDE_DIR)

I tried setting env vars in Terminal:

export CMAKE_LIBRARY_PATH=/usr/local/Cellar/protobuf/3.5.1_1/lib
export CMAKE_INCLUDE_PATH=/usr/local/Cellar/protobuf/3.5.1_1/include

and launching AS from the command line in the same Term but no luck.

**Comment by DanAlbert** [comment]
If it works form the command line but not in Studio you'll need to file that bug against Studio, since our half of this is working: http://b.android.com
