### ISSUE TITLE
Compiler flags are overridden during CMake build 

### ISSUE THREAD

**Issue by dturner** [android-ndk/ndk#699]
When using Android Studio/CMake compiler flags can be specified in `app/build.gradle` file as follows: 

    externalNativeBuild {
        cmake {
            cppFlags "-std=c++14 -Ofast"
        }
    }

However, these flags are not respected when the build occurs. Instead different build flags are appended. For example, if you do a release build the compiler flags will *always* include `-std=c++11` and `-O2`. 

This can be verified by checking the file: `app/.externalNativeBuild/cmake/release/arm64-v8a/build.ninja` under the `FLAGS` variable. 

This behaviour can cause major performance problems which can be difficult to diagnose if you believe that you're already using the best compiler optimisations. 

Test case: 

- Create a new C++ project in Android Studio
- Add the following lines to app/build.gradle in the defaultConfig block: 

    externalNativeBuild {
        cmake {
            cppFlags "-std=c++14 -Ofast"
        }
    }
- Set the build variant to `release`
- Compile and run for either emulator or real device
- Open `app/.externalNativeBuild/cmake/release/<your-arch>/build.ninja`
- Look at the first row which starts with `FLAGS`

Expected outcome
- `FLAGS` contains only `-std=c++14` and `-Ofast`

Actual outcome
- `FLAGS` contains conflicting settings `-std=c++11 -std=c++14` and `-O2 -Ofast`

Note: These flags are hardcoded in `build/cmake/android.toolchain.cmake`

**Comment by hogliux** [comment]
I also ran into this problem and filed a bug [here](https://issuetracker.google.com/issues/63788909) and [here](https://gitlab.kitware.com/cmake/cmake/issues/17077).

A workaround is to use CMAKE_CXX_FLAGS_RELEASE instead. In gradle this can be set via externalNativeBuild.cmake.arguments. So

```
externalNativeBuild {
  cmake {
    arguments "-DCMAKE_CXX_FLAGS_RELEASE=-Ofast"
  }
}
```

But having NDK silently ignore optimisation flags in `externalNativeBuild.cmake.cppFlags` is definitely confusing. There must be hundreds of apps being built with _only_ `-O2` when the developers intended to build with `-O3` or `-Ofast`.

**Comment by dturner** [comment]
Thanks Fabian. You can also use `CMAKE_CXX_FLAGS_DEBUG` either in `app/build.gradle`:

    externalNativeBuild {
        cmake {
            arguments "-DCMAKE_CXX_FLAGS_DEBUG=-Ofast"
        }
    }

or in `CMakeLists.txt`:

    set(CMAKE_CXX_FLAGS_DEBUG "${CMAKE_CXX_FLAGS_DEBUG} -Ofast")

Just to be clear this is a workaround rather than a fix because `-O0` still appears in the list of flags, it's just that `-Ofast` appears *after*, so takes precedence.

**Comment by DanAlbert** [comment]
Actually, after some investigation it looks like this is the correct behavior for CMake (i.e. this is how it behaves for non-Android as well).

```cmake
# CMakeLists.txt
cmake_minimum_required(VERSION 3.6)
add_executable(foo foo.cpp)
```

```cpp
// foo.cpp
int main() { return 0; }
```

```bash
$ mkdir build && cd build
$ cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS=-Ofast -G Ninja ..
$ ninja -v
[1/2] /usr/bin/c++    -Ofast -O3 -DNDEBUG -MD -MT CMakeFiles/foo.dir/foo.cpp.o -MF CMakeFiles/foo.dir/foo.cpp.o.d -o CMakeFiles/foo.dir/foo.cpp.o -c ../foo.cpp
[2/2] : && /usr/bin/c++  -Ofast -O3 -DNDEBUG   CMakeFiles/foo.dir/foo.cpp.o  -o foo   && :
```

CMake's default `CMAKE_CXX_RELEASE_FLAGS` overrides the user's `CMAKE_CXX_FLAGS`. It looks like the correct way to set optimization flags in cmake is to do it in the build-type specific variables.

As for the `-std` flags, like you said, they come in the correct order so the user's choice is obeyed. Just checked really quick and the more modern CMake approach of using:

```cmake
target_compile_features(foo PRIVATE cxx_range_for)
```

or

```cmake
set_property(TARGET foo PROPERTY CXX_STANDARD 14)
```

instead of adding `-std` to `CMAKE_CXX_FLAGS` also overrides our toolchain file.

**Comment by dturner** [comment]
@DanAlbert Thanks very much for looking into this. I've done a bit more research and put together some recommended approaches below. 

**Setting the optimization level**
*Modern approach:* Use `target_compile_options` to specify the target. This must be placed *after* the target is defined. 

    target_compile_options(foo PUBLIC "$<$<CONFIG:RELEASE>:-Ofast>")

You can also use `add_compile_options` to specify for all targets in `CMakeLists.txt`. This must be placed *before* the targets are defined. 

    add_compile_options("$<$<CONFIG:RELEASE>:-Ofast>")

A final, less preferred option is to use `CMAKE_CXX_FLAGS_<BUILDCONFIG>`.  

    set(CMAKE_CXX_FLAGS_RELEASE "${CMAKE_CXX_FLAGS_RELEASE} -Ofast")

**Setting the C++ standard**
*Simplest approach:* Use `CMAKE_CXX_STANDARD`. 

    set(CMAKE_CXX_STANDARD 14)

You can specify the standard for an individual target using `set_property`

     set_property(TARGET foo PROPERTY CXX_STANDARD 14) 

More information here: https://stackoverflow.com/questions/15100351/changing-cmake-cxx-flags-in-project

**Comment by dturner** [comment]
@ggfan has just pointed out to me that using `set(CMAKE_CXX_STANDARD 14)` results in `-std=gnu++14` being added. 

In some cases this may not be desirable. The solution is to use: 

    target_compile_options(foo PRIVATE -std=c++14)

Additionally, [here's a good explanation](https://stackoverflow.com/questions/26037954/cmake-target-link-libraries-interface-dependencies) of the difference between `PUBLIC` and `PRIVATE` scope specifiers.
