### ISSUE TITLE
Clang + GNU STL in r17 seems to have stricter warnings

### ISSUE THREAD

**Issue by rcdailey** [android-ndk/ndk#703]
I literally changed nothing about my code or build.gradle/CMake configuration between r16 and r17 and I'm seeing a boat load more warnings. The warnings are correct, but before my NDK upgrade I was not seeing these warnings. Things like virtual destructors not being present on virtual classes, `>= 0` warnings on unsigned types, and things like this:

> Core/ThirdParty/cereal/cereal/include\cereal/external/rapidjson/document.h:597:9: error: 'GenericValue' has a non-throwing exception specification but can still throw [-Werror,-Wexceptions]
>          CEREAL_RAPIDJSON_ASSERT(type <= kNumberType);

Could someone please explain why the warnings are appearing all of a sudden? I'm using clang and GNU STL. The only thing I can think of that happened is maybe a clang upgrade that has more warnings enabled by default.

**Comment by rcdailey** [comment]
Yep looks like clang went from v5.0.3 to v6.0.2. Maybe this is the reason.

**Comment by stephenhines** [comment]
This is WAI. GNU STL is deprecated in r17, and will be removed soon. The release notes (https://developer.android.com/ndk/downloads/revision_history) have been suggesting migration to libc++ for a few releases now, and r18 will remove GNU STL as an option for the NDK.

**Comment by enh** [comment]
(and, yes, newer versions of clang pretty much always have more diagnostics, or better implementations of existing diagnostics.)

**Comment by rcdailey** [comment]
Thanks @enh, that addresses my specific question. I was already aware of the deprecation but for the purposes of my question and r17 and below it's not relevant.
