### ISSUE TITLE
could not find aarch64 strip

### ISSUE THREAD

**Issue by fredroo** [android-ndk/ndk#707]
Look this bug reported in stackoverflow

https://stackoverflow.com/questions/42739916/aarch64-linux-android-strip-file-missing

> Error:org.gradle.process.internal.ExecException: A problem occurred starting process 'command 'C:\Users\...\AppData\Local\Android\sdk\ndk-bundle\toolchains\aarch64-linux-android-4.9\prebuilt\windows-x86_64\bin\aarch64-linux-android-strip''
>
>
> Error:net.rubygrapefruit.platform.NativeException: Could not start 'C:\Users\...\AppData\Local\Android\sdk\ndk-bundle\toolchains\aarch64-linux-android-4.9\prebuilt\windows-x86_64\bin\aarch64-linux-android-strip'
>
>
> Error:java.io.IOException: Cannot run program "C:\Users\...\AppData\Local\Android\sdk\ndk-bundle\toolchains\aarch64-linux-android-4.9\prebuilt\windows-x86_64\bin\aarch64-linux-android-strip" (in directory "E:\projectNmame\app"): CreateProcess error=2, The system cannot find the file specified

**Comment by DanAlbert** [comment]
We haven't seen this in any of our testing, so we can't do anything without a repro case.

**Comment by fredroo** [comment]
@DanAlbert I use project Ionic with Cordova

https://ionicframework.com/

this project use Android studio to build App

I fix this problem with uninstalling NDK from ANDROID follow this answer:

https://stackoverflow.com/questions/42739916/aarch64-linux-android-strip-file-missing#answer-50316120

to reproduce the error:

install node:
https://nodejs.org/en/

run command in terminal:
`npm install -g npm@latest ionic@latest cordova@latest`

after run command: 
`ionic start myApp blank`

enter in app folder and run command:
`ionic cordova run android`

but you need Android studio with SDK Platforms and SDK Tools installed

**Comment by DanAlbert** [comment]
Works for me. It fails later on for unrelated reasons ("rm failed for -f, No such file or directory"), but it builds fine using NDK r17.

**Comment by fredroo** [comment]
@DanAlbert what OS window, linux or mac?

**Comment by DanAlbert** [comment]
Linux

**Comment by rprichard** [comment]
What version of Android Studio are you using?

**Comment by DanAlbert** [comment]
I used Studio 3.1. All the build.gradle files in the generated project directory used 3.0 (or earlier).

**Comment by fredroo** [comment]
I found the error, is with cordova-android 7.1.0
https://github.com/apache/cordova-android/tree/rel/7.1.0
is not compatible with this version, I returned to version 6.3.0

to replicate error create the project again with commands above and run this:

`ionic cordova platform rm android && ionic cordova add android@7.1.0 && ionic cordova run android`

**Comment by fredroo** [comment]
I opened issue in apache cordova
https://issues.apache.org/jira/browse/CB-14115
