### ISSUE TITLE
NDK r11c contains 2 duplicate folders located at toolchains\llvm\prebuilt\windows-x86_64\lib64\clang\

### ISSUE THREAD

**Issue by dosvidos** [android-ndk/ndk#71]
The folder `android-ndk-r11c\toolchains\llvm\prebuilt\windows-x86_64\lib64\clang\` contains two identical sub-folders `3.8` and `3.8.243773`
>$ du -ls *
>6764    3.8
>6764    3.8.243773

**Comment by DanAlbert** [comment]
Yep. In a POSIX environment the 3.8 is a symlink to the other, but we can't reasonably do symlinks on Windows (extracting the NDK would require administrator privileges). Nothing that can be done here.

**Comment by dosvidos** [comment]
I suggest you to use `mklink /J` command, which creates NTFS directory junction - it's works the same as symlink in this case and doesn't require administrator's permissions.

**Comment by dosvidos** [comment]
Hi, Dan.
I suggest you to use the mklink /J command which creates directory junction
and doesn't require administrators permissions. You only need NTFS
directory junction here instead of a full symbolic link

чт, 7 апр. 2016 г., 20:06 Dan Albert <notifications@github.com>:

**Comment by DanAlbert** [comment]
A directory junction is a hard link; it can't be added to a zip file.

**Comment by stephenhines** [comment]
It's possible that we might eventually fix this, but it would require changing the LLVM configuration (and version info). I am not opposed to doing that, but it goes beyond being just an NDK bug. This works just fine on non-Windows, and keeps things easier to manage, but I can see where the duplicate dirs are annoying on Windows.
