### ISSUE TITLE
Sideband API access

### ISSUE THREAD

**Issue by kilaparthy** [android-ndk/ndk#710]
**Note**: Bugs against Android Studio or Gradle should be filed at
http://b.android.com, not here.

Before filing a bug, check that you are using the latest version of the NDK. The
latest stable version and the preview release of the next stable version are
listed on our wiki: https://github.com/android-ndk/ndk/wiki#downloads.

Make sure your issue isn't on the list of common problems before filing a bug:
https://android.googlesource.com/platform/ndk/+/master/docs/user/common_problems.md

Delete everything above this line before submitting.

--------------------------------------------------------------------------------

#### Description
This is regarding the Android TV application. Here the "TV input service" passes the video surface to driver and request to render it on the video surface passed. For this the below API was used

**native_window_set_sideband_stream**() was used.

This API now not allowed to access as it become an non-NDK API post Android N release.
Can you suggest an alternate to this API or any other approach to achieve this.

**Comment by DanAlbert** [comment]
We don't own this API, we just ship it. Try the NDK mailing list. android-ndk@googlegroups.com.
