### ISSUE TITLE
No way to control input type of soft keyboard from Native app

### ISSUE THREAD

**Issue by jonlgreen** [android-ndk/ndk#712]
I am displaying a soft native keyboard in my NDK app, but I want to be able to control the input type of the keyboard, eg for entering a phone number instead of general text. There is an _onCreateInputConnection_ function of the View class which gives control of the input type through attributes. However, the _NativeActivity_ creates its own custom view which is held privately and inaccessible, so I cannot override it.

Note that I am using my own GL rendered UI, so I don't have a TextInput object on which to set the input type.

**Comment by DanAlbert** [comment]
You'll need to file a platform bug. http://b.android.com

**Comment by alexcohn** [comment]
https://groups.google.com/d/msg/android-ndk/eFFj20gPZnI/tCFPElGtAQAJ
