### ISSUE TITLE
Undefined reference to glob and globfree in libc.so

### ISSUE THREAD

**Issue by yagnasrinath** [android-ndk/ndk#718]
#### Description
Undefined reference to glob and globfree in libc.so. They are indeed defined in libc.a
`g_initialize.c:(.text+0x41d8): undefined reference to 'glob'`
`g_initialize.c:(.text+0x4228): undefined reference to 'globfree'`

`$ aarch64-linux-android-nm -a ./libc.so | grep globfree`
`$ aarch64-linux-android-nm -a ./libc.a | grep globfree`
`  0000000000000000 T globfree`
`  0000000000000000 t .text.globfree`

#### Environment Details

* NDK Version: r17
* Build sytem: standalone toolchain - (make_standalone_toolchain.py --arch arm64 --api 28 --stl libc++)
* Host OS: Linux(Ubuntu 1604.4)
* Compiler: Clang
* ABI: ARM64
* STL: libc++
* NDK API level: 28
* Device API level: NA

**Comment by DanAlbert** [comment]
Another dup of https://github.com/android-ndk/ndk/issues/702.

**Comment by enh** [comment]
that is: "fixed in r17b, coming soon".

**Comment by yagnasrinath** [comment]
Can I please get access to r17b to get myself unblocked?

**Comment by yagnasrinath** [comment]
Thank you.

**Comment by tangxinfa** [comment]
Don't forget to set API Level to 28 for use glob.
