### ISSUE TITLE
Unable to resolve dependency for ':app@externalNativeBuild/compileClasspath'

### ISSUE THREAD

**Issue by sam4444** [android-ndk/ndk#719]
I have wrote code in CPP and linked with gradle using cmake now there other sub module like bottomsheet and few more and now in sync gradle i get following error 

Unable to resolve dependency for ':app@externalNativeBuild/compileClasspath': Could not resolve project :bottomsheet

Here native code not used in other module how can i resolve this one ?

**Comment by DanAlbert** [comment]
Wrong bug tracker. Gradle is not a part of the NDK. Try https://b.android.com.
