### ISSUE TITLE
llvm-config is not provided

### ISSUE THREAD

**Issue by yagnasrinath** [android-ndk/ndk#720]
#### Description
Unable to find the llvm-config tool necessary to build other llvm related modules. I am trying to build flang(fortran compiler for llvm) which has llvm-config as one of it's needed packages. I cannot build gfortran as well because gcc toolchain is being deprecated. Can we expect this tool to be added to the toolchains shipped with NDK?
#### Environment Details
* NDK Version: ndk-canary(18.0.4829896)
* Build sytem: standalone toolchain
* Host OS: Linux(ubuntu 1604)
* Compiler: Clang
* ABI: NA
* STL: libc++
* NDK API level: 28
* Device API level: 28

**Comment by DanAlbert** [comment]
No, the NDK is for building Android binaries, not host binaries.

It's probably easiest for you to just go through the normal method of building clang and its various tools, but if it's a huge hassle to get Android support into that then you could use our toolchain repo as a base and try adding flang to it. @stephenhines: I can't find any docs for how to build the new toolchain repo. Are there any?

**Comment by yagnasrinath** [comment]
@DanAlbert Thanks, that makes sense. Another question I have is that I cannot find any arm64/arm32 emulator images for oreo and android p. They may not be needed for java development, but they do matter a lot to validate your app when it has heavy native code. Am I missing something here, is there any documentation about them? I am not sure if this is the right place to as the question? Could you please point me to right place where this question belongs to?

**Comment by pirama-arumuga-nainar** [comment]
We'll package llvm-config  (https://android-review.googlesource.com/c/toolchain/llvm_android/+/675811) starting with the next Clang update to AOSP (but this may not be in the NDK r18).  But as Dan pointed out, this is not a supported use case - we won't address issues with flang, but may look issues with using llvm-config (without any promise on turnaround times).

@DanAlbert The documentation for building the toolchain is pending for a while.  We'll try to cobble together a quick README.

**Comment by DanAlbert** [comment]
> I am not sure if this is the right place to as the question? Could you please point me to right place where this question belongs to?

http://b.android.com

**Comment by yagnasrinath** [comment]
@pirama-arumuga-nainar Is the documentation available now to build the toolchain?

**Comment by pirama-arumuga-nainar** [comment]
@yagnasrinath https://android.googlesource.com/toolchain/llvm_android/+/master/README.md

**Comment by pirama-arumuga-nainar** [comment]
Use --no-build-windows if you're building on linux to reduce the build time: https://android-review.googlesource.com/c/toolchain/llvm_android/+/712515

**Comment by yagnasrinath** [comment]
Thanks @pirama-arumuga-nainar Will give it a try!
