### ISSUE TITLE
Android-ndk dlopen("libmedia.so") not access android 7.1

### ISSUE THREAD

**Issue by viralchauhan** [android-ndk/ndk#722]
For Help
Dear All Android Developer,
I have develop one android application call recording.This app work fine up to 6.0. i record call using mic and some audio settings changes using native lib like dlopen("libmedia.so") and use libmedia function and modified audio but in android 7.1 & 7.2 android os some changes is i am not use dlopen("libmedia.so") it retruns "NULL".i know why this retrun NULL it's about private lib i can not access using ndk any private lib than my Question is how to access private lib in android 7.1 &7.2 please help for step by step soluation.. 
give me solution for step by step with development step.

**Comment by DanAlbert** [comment]
As you said, it is a private API. You cannot access private APIs.

**Comment by viralchauhan** [comment]
but how to resolve this problem ?

**Comment by DanAlbert** [comment]
What problem?

**Comment by viralchauhan** [comment]
how to resolved and how to access ?

**Comment by viralchauhan** [comment]
problem is my call recording app  incoming voice not record  using mic so i can use native lib ndk dlopen("libmedia.so") access and modify audio settings .only record my voce not record opinetate voice .

**Comment by viralchauhan** [comment]
I share sample my code 
retrun NULL in Android 7.1/7.2  **handleLibMedia = dlopen("libmedia.so", RTLD_NOW | RTLD_GLOBAL);** 
    if (handleLibMedia != NULL) {
        func = dlsym(handleLibMedia, "_ZN7android11AudioSystem13setParametersEiRKNS_7String8E");
        if (func != NULL) {
//            result = func(env, thiz);
            result = 0;
        }
        audioSetParameters = (lasp) func;
    } else {
        result = -1;
    }

**Comment by viralchauhan** [comment]
I share sample my code
retrun NULL in Android 7.1/7.2 *handleLibMedia = dlopen("libmedia.so",
RTLD_NOW | RTLD_GLOBAL);*
if (handleLibMedia != NULL) {
func = dlsym(handleLibMedia,
"_ZN7android11AudioSystem13setParametersEiRKNS_7String8E");
if (func != NULL) {
// result = func(env, thiz);
result = 0;
}
audioSetParameters = (lasp) func;
} else {
result = -1;
}

**Comment by viralchauhan** [comment]
I share sample my code
retrun NULL in Android 7.1/7.2 *handleLibMedia = dlopen("libmedia.so",
RTLD_NOW | RTLD_GLOBAL);*
if (handleLibMedia != NULL) {
func = dlsym(handleLibMedia,
"_ZN7android11AudioSystem13setParametersEiRKNS_7String8E");
if (func != NULL) {
// result = func(env, thiz);
result = 0;
}
audioSetParameters = (lasp) func;
} else {
result = -1;
}

**Comment by viralchauhan** [comment]
i think you have not solution .
