### ISSUE TITLE
Android-ndk dlopen("libmedia.so") not access android 7.0,7.1 & 7.2 

### ISSUE THREAD

**Issue by viralchauhan** [android-ndk/ndk#723]
For Help
Dear All Android Developer,
I have develop one android application call recording.This app work fine up to 6.0. i record call using mic and some audio settings changes using native lib like dlopen("libmedia.so") and use libmedia function and modified audio but in android 7.0,7.1 & 7.2 android os some changes is i am not use dlopen("libmedia.so") it retruns "NULL".i know why this retrun NULL it's about private lib i can not access using ndk any private lib than my Question is how to access private lib in android 7.0,7.1 &7.2 please help for step by step soluation..
give me solution for step by step with development step.

**Comment by enh** [comment]
See https://android-developers.googleblog.com/2016/06/improving-stability-with-private-cc.html --- you'll need to find public API.

You can file bugs requesting more public API at using the links on https://source.android.com/setup/contribute/report-bugs for the appropriate component (in this case, GfxMedia).
