### ISSUE TITLE
Error: app:transformNativeLibsWithStripDebugSymbolForDebug caused by the removal of mips64 in NDK r17b

### ISSUE THREAD

**Issue by ntanen3381** [android-ndk/ndk#724]
NDK version r17b removes support for mips and mips64 which if used will throw an error ":app:transformNativeLibsWithStripDebugSymbolForDebug'". Instead of installing an older version of the NDK that does not disclude mips64 is there a better way of removing the need for mips and mips64 from my app? I am using the ionic cordova framework to code and build the app for android and ios so there must be a good way to use the NDK r17b version without getting the error and needing mips/mips64.

--------------------------------------------------------------------------------

#### Description

Bug description goes here. Include a test case. It's unlikely that anything can
be done without a test case.

Bug reports with better test cases will be resolved sooner than those with bad
test cases. A good test case:

 * Is as small as possible while still exposing the bug.
 * Does not require Android Studio or Gradle (if your bug cannot be reproduced
   without either of those, it's a bug in Studio or Gradle, and should be
   reported to Android Studio).
 * Is complete. Snippets that would not compile even in the absence of the bug
   you are reporting slow down the process.

Here's an example of a good test case:
https://github.com/DanAlbert/dynamic-cast-repro

#### Environment Details

Not all of these will be relevant to every bug, but please provide as much
information as you can.

* NDK Version: Value from Pkg.Revision in ndk-bundle/source.properties. If not
  the latest version, check there before filing.
* Build sytem: ndk-build? cmake? standalone toolchain? custom? (if gradle, file
  a bug against studio as specified above)
* Host OS: Windows, Mac, or Linux? Which Linux?
* Compiler: If GCC, check Clang before filing. GCC is no longer supported.
* ABI:
* STL:
* NDK API level:
* Device API level:

**Comment by DanAlbert** [comment]
Dup of https://github.com/android-ndk/ndk/issues/700. You may need to raise a bug with Cordova if they're tools are the ones choosing your gradle plugin version.

**Comment by alexcohn** [comment]
Here is yet another fresh complaint: https://stackoverflow.com/questions/50928778/how-to-disable-ndk-for-a-certain-project-in-android-studio

Let me repeat my plea: until Android Studio learns to handle automatic upgrade of the gradle plugin, or to match it to compatible NDK version, adding dummies for MIPS strip binaries would be a major relief for many developers.
