### ISSUE TITLE
unable to override CMake's default C++ standard version

### ISSUE THREAD

**Issue by genbattle** [android-ndk/ndk#726]
#### Description

The company I'm working at has a fairly _mature_ codebase that is limited to C++03 due to older platforms we have to support (Windows CE). This codebase has thus developed some weird quirks which compile fine under C++03, but will not compile with a C++11-enabled compiler/stdlib. We'd like to avoid having to do the work necessary to make the codebase C++11-compatible until we can get rid of our older platforms. To this end we usually have something along the following lines in our CMakeLists.txt:

```
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++03")
```

The problem is that the current version of the NDK (17.1.4828580) inserts a `-std=c++11` flag in CXX_FLAGS if `libc++` is selected (android.toolchain.cmake:526-532):

```
elseif(ANDROID_STL MATCHES "^c\\+\\+_")
  set(ANDROID_STL_PREFIX llvm-libc++)
  if(ANDROID_ABI MATCHES "^armeabi")
    list(APPEND ANDROID_LINKER_FLAGS -Wl,--exclude-libs,libunwind.a)
  endif()
  list(APPEND ANDROID_COMPILER_FLAGS_CXX
    -std=c++11)
```

Our options for preventing the adding of this flag are:
1. Copy the android.toolchain.cmake file, modify it and override it with the `-DCMAKE_TOOLCHAIN_FILE` argument in our gradle file. We then wouldn't pick up any future changes to the toolchain file in the NDK.
2. Somehow remove the flag from the flag strings in our target CMakeLists.txt; although I've tried I haven't been able to get it working.
3. Use `gnustl` or `stlport` for our stdlib instead of `libc++`. This is problematic because both former options are deprecated and will be removed in the near future.

We will implement options 1 or 3 for now, but I would really appreciate a fix for this in the NDK. I don't understand why the `-std` flag is even being set by the toolchain file (and only for libc++), and judging from other issues like #403 I'm not the only one for whom this sort of practice causes issues.

#### Environment Details

* NDK Version: Pkg.Revision = 17.1.4828580
* Build sytem: gradle + cmake
* Host OS: Linux (Ubuntu 14.04 with clang 5.0 installed), issue doesn't occur on Windows by default (I'm guessing Windows may have a different default stdlib?)
* Compiler: clang
* NDK API level: 23

**Comment by genbattle** [comment]
A colleague just reminded me that libc++ doesn't support C++03, so I guess that's the reason for this limitation in the first place? It seems I'll have to go with gnustl in the meantime until we make our codebase C++11-compatible.

**Comment by rprichard** [comment]
It should still be possible to override the C++11 default with a newer standard version, though, right?

**Comment by DanAlbert** [comment]
Yep.

**Comment by DanAlbert** [comment]
AFAICT this has always been a red herring. Yes, `-std=c++11` gets set, but the user's flag overrides:

For a trivial test case:

```cmake
cmake_minimum_required(VERSION 3.6.0)

set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++17")

add_executable(foo foo.cpp)
```

`ninja -v` shows:

> [2/2] : && /usr/local/google/home/danalbert/src/ndk/out/linux/android-ndk-r19-canary/toolchain/bin/clang++  --target=armv7-none-linux-androideabi16 --gcc-toolchain=/usr/local/google/home/danalbert/src/ndk/out/linux/android-ndk-r19-canary/toolchain  --sysroot /usr/local/google/home/danalbert/src/ndk/out/linux/android-ndk-r19-canary/toolchain/sysroot -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -mfpu=vfpv3-d16 -mthumb -Wa,--noexecstack -Wformat -Werror=format-security -stdlib=libc++ **-std=c++11  -std=c++17**  -Wl,--exclude-libs,libgcc.a -Wl,--exclude-libs,libatomic.a -static-libstdc++ -Wl,--build-id -Wl,--warn-shared-textrel -Wl,--fatal-warnings -Wl,--exclude-libs,libunwind.a -Wl,--no-undefined -Qunused-arguments -Wl,-z,noexecstack -Wl,-z,relro -Wl,-z,now -Wl,--gc-sections CMakeFiles/foo.dir/foo.cpp.o  -o foo  -latomic -lm && :

I checked the git history and this should be the behavior going all the way back to our original toolchain implementation. If my trivial test case missed something, could you upload a sample that shows the problem?
