### ISSUE TITLE
CPP headers with MacOS 10.14

### ISSUE THREAD

**Issue by qlemaire22** [android-ndk/ndk#728]
Hello, 

I have been trying to compile this app https://github.com/andyli/AICamera/tree/submodule on MacOS 10.14 (it is a beta and I don't know if my problem is related to that or not) and Android NDK 17 but I cannot find any basic CPP header (fatal error: 'limits' file not found) during the compilation (algorithm, limits, memory, climits,..).

The command line tool is well installed, I have tried multiples values for DANDROID_STL but I can't find anything that makes it work. When I use native clang++ I can compile CPP libraries but not when I am using clang++ of the Android sdk (Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/bin/clang++).

I have also tried on a Linux computer and it works.

Thank you for your help!

**Comment by DanAlbert** [comment]
Not really sure what OS X could have done to make our CMake integration stop working... Have you tested this on a non-beta version of OS X?

**Comment by qlemaire22** [comment]
No I don't have a non-beta version of OS X available ... I was wondering that since it worked on linux and I have seem this issue on other things with the beta. I managed to solve it for the other things but still not for that.

**Comment by alexcohn** [comment]
Isn't this in `build_host_protoc` ? Maybe you should simply use the prebuilt jniLibs on MacOS.

**Comment by DanAlbert** [comment]
Closing for lack of information.
