### ISSUE TITLE
Incosistent escaping of # in CFLAGS and LDFLAGS

### ISSUE THREAD

**Issue by styurin** [android-ndk/ndk#730]
## Description

There was a change in how `#` is escaped as part of https://github.com/android-ndk/ndk/issues/161. The commit in that issue changed the escaping for CFLAGS and some other flags, but not for LDFLAGS. As a result, escaping for variables became inconsistent.

We use Android NDK as part of Buck build procedure to build Android applications. Before that change (NDK 15 and older) we handled escaping of `#` by adding multiple backslashes. We use it for both `CFLAGS` and `LDFLAGS`.

The issue is not blocking us, but it would be great to have consistency. Right now users have to use different escaping for different flags which is very confusing.

## Steps to reproduce

I'll use https://github.com/styurin/dynamic-cast-repro to show how to reproduce the issue. I use `-rpath` option for illustration only.

## Working escaping of LDFLAGS (and all other flags) with NDK 15 and older

In branch `working-escaping-ldflags`:

```
$ grep rpath jni/Android.mk
LOCAL_LDFLAGS := -rpath /tmp/\\\\\\\\\\\\\\\#rpath

$ <path-to-ndk>/android-ndk-r15/ndk-build -n | grep rpath
... -rpath /tmp/\#rpath -Wl,--build-id ...
```

This escaping used to work for all arguments, but stopped working for CFLAGS after the fix in NDK 16. It's still working for other arguments in NDK 16+.

## Working escaping of CFLAGS with NDK 16 and newer

In branch `working-double-escaping-cflags`:

```
$ grep rpath jni/Android.mk
LOCAL_CFLAGS := -rpath "/tmp/\#rpath"

$ <path-to-ndk>/android-ndk-r16b/ndk-build -n | grep rpath
... -rpath "/tmp/#rpath" -Wl,--build-id ...
```

This only works with CFLAGS and some other arguments in NDK 16+.

## Broken escaping of LDFLAGS with double quotes in NDK 16+

```
$ grep rpath jni/Android.mk
LOCAL_LDFLAGS := -rpath "/tmp/\#rpath"

$ <path-to-ndk>/android-ndk-r16b/ndk-build -n | grep rpath
... -rpath "/tmp/ -Wl,--build-id ...
```

This is clearly broken and looks identical to the issue reported in https://github.com/android-ndk/ndk/issues/161.

#### Environment Details

Not all of these will be relevant to every bug, but please provide as much
information as you can.

* NDK Version: 16.1.4479499 and 15.0.4075724
* Build sytem: ndk-build
* Host OS: Mac
* Compiler: Clang

**Comment by DanAlbert** [comment]
Thanks for the detailed report! https://android-review.googlesource.com/c/platform/ndk/+/711246 fixes ldflags and all the other flag types.
