### ISSUE TITLE
android_support headers, fgetpos/fsetpos and CMake

### ISSUE THREAD

**Issue by rprichard** [android-ndk/ndk#734]
Test case: 32-bit Android and libc++:
```
#define _FILE_OFFSET_BITS 64
#include <stdio.h>
namespace dummy {
  using ::fgetpos;
  using ::fsetpos;
}
```

r18 ndk-build:
 - compiles with android-19 [declared in android_support]
 - doesn't compile with android-21 [no declaration]
 - compiles with android-24 [functions come from Bionic/libc.so]

r18 CMake:
 - compiles with android-19 [declared in android_support]
 - compiles with android-21 [declared in android_support]
 - compiles with android-24 [functions come from Bionic/libc.so]

There are two inconsistencies that look like possible oversights to me:
 - android_support declares {fgetpos,fsetpos} when libc.so doesn't have them, previously for the sake of cstdio, but we modified cstdio to only declare std::{fgetpos,fsetpos} when libc.so has them.
 - CMake uses android_support's headers even for API >= 21, while ndk-build only uses them for API < 21.

I'm guessing we don't want our CMake toolchain to include android/support for API >= 21.

Because we're not using android_support for 21..23, maybe it shouldn't declare the 64-bit fgetpos/fsetpos, which is needed until 24.

I noticed this issue while trying to get Qt building with r18. It is more convenient if Qt's build system unconditionally adds android_support to the include path, and I wondered if that broke anything when targeting API >= 21. I think it doesn't.

**Comment by DanAlbert** [comment]
Fix CMake using libandroid_support headers post-21: https://android-review.googlesource.com/c/platform/ndk/+/715279

Fix the incorrectly declared fgetpos/fsetpos in libandroid_support: https://android-review.googlesource.com/c/platform/ndk/+/715280
