### ISSUE TITLE
org.gradle.internal.UncheckedException: Build command failed or Building CXX object CMakeFiles/native-lib.dir/src/main/cpp/native-lib.cpp.o FAILED

### ISSUE THREAD

**Issue by Ni30patel** [android-ndk/ndk#736]
I am tried to build C++ file using android-ndk but I got error
`Caused by: org.gradle.internal.UncheckedException: Build command failed.
Error while executing process D:\Android_Studio\sdk\cmake\3.6.4111459\bin\cmake.exe with arguments {--build D:\Android_Studio\Workspace\NDKTestSample\app\.externalNativeBuild\cmake\debug\x86 --target native-lib}
[1/2] Building CXX object CMakeFiles/native-lib.dir/src/main/cpp/native-lib.cpp.o
FAILED: D:\Android_Studio\sdk\ndk-bundle\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe  --target=i686-none-linux-android --gcc-toolchain=D:/Android_Studio/sdk/ndk-bundle/toolchains/x86-4.9/prebuilt/windows-x86_64 --sysroot=D:/Android_Studio/sdk/ndk-bundle/sysroot  -Dnative_lib_EXPORTS -isystem D:/Android_Studio/sdk/ndk-bundle/sources/cxx-stl/llvm-libc++/include -isystem D:/Android_Studio/sdk/ndk-bundle/sources/android/support/include -isystem D:/Android_Studio/sdk/ndk-bundle/sources/cxx-stl/llvm-libc++abi/include -isystem D:/Android_Studio/sdk/ndk-bundle/sysroot/usr/include/i686-linux-android -D__ANDROID_API__=15 -g -DANDROID -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -mstackrealign -Wa,--noexecstack -Wformat -Werror=format-security -std=c++11 -frtti -fexceptions -O0 -fno-limit-debug-info  -fPIC -MD -MT CMakeFiles/native-lib.dir/src/main/cpp/native-lib.cpp.o -MF CMakeFiles\native-lib.dir\src\main\cpp\native-lib.cpp.o.d -o CMakeFiles/native-lib.dir/src/main/cpp/native-lib.cpp.o -c D:\Android_Studio\Workspace\NDKTestSample\app\src\main\cpp\native-lib.cpp
error: error reading 'D:\Android_Studio\Workspace\NDKTestSample\app\src\main\cpp\native-lib.cpp'
1 error generated.
ninja: build stopped: subcommand failed.`

* NDK Version: 17.1.4828580
* Build system: default ndk system. I dont know much about it. Nothing customized to build
* Host OS: Windows 10
* Compiler: Clang
* ABI: all 
* Cmake: 3.6.4111459
* android studio: 3.1.3
* Gradle: 4.4
* Android Plugin for Gradle: 3.1.3

I have already reported it [here](https://github.com/googlesamples/android-ndk/issues/310) and on [stackoverflow](https://stackoverflow.com/questions/51100111/how-to-resolve-android-ndk-build-command-faild/51161948?noredirect=1#comment89339554_51161948)

**Comment by HUSTWillHe** [comment]
have you slove this problem, i have the same problem now.

**Comment by Ni30patel** [comment]
@HUSTWillHe No. I am still finding solution for these.

**Comment by Ni30patel** [comment]
@HUSTWillHe After lot of trials and help from github google guy I am able to solve. To resolve problem I have follow below steps.

1.go to project directory.

2.deleted .gradle ,app/.externalNativeBuild and app/build.

3.changed local.properties ndk path to external ndk-r16b.

4.Run through Android studio.

5.Finally apk is generate.

**Comment by DanAlbert** [comment]
There's nothing we can do without a test case.
