### ISSUE TITLE
Vulkan validation layer causes a segfault for a Google's Vulkan tutorial sample.

### ISSUE THREAD

**Issue by jaebaek** [android-ndk/ndk#737]
#### Description

Vulkan validation layer causes a segfault for a Google's Vulkan tutorial sample.
It works fine without the Vulkan validation layer.

I added the following Vulkan validation layers

VK_LAYER_LUNARG_parameter_validation
VK_LAYER_GOOGLE_unique_objects
VK_LAYER_LUNARG_core_validation
VK_LAYER_GOOGLE_threading
VK_LAYER_LUNARG_object_tracker

to [tutorial04_first_window](https://github.com/googlesamples/android-vulkan-tutorials/tree/master/tutorial04_first_window).

You can find the edited code in
[here](https://github.com/jaebaek/android-vulkan-tutorials/tree/triangle/tutorial04_first_window).

You can reproduce it by running
1. Download the [latest stable NDK](https://developer.android.com/ndk/downloads/) i.e., r17b.
2. Unzip it in $HOME on Linux and put local.properties in `tutorial04_first_window` with the following code:
sdk.dir=/path/to/Android/Sdk/
ndk.dir=/path/to/android-ndk-r17b/

3. Build and install it using `cd /path/to/tutorial04_first_window && ./gradlew installDebug`.

#### Environment Details

* Device: Google Pixel 2

* NDK Version: Pkg.Revision = 17.1.4828580
* Build system: gradle + cmake
* Host OS: Linux (Debian GNU/Linux rodete).
* Compiler: Clang.
* ABI: arm64-v8a
* STL: GNU STL
* NDK API level: 24
* Device API level: Android 8.1.0.

**Comment by cnorthrop** [comment]
The layers in r17b are from February, so worth trying the latest.  I gave @jaebaek a recent build offline. 
 Adding @ggfan and @tobine.

**Comment by cnorthrop** [comment]
Latest layers didn't help.  We can migrate this issue to https://github.com/KhronosGroup/Vulkan-ValidationLayers

**Comment by ggfan** [comment]
thank you, @cnorthrop! let's track it over there.  Together with this one: https://github.com/googlesamples/android-vulkan-tutorials/issues/53

**Comment by cnorthrop** [comment]
Just to tidy this up, I'm getting the following error out of tutorial 04 just before the crash:

```
07-10 16:55:50.775  5717  5734 E vulkan  : [Validation] Code -1 :  [ VUID_Undefined ] Object: VK_NULL_HANDLE (Type = 0) | vkQueueSubmit: required parameter pSubmits[0].pWaitDstStageMask specified as NULL.
```
If I specify the mask, the error and crash go away:

```
diff --git a/tutorial04_first_window/app/src/main/jni/VulkanMain.cpp b/tutorial04_first_window/app/src/main/jni/VulkanMain.cpp
index 15e73fc..0775fc8 100644
--- a/tutorial04_first_window/app/src/main/jni/VulkanMain.cpp
+++ b/tutorial04_first_window/app/src/main/jni/VulkanMain.cpp
+
+  VkPipelineStageFlags waitStageMask =
+  VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT;
+
  VkSubmitInfo submit_info = {.sType = VK_STRUCTURE_TYPE_SUBMIT_INFO,
                              .pNext = nullptr,
                              .waitSemaphoreCount = 1,
                              .pWaitSemaphores = &render.semaphore_,
+                            .pWaitDstStageMask = &waitStageMask,
```

So this is probably an application issue and can be filed against the tutorial.

**Comment by cnorthrop** [comment]
Another bit of info, the error was not logged in the original test case because of the ordering of layers. `core_validation` crashed before `parameter_validation` could flag the error. On Android, the order must be specified for correct results:
```
const char *instance_layers[] = {
    "VK_LAYER_GOOGLE_threading",
    "VK_LAYER_LUNARG_parameter_validation",
    "VK_LAYER_LUNARG_object_tracker",
    "VK_LAYER_LUNARG_core_validation",
    "VK_LAYER_GOOGLE_unique_objects"
};
```
https://developer.android.com/ndk/guides/graphics/validation-layer#enabling

**Comment by ggfan** [comment]
they do seems to be app related: validation layers doing their work :-)!  I will follow it up on the app repo with you filed bug there: https://github.com/googlesamples/android-vulkan-tutorials/issues/53
