### ISSUE TITLE
__res_randomid not exist in dynamic library libc.so 

### ISSUE THREAD

**Issue by jamesho8743** [android-ndk/ndk#739]
Hello,
I am trying to build samba server 4.8.3 for Android, using latest NDK r17b.
When linking, it says undefined reference to __res_randomid.

I grep __res_randomid under ndk directory, it can find it in libc.a for all platforms, from android-14 to android-28. But Not in libc.so. It also doesn't make sense since all other __res_xxxx functions exist.

Also I check libraries under AOSP, it does exist in libc.a and libc.so
Is this intentional? What should I do to correctly link to __res_randomid()? 

NDK r17b
Host LinuxMint 17
API 24

**Comment by enh** [comment]
> Is this intentional?

no. i'll fix it for Android Q next year.

> What should I do to correctly link to __res_randomid()?

copy and paste the code, i'm afraid. the underlying `arc4random` is available, but `__res_randomid`/`res_randomid` are not currently exposed.

**Comment by enh** [comment]
https://android-review.googlesource.com/c/platform/bionic/+/718510

**Comment by enh** [comment]
fixed in Q by https://android-review.googlesource.com/718510
