### ISSUE TITLE
 fatal error: rs/cpp/utils/RefBase.h: No such file or directory

### ISSUE THREAD

**Issue by ckcfcyentn** [android-ndk/ndk#74]
In my code, I have..
...
#include <rs/cpp/util/RefBase.h>
...

In Application.mk, I have 
APP_STL:=stlport_static
APP_PLATFORM := android-19
APP_OPTIM := debug

When build, it has exception like this

 fatal error: rs/cpp/utils/RefBase.h: No such file or directory
 #include <rs/cpp/utils/RefBase.h>
                           ^
compilation terminated.

It happens when I switch ndk from r10e to r11c. Is it due to some removal of library?

**Comment by DanAlbert** [comment]
https://github.com/android-ndk/ndk/issues/7
