### ISSUE TITLE
Boost_log compilation issue with ndk16b

### ISSUE THREAD

**Issue by DeepthyR** [android-ndk/ndk#743]
I am trying to compile Boost 1.64.0 using android NDK 16b for arm64 using gcc (since we have specific requirement for gcc compilation)
It fails to compile boost_log and results in below error .

boost/boost_1_64_0/libs/log/src/dump_avx2.cpp:21:23: fatal error: immintrin.h: No such file or directory
#include <immintrin.h>
compilation terminated.
CMakeFiles/boost_log.dir/build.make:278: recipe for target 'CMakeFiles/boost_log.dir/boost_1_64_0/libs/log/src/dump_avx2.cpp.o' failed
make[2]: *** [CMakeFiles/boost_log.dir/boost_1_64_0/libs/log/src/dump_avx2.cpp.o] Error 1
make[2]: *** Waiting for unfinished

My build environment:
Android NDK - android-ndk16b
NDK API level - 24
C Compiler - GCC (GNU 4.9.0)
Cmake - 3.9.4
STL - gnustl_static
Host - Ubuntu 16.04.4

Thankyou.

**Comment by DanAlbert** [comment]
Probably either a misconfiguration of your build or an error in the boost source. immintrin.h only exists for x86/x86_64. If that failure is happening while you're building for arm/arm64, that's the problem.
