### ISSUE TITLE
Update cmake SDK package

### ISSUE THREAD

**Issue by vok1980** [android-ndk/ndk#746]
--------------------------------------------------------------------------------

#### Description
Currently Android SDK uses cmake 3.6, meanwhile [cmake 3.12 already released](https://blog.kitware.com/tag/release-notes/). Can you please update cmake package in Android SDK?

```
$ ./tools/bin/sdkmanager --list
<....>
Available Packages:
  Path                                                                                     | Version      | Description                                                         
  -------                                                                                  | -------      | -------                       
  cmake;3.6.4111459                                                                        | 3.6.4111459  | CMake 3.6.4111459  
```
#### Environment Details

* Build system: cmake
* Host OS: Linux

**Comment by vok1980** [comment]
@VestniK FYI

**Comment by Zingam** [comment]
You should use external CMake anyway.

**Comment by DanAlbert** [comment]
Wrong bug tracker. We don't maintain the SDK, only one component in it. Try https://b.android.com.

**Comment by vok1980** [comment]
https://issuetracker.google.com/issues/111569282
