### ISSUE TITLE
c++stl_shared.so comes without symbols

### ISSUE THREAD

**Issue by dryganets** [android-ndk/ndk#749]
#### Description

While gnu STL library comes unstripped the c++stl_shared.so comes without debugging symbols.
As you are going to deprecate gnu STL soon it will be handy to have a debugging information for the recommended library.

**Comment by DanAlbert** [comment]
We'll need to check and make sure that our various build system's will strip the library before packaging it in the APK, but as long as that happens this sounds like a good idea. (Woe be to anyone that has to debug libc++, but it should at least be possible.)

**Comment by dryganets** [comment]
I figured out the problem without symbols. One of the modules of my project was linked with c++shared instead of gnustl.
As result, an exception was thrown by c++shared and handled by gnustl stack hence undefined behavior and stack trace in c++lib only.

If I'd had symbols, it would save me some time.

**Comment by DanAlbert** [comment]
Looks like gradle will strip prebuilt libraries before installing them in your APK, so this is doable.

**Comment by DanAlbert** [comment]
https://android-review.googlesource.com/q/topic:%22libcxx-debug%22+(status:open%20OR%20status:merged)

**Comment by dryganets** [comment]
Thank you for fixing it!

**Comment by DanAlbert** [comment]
(keeping the bug open until the change is merged into the r18 branch)

**Comment by DanAlbert** [comment]
Okay, merged into r18 now.
