### ISSUE TITLE
API to enumerate system fonts from NDK?

### ISSUE THREAD

**Issue by tmm1** [android-ndk/ndk#751]
The libass open-source project needs to be able to enumerate system fonts available on Android. Currently the only way to do this is by parsing the `/system/etc/fonts.xml` file. However, this file has a huge warning at the top warning against using it and suggesting that the format is likely to change soon.

Is there an alternative method available to get a list of system fonts, ideally via the NDK?

On the Java side, it looks like `android.text.FontManager#getSystemFonts()` was proposed but then eventually removed from the public API (suggested in https://github.com/aosp-mirror/platform_frameworks_base/commit/19b05500b7ecc3998b77e1d03f36a73fe0531a9f#diff-59cec50835cfa2d987438f8b86daf314, removed in https://github.com/aosp-mirror/platform_frameworks_base/commit/ff55115121a7a2753ba2265cb3201a3a14c0874d#diff-59cec50835cfa2d987438f8b86daf314)

cc https://github.com/libass/libass/pull/312

**Comment by enh** [comment]
you'll want to file a bug with the Text folks over at https://source.android.com/setup/contribute/report-bugs

we just ship the platform folks' APIs.
