### ISSUE TITLE
-flto doesn''t work in r17b on Windows

### ISSUE THREAD

**Issue by vegorovinno** [android-ndk/ndk#752]
#### Description

We've tried adding -flto to compiler flags after upgrading to r17b, since release notes contained 'LTO now works on Windows', but the link fails the same way it did before:

```
make: Entering directory `E:/src/main/jni'
[armeabi-v7a] Install        : libfmod.so => libs/armeabi-v7a/libfmod.so
[armeabi-v7a] SharedLibrary  : libmain.so

C:/Work/android-ndk-r17b/build//../toolchains/arm-linux-androideabi-4.9/prebuilt/windows-x86_64/lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin\ld: error: E:/src/main/obj/local/armeabi-v7a/objs/external/spine/src/IkConstraint.o:1:3: invalid character
C:/Work/android-ndk-r17b/build//../toolchains/arm-linux-androideabi-4.9/prebuilt/windows-x86_64/lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin\ld: error: E:/src/main/obj/local/armeabi-v7a/objs/external/spine/src/IkConstraint.o:1:3: syntax error, unexpected $end
C:/Work/android-ndk-r17b/build//../toolchains/arm-linux-androideabi-4.9/prebuilt/windows-x86_64/lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin\ld: error: E:/src/main/obj/local/armeabi-v7a/objs/external/spine/src/IkConstraint.o: not an object or archive
...
```

A small snippet from NDK_LOG to confirm that clang toochain is used:

```Android NDK: Selecting release optimization mode (app is not debuggable)
Android NDK: Adding import directory: C:/Work/android-ndk-r17b/build//../sources
Android NDK: Building application 'local' for ABI 'armeabi-v7a'
Android NDK:   Enabling -fPIE for TARGET_PLATFORM android-16
Android NDK: Using target toolchain 'arm-linux-androideabi-clang' for 'armeabi-v7a' ABI (through NDK_TOOLCHAIN_VERSION)
```

#### Environment Details

* NDK Version: 17.1.4828580
* Build system: ndk-build
* Host OS: Windows
* Compiler: clang
* ABI: armeabi-v7a
* STL: c++_static
* NDK API level: android-16
* Device API level: min 16 target 26

**Comment by pirama-arumuga-nainar** [comment]
The linker complaining about invalid archive/object pretty much means Clang's gold plugin is not run/loaded while linking.

Can you confirm that `-flto` is passed to the link step, and that you're using the Gold linker?  The Clang driver passes the gold plugin to the linker command when `-flto` is present.

**Comment by pirama-arumuga-nainar** [comment]
As an aside, note that while LTO works with bfd using the plugin, it is not officially tested in upstream: https://llvm.org/docs/GoldPlugin.html

**Comment by vegorovinno** [comment]
Linker `LOCAL_LDFLAGS` were missing the -lto argument.

Thank you for your help and sorry for the inconvenience.
