### ISSUE TITLE
statically linking c++ files fails with standalone ndk r17b

### ISSUE THREAD

**Issue by johannkoenig** [android-ndk/ndk#754]
$ ./build/tools/make_standalone_toolchain.py --arch arm --install-dir /tmp/ndk17 --stl libc++ --api 28
$ PATH=/tmp/ndk17/bin:$PATH

$ cat test.cc
#include <iostream>

int main() {
  std::cout << "Test.\n";
  return 0;
}

$ arm-linux-androideabi-clang++ -o test test.cc -static
/buildbot/src/android/ndk-release-r17/external/libcxx/../../external/libunwind_llvm/src/AddressSpace.hpp:467: error: undefined reference to 'dladdr'

**Comment by DanAlbert** [comment]
Dup of https://github.com/android-ndk/ndk/issues/672 (already fixed for r18 beta 1, due out Soon).
