### ISSUE TITLE
GCC 4.9 from NDK r11c for Windows x86 can't link the binary if the '-fuse-ld' switch is specified as an argument to compiler driver

### ISSUE THREAD

**Issue by dosvidos** [android-ndk/ndk#76]
I'm using the compiler executable as linker front-end:
>android-ndk-r11c\toolchains\arm-linux-androideabi-4.9\prebuilt\windows\bin\arm-linux-androideabi-g++.exe Debug/main.o Debug/android_native_app_glue.o 
-Wl,-soname,libAndroid5.so
-shared
--sysroot=android-ndk-r11c/platforms/android-9/arch-arm
-Wl,-rpath-link=android-ndk-r11c/platforms/android-9/arch-arm/usr/lib "-landroid" "-lEGL" "-lGLESv1_CM"
-fuse-ld=gold
-Wl,--no-undefined
-Wl,-z,noexecstack
-Wl,-z,relro
-Wl,-z,now
-L"android-ndk-r11c/toolchains/arm-linux-androideabi-4.9/prebuilt/windows/lib/gcc/arm-linux-androideabi/4.9/armv7-a"
-L"android-ndk-r11c/platforms/android-9/arch-arm/usr/lib"
-L"android-ndk-r11c/sources/cxx-stl/gnu-libstdc++/4.9/libs/armeabi-v7a"
-L"android-ndk-r11c/toolchains/arm-linux-androideabi-4.9/prebuilt/windows/lib/gcc/arm-linux-androideabi/4.9/armv7-a" 
"android-ndk-r11c/sources/cxx-stl/gnu-libstdc++/4.9/libs/armeabi-v7a/libgnustl_static.a"
-lc
-lm
-llog
-lgcc
-oDebug/libAndroid5.so

That command line leads to the following error message:
>collect2.exe: fatal error: cannot find 'ld'
compilation terminated.

It works in case of NDK r11c for Windows x86_64

**Comment by DanAlbert** [comment]
(we're no longer updating GCC)
