### ISSUE TITLE
Check of the Android code by PVS-Studio

### ISSUE THREAD

**Issue by AndreyKarpov** [android-ndk/ndk#760]
I checked the Android code using the PVS-Studio static code analyzer and wrote the article on this topic: https://www.viva64.com/en/b/0579/

If you find this article interesting and you would like to analyze the code by yourself more thoroughly, we're ready to provide a temporary license.

**Comment by enh** [comment]
wrong bug tracker :-)

i went through your doc and filed internal bugs for the ones that hadn't already been fixed. i'm not sure what fraction were caught by the clang static analyzer vs humans.
