### ISSUE TITLE
Outdated ndk/docs folder at github

### ISSUE THREAD

**Issue by fornwall** [android-ndk/ndk#762]
The folder https://github.com/android-ndk/ndk/tree/master/docs seems to be outdated and can thus be misleading.

It can probably be removed (or should at least be updated if the docs should be there).

**Comment by rprichard** [comment]
The markdown files in the repository root are also out-of-date.

The `README.md` has a link to the up-to-date readme. The `CONTRIBUTING.md` file isn't linked from the up-to-date readme.

**Comment by DanAlbert** [comment]
Apparently the GoB to github merging service is ready for business now, so I'll try to find some time to get that set up.

**Comment by DanAlbert** [comment]
We deleted this in favor of just pointing at gitiles/dac from github.
