### ISSUE TITLE
LLVM_TRIPLE for armv7-none-linux-androideabi has APP_PLATFORM_LEVEL appended twice

### ISSUE THREAD

**Issue by JonathanLennox** [android-ndk/ndk#763]
#### Description

In the arm-linux-androideabi-clang toolchain, the ndk-build makefile variable LLVM_TRIPLE has the APP_PLATFORM_LEVEL appended to it twice -- once before TARGET_CFLAGS is set, once after.

To see this, add the following lines to an Android.mk file for a project targeting 32-bit arm:

$(info $$TARGET_CFLAGS is $(TARGET_CFLAGS))
$(info $$LLVM_TRIPLE is $(LLVM_TRIPLE))

You will see something like

$TARGET_CFLAGS is -gcc-toolchain /Users/jonathan/Library/Android/sdk/ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64 -fpic -ffunction-sections -funwind-tables -fstack-protector-strong -Wno-invalid-command-line-argument -Wno-unused-command-line-argument -no-canonical-prefixes -g -target armv7-none-linux-androideabi19 -march=armv7-a -mfloat-abi=softfp -mfpu=vfpv3-d16
$LLVM_TRIPLE is armv7-none-linux-androideabi1919

Note that the LLVM_TRIPLE ends in "1919", even though the -triple argument to TARGET_CFLAGS is correct.

This means that any attempt to use LLVM_TRIPLE for specialized clang invocations will be confused about the Android API version being targeted.

(It's also not clear to me why only 32-bit arm has the API specified on the triple, but that's another issue...)

#### Environment Details

Not all of these will be relevant to every bug, but please provide as much
information as you can.

* NDK Version: 17.1.4828580
* Build system: ndk-build
* Host OS: Mac (but irrelevant)
* Compiler: clang
* ABI: 19 (but irrelevant)
* STL:
* NDK API level: 19 (but irrelevant)
* Device API level:

**Comment by rprichard** [comment]
This is already fixed in r18 beta 1:
https://android-review.googlesource.com/c/platform/ndk/+/659627/

Now LLVM_TRIPLE doesn't have a target API on it, and ndk-build appends one using `$(TARGET_PLATFORM_LEVEL)` when it passes the triple to clang.
