### ISSUE TITLE
Turn on LLVM_ENABLE_THREADS

### ISSUE THREAD

**Issue by tavianator** [android-ndk/ndk#764]
LLVM's "ThinLTO" has nice support for running LTO in parallel, but apparently the NDK toolchain is built with threads disabled.  It would be nice if the next NDK release had threading enabled for faster LTO.

```
$ cat foo.c
int main() {
  return 0;
}
$ clang -O3 -flto=thin foo.c
$ /opt/ndk-arm64/bin/aarch64-linux-android-clang -O3 -flto=thin foo.c
Warning: request a ThreadPool with 1 threads, but LLVM_ENABLE_THREADS has been turned off
```

**Comment by DanAlbert** [comment]
It's too late for a clang update in r18, but I don't think there's been an update for r19 yet so hopefully it can happen then.

**Comment by pirama-arumuga-nainar** [comment]
AOSP's clang prebuilts clang-4679922 and clang-r328903 are built with LLVM_ENABLE_THREADS.  The former might be in r17 and the latter is definitely in r18.

**Comment by DanAlbert** [comment]
Oh, great! I'm guessing OP was using r17 (correct me if I'm wrong), so this is fixed in r18.

**Comment by enh** [comment]
(i can certainly reproduce the problem with r17b.)

**Comment by tavianator** [comment]
Yep sorry, meant to say I'm on r17b.  Glad it's already fixed, thanks!
