### ISSUE TITLE
Is there any way to generate compile_commands.json file through ndk-build?

### ISSUE THREAD

**Issue by fiddleyuan** [android-ndk/ndk#765]
I'm using android-ndk-r13 for Windows for developing in my company. Our working model is using Visual Studio+Visual GDB to trigger ndk-build for compilation. I'm wondering if there is any way to generate compile_commands.json database file?

I googled this topic, seems there's no support till now. Please correct me if I was wrong. Also, any workarounds are welcomed. Thank you very much.

**Comment by enh** [comment]
@DanAlbert is working on it here: https://android-review.googlesource.com/c/platform/ndk/+/709061

**Comment by DanAlbert** [comment]
Finally addressed the review comments. Should be in r18.

**Comment by fiddleyuan** [comment]
@enh @DanAlbert Fantastic job!
Thank you very much, looking forward to Windows platform binary release.

**Comment by DanAlbert** [comment]
Merged into r18.

**Comment by safield** [comment]
So how does this feature work?

**Comment by DanAlbert** [comment]
Check the r18 changelog: https://github.com/android/ndk/wiki/Changelog-r18

Should also get this into the docs

**Comment by enh-google** [comment]
(i've sent a doc change adding this to the ndk-build page out for review...)
