### ISSUE TITLE
--fix-cortex-a8 for lld

### ISSUE THREAD

**Issue by DanAlbert** [android-ndk/ndk#766]
Do we still need to support fixing this errata? Still waiting on data...

**Comment by arturbac** [comment]
With ndk18 beta 1, armv7a and -fuse-ld=lld i had to add to get rid ot that (it was added by default by cmake toolchain)

  string(REPLACE "-Wl,--fix-cortex-a8" "" CMAKE_SHARED_LINKER_FLAGS ${CMAKE_SHARED_LINKER_FLAGS})
  string(REPLACE "-Wl,--fix-cortex-a8" "" CMAKE_MODULE_LINKER_FLAGS ${CMAKE_MODULE_LINKER_FLAGS})
  string(REPLACE "-Wl,--fix-cortex-a8" "" CMAKE_EXE_LINKER_FLAGS ${CMAKE_EXE_LINKER_FLAGS})

**Comment by DanAlbert** [comment]
It's also in ndk-build and standalone toolchains. For the latter two we can check the user's ldflags to see if they're using lld, but for CMake we don't have that information yet (the CMakeLists.txt hasn't been parsed that early).

Would be a good candidate for hoisting into the driver. It may already have been, actually. I'll check.

https://github.com/android-ndk/ndk/issues/776

**Comment by DanAlbert** [comment]
Finally got the data we need. There are an insignificant number of devices in the API range supported by the NDK that use Cortex-A8 CPUs, so we'll drop that from the default flags and mention it in the changelog with a link to CPU blacklisting like we did for NEON.

Closing this bug in favor of https://github.com/android-ndk/ndk/issues/776 to handle actually removing the flag from the defaults.
