### ISSUE TITLE
`endpwent` is in pwd.h header but cannot be referenced

### ISSUE THREAD

**Issue by jacksparser** [android-ndk/ndk#77]
When running ndk-build using r11b, the endpwent function cannot be found.

`error: undefined reference to 'endpwent'`

It's still in header, pwd.h, though.

**Comment by mikaelfoo** [comment]
hi, i am facing similar issues, any fix for this?

**Comment by DanAlbert** [comment]
Unfortunately no. This wasn't added to Android until very recently (won't even be in N). Even when you do have the definition available, it won't actually be usable until Android O.

Longer term we have plans to create a compatibility library that fills in gaps like this for older platforms, but that's a ways out.
