### ISSUE TITLE
minSdkVersion 19 got error, undefined reference to 'strtof'

### ISSUE THREAD

**Issue by cyxcw1** [android-ndk/ndk#770]
#### Description
When I use ***minSdkVersion 19*** compile my project, and in the link step, I got this error:
``
protobuf/android/armeabi-v7a/libProtobuf.a(strutil.cc.o):strutil.cc:function protobuf::safe_strtof(char const*, float*): error: undefined reference to 'strtof'
``
But I change my ***minSdkVersion*** to **21**, the error disappear. 
My APP must support API 19, Do we have some workaround to solve this problem?

(It is similar to the question: https://github.com/android-ndk/ndk/issues/769. It is the same project)

#### Environment Details

* NDK Version: 15c, 16b ( I have tried some version, got the same error)
* Build system:  cmake
* ABI: armeabi-v7a
* STL: c++static

**Comment by enh** [comment]
looks like exactly the same problem as you had with rand(3). there's an inline workaround in `include/android/legacy_stdlib_inlines.h` that you should get for free if you `#include <stdlib.h>`. at ToT strutil.h seems to include that, and git blame says it was added 9 years ago, so you might have to do some digging to work out why.

check that your old NDK versions actually have this (or upgrade to r17b), check that you have the #include, check that you're actually setting your target API level correctly...

**Comment by cyxcw1** [comment]
@enh 
I have spent a lot time to dig, but I only found ***minSdkVersion 21*** will solve it. We can not upgrade our app to ***minSdkVersion 21***.
I have tried to upgrade to r17b, still did not work.

**Comment by enh** [comment]
check that `<stdlib.h>` is actually getting included where strtof is called. check that you have your target API level set to 19. one (or both) of this is wrong, because our `<stdlib.h>` will give you an inline strtof(3) on old API levels.

**Comment by cyxcw1** [comment]
@enh 
I have `<csstdlib>` included where strtof is called.
I have set my **mindSdkVersion to 19**.

But I still got this error.
And I found the definition of strtof:
![image](https://user-images.githubusercontent.com/3744610/44032671-71f98d16-9f3a-11e8-8cab-97421016e390.png)
Its path is:
![image](https://user-images.githubusercontent.com/3744610/44032706-87e78326-9f3a-11e8-8afb-5b772b676f18.png)
Is it right?

**Comment by cyxcw1** [comment]
@enh 
And these are my build.gradle defaultConfig:
`
defaultConfig {
        applicationId "com.example.jnitest"
        minSdkVersion 19
        targetSdkVersion 23
        versionCode 1
        versionName "1.0"
        multiDexEnabled true

        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
        externalNativeBuild {
            cmake {
                cppFlags "-std=c++11 -fexceptions -frtti -v"
                abiFilters 'armeabi-v7a'
                arguments "-DANDROID_STL=c++_static"
            }
        }
    }
`

**Comment by cyxcw1** [comment]
I think I have resolve this problem. I should use the right build tool-chain. 
My **minSdkVersion** is 19, I should use tool-chain:  android-ndk-r16b-api-19-armeabi-v7a-clang-libcxx.cmake.
I got error before because I use a tool-chain of API 21: android-ndk-r16b-api-21-armeabi-v7a-clang-libcxx.cmake.
The tool-chain could be found here: https://github.com/ruslo/polly

**Comment by DanAlbert** [comment]
Correct. Your NDK target version cannot be higher than your `minSdkVersion`: https://android.googlesource.com/platform/ndk/+/master/docs/user/common_problems.md
