### ISSUE TITLE
fatal error: stddef.h: No such file or directory with android standalone toolchain for API-26.

### ISSUE THREAD

**Issue by ranjankumar23** [android-ndk/ndk#772]
**Note**: Bugs against Android Studio or Gradle should be filed at
http://b.android.com, not here.

Before filing a bug, check that you are using the latest version of the NDK. The
latest stable version and the preview release of the next stable version are
listed on our wiki: https://github.com/android-ndk/ndk/wiki#downloads.

Make sure your issue isn't on the list of common problems before filing a bug:
https://android.googlesource.com/platform/ndk/+/master/docs/user/common_problems.md

Delete everything above this line before submitting.

--------------------------------------------------------------------------------

#### Description

                 ^
+++ Message from REF_BCM97252S_BCM7252S_ANDROID_LNUX_01/platform.mk - Creating object /code/build/enzbb1/epg/release/components/mediacas_engine/src/engine/mediacas_notify.o
/code/code/BLD_REF_BCM97252S_BCM7252S_ANDROID_LNUX_01/platform_cfg/linux/compiler/stbgcc-4.9/bin/arm-linux-androideabi-g++  -O2 -fno-strict-aliasing -Wall -Fpie -mfloat-abi=soft -DNeedFunctioPrototypes=1 -Wshadow -Wpointer-arith  -std=c++0x -I/code/code/BLD_REF_BCM97252S_BCM7252S_ANDROID_LNUX_01/platform_cfg/linux/compiler/stbgcc-4.9/nds/inc/ -c src/engine/mediacas_notify.cpp -o /code/build/enzbb1/epg/release/components/mediacas_engine/src/engine/mediacas_notify.o

In file included from src/engine/mediacas_notify.cpp:39:0:

In file included from /auto/spvss-evo-bin1/Published/code/compilers/AndroidNexus/Android-26-tool-chain/include/c++/4.9.x/type_traits:390:0,
                 from /auto/spvss-evo-bin1/Published/code/compilers/AndroidNexus/Android-26-tool-chain/include/c++/4.9.x/memory:643,
                 from /auto/spvss-evo-bin1/Published/code/compilers/AndroidNexus/Android-26-tool-chain/include/c++/4.9.x/list:173,
                 from /code/code/build_system/components/mediacas_engine/inc/mediacas_descriptors.h:6,
                 from src/engine/mediacas_notify.cpp:66:
/auto/spvss-evo-bin1/Published/code/compilers/AndroidNexus/Android-26-tool-chain/include/c++/4.9.x/cstddef:44:25: fatal error: stddef.h: No such file or directory
 #include_next <stddef.h>

#### Environment Details
$NDK/build/tools/make_standalone_toolchain.py 
--arch arm 
--api 26 
--stl=libc++ 
--install-dir=my-toolchain

Not all of these will be relevant to every bug, but please provide as much
information as you can.
NDK Version: 17.0.4754217
Build sytem: standalone toolchain
Host OS: Linux["Red Hat Enterprise Linux Server 7.4 (Maipo)"]
Compiler:
ABI:
STL:
NDK API level:
Device API level:

**Comment by rprichard** [comment]
The compiler here is `arm-linux-androideabi-g++`. gcc is deprecated in r17 and removed from r18. Clang is the supported NDK compiler.

I don't think the NDK's gcc works with the libc++ STL. I suggest switching to Clang, or if that isn't possible, then maybe try gnustl with GCC. Neither gnustl nor GCC exist in r18, though, so it would only be a temporary fix.

**Comment by ranjankumar23** [comment]
Thanks Richard.
I was so naive.

**Comment by wangdongxuking61** [comment]
in file include/c++/4.9.x/cstddef  line 44
change `#include_next <stddef.h>` to `#include<stddef.h>`
