### ISSUE TITLE
Segfault when compiling firefox for android

### ISSUE THREAD

**Issue by jyavenard** [android-ndk/ndk#775]
#### Description

Bug description goes here. Include a test case. It's unlikely that anything can
be done without a test case.

All files (included pre-processor output) are attached to bug https://bugzilla.mozilla.org/show_bug.cgi?id=1484723

* NDK Version: Value from Pkg.Revision in ndk-bundle/source.properties. If not
  the latest version, check there before filing.
r17b

* Build system: ndk-build? cmake? standalone toolchain? custom? (if gradle, file
  a bug against studio as specified above)
custom

* Host OS: Windows, Mac, or Linux? Which Linux?
macOS 10.13.6
* Compiler: If GCC, check Clang before filing. GCC is no longer supported.
ndk's clang (6.0.0)

**Comment by enh** [comment]
have you tried the r18 beta? it has a much newer version of clang...

**Comment by jyavenard** [comment]
Didn't try with r18b, upgrading the version of ndk is usually not straightforward.

using clang 6.0.1 from brew doesn't segfault.

**Comment by jyavenard** [comment]
Same issue occurs on ubuntu 18.04 LTS with the r17b ndk

**Comment by pirama-arumuga-nainar** [comment]
The reproducer in the mozilla bug does not crash with the [Clang in r18b](https://android.googlesource.com/platform/prebuilts/clang/host/linux-x86/+/master/clang-r328903/).  I suggest you try the new Clang on just this source file.

**Comment by jyavenard** [comment]
I don't know who the reproducer is, but I just tried with the r18-beta1 ndk and it crashes in various spots (always segfault).
So I'm confused on why you would think clang in r18b was okay

**Comment by pirama-arumuga-nainar** [comment]
> I don't know who the reproducer is

I meant the test case in https://bugzilla.mozilla.org/show_bug.cgi?id=1484723.  I ran the .cpp file using the command in the .sh after replacing the path to the compiler with the one in the r18 beta.

> but I just tried with the r18-beta1 ndk and it crashes in various spots (always segfault).

Can you share a test case that fails with r18-beta?

> So I'm confused on why you would think clang in r18b was okay

My bad.  I confused the state of the r18 release.  I meant r18-beta1.

**Comment by jyavenard** [comment]
The problem is that with the r18-beta1, compilation hangs now, so I don't get the pre-processed file message. and don't know where to fetch it

**Comment by pirama-arumuga-nainar** [comment]
@jyavenard https://bugzilla.mozilla.org/show_bug.cgi?id=1484723 and https://bugzilla.mozilla.org/show_bug.cgi?id=1484823 seem to imply that r18-beta1 is now working.  Please reopen if that's not the case.
