### ISSUE TITLE
android ndk cmake is not able to generate one executable file

### ISSUE THREAD

**Issue by zcy618** [android-ndk/ndk#777]
hi all:
my ndk version is android-ndk-r17b-linux-x86_64.zip
my cmake version is 3.12
I meet one strange issue, I write one demo code with cpp and aarch64 asm, my cmakelists.txt is as below:
cmake_minimum_required(VERSION 3.6)

set(CMAKE_SYSTEM_NAME Android)
set(CMAKE_SYSTEM_VERSION 21) # API level
set(CMAKE_ANDROID_ARCH_ABI arm64-v8a)
set(CMAKE_ANDROID_NDK /home/chenyuz/android-ndk)
set(CMAKE_ANDROID_STL_TYPE gnustl_static)

PROJECT(test_hello LANGUAGES C CXX ASM VERSION 0.1)

find_package(Threads)

INCLUDE_DIRECTORIES(
inc
)

AUX_SOURCE_DIRECTORY(src Source)

list(APPEND Source src/rsCpuIntrinsics_advsimd_Resize.S)

add_executable(${PROJECT_NAME} ${Source})

target_link_libraries(${PROJECT_NAME} ${CMAKE_THREAD_LIBS_INIT})

TARGET_LINK_LIBRARIES(${PROJECT_NAME} m)
TARGET_LINK_LIBRARIES(${PROJECT_NAME} log)
TARGET_LINK_LIBRARIES(${PROJECT_NAME} c)

Then I run:

chenyuz@chenyuz-youdao:~/Youdao/Aarch64_unittest/build$ cmake -DCMAKE_TOOLCHAIN_FILE=/home/chenyuz/android-ndk/build/cmake/android.toolchain.cmake -DCMAKE_BUILD_TYPE=Release -DANDROID_ABI=arm64-v8a .. 
-- The ASM compiler identification is Clang 
-- Found assembler: /home/chenyuz/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/clang 
-- Check for working C compiler: /home/chenyuz/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/clang 
-- Check for working C compiler: /home/chenyuz/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/clang -- works 
-- Detecting C compiler ABI info -- Detecting C compiler ABI info - done 
-- Detecting C compile features 
-- Detecting C compile features - done 
-- Check for working CXX compiler: /home/chenyuz/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++ 
-- Check for working CXX compiler: /home/chenyuz/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++ -- works 
-- Detecting CXX compiler ABI info 
-- Detecting CXX compiler ABI info - done 
-- Detecting CXX compile features 
-- Detecting CXX compile features - done 
-- Configuring done 
-- Generating done 
-- Build files have been written to: /home/chenyuz/Youdao/Aarch64_unittest/build 
chenyuz@chenyuz-youdao:~/Youdao/Aarch64_unittest/build$ make 
Scanning dependencies of target test_hello 
[ 50%] Building CXX object CMakeFiles/test_hello.dir/jni/test-asm.cpp.o 
[100%] Linking CXX executable test_hello 
[100%] Built target test_hello 
chenyuz@chenyuz-youdao:~/Youdao/Aarch64_unittest/build$ file test_hello 
test_hello: ELF 64-bit LSB shared object, ARM aarch64, version 1 (SYSV), dynamically linked (uses shared libs), BuildID[sha1]=e12c6117eba88c1c844d719d6707a5ef48d233de, not stripped 
chenyuz@chenyuz-youdao:~/Youdao/Aarch64_unittest/build$

as you see, it is generated as shared object, not executable file. I already use add_executable() function, so I am really wonderring how to generate one executable file, it already tormented some days, I really need your help!

Thanks in advanced!

**Comment by DanAlbert** [comment]
Unfortunately this is a really confusing area because there are two different forms of NDK support for CMake. One that's built in to CMake and doesn't always work with the latest NDK, and one that's included with the NDK and doesn't always work with the latest CMake. You're using the former, which we do not support.

If you'd like to continue using that method, you'll need to file this bug with the cmake folks as we don't have the ability to do anything about it.

Alternatively, you could try using our toolchain file instead (I haven't heard of any issues with r17 and CMake 3.12 when using our toolchain file). Invoke CMake with `-DCMAKE_TOOLCHAIN_FILE=path/to/ndk/build/cmake/android.toolchain.cmake -DANDROID_ABI=arm64-v8a -DANDROID_PLATFORM=android-21 -DANDROID_STL=gnustl_static` and remove this block from your CMakeLists.txt:

```cmake
set(CMAKE_SYSTEM_NAME Android)
set(CMAKE_SYSTEM_VERSION 21) # API level
set(CMAKE_ANDROID_ARCH_ABI arm64-v8a)
set(CMAKE_ANDROID_NDK /home/chenyuz/android-ndk)
set(CMAKE_ANDROID_STL_TYPE gnustl_static)
```

Those flags match your configuration above. Others are documented here: https://developer.android.com/ndk/guides/cmake

**Comment by zcy618** [comment]
hi Dan:
Thanks for your reply, but your suggestion seems not able to fix, currently my cmake file is as below:

cmake_minimum_required(VERSION 3.6)

PROJECT(test_hello LANGUAGES C CXX ASM VERSION 0.1)

enable_language(ASM)

find_package(Threads)

INCLUDE_DIRECTORIES(
inc
)

AUX_SOURCE_DIRECTORY(src Source)

#set(Source ${Source} src/rsCpuIntrinsics_advsimd_Resize.S)
list(APPEND Source src/rsCpuIntrinsics_advsimd_Resize.S)

add_executable(${PROJECT_NAME} ${Source})

target_link_libraries(${PROJECT_NAME} ${CMAKE_THREAD_LIBS_INIT})

TARGET_LINK_LIBRARIES(${PROJECT_NAME} m)
TARGET_LINK_LIBRARIES(${PROJECT_NAME} log)
TARGET_LINK_LIBRARIES(${PROJECT_NAME} c)

chenyuz@chenyuz-youdao:~/android-cmake/build$ cmake DCMAKE_TOOLCHAIN_FILE=/home/chenyuz/android-ndk/build/cmake/android.toolchain.cmake -DANDROID_ABI=arm64-v8a -DANDROID_PLATFORM=android-21 -DANDROID_STL=gnustl_static ..
-- The C compiler identification is GNU 4.8.4
-- The CXX compiler identification is GNU 4.8.4
-- The ASM compiler identification is GNU
-- Found assembler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Configuring done
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    ANDROID_ABI
    ANDROID_PLATFORM
    ANDROID_STL


-- Build files have been written to: /home/chenyuz/android-cmake/build
chenyuz@chenyuz-youdao:~/android-cmake/build$ make
Scanning dependencies of target test_hello
[ 25%] Building CXX object CMakeFiles/test_hello.dir/src/Helloworld.cpp.o
[ 50%] Building CXX object CMakeFiles/test_hello.dir/src/sqrt.cpp.o
[ 75%] Building ASM object CMakeFiles/test_hello.dir/src/rsCpuIntrinsics_advsimd_Resize.S.o
/home/chenyuz/android-cmake/src/rsCpuIntrinsics_advsimd_Resize.S: Assembler messages:
/home/chenyuz/android-cmake/src/rsCpuIntrinsics_advsimd_Resize.S:112: Error: unrecognized symbol type ""
/home/chenyuz/android-cmake/src/rsCpuIntrinsics_advsimd_Resize.S:113: Error: too many memory references for `lsl'

as you may see, asm instructions are regconized.

Thanks
