### ISSUE TITLE
ndk-gdb r11b for Windows 10 64bits problems

### ISSUE THREAD

**Issue by CicTec** [android-ndk/ndk#78]
Hello

I have found problems running the debugger on r11c (Windows 10 64bits):

Use the following command line to start a package installed in the emulator:
ndk-gdb.cmd --launch --verbose --nowait

The first log is this:
ADB command used: 'adb -s emulator-5554'
ADB version: Android Debug Bridge version 1.0.32 Revision 09a0d98bebce-android
Using project directory: C:\android-project
Found package name: org.libsdl.app
Selected target activity: 'org.libsdl.app.SDLActivity'
Application ABIs: armeabi, armeabi-v7a
Traceback (most recent call last):
File "C:\android-ndk\prebuilt\windows-x86_64\bin\ndk-gdb.py", line 688, in 
main()
File "C:\android-ndk\prebuilt\windows-x86_64\bin\ndk-gdb.py", line 607, in main
abi = fetch_abi(args)
File "C:\android-ndk\prebuilt\windows-x86_64\bin\ndk-gdb.py", line 340, in fetch_abi
device_abis = [device_props[key].split(",") for key in abi_props]
KeyError: 'ro.product.cpu.abi2'

I commented the line 334 on ndk-gdb.py file:
old_abi_props = ["ro.product.cpu.abi", "ro.product.cpu.abi2"]

and adding:
old_abi_props = ["ro.product.cpu.abi"]

re-launched the debugger, with the log:
ADB command used: 'adb -s emulator-5554'
ADB version: Android Debug Bridge version 1.0.32 Revision 09a0d98bebce-android
Using project directory: C:\android-project 
Found package name: org.libsdl.app
Selected target activity: 'org.libsdl.app.SDLActivity'
Application ABIs: armeabi, armeabi-v7a
Device ABIs: armeabi
Selecting ABI: armeabi
Detected pretty printer: none
Found application data directory: /data/data/org.libsdl.app
Found app gdbserver: /data/data/org.libsdl.app/lib/gdbserver
Launching activity org.libsdl.app/org.libsdl.app.SDLActivity...
Sleeping for 0.25 seconds.
Traceback (most recent call last):
File "C:\android-ndk\prebuilt\windows-x86_64\bin\ndk-gdb.py", line 688, in 
main()
File "C:\android-ndk\prebuilt\windows-x86_64\bin\ndk-gdb.py", line 648, in main
pids = gdbrunner.get_pids(device, pkg_name)
File "C:\android-ndk\python-packages/gdbrunner/__init__.py", line 137, in get_pids
processes = get_processes(device)
File "C:\android-ndk\python-packages/gdbrunner/__init__.py", line 127, in get_processes
pid = int(columns[pid_column])
ValueError: invalid literal for int() with base 10: 'PID'

I'm doing some work in the wrong way or have bugs?

Regards.

**Comment by DanAlbert** [comment]
@jmgao have you had a chance to look in to this?

**Comment by jmgao** [comment]
Sorry for not looking at this, I had other stuff on my plate. Should be fixed by the following two commits:

https://android-review.googlesource.com/#/c/222517/
https://android-review.googlesource.com/#/c/222584/

**Comment by jmgao** [comment]
Patches merged to master/r12
