### ISSUE TITLE
reject unspecified APP_PLATFORM without manifest

### ISSUE THREAD

**Issue by DanAlbert** [android-ndk/ndk#79]
Unless the user is building an app, there's no good way to guess an `APP_PLATFORM` level. We should:
- If we have a `minSdkVersion` and no `APP_PLATFORM`, use `minSdkVersion`
- If we have an `APP_PLATFORM` and no `minSdkVersion, use`APP_PLATFORM`
- If we have both and they are mismatched, use `APP_PLATFORM` and issue a warning
- If we have neither, fail

**Comment by DanAlbert** [comment]
@enh: Any thoughts on if we should still do this? We now have good automatic configuration of this and a warning will be emitted if the user hasn't set one. I'm not sure it's worth the disruptions to turn this into an error or not.

**Comment by enh** [comment]
yeah, the warning's probably enough.
