### ISSUE TITLE
Toolchain doesn't work with Windows 32 bit version

### ISSUE THREAD

**Issue by Jeruntu** [android-ndk/ndk#791]
#### Description

I downloaded the 32 bit version of ndk r17c for Windows from: https://developer.android.com/ndk/downloads/
The cmake toolchain always assumes the host is a 64 bit system, even in the 32 bit version of the ndk for windows:
`elseif(CMAKE_HOST_SYSTEM_NAME STREQUAL Windows)
    set(ANDROID_HOST_TAG windows-x86_64)
endif()`
It should check if the ndk is 32 or 64 bit and set the ANDROID_HOST_TAG variable accordingly. So for 32 bit it should be:
`set(ANDROID_HOST_TAG windows)`

* NDK Version: r17c
* Build system: cmake
* Host OS: Windows 10

**Comment by wang-bin** [comment]
the bug exists for a long time. please fix it

**Comment by DanAlbert** [comment]
https://android-developers.googleblog.com/2019/06/moving-android-studio-and-android.html

The 32-bit Windows NDK won't exist starting with r21, so this bug is now obsolete.
