### ISSUE TITLE
lgamma() is broken in ToT libandroid_support

### ISSUE THREAD

**Issue by rprichard** [android-ndk/ndk#793]
A couple of the 32-bit x86 NDK libc++ tests currently fail with errors like this:

```
/x/ndk/out/android-ndk-r19-canary/sources/cxx-stl/llvm-libc++/test/std/numerics/c.math/cmath.pass.cpp:1152: void test_lgamma(): assertion "std::lgamma(1) == 0" failed
```

The lgamma function in libandroid_support.a for arm32 and x86 is broken. It's merely a wrapper around lgamma_r, which it implicitly declares to return int. It should return double.

Building the NDK libc++ module shows the warning in out/dist/logs/libc++.log:

```
/x/ndk/bionic/libm/upstream-freebsd/lib/msun/src/e_lgamma.c:34:9: warning: implicit declaration of function 'lgamma_r' is invalid in C99 [-Wimplicit-function-declaration]
        return __ieee754_lgamma_r(x,&signgam);
               ^
/x/ndk/bionic/libm/upstream-freebsd/lib/msun/src/math_private.h:845:28: note: expanded from macro '__ieee754_lgamma_r'
#define __ieee754_lgamma_r lgamma_r
                           ^
```

The lgamma_r function is only declared with __USE_BSD or __USE_GNU (so _BSD_SOURCE or _GNU_SOURCE). This C file is compiled with _BSD_SOURCE in Bionic, so that's presumably the android_support fix.

r18 squeaks by:
 - android/support/Android.mk uses `-include freebsd-compat.h` then `-include openbsd-compat.h`. The OpenBSD header declares _BSD_SOURCE.
 - In master, the FreeBSD compat header doesn't include much, but it recently added a math.h include, which I assume triggered this bug.

The android_support makefile compiles its C++ files (a handful) with `-Werror`, but not the C files. With a fix for the above, the code still has implicit declarations of cimag and creal, but the compiler recognizes them as standard library functions, so it does the right thing:

```
/x/ndk/bionic/libm/upstream-freebsd/lib/msun/src/k_exp.c:94:6: warning: implicitly declaring library function 'creal' with type 'double (_Complex double)' [-Wimplicit-function-declaration]
        x = creal(z);
            ^
/x/ndk/bionic/libm/upstream-freebsd/lib/msun/src/k_exp.c:94:6: note: include the header <complex.h> or explicitly provide a declaration for 'creal'
[armeabi-v7a] Compile thumb  : android_support <= s_remquo.c
/x/ndk/bionic/libm/upstream-freebsd/lib/msun/src/k_exp.c:95:6: warning: implicitly declaring library function 'cimag' with type 'double (_Complex double)' [-Wimplicit-function-declaration]
        y = cimag(z);
            ^
/x/ndk/bionic/libm/upstream-freebsd/lib/msun/src/k_exp.c:95:6: note: include the header <complex.h> or explicitly provide a declaration for 'cimag'
```

k_exp.c *is* including complex.h, but I think the `__ANDROID_API__` value is too low to provide the cimag and creal functions. Maybe we should declare those functions somewhere for the sake of android_support?

**Comment by rprichard** [comment]
Also: it's not clear to me that android_support needs `e_lgamma.c`. `libm.map.txt` already declares both `lgamma` and `lgamma_r` for all versions.

**Comment by rprichard** [comment]
Maybe another option is to #ifdef out `__ldexp_cexp` from `k_exp.c` when `__BIONIC_BUILD_FOR_ANDROID_SUPPORT` is defined. That looks like the only function in `libandroid_support.a` that needs `cimag` / `creal`. If I remove it, then I'm able to build `libandroid_support.a` with `-Werror`.

**Comment by enh** [comment]
> Maybe another option is to #ifdef out `__ldexp_cexp` from `k_exp.c` when `__BIONIC_BUILD_FOR_ANDROID_SUPPORT` is defined. That looks like the only function in `libandroid_support.a` that needs `cimag` / `creal`. If I remove it, then I'm able to build `libandroid_support.a` with `-Werror`.

i'd rather not modify libm source unless we have to.

what happens if you stop building `e_lgamma.c`?

**Comment by rprichard** [comment]
> what happens if you stop building `e_lgamma.c`?

Removing the file is sufficient to fix this bug, so I think we should remove it.

Do we want to try building libandroid_support's C files with `-Werror`? It would have caught this bug more easily/quickly, and implicitly declared functions seems like something we want to avoid. The bug breaks `lgamma` on arm32/x86, but it's only caught on x86, because the libc++ test only tests `lgamma(1) == 0`, and that's easy to pass even with double/int return type mismatch.

Enabling `-Werror` breaks because even with `e_lgamma.c` removed, there are still calls to implicitly-declared `cimag` and `creal` functions. The calls come from a function that libandroid_support doesn't use (`__ldexp_cexp`), from a file that also has `__ldexp_exp`, which libandroid_support *does* use. The `cimag`/`creal` functions are trivial, and Clang provides predeclared equivalents named `__builtin_cimag`/`__builtin_creal`. AFAICT, all of them are treated as builtins and inlined. We could conceivably declare them in complex.h, though I suppose taking the address of `creal`/`cimag` wouldn't work pre-M.

Maybe we could add this to `libm/freebsd-compat.h`?

```c
// complex.h doesn't declare cimag/creal when building libandroid_support,
// because the functions are only available starting with M, and
// libandroid_support is compiled for the oldest supported NDK API. Clang
// inlines calls to these functions even with -O0.
double cimag(double _Complex z);
double creal(double _Complex z);
```

**Comment by enh** [comment]
> +1 for dialing up warnings/werror anywhere in the NDK's own code (just have to be careful to not force anything on users). I was under the impression we already did build libandroid_support with werror.

(yeah, "what he said". i was surprised and disappointed to learn that we don't.)

> Maybe we could add this to `libm/freebsd-compat.h`?

there's no -include for `libandroid_support` we could declare them in? (i'm a bit wary that adding this to libm might cause us trouble there at some point. but it's probably fine?)

**Comment by rprichard** [comment]
> (... i was surprised and disappointed to learn that we don't.)

`-Werror` is set in `LOCAL_CPPFLAGS` in `android/support/Android.mk`, but that C++ only.

> there's no -include for libandroid_support we could declare them in?

Not yet, but we could add one. `android/support/src/support_preinclude.h`?

**Comment by enh** [comment]
> Not yet, but we could add one. `android/support/src/support_preinclude.h`?

sgtm.

**Comment by rprichard** [comment]
https://android-review.googlesource.com/c/platform/ndk/+/758122
