### ISSUE TITLE
Performance regression in r18 with ndk-build inside makefiles themselves

### ISSUE THREAD

**Issue by b-spencer** [android-ndk/ndk#799]
#### Description

When upgrading from r16b to r18, I'm experiencing a significant performance regression with `ndk-build` when doing even `ndk-build clean` (or a anything else).  One example:

`ndk-build -j16 clean` time for r16b: 0m1.070s
`ndk-build -j16 clean` time for r18: **1m21.414s**

Yes, that's an increase of 80 seconds. :)  This project only takes 70 seconds to compile in r16b.

The time is all spent executing expressions inside the setup of `make`.  It appears that the changes for [`f99eb9f`](https://android.googlesource.com/platform/ndk.git/+/f99eb9f1751dd85ff15a6f960bec7cb89aac3273^!/#F2) (JSON Compilation Database support) are the source of the problem, even though I am taking no actions to enable or use this feature.

It seems that `make` is spending a lot of time executing the highly recursive (and probably slow) `generate-list-file` sequence for thousands of targets.  By simply commenting out three lines in `definitions.mk`, the performance regression disappears (and the build seems to work):

https://android.googlesource.com/platform/ndk.git/+/ndk-release-r18/build/core/definitions.mk#1509
https://android.googlesource.com/platform/ndk.git/+/ndk-release-r18/build/core/definitions.mk#1526
https://android.googlesource.com/platform/ndk.git/+/ndk-release-r18/build/core/definitions.mk#1527

`ndk-build -j16 clean` time for r18 with these lines commented out: 0m1.288s

The first commented-out line is the most important and gives the largest benefit.  Perhaps this feature and thus these expansions can, at the very least, be enabled only when the JSON Compilation Database is requested?

#### Environment Details

* NDK Version: 18.0.5002713
* Build system: ndk-build
* Host OS: Linux x86_64 Debian Stretch
* Compiler: clang
* ABI: android-19
* STL: libc++

**Comment by DanAlbert** [comment]
Putting this in the r19 bucket for now. If we end up making an r18b this will be in it.

**Comment by DanAlbert** [comment]
Nothing else has come in yet, but I think this probably justifies it on its own.

**Comment by DanAlbert** [comment]
Managed to make `generate-list-file` quite a bit faster. Would you mind applying [this patch](https://android-review.googlesource.com/c/platform/ndk/+/776226) to your NDK to see how much it helps? I think we probably should still only use the list files when `LOCAL_SHORT_COMMANDS` is set, but if the performance cost is now negligible I'd rather keep everyone on the same code path.

**Comment by b-spencer** [comment]
Hmm.  It's better, but unfortunately, it's still slow enough to be frustrating in a edit-compile cycle.  

For the same project, it now takes ~9 seconds to clean, almost all of which is spent in the startup time:

```
r16b:
  real    0m1.046s

r18 orig: 
  real    1m25.578s
  real    1m20.962s

r18 my commented-out hack:
  real    0m1.291s
  real    0m1.311s

r18 upstream patch:
  real    0m9.064s
  real    0m9.083s
```

Commenting out the `generate-list-file` call right before the `_JSON_INTERMEDIATE` target still shaves the time down to only twice as long as r16.  Cutting the number of objects in play (such as by removing one of the ABI targets, for example) also cuts the time, of course.

BTW, I was able to measure that `generate-list-file` is being evaluated 2748 times (once per `.o`) in this project when running `ndk-build clean`.

(Another large project I tried it on takes ~6.2 seconds to clean with r18 plus this patch vs. ~2.0 seconds with r16b.)

**Comment by b-spencer** [comment]
I just tried this out on a minimal ndk-build project that just compiles 3000 zero-byte `.cc` files into an executable and it exhibits the same kind of relative timings.  I'm definitely happy to help out, but perhaps making a project like that would let you get a good feel for the speed without waiting for me . :)

**Comment by DanAlbert** [comment]
That's what I figured, but thanks for confirming. I'll continue in to making sure we don't use these code paths unless necessary then.

**Comment by DanAlbert** [comment]
Okay, here's the second round of improvements: https://android-review.googlesource.com/c/platform/ndk/+/777020

With that, a project with 3000 empty source files (12000 object files total) it takes 6 seconds to do a no-op clean instead of 2 like it would in r17. If the user sets `LOCAL_SHORT_COMMANDS=true` it takes 30 seconds compared to 2m10s for r17b (that first patch really paid off, apparently).

I'm not sure if we can do better without changing the interface. The only way to get more time back would be to check if the compilation database was requested and avoid generating the rules entirely if it wasn't. This is indicated by either building the `compile_commands.json` goal or setting `$(GEN_COMPILE_COMMANDS_DB)` to true. We can detect if the user explicitly requests the former on the command line with `$(MAKECMDGOALS)`, but I don't know off the top of my head how to detect something like the following:

```makefile
# Android.mk snippet
my-custom-goal: compile_commands.json
```

```bash
$ ndk-build my-custom-goal
```

I'll give it some more thought.

**Comment by DanAlbert** [comment]
(one option would of course be documenting that unlikely case and just requiring that anyone with such a rule handles it by flipping `GEN_COMPILE_COMMANDS_DB` to true if they see `my-custom-goal` in `MAKECMDGOALS`, and that might be good enough)

**Comment by b-spencer** [comment]
👍  With both yesterday's and today's patches applied, r18 is showing good speeds on the same project:

```
r18 + both patches:
  real    0m1.552s
  real    0m1.733s
```

As for the `my-custom-goal` question, you might consider making the `compile_commands.json` target have a conditional definition.  When it's not a command-line target and `GEN_COMPILE_COMMANDS_DB` isn't defined, it could fail and print a message that says "Please define GEN_COMPILE_COMMANDS_DB` before depending on `compile_commands.json`" or something like that.

**Comment by DanAlbert** [comment]
Oh, so what we have now is actually more or less equivalent to r17 for a less contrived project. That's better than I thought. I suppose an extra half a second might still be worth trying to win back though?

I think for the moment it's time to stop fiddling with it to keep the risk down for r18b, but that could be an improvement for r19.

**Comment by DanAlbert** [comment]
The two big fixes are in the r18 branch now. Filed https://github.com/android-ndk/ndk/issues/808 to track post-r18 work.

**Comment by DanAlbert** [comment]
Managed to speed things up more (about 2x) now that we have Make 4: https://android-review.googlesource.com/c/platform/ndk/+/1118751. It looks like we've also improved since r18b from other changes (presumably just by updating to a newer version of make?).
