### ISSUE TITLE
clang __thread caused linker error

### ISSUE THREAD

**Issue by arseny30** [android-ndk/ndk#8]
ndk r11
APP_STL := c++_static
NDK_TOOLCHAIN_VERSION := clang

Trying to build shared library from single line file:
x.cpp:
`__thread const char *x = "";`
Got:
``` 
/Users/arseny30/ndk/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/lib/gcc/arm-linux-androideabi/4.9/../../../../arm-linux-androideabi/bin/ld: warning: shared library text segment is not shareable
/Users/arseny30/ndk/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/lib/gcc/arm-linux-androideabi/4.9/../../../../arm-linux-androideabi/bin/ld: error: treating warnings as errors
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
```

Everything is OK, when I replace the line with:
`__thread const char *x = nullptr;`

**Comment by DanAlbert** [comment]
@chih-hung, at first glance I would guess this is something in clang? Any known issues that were fixed very recently? r11 has clang version 3.8.243773

**Comment by stephenhines** [comment]
Yes, the final patches for emutls are only in a clang that I updated yesterday for AOSP (still labeled 3.8.256229, but from build ID 2658975 instead).

**Comment by DanAlbert** [comment]
Ahh damn. I shouldn't have called out `__thread`in the changelog then :( I thought we had all the fixes.

> still labeled 3.8.256229, but from build ID 2658975 instead

Is it actually still the same revision, or did we miss updating the config for the build? I'm wondering about impact of pulling in the new build. If it's small I'll do it for r11b, if not I'll just fix the changelog and we'll do this for r12.

**Comment by stephenhines** [comment]
It's a merge + a handful of cherry-picks for emutls, long double, and "krait". We don't update the "merge" CL ID when we do these cherry-picks, as it would be pretty misleading. I need a better strategy though for labeling these as 256229A, etc., instead. That said, r11 only has r243773, so you are missing quite a lot of changes because of the actual merge.

**Comment by DanAlbert** [comment]
Talked to @stephenhines, there was another patch that was needed to get this fully enabled that we didn't get in the NDK (wasn't available to us until a week or two ago, at which point I didn't want to rev the compiler again).

I'll fix the changelog, and get the feature out in r12.

**Comment by DanAlbert** [comment]
(closing because this is fixed in master)
