### ISSUE TITLE
[doc] Where to find the list of flags to compile a simple C++ program

### ISSUE THREAD

**Issue by theodelrieu** [android-ndk/ndk#800]
Hello,

I've been struggling for two days on this.

I'm using Conan to cross-compile lots of libraries for Android, and with `r16` I managed to make it work by using standalone toolchains (which are quite packagers-friendly).

However with the latest version (`r18`) I've been banging my head on walls.

The standalone toolchain breaks some CMake detection scripts (`Determine-Compiler-Standalone.cmake`, `Android-Determine.cmake`), so I tried the other way: Using the NDK directly.

I would like to know the minimal required compiler/linker flags that I need to set in order to find every library/header/binary object (like `crtend.o`, etc...).

Thank you.

**Comment by DanAlbert** [comment]
Use our CMake toolchain file? It's at `$NDK/build/cmake/android.toolchain.cmake`. Standalone toolchains are not intended to be used with CMake, that's what the toolchain file is for.

**Comment by theodelrieu** [comment]
I remember I tried to use that as well, I'll try again on monday and post the results.

**Comment by DanAlbert** [comment]
SGTM. If that's not working then we'll reopen this.

**Comment by theodelrieu** [comment]
Hello, I managed to make it work with the following cmake code:

```cmake
set(CMAKE_MODULE_PATH "${CMAKE_CURRENT_LIST_DIR}/build/cmake;${CMAKE_MODULE_PATH}")

set(ANDROID_NATIVE_API_LEVEL "21")
set(ANDROID_ABI arm64-v8a)
include(android.toolchain)
```

Now, I have to see what compiler/linker flags CMake sets, thanks for your help!

**Comment by DanAlbert** [comment]
Just FYI, using the toolchain file that way is not the usual timing for it to be loaded. It may behave unexpectedly. I'd recommend using `-DCMAKE_TOOLCHAIN_FILE` instead.

**Comment by theodelrieu** [comment]
I forgot to mention that I use the snippet I posted as a CMake Toolchain File itself.

**Comment by DanAlbert** [comment]
Ah, okay. That should be fine then.
