### ISSUE TITLE
Has GCC really been removed from r18?

### ISSUE THREAD

**Issue by juha-h** [android-ndk/ndk#802]
Changelog r18 https://github.com/android-ndk/ndk/wiki/Changelog-r18 tells that "GCC has been removed".  I just downloaded r18 and it still has ./toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64/lib/gcc.  What does the changelog entry really mean?

**Comment by DanAlbert** [comment]
Exactly what it says. GCC of not a part of the NDK.

**Comment by enh** [comment]
but note that there are still `gcc` and `g++` wrapper scripts which redirect to clang, plus we still use GNU binutils which means a few hard-coded `gcc`s in paths (like this one for the directory where stuff like `crtbegin.o` lives).

so, yeah, GCC itself is gone, but the _word_ 'gcc' might still be around for a while yet.

**Comment by juha-h** [comment]
Elliott Hughes writes:

> but note that there are still `gcc` and `g++` wrapper scripts which
> redirect to clang, plus we still use GNU binutils which means a few
> hard-coded `gcc`s in paths (like this one for the directory where
> stuff like `crtbegin.o` lives). 
> 
> so, yeah, GCC itself is gone, but the _word_ 'gcc' might still be
> around for a while yet.

Thanks for the explanation,
