### ISSUE TITLE
make_standalone_toolchain.py produces broken gcc wrapper scripts

### ISSUE THREAD

**Issue by abustany** [android-ndk/ndk#803]
#### Description

It seems that GCC binaries are now stubbed by shell scripts that invoke Clang instead. The way the Clang binary is located breaks when those binaries are copied out of the NDK tree by `make_standalone_toolchain.py`.

Test case:
1. `/place/to/android-ndk-r18/build/tools/make_standalone_toolchain.py --api 27 --arch arm64 --install-dir arm64`
1. `./arm64/bin/aarch64-linux-android-gcc`

This prints en error because the `clang` binary cannot be found.

#### Environment Details

Not all of these will be relevant to every bug, but please provide as much
information as you can.

* NDK Version: 18.0.5002713
* Build system: none
* Host OS: Linux 4.18.9-200.fc28.x86_64
* Compiler: Clang via GCC stubs
* ABI: arm64

**Comment by DanAlbert** [comment]
https://android-review.googlesource.com/c/platform/ndk/+/778917
