### ISSUE TITLE
clang do not provide __ANDROID__ macro

### ISSUE THREAD

**Issue by misery** [android-ndk/ndk#807]
We use cmake to generate moc_predefs.h for Qt5 and his moc binary.

Since we switched to clang compiler we see that it does not provide ```__ANDROID__``` anymore.

```
$ /opt/android-ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++ -dM -E -c /usr/share/cmake-3.12/Modules/CMakeCXXCompilerABI.cpp

[...]
```

```
$ /opt/android-ndk/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64/bin/aarch64-linux-android-g++ -dM -E -c /usr/share/cmake-3.12/Modules/CMakeCXXCompilerABI.cpp

[...]
#define __ANDROID__ 1
```

Is this a bug? The moc binary of Qt5 cannot detect Android anymore.

**Comment by DanAlbert** [comment]
You're not targeting Android. You have to tell Clang your target with `--target`.

You might want to use a [standalone toolchain](https://developer.android.com/ndk/guides/standalone_toolchain) so you don't have to worry about the details.
