### ISSUE TITLE
NDK r12 lost std::mutex

### ISSUE THREAD

**Issue by alexcohn** [android-ndk/ndk#81]
Upgraded to r12, and got errors like `'mutex' in namespace 'std' does not name a type`. After using the workaround suggested by [James Swift](https://groups.google.com/d/msg/android-ndk/ImGINcMuzdU/zj2z45QsBQAJ), I get `undefined reference to 'std::condition_variable::notify_one()'`.

Using **gnustl_static**, NDK_TOOLCHAIN=**x86-4.9**.

Same library compiles clean with r11.

**Comment by DanAlbert** [comment]
FYI I have an internal bug open tracking this. It's part of the fallout from synchronizing our GCC with chromeos (solved a bunch of bugs, caused a few more). The detection for `_GLIBCXX_HAS_GTHREADS` apparently got hacked into place in the NDK a long time ago and we lost the hack in the sync.

**Comment by chaoren** [comment]
Looks like `std::thread` is also missing.

```
$ ~/Android/toolchains/arm/bin/arm-linux-androideabi-clang++ -std=c++11 test.cpp
test.cpp:11:7: error: no member named 'this_thread' in namespace 'std'
        std::this_thread::get_id();
        ~~~~~^
test.cpp:12:7: error: no type named 'mutex' in namespace 'std'
        std::mutex m;
        ~~~~~^
test.cpp:13:7: error: no type named 'thread' in namespace 'std'
        std::thread t;
        ~~~~~^
```

**Comment by DanAlbert** [comment]
Yes, everything thread related is probably missing. `_GLIBCXX_HAS_GTHREADS` isn't getting defined.

(FYI, internal bug is http://b/27433401)

**Comment by DanAlbert** [comment]
https://android-review.googlesource.com/#/c/219744/
