### ISSUE TITLE
NDKr18 is not working on Red Hat 7.4

### ISSUE THREAD

**Issue by bog-dan-ro** [android-ndk/ndk#810]
As the summary says, the latest NDKs don't work **anymore** on RH 7.4.

Qt is using RH 7.4 to build Android (and linux) Qt SDK. The latest NDK which we could use in RH 7.4 was r16 (IIRC).

It will be great if you'll compile the NDK using an older Linux distribution which is compatible with RH 7.4, it will enable us to ship bins compiled with latest NDK which it's clang compiler seems to produce smaller and faster bins than the one from r16.

**Comment by DanAlbert** [comment]
What doesn't work?

**Comment by liangqi** [comment]
Looks like I managed to build qtbase(5.12) libs with r18 on RH 7.4, so assume it got fixed already. Thanks.

**Comment by bog-dan-ro** [comment]
@DanAlbert you can close it. If you still want to know what happened, here https://bugreports.qt.io/browse/QTBUG-47672 you can find the entire discussion.

**Comment by DanAlbert** [comment]
Definitely worth checking the latest NDK whenever you encounter a bug.
