### ISSUE TITLE
Docs: ANDROID_ARM_NEON

### ISSUE THREAD

**Issue by Zingam** [android-ndk/ndk#813]
The change log states that "ndk-build and CMake now default to using NEON for ARM when targeting android-23 (Marshmallow) or newer."
https://github.com/android-ndk/ndk/wiki/Changelog-r18
The docs [here ](https://developer.android.com/ndk/guides/cmake) state
ANDROID_ARM_NEON FALSE (default)
Shouldn't that discrepancy be clarified?

**Comment by enh** [comment]
you might have to hit reload, but this should be fixed now.

(at some point we need to find the time to go through all of these and check that they're still accurate, but in the meantime please file bugs for any more mistakes you find.)

**Comment by DanAlbert** [comment]
Look at the build log. Look for `-mfpu=neon`

**Comment by DanAlbert** [comment]
Correct. If you're not using our toolchain file none of this will be handled for you. Enabling NEON by default for Clang regardless of build system won't happen until r20.
