### ISSUE TITLE
android-ndk-r17b compile issue

### ISSUE THREAD

**Issue by kusumakara** [android-ndk/ndk#814]
While compiling Android ndk
ERROR:

/toolchains/arm-linux-androideabi-4.9/prebuilt/windows-x86_64/bin/../l
-linux-androideabi/4.9.x/liblto_plugin-0.dll: could not load plugin library: The param
ect.

**Comment by DanAlbert** [comment]
You'll need to provide a test case that fails with r18. We don't have enough information to know what went wrong here, and NDK r17 is no longer supported.

**Comment by kusumakara** [comment]
please suggest latest stable version of ndk with API level 23 support

**Comment by DanAlbert** [comment]
r18. The latest version is always the version we believe to be the most stable. We wouldn't ship it if we thought otherwise.

**Comment by enh** [comment]
you can always find the latest answer to that question by looking at https://github.com/android-ndk/ndk/wiki which shows what's coming next, what's current, and even see historical releases.
