### ISSUE TITLE
Crash when exception is thrown

### ISSUE THREAD

**Issue by asdadada** [android-ndk/ndk#826]
I have a crash when any exception is thrown.
The project build by ndk_build ! .
The Application.mk contain APP_CPPFLAGS := -frtti -fexceptions

here is the call stack:

 	libc.so!tgkill()	
 	libc.so!pthread_kill()	
 	libc.so!raise()	
 	libc.so!__libc_android_abort()	
 	libc.so!abort()	
 	libc.so!__libc_fatal()	
 	libc.so!__assert2()	
 	get_shim_type_info()	C++ (gdb)
 	__cxxabiv1::scan_eh_tab()	C++ (gdb)
 	__gxx_personality_v0()	C++ (gdb)
 	unwind_phase1()	C++ (gdb)
 	_Unwind_RaiseException()	C++ (gdb)
 	__cxa_throw()	C++ (gdb)
	CGroupLayerData::SetProperty()	C++ (gdb)

we didn't tried to compile it with latest NDK 
because the project is very large and it is take us a lot of efforts to do this.
I saw some threads in this forum that talk about this issue , but I didn't saw
any solution for this.
we will be happy for your help.
Thanks !

* NDK Version: 10d and 11c
 Host OS: Windows, 
 Compiler: Clang 
 ABI: armeabi-v7a
 STL: c++_shared
 NDK API level: android-14

**Comment by DanAlbert** [comment]
The fix is almost certainly upgrading you're NDK. If you search this bug tracker you'll see that we fixed a handful of libc++ exception handling issues in later NDKs.
