### ISSUE TITLE
libstdc++ and c++_shared

### ISSUE THREAD

**Issue by asdadada** [android-ndk/ndk#827]
Hello.

I a little bit confused about the c++ run time libraries that
I see when I execute readelf on my .so that created by ndk_build.
when I used  APP_STL := c++_shared
I expected to see, according to the document help, the following dependency:
libc++.so
libc++_shared.so

but what I actually see is:

libstdc++.so
libc++_shared.so

is the libstdc++.so can be together with  libc++_shared ?

* NDK Version: r11c
 Host OS: Windows, 
 Compiler: Clang 
 ABI: armeabi-v7a
 STL: c++_shared
 NDK API level: android-14

**Comment by DanAlbert** [comment]
Update your NDK and you won't see libstdc++ being linked.
