### ISSUE TITLE
C++ 17 support in NDK r18b

### ISSUE THREAD

**Issue by Slion** [android-ndk/ndk#828]
#### Description

According to the [docs](https://developer.android.com/ndk/guides/cpp-support) the latest NDK supports C++ 17. However if I set CMAKE_CXX_STANDARD to 17 I get cmake errors when trying to add_library.

Moreover I'm not sure why header files like <experimental/string_view> were left in place and simply contain a precompiler error statement. It seems like a bad idea as it breaks usage of __has_include(<experimental/string_view>) for instance.

#### Environment Details

Android Studio 3.2.1 on Windows 10.

**Comment by DanAlbert** [comment]
> However if I set CMAKE_CXX_STANDARD to 17 I get cmake errors when trying to add_library.

What errors? If you're using an old enough version of CMake (3.6 has this problem, idk when it was fixed) then CMake doesn't know C++17 exists. That's not an NDK issue.

If you're seeing something else, you'll have to be more specific.

> Moreover I'm not sure why header files like <experimental/string_view> were left in place and simply contain a precompiler error statement. It seems like a bad idea as it breaks usage of __has_include(<experimental/string_view>) for instance.

This is a third-party library. You'll have to ask the LLVM folks if you want this to change. I don't suspect they will change it though, since having that file there helps people migrate their code from earlier stdlib versions. Your check works fine if it's written as:

```c++
#if __has_include(<string_view>)
#include <string_view>
#elif __has_include(<experimental/string_view>)
#include <experimental/string_view>
#else
#error No string_view implementation available!
#endif
```

**Comment by Slion** [comment]
> What errors?

The error description was not shown in the Android Studio output window.

> If you're using an old enough version of CMake (3.6 has this problem, idk when it was fixed) then CMake doesn't know C++17 exists. That's not an NDK issue.

I'm using whatever CMake version Android Studio is using. I do believe it is stuck on 3.6.0 for some reason. Strictly speaking it is not an NDK issue I guess but still it would be nice if the NDK could work with Android Studio, not?

I'm off searching for a solution to have Android Studio use a newer version of CMake.
Thanks for the quick answer, much appreciated.

**Comment by Slion** [comment]
There was a few things needed for me to able to compile using C++ 17 from Android Studio:

- Android local.properites should contain the path to the cmake binaries: cmake.dir="C\:\\Program Files\\CMake"
- Download ninja.exe and copy it next to cmake.exe, don't ask
- set(CMAKE_CXX_STANDARD 17)

**Comment by DanAlbert** [comment]
> Strictly speaking it is not an NDK issue I guess but still it would be nice if the NDK could work with Android Studio, not?

The NDK doesn't play any part in that issue. The same thing happens on every other platform. The problem is entirely contained within CMake.

**Comment by Slion** [comment]
> The problem is entirely contained within CMake.
... and Android Studio for sticking to an ancient CMake version. We ought to tell the Android Studio guys to update their CMake.

**Comment by DanAlbert** [comment]
They did (or perhaps they are? I'm not sure about the status of the release but I know they're working in 3.10)

**Comment by enh** [comment]
cmake 3.12 is currently planned for Studio 3.3 (according to https://issuetracker.google.com/111569282).

**Comment by DanAlbert** [comment]
btw (commenting in both places for anyone landing here first), updating CMake is not the only way to use C++17; it's just the only way to do it idiomatically in CMake. You can also do:

```cmake
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++17")
```

**Comment by jeremyong** [comment]
Doh found this issue. When I looked at the android toolchain file, sure enough, it *hardcodes* C++11 as the standard in the cxx flags with an utter disregard for what the toolchain user wanted.

As a user, my life would be a lot nicer if the toolchain providers realized that nobody is building for android exclusively, and I'd pretty a better experience for building android apps without Android Studio in the picture at all.

Forcing things like setting CMAKE_CXX_FLAGS globally is a huge anti-pattern. What if I need certain modules compiled with a different set of flags? Modern cmake projects generally forbid this (correctly).

**Comment by DanAlbert** [comment]
> Doh found this issue. When I looked at the android toolchain file, sure enough, it hardcodes C++11 as the standard in the cxx flags with an utter disregard for what the toolchain user wanted.

No, it doesn't. It only provides a default. The user's choice takes priority.

```cmake
cmake_minimum_required(VERSION 3.6.0)

set(CMAKE_CXX_STANDARD 14)
add_executable(foo foo.cpp)
```

The compilation command when built (note the order of the two `-std` flags):

> [1/2] /usr/local/google/home/danalbert/src/ndk/out/linux/android-ndk-r20-canary/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++  --target=armv7-none-linux-androideabi16 --gcc-toolchain=/usr/local/google/home/danalbert/src/ndk/out/linux/android-ndk-r20-canary/toolchains/llvm/prebuilt/linux-x86_64    --sysroot /usr/local/google/home/danalbert/src/ndk/out/linux/android-ndk-r20-canary/toolchains/llvm/prebuilt/linux-x86_64/sysroot -g -DANDROID -fdata-sections -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -mfpu=vfpv3-d16 -mthumb -Wa,--noexecstack -Wformat -Werror=format-security -stdlib=libc++ **-std=c++11**  -fPIE   -**std=gnu++14** -MD -MT CMakeFiles/foo.dir/foo.cpp.o -MF CMakeFiles/foo.dir/foo.cpp.o.d -o CMakeFiles/foo.dir/foo.cpp.o -c /usr/local/google/home/danalbert/src/ndk/ndk/foo/foo.cpp

If you're seeing different behavior then open a bug.

**Comment by jeremyong** [comment]
You're right, the issue was actually that `CMAKE_CXX_STANDARD 17` is unrecognized by cmake 3.6. Thanks for clarifying.

**Comment by zwcloud** [comment]
What if I'm using a custom CMake version?

**local.properties**
```
cmake.dir=C\:/Program Files/CMake
```
`C:/Program Files/CMake` is of version 3.15 and it knows C++ 17.

**Comment by DanAlbert** [comment]
Then you can use either.

**Comment by alexcohn** [comment]
> What if I'm using a custom CMake version?
> `C:/Program Files/CMake` is of version 3.15 and it knows C++ 17.

But, see https://github.com/android-ndk/ndk/issues/1049

**Comment by prprDog** [comment]
> btw (commenting in both places for anyone landing here first), updating CMake is not the only way to use C++17; it's just the only way to do it idiomatically in CMake. You can also do:
> 
> ```cmake
> set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++17")
> ```

thx  a lot
