### ISSUE TITLE
In the presence of `noexcept`, clang generates code which crashes

### ISSUE THREAD

**Issue by MaxKellermann** [android-ndk/ndk#831]
#### Description

My Android app (org.musicpd) crashes a lot recently, triggering `std::terminate()` for no apparent reason. I found out that this always happens inside `noexcept` or `__attribute__((pure))` functions, which of course are not allowed to throw; however, those functions have a catch-all exception handler, and no exception can ever leak. For example this one: https://github.com/MusicPlayerDaemon/MPD/blob/master/src/db/update/UpdateIO.cxx#L34-L42

I was able to come up with a very small C++ source which reproduces the problem:

```
/*
  Compile with:

  $NDK/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++ -I/usr/src/stable-mpd/android64/lib/aarch64-linux-android/root/include    --sysroot=$NDK/sysroot -isystem /usr/src/stable-mpd/android64/lib/aarch64-linux-android/root/include -isystem $NDK/sysroot/usr/include/aarch64-linux-android -D__ANDROID_API__=21 -target aarch64-none-linux-android -gcc-toolchain $NDK/toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64 -isystem $NDK/sources/cxx-stl/llvm-libc++/include -isystem $NDK/sources/android/support/include -L$NDK/sources/cxx-stl/llvm-libc++/libs/arm64-v8a    -L$NDK/platforms/android-21/arch-arm64/usr/lib -B$NDK/platforms/android-21/arch-arm64/usr/lib -o clang_noexcept_bug clang_noexcept_bug.cxx  -lc++_static -lc++abi

  adb push clang_noexcept_bug /data/local/tmp/
  adb shell /data/local/tmp/clang_noexcept_bug

  Results in: "terminating with uncaught exception of type int"
 */

static void Foo() noexcept {
	try {
		throw 1;
	} catch (...) {
		/* catch-all discards the exception, and no exception
		   will leak from this function */
	}
}

static void Bar() {
	try {
		throw 2;
	} catch (...) {
	}
}

int main()
{
	Foo();

	/* uncommenting the Bar() call stops the program from
	   crashing */
	//Bar();
}
```

With very limited knowledge about how C++ exception handling is implemented at the lowest level, I found it suspicious that there is only a `.debug_frame` section in the above binary, which gets renamed to `.eh_frame` when I uncomment the `Bar()` call.

#### Environment Details

* NDK Version: r18b
* Build system: custom
* Host OS: Debian Buster
* Compiler: clang from NDK r18b
* ABI: aarch64
* STL: libc++_static
* NDK API level: 21
* Device API level: 28

**Comment by rprichard** [comment]
This looks like a Clang bug. I'll file something upstream.

The problem affects Clang on Linux too. It affects 32-bit x86 and arm64 by default, but it also affects x86-64 if I build with `-fno-unwind-tables`.

Building with `-funwind-tables` looks like a workaround, because it forces the compiler to output `.eh_frame` instead of just `.debug_frame`. `.eh_frame` is allocated on the target and is available to the unwinder, but `.debug_frame` isn't.

**Comment by stephenhines** [comment]
I think that cferris reported seeing similar missing .eh_frame sections on x86 in some cases recently. This is most likely the same issue. Yi's next update to r344140 will include this patch.

**Comment by MaxKellermann** [comment]
Thanks @rprichard, indeed `-funwind-tables` successfully works around the bug.

**Comment by DanAlbert** [comment]
Doesn't crash with r20.
