### ISSUE TITLE
std::regex("[\\S ]*") does not work as expected

### ISSUE THREAD

**Issue by tobiasmaier** [android-ndk/ndk#834]
#### Description

The regular expression `\S` should match any non-whitespace character. This is working. But if we put it in a list it does not work any more.
Example: `[\S ]*` should match a sequence of any non-whitespace character and spaces.
But `std::regex_search("foo bar", match, std::regex("[\\S ]*"))` has an empty match.

If I compile the code for Linux using the same clang version the result is as expected and "foo bar" is matched.

Code to reproduce:
https://github.com/tobiasmaier/ndk-regex-repro

The expected output of the example would be:
```
matches \S*:
"foo"
matches \w*:
"foo"
matches [\S ]*:
"foo bar"
matches [\w ]*:
"foo bar"
```
the output of the android binary is:
```
matches \S*:
"foo"
matches \w*:
"foo"
matches [\S ]*:
""
matches [\w ]*:
"foo bar"
```
It is important to note that with an older NDK (17.1.4828580) this issue does not occur and the result is as expected.

#### Environment Details

* NDK Version: 18.1.5063045
* Build system: cmake
* Host OS: Linux
* Compiler: Clang 
* ABI: armeabi-v7a
* STL: c++_static
* NDK API level: 26
* Device API level: 26

**Comment by DanAlbert** [comment]
Looks like this is fixed by https://reviews.llvm.org/D50534. We're a little overdue for a libc++ update anyway.

(thanks for the solid repro case btw, that made this really easy to handle)

**Comment by DanAlbert** [comment]
Fixed in r19 beta 1.
