### ISSUE TITLE
libc++_shared.so missing in ROM

### ISSUE THREAD

**Issue by Murphy0571** [android-ndk/ndk#835]
#### Description

Hi guys,

I'm using NDK r18 and linking libc++_shared.so as the STL implementation for clang. 

APP_STL := c++_shared
NDK_TOOLCHAIN_VERSION=clang

However, from ROM's /system/lib or /vendor/lib or any other relevant directories, there is no such libc++_shared.so and only a libc++.so existing. Therefore naturally I had the error that libc++_shared.so couldn't be found.

Appreciate your support.

Br, Murphy

#### Environment Details

* NDK Version: r18
* Build system: ndk-build
* Host OS: Ubuntu 16.04
* Compiler: clang
* ABI: armeabi-v7a
* STL: c++_shared
* NDK API level: any
* Device API level: any

**Comment by amartinz** [comment]
you need to ship libc++_shared within your apk

**Comment by enh** [comment]
amartinz is corect. see the "note" at https://developer.android.com/ndk/guides/cpp-support#libc

i'll reorder that page to make it a bit more logical...
