### ISSUE TITLE
Cygwin compatibility with NDK standalone toolchains (make_standalone_toolchain.py vs. make-standalone-toolchain.sh)

### ISSUE THREAD

**Issue by osm0sis** [android-ndk/ndk#838]
Hi! Apologies for not following the issue guideline, but this crosses multiple NDK revisions (**r12** to **r18b**), and doesn't really fit cleanly into that format.

I noticed that since it's creation in **r12** the `make_standalone_toolchain.py` will fail to create a toolchain on Cygwin with Python installed, erroring with:
`Unsupported platform: CYGWIN_NT-10.0`

This seems a little harsh considering **r12b**'s `make-standalone-toolchain.sh` (the last before it was reworked into a wrapper for the .py) worked, and I've discovered can even be used with _--ndk-path_ pointed to a newer NDK revision to build a working Cygwin standalone for any NDK before the deprecated headers were dropped (so up to **r15c** since the original `make-standalone-toolchain.sh` lacks Unified header support, naturally).

I experimented further by generating a toolchain using Windows Python (i.e. non-Cygwin) with `make_standalone_toolchain.py`, and also another using Cygwin's Python with a modified `make_standalone_toolchain.py` (simply changed to give CYGWIN_NT-10.0 the _HOST_TAG=windows_ it used to have with `make-standalone-toolchain.sh`), but in both cases attempts to use the toolchain in Cygwin resulted in the following error:
```
G:/cygwin/home/Chris/busybox-1.29.3/scripts/gcc-version.sh: line 11: tail: command not found
<stdin>:1:0: fatal error: when writing output to : Invalid argument
compilation terminated.
```

I dumped the _$PATH_ within the toolchain (by editing the erroring gcc-version.sh) and it showed that it had become broken as:
`"G:\cygwin\home\Chris\x-tools\arm-linux-androideabi-r12b-api21\bin;G:\cygwin\usr\local\bin;G:\cygwin\bin;C:\Python27;C:\Python27\Scripts;C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0;C:\Program Files\Skype\Phone;C:\Program Files\NVIDIA Corporation\PhysX\Common;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0;C:\WINDOWS\System32\OpenSSH;C:\Users\Chris\AppData\Local\Microsoft\WindowsApps"`

instead of the expected/working:
`"/home/Chris/x-tools/arm-linux-androideabi-r12b-api21/bin:/usr/local/bin:/usr/bin:/cygdrive/c/Python27:/cygdrive/c/Python27/Scripts:/cygdrive/c/ProgramData/Oracle/Java/javapath:/cygdrive/c/WINDOWS/system32:/cygdrive/c/WINDOWS:/cygdrive/c/WINDOWS/System32/Wbem:/cygdrive/c/WINDOWS/System32/WindowsPowerShell/v1.0:/cygdrive/c/Program Files/Skype/Phone:/cygdrive/c/Program Files/NVIDIA Corporation/PhysX/Common:/cygdrive/c/WINDOWS/system32:/cygdrive/c/WINDOWS:/cygdrive/c/WINDOWS/System32/Wbem:/cygdrive/c/WINDOWS/System32/WindowsPowerShell/v1.0:/cygdrive/c/WINDOWS/System32/OpenSSH:/cygdrive/c/Users/Chris/AppData/Local/Microsoft/WindowsApps"`

Again, there doesn't seem to be a practical reason NDK standalone toolchains can't work on Cygwin anymore, since I've modified **r12b**'s `make-standalone-toolchain.sh` to accept _--unified-headers_ and it still makes a working toolchain with working _$PATH_ (attachment): [make-standalone-toolchain-r12b-mod.zip](https://github.com/android-ndk/ndk/files/2570614/make-standalone-toolchain-r12b-mod.zip)

I'm not sure what's actually different in the generated toolchain when made by the .sh that makes them cooperate with the Cygwin _$PATH_ but this all suggests it could be easily resolved in the .py version. That said, I see on master branch that NDK **r19** is planning on having the _$ANDROID_NDK_ROOT_ itself function as a standalone toolchain directory, so I guess all I'm asking is please try to ensure that it works from Cygwin again when you do, since fixing `make_standalone_toolchain.py` or `make-standalone-toolchain.sh` upstream is likely a moot point for everybody.

Thank you for your consideration!
Chris

**Comment by DanAlbert** [comment]
I may be misunderstanding the use case here. The point of `make_standalone_toolchain.py` as opposed to `make-standalone-toolchain.sh` is that it doesn't require cygwin. It behaves as expected when using the stock Windows tools.

The NDK includes a Python distribution (`$NDK/prebuilt/$HOST_TAG/bin/python`) that can be used if your system's distribution is not compatible with any of our scripts.

> I dumped the $PATH within the toolchain (by editing the erroring gcc-version.sh)

This part has me confused as well. `gcc-version.sh` is not a part of the toolchain, it's a part of the project you're trying to build. The toolchain doesn't have a `PATH` at all. I don't know of any NDK release with a toolchain that modified the user's `PATH`.

> I'm asking is please try to ensure that [the toolchain] works from Cygwin again when you do

AIUI this is mostly up to the tools that make use of the toolchain. None of the NDK tools are built against Cygwin (nor will they be, as this amounts to supporting an entirely new OS). This means that the following disclaimer applies (taken from our [standalone toolchain](https://developer.android.com/ndk/guides/standalone_toolchain#windows_support) docs):

> The Windows binaries do not depend on Cygwin. This lack of dependency makes them faster. The cost, however, is that they do not understand Cygwin path specifications like cygdrive/c/foo/bar, as opposed to C:/foo/bar.

Aside from that caveat, we do intend to keep NDK tooling working with Cygwin. We do rely on user feedback to let us know when things go wrong because it is not a tested configuration, but we're happy to make fixes when they're reported. This should fix at least part of your issue: https://android-review.googlesource.com/c/platform/ndk/+/820360 (waiting for a Windows VM to spin up to test it; lmk if you beat me to it).

**Comment by osm0sis** [comment]
Hi Dan! Thanks for the patch and thanks for getting back to me. Sorry if that wasn't entirely clear! I'll try to explain a bit better.

I found the general cause of the issues with the NDK toolchains on Cygwin from my test case, which is a busybox cross-compile to ARM under Cygwin, by editing that `gcc-version.sh` from busybox to dump the `PATH` during the compile. I also agree it doesn't entirely make sense, since I didn't think the toolchain would modify the `PATH` like that, but the tests seem to show something like that is occurring on Cygwin with Windows NDK toolchains created from `make_standalone_toolchain.py` since it's conception.

I absolutely agree it's great that `make_standalone_toolchain.py` doesn't rely on Cygwin or Cygwin's Python, but what I was trying to explain was that somehow when a toolchain is generated with `make_standalone_toolchain.py` it seems somehow when using the toolchain that the operative `PATH` always becomes translated to the Windows version above ("G:\" etc.), whereas when the same toolchain is generated with `make-standalone-toolchain.sh` (non-wrapper version) that the operative `PATH` remains intact.

I've tested the proposed .py patch and it does allow it to run on Cygwin (thanks again!), but in practice, the generated toolchain still somehow results in the same issue with `PATH` as before.

The crucial thing is that using NDK r12b, which is the last revision with both `make_standalone_toolchain.py` and the fully-functional (non-wrapper) `make-standalone-toolchain.sh`, I can generate the same toolchain with both methods and only the .sh version works in Cygwin due to the `PATH` issue. What I was trying to explain above is that with my modified .sh it seems I can continue to do so, even with newer NDK revisions, so hopefully the .py could be fixed as well going forward.

Thank you again for your time and consideration,
Chris

**Comment by DanAlbert** [comment]
> it seems somehow when using the toolchain that the operative PATH always becomes translated to the Windows version above ("G:" etc.), whereas when the same toolchain is generated with make-standalone-toolchain.sh (non-wrapper version) that the operative PATH remains intact.

I don't understand how this could happen. The toolchain plays no part in the execution of a shell script.

**Comment by osm0sis** [comment]
I don't understand it either, but the practical application seems to prove otherwise.

**Comment by osm0sis** [comment]
Hi Dan, I understand the issue now! I ran a `diff -r` between the .sh toolchain and .py toolchain generated by **r12b** (with your Cygwin patch), and found the following:

> Only in arm-linux-androideabi-r12b-api21-py: AndroidVersion.txt
> Only in arm-linux-androideabi-r12b-api21-py/bin: 2to3
> Only in arm-linux-androideabi-r12b-api21-py/bin: arm64-v8a
> Only in arm-linux-androideabi-r12b-api21-py/bin: armeabi
> Only in arm-linux-androideabi-r12b-api21-py/bin: armeabi-v7a
> Only in arm-linux-androideabi-r12b-api21-py/bin: armeabi-v7a-hard
> Only in arm-linux-androideabi-r12b-api21-py/bin: arm-linux-androideabi-clang
> Only in arm-linux-androideabi-r12b-api21-py/bin: arm-linux-androideabi-clang.cmd
> Only in arm-linux-androideabi-r12b-api21-py/bin: arm-linux-androideabi-clang++
> Only in arm-linux-androideabi-r12b-api21-py/bin: arm-linux-androideabi-clang++.cmd
> Only in arm-linux-androideabi-r12b-api21-py/bin: asan_device_setup
> Only in arm-linux-androideabi-r12b-api21-py/bin: awk.exe
> Only in arm-linux-androideabi-r12b-api21-py/bin: clang
> Only in arm-linux-androideabi-r12b-api21-py/bin: clang.cmd
> Only in arm-linux-androideabi-r12b-api21-py/bin: clang_32.exe
> Only in arm-linux-androideabi-r12b-api21-py/bin: clang++
> Only in arm-linux-androideabi-r12b-api21-py/bin: clang++.cmd
> Only in arm-linux-androideabi-r12b-api21-py/bin: clang38.exe
> Only in arm-linux-androideabi-r12b-api21-py/bin: clang38++.exe
> Only in arm-linux-androideabi-r12b-api21-py/bin: clang-tidy.exe
> Only in arm-linux-androideabi-r12b-api21-py/bin: cmp.exe
> Only in arm-linux-androideabi-r12b-api21-py/bin: echo.exe
> Only in arm-linux-androideabi-r12b-api21-py/bin: gdb.exe
> Only in arm-linux-androideabi-r12b-api21-py/bin: gdb-orig.exe
> Only in arm-linux-androideabi-r12b-api21-py/bin: idle
> Only in arm-linux-androideabi-r12b-api21-py/bin: make.exe
> Only in arm-linux-androideabi-r12b-api21-py/bin: mips
> Only in arm-linux-androideabi-r12b-api21-py/bin: mips64
> Only in arm-linux-androideabi-r12b-api21-py/bin: ndk-depends.exe
> Only in arm-linux-androideabi-r12b-api21-py/bin: ndk-gdb
> Only in arm-linux-androideabi-r12b-api21-py/bin: ndk-gdb.cmd
> Only in arm-linux-androideabi-r12b-api21-py/bin: ndk-gdb.py
> Only in arm-linux-androideabi-r12b-api21-py/bin: ndk-stack.exe
> Only in arm-linux-androideabi-r12b-api21-py/bin: ndk-which
> Only in arm-linux-androideabi-r12b-api21-py/bin: pydoc
> Only in arm-linux-androideabi-r12b-api21-py/bin: python2.7-config
> Only in arm-linux-androideabi-r12b-api21-py/bin: python2-config
> Only in arm-linux-androideabi-r12b-api21-py/bin: python-config
> Only in arm-linux-androideabi-r12b-api21-py/bin: python-config.sh
> Only in arm-linux-androideabi-r12b-api21-py/bin: smtpd.py
> Only in arm-linux-androideabi-r12b-api21-py/bin: x86
> Only in arm-linux-androideabi-r12b-api21-py/bin: x86_64
> Only in arm-linux-androideabi-r12b-api21-py/bin: yasm.exe
> Only in arm-linux-androideabi-r12b-api21-py/lib: pkgconfig
> Only in arm-linux-androideabi-r12b-api21-py: lib64
> Only in arm-linux-androideabi-r12b-api21-py: MODULE_LICENSE_BSD_LIKE
> Only in arm-linux-androideabi-r12b-api21-py: MODULE_LICENSE_MIT

Then it occurred to me that the common Linux practice for cross-compiling of e.g. `export PATH="/home/ndk/arm-linux-androideabi-r12b-api21/bin:$PATH"` would of course cause Cygwin to use the standalone toolchain's make.exe instead of its own, which explains my first reported error:

```G:/cygwin/home/Chris/busybox-1.29.3/scripts/gcc-version.sh: line 11: tail: command not found
<stdin>:1:0: fatal error: when writing output to : Invalid argument
compilation terminated.
Makefile:992: *** multiple target patterns.  Stop.
```

So then using a **r16b** Python (with your Cygwin patch) generated toolchain, I made the following change: `arm-linux-androideabi-r16b-api21/bin/make.exe -> arm-linux-androideabi-r16b-api21/bin/ndk-make.exe`

And the busybox compile then performed as expected, at least until the linker phase:

```  LINK    busybox_unstripped
Trying libraries: m
  -Wl,--end-grouprt-group  -lm
Output of:
/home/Chris/x-tools/arm-linux-androideabi-r16b-api21/bin/arm-linux-androideabi-gcc -Wold-style-definition -DANDROID -D__ANDROID__ -D__ANDROID_API__=21 -DSK_RELEASE -Os -fno-short-enums -fgcse-after-reload -frename-registers -fno-builtin-stpcpy -fuse-ld=bfd -static -o busybox_unstripped -Wl,--sort-common -Wl,--sort-section,alignment -Wl,--gc-sections -Wl,--start-group applets/built-in.o archival/lib.a archival/libarchive/lib.a console-tools/lib.a coreutils/lib.a coreutils/libcoreutils/lib.a debianutils/lib.a klibc-utils/lib.a e2fsprogs/lib.a editors/lib.a findutils/lib.a init/lib.a libbb/lib.a libpwdgrp/lib.a loginutils/lib.a mailutils/lib.a miscutils/lib.a modutils/lib.a networking/lib.a networking/libiproute/lib.a networking/udhcp/lib.a printutils/lib.a procps/lib.a runit/lib.a selinux/lib.a shell/lib.a sysklogd/lib.a util-linux/lib.a util-linux/volume_id/lib.a archival/built-in.o archival/libarchive/built-in.o console-tools/built-in.o coreutils/built-in.o coreutils/libcoreutils/built-in.o debianutils/built-in.o klibc-utils/built-in.o e2fsprogs/built-in.o editors/built-in.o findutils/built-in.o init/built-in.o libbb/built-in.o libpwdgrp/built-in.o loginutils/built-in.o mailutils/built-in.o miscutils/built-in.o modutils/built-in.o networking/built-in.o networking/libiproute/built-in.o networking/udhcp/built-in.o printutils/built-in.o procps/built-in.o runit/built-in.o selinux/built-in.o shell/built-in.o sysklogd/built-in.o util-linux/built-in.o util-linux/volume_id/built-in.o -Wl,--end-group -Wl,--start-group -lm
==========
g:/cygwin/home/chris/x-tools/arm-linux-androideabi-r16b-api21/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld.bfd.exe: cannot find -lm
collect2.exe: error: ld returned 1 exit status
```

So then I guessed another .exe from the `PATH` must be interfering, so tried the following change: `arm-linux-androideabi-r16b-api21/bin/echo.exe -> arm-linux-androideabi-r16b-api21/bin/ndk-echo.exe`

And then the linker also worked! Looking at the old .sh I have no idea why the .sh wasn't copying over make.exe and echo.exe from the prebuilt NDK directories and the .py is, but that's the root of the issue!

Hopefully there's something the Python version can do to accommodate Cygwin better in the future, and/or the NDK-as-standalone setup in r19 will play more nicely! Thanks so much again for your time and consideration!

Chris

**Comment by DanAlbert** [comment]
Glad you were able to track it down. Like you say, r19 should have this cleaned up, so I don't think there's anything we need to do here. Closing.
