### ISSUE TITLE
Dead links in CONTRIBUTING.md

### ISSUE THREAD

**Issue by chaoren** [android-ndk/ndk#84]
> Follow the contribution instructions for AOSP. When you run repo init, follow the instructions in the NDK's [README.md](https://github.com/android-ndk/ndk/blob/master/README.md). We have a different set of dependencies than AOSP, also noted in our [README.md](https://github.com/android-ndk/ndk/blob/master/README.md).
>
> Instructions for building the NDK and running our tests are documented in [README.md](https://github.com/android-ndk/ndk/blob/master/README.md) and [Testing.md](https://github.com/android-ndk/ndk/blob/master/docs/Testing.md). Note that the NDK cannot be built on Windows; only Linux and Darwin hosts are supported.
>
> Check the [OWNERS file](https://github.com/android-ndk/ndk/blob/master/OWNERS) for reviewers.

**Comment by DanAlbert** [comment]
"Fixed". I need to see about getting gerrit to actually mirror this for us.
