### ISSUE TITLE
NDK 19-beta1 clang compiler version is incorrect in android.toolchain.cmake

### ISSUE THREAD

**Issue by birsoyo** [android-ndk/ndk#841]
It should be 8.0 not 7.0.
in android.toolchain.cmake it is forced to be 7.0:

    set(CMAKE_C_COMPILER_VERSION 7.0)
    set(CMAKE_CXX_COMPILER_VERSION 7.0)

While it is actually 8.0 

    > .\clang.exe --version
    Android (5058415 based on r339409) clang version 8.0.2

**Comment by DanAlbert** [comment]
Fixed for beta 2.
