### ISSUE TITLE
spell check framework ignores Locale and always uses English dictionary

### ISSUE THREAD

**Issue by eyalhoc** [android-ndk/ndk#845]
Locale locale = Locale.forLanguageTag("es");

TextServicesManager tsm = (TextServicesManager) getSystemService(TEXT_SERVICES_MANAGER_SERVICE);

SpellCheckerSession session = tsm.newSpellCheckerSession(null, locale, this, false);

**Comment by DanAlbert** [comment]
This is the NDK, not the SDK. You want http://b.android.com.
