### ISSUE TITLE
Android NDK LLVM compiler for SDM 845 HDK

### ISSUE THREAD

**Issue by shivkupps** [android-ndk/ndk#847]
Could you please share the appropriate android ndk where in we can compile lmbench for android based snapdragon sdm845 arm A75/A65 core?

It seems, the LLVM compiler as part of android ndk -r18b release doesn't support sdm 845 arm cortex A75/A55 core and we are getting "clang not supported linker error". We understand the LLVM compiler as part of android ndk -r18b is not compatible to A75/A55 cortex core of qualcomm snapdragon 845 HDK.

Could you please share the link to download the android ndk package which is compatible SDM 845 HDK?

Thanks

**Comment by DanAlbert** [comment]
> "clang not supported linker error"

What error? From what?
