### ISSUE TITLE
NDK 19-beta1: libvpx error: argument unused during compilation: '-stdlib=libc++'

### ISSUE THREAD

**Issue by aberaud** [android-ndk/ndk#849]
Error when configuring libvpx with NDK 19-beta1 with a standalone toolchain:

from `config.log`:
```
check_cflags -march=armv7-a -mfloat-abi=softfp
check_cc -Werror -march=armv7-a -mfloat-abi=softfp
BEGIN /tmp/vpx-conf-18897-6252.c
     1	int x;
END /tmp/vpx-conf-18897-6252.c
android-toolchain-19-arm/bin/arm-linux-androideabi-clang -Icontrib/arm-linux-androideabi/include -DNDEBUG=1 -O3 -march=armv7-a -mthumb -mfloat-abi=softfp -mfpu=vfpv3-d16 -DNDEBUG -fPIC -fno-integrated-as -fPIC -Werror -march=armv7-a -mfloat-abi=softfp -c -o /tmp/vpx-conf-18897-6252.o /tmp/vpx-conf-18897-6252.c
clang80: error: argument unused during compilation: '-stdlib=libc++' [-Werror,-Wunused-command-line-argument]

```

Removing `-stdlib=libc++` from forced flags at `make_standalone_toolchain.py:125` made it build.

**Comment by aberaud** [comment]
It also produces warnings when building other C projects.

Looks like this C++-specific flag shouldn't end up in CFLAGS or other non C++-specific flags.

**Comment by DanAlbert** [comment]
I've already solved this the right way upstream (changing Clang's default `-stdlib` for Android), but that doesn't help us for r19.

I think I probably do need to do something here. It's probably going to be a gross hack, but we shouldn't regress this behavior in r19 if it can be avoided.

**Comment by DanAlbert** [comment]
Actually this is super simple: https://android-review.googlesource.com/c/platform/ndk/+/836405

**Comment by DanAlbert** [comment]
Fixed for beta 2. Thanks for the report!

**Comment by DanAlbert** [comment]
Crap, only half of this was actually cherry-picked. Beta 2 was still broken an now so is stable. Will be a part of r19b.

**Comment by DanAlbert** [comment]
https://android-review.googlesource.com/c/platform/ndk/+/875216

**Comment by epicstar** [comment]
I noticed that r19 is out (stable) but this is still open. So did this make the r19 stable build, or will we have to wait for r19b? Thanks all.

**Comment by DanAlbert** [comment]
Read the previous two comments.

**Comment by aberaud** [comment]
Hi,
When is r19b planned to be released ?
Thanks

**Comment by DanAlbert** [comment]
I'm staging a release candidate right now. We'll need to wait for QA to have room in their schedule (sometime this week, last I heard) and I have a bit more testing of my own to do. Once that's done, it goes live. Should be this week.
