### ISSUE TITLE
O_TMPFILE present in headers but unsupported?

### ISSUE THREAD

**Issue by fornwall** [android-ndk/ndk#85]
The `O_TMPFILE` constant is defined but trying to use it (at least on a Nexus 6P running Android 6.0) results in `EISDIR`.

**Comment by DanAlbert** [comment]
http://man7.org/linux/man-pages/man2/open.2.html
> O_TMPFILE (since Linux 3.11)

Almost no Android devices have a kernel new enough for that.

There's no NDK bug here afaik, just that Android devices need up to date kernels.

**Comment by DanAlbert** [comment]
(we don't do anything special in libc, we just make the syscall)
