### ISSUE TITLE
NDK should be versionable in sdkmanager

### ISSUE THREAD

**Issue by aberaud** [android-ndk/ndk#850]
Currently, when pulling the NDK through sdkmanager in command line along with other packages, the latest NDK version is always retrieved and the only way to pull an older revision is by downloading and extracting the zip file.

Different NDK versions often include various breaking changes, so IMHO the NDK version should be versionable in sdkmanager in the same way as the build tools and the platform to make building Android apps using the NDK more robust, consistent and reproducible.

Many thanks

**Comment by DanAlbert** [comment]
100% agree, but wrong bug tracker :) I opened a Studio bug for this a while back: https://issuetracker.google.com/80431718

Frustratingly it got duped into an internal bug, but rest assured that this is actually being looked at right now. There's a fair amount of complexity in figuring out how that actually behaves given that a single SDK install needs to remain compatible with multiple versions of Studio and the gradle plugin (which are also not necessarily the same version, and aiui rarely are), but that is being worked on.

If you have any input, leave it on that bug. I CC'd the engineer the internal one is now assigned to so he'll see it.
