### ISSUE TITLE
Symbols mangled name has changes due to the change of gnustl to libc++

### ISSUE THREAD

**Issue by bhupeshpant19jan** [android-ndk/ndk#851]
#### Symbols Mangled name is changing with libc++

I am migrating from GNUSTL to libc++ and I have observed the linking error for one of the projects that were consuming previously built library, so. The reason was that consumer of the so, could not find the symbols.
After the investigation, I observed that the mangled symbol name has changed for this public API,

```purgeResourcesNotUsedInMs(std::chrono::milliseconds ms)```

This change is because of the fact that chrono is defined under std:: namespace in gnustl whereas in libc++ it is defined under std::__ndk. Due to this change the mangled name has changed.  
Although I have updated the versionmap file for this so but this approach is bothering me as there could be multiple places where this needs to be changed and this issue will only surface when we will link to the so. 
I believe there must be a way to avoid this issue because I don't find it appropriate to update the mangled name everywhere because of this change. Please share your view on this issue and appropriate action for this issue.

Older Mandled name:  **_ZN9GrContext25purgeResourcesNotUsedInMsENSt6chrono8durationIxSt5ratioILx1ELx1000EEEE;**

New Mangled name:  **_ZN9GrContext25purgeResourcesNotUsedInMsENSt6__ndk16chrono8durationIxNS0_5ratioILx1ELx1000EEEEE;**

Regards,
Bhupesh

#### Environment Details

* NDK Version: 16
* Build system: NMAKE, Clang
* Compiler: Clang
* STL: libc++
* NDK API level: 21

**Comment by alexcohn** [comment]
This breaking change was intentional, and it is for good. There are too many differences between the runtime libraries (see e.g. *[Using libstdc++ compiled libraries with clang++ -stdlib=libc++
](https://stackoverflow.com/q/12542971/192373)* and *[OpenCV build issue](https://stackoverflow.com/q/13037659/192373)*). One **must** recompile when switching from gnustl to libc++.

**Comment by bhupeshpant19jan** [comment]
The painful thing is that we have to manually maintain the entries of all the exported symbols. hence all the process of updating the entries in versionmap.export are manual for us.

**Comment by DanAlbert** [comment]
Use sed?
