### ISSUE TITLE
what's difference between NDK 18.1.5063045 and NDK 18b

### ISSUE THREAD

**Issue by drelaptop** [android-ndk/ndk#852]
- In NDK change log, it's like r18b, r10e ...
- But in Android Studio, it's 18.1.5063045. what's the numbers mean?

how I download a NDK which version is 18.1.5063045 ? it's quite equals to r18b?

**Comment by noangel** [comment]
from NDK r18b source.properties:
Pkg.Revision = 18.1.5063045
18 - major version
1 - minor version
5063045 - build number
if all three the same, should be built from same source.

**Comment by drelaptop** [comment]
thanks for your answer. @noangel

**Comment by enh** [comment]
yeah, sadly Studio's SDK manager stuff doesn't support letters, so we have to use the build numbers there instead. but maybe we should add the build numbers to the wiki/version history to make them easier to compare...
