### ISSUE TITLE
Got these errors while trying to build libicu

### ISSUE THREAD

**Issue by twaik** [android-ndk/ndk#853]
#### Got these errors while trying to build libicu
```
/buildbot/src/android/ndk-release-r18/bionic/libc/bionic/locale.cpp:136: error: undefined reference to 'operator new(unsigned int)'
/buildbot/src/android/ndk-release-r18/bionic/libc/bionic/locale.cpp:140: error: undefined reference to 'operator delete(void*)'
/buildbot/src/android/ndk-release-r18/bionic/libc/bionic/locale.cpp:155: error: undefined reference to 'operator new(unsigned int)'

```
#### Environment Details
NDK r18, ndk-build
* Host OS:  Ubuntu cosmic
* ABI: armeabi-v7a
* STL: c++_shared
* NDK API level:19

**Comment by epicstar** [comment]
What version of libicu are you building? On the standalone toolchain of r13b, r16b, and r18b, my build works as expected but I'm building 53.1.

**Comment by twaik** [comment]
These errors are shown if the c source contains localeconv()

**Comment by DanAlbert** [comment]
Not enough information here, but I'm guessing there's something wrong with your build scripts. Can you share those?

**Comment by twaik** [comment]
Looks like I lost sources. Sorry.
