### ISSUE TITLE
CMake toolchain issue in Android Studio 3.1.2

### ISSUE THREAD

**Issue by ils-aashishj** [android-ndk/ndk#854]
I am always getting this below issue.
I have just created one sample app and installed NDK and CMake.

**Build command failed.**

Error while executing process D:\Software\Latest\Android Sdk\sdk\cmake\3.6.4111459\bin\cmake.exe with arguments {-HD:\Ilead\Home\Game Porting App\app -BD:\Ilead\Home\Game Porting App\app\.externalNativeBuild\cmake\debug\armeabi-v7a -DANDROID_ABI=armeabi-v7a -DANDROID_PLATFORM=android-23 -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=D:\Ilead\Home\Game Porting App\app\build\intermediates\cmake\debug\obj\armeabi-v7a -DCMAKE_BUILD_TYPE=Debug -DANDROID_NDK=D:\Software\Latest\Android Sdk\sdk\ndk-bundle -DCMAKE_CXX_FLAGS=-fexceptions -DCMAKE_TOOLCHAIN_FILE=D:\Software\Latest\Android Sdk\sdk\ndk-bundle\build\cmake\android.toolchain.cmake -DCMAKE_MAKE_PROGRAM=D:\Software\Latest\Android Sdk\sdk\cmake\3.6.4111459\bin\ninja.exe -GAndroid Gradle - Ninja}

-- Check for working C compiler: D:/Software/Latest/Android Sdk/sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe

-- Check for working C compiler: D:/Software/Latest/Android Sdk/sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe -- broken

/Software/Latest/Android   Sdk/sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe"   is not able to compile a simple test program. 
Open File

  It fails with the following output:

   Change Dir: D:/Ilead/Home/Game Porting App/app/.externalNativeBuild/cmake/debug/armeabi-v7a/CMakeFiles/CMakeTmp

  Run Build Command:"D:/Software/Latest/Android

  Sdk/sdk/cmake/3.6.4111459/bin/ninja.exe" "cmTC_88ed0"

  [1/2] Building C object CMakeFiles/cmTC_88ed0.dir/testCCompiler.c.o

  FAILED:

  D:\Software\Latest\ANDROI~1\sdk\NDK-BU~1\TOOLCH~1\llvm\prebuilt\WINDOW~1\bin\clang.exe

  --target=armv7-none-linux-androideabi23

  --gcc-toolchain="D:/Software/Latest/Android

  Sdk/sdk/ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/windows-x86_64"

  --sysroot="D:/Software/Latest/Android Sdk/sdk/ndk-bundle/sysroot" -isystem

  D:/Software/Latest/Android

  Sdk/sdk/ndk-bundle/sysroot/usr/include/arm-linux-androideabi -g -DANDROID

  -ffunction-sections -funwind-tables -fstack-protector-strong

  -no-canonical-prefixes -march=armv7-a -mfloat-abi=softfp -mfpu=vfpv3-d16

  -mthumb -mfpu=neon -Wa,--noexecstack -Wformat -Werror=format-security -fPIE

  -o CMakeFiles/cmTC_88ed0.dir/testCCompiler.c.o -c "D:\Ilead\Home\Game

  Porting

  App\app\.externalNativeBuild\cmake\debug\armeabi-v7a\CMakeFiles\CMakeTmp\testCCompiler.c"

error: no such file or directory:

  'Sdk/sdk/ndk-bundle/sysroot/usr/include/arm-linux-androideabi'

  ninja: build stopped: subcommand failed.

  CMake will not be able to correctly generate this project.

Call Stack (most recent call first):

  CMakeLists.txt

-- Configuring incomplete, errors occurred!

See also "D:/Ilead/Home/Game Porting App/app/.externalNativeBuild/cmake/debug/armeabi-v7a/CMakeFiles/CMakeOutput.log".

See also "D:/Ilead/Home/Game Porting App/app/.externalNativeBuild/cmake/debug/armeabi-v7a/CMakeFiles/CMakeError.log".

Build command failed.

Error while executing process D:\Software\Latest\Android Sdk\sdk\cmake\3.6.4111459\bin\cmake.exe with arguments {-HD:\Ilead\Home\Game Porting App\app -BD:\Ilead\Home\Game Porting App\app\.externalNativeBuild\cmake\release\armeabi-v7a -DANDROID_ABI=armeabi-v7a -DANDROID_PLATFORM=android-23 -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=D:\Ilead\Home\Game Porting App\app\build\intermediates\cmake\release\obj\armeabi-v7a -DCMAKE_BUILD_TYPE=Release -DANDROID_NDK=D:\Software\Latest\Android Sdk\sdk\ndk-bundle -DCMAKE_CXX_FLAGS=-fexceptions -DCMAKE_TOOLCHAIN_FILE=D:\Software\Latest\Android Sdk\sdk\ndk-bundle\build\cmake\android.toolchain.cmake -DCMAKE_MAKE_PROGRAM=D:\Software\Latest\Android Sdk\sdk\cmake\3.6.4111459\bin\ninja.exe -GAndroid Gradle - Ninja}

-- Check for working C compiler: D:/Software/Latest/Android Sdk/sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe

-- Check for working C compiler: D:/Software/Latest/Android Sdk/sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe -- broken
CMake Error at D:/Software/Latest/Android Sdk/sdk/cmake/3.6.4111459/share/cmake-3.6/Modules/CMakeTestCCompiler.cmake:61 (message):

  The C compiler "D:/Software/Latest/Android

  Sdk/sdk/ndk-bundle/toolchains/llvm/prebuilt/windows-x86_64/bin/clang.exe"

  is not able to compile a simple test program.

  It fails with the following output:

   Change Dir: D:/Ilead/Home/Game Porting App/app/.externalNativeBuild/cmake/release/armeabi-v7a/CMakeFiles/CMakeTmp

  Run Build Command:"D:/Software/Latest/Android

  Sdk/sdk/cmake/3.6.4111459/bin/ninja.exe" "cmTC_28885"

  [1/2] Building C object CMakeFiles/cmTC_28885.dir/testCCompiler.c.o

  FAILED:

  D:\Software\Latest\ANDROI~1\sdk\NDK-BU~1\TOOLCH~1\llvm\prebuilt\WINDOW~1\bin\clang.exe

  --target=armv7-none-linux-androideabi23

  --gcc-toolchain="D:/Software/Latest/Android

  Sdk/sdk/ndk-bundle/toolchains/arm-linux-androideabi-4.9/prebuilt/windows-x86_64"

  --sysroot="D:/Software/Latest/Android Sdk/sdk/ndk-bundle/sysroot" -isystem

  D:/Software/Latest/Android

  Sdk/sdk/ndk-bundle/sysroot/usr/include/arm-linux-androideabi -g -DANDROID

  -ffunction-sections -funwind-tables -fstack-protector-strong

  -no-canonical-prefixes -march=armv7-a -mfloat-abi=softfp -mfpu=vfpv3-d16

  -mthumb -mfpu=neon -Wa,--noexecstack -Wformat -Werror=format-security -fPIE

  -o CMakeFiles/cmTC_28885.dir/testCCompiler.c.o -c "D:\Ilead\Home\Game

  Porting

  App\app\.externalNativeBuild\cmake\release\armeabi-v7a\CMakeFiles\CMakeTmp\testCCompiler.c"

error: no such file or directory:

  'Sdk/sdk/ndk-bundle/sysroot/usr/include/arm-linux-androideabi'

  ninja: build stopped: subcommand failed.

  CMake will not be able to correctly generate this project.

Call Stack (most recent call first):

  CMakeLists.txt

-- Configuring incomplete, errors occurred!

See also "D:/Ilead/Home/Game Porting App/app/.externalNativeBuild/cmake/release/armeabi-v7a/CMakeFiles/CMakeOutput.log".

See also "D:/Ilead/Home/Game Porting App/app/.externalNativeBuild/cmake/release/armeabi-v7a/CMakeFiles/CMakeError.log".

**Comment by alexcohn** [comment]
Android NDK does not work when its full path contains spaces, like `D:/Software/Latest/Android Sdk/sdk/ndk-bundle`. I recommend to keep both SDK and projects paths with no spaces.

**Comment by DanAlbert** [comment]
I'm guessing Alex is right about the cause here. Hard to say for sure since idk if the newlines splitting paths in your post are actually there in the log or if that's just bad formatting in the message.

**Comment by l1uchao** [comment]
@alexcohn , @DanAlbert ，I have the same problems, but my projects paths with no spaces.Please help me fix it,thank you 
![image](https://user-images.githubusercontent.com/41014650/54668646-58152080-4b2a-11e9-8858-f58d3d421d1f.png)

**Comment by DanAlbert** [comment]
Then you have a different problem. File a new bug with all the information in the template with repro steps.

**Comment by alexcohn** [comment]
@l1uchao there may be some details about *broken clang compiler* in the `cmake_build_*.txt` files in the **.externalnativeBuild/cmake/debug/x86** directory of your library.
