### ISSUE TITLE
Memory leak is detected while str() on std::wstringstream

### ISSUE THREAD

**Issue by pendyalasyam** [android-ndk/ndk#857]
I have a following function in my code.

> std::wstring function() noexcept
> {
> 	static const wchar_t c_tokenStartChar = L'|';
> 
> 	std::wstringstream returnValueBuilder;
> 
> 	//some operations on returnValueBuilder;
> 	returnValueBuilder <<  c_tokenStartChar;
> 	//some operations on returnValueBuilder;
> 
> 	return returnValueBuilder.str();
> }

I have developed a test case around this function using our test infrastructure. When I am verifying this test case with gnustl, it is successfully passing. But when I try to run the test case with libc++, memory leaks are detected and test case is failing.

Following is the stack of leak detection.

> [1 / 4] Leaked 32 bytes allocated at 0xa1087ba8
>      at Myso::Memory::AllocateEx(unsigned int, unsigned long) (line 0)
>      at Myso::Memory::Throw::AllocateEx(unsigned int, unsigned long) (line 0)
>      at operator new(unsigned int) (line 0)
>      at std::__ndk1::enable_if<__is_forward_iterator<wchar_t*>::value, void>::type std::__ndk1::basic_string<wchar_t, wc16::wchar16_traits, std::__ndk1::allocator<wchar_t> >::__init<wchar_t*>(wchar_t*, wchar_t*) (line 0)
>      at std::__ndk1::basic_stringbuf<wchar_t, wc16::wchar16_traits, std::__ndk1::allocator<wchar_t> >::str() const (line 0)
>      at Myso::StringCore::function() (line 0) 

When I read the link https://stackoverflow.com/questions/28918189/am-i-responsible-for-freeing-deleting-a-string-returned-by-stringstream-str, the link is saying when we call str(), a temporary object will be created on the stack and will be automatically garbage collected when it goes out of scope. But it seems such garbage collection is not happening when libc++ used. It seems behavior might have changed when used with libc++. Please let me know what is happening here.

Since the return value std::basic_string and not the pointer, I can not call delete also. Please let me know how to fix the memory leak.

Thanks.

**Environment Details**

NDK Version: r16
Build system: Clang
Host OS: Android on Windows
Compiler: Clang
ABI:
STL: libc++
NDK API level: 21
Device API level: 23

**Comment by DanAlbert** [comment]
What are you using to detect memory leaks? Haven't looked at this yet but asking just in case it's unique to the leak detector.

**Comment by pendyalasyam** [comment]
We are using our own leak detector tool which is built in-house. I believe, this in-house tool is stable and give proper results.

**Comment by jmgao** [comment]
It looks like your leak detector is implemented via interposition of `operator new`. Have you interposed the C++11 [sized deallocation](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2013/n3536.html) version of `operator delete` as well?

**Comment by pendyalasyam** [comment]
@jmgao, yes, we have interposed the operator delete also.

I have tried to understand the problem little more today. Few lines from above leak snippet.

> at operator new(unsigned int) (line 0)
> at std::__ndk1::enable_if<__is_forward_iterator<wchar_t*>::value, void>::type std::__ndk1::basic_string<wchar_t, wc16::wchar16_traits, std::__ndk1::allocator<wchar_t> >::__init<wchar_t*>(wchar_t*, wchar_t*) (line 0)
> at std::__ndk1::basic_stringbuf<wchar_t, wc16::wchar16_traits, std::__ndk1::allocator<wchar_t> >::str() const (line 0)

From these lines, it is clear that str() function call is allocating memory (because it is calling into new operator). Since it is the str() who is allocating memory, delete has to be called str() only.

**Comment by pendyalasyam** [comment]
Tested using gnustl. When str() function is called, there is no dynamic memory allocation done.

**Comment by DanAlbert** [comment]
Operator delete and sized operator delete are two different things. You need to overload the full set described on https://en.cppreference.com/w/cpp/memory/new/operator_new.

**Comment by pendyalasyam** [comment]
Our leak detector is written to track only "new" allocations. 
Our leak detector is not implemented to track deallocations done while destructing global/static variables 
which happens during program termination.

Earlier, when we were using GNUStl, since the allocations inside string implementation are done using malloc, those allocations were untracked and no leaks were reported.

Now, with libc++, allocation done inside global variables using new operators. If these allocations are manually released(like reassigning with empty string/clear contents), no issues are reported. Otherwise, they are reported as leaks.

THERE ARE NO MEMORY LEAKS INSIDE LIBC++ STR()  FUNCTION
