### ISSUE TITLE
timespec_get no longer works after upgrade to NDK 18 

### ISSUE THREAD

**Issue by mcclure** [android-ndk/ndk#864]
I am compiling a [library](https://github.com/bjornbytes/lovr/blob/master/src/thread/channel.c#L47). Yesterday, it compiled. Then I upgraded from NDK 17 to NDK 18 in the Android Studio updater. Now, that same compile fails with the linker error

```
  CMakeFiles/lovr.dir/src/thread/channel.c.o: In function `lovrChannelPush':
  /Users/mcc/work/h/oculus/lovrapp-temp/cmakelib/lovr/src/thread/channel.c:47: undefined reference to `timespec_get'
  /Users/mcc/work/h/oculus/lovrapp-temp/cmakelib/lovr/src/thread/channel.c:53: undefined reference to `timespec_get'
  CMakeFiles/lovr.dir/src/thread/channel.c.o: In function `lovrChannelPop':
  /Users/mcc/work/h/oculus/lovrapp-temp/cmakelib/lovr/src/thread/channel.c:87: undefined reference to `timespec_get'
  /Users/mcc/work/h/oculus/lovrapp-temp/cmakelib/lovr/src/thread/channel.c:93: undefined reference to `timespec_get'
  clang++: error: linker command failed with exit code 1 (use -v to see invocation)
```

At least one open source project seems to be hitting the same issue https://github.com/tinycthread/tinycthread/issues/47

Why would this function have been removed just from upgrading Android Studio?

### Repro steps

Check out https://github.com/mcclure/lovr-oculus-mobile . Either clone with `--recurse-submodules` or run `(cd cmakelib/lovr && git submodule init && git submodule update)` after checkout.

Build the subdirectory cmakelib/ . I do this with

    (export PATH="/Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin":~/Library/Android/sdk/platform-tools:$PATH ANDROID_HOME=~/Library/Android/sdk GRADLE=`pwd`/gradlew; (cd cmakelib && $GRADLE build))

On NDK 18 I see the error.

**Comment by enh** [comment]
`timespec_get` isn't available until next year's OS release. so it's actually the opposite: NDK r18 is the first NDK to have headers that declare it. but unless you're targeting an API level in the future, you shouldn't see the declaration?

**Comment by enh** [comment]
does your project have the same problem as tinycthread/tinycthread#47? assuming that the presence/absence of the constant tells you whether or not you have the function?

**Comment by mcclure** [comment]
@enh Thank you for clarifying… in fact it turns out that the problem IS tinycthread, which we are using… I had not realized this but tinycthread.h defines `timespec_get` if it is not present. I have hotfixed tinycthread as described in that other issue, and so the problem is fixed for me.

However, can you clarify: Are you **certain** that it is correct for `TIME_UTC` to be defined in `time.h` if `timespec_get` is not present? According to cppreference.com, `TIME_UTC` is a constant defined in C11 and moreover it appears to be not used by any function other than `timespec_get`. It seems the thing that breaks tinycthread is the TIME_UTC constant being defined, and if the definition had also been in the `__ANDROID_API__ >= __ANDROID_API_FUTURE__` block there would have been no breakage. If the stray TIME_UTC define is correct or WONTFIX then this issue can be closed.

**Comment by DanAlbert** [comment]
The intent of leaving the constant available is that if you were to use `dlsym` to conditionally call `timespec_get` (like you would if you were building for an older release, but want to use it when running on a new one), you still need to be able to use the constant.

We've made exceptions to this before, but we should see if we can get that project fixed first.
