### ISSUE TITLE
The parameter "long frameTimeNanos" of AChoreographer_frameCallback not working in 32-bit platforms

### ISSUE THREAD

**Issue by AlanCMH** [android-ndk/ndk#868]
It should be an explicit int64_t-type parameter to hold the nanosecond timestamp or the value will be truncated in 32-bit platforms.

Google sample "choreographer-30fps" is a test case for this issue.
  https://github.com/googlesamples/android-ndk/tree/master/teapots/choreographer-30fps
Build the apk with 32-bit version (armeabi-v7a) only and run. The teapot cannot move and the FPS value does not update.

NDK version: 18.1
Android: 8.0
Test case: build armeabi-v7a version only

**Comment by enh** [comment]
this is OS bug https://issuetracker.google.com/111337895
