### ISSUE TITLE
make-standalone-toolchain.sh doesn't copy STL libs for armeabi-v7a-hard

### ISSUE THREAD

**Issue by buffer51** [android-ndk/ndk#87]
Hi,

When using `make-standalone-toolchain.sh` for armeabi-v7-hard, the hard STL libs are not copied.
I filed an [issue on the previous tracker](https://code.google.com/p/android/issues/detail?id=188895) with a patch, but since it seems to have been forgotten and is not in r11c nor master, I though I'd report it here as well.

**Comment by fornwall** [comment]
Considering https://android.googlesource.com/platform/ndk/+/master/docs/HardFloatAbi.md I guess this isn't going to change?

**Comment by DanAlbert** [comment]
That's correct.
