### ISSUE TITLE
[BUG] Clang defines __gnu_linux__ when targeting Android

### ISSUE THREAD

**Issue by alexeikh** [android-ndk/ndk#874]
#### Description

Clang which is included with Android NDK defines `__gnu_linux__` , in addition to `__linux__`. GCC, while it was still included in Android NDK, did not define `__gnu_linux__`. GCC only defined `__linux__`.

The issue is reproducible on all the latest versions of Android NDK, including r18b and r19 Beta 2.

In my view of the world:
* GNU/Linux is an OS with Linux kernel and GNU system utilities. Thus Android/Linux is not GNU/Linux.
* `__gnu_linux__` macro exists in addition to `__linux__` for identifying specifically GNU/Linux OS, not any OS with Linux kernel. Otherwise, `__linux__` would be enough.
* On Android, `__linux__` and `__ANDROID__` should be defined, but not `__gnu_linux__`.
* On GNU/Linux, `__linux__` and `__gnu_linux__` must be defined, but not `__ANDROID__`.

Different people on the Internet seem to share this point of view:

* https://sourceforge.net/p/predef/wiki/OperatingSystems/
* https://github.com/panda3d/panda3d/issues/343
* https://reviews.llvm.org/D17880
* https://tracker.crystax.net/issues/916
* https://annoyingtechnicaldetails.wordpress.com/2012/02/01/which-macros-does-the-android-ndk-gcc-define/

A practical example. We had some code in a project that was shared between Android and desktop Linux. The code had GNU/Linux-specific parts that were enclosed in `#if __gnu_linux__`. It worked fine with GCC. When migrating to Clang, we had to change those places to use `#if __gnu_linux__ && !__ANDROID__`, which feels wrong and redundant.

I'd like to find out what is Android NDK maintainer's position on this question. Is it a bug or is it an expected behavior?

#### Steps to reproduce

A small command-line app at https://github.com/alexeikh/android-ndk-compiler-version can be used for reproducing the issue. The app will print the value of `__gnu_linux__`, among other information.

Here is how you use it:

1. Edit path to your `ndk-build` in `Makefile`. Alternatively, supply `NDK_BUILD=/path/to/ndk-build` parameter for `make` in the `make run` step.
2. Change `NDK_TOOLCHAIN_VERSION` in `jni/Application.mk`, if you want to test with GCC.
3. Connect an Android device to your machine or start Android emulator.
4. Build and run the app on your phone:
```sh
make run
```

#### Environment Details

* NDK Version: r19-beta2, r18b, r16b, etc.
* Build system: ndk-build
* Host OS: Debian GNU/Linux
* Compiler: Clang
* ABI: armeabi-v7a, arm64-v8a, probably all others as well
* STL: libc++
* NDK API level: 16
* Device API level: 28

**Comment by enh** [comment]
and don't forget `__BIONIC__` which might be on Android _or_ desktop Linux, and is Android's equivalent of `__GLIBC__`...

from a quick google-internal code search, it seems like this might already be an unsalvageable mess. just looking at the first page of matches:

1. eigen3 already tests `__gnu_linux__` and not `__ANDROID__`.
2. some camera code has `__gnu_linux__` with an "else" `__ANDROID__` but they should be using the `__gnu_linux__` case for Android too. (and, by accident, are right now.)
3. libffi has a document talking about this mess :-) ... and then has the "and not Android" check.
4. uhubctl is a genuine use of `__gnu_linux__` that should only be on a Debian-like system.

so i think, yeah, there's a good argument that this is a bug, but it may be that the ship already sailed and it's more problematic to change it now?

**Comment by alexcohn** [comment]
- **eigen3** or **libffi** won't suffer from fixing NDK
- **uhubctl** usage seems to take advantage from fixing NDK
- regarding **camera**, maybe you can give a reference?

**Comment by DanAlbert** [comment]
This is wrong enough that I think we should make the change even though there's code it will break. There's possibly still plenty of code that's broken in the opposite direction out there because it hasn't adapted to Android Clang yet.

https://reviews.llvm.org/D55953

Bionic non-Android Linux is a whole other can of worms that I'm not going to address in this patch. I suspect we'll want to use "bionic" as the environment part of the triple in that case (i.e. x86_64-linux-bionic instead of x86_64-linux-gnu) when that becomes a more fleshed out configuration.

**Comment by DanAlbert** [comment]
Fix has landed upstream, so the NDK will get the fix whenever Android gets a new Clang. I'm guessing that'll happen for r20.

**Comment by DanAlbert** [comment]
Fix is in master (r21).
