### ISSUE TITLE
Allow pick 32 or 64 bit native lib if device supports both architectures [FR]

### ISSUE THREAD

**Issue by bruenor41** [android-ndk/ndk#875]
**Is your feature request related to a problem? Please describe.**
Since August 2019 each APK which contains native code must add 64bit version. Emulators have dynamic recompiler from asm of one architecture to another. 32bit dynamic recompilers are faster then 64bit.

**Describe the solution you'd like**
Would be great to add possibility for detecting which architectures device supports and API which allows load native library for chosen architecture manually. Maybe like a parameter for System.loadLibrary. For example, if device has 64bit x86 architecture with backward support for 32bit, I would like to pick which my native library should be loaded. If it supports only 64bit then I will load 64bit native library.

**Comment by DanAlbert** [comment]
This isn't anything the NDK has a say in. File a platform bug at b.android.com.

**Comment by bruenor41** [comment]
Thank you for point me to correct forum
