### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by lenniea** [android-ndk/ndk#877]
--------------------------------------------------------------------------------

#### Description

Latest android gcc compiler appears to handle signed integer divide incorrectly:

```
#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>

int frameWidth = 208;

int main(int argc, char* argv[])
{
    int32_t count = (argc > 1) ? atoi(argv[1]) : -1;
    int width = frameWidth;
    int rows = count / (width * sizeof(int16_t));
    if (rows >= 3) {
        printf("rows=%u\n", rows);
    } else {
        printf("count=%d rows=%d\n", count, rows);
    }
}
```
if this is compiled and run as a cmdline executable on arm with no arguments or a negative number the if statement incorrectly executes the first statement.

You can also see it in the assembly language source code main.s (compiled with --save-temps):

```
.Ltmp7:
        @DEBUG_VALUE: main:count <- $r4
        .loc    1 11 22 is_stmt 0       @ ./main.c:11:22
        mov     r0, r4
.Ltmp8:
        bl      __aeabi_uidiv
        mov     r2, r0
.Ltmp9:
        @DEBUG_VALUE: main:rows <- $r2
        .loc    1 12 9 is_stmt 1        @ ./main.c:12:9
        cmp     r0, #3
        blt     .LBB0_5

```
#### Environment Details

Not all of these will be relevant to every bug, but please provide as much
information as you can.

* NDK Version: 18.1.5063045
* Build system: ndk-build or standalone toolchain
* Host OS: Mac OSX Mojave
* ABI: android armeabi-v7a
* STL: c++_static
* NDK API level: 27
* Device API level: N/A

Attached is a ndkbug.tar.gz which contains an Android.mk, Application.mk and main.c source file to illustrate this bug.

[ndkbug.tar.gz](https://github.com/android-ndk/ndk/files/2696512/ndkbug.tar.gz)

**Comment by rprichard** [comment]
I think this is expected behavior. `sizeof(int16_t)` will have an unsigned type (either `unsigned int` or `unsigned long`). Usual arithmetic conversions make the multiplication unsigned, then the divide. `count` is coerced to a very large unsigned value, divided to a not-quite-as-large unsigned number, then coerced to `int`.

**Comment by lenniea** [comment]
Yes you are indeed correct: I found this on - per rule 4:

https://wiki.sei.cmu.edu/confluence/display/c/INT02-C.+Understand+integer+conversion+rules

Usual Arithmetic Conversions

1. The usual arithmetic conversions are rules that provide a mechanism to yield a common type when both operands of a binary operator are balanced to a common type or the second and third operands of the conditional operator ( ? : ) are balanced to a common type. Conversions involve two operands of different types, and one or both operands may be converted. Many operators that accept arithmetic operands perform conversions using the usual arithmetic conversions. After integer promotions are performed on both operands, the following rules are applied to the promoted operands:
2. If both operands have the same type, no further conversion is needed.
3. If both operands are of the same integer type (signed or unsigned), the operand with the type of lesser integer conversion rank is converted to the type of the operand with greater rank.
4. If the operand that has unsigned integer type has rank greater than or equal to the rank of the type of the other operand, the operand with signed integer type is converted to the type of the operand with unsigned integer type.
5. If the type of the operand with signed integer type can represent all of the values of the type of the operand with unsigned integer type, the operand with unsigned integer type is converted to the type of the operand with signed integer type.
6. Otherwise, both operands are converted to the unsigned integer type corresponding to the type of the operand with signed integer type.
