### ISSUE TITLE
No toolchains found in the NDK toolchains folder for ABI with prefix: mips64el-linux-android

### ISSUE THREAD

**Issue by Ankit48** [android-ndk/ndk#878]
1. No toolchains found in the NDK toolchains folder for ABI with prefix: mips64el-linux-android
- is there any issue of machine changing ? my code is uploded with mac os and then i open it in windows 
  os ?

**Comment by alexcohn** [comment]
See https://github.com/android-ndk/ndk/issues/700#issuecomment-392935541. The bottom line is that when you use a newer NDK, you also need a compatible gradle plugin. Upgrade of the gradle plugin is usually straightforward, but involves touching build.gradle files.
