### ISSUE TITLE
make-standalone-toolchain.sh fails to package

### ISSUE THREAD

**Issue by buffer51** [android-ndk/ndk#88]
Hi,

When using `make-standalone-toolchain.sh` without an installation directory to generate a package, it fails at the packaging step:
```
Creating package file: /tmp/ndk-paul/arm-linux-androideabi-4.9.tar.bz2
## COMMAND: tar -j --exclude='*.py[cod]' --exclude='*.swp' --exclude=.git --exclude=.gitignore -cf /tmp/ndk-paul/arm-linux-androideabi-4.9.tar.bz2 arm-linux-androideabi-4.9
tar: arm-linux-androideabi-4.9: Cannot stat: No such file or directory
tar: Exiting with failure status due to previous errors
ERROR: Could not create tarball from /tmp/ndk-paul/tmp/build-6259/ndk.2SVrzLo
```

My understanding is that it's looking for the folder `arm-linux-androideabi-4.9`, which is instead named something temporary (in this case `ndk.2SVrzLo`). Changing the packaging line to
```
pack_archive "$PACKAGE_FILE" "$TMPDIR"
```
solves the problem, although the tarball doesn't contain everything in a `arm-linux-androideabi` folder.

**Comment by DanAlbert** [comment]
Offending commit: https://android.googlesource.com/platform/ndk/+/f40aaf9fb17aa0261c9ed89e2eca40cf68e5d0fc

Should be an easy enough fix.

**Comment by DanAlbert** [comment]
https://android-review.googlesource.com/220070

**Comment by buffer51** [comment]
Thanks!

**Comment by DanAlbert** [comment]
Going to keep this open so I don't forget to actually get that submitted :) It's currently waiting for review.

**Comment by buffer51** [comment]
My bad :+1:
