### ISSUE TITLE
[BUG]  error: the specified comparator type does not provide a const call operator

### ISSUE THREAD

**Issue by bhupeshpant19jan** [android-ndk/ndk#880]
#### Error: the specified comparator type does not provide a const call operator

I am getting the below error while trying to compile my existing project in libc++ which is successfully compiled on gnustl.

`
![image](https://user-images.githubusercontent.com/5937254/50588187-f50ada80-0ea6-11e9-8496-a74b7bef4abf.png)
![image](https://user-images.githubusercontent.com/5937254/50588610-e8878180-0ea8-11e9-82d8-812ce4ccc6dc.png)

`

Based on the this link:- [https://groups.google.com/forum/#!msg/protobuf/9W6zFIHaJ-4/9RrfwelpEQAJ](https://groups.google.com/forum/#!msg/protobuf/9W6zFIHaJ-4/9RrfwelpEQAJ) , this looks like the behavioral difference b/w gnustl and libc++.

=========================================================
* NDK Version: r16b
* Build system: cmake
* Host OS: windows
* Compiler: Clang
* ABI: 
* STL: libc++
* NDK API level: 21
* Device API level:

**Comment by enh** [comment]
as mentioned on the protobuf thread you link to, this is a bug in your code that wasn't previously detected.
