### ISSUE TITLE
CMake update causes issues with withespaces in project file structure

### ISSUE THREAD

**Issue by Consti10** [android-ndk/ndk#882]
--------------------------------------------------------------------------------
I recently updated CMake via the SDK-Tools in Android studio 3.2.1, probably from version 3.6.4 to 3.10.2.
Suddenly, my ndk-build would  not run any more, and CMake throw the following error (shortened)

```
 Error while executing process 
Usage: cmake --build <dir> [options] [-- [native-options]]
```

I did not immediately understand the warning correctly, but figured out that it might be the following:
CMake reading the strings containing my folder structure not as single params, but multiple params due to whitespaces in them. (I also remebered about some warning message when installing ndk/cmake the fist time, years ago)

And **after eliminating all whitespaces** in my project's folders the **issue was resolved**.

I also noticed that Android Studio now throws an warning when importing a project that contains whitespaces - **but not when updating CMake and opening an already imported project**.

I probably should have avoided white spaces from the beginning, but it worked with the 
previous version of CMake (at least for my project structure). Please check if the update in the CMake version really changed the behaviour with whitespaces, or if it's just a random experience with my project.

It would then not be a bad idea to check already  imported projects when updating CMake via the SDK-Tools for whitespaces & throw a warning, maybe this can be implemented in a future android studio release.

**Comment by DanAlbert** [comment]
Wrong bug tracker. The CMake distribution is not included in the NDK. Please file a bug against Studio by following b.android.com (post it back here if you need it triaged).

**Comment by Consti10** [comment]
Thanks for clarifying this.
Under [https://developer.android.com/ndk/guides/cmake](url) it says
**If you run into any issues that aren't due to the open source version of CMake, report them via the android-ndk/ndk issue tracker on GitHub.**

Should have read the whole sentence.
