### ISSUE TITLE
[FR] --hash-style=both for ndk-build?

### ISSUE THREAD

**Issue by enh** [android-ndk/ndk#883]
(from internal bug http://b/30403411)

We started using --hash-style=both in the platform quite some time ago, but I don't think it was ever done for the NDK (though it was done for NDK things built in the platform).

I don't know the size implications here, but maybe it's worth doing both for low target APIs and gnu for things that are new enough.

dimitry: when did this support get added? Was that M or L?

It was Android M

**Comment by DanAlbert** [comment]
I fixed this in the driver in https://reviews.llvm.org/D53118, which we now have in master.
