### ISSUE TITLE
filesystem support in r18b Android NDK

### ISSUE THREAD

**Issue by pglushkov** [android-ndk/ndk#886]
Hi all!

I'm trying to compile and run my code that heavily uses <experimental/filesystem> headers. Some of functions from this header seem to work ok (e.g. path::string()), while some other seem to be declared, but linker cannot find them (e.g. directory_iterator implementation). 

My build-system:
OS : Windows 10
IDE : Android Studio 3.2.1
NDK : r18b
CMake : 3.6-rc2
CLang : 7.0 (at least so is reported by CMake)

by googling for the solution I either see people recommending including 'c++experimental' library, but it does not exist in my ndk-bundle (and probably is obsolete by now?) or using libstdc++ (basically using gcc) which is also deprecated or even including source-code of the 'filesystem' library all along from previous NDK releases (which I actually did and it works).

My question is basically - is there such thing as 'filesystem' library in the NDK r18b all along? If there is - what is the CORRECT way of linking against it in Android Studio for Windows?

If I'm asking at the wrong place - please be so kind, and point to the correct place to ask :)

Build errors are attached in the file.
[build.log](https://github.com/android-ndk/ndk/files/2746912/build.log)

**Comment by DanAlbert** [comment]
https://github.com/android-ndk/ndk/issues/609
