### ISSUE TITLE
Allow build.py to build a standalone toolchain

### ISSUE THREAD

**Issue by buffer51** [android-ndk/ndk#89]
Hi,

When building the GNU toolchains from [android/toolchain/gcc](https://android.googlesource.com/toolchain/gcc) with `build.py`, it automatically removes the `sysroot/` folder at the end.
Could we make that optional so that the script can generate standalone toolchains?
Here is a [proposed patch](https://github.com/android-ndk/ndk/files/237096/make-standalone.zip) adding that option. 

PS: I was not sure if this is the right place for changes regarding [android/toolchain/gcc](https://android.googlesource.com/toolchain/gcc), if not tell me where I can ask for the change.
Also, the current `build.py` removes the `sysroot/` folder twice, which I fixed.

**Comment by DanAlbert** [comment]
It would be a fairly non-functional toolchain. GCC is built against an older version of the platform headers and libraries because bootstrapping is awful. Your standalone toolchain won't have an STL either. I don't think we want to encourage something that will not work well.
