### ISSUE TITLE
[FR] Unable to set stack size on android libc++, libc++ on mac provides _LIBCPP_DEFAULT_STACKSIZE to set the stack size

### ISSUE THREAD

**Issue by yagnasrinath** [android-ndk/ndk#892]
**Is your feature request related to a problem? Please describe.**
One of out applications require larger stack size. We were able to set the stack size on mac OSX which also uses libc++ using the macro _LIBCPP_DEFAULT_STACKSIZE. Is there a way to set the stack size on android as well?
 
**Describe the solution you'd like**
Since setting attributes is not an option on std::thread, it is simpler to make _LIBCPP_DEFAULT_STACKSIZE available for developers to set the stack size.
Tried ulimit, but that did not help either.

**Describe alternatives you've considered**
Don't have alternatives yet :-(

**Additional context**

**Comment by yagnasrinath** [comment]
@DanAlbert Is there any alternative way of setting stack size?

**Comment by DanAlbert** [comment]
You can use http://man7.org/linux/man-pages/man3/pthread_attr_setstacksize.3.html before calling `pthread_create` can set the stack size for a new thread, but no, you can't change this at build time.

The only google result for `_LIBCPP_DEFAULT_STACKSIZE` is this bug. What are you referring to?

**Comment by yagnasrinath** [comment]
@DanAlbert But when we are using std::thread, how may I use pthread_attr. I was referring to source files from xcode c++ compiler. I guess it is not very well documented.

**Comment by yagnasrinath** [comment]
Yes, our application is using lot's of stack space and blew past the 1MB size which was the default.
