### ISSUE TITLE
[BUG] update arm-linux-androideabi-4.9 from r16 to r17, linker fail to work

### ISSUE THREAD

**Issue by shero21** [android-ndk/ndk#893]
-------------------------------------------------------------------------------
#### Description
    After I have updated arm-linux-androideabi-4.9 from r16 to r17,  the linker program refuse to work.
    The first phenomenon is that system can not start.  After a few hours I found that linker is where the problem is. Then I  update the system with r16 version and try to reproduce the problem with a test program.
    First I write a test program and specified the linker path:
    substitute /system/bin/linker to  /online/bin/linker (build/core/combo/TARGET_linux-arm.mk)
   Second I set the LD_DEBUG to 2 to obtain linker log.
   After that I run the test program and it said segmentation fault, then  I  try to use gdb to trace the problem, it said like this:
Reading symbols from /usr1/linker/test/symbols/app/bin/test...done.
warning: Unable to find dynamic linker breakpoint function.
GDB will be unable to debug shared library initializers
and track explicitly loaded dynamic code.
Core was generated by `/online/debug/test'.
Program terminated with signal 11, Segmentation fault.
#0  0xb6fc9f38 in ?? ()
(gdb) bt
#0  0xb6fc9f38 in ?? ()
#1  0xb6fca2f2 in ?? ()
Backtrace stopped: frame did not save the PC
(gdb) bt full
#0  0xb6fc9f38 in ?? ()
No symbol table info available.
#1  0xb6fca2f2 in ?? ()
No symbol table info available.
Backtrace stopped: frame did not save the PC
  The linker do not show any message.   I noticed that if a normal program run, the first log from linker is "[ android linker & debugger ]", for this reason, i guess that the linker with problem has not reach that point.
   
* NDK Version: NDK R17
* Build system: ndk-build? cmake? standalone toolchain? custom? (if gradle, file
  a bug against studio as specified above)
* Host OS: Ubuntu 14.04.5 LTS
* Compiler: GCC 
* ABI: 4.9
* STL:
* NDK API level:
* Device API level:

**Comment by DanAlbert** [comment]
None of these things are supported. Does it work with r19 and clang?

Regardless, you need to fill out the template. We need to know your build system. What device are you running on? What OS is it running? What did you build for?

What system cannot start? What is the problem you're seeing? How do we reproduce the problem?

What is /online/bin/linker? You should never need to change the linker. What are you trying to accomplish?

**Comment by DanAlbert** [comment]
Wait, you're building the system linker with the NDK? Use the platform build system to build platform things. The NDK is for building apps.

**Comment by shero21** [comment]
I use platform build system, I just update arm-linux-androideabi-4.7 to arm-linux-androideabi-4.9(R17), the download website is:
https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.9/

**Comment by shero21** [comment]
I download r17 at this place:
git clone https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.9
can you tell me where I can get further help? thinks.
