### ISSUE TITLE
[BUG] catch(const Ex& ex) not able to catch exceptions of type Ex

### ISSUE THREAD

**Issue by pendyalasyam** [android-ndk/ndk#899]
Problem: catch(const Ex& ex) not able to catch exceptions of type Ex

Details:

###############MyException.h##################
class MyException : public std::exception
{
public:
    MyException (){}
    MyException (const std::string& msg) : m_msg(msg) {}
    const char* what() const override { return m_msg.c_str(); }
protected:
    std::string m_msg;
};

############Test.cpp: This is bundled into Test.so#########
#include "MyException.h"
#include "service.h"
template<typename Ex, typename Fn>
bool ExpectException(const Fn& fn)
{
	try{
		fn();
	}catch(const Ex& ex){
		return true;
	}catch(...){
		//log statement: Unexpected exception
	}
	return false;
}

class Test
{
public:
	void test()
	{
		if(ExpectException<MyException>(TestFunction))
			//log statement: Test Success
		else
			//log statement: Test Failure
	}
}

############## service.cpp: This is bundled into service.so ########################
#include "MyException.h"

void TestFunction()
{
	throw MyException("Something went wrong");
}

We are bundling these shared libraries into one single APK and running the test() method.
As you can see, test method calls TestFunction and TestFunction is throwing exception.
Butn this thrown exception is not caught by catch(const Ex& ex).

Please help me to understand what is going wrong.

**Comment by DanAlbert** [comment]
It looks like your exception type doesn't have a key function. RTTI don't work across library boundaries unless the type has a key function.

**Comment by pendyalasyam** [comment]
Could you please tell me what is key function?

**Comment by DanAlbert** [comment]
https://github.com/android-ndk/ndk/issues?utf8=%E2%9C%93&q=%22key+function%22

**Comment by DanAlbert** [comment]
FYI I've added a section to our FAQ about this: https://android-review.googlesource.com/c/platform/ndk/+/892975

**Comment by pendyalasyam** [comment]
Adding key function worked. Thanks Dan.
