### ISSUE TITLE
Shared libraries are not copied when buildDir is overridden

### ISSUE THREAD

**Issue by blyn** [android-ndk/ndk#90]
Specifying a custom `buildDir` for a library or application prevents the NDK compiled library from being copied into the APK.  

For example (truncated to illustrated the important parts):
```
android {
    defaultConfig.with {
        buildDir = "${rootDir}/customBuildDir"
    }
    ndk {
        moduleName = "MyModule"
        toolchain = "clang"
        toolchainVersion = "3.6"
        stl = 'c++_shared'
    }
}
```

The created APK does not contain either libMyModule.so or libc++_shared.so.  Removing the buildDir line and rebuilding successfully creates an APK with the libraries.

**Comment by DanAlbert** [comment]
As stated in CONTRIBUTING.md, Gradle/Android Studio bugs go to http://b.android.com.
