### ISSUE TITLE
[DOC] r16b ERROR: ABIs [armeabi, mips, mips64] are not supported for platform. Supported ABIs are [arm64-v8a, armeabi-v7a, x86, x86_64]

### ISSUE THREAD

**Issue by jhwsx** [android-ndk/ndk#911]
**Note:** The NDK docs reside under https://developer.android.com/ndk/. If the bug you are reporting belongs to a different section of the site, this is the wrong bug tracker. See http://b.android.com.

**URL**
URL to the incorrect documentation (if the problem is that there is no documentation and it belongs on a new page, say so).

**Problem**
What's wrong? Does something need clarification/expansion? Is there a typo?

 Relevant infos are as follows:
- IDE : AndroidStudio
- gradle : 3.3.0/4.10.1
- targetSdkVersion : 28
- minSdkVersion : 16
- compileSdkVersion : 28
- C++ Standard : Toolchain Default

In fact, I followed the guide of [Build and run the sample app](https://developer.android.com/studio/projects/add-native-code#download-ndk) to build an apk. However, I cannot see armeabi, mips and mips64 in my apk file.
The following are the steps that I have tried:
- Check armeabi, mips and mips64 in my toolchain dir, they actually exists.
- include these abis in defaultConfig node of my build.gradle:
```text
splits {
            abi {
                reset()
                include 'armeabi', 'armeabi-v7a', 'arm64-v8a', 'x86', 'mips64', 'x86_64', 'mips'
            }
}
```
the result is the same as before.
- add abifilters in defaultConfig node of my build.gradle:
```text
ndk {
            abiFilters 'armeabi', 'armeabi-v7a', 'arm64-v8a', 'x86', 'mips64', 'x86_64', 'mips'
}
```
I got the error:
```text
ERROR: ABIs [armeabi, mips, mips64] are not supported for platform. Supported ABIs are [arm64-v8a, armeabi-v7a, x86, x86_64]
```
As r16b doc said,
```text
Support for ARMv5 (armeabi), MIPS, and MIPS64 are deprecated. They will no longer build by default with ndk-build, but are still buildable if they are explicitly named, and will be included by "all", "all32", and "all64". Support for each of these has been removed in r17.
```
I want to know how to **expilcitly name them (ARMv5 (armeabi), MIPS, and MIPS64)**, which is not explained in the doc and frustrated me for dozens of hours.

**Comment by DanAlbert** [comment]
The NDK has no control over gradle error messages. If you use ndk-build directly you can explicitly name them in `APP_ABI` as you always have.

Do you really want those ABIs? There aren't any devices on the play store that you're targeting by building those ABIs. If you really want that behavior, you'll need to file a bug against the gradle plugin (a Studio bug) or maybe revert to an older gradle plugin.

**Comment by alexcohn** [comment]
You must step back few versions of Gradle Plugin. There is no guarantee that the latest one cooperates with NDK r16 correctly, not limited to missing ABI issues.
