### ISSUE TITLE
"-fvisibility=hidden" have no effect in r19 in some condition

### ISSUE THREAD

**Issue by howardpang** [android-ndk/ndk#913]
Application.mk:

APP_ABI := armeabi-v7a 
APP_PLATFORM := android-19
APP_STL := c++_static
APP_OPTIM := release

Android.mk:
LOCAL_PATH := $(call my-dir) 
include $(CLEAR_VARS) 
LOCAL_C_INCLUDES := ${LOCAL_PATH}/include
LOCAL_SRC_FILES := mylib.cpp 
LOCAL_CXXFLAGS += -fvisibility=hidden
LOCAL_MODULE := mylib_shared
LOCAL_LDLIBS += -llog
include $(BUILD_SHARED_LIBRARY)

mylib.cpp:

#include <stdio.h>

uint32_t var1;
uint32_t var2;
void test() {
	printf("%d %d", var1, var2);
}

version: r19b-windows-x86_64
command: ndk-build

Detail:
When use r17 build the code and use "nm -D" to check the export info, the variable "var, var2" is hidden but r19 is not

**Comment by rprichard** [comment]
This looks like the same issue as https://bugs.llvm.org/show_bug.cgi?id=39413 / https://github.com/android-ndk/ndk/issues/829. `-Oz` turns on the GlobalMerge optimization, which isn't preserving the visibility attributes on variables.

Adding `-mno-global-merge` to the cflags is a workaround.

**Comment by DanAlbert** [comment]
Probably a dup of https://github.com/android-ndk/ndk/issues/829
