### ISSUE TITLE
[FR] wrap.sh support for cmake

### ISSUE THREAD

**Issue by afshinpir** [android-ndk/ndk#915]
Hi all

As you know, `wrap.sh` is a new feature that can be used for debugging native code with ASAN.
Starting NDK 17, `APP_WRAP_SH` is added to ndk-build to automatically include `wrap.sh` into your apk. But this feature is missing when we try to use cmake to build our native library. Check following `CMakeList.txt`:
```
cmake_minimum_required(VERSION 3.4.1)

add_library(hello-jni SHARED
            hello-jni.c)

# Include libraries needed for hello-jni lib
target_link_libraries(hello-jni
                      android
                      log)

add_custom_command(TARGET hello-jni POST_BUILD
                   COMMAND ${CMAKE_COMMAND} -E copy_if_different
                       ${CMAKE_CURRENT_SOURCE_DIR}/wrap.sh
                       $<TARGET_FILE_DIR:hello-jni>
                   COMMENT "Copying wrap.sh to output directory")
```
As you see, I have easily added my `wrap.sh` into my library's output folder. But since apk packaging process just include `lib*.so` inside apk, it will not be added to apk.

Since adding abi specific files is pain in gradle scripts, this can simplify gradle scripts a lot and we will be able to manage it completely inside cmake. In addition, I think adding this feature will not be too complicated.

**Comment by DanAlbert** [comment]
I don't think there's actually anything _we_ can do about this. As you've pointed out, gradle will throw away whatever we do in CMake. I don't think there's a good way to add support for this to the CMake toolchain file either (a custom command like you've shown works well, but that's definitely not something a CMake toolchain file should be doing).

Could you file this as a FR against Gradle? Follow http://b.android.com.

**Comment by nathan-fiscaletti** [comment]
Is there an alternative for enabling environment variables at run time for your application since this isn't available?

**Comment by DanAlbert** [comment]
It is available: https://developer.android.com/ndk/guides/wrap-script#packaging_wrapsh

**Comment by nathan-fiscaletti** [comment]
When using CMake @DanAlbert

**Comment by DanAlbert** [comment]
Those instructions work when you're using CMake.
