### ISSUE TITLE
[FR] Need fpucontrol.h to build lapack library

### ISSUE THREAD

**Issue by yagnasrinath** [android-ndk/ndk#917]
**Is your feature request related to a problem? Please describe.**
Android NDK doesn't come with fortran compiler. Fortran compiler is necessary to build lapack library. There is a very old c port of lapack which is clapack. But this tries to access fpu registers directly which is provided in glibc in fpucontrol.h as an extension.

**Describe the solution you'd like**
Two solutions can be possible:
1. Provide a fortran compiler along with NDK C and C++ compilers which allows us to compile lapack directly.
2. Provide fpucontrol.h as a temporary solution(not sure if it is possible on llvm as llvm itself doesn't come with it).

**Describe alternatives you've considered**
Until now we disabled all the functions that are using functions from lapack. But our customers needs them going forward.

**Additional context**

**Comment by enh** [comment]
i don't see us adding this. it looks like `CLAPACK-3.2.1/F2CLIBS/libf2c/uninit.c` also has code to use the standard `<fenv.h>` --- you should probably use that instead.

**Comment by alexcohn** [comment]
NDK toolchains are open-source. Have you tried to add FORTRAN front-end with https://github.com/flang-compiler/flang ?

**Comment by yagnasrinath** [comment]
I did check flang sometime back. They don't seem to support cross compilation.
