### ISSUE TITLE
[BUG] Unable to build QT-based application with external QT installation

### ISSUE THREAD

**Issue by PeterPetrik** [android-ndk/ndk#919]
I have this folder structure
```
/opt/android-ndk-r19b
/opt/Qt/5.11.2/android_armv7
```
and I want to use `Qt5CoreConfig.cmake` from `/opt/Qt/5.11.2/android_armv7/lib/cmake/...`
With the recent fix in r19b https://github.com/android-ndk/ndk/issues/890, the `/opt/Qt/` path is ignored.

Would it be possible to use `if` in setting `CMAKE_FIND_ROOT_PATH` so one can set this list outside and include also Qt folder (so we do not need to allow other host's paths) 

```
if(NOT CMAKE_FIND_ROOT_PATH)
   set(CMAKE_FIND_ROOT_PATH “${ANDROID_NDK}“)
endif()
```

#### Environment Details
* NDK Version: r19b
* Build system: cmake
* Host OS: Mac Mojave
* Compiler: Clang

**Comment by DanAlbert** [comment]
https://github.com/android-ndk/ndk/issues/912

**Comment by PeterPetrik** [comment]
thanks, any idea when r19c will be out?

**Comment by DanAlbert** [comment]
Soon.
