### ISSUE TITLE
[BUG] standalone clang batch files point to clang++ on Windows

### ISSUE THREAD

**Issue by eliasnaur** [android-ndk/ndk#920]
--------------------------------------------------------------------------------

#### Description

Invoking the new in r19b standalone clang on Windows gave me this weird error:

`clang++.exe: error: treating 'c' input as 'c++' when in C++ mode, this behavior is deprecated [-Werror,-Wdeprecated]`

It turns out that the Windows clang *.cmd actually points to clang++. For example, the content of `toolchains\llvm\prebuilt\windows-x86_64\bin\armv7a-linux-androideabi16-clang.cmd`  is below. Note the references to "clang++.exe"

```
@echo off
setlocal
call :find_bin
if "%1" == "-cc1" goto :L

set "_BIN_DIR=" && %_BIN_DIR%clang++.exe --target=armv7a-linux-androideabi16 -fno-addrsig -stdlib=libc++ %*
if ERRORLEVEL 1 exit /b 1
goto :done

:L
rem Target is already an argument.
set "_BIN_DIR=" && %_BIN_DIR%clang++.exe %*
if ERRORLEVEL 1 exit /b 1
goto :done

:find_bin
rem Accommodate a quoted arg0, e.g.: "clang"
rem https://github.com/android-ndk/ndk/issues/616
set _BIN_DIR=%~dp0
exit /b

:done
```

Using the builtin standalone clangs from Linux or macOS works fine. Editing the Windows batch files to refer to clang.exe instead of clang++.exe also fixes the problem.

Another thing is that it seems that there are no clang++ Windows batch files included. I don't need clang++, but that might be part of the issue.

#### Environment Details
* NDK Version: r19b
* Build system: Using clang directly with CC= for a Go Android project.
* Host OS: Windows 10 64-bit
* Compiler: clang

**Comment by DanAlbert** [comment]
> Another thing is that it seems that there are no clang++ Windows batch files included. I don't need clang++, but that might be part of the issue.

Yep, typo meant both wrappers were written to the same location, so the clang++ one clobbered the clang one.

https://android-review.googlesource.com/c/platform/ndk/+/914453

**Comment by DanAlbert** [comment]
Merged into r19.
