### ISSUE TITLE
[BUG] Email implicit intents cannot load attachments

### ISSUE THREAD

**Issue by keldavis** [android-ndk/ndk#921]
#### Description

Email Implicit intent cannot attach file. 

I have recreated the methods from the [Building Intents](https://developer.android.com/training/basics/intents/sending?authuser=1#java) developer page and the [Common Intents](https://developer.android.com/guide/components/intents-common) developer page. 

`Intent emailIntent = new Intent(Intent.ACTION_SEND);
// The intent does not have a URI, so declare the "text/plain" MIME type
emailIntent.setType(HTTP.PLAIN_TEXT_TYPE);
emailIntent.putExtra(Intent.EXTRA_EMAIL, new String[] {"jon@example.com"}); // recipients
emailIntent.putExtra(Intent.EXTRA_SUBJECT, "Email subject");
emailIntent.putExtra(Intent.EXTRA_TEXT, "Email message text");
emailIntent.putExtra(Intent.EXTRA_STREAM, Uri.parse("content://path/to/email/attachment"));
// You can also attach multiple items by passing an ArrayList of Uris`

#### Environment Details

* Host OS: Windows

* NDK API level: 28
* Device API level: 27

**Comment by enh** [comment]
You're in the wrong place... That's Java, not C++ :-)
