### ISSUE TITLE
[BUG] iconv.h can interfere for API < 28

### ISSUE THREAD

**Issue by iguessthislldo** [android-ndk/ndk#922]
#### Description

For API 28, the fact that it has iconv is nice, but the `iconv.h` sitting in the sysroot causes problems if the API is less than 28. In particular I'm making sure Xerces-C++ can be used in our library for all API Levels supported in the recent NDKs. We are building it using CMake and the NDKs `CrossCompile.cmake`. Xerces has to be patched to allow a custom iconv that's not the system iconv (a separate issue that I hope to submit a fix for), but once it is patched, during its checks CMake (or more precisely the compiler) finds the iconv.h in the NDK first and rejects it because the iconv functions are not defined.

This requires either patching Xerces further by getting rid of checks for iconv, which the Xerces devs wouldn't accept or by deleting `iconv.h` if someone knows they're not going to compile for API>=28. I would like to be able to compile Xerces with the NDK without modifying anything in either.

#### Environment Details

* NDK Version: 19.0.5232133
* Build system: cmake
* Host OS: Ubuntu 18.04
* Compiler: Clang
* NDK API level: Any Less than <28

**Comment by DanAlbert** [comment]
The presence of a header is not a good proxy for the presence of an API. The CMake check should be checking for the availability of the APIs it needs (`check_function_exists`).

I don't disagree that it would be nice if this were simpler, but unfortunately it's reality that's complicated here, and the tools need to reflect that. The only alternative that we have is to revert to a pre-unified headers architecture, which had problems that *couldn't* be simply worked around by asking a more specific question.
