### ISSUE TITLE
[BUG] feature test macros for c++17 are not defined

### ISSUE THREAD

**Issue by robertoleksy** [android-ndk/ndk#924]
Feature test macros for c++17 like `__cpp_lib_byte` are not defined. I.e. this code not works.
`#if __cpp_lib_byte`
	`// macro defined`
`#else`
	`static_assert(false, "macro is not set");`
`#endif`

**Comment by enh** [comment]
upstream claims otherwise: https://libcxx.llvm.org/docs/FeatureTestMacroTable.html

...and it seems to be in our internal libc++.

ah, but most of the content of this file was added this January: https://reviews.llvm.org/D56750

and, yes, checking r19b shows that it doesn't have this yet.

**Comment by DanAlbert** [comment]
I don't think I've done an update to libc++ in master since the one for r19 (but it's been a long time since r19 branched, so maybe I have and just don't remember), so this probably isn't in r20 beta 1, but I can do it for beta 2.

**Comment by DanAlbert** [comment]
Merged to master. Will merge into r20 just as soon as beta 1 is finalized. Keeping the bug open for now to track that.

**Comment by DanAlbert** [comment]
Beta 2 had very quick turn around so we didn't have much time to do much other than merge Q API changes, so we're doing a beta 3 for actual NDK changes. I've prepared the merge for this: https://android-review.googlesource.com/q/topic:"ndk-r20-libcxx"

**Comment by DanAlbert** [comment]
Merged into beta 3.
