### ISSUE TITLE
make-standalone-toolchain.sh didn't work on Mac 10.11.4

### ISSUE THREAD

**Issue by gohome** [android-ndk/ndk#93]
Similar to https://github.com/android-ndk/ndk/issues/41. There is no prebuilt toolchains for "darwin-x86" on NDK for Mac but the computed $HOST_TAG is always "darwin-x86" on OSX 10.11.4 (should be darwin-x86_64). Not sure the way you did in ndk-common.sh to get $HOST_ARCH is still correct.

Also, the --system option is removed since r11, thus no way to override the value of $HOST_TAG

**Comment by DanAlbert** [comment]
I've actually completely rewritten that tool for r12, and it doesn't have this problem. Sorry for the breakage.
