### ISSUE TITLE
[BUG] After I have switched to Libc++ my application is crashing on usage of unordered_map

### ISSUE THREAD

**Issue by bhupeshpant19jan** [android-ndk/ndk#930]
#### Description

We are in the process of migrating from gnustl to libc++. After the migration we are seeing crashes, upon investigation, I have observed that somhow the map is getting corrupted and when we are trying to search for the key we are getting the crash.

I am exactly seeing the crash here,
```

   if (__nd != nullptr)
        {
            for (__nd = __nd->__next_; __nd != nullptr &&
                (__nd->__hash() == __hash
                  || __constrain_hash(__nd->__hash(), __bc) == __chash);
                                                           __nd = __nd->__next_)
            {
                if ((__nd->__hash() == __hash)
                    && key_eq()(__nd->__upcast()->__value_, __k))
#if _LIBCPP_DEBUG_LEVEL >= 2
                    return iterator(__nd, this);
#else
                    return iterator(__nd);
#endif
            }
        }
```

I am able to replicate this issue in my code base with the key I have already inserted and key I am trying to use find in the unordered_map. The iterative command **__nd = __nd->__next_** is populating corrupted value to that variable.
__nd = 0xcccccccd

we are first trying to insert these as keys with config object as value,
```
TimerPoolShutdownTimeout 
WorkerObjectsShutdownTimeout 
PeriodicTimerShutdownTimeout 
```
 and then we are trying to query the map that whether **"featureafterregistryread"** already exists or not using find function we are seeing the crash.

#### Environment Details

Not all of these will be relevant to every bug, but please provide as much
information as you can.

* NDK Version: Value from Pkg.Revision in ndk-bundle/source.properties. If not
  the latest version, check there before filing.
* Build system: ndk-build? cmake? standalone toolchain? custom? (if gradle, file
  a bug against studio as specified above)
* Host OS: Windows, Mac, or Linux? Which Linux?
* Compiler: If GCC, check Clang before filing. GCC is no longer supported.
* ABI:
* STL: libc++
* NDK API level: r16
* Device API level: 23

**Comment by DanAlbert** [comment]
> I have observed that somhow the map is getting corrupted

That sounds like an app bug. Try https://github.com/google/sanitizers/wiki/AddressSanitizerOnAndroid

If you think this isn't an app bug, we need a repro case. There's nothing actionable here.
