### ISSUE TITLE
[BUG] `getloadavg` exists in libc.so of API 29 but not declared in stdlib.h

### ISSUE THREAD

**Issue by yan12125** [android-ndk/ndk#932]
#### Description

`getloadavg` exists in libc.so of API 29:
```
$ nm /opt/android-ndk-beta/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/lib/arm-linux-androideabi/29/libc.so | grep getloadavg
0000eacf T getloadavg
```
But not in stdlib.h:
```
$ rg -A 1 -B 1 'int getloadavg' /opt/android-ndk-beta/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include
/opt/android-ndk-beta/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/include/stdlib.h
206-#if __ANDROID_API__ >= __ANDROID_API_FUTURE__
207:int getloadavg(double __averages[], int __n) __INTRODUCED_IN_FUTURE;
208-#endif /* __ANDROID_API__ >= __ANDROID_API_FUTURE__ */
```

Such a difference prevents building CPython. CPython uses the m4 macro `AC_CHECK_FUNCS` to determine whether `getloadavg` is available or not [1]. This m4 macro only checks whether a symbol exists or not, but not whether a function is declared or not. The result is compilation failure:
```
./Modules/posixmodule.c:11390:9: error: implicit declaration of function 'getloadavg' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
    if (getloadavg(loadavg, 3)!=3) {
        ^
```
A full log can be found in [2].

/cc @enh - the author of the relevant Gerrit revision [3].

[1] https://github.com/python/cpython/blob/f2f55e7f03d332fd43bc665a86d585a79c3b3ed4/configure.ac#L3519
[2] https://ci.chyen.cc/api/v2/logs/2759/raw
[3] https://android-review.googlesource.com/c/platform/bionic/+/799647

#### Environment Details

* NDK Version: NDK r20 beta 1
* Build system: custom
* Host OS: Arch Linux
* Compiler: Clang
* ABI: ARM
* STL: N/A
* NDK API level: 29
* Device API level: N/A - build issue

**Comment by enh** [comment]
d'oh, yeah, it's time to replace `__INTRODUCED_IN_FUTURE` with `__INTRODUCED_IN(29)`.

i might just take the opportunity to remove `__INTRODUCED_IN_FUTURE`. i'm not sure it's buying us anything, and it's probably easier to remove it than to add some kind of check that we don't release an NDK that's supposed to offer "this year's" API with `__INTRODUCED_IN_FUTURE` still present...

**Comment by enh** [comment]
fix uploaded: https://android-review.googlesource.com/c/platform/bionic/+/929714

**Comment by yan12125** [comment]
> fix uploaded: https://android-review.googlesource.com/c/platform/bionic/+/929714

Great! Can I expect the fix to be available in r20 beta 2?

**Comment by DanAlbert** [comment]
Yeah, we'll make sure it gets cherry-picked for that.

**Comment by DanAlbert** [comment]
(beta 2 ended up being an incredibly quick turnaround, but we're doing a beta 3 for r20 so it'll be in that)

**Comment by yan12125** [comment]
No problem, thanks for the information!

**Comment by DanAlbert** [comment]
Merged into beta 3.
