### ISSUE TITLE
sources\cxx-stl\gabi++\libs\ directory is missing from android-ndk-r11c-windows-x86_64.zip and android-ndk-r12-beta1-windows-x86_64.zip

### ISSUE THREAD

**Issue by nvidiamfilimonov** [android-ndk/ndk#94]
sources\cxx-stl\gabi++\libs\ directory is missing from NDK r11c and r12 beta 1
>android-ndk-r11c-windows-x86_64.zip
>android-ndk-r12-beta1-windows-x86_64.zip so 

so you can't link the code if your application is using this STL variant.

**Comment by DanAlbert** [comment]
It's included in stlport. Just use that.
