### ISSUE TITLE
NDK build x264 static library for abi:arm64-v8a contains many undefined references when link with ffmpeg 

### ISSUE THREAD

**Issue by cmeng-git** [android-ndk/ndk#940]
I am trying to build ffmpeg with codec x264 integration for abi:arm64-v8a native library for inclusion with aTalk; but facing problems with many undefined references in libx264.a:
Please refer to the site on aTalk: https://github.com/cmeng-git/atalk-android

#### Environment Details #######
* NDK Version: ndk-r15c using gcc/g++
* Build system: SDK toolschains
* Host OS: Ubuntu 18.04
* ABI: arm64-v8a
* NDK API level: 21
* Device API level: 21

Current aTalk v1.7.3 is only compatible (tested with) with the following ffmpeg and x264 versions 
i.e. ffmpeg-v1.0.10 and x264- v152 (highest x264 version that is compatible with ffmpeg 1.0.10).
I was able to build ffmpeg for ABIS=("armeabi-v7a" "arm64-v8a" "x86" "x86_64") with the attached build scripts. However for arm64-v8a build, it is required to set linker to ignore any undefined references with the following settings i.e.:
a. ffmpeg-x264_build_settings.sh: 
ADDI_LDFLAGS="-Wl,--unresolved-symbols=ignore-in-shared-libs"

b. android.mk (aTalk/jni)
LOCAL_DISABLE_FATAL_LINKER_WARNINGS := true
LOCAL_ALLOW_UNDEFINED_SYMBOLS := true

```
without the "-Wl,--unresolved-symbols=ignore-in-shared-libs"; ndk build will have errors on undefined references (see x264_build_arm64-v8a.sh for full list) for all version of x264 i.e. v147, v152, v157 when linked with ffmpeg

#/opt/android/android-ndk-r15c//toolchains/aarch64-linux-android-4.9/prebuilt/linux-x86_64/bin/aarch64-linux-android-gcc -lc -lm -ldl -llog -Wl,-z,defs -L../android/arm64-v8a/lib -lx264 --sysroot=/opt/android/android-ndk-r15c//platforms/android-21/arch-arm64 -o /tmp/ffconf.xRNiiZtH /tmp/ffconf.SEhNtBoJ.o -lgcc
#../android/arm64-v8a/lib/libx264.so: undefined reference to `x264_nal_escape_neon'
#../android/arm64-v8a/lib/libx264.so: undefined reference to `x264_pixel_hadamard_ac_8x8_neon'
#../android/arm64-v8a/lib/libx264.so: undefined reference to `x264_decimate_score16_neon'
#../android/arm64-v8a/lib/libx264.so: undefined reference to `x264_pixel_sad_x4_4x4_neon'
```

The followings jni/libjnffmpeg.so have been tested working on aTalk i.e.
a. abi:armeabi-v7a on Note-8 and Note-3 (need to exclude  "arm64-v8a" ABI from aTalk)
b. abi:"x86_64" on AVD Pixel-2-API-28

However when jni/libjnffmpeg.so for abi:arm64-v8a is used on Note-8, aTalk immediately displays error as shown in Screenshot_20190325-092048_aTalk on launch. I have also tried to build ffmpeg with x264-157 (only for testing the undefined symbols), it too throws similar error as above when aTalk is launched.

I have done a quick check on x264 source, and found the undefined references are actually being defined in asm files.
I am not sure why the x264 undefined symbols are not being exported when building the libx264.a; x264 configure error or ndk linker error?
Any help is much appreciated.

I also try to build ffmpeg-x264 with clang (https://github.com/cmeng-git/ffmpeg-android), the undefined references also appear in libx264.a library.

![Screenshot_20190325-092048_aTalk](https://user-images.githubusercontent.com/7959606/54896693-5f5c7580-4f00-11e9-8a0e-433d0a2cbae9.jpg)
[ffmpeg-x264_buildScript.zip](https://github.com/android-ndk/ndk/files/3001640/ffmpeg-x264_buildScript.zip)

**Comment by cmeng-git** [comment]
Here are two additional scripts if you want to fetch the ffmpeg & x264 and applying the patches.
a. ./init_update_libs.sh
b. ./ffmpeg-x264_patch.sh

[initlib-patches.zip](https://github.com/android-ndk/ndk/files/3002090/initlib-patches.zip)

**Comment by DanAlbert** [comment]
This doesn't look like an NDK bug. Your libraries are either not being built properly or linked properly.

If you think this _is_ an NDK bug, you'll need to try r19 first since we don't support GCC any more.

**Comment by enh** [comment]
(yeah, the mentions of "neon" in the missing symbols makes me wonder if you're building code that doesn't actually support arm64, and is assuming 32-bit arm instead?)

**Comment by cmeng-git** [comment]
Thank for the clarifications. Yes it is my configuration error:
After reviewing the configure, config.mak and Makefile files, I realize that I must not include the following option. It is actually used by configure to define AS and also to include the required *.S assembly files for compilation. Everything is working now.

 --disable-asm            disable platform-specific assembly optimizations

**Comment by iBotasky** [comment]
I got the same issue while i build the x264 64bit .so file with NDK 15c, How do you solve this problem?
this is my build shell:
```
NDK=/Users/botaskywells/Downloads/android-ndk-r15c
configure()
{
    CPU=$1
    PREFIX=/Users/botaskywells/Downloads/$CPU
    HOST=""
    CROSS_PREFIX=""
    SYSROOT=""
    if [ "$CPU" == "armv7-a" ]
    then
        HOST=arm-linux
        SYSROOT=$NDK/platforms/android-21/arch-arm/
        CROSS_PREFIX=$NDK/toolchains/arm-linux-androideabi-4.9/prebuilt/darwin-x86_64/bin/arm-linux-androideabi-
    else
        HOST=aarch64-linux-android
        SYSROOT=$NDK/platforms/android-21/arch-arm64/
        CROSS_PREFIX=$NDK/toolchains/aarch64-linux-android-4.9/prebuilt/darwin-x86_64/bin/aarch64-linux-android-
    fi
    ./configure \
    --prefix=$PREFIX \
    --host=$HOST \
    --enable-pic \
    --enable-static \
    --enable-shared \
    --disable-asm \
    --disable-cli \
    --cross-prefix=$CROSS_PREFIX \
    --sysroot=$SYSROOT 
}

build()
{
    make clean
    cpu=$1
    echo "build $cpu"

    configure $cpu
    #-j<CPU核心数>
    make -j4
    make install
}

# build armv7-a
build armv8-a
```

**Comment by iBotasky** [comment]
I remove --disable-asm and it works fine.
