### ISSUE TITLE
upgrade to a newer version of make

### ISSUE THREAD

**Issue by DanAlbert** [android-ndk/ndk#947]
Studio is asking for us to upgrade to a newer version of make so they can take advantage of improved error reporting (apparently it now has an option to buffer error output so it doesn't get interleaved, which would allow Studio do display ndk-build compile errors in a much more useful format).

We'd also be able to fix a couple other bugs by doing this:
* https://github.com/android-ndk/ndk/issues/284
* Can't find it now, but we have some open Windows issues that would be resolved by moving our response file generation over to https://www.gnu.org/software/make/manual/html_node/File-Function.html#File-Function

**Comment by alexcohn** [comment]
Also, https://github.com/android-ndk/ndk/issues/676#issuecomment-463640713

**Comment by huww98** [comment]
I've just hit https://github.com/android-ndk/ndk/issues/676#issuecomment-463640713, and spent hours to investigate on it. This prevents Android Studio from determine the correct include path for gstreamer (which executes `pkg-config` to get these path). Finally, I have to manually add include path to LOCAL_C_INCLUDES to make Android Studio happy.

Hopes this can be fixed, or gstreamer can switch to CMake.

**Comment by DanAlbert** [comment]
I don't see how #676 is related.

Make 4.2.1 is in r21.

**Comment by alexcohn** [comment]
@DanAlbert , #676 is related because on Windows with current **make**, `make -n` does not execute `$shell` commands.

**Comment by enh** [comment]
do you have a reference that suggests that make 4.2.1 fixes that though? i tried to find something but failed when i looked the other day...

**Comment by alexcohn** [comment]
@enh my experiment shows that it does fix $shell behavior on WIndows 10 with cmd.exe as $SHELL.

**Comment by enh** [comment]
nice! that's an added bonus. i don't think we knew that when we upgraded :-)
