### ISSUE TITLE
[BUG] error: cannot find -lc++

### ISSUE THREAD

**Issue by ericLemanissier** [android-ndk/ndk#951]
#### Description

When trying to link a program using `toolchains/llvm/prebuilt/linux-x86_64/bin/armv7a-linux-androideabi21-clang++`, it fails with error `...toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: cannot find -lc++`
I think it should be solved by removing the ` -stdlib=libc++` argument in all the files `*-clang++` in folder `toolchains\llvm\prebuilt\linux-x86_64\bin\`

#### Environment Details

* NDK Version: 19.2.5345600
* Build system: Standalone toolchain
* Host OS: Linux

**Comment by DanAlbert** [comment]
Can you provide the full command line?

**Comment by ericLemanissier** [comment]
sure:
```
> /path/to/ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/armv7a-linux-androideabi21-clang++ -Wl,--exclude-libs,libgcc.a -Wl,--exclude-libs,libatomic.a -Wl,--exclude-libs,libunwind.a --sysroot=/path/to/ndk/platforms/android-21/arch-arm/ -Wl,-soname,libverifyspec.so -Wl,--no-undefined -Wl,-z,noexecstack -shared -o libverifyspec.so verifyspec.o     -L/path/to/ndk/sources/cxx-stl/llvm-libc++/libs/armeabi-v7a /path/to/ndk/sources/cxx-stl/llvm-libc++/libs/armeabi-v7a/libc++.so.21 -llog -lz -lm -ldl -lc
> /path/to/ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/../lib/gcc/arm-linux-androideabi/4.9.x/../../../../arm-linux-androideabi/bin/ld: error: cannot find -lc++
```
Switching from `/path/to/ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/armv7a-linux-androideabi21-clang++` to `/path/to/ndk/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++ -target armv7-none-linux-androideabi` is a way to workaround the problem

**Comment by DanAlbert** [comment]
Stop passing `--sysroot`. It's unnecessary and you have the wrong path. See https://android.googlesource.com/platform/ndk/+/ndk-release-r19/docs/BuildSystemMaintainers.md.

**Comment by ericLemanissier** [comment]
Ok, so I removed the `--sysroot` argument, and still the link if failing:
```
> /android-ndk-r19c/toolchains/llvm/prebuilt/linux-x86_64/bin/x86_64-linux-android21-clang++ -c -D__ANDROID_API__=21 -target x86_64-none-linux-android -gcc-toolchain /android-ndk-r19c/toolchains/x86_64-4.9/prebuilt/linux-x86_64 -fno-limit-debug-info -DANDROID_HAS_WSTRING -isystem /android-ndk-r19c/sysroot/usr/include/x86_64-linux-android -isystem /android-ndk-r19c/sources/cxx-stl/llvm-libc++/include -isystem /android-ndk-r19c/sources/android/support/include -isystem /android-ndk-r19c/sources/cxx-stl/llvm-libc++abi/include -fstack-protector-strong -DANDROID -ftemplate-depth=1024 -O2 -O2 -fPIC  -I/home/conan/.conan/data/qt/5.13.0-beta1/bincrafters/testing/source/qt5/qtbase/config.tests/verifyspec -I. -I/home/conan/.conan/data/qt/5.13.0-beta1/bincrafters/testing/source/qt5/qtbase/mkspecs/android-clang -o verifyspec.o /home/conan/.conan/data/qt/5.13.0-beta1/bincrafters/testing/source/qt5/qtbase/config.tests/verifyspec/verifyspec.cpp
> /android-ndk-r19c/toolchains/llvm/prebuilt/linux-x86_64/bin/x86_64-linux-android21-clang++ -D__ANDROID_API__=21 -target x86_64-none-linux-android -gcc-toolchain /android-ndk-r19c/toolchains/x86_64-4.9/prebuilt/linux-x86_64 -fno-limit-debug-info -Wl,--exclude-libs,libgcc.a -Wl,--exclude-libs,libatomic.a -Wl,-soname,libverifyspec.so -Wl,--no-undefined -Wl,-z,noexecstack -shared -o libverifyspec.so verifyspec.o     -L/android-ndk-r19c/sources/cxx-stl/llvm-libc++/libs/x86_64 /android-ndk-r19c/sources/cxx-stl/llvm-libc++/libs/x86_64/libc++.so.21 -llog -lz -lm -ldl -lc
> /android-ndk-r19c/toolchains/x86_64-4.9/prebuilt/linux-x86_64/lib/gcc/x86_64-linux-android/4.9.x/../../../../x86_64-linux-android/bin/ld: error: cannot open crtbegin_so.o: No such file or directory
> /android-ndk-r19c/toolchains/x86_64-4.9/prebuilt/linux-x86_64/lib/gcc/x86_64-linux-android/4.9.x/../../../../x86_64-linux-android/bin/ld: error: cannot open crtend_so.o: No such file or directory
> /android-ndk-r19c/toolchains/x86_64-4.9/prebuilt/linux-x86_64/lib/gcc/x86_64-linux-android/4.9.x/../../../../x86_64-linux-android/bin/ld: error: cannot find -llog
> /android-ndk-r19c/toolchains/x86_64-4.9/prebuilt/linux-x86_64/lib/gcc/x86_64-linux-android/4.9.x/../../../../x86_64-linux-android/bin/ld: error: cannot find -lc++
```

**Comment by DanAlbert** [comment]
Don't pass `-gcc-toolchain`. Please read the documentation I linked.

**Comment by DanAlbert** [comment]
Quick follow up after having discussed this with another person that encountered this:

I think there are two ways that you can get into this state:

1. You've only partially migrated to the new toolchain format. That seems to be what the OP has done (please correct me if I'm wrong; I'm relying on command line forensics with that guess) by switching to the triple-prefixed Clangs, but still keeping all the old flags. Partial migrations are very likely to run into these sorts of problems, and it's best to just clean up all your flags at the same time.

2. You haven't started migrating at all, but now your build is broken. Presumably the reason this happens because your build wasn't passing `-nostdlib++` in prior releases. This flag is fairly new and the result of not passing it was fairly innocuous (even ndk-build and the CMake toolchain didn't do this until somewhat recently), so it was easy to forget. However it's something that you *should* be using if you're manually linking libc++. If you just add that flag that should let you continue using NDK r20 without more involved modifications to your build system (though you'll want to start looking into this soon, I'm guessing that r22 will be the release that does away with the legacy paths).

**Comment by ericLemanissier** [comment]
Thanks for following-up. The project I'm trying to build is Qt, and [their documentation ](https://doc.qt.io/qt-5/android.html)does not mention the supported ndk versions(except for a [wiki page](https://wiki.qt.io/Android) mentionning r18b)
I guess they did not migrate to the new toolchain format, and I'm not sure they require backward compatibility or not. 
Most of the logic involved in the clang build is in this file: https://code.qt.io/cgit/qt/qtbase.git/tree/mkspecs/android-clang/qmake.conf. From your message, do I understand correctly that we should add flag `-nostdlib++` to line 52 `ANDROID_CXX_STL_LIBS = $$ANDROID_SOURCES_CXX_STL_LIBDIR/libc++.so.$$replace(ANDROID_PLATFORM, "android-", "")` ?
We probably need to add `-nostdinc++` to QMAKE_CFLAGS as well right ?

**Comment by DanAlbert** [comment]
That seems likely, yes.

**Comment by Stokestack** [comment]
I'm having the same problem, also in Qt. Did you get your build working, Eric?

**Comment by triplef** [comment]
Looks like this is being tracked and fixed by Qt already:
https://bugreports.qt.io/browse/QTBUG-76293
