### ISSUE TITLE
[BUG]Build command failed.

### ISSUE THREAD

**Issue by q805699513** [android-ndk/ndk#955]
Build command failed.
Error while executing process C:\Users\longshaohua\AppData\Local\Android\Sdk\cmake\3.6.4111459\bin\cmake.exe with arguments {--build D:\sf-locker\app\.externalNativeBuild\cmake\debug\armeabi-v7a --target Face}
[1/4] Building C object CMakeFiles/Face.dir/src/main/cpp/include/cJSON.c.o
[2/4] Building CXX object CMakeFiles/Face.dir/src/main/cpp/FSBoxFR.cpp.o
[3/4] Building CXX object CMakeFiles/Face.dir/src/main/cpp/native-lib.cpp.o
FAILED: D:\android-ndk-r16b-windows-x86_64\android-ndk-r16b\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe  --target=armv7-none-linux-androideabi --gcc-toolchain=D:/android-ndk-r16b-windows-x86_64/android-ndk-r16b/toolchains/arm-linux-androideabi-4.9/prebuilt/windows-x86_64 --sysroot=D:/android-ndk-r16b-windows-x86_64/android-ndk-r16b/sysroot  -DFace_EXPORTS -I../../../../src/main/cpp/include -I../../../../src/main/cpp -isystem D:/android-ndk-r16b-windows-x86_64/android-ndk-r16b/sources/cxx-stl/gnu-libstdc++/4.9/include -isystem D:/android-ndk-r16b-windows-x86_64/android-ndk-r16b/sources/cxx-stl/gnu-libstdc++/4.9/libs/armeabi-v7a/include -isystem D:/android-ndk-r16b-windows-x86_64/android-ndk-r16b/sources/cxx-stl/gnu-libstdc++/4.9/include/backward -isystem D:/android-ndk-r16b-windows-x86_64/android-ndk-r16b/sysroot/usr/include/arm-linux-androideabi -D__ANDROID_API__=21 -g -DANDROID -ffunction-sections -funwind-tables -fstack-protector-strong -no-canonical-prefixes -march=armv7-a -mfloat-abi=softfp -mfpu=vfpv3-d16 -fno-integrated-as -mthumb -Wa,--noexecstack -Wformat -Werror=format-security   -fopenmp -O2 -fvisibility=hidden -fvisibility-inlines-hidden -fomit-frame-pointer -fstrict-aliasing -ffunction-sections -fdata-sections -ffast-math   -std=c++11 -frtti -fexceptions -O0 -fno-limit-debug-info  -fPIC -MD -MT CMakeFiles/Face.dir/src/main/cpp/native-lib.cpp.o -MF CMakeFiles\Face.dir\src\main\cpp\native-lib.cpp.o.d -o CMakeFiles/Face.dir/src/main/cpp/native-lib.cpp.o -c D:\sf-locker\app\src\main\cpp\native-lib.cpp
In file included from D:\sf-locker\app\src\main\cpp\native-lib.cpp:3:

D:\android-ndk-r16b-windows-x86_64\android-ndk-r16b\toolchains\llvm\prebuilt\windows-x86_64\lib64\clang\5.0.300080\include\altivec.h:27:2: error: "AltiVec support not enabled"

#error "AltiVec support not enabled"

 ^

D:\android-ndk-r16b-windows-x86_64\android-ndk-r16b\toolchains\llvm\prebuilt\windows-x86_64\lib64\clang\5.0.300080\include\altivec.h:62:19: error: unknown type name 'vector'

static __inline__ vector signed char __ATTRS_o_ai vec_perm(

                  ^

D:\android-ndk-r16b-windows-x86_64\android-ndk-r16b\toolchains\llvm\prebuilt\windows-x86_64\lib64\clang\5.0.300080\include\altivec.h:62:26: error: expected unqualified-id

static __inline__ vector signed char __ATTRS_o_ai vec_perm(

                         ^

D:\android-ndk-r16b-windows-x86_64\android-ndk-r16b\toolchains\llvm\prebuilt\windows-x86_64\lib64\clang\5.0.300080\include\altivec.h:65:19: error: unknown type name 'vector'

static __inline__ vector unsigned char __ATTRS_o_ai

                  ^

D:\android-ndk-r16b-windows-x86_64\android-ndk-r16b\toolchains\llvm\prebuilt\windows-x86_64\lib64\clang\5.0.300080\include\altivec.h:65:26: error: expected unqualified-id

static __inline__ vector unsigned char __ATTRS_o_ai

                         ^

D:\android-ndk-r16b-windows-x86_64\android-ndk-r16b\toolchains\llvm\prebuilt\windows-x86_64\lib64\clang\5.0.300080\include\altivec.h:69:19: error: unknown type name 'vector'

static __inline__ vector bool char __ATTRS_o_ai

                  ^

D:\android-ndk-r16b-windows-x86_64\android-ndk-r16b\toolchains\llvm\prebuilt\windows-x86_64\lib64\clang\5.0.300080\include\altivec.h:69:26: error: expected unqualified-id

static __inline__ vector bool char __ATTRS_o_ai

                         ^

D:\android-ndk-r16b-windows-x86_64\android-ndk-r16b\toolchains\llvm\prebuilt\windows-x86_64\lib64\clang\5.0.300080\include\altivec.h:72:19: error: unknown type name 'vector'

static __inline__ vector short __ATTRS_o_ai vec_perm(vector signed short __a,

                  ^

D:\android-ndk-r16b-windows-x86_64\android-ndk-r16b\toolchains\llvm\prebuilt\windows-x86_64\lib64\clang\5.0.300080\include\altivec.h:72:26: error: expected unqualified-id

static __inline__ vector short __ATTRS_o_ai vec_perm(vector signed short __a,

                         ^

D:\android-ndk-r16b-windows-x86_64\android-ndk-r16b\toolchains\llvm\prebuilt\windows-x86_64\lib64\clang\5.0.300080\include\altivec.h:76:19: error: unknown type name 'vector'

static __inline__ vector unsigned short __ATTRS_o_ai

                  ^

D:\android-ndk-r16b-windows-x86_64\android-ndk-r16b\toolchains\llvm\prebuilt\windows-x86_64\lib64\clang\5.0.300080\include\altivec.h:76:26: error: expected unqualified-id

static __inline__ vector unsigned short __ATTRS_o_ai

                         ^

D:\android-ndk-r16b-windows-x86_64\android-ndk-r16b\toolchains\llvm\prebuilt\windows-x86_64\lib64\clang\5.0.300080\include\altivec.h:80:19: error: unknown type name 'vector'

static __inline__ vector bool short __ATTRS_o_ai vec_perm(

                  ^

D:\android-ndk-r16b-windows-x86_64\android-ndk-r16b\toolchains\llvm\prebuilt\windows-x86_64\lib64\clang\5.0.300080\include\altivec.h:80:26: error: expected unqualified-id

static __inline__ vector bool short __ATTRS_o_ai vec_perm(

                         ^

D:\android-ndk-r16b-windows-x86_64\android-ndk-r16b\toolchains\llvm\prebuilt\windows-x86_64\lib64\clang\5.0.300080\include\altivec.h:83:19: error: unknown type name 'vector'

static __inline__ vector pixel __ATTRS_o_ai vec_perm(vector pixel __a,

                  ^

D:\android-ndk-r16b-windows-x86_64\android-ndk-r16b\toolchains\llvm\prebuilt\windows-x86_64\lib64\clang\5.0.300080\include\altivec.h:83:32: error: '__overloadable__' attribute only applies to functions

static __inline__ vector pixel __ATTRS_o_ai vec_perm(vector pixel __a,

                               ^

D:\android-ndk-r16b-windows-x86_64\android-ndk-r16b\toolchains\llvm\prebuilt\windows-x86_64\lib64\clang\5.0.300080\include\altivec.h:56:37: note: expanded from macro '__ATTRS_o_ai'

#define __ATTRS_o_ai __attribute__((__overloadable__, __always_inline__))

                                    ^

D:\android-ndk-r16b-windows-x86_64\android-ndk-r16b\toolchains\llvm\prebuilt\windows-x86_64\lib64\clang\5.0.300080\include\altivec.h:83:44: error: expected ';' after top level declarator

static __inline__ vector pixel __ATTRS_o_ai vec_perm(vector pixel __a,

                                           ^

D:\android-ndk-r16b-windows-x86_64\android-ndk-r16b\toolchains\llvm\prebuilt\windows-x86_64\lib64\clang\5.0.300080\include\altivec.h:87:19: error: unknown type name 'vector'

static __inline__ vector int __ATTRS_o_ai vec_perm(vector signed int __a,

                  ^

D:\android-ndk-r16b-windows-x86_64\android-ndk-r16b\toolchains\llvm\prebuilt\windows-x86_64\lib64\clang\5.0.300080\include\altivec.h:87:26: error: expected unqualified-id

static __inline__ vector int __ATTRS_o_ai vec_perm(vector signed int __a,

                         ^

D:\android-ndk-r16b-windows-x86_64\android-ndk-r16b\toolchains\llvm\prebuilt\windows-x86_64\lib64\clang\5.0.300080\include\altivec.h:91:19: error: unknown type name 'vector'

static __inline__ vector unsigned int __ATTRS_o_ai vec_perm(

                  ^

fatal error: too many errors emitted, stopping now [-ferror-limit=]

20 errors generated.

ninja: build stopped: subcommand failed.

**Comment by enh** [comment]
Altivec is the PowerPC equivalent of NEON. seems like you're trying to build PowerPC code on ARM, which obviously won't work...

**Comment by q805699513** [comment]
@enh remove #include<altivec.h> ok .thank
