### ISSUE TITLE
merge vulkan changes from master

### ISSUE THREAD

**Issue by DanAlbert** [android-ndk/ndk#963]
The vulkan update to fix the files that went missing since r19 wasn't merged in time for beta 3. Pick it up before stable.

**Comment by Zingam** [comment]
The current LungarG Vulkan SDK:

> Khronos Validation Layer: VK_LAYER_KHRONOS_validation
This single, configurable layer continues the transition to a unified Khronos Vulkan ecosystem, and will replace the legacy validation layers listed below. The improved layer will also reduce platform disparities between desktop and mobile implementations, as well as increasing performance, flexibility, usability and maintainability over the long-term.
> 
> Deprecated Validation Layers:
> 
> VK_LAYER_GOOGLE_threading
> VK_LAYER_LUNARG_parameter_validation
> VK_LAYER_LUNARG_object_tracker
> VK_LAYER_LUNARG_core_validation
> VK_LAYER_GOOGLE_unique_objects
> VK_LAYER_LUNARG_standard_validation (meta-layer)

Are you syncing with that SDK or you are updating the Vulkan stuff independently? Will this new layer be available soon?

**Comment by DanAlbert** [comment]
@cnorthrop should be able to answer those questions.

**Comment by cnorthrop** [comment]
`VK_LAYER_KHRONOS_validation` for Android is already available if you build validation layers from [source](https://github.com/KhronosGroup/Vulkan-ValidationLayers/blob/master/BUILD.md#building-on-android).  We'll pull it into the NDK with the next release, along with updated documentation and such.  It didn't make r20.

**Comment by DanAlbert** [comment]
(I think this bug is still correct in that it's closed for r20, and that the things being discussed are yet another update separate from this. Is that right?)

**Comment by cnorthrop** [comment]
> (I think this bug is still correct in that it's closed for r20, and that the things being discussed are yet another update separate from this. Is that right?)

Yep.
