### ISSUE TITLE
Shared libraries cannot locate symbol "__register_atfork"

### ISSUE THREAD

**Issue by tanersener** [android-ndk/ndk#964]
#### Description
Shared libraries built by the latest NDK r19 can not locate `__register_atfork` symbol. Consequently applications fail with the following error on startup: 

`java.lang.UnsatisfiedLinkError: dlopen failed: could not load library ... caused by cannot locate symbol "__register_atfork" referenced by ... `

In my case, I'm building [ffmpeg](https://ffmpeg.org) with NDK r19c using the following two lines:
```
./configure \
--cross-prefix=${ANDROID_NDK_ROOT}/toolchains/llvm/prebuilt/linux-x86_64/bin/armv7a-linux-androideabi24- \
--sysroot=${ANDROID_NDK_ROOT}/toolchains/llvm/prebuilt/linux-x86_64/sysroot \
--arch=arm-v7a \
--target-os=android \
--ar=${ANDROID_NDK_ROOT}/toolchains/llvm/prebuilt/linux-x86_64/bin/arm-linux-androideabi-ar \
--nm=${ANDROID_NDK_ROOT}/toolchains/llvm/prebuilt/linux-x86_64/bin/arm-linux-androideabi-nm \
--ranlib=${ANDROID_NDK_ROOT}/toolchains/llvm/prebuilt/linux-x86_64/bin/arm-linux-androideabi-ranlib \
--enable-shared \
--disable-programs
make -j8
```

All `.so` files created has the following undefined symbol.

` U __register_atfork`

This error does not happen if cross-prefix uses API <= 22 (`armv7a-linux-androideabi22-`). ~~Also I remember that I didn't have this error when using NDK 19.0 or NDK 19.1.~~

#### Environment Details
* NDK Version: 19.2.5345600
* Build system: clang
* Host OS: Ubuntu 18.04.2 LTS
* ABI: armeabi-v7a
* NDK API level: 24
* Device API level: 24

**Comment by DanAlbert** [comment]
1) stop passing `--sysroot`
2) Look at a link command. The wrong crt objects are being used.

Most likely an issue with the ffmpeg configure script, so closing. No problem reopening if that's not the case.

**Comment by tanersener** [comment]
> 1. stop passing `--sysroot`

Removing `--sysroot` doesn't change anything.

> 2. Look at a link command. The wrong crt objects are being used.

Successful link command for API <= 22 and unsuccessful link command for API >= 23 is completely the same (except clang variant name). I don't specify crt objects, they are selected by clang itself and I couldn't find any documentation about selecting/specifying crt objects in NDK documentation. So I'd be glad if you can share a reference about it. 

Also I see that `__register_atfork` is defined in `libc` but appending `-lc` option has no effect.

```
armv7a-linux-androideabi24-clang -shared -Wl,-soname,libavdevice.so -Wl,-Bsymbolic \
-Wl,--version-script,libavdevice/libavdevice.ver -Llibavcodec -Llibavdevice -Llibavfilter \
-Llibavformat -Llibavresample -Llibavutil -Llibpostproc -Llibswscale -Llibswresample \
-lc  -march=armv7-a -Wl,--as-needed -Wl,-z,noexecstack -Wl,--warn-common \
-Wl,-rpath-link=:libpostproc:libswresample:libswscale:libavfilter:libavdevice:libavformat:libavcodec:libavutil:libavresample \
-Qunused-arguments  -o libavdevice/libavdevice.so.58 libavdevice/alldevices.o \
libavdevice/avdevice.o libavdevice/fbdev_common.o libavdevice/fbdev_dec.o \
libavdevice/fbdev_enc.o libavdevice/lavfi.o libavdevice/reverse.o \
libavdevice/timefilter.o libavdevice/utils.o libavdevice/v4l2-common.o \
libavdevice/v4l2.o libavdevice/v4l2enc.o -lavfilter -lswscale -lavformat -lavcodec \
-lswresample -lavutil -lm -pthread -lm -lm -lm -lz -pthread -lm -lz -lm -pthread -lm 
```

**Comment by enh** [comment]
from the libc map file:
```
    __register_atfork; # introduced=23
```

so if you tell us you target >= 23, you'd expect to see problems with `__register_atfork` if you try to run the result < 23.

are you _sure_ the device's API level is actually 24? seems like it might be 22?

**Comment by tanersener** [comment]
> are you _sure_ the device's API level is actually 24? seems like it might be 22?

Well, you are right. I thought having `U __register_atfork` inside my `.so` files was the actual error here. So I tested it only once on a physical device, which was indeed an API < 23 device. Apparently I was wrong and this is the expected behavior for target >= 23 devices. UnsatisfiedLinkError is never thrown if device's API level is >= 23 as it should be. Sorry for the confusion.

**Comment by enh** [comment]
i can't find anywhere where this is clearly documented (in particular, there's nothing in https://android.googlesource.com/platform/bionic/+/master/android-changes-for-ndk-developers.md), so reopening and assigning to myself to add some documentation...

**Comment by enh** [comment]
suggested doc change: https://android-review.googlesource.com/c/platform/bionic/+/948880

**Comment by tanersener** [comment]
@enh thanks 👍
