### ISSUE TITLE
[BUG]-lcompiler_rt-extras flag not being recognized

### ISSUE THREAD

**Issue by dibya001** [android-ndk/ndk#978]
Hi, I am using NDK Version 17 in my project. I wanted to integrate UBSAN into my project. For x86, I   was able to build my project with UBSAN enabled. Then I tried to build it for 64 bit clang architecture. I got 
**android-ndk/android-ndk-r17c/sources/cxx-stl/llvm-libc++/include/fstream:824: error: undefined reference to '__mulodi4'
clang++: error: linker command failed with exit code 1 (use -v to see invocation)**
In order to resolve the above error, I searched in Google and found that I need to add -lcompiler_rt-extras flag. So for aarch64 clang I appended this to CMAKE_C_FLAGS and CMAKE_CXX_FLAGS property. But Now I am getting another error.
/usr/bin/ld: error: cannot find -lcompiler_rt-extras
clang-7: fatal error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by enh** [comment]
seems like a dupe of #184 which is fixed in r19?

**Comment by dibya001** [comment]
In #184, they have mentioned this additional flag as a workaround, that also seems to be not working.

**Comment by stephenhines** [comment]
Right, but you are still using r17 which doesn't use compiler-rt for your builtins. Please try r19, which should resolved this problem.

**Comment by dibya001** [comment]
I could give it a try. But Initially I was facing a few compilation issues due to complete removal of gcc. I can't  really upgrade NDK as of now in productions. 
Any possible workaround for this issue?
 And also Along with the -fsanitize=undefined flag if I pass in -fno-sanitize=signed-integer-overflow, will it resolve the issue?

**Comment by stephenhines** [comment]
Signed integer overflow is a common form of undefined behavior, so you would be decreasing the capabilities of UBSan to find issues with your code. I'll also note that the UBSan shipped in the NDK isn't compatible with GCC, so you really should move to a set of consistent tools. As another alternative, you can implement the missing function yourself (or get it from a properly licensed open source implementation). Then you would only need to link your new library with any binaries you create.

**Comment by dibya001** [comment]
You're correct though!! Will try and see if its feasible to upgrade to NDK 19.
