### ISSUE TITLE
[question] Recent spike in dlopen() 'permission denied' at runtime

### ISSUE THREAD

**Issue by emmanuel-marty** [android-ndk/ndk#979]
This may not be directly an issue with the NDK, but it is related to its build product, and I think you'd be the most expert person to ask.

With the latest update of my app, I've seen (in Crashlytics reports, sadly not in person) a spike in a very odd crash:

Fatal Exception: java.lang.UnsatisfiedLinkErrordlopen failed: couldn't map "/mnt/asec/com.dg.puzzlebrothers.mahjong.mysterymansion-2/split_config.arm64_v8a.apk!/lib/arm64-v8a/libnative-lib.so" segment 0: Permission denied

This occurs on recent Android builds (8.0, 8.1, 9.0) as well as slightly older (6.0.1, 7.0).

Sadly there is no SElinux info attached, basically just this. The app has been using bundles for a while, but this only happens on the latest update. This happens disproportionately on a small number of devices, but seems to happen systematically on the devices that are affected.

I found one identical report from an unrelated app that also uses a native lib, from 4 days ago:
https://github.com/algolia/algoliasearch-client-android/issues/576

I have one of the devices listed in the reports and was unable to reproduce the issue, even by installing the app from the store, presumably delivered as a split apk as seems to happen with the crash.

I haven't updated the NDK since january (still r19c). I was wondering if you have any idea of what might throw up what seems to be a SElinux violation on some devices, and seemingly  when the native lib is delivered through an app bundle-generated split apk

This might also be a server-side packaging issue when delivering the app bundle. Either way I'm not sure what to do, I am hoping you'll have an idea or run it up the flagpole

Thanks!

**Comment by enh** [comment]
so that error message comes from this code in the linker:
```
      void* seg_addr = mmap64(reinterpret_cast<void*>(seg_page_start),
                            file_length,
                            prot,
                            MAP_FIXED|MAP_PRIVATE,
                            fd_,
                            file_offset_ + file_page_start);
      if (seg_addr == MAP_FAILED) {
        DL_ERR("couldn't map \"%s\" segment %zd: %s", name_.c_str(), i, strerror(errno));
        return false;
      }
```

if you look at http://man7.org/linux/man-pages/man2/mmap.2.html you'll see that there are two causes of EPERM listed:
```
       EPERM  The prot argument asks for PROT_EXEC but the mapped area
              belongs to a file on a filesystem that was mounted no-exec.

       EPERM  The operation was prevented by a file seal; see fcntl(2).
```

the latter seems unlikely, because the system doesn't use seals to my knowledge, and you'd probably know if you were doing that yourself :-)

so it seems like you have some devices that are storing your apk on a file system mounted noexec. (the segment number in the error message might vary, but it should correspond with the first segment marked executable in your .so file if you check with `readelf -aW`.)

i'll try to find someone who knows something about split apks to see if they're aware of this, though my guess is that this is nothing to do with split apks specifically, but that when you weren't using split apks you were compressing and extracting your .so file rather than trying to use it directly from the .apk? (obviously the latter is preferable in theory, but if it doesn't work in practice... seems like there's at least a missing CTS test there.)

(i'll also try to find someone who knows something about `/mnt/asec`; i'm curious whether this `noexec` is inherent or a misconfiguration [and missing CTS test] on some subset of devices.)

**Comment by benvonhandorf** [comment]
I filed https://github.com/algolia/algoliasearch-client-android/issues/576.  Here is what I know so far:

This seems to occur much more often on LGE devices, far out of proportion with our install base... 73% of crashes are on LGE devices where it's less than 20% of our install.  For our app, we're seeing this occur almost exclusively on 8.X devices - 85% of crashes.  We saw this crash occur occasionally while we were using APK distribution without using App Signing, but the crash rate has spiked massively with going to App Bundle distribution and turning on App Signing, even after a point release to disable ABI splits.

**Comment by emmanuel-marty** [comment]
Thanks! It seems likely that the device is trying to load a .so library from a noexec filesystem. I don't do anything specific myself to load the native library (ie. I just use System.loadLibrary(), I don't even use ReLinker, although maybe I should..). 

I wonder why it spiked all of a sudden (I've been shipping this native lib as part of an app bundle for the last ~5 months and it only spiked in April), but it could be an OS update that contains the misconfiguration that got deployed on a bunch of devices, or a side effect of switching to targetting API level 28 in the app itself (although that was also done a couple months ago). An oversight/missed CTS test would be "good news" I guess and would make sense!

This seems to occur a lot on a small subset of devices, in particular Samsung (SM-J730F, SM-A320FL, SM-J530F, SM-G955F..) and LG.

Sorry this isn't directly NDK related (or only tangentially - failing to load the NDK build product on some devices) but I knew I would get an expert answer :-) Thanks for tracking down people who might know more about /mnt/asec and noexec as well

**Comment by enh** [comment]
seems like https://issuetracker.google.com/127691101 ? there are a couple of workarounds mentioned there (disallowing installation to sdcard, or using compression on your .so so that it has to be decompressed on the device which should leave it on a non-noexec file system).

**Comment by emmanuel-marty** [comment]
Thank you! I'll try using android.bundle.enableUncompressedNativeLibs=false in gradle.properties since that seems like the safest option.

**Comment by benvonhandorf** [comment]
Same, I should be able to get that into a release today and report back after the weekend on progress.

**Comment by benvonhandorf** [comment]
Sorry for the lag.

We added `android.bundle.enableUncompressedNativeLibs=false` to our gradle.properties and it appears to have resolved the issue for us.

**Comment by emmanuel-marty** [comment]
The crash disappeared in the update for us as well after applying android.bundle.enableUncompressedNativeLibs=false, and we have reports from users that previously experienced the issue on their devices, that confirm it is fixed. Thanks again for the pointer!
