### ISSUE TITLE
[BUG] Not all submodules being built

### ISSUE THREAD

**Issue by GRRedWings** [android-ndk/ndk#980]
I've been cross compiling python for Android across a number of NDK releases. It was originally done with GCC and NDK 10 I believe.  Slowly, I have converted it to build with clang, but when this happens not all of my python modules are built.
 
Here is my project and the clang branch https://github.com/GRRedWings/python3-android/tree/clang
 
I am trying to build against Python 3.5.1. With this, I have the project so that I can compile and get the Shared Library output, but in doing so a number of the modules that are part of the project are not created.  As an example, the _socket module is not created.   Nothing in the build output seems to indicate that anything failed though.
 
When I look at the output, I have the Shared Library that I would expect (libpython3.5m.so), and I have the Python folder with all of the required *.py files.  But when I look at the output lib-dynload folder, only a small subset of the *.so files are there.  And as soon as I try to run with this, I get that the socket module is missing.
 
I'm not sure if this is something in the makefile, if there is some sort of pre-build step that I am not doing correctly in order to have the makefile generated properly.  I've spent a great deal of time on this, and I'm wondering if it's possible that there is something in the NDK build chain that is not being done properly.
 
 
I'm learning on the fly about makefiles and cross compiling, but is there any way to know if the issue is with something I have done vs the NDK not doing something properly?  I don't understand how the modules to build are chosen, or how to troubleshoot these missing ones.

After talking with Dan & Elliott at their IO session, I'm hopeful that you might be able to give a little bit of insight.

#### Environment Details
I'm building this on an Unbutu 16.04 LTS
NDK_REV=19c
SDK_REV=25.2.4
ANDROID_API_LEVEL=22
ANDROID_PLATFORM=arm64
ANDROID_COMPILER=4.9

**Comment by DanAlbert** [comment]
I see:

```
configure:5255: checking whether the C compiler works
configure:5277: /usr/local/google/home/danalbert/src/python3-android/sdk/android-ndk-r19c/toolchains/llvm/prebuilt/linux-x86_64/bin/clang -fPIC -target armv7-none-linux-androideabi -gcc-toolchain /usr/local/google/home/danalbert/src/python3-android/sdk/android-ndk-r19c/toolchains/llvm/prebuilt/linux-x86_64 --sysroot=/usr/local/google/home/danalbert/src/python3-android/sdk/android-ndk-r19c/platforms/android-22/arch-arm/usr -isystem /usr/local/google/home/danalbert/src/python3-android/sdk/android-ndk-r19c/sysroot/usr/include -isystem /usr/local/google/home/danalbert/src/python3-android/sdk/android-ndk-r19c/sysroot/usr/include/arm-linux-androideabi -D__ANDROID_API__=22 -target armv7-none-linux-androideabi -gcc-toolchain /usr/local/google/home/danalbert/src/python3-android/sdk/android-ndk-r19c/toolchains/llvm/prebuilt/linux-x86_64 --sysroot=/usr/local/google/home/danalbert/src/python3-android/sdk/android-ndk-r19c/platforms/android-22/arch-arm/usr -fuse-ld=lld conftest.c  >&5
ld.lld: error: unable to find library -lunwind
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

I fixed those issues by removing most of the unnecessary flags (`--sysroot`, `-gcc-toolchain`, `-isysroot`, etc) and adding the missing API level to `-target` where necessary (it's probably the latter that fixed the issue). https://github.com/GRRedWings/python3-android/pull/6

As for the missing modules, debugging Python's module build is the worst. If you grep the log for "detect_modules", you'll find the section where the Python build scripts reported this and then flooded the screen with other output that made it unnoticable:

```
/usr/local/google/home/danalbert/src/python3-android/sdk/android-ndk-r19c/toolchains/llvm/prebuilt/linux-x86_64/bin/clang -fPIC -I. -IInclude -I./Include -target armv7-none-linux-androideabi22 -target armv7-none
-linux-androideabi22 -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -fPIC -Werror=declaration-after-statement -Ibuild/temp.linux-arm-3.5/libffi/inclu
de -Ibuild/temp.linux-arm-3.5/libffi -I/work/src/python3-android/src/Python-3.5.1/Modules/_ctypes/libffi/src -I./Include -I. -IInclude -I/usr/local/google/home/danalbert/src/python3-android/src/Python-3.5.1/Incl
ude -I/usr/local/google/home/danalbert/src/python3-android/src/Python-3.5.1 -c /work/src/python3-android/src/Python-3.5.1/Modules/_ctypes/libffi/src/arm/sysv.S -o build/temp.linux-arm-3.5/work/src/python3-androi
d/src/Python-3.5.1/Modules/_ctypes/libffi/src/arm/sysv.o -Wall -fexceptions
/work/src/python3-android/src/Python-3.5.1/Modules/_ctypes/libffi/src/arm/sysv.S:363:2: error: invalid instruction, did you mean: fldmiax?
 fldmiadgt ip, {d0-d7}
 ^
/work/src/python3-android/src/Python-3.5.1/Modules/_ctypes/libffi/src/arm/sysv.S:399:2: error: invalid instruction
 stmeqia r2, {r0, r1}
 ^
/work/src/python3-android/src/Python-3.5.1/Modules/_ctypes/libffi/src/arm/sysv.S:412:2: error: invalid instruction, did you mean: fstmiax?
 fstmiadeq r2, {d0-d3}
 ^
/tmp/sysv-f3897a.s:263:2: error: invalid instruction
 fstmfdd sp!, {d0-d7}
 ^
/tmp/sysv-f3897a.s:313:2: error: invalid instruction, did you mean: fldmiax?
 fldmiad sp, {d0-d1}
 ^
/tmp/sysv-f3897a.s:316:2: error: invalid instruction, did you mean: fldmiax?
 fldmiad sp, {d0-d3}
 ^

Python build finished successfully!
The necessary bits to build these optional modules were not found:
_bz2                  _curses               _curses_panel      
_dbm                  _gdbm                 _lzma              
_sqlite3              _ssl                  _tkinter           
nis                   readline              spwd               
zlib                                                           
To find the necessary bits, look in setup.py in detect_modules() for the module's name.


Failed to build these modules:
_ctypes
```

`_ctypes` actually failed to build and you can see that it's probably a matter of adding `-fno-integrated-as` in the right place.

The others are really annoying to debug, and the best approach I've found it to sprinkle prints throughout `detect_modules()` in `$PYTHON/setup.py` and keep building until I figure out why a module was rejected.

I wouldn't be surprised if some of those missing modules are actually compatibility issues that we could work on. If you find that to be the case, let us know. If you find multiple compatibility issues, please file separate bugs for each.

**Comment by GRRedWings** [comment]
Dan,

Thanks for spending the time on this, it's greatly appreciated.  I will
look into the suggestions that you offered and work through them. Hopefully
working through them I can clean things up and find any compatibility
issues as you suggest.  I'll be sure to keep them separate as you
recommended.

Brian

**Comment by GRRedWings** [comment]
Trying to understand how you know that I need to add -fno-integrated-as.  Not being familiar enough with this flag, it appears that the .configure call fails when I add this flag to CC.  

checking for --enable-universalsdk... no
checking for --with-universal-archs... no
checking MACHDEP... linux
checking for --without-gcc... no
checking for arm-linux-androideabi-gcc... /disk1/python3-android-albert/sdk/android-ndk-r19c/toolchains/llvm/prebuilt/linux-x86_64/bin/clang -fno-integrated-as
checking whether the C compiler works... no
configure: error: in `/disk1/python3-android-albert/src/Python-3.5.1':
configure: error: C compiler cannot create executables





I can see from the output that ssl has this flag enabled.  but the .configure and such is still a bit of black magic to me.

**Comment by DanAlbert** [comment]
I guessed `-fno-integrated-as` because of the lines like this:

```
/tmp/sysv-f3897a.s:316:2: error: invalid instruction, did you mean: fldmiax?
 fldmiad sp, {d0-d3}
```

Which appears to be the assembler complaining about the wrong variant of the instruction (http://infocenter.arm.com/help/index.jsp?topic=/com.arm.doc.dui0068b/Bcfchhif.html).

Actually, when I Googled the instruction to confirm that, one of the first results was https://github.com/kivy/python-for-android/issues/1525, which says that updating the libffi used by Python fixes it.

**Comment by GRRedWings** [comment]
Thank you for the info.  I realize how little I know about cross compile and this process.  In looking at this up to now I've realized that the newer versions of Python have done a good job at adding Android specific build parameters, and I might try to build with the latest released version of Python.  Between that and kivy I should hopefully be able to piece together everything.

I do appreciate the links as well. I had seen the kivy one, I just didn't understand the error enough to know that fldmiax and such were assembler errors.

**Comment by DanAlbert** [comment]
Closing as it looks like these probably aren't NDK issues. LMK if you find anything we can improve and we'll reopen.
