### ISSUE TITLE
[question] libm prevents libunwind.a for arm from being linked?

### ISSUE THREAD

**Issue by tomty89** [android-ndk/ndk#981]
So we have been observing weird issue(s) on arm that is apparently `libunwind.a` related when building program(s), e.g. `gmic`, with NDK r19b.

After some tests I found that seemingly `libunwind.a` is omitted / ignored during linking, *if* `-lunwind` is placed after `-lm` (which is the current default behaviour, as `-lunwind` is now linked via the "fake" `libgcc.a` linker script, while `-lm` is pulled in by "CXX" and hence placed right after `-lc++` and before `-lgcc`).

On the other hand, I realized that the current `libc++_shared.so` does not have linkage to `libm.so` anymore (while my `/system/lib/libc++.so` does, if that's relevant).

So is this a bug of the `libunwind.a`? Or maybe the NDK toolchain? Or have we been doing something wrong?

Also, is the `-lm` still necessary with current `libc++_shared.so`?

Ref.: https://github.com/llvm-mirror/clang/blob/release_80/lib/Driver/ToolChains/Gnu.cpp#L475-L487

**Comment by DanAlbert** [comment]
From your description I don't know what the question is. Is what a bug? What's the failure that you're seeing? How are you building that's getting you into this situation?

**Comment by tomty89** [comment]
Well, that the order of the link flags could lead to a broken product. For instance:
```
$ echo 'int main() { return 0; }' > test.cpp
$ clang test.cpp -lGraphicsMagick++ -lc++_shared
$ readelf -Ws a.out | grep Unwind | head
     5: 00000000     0 FUNC    GLOBAL DEFAULT  UND __gnu_Unwind_Find_exidx@LIBC_N (3)
    18: 00000eb9   336 FUNC    GLOBAL DEFAULT   12 _Unwind_VRS_Pop
    19: 00001209     2 FUNC    GLOBAL DEFAULT   12 _Unwind_Complete
    20: 000012dd    12 FUNC    GLOBAL DEFAULT   12 _Unwind_DeleteException
    23: 00000d61   172 FUNC    GLOBAL DEFAULT   12 _Unwind_VRS_Get
    24: 00000e0d   172 FUNC    GLOBAL DEFAULT   12 _Unwind_VRS_Set
    25: 00001275    52 FUNC    GLOBAL DEFAULT   12 _Unwind_GetLanguageSpecificData
    30: 00001051   160 FUNC    GLOBAL DEFAULT   12 _Unwind_RaiseException
    31: 0000120d   104 FUNC    GLOBAL DEFAULT   12 _Unwind_Resume
    32: 000012a9    52 FUNC    GLOBAL DEFAULT   12 _Unwind_GetRegionStart
$ clang test.cpp -lGraphicsMagick++ -lc++_shared -lm
$ readelf -Ws a.out | grep Unwind | head
$
```

**Comment by tomty89** [comment]
Never mind, it's a dup of the libgcc/libunwind issues. I have it figured out.
