### ISSUE TITLE
[FR] support for controlling ninja parallelism from cmake

### ISSUE THREAD

**Issue by bio007** [android-ndk/ndk#983]
We are using cmake + ninja setup to build our android c++ library. It's quite big lib with 1000+ cpp files.

Ninja by default runs as many parallel jobs as many cores your cpu has. With so many files to compile this renders our PCs quite unresponsive for considerable amount of time. I would like to be able to limit no of build processes for ninja so we can have maybe slightly slower builds but responsive computers able to browse some code review or anything else.

Ninja by itself supports this behavior with `-j` argument (just like original ndkBuild did) but I can't find a way how to tell cmake to set it to ninja.

This is my question on stackoverflow for a reference:
https://stackoverflow.com/questions/51557585/limit-cpu-cores-for-ndkbuild-with-cmake-and-ninja

Am I missing something or it's just not there yet? :)

**Comment by DanAlbert** [comment]
@jomof is this doable today, or is this a FR? I couldn't find anything.

**Comment by bio007** [comment]
Hello, any news here?

**Comment by DanAlbert** [comment]
I'd searched around the gradle code base for a while back when this was originally filed and didn't find anything. Given that and the lack of response, I think this is probably not currently possible. Could you file a bug against Studio C++ by following https://source.android.com/setup/contribute/report-bugs? Post the link to the bug back here and I'll make sure it gets triaged ASAP.

**Comment by bio007** [comment]
thanks @DanAlbert
issue created: https://issuetracker.google.com/issues/137878831

**Comment by cdsousa** [comment]
I found a workaround: https://stackoverflow.com/a/59174124/1062531
