### ISSUE TITLE
[question] Any plan for aosp_walleye_hwasan-userdebug

### ISSUE THREAD

**Issue by simpleton** [android-ndk/ndk#984]
Thanks Dan & Elliott, gave us a great presentation on What's New in Android C++ Development in Google IO.

I'm curious is there any plan to open source `walleye_hwasan-userdebug`. I do see the documents mentioned this target,[using-hwasan](https://source.android.com/devices/tech/debug/asan#using-hwasan). But I can't find it in current AOSP master.

**Comment by DanAlbert** [comment]
@eugenis updated those docs to point to the non-hwasan walleye target. Does that work?

**Comment by enh** [comment]
to be clear: the "hwasan" target is just a target with less stuff in it, so that the system image still fits on the device even when you're building with hwasan. it's the `SANITIZE_TARGET=hwaddress` bit that makes a build have hwasan or not.
