### ISSUE TITLE
Unable to use crypt [BUG]

### ISSUE THREAD

**Issue by GRRedWings** [android-ndk/ndk#987]
In trying to build this project branch
https://github.com/GRRedWings/python3-android/tree/clang

I am unable to build the crypt module because it is missing the crypt function

4 warnings and 4 errors generated.
building '_crypt' extension
/disk1/python3-android-clang/python3-android/sdk/android-ndk-r19c/toolchains/llvm/prebuilt/linux-x86_64/bin/clang -I. -I./Include -target aarch64-none-linux-androideabi22 -target aarch64-none-linux-androideabi22 -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -fPIC -std=c99 -Wextra -Wno-unused-result -Wno-unused-parameter -Wno-missing-field-initializers -Wstrict-prototypes -Werror=implicit-function-declaration -I./Include -I. -I/disk1/python3-android-clang/python3-android/src/Python-3.7.3/Include -I/disk1/python3-android-clang/python3-android/src/Python-3.7.3 -c /disk1/python3-android-clang/python3-android/src/Python-3.7.3/Modules/_cryptmodule.c -o build/temp.linux-aarch64-3.7/disk1/python3-android-clang/python3-android/src/Python-3.7.3/Modules/_cryptmodule.o
/disk1/python3-android-clang/python3-android/src/Python-

3.7.3/Modules/_cryptmodule.c:43:20: error: implicit declaration of function 'crypt' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
    crypt_result = crypt(word, salt);

**Comment by enh** [comment]
Android doesn't include crypt(). if you need it, your best bet is probably to take an open source implementation such as https://github.com/freebsd/freebsd/tree/master/lib/libcrypt and include it in your project.
