### ISSUE TITLE
fatal error: 'machine/asm.h' file not found

### ISSUE THREAD

**Issue by CyborgRahil** [android-ndk/ndk#989]
After upgrading NDK from  **android-ndk-r11c** to **android-ndk-r19c** found fatal error: 'machine/asm.h' file not found during compilation.

**Comment by enh** [comment]
yeah, that internal implementation detail was removed. strictly, it was moved into the private bionic/libc/private/bionic_asm.h in the OS that isn't part of the NDK. but there was so little in it, and what was in it was only used by that non-NDK header anyway, that i assume you can just remove the `#include` and everything's fine?

here's the complete content of the arm32 file, for example:
```
#define __bionic_asm_align 0

#undef __bionic_asm_custom_entry
#undef __bionic_asm_custom_end
#define __bionic_asm_custom_entry(f) .fnstart
#define __bionic_asm_custom_end(f) .fnend

#undef __bionic_asm_function_type
#define __bionic_asm_function_type #34 
```

presumably you have no need for that?
