### ISSUE TITLE
ndk-depends prebuilt for Windows 64-bit depends on libstdc++-6.dll, not included in NDK

### ISSUE THREAD

**Issue by jubajube** [android-ndk/ndk#99]
Upgrading from r10e to r11c, I noticed that I can no longer run ndk-depends because it depends itself upon libstdc++-6.dll (from mingw64?) which I didn't have.
![ndk-depends-libstdc-dependency-missing](https://cloud.githubusercontent.com/assets/6889558/15377522/23b7710c-1d11-11e6-9358-5cd971be24a2.png)

Either the NDK should include libstdc++-6.dll or it should be clearly documented that the NDK depends on the user installing mingw64 separately.

**Comment by DanAlbert** [comment]
I think we use a static libstdc++ for all the platform tools (adb, fastboot, etc). I'll look into doing that for `ndk-depends`.

**Comment by jubajube** [comment]
Thank you for the quick response!

**Comment by jmgao** [comment]
Makefile fix at https://android-review.googlesource.com/#/c/231616/
I think this should be able to make it in for r12.
