### ISSUE TITLE
[BUG] SIGSEGV when output to std::cerr in global object constructor

### ISSUE THREAD

**Issue by dstoyanovsky** [android-ndk/ndk#990]
--------------------------------------------------------------------------------

#### Description

Initially issue was encountered in a project which uses Tensorflow. Example below reproduces logic of CPUFeatureGuard class of Tensorflow (native library has global object, constructor of which prints log messages to Android log and std::cerr):

```
#include <jni.h>
#include <string>

#include <iostream>
#include <sstream>
#include <android/log.h>

class OutputClass {
public:
    OutputClass() {
        std::stringstream hello;
        hello << "Hello from Test Output";
        __android_log_write(ANDROID_LOG_INFO, "native", hello.str().c_str());
        std::cerr << "native:" << hello.str() << std::endl; // <- Point of SIGSEGV
    }
};

OutputClass output;

extern "C" JNIEXPORT jstring JNICALL
Java_com_example_myapplication_MainActivity_stringFromJNI(
        JNIEnv *env,
        jobject /* this */) {
    std::stringstream hello;
    hello << "Hello from C++";
    __android_log_write(ANDROID_LOG_INFO, "native", hello.str().c_str());
    std::cerr << "native:" << hello.str() << std::endl;
    return env->NewStringUTF(hello.str().c_str());
}
```

NOTE: If global object definition is commented out, then output to std::cerr in JNI call does not cause the issue.

#### Steps

Complete example can be created via Android studio as a standard new project template (Phone and Tablet -> Native C++). Just replace code in the native-lib.cpp by snippet above.

- Select debug-x86_64 as a target Build variant
- Add new (or use existing) virtual device based on x86_64 image of Android 9
- Debug application (execution stops at line 262 of ~/Library/Android/sdk/ndk-bundle/toolchains/llvm/prebuilt/darwin-x86_64/sysroot/usr/include/c++/v1/ostream)

#### Environment Details

NDK: 19.2.5345600 (True for 20.0.5471254 rc3 also)
Build system: CMake
OS: MacOS 10.14.3
ABI: x86_64 (x86)
Android Studio: 3.4.1
Target Platform: Android Emulator x86_64 (x86)
NDK API level: 21+
Device API level: 28 (Android 9)

**Comment by DanAlbert** [comment]
I assume you're using a static libc++? This is undefined behavior in that case because the ordering of static initialization is not specified, so `std::cerr` is not guaranteed to have been constructed yet.

I think if you're using a shared standard library it works, but I don't know if that's specified or just something that happens to work.

**Comment by dstoyanovsky** [comment]
Thank you for your comment. Yes, you are right a static libc++ is used and SIGSEGV caused by undefined behaviour. Considering that, the right decision is patching of Tensorflow, to prevent output to `std::cerr` in CPUFeatureGuard class of Tensorflow for Android.
