### ISSUE TITLE
[BUG] Size increase on usage of LibC++

### ISSUE THREAD

**Issue by bhupeshpant19jan** [android-ndk/ndk#991]
#### Observing an increase in Size after migrating to LibC++.

Hi, 

I am observing an overall **8-10 % Increase** in size after migrating to LibC++ from gnustl. Few additional dependencies that we have added that could account for the size is,
* Statically linking additional libunwind.a from libc++ in each so.
* Overriding typeInfo class, especially due to the difference in the behavior of checking typeInfo == operator.
 But even after these two changes, I don't understand what has accounted for overall size increase.

I initially suspected somehow introduction of LibC++ is disabling the debug symbols stripping but that's also not true, I have verified by explicitly disabling the **  -Wl,--gc-sections \ ** & **-ffunction-sections -fdata-sections** , which further increases the size of the generated SO and APKs.

Are there any known issue or side effects of increasing size when using LibC++?

Regards,
Bhupesh

#### Environment Details

Not all of these will be relevant to every bug, but please provide as much
information as you can.

* NDK Version: r16
* Build system: Clang
* Host OS: Windows
* NDK API level: 23

**Comment by bhupeshpant19jan** [comment]
Hi team,

Any updates on this?

Regards,
Bhupesh

**Comment by DanAlbert** [comment]
You can try https://github.com/google/bloaty, but there's really no information here for us to go on.

**Comment by bhupeshpant19jan** [comment]
Bloaty is not yet supported for Android APKs.

**Comment by DanAlbert** [comment]
Run it on the shared libraries in the APK.
