### ISSUE TITLE
[question] Why the generated .so file contains the full path name for referred third party shared library?

### ISSUE THREAD

**Issue by valwang** [android-ndk/ndk#993]
Please include any context relevant to your question (NDK version, ABI, etc).

I am compiling one Android Studio project with native C++ support which will import third party shared libraries. The used NDK version is android-ndk-r18b. The target ABI is arm64-v8a.

I created my Android.mk file as below:

+++++++++++++++++++++++++++++++++
LOCAL_PATH := $(call my-dir)
SRC_PATH := $(LOCAL_PATH)/../

include $(CLEAR_VARS)
LOCAL_MODULE := tensorflowlite_gpu_gl
LOCAL_SRC_FILES := $(LOCAL_PATH)/lib/libtensorflowlite_gpu_gl.so
include $(PREBUILT_SHARED_LIBRARY)

include $(CLEAR_VARS)
LOCAL_MODULE := tensorflowlite
LOCAL_SRC_FILES := $(LOCAL_PATH)/lib/libtensorflowlite.so
include $(PREBUILT_SHARED_LIBRARY)

include $(CLEAR_VARS)
LOCAL_MODULE    := libtestmodel
LOCAL_SRC_FILES := TestModel.cpp TestModelJni.cpp
LOCAL_LDLIBS    += -landroid -ldl -Wall -llog
LOCAL_SHARED_LIBRARIES += tensorflowlite_gpu_gl
LOCAL_SHARED_LIBRARIES += tensorflowlite
include $(BUILD_SHARED_LIBRARY)
++++++++++++++++++++++++++++++++++

All compilation and link works, and libtestmodel.so is generated at 
~/project/TestModel/TestModel/app/build/intermediates/ndkBuild/debug/obj/local/arm64-v8a.
But when I use readelf to check the dynamic section, I get following information:

++++++++++++++++++++++++++++++++++
readelf -d libtestmodel.so | more

Dynamic section at offset 0x148e8 contains 33 entries:
  Tag        Type                         Name/Value
 0x0000000000000001 (NEEDED)             Shared library: [/home/valwang/project/
TestModel/TestModel/app/build/intermediates/ndkBuild/debug/obj/local/arm64-v8a/l
ibtensorflowlite_gpu_gl.so]
 0x0000000000000001 (NEEDED)             Shared library: [libtensorflowlite.so]
 0x0000000000000001 (NEEDED)             Shared library: [libc++_shared.so]
 0x0000000000000001 (NEEDED)             Shared library: [libandroid.so]
 0x0000000000000001 (NEEDED)             Shared library: [libdl.so]
 0x0000000000000001 (NEEDED)             Shared library: [liblog.so]
 0x0000000000000001 (NEEDED)             Shared library: [libc.so]
 0x0000000000000001 (NEEDED)             Shared library: [libm.so]
 0x0000000000000001 (NEEDED)             Shared library: [libstdc++.so]
 0x000000000000000e (SONAME)             Library soname: [libtestmodel.so]
+++++++++++++++++++++++++++++++++++

It is quite strange that for libtensorflowlite_gpu_gl.so, it is using the local full path name. It caused the generated apk running failure on device, error happens during loading the library libtestmodel.so.

My question is why the generated .so using the full path name for the referred third party .so? How to solve this problem? Thanks!

**Comment by alexcohn** [comment]
see https://github.com/android-ndk/ndk/issues/177

**Comment by valwang** [comment]
Thanks, by regenerating the .so file with defined soname, the problem solved!
