### ISSUE TITLE
[DOC] Possible Typo in README regarding standalone toolchain

### ISSUE THREAD

**Issue by oxr463** [android-ndk/ndk#994]
**Note:** The NDK docs reside under https://developer.android.com/ndk/. If the bug you are reporting belongs to a different section of the site, this is the wrong bug tracker. See http://b.android.com.

**URL**
URL to the incorrect documentation (if the problem is that there is no documentation and it belongs on a new page, say so).

https://android.googlesource.com/platform/ndk/+/master/README.md

**Problem**
What's wrong? Does something need clarification/expansion? Is there a typo?

Under __Build Systems__, it says,

> As of NDK r19 it is necessary, as the installed toolchain may be invoked directly, but it remains for compatibility.

Should it rather say, "... it is unnecessary ...", instead?

**Comment by DanAlbert** [comment]
Good catch :+1: https://android-review.googlesource.com/c/platform/ndk/+/975177
